Repository status-im/status-mobile, pull requests merged in 2018-11, with the labels that each got.

#5784 Force node restart during initialization on desktop
  src/status_im/node/core.cljs
Labels: Tested - OK, desktop

#6467 [#6415] mark button as inactive when no internet or mailserver connec…
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK, chat, desktop, mobile

#6302 Typo in "new message" notification fixed
  translations/en.json
Labels: skip-manual-qa

#6566 Dont use github archive for desktop status-go version
  modules/react-native-status/desktop/CMakeLists.txt
Labels: Tested - OK

#6591 [TESTS/FIX] Refreshed saucelabs image templates
  test/appium/views/elements_templates/sauce_logo.png
  test/appium/views/elements_templates/sauce_logo_red.png
  test/appium/views/elements_templates/saucelabs_sauce.png
Labels: skip-manual-qa, tests

#6592 [TESTS/FIX] Changed a way to toggle airplane mode
  test/appium/tests/atomic/chats/test_one_to_one.py
Labels: skip-manual-qa, tests

#6532 Add system messages to group chats
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/constants.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/subs.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  test/cljs/status_im/test/chat/models/loading.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/chat/subs.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  translations/en.json
Labels: Tested - OK

#6611 Updated Kudos address to reflect latest contract
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#6612 [TESTS/FIX] Need help section in Profile test
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#6610 Fixed some extensions issues (smallish)
  src/status_im/chat/commands/core.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
  src/status_im/models/wallet.cljs
Labels: skip-manual-qa

#6554 Introduced Inter UI font and made some cleanup
  android/app/src/main/assets/fonts/Inter-UI-Bold.otf
  android/app/src/main/assets/fonts/Inter-UI-Medium.otf
  android/app/src/main/assets/fonts/Inter-UI-Regular.otf
  components/src/status_im/ui/components/react.cljs
  desktop_files/package.json
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/Info.plist
  ios/fonts/Inter-UI-Bold.otf
  ios/fonts/Inter-UI-Medium.otf
  ios/fonts/Inter-UI-Regular.otf
  resources/fonts/Inter-UI-Bold.otf
  resources/fonts/Inter-UI-Medium.otf
  resources/fonts/Inter-UI-Regular.otf
  resources/fonts/SF-Pro-Text-Light.otf
  resources/fonts/SF-Pro-Text-Medium.otf
  resources/fonts/SF-Pro-Text-Regular.otf
  scripts/build-desktop.sh
  src/status_im/android/platform.cljs
  src/status_im/desktop/platform.cljs
  src/status_im/ios/platform.cljs
  src/status_im/ui/screens/chat/input/utils.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/views.cljs
  src/status_im/utils/platform.cljs
Labels: Tested - OK

#6370 [#2884] added name lookup for recipient after qr code scanning
  src/status_im/contact/subs.cljs
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/utils/contacts.cljs
  src/status_im/utils/ethereum/core.cljs
Labels: Tested - OK, bounty

#6560 bug #5899 - restored missing transaction error messages
  src/status_im/models/wallet.cljs
Labels: Tested - OK

#6372 Plug-in new text parsing engine
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_content.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  test/cljs/status_im/test/chat/models/message_content.cljs
  test/cljs/status_im/test/chat/views/message.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK, feature, tech-debt

#6623 Improve ubuntu-server and RCTStatus logging
  desktop/main.cpp
  modules/react-native-desktop-linking/desktop/desktoplinking.cpp
  modules/react-native-desktop-linking/desktop/desktoplinking.h
  modules/react-native-desktop-notification/desktop/desktopnotification.cpp
  modules/react-native-desktop-notification/desktop/desktopnotification.h
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
Labels: Tested - OK, desktop

#6362 Synchronize your own messages in 1-to-1
  .env
  .env.jenkins
  .env.nightly
  Makefile
  STATUS_GO_VERSION
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/CMakeLists.txt
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/chat/commands/sending.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/installations.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/installation.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/pairing/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/impl/send.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/pairing.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/transport/message/transit.cljs
  src/status_im/ui/screens/pairing/styles.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/pairing/core.cljs
  translations/en.json
Labels: Tested - OK, chat

#6626 Increase build timeout as it is failing intermittently now
  ci/Jenkinsfile.combined
Labels: skip-manual-qa

#6630 Fix request ETH in simple dapp
  test/appium/views/web_views/status_test_dapp.py
Labels: tests

#6146 Unread messages indicator
  modules/react-native-desktop-notification/desktop/desktopnotification.cpp
  modules/react-native-desktop-notification/desktop/desktopnotification.h
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/init/core.cljs
  test/cljs/status_im/test/chat/models.cljs
Labels: Tested - OK, desktop

#6632 [TESTS] Can complete txn to dapp after onboarding called from dapp is completed
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/users.py
  test/appium/views/send_transaction_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#6373 [fix #3913] do not logout when changing mailserver
  resources/icons/mailserver.svg
  src/status_im/accounts/db.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/mailservers.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/mailserver_topic.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/migrations.cljs
  src/status_im/data_store/transport.cljs
  src/status_im/events.cljs
  src/status_im/fleet/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/db.cljs
  src/status_im/mailserver/subs.cljs
  src/status_im/network/core.cljs
  src/status_im/protocol/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/chat/core.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/filters.cljs
  src/status_im/transport/inbox.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/extensions/styles.cljs
  src/status_im/ui/screens/extensions/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/db.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/subs.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/styles.cljs
  src/status_im/ui/screens/offline_messaging_settings/subs.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/status_im/ui/screens/subs.cljs
  test/cljs/status_im/test/mailserver/core.cljs
  test/cljs/status_im/test/protocol/web3/inbox.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/core.cljs
  test/cljs/status_im/test/transport/inbox.cljs
  translations/el.json
  translations/en.json
  translations/es_419.json
  translations/fa.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ms.json
  translations/pl.json
  translations/ru.json
  translations/uk.json
  translations/zh_Hans_CN.json
Labels: Tested - OK, desktop, mobile-app

#6627 Fixed CK
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/utils/browser_config.edn
Labels: Tested - OK

#6636 [TESTS] Fixed onboarding from DApp and openning links tests
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
Labels: skip-manual-qa, tests

#6617 [#6294] add desktop alpha release warning
  desktop_files/package-lock.json
  desktop_files/package.json
  src/status_im/accounts/core.cljs
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/db.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/migrations.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  translations/en.json
Labels: Tested - OK, desktop

#6431 [ios only] prevent logging of password in nightly builds
  src/status_im/accounts/db.cljs
  src/status_im/accounts/login/core.cljs
  src/status_im/accounts/recover/core.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/handlers.cljs
  src/status_im/utils/keychain/core.cljs
  src/status_im/utils/security.cljs
Labels: Tested - OK

#6620 [#6169] Display .eth or other domain rather than IPFS redirect
  src/status_im/browser/core.cljs
  src/status_im/browser/db.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/browser/subs.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/utils/ethereum/ens.cljs
Labels: Tested - OK

#6512 [fix 6508] user own picture should be unclickable in chats
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, chat, medium-priority

#6647 [6628] don't block message sending when mailserver disconnected
  src/status_im/mailserver/subs.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: 1-offline-inboxing, Tested - OK

#6661 Improved extensions error handling. Various fixes.
  deps.edn
  project.clj
  src/status_im/chat/commands/core.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/extensions/add/events.cljs
  src/status_im/ui/screens/extensions/add/views.cljs
Labels: skip-manual-qa

#6668 [Fixes #6665] Wrap view child elements when needed
  src/status_im/extensions/core.cljs
Labels: skip-manual-qa

#6667 Added some new DApps
  resources/images/contacts/blockimmo.png
  resources/images/contacts/cryptographics.png
  resources/images/contacts/cryptotakeovers.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/browser/default_dapps.cljs
Labels: browser

#6653 Add automated tests according to #6649
  test/appium/tests/atomic/account_management/test_wallet_modal.py
  test/appium/views/transactions_view.py
Labels: tests

#6670 Open chat for ens names
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#6677 [fix] error when switching chats
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: high-priority, high-severity, skip-manual-qa

#6625 Add ST to assets list
  resources/images/tokens/mainnet/ST.png
  resources/images/tokens/mainnet/ST@2x.png
  resources/images/tokens/mainnet/ST@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK, wallet

#6582 fix to #5699 : 'Reset to default' from transaction fee screen resets gas limit to 21000 always sending tx from Dapp
  src/status_im/models/wallet.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/db.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#6695 Fix RN dependency before Windows PR is merged
  desktop_files/package-lock.json
  desktop_files/package.json
Labels: desktop

#6702 Adding SNT voting DApp
  resources/images/contacts/snt-voting.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/browser/default_dapps.cljs
Labels: skip-manual-qa

#6719 [TESTS] Fixed chat element locator
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#6690 [TESTS] Check fiat value is correct for token transactions
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/users.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#6325 Show debug information when LES is selected (in the titlebar).
  resources/config/fleets-les.json
  src/status_im/events.cljs
  src/status_im/network/core.cljs
  src/status_im/node/core.cljs
  src/status_im/protocol/core.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/subs.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/web3/core.cljs
  src/status_im/web3/events.cljs
Labels: Tested - OK

#6729 Fix QTROOT for clang64-based Qt
  desktop/CMakeModules/QtConfiguration.cmake
Labels: desktop, skip-manual-qa

#6732 [TESTS] Fixed transactions history test
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/users.py
  test/appium/views/transactions_view.py
Labels: skip-manual-qa, tests

#5937 Add Fastlane action to upload Google Play metadata
  fastlane/Fastfile
Labels: skip-manual-qa

#6706 [#5749] transaction history fixes
  src/status_im/accounts/logout/core.cljs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/init/core.cljs
  src/status_im/models/transactions.cljs
  src/status_im/ui/screens/wallet/db.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/transactions/subs.cljs
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/ethereum/tokens.cljs
  src/status_im/utils/transactions.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/ethereum/eip681.cljs
  test/cljs/status_im/test/wallet/transactions.cljs
Labels: Tested - OK

#6742 Feature/update links
  .github/CONTRIBUTING.md
  Makefile
  README.md
  scripts/lib/setup/platform.sh
  src/status_im/ui/screens/help_center/views.cljs
Labels: Tested - OK, release

#6712 [TESTS] testrail report and runner for desktop e2e tests
  test/desktop.sikuli/pytest.ini
  test/desktop.sikuli/start_here.py
  test/desktop.sikuli/tests/account_management/__init__.py
  test/desktop.sikuli/tests/base_test_case.py
  test/desktop.sikuli/tests/conftest.py
  test/desktop.sikuli/tests/report.py
  test/desktop.sikuli/views/images/sign_in_view/create_new_account.png
  test/desktop_sikuli/Dockerfile
  test/desktop_sikuli/Jenkinsfile
  test/desktop_sikuli/main.py
  test/desktop_sikuli/pytest.ini
  test/desktop_sikuli/requirements.txt
  test/desktop_sikuli/start.sh
  test/desktop_sikuli/tests/__init__.py
  test/desktop_sikuli/tests/base_test_case.py
  test/desktop_sikuli/tests/conftest.py
  test/desktop_sikuli/tests/report.py
  test/desktop_sikuli/tests/test_chats.py
  test/desktop_sikuli/tests/test_create_account.py
  test/desktop_sikuli/tests/test_privacy_policy.py
  test/desktop_sikuli/tests/test_profile.py
  test/desktop_sikuli/tests/test_recover_access.py
  test/desktop_sikuli/views/__init__.py
  test/desktop_sikuli/views/base_element.py
  test/desktop_sikuli/views/base_view.py
  test/desktop_sikuli/views/home_view.py
  test/desktop_sikuli/views/images/base_view/back_button.png
  test/desktop_sikuli/views/images/base_view/home_button.png
  test/desktop_sikuli/views/images/base_view/profile_button.png
  test/desktop_sikuli/views/images/home_view/contact_code_input.png
  test/desktop_sikuli/views/images/home_view/plus_button.png
  test/desktop_sikuli/views/images/home_view/start_chat_button.png
  test/desktop_sikuli/views/images/profile_view/copy_code_button.png
  test/desktop_sikuli/views/images/profile_view/log_out_button.png
  test/desktop_sikuli/views/images/profile_view/share_my_code_button.png
  test/desktop_sikuli/views/images/sign_in_view/confirm_password_input.png
  test/desktop_sikuli/views/images/sign_in_view/create_account.png
  test/desktop_sikuli/views/images/sign_in_view/create_new_account.png
  test/desktop_sikuli/views/images/sign_in_view/create_password_input.png
  test/desktop_sikuli/views/images/sign_in_view/i_have_account.png
  test/desktop_sikuli/views/images/sign_in_view/next_button.png
  test/desktop_sikuli/views/images/sign_in_view/other_accounts.png
  test/desktop_sikuli/views/images/sign_in_view/password_input.png
  test/desktop_sikuli/views/images/sign_in_view/privacy_policy_button.png
  test/desktop_sikuli/views/images/sign_in_view/recover_password_input.png
  test/desktop_sikuli/views/images/sign_in_view/recovery_phrase_input.png
  test/desktop_sikuli/views/images/sign_in_view/sign_in_button.png
  test/desktop_sikuli/views/images/sign_in_view/username_input.png
  test/desktop_sikuli/views/profile_view.py
  test/desktop_sikuli/views/sign_in_view.py
Labels: skip-manual-qa, tests

#6721 Show chat name, source contact and time in PN body
  modules/react-native-desktop-notification/desktop/desktopnotification.cpp
  modules/react-native-desktop-notification/desktop/desktopnotification.h
  src/status_im/chat/models/message.cljs
Labels: Tested - OK, desktop

#6753 updating cljs compiler
  deps.edn
  project.clj
  src/status_im/data_store/realm/core.cljs
  src/status_im/models/wallet.cljs
  src/status_im/ui/components/list_selection.cljs
  src/status_im/ui/screens/group/db.cljs
  src/status_im/ui/screens/hardwallet/components.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/utils/clocks.cljs
  src/status_im/utils/ethereum/mnemonic.cljs
Labels: developer-xp, skip-manual-qa

#6756 [fix] resurrect cljs-react-navigation
  deps.edn
Labels: skip-manual-qa

#6755 Recovery view: added accessibility labels for passphrase and password input fields
  src/status_im/ui/screens/accounts/recover/views.cljs
Labels: skip-manual-qa

#6754 [fix] align min chat input container height with tab menu
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
Labels: Tested - OK, chat, desktop

#6769 [refactor] move chat.subs fns to chat.db
  src/status_im/chat/db.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  test/cljs/status_im/test/chat/db.cljs
  test/cljs/status_im/test/runner.cljs
Labels: skip-manual-qa

#6770 introduce priority map
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/utils/priority_map.cljs
Labels: skip-manual-qa

#6692 [TESTS] Dockerize appium and track battery and network consumption on real devices
  test/appium/docker/Dockerfile
  test/appium/docker/HOWTO.md
  test/appium/docker/entry_point.sh
  test/appium/requirements.txt
  test/appium/support/appium_container.py
  test/appium/support/device_stats_db.py
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/marks.py
Labels: tests

#6771 [refactor] move contact.subs and utils.contacts to contact.db
  src/status_im/chat/models/message.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/contact/subs.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/utils/contacts.cljs
  test/cljs/status_im/test/contacts/db.cljs
  test/cljs/status_im/test/runner.cljs
Labels: skip-manual-qa

#6773 [TESTS] Skip tests in order not to false fail in PRs
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
Labels: skip-manual-qa, tests

#6776 [fix] query-chat-contacts subscription params
  src/status_im/contact/subs.cljs
Labels: skip-manual-qa

#6762 [TESTS] Check that system replaces capital letters when typing passphrase
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/views/base_view.py
  test/appium/views/recover_access_view.py
Labels: skip-manual-qa, tests

#6766 [#6736] support multi-extensions store
  deps.edn
  src/status_im/extensions/core.cljs
  src/status_im/extensions/registry.cljs
  src/status_im/ui/screens/extensions/add/events.cljs
Labels: Tested - OK, skip-manual-qa

#6745 [TESTS] Assets shown after account recovery (tokens and collectibles)
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/users.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#6778 [fix] current chat in bold on Linux
  src/status_im/ui/screens/desktop/main/tabs/home/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
Labels: Tested - OK, skip-manual-qa

#6791 Reduce number of days required to consider a PR stale to 14
  .github/github-bot.yml
Labels: skip-manual-qa

#6804 [TESTS] Fix switch network flow
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
Labels: skip-manual-qa, tests

#6805 Lock down conan.cmake file version to avoid having upstream break our builds
  desktop/CMakeModules/QtConfiguration.cmake
Labels: skip-manual-qa

#6744 Changed 2-button confirmations to 1-button popups for installing and uninstalling extensions
  src/status_im/extensions/registry.cljs
Labels: Tested - OK

#6622 Automated token settings internal validation 6509
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/migrations.cljs
  src/status_im/init/core.cljs
  src/status_im/models/transactions.cljs
  src/status_im/models/wallet.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties/events.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/ui/screens/wallet/collectibles/kudos/events.cljs
  src/status_im/ui/screens/wallet/collectibles/superrare/events.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/settings/models.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/subs.cljs
  src/status_im/ui/screens/wallet/transaction_fee/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/core.cljc
  src/status_im/utils/ethereum/eip681.cljs
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/ethereum/tokens.cljs
  test/cljs/status_im/test/chat/commands/impl/transactions.cljs
  test/cljs/status_im/test/utils/ethereum/eip681.cljs
  test/cljs/status_im/test/utils/utils.cljs
  translations/en.json
Labels: Tested - OK

#6748 [#6718] Wallet onboarding setup re-style for new wallet flow
  resources/images/ui/wallet-setup.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/styles.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/views.cljs
  src/status_im/ui/screens/wallet/onboarding/styles.cljs
  src/status_im/ui/screens/wallet/onboarding/views.cljs
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/views/base_view.py
  test/appium/views/wallet_view.py
  translations/en.json
  translations/es_419.json
  translations/fa.json
  translations/ko.json
  translations/ms.json
  translations/pl.json
  translations/ru.json
  translations/zh_Hans_CN.json
Labels: Tested - OK, to be automated

#6783 [Fixes #6739] Introduced wallet.settings hook
  project.clj
  src/status_im/extensions/core.cljs
  src/status_im/extensions/registry.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/settings/subs.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
Labels: extensions, skip-manual-qa

#6813 [slow sign in] faster get-unviewed-messages
  src/status_im/data_store/messages.cljs
Labels: skip-manual-qa

#6777 [fix] usernames in bold on Linux
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
Labels: Tested - OK, chat

#6820 [slow sign in] faster :get-referenced-messages
  src/status_im/chat/models/loading.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/core.cljs
Labels: skip-manual-qa

#6809 [Fixes #6784] Fixed some ABI codec issues
  src/status_im/extensions/ethereum.cljs
  src/status_im/utils/ethereum/abi_spec.cljs
  test/cljs/status_im/test/utils/ethereum/abi_spec.cljs
Labels: extensions, skip-manual-qa

#6774 [refactor] differentiate private and public chat and contact subs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/db.cljs
  src/status_im/chat/subs.cljs
  src/status_im/contact/subs.cljs
  src/status_im/search/subs.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
  src/status_im/ui/screens/chat/bottom_info.cljs
  src/status_im/ui/screens/chat/input/animations/expandable.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/input/parameter_box.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/chat/input/suggestions.cljs
  src/status_im/ui/screens/chat/input/validation_messages.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/options.cljs
  src/status_im/ui/screens/chat/photos.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/group/add_contacts/views.cljs
  src/status_im/ui/screens/group/subs.cljs
  src/status_im/ui/screens/home/subs.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/transaction_sent/views.cljs
  src/status_im/ui/screens/wallet/transactions/subs.cljs
Labels: skip-manual-qa

#6578 stop using build-* git tags for counting build numbers
  .gitignore
  android/app/build.gradle
  ci/Jenkinsfile.combined
  ci/android.groovy
  ci/common.groovy
  ci/ios.groovy
  ios/scripts/set_xcode_version.sh
  scripts/build_no.sh
  scripts/gen_build_no.sh
  src/status_im/utils/build.clj
Labels: devops, jenkins

#6794 fix naming of download status-go archives to avoid re-downloads
  Makefile
Labels: devops, jenkins

#6826 [Fixes #6825] Do not open settings as a modal
  src/status_im/ui/screens/wallet/settings/views.cljs
Labels: Tested - OK

#6722 fix slow sign in (first iteration)
  src/status_im/accounts/login/core.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/specs.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/init/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/transport/utils.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/main_tabs/views.cljs
Labels: Tested - OK, high-priority

#6854 Add LES nodes back into list of static nodes
  src/status_im/node/core.cljs
Labels: skip-manual-qa

#6853 fix user-statuses after migration from #6722
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
Labels: Tested - OK, bug

#6858 Fixed broken extensions HTTP events
  src/status_im/extensions/core.cljs
  src/status_im/utils/ethereum/abi_spec.cljs
Labels: extensions, skip-manual-qa

#6792 faster unviewed messages
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/specs.cljs
  src/status_im/chat/subs.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/schemas/account/chat.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/chat/models/message.cljs
Labels: Tested - OK

#6857 [fix 6841] wrongs subscription in group chat
  src/status_im/ui/screens/group/subs.cljs
Labels: Tested - OK, chat

#6868 Fixed an issue with uninstalling non-active extensions
  src/status_im/extensions/registry.cljs
Labels: Tested - OK

#6863 [#6802] Expose a query allowing to access supported ERC20 tokens
  src/status_im/extensions/core.cljs
Labels: skip-manual-qa

#6873 [Fixes #6800] Introduce picker component (and expose activity-loading, list)
  components/src/status_im/ui/components/react.cljs
  deps.edn
  project.clj
  src/status_im/extensions/core.cljs
  src/status_im/extensions/registry.cljs
Labels: skip-manual-qa

#6885 [TESTS] Fixed test_user_can_interact_with_public_chat
  test/appium/tests/atomic/chats/test_public.py
Labels: skip-manual-qa, tests

#6752 Disable send button when no peers are connected.
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK, chat, chat-reliability

#6899 download from DigitalOcean first since it's faster
  Makefile
Labels: skip-manual-qa

#6900 Don't show the LES debug label if the network wasn't initialized just yet
  src/status_im/ui/screens/home/subs.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: LES, Tested - OK

#6890 [#6867] Add on-send-sync to chat.command extension
  deps.edn
  project.clj
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/events.cljs
  src/status_im/extensions/core.cljs
Labels: extensions, skip-manual-qa

#6896 [TESTS] Not enough eth for gas validation from DApp/wallet/chat
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/chat_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#6908 [TESTS] Do not save device stats in InfluxDB if database not provided
  test/appium/tests/conftest.py
Labels: tests

#6911 Upgrade developer builds version to 0.9.33 (Intentionally skip 0.9.32).
  mobile_files/VERSION
Labels: Tested - OK

#6845 [TESTS] redirect to public chat upon tap on the #tag in message
  test/appium/tests/atomic/chats/test_public.py
Labels: skip-manual-qa, tests

#6666 Allow running multiple Desktop instances on the same machine
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.windows
  desktop/main.cpp
  env/dev/env/android/main.cljs
  env/dev/env/desktop/main.cljs
  env/dev/env/ios/main.cljs
  figwheel-bridge.js
  modules/react-native-status/desktop/rctstatus.cpp
  scripts/build-desktop.sh
  src/status_im/android/core.cljs
  src/status_im/data_store/realm/core.cljs
  src/status_im/desktop/core.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/ios/core.cljs
  src/status_im/node/core.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/subs.cljs
  ubuntu-server.js
Labels: Tested - OK, desktop

#6917 Lokalise: Translations update for 0.9.32
  translations/es_419.json
  translations/fa.json
  translations/ko.json
  translations/ms.json
  translations/ne.json
  translations/pl.json
  translations/ru.json
  translations/zh_Hans_CN.json
Labels: release

#6930 [TESTS] User can see own collectibles after recovering the account
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/users.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#6714 Keep username/photo-path synced across devices
  src/status_im/pairing/core.cljs
  src/status_im/transport/impl/send.cljs
  src/status_im/transport/message/contact.cljs
  src/status_im/transport/message/pairing.cljs
  src/status_im/transport/message/transit.cljs
  test/cljs/status_im/test/pairing/core.cljs
Labels: Tested - OK, chat

#6887 [#6789] Allow ENS names to be used for ethereum events
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
Labels: skip-manual-qa

#6865 Connection status info
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK

#6928 Status 💛 Yarn. Lock dependencies.
  Makefile
  ci/Jenkinsfile.linux
  ci/common.groovy
  desktop/docker/linux/Dockerfile
  desktop/docker/windows/Dockerfile
  desktop_files/package-lock.json
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  docker-build/Dockerfile
  mobile_files/package-lock.json
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  scripts/build-desktop.sh
  scripts/lib/setup/installers.sh
  scripts/prepare-for-platform.sh
  scripts/run-osx
  scripts/run-pre-build-check.sh
  scripts/setup
Labels: dev-tools, security, skip-manual-qa

#6922 [Fixes #6874] Added transaction-receipt, schedule and balance events
  src/status_im/constants.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
  src/status_im/utils/ethereum/abi_spec.cljs
  src/status_im/utils/ethereum/tokens.cljs
  src/status_im/utils/money.cljs
  test/cljs/status_im/test/utils/ethereum/abi_spec.cljs
Labels: extensions, skip-manual-qa

#6948 Fix make startdev-desktop target
  Makefile
Labels: skip-manual-qa

#6923 Enable group chats
  .env.e2e
  .env.nightly.staging.fleet
  .env.prod
  src/status_im/chat/db.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/node/core.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  test/cljs/status_im/test/node/core.cljs
Labels: Tested - OK

#6916 Remove slack from fastlane
  fastlane/Fastfile
Labels: skip-manual-qa

#6947 Fix check for yarn
  Makefile
  scripts/lib/setup/installers.sh
  scripts/run-pre-build-check.sh
Labels: skip-manual-qa

#6929 [#6856] Add ethereum/sign event
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
Labels: extensions, skip-manual-qa

#6949 update realm to 2.20.1 and node to 10.14.0
  ci/Jenkinsfile.ios
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  docker-build/Dockerfile
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  scripts/lib/setup/installers.sh
  scripts/run-pre-build-check.sh
Labels: blocked, skip-manual-qa

#6970 Fix 'make setup'
  Makefile
  ci/common.groovy
  scripts/prepare-for-platform.sh
  scripts/run-environment-check.sh
Labels: skip-manual-qa

#6950 [TESTS] Fix pytest internal error if no response from saucelabs API
  test/appium/tests/conftest.py
Labels: skip-manual-qa, tests
