Repository status-im/status-mobile, pull requests merged in 2018-02, with the labels that each got.

#3173 [#3006]: No more search features
  resources/icons/search.svg
  src/status_im/chat/views/actions.cljs
  src/status_im/chat/views/api/choose_contact.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/components/styles.cljs
  src/status_im/ui/components/toolbar/actions.cljs
  src/status_im/ui/components/toolbar/styles.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/contacts/contact_list/views.cljs
  src/status_im/ui/screens/contacts/contact_list_modal/views.cljs
  src/status_im/ui/screens/contacts/navigation.cljs
  src/status_im/ui/screens/contacts/styles.cljs
  src/status_im/ui/screens/contacts/subs.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/discover/events.cljs
  src/status_im/ui/screens/discover/navigation.cljs
  src/status_im/ui/screens/discover/styles.cljs
  src/status_im/ui/screens/discover/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/group/add_contacts/views.cljs
  src/status_im/ui/screens/group/edit_contacts/views.cljs
  src/status_im/ui/screens/group/navigation.cljs
  src/status_im/ui/screens/group/styles.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK, medium-priority

#3279 bug #3232 - fixed profile image setting
  src/status_im/ui/components/camera.cljs
  src/status_im/utils/image_processing.cljs
Labels: Tested - OK, bug

#3236 Update status-go to develop-g607954bf
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
Labels: Tested - OK

#2856 [Fix #2719] App does not fit on iPhone X screen
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/Contents.json
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen1125x2436.png
  src/status_im/chat/subs.cljs
  src/status_im/ios/platform.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/contacts/contact_list_modal/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/choose_recipient/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/utils/platform.cljs
Labels: Tested - OK, bounty, medium-priority

#3272 [ISSUE #3213] Allow to reset gas details
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: wallet

#3302 bug #3300 - updated leftover sub after rebase
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK, bug

#3266 feature #3243 - contact profile screen cleanup
  src/status_im/ui/screens/profile/styles.cljs
  src/status_im/ui/screens/profile/views.cljs
Labels: Tested - OK

#3309 Fetch short preview during sending
  src/status_im/chat/events/input.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: Tested - OK, bug, high-priority, release

#3298 fix location/phone commands migrations #3256
  src/status_im/data_store/realm/schemas/account/v21/core.cljs
Labels: Tested - OK, bug, release

#3297 upgrade rn-camera (attempt to fix #3289)
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  ios/StatusIm.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/status_im/ui/components/camera.cljs
  src/status_im/ui/screens/profile/photo_capture/views.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
Labels: Tested - OK

#3288 [ISSUE #3241] Do not use hardcoded gas price
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/ethereum/core.cljs
Labels: wallet

#3311 [Tests #3284] added sanity profile and browsing tests
  test/appium/tests/test_dapps_and_browsing.py
  test/appium/tests/test_profile.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/start_new_chat_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#3287 [tests #3281] added/reworked transaction tests (sanity)
  test/appium/tests/base_test_case.py
  test/appium/tests/test_multiple_devices.py
  test/appium/tests/test_transaction.py
  test/appium/tests/test_wallet.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/console_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#3324 [tests #3282] Added sanity tests for message sending verification
  test/appium/requirements.txt
  test/appium/tests/__init__.py
  test/appium/tests/base_test_case.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_multiple_devices.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/start_new_chat_view.py
Labels: tests

#3291 Update status-go to `develop-g9cc9982a`.
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
Labels: Tested - OK, high-priority

#3347 [ISSUE #3320] Fixed incorrect label
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK

#3384 Update mailserver node id
  src/status_im/constants.cljs
Labels: bug, high-priority, offline-inboxing

#3192 Fix #3013 Swipe chat based deletion
  resources/icons/delete.svg
  src/status_im/data_store/browser.cljs
  src/status_im/data_store/realm/browser.cljs
  src/status_im/ui/components/animation.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/animations/responder.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK, bounty

#3389 Fix wrong derefs
  src/status_im/chat/views/input/input.cljs
Labels: bug

#3390 Revert "Fix #3013 Swipe chat based deletion"
  resources/icons/delete.svg
  src/status_im/data_store/browser.cljs
  src/status_im/data_store/realm/browser.cljs
  src/status_im/ui/components/animation.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/animations/responder.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/subs.cljs
Labels: bug

#3358 Migrate figwheel conf from project.clj to figwheel ns
  env/dev/figwheel.clj
  env/dev/figwheel_api.clj
  project.clj
Labels: bounty

#3374 [TESTS #3344] Updated group chat creation flow
  test/appium/tests/test_messaging.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/start_new_chat_view.py
Labels: tests

#3395 Improved french translation
  src/status_im/translations/fr.cljs
Labels: translations

#3355 Simplify input handling
  src/status_im/chat/events/commands.cljs
  src/status_im/chat/events/input.cljs
  src/status_im/chat/events/requests.cljs
  src/status_im/chat/events/send_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/chat/views/message/request_message.cljs
Labels: Tested - OK, clojure, medium-priority, tech-debt

#3225 [refs #3210] Replace realm reads for chats with app-db reads
  src/status_im/chat/handlers.cljs
  src/status_im/chat/models.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/realm/chats.cljs
  src/status_im/protocol/handlers.cljs
Labels: medium-priority, tech-debt

#3265 [refs #3210] remove unnecessary reads from Realm for messages
  src/status_im/chat/constants.cljs
  src/status_im/chat/events.cljs
Labels: Tested - OK, tech-debt

#3212 Replace contacts/get-by-id realm read with app-db read
  src/status_im/protocol/handlers.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
Labels: Tested - OK, medium-priority, tech-debt

#3343 Etherscan api update
  src/status_im/utils/transactions.cljs
  test/appium/tests/api_requests.py
Labels: Tested - OK, bounty

#3402 [ISSUE #3396] Fixed incorrect atom access
  src/status_im/chat/views/input/input.cljs
Labels: Tested - OK

#3345 [FIX #3123] ui: fix network field overflow on long network names in profile
  src/status_im/ui/screens/profile/styles.cljs
  src/status_im/ui/screens/profile/views.cljs
Labels: Tested - OK, good first issue

#3315 Tech debt/kebab case
  src/status_im/chat/styles/animations.cljs
  src/status_im/chat/styles/input/box_header.cljs
  src/status_im/chat/styles/message/command_pill.cljs
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/styles/screen.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/native_module/impl/non_status_go_module.cljs
  src/status_im/ui/components/carousel/styles.cljs
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/components/checkbox/styles.cljs
  src/status_im/ui/components/common/styles.cljs
  src/status_im/ui/components/contact/styles.cljs
  src/status_im/ui/components/image_button/styles.cljs
  src/status_im/ui/components/styles.cljs
  src/status_im/ui/components/toolbar/styles.cljs
  src/status_im/ui/screens/contacts/styles.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/qr_scanner/styles.cljs
  src/status_im/ui/screens/wallet/choose_recipient/styles.cljs
  src/status_im/ui/screens/wallet/transactions/styles.cljs
Labels: Tested - OK, bounty, tech-debt

#3404 Increased chat icon tapping area
  src/status_im/chat/styles/input/input.cljs
  src/status_im/chat/styles/input/send_button.cljs
  src/status_im/chat/views/input/input.cljs
  src/status_im/chat/views/input/send_button.cljs
  src/status_im/ui/screens/profile/events.cljs
Labels: Tested - OK

#3425 Repair prod-build from component is null issues
  .re-natal
  modules/desktop-3rd-party/CMakeLists.txt
  modules/desktop-3rd-party/rctmapboxglmanager.cpp
  modules/desktop-3rd-party/rctmapboxglmanager.h
  package.json
  react-native/src/status_im/react_native/js_dependencies.cljs
  src/status_im/desktop/core.cljs
  src/status_im/ui/components/camera.cljs
  src/status_im/ui/components/icons/custom_icons.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/chats_list/views.cljs
  src/status_im/ui/screens/contacts/views.cljs
  src/status_im/ui/screens/profile/photo_capture/views.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  src/status_im/utils/image_processing.cljs
  src/status_im/utils/instabug.cljs
  ubuntu-server.js
Labels: desktop

#3419 Properly open/navigate-to chat
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/views.cljs
Labels: Tested - OK, bug, release

#3357 [FIX #3223] Fit "Enter contact code" screen to mocks on iOS
  src/status_im/ui/screens/wallet/components.cljs
  src/status_im/ui/screens/wallet/components/styles.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/styles.cljs
Labels: Tested - OK, bounty

#3334 [FIX #3229] Change home add button on ios to blue
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/styles.cljs
  src/status_im/ui/components/toolbar/actions.cljs
Labels: Tested - OK, bounty

#3405 [#3366, #3349]: Fixes for expandable; better animations for parameter boxes
  resources/js/bots/console/bot.js
  resources/js/bots/transactor/bot.js
  src/status_im/chat/events.cljs
  src/status_im/chat/events/animation.cljs
  src/status_im/chat/events/input.cljs
  src/status_im/chat/screen.cljs
  src/status_im/chat/styles/animations.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/input/animations/expandable.cljs
  src/status_im/chat/views/input/animations/responder.cljs
  src/status_im/chat/views/input/parameter_box.cljs
  src/status_im/chat/views/input/result_box.cljs
  src/status_im/chat/views/input/suggestions.cljs
  src/status_im/commands/handlers/jail.cljs
  src/status_im/ui/screens/events.cljs
Labels: Tested - OK, bug

#3403 feature #3011 - reworked group chat profile and refactored common pro…
  resources/icons/delete.svg
  src/status_im/translations/en.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/components/contact/styles.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/components/list/styles.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/group/add_contacts/views.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
  src/status_im/ui/screens/group/chat_settings/views.cljs
  src/status_im/ui/screens/group/edit_contacts/views.cljs
  src/status_im/ui/screens/group/styles.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/contact/styles.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/edit/views.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/group_chat/styles.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/profile/styles.cljs
  src/status_im/ui/screens/profile/subs.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/profile/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
  test/cljs/status_im/test/profile/events.cljs
Labels: Tested - OK

#3453 [ISSUE #3432] Make sure public chat topic can be fully erased
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
Labels: Tested - OK

#3454 [ISSUE #3386] Improved group chat details action label
  src/status_im/chat/views/actions.cljs
  src/status_im/translations/en.cljs
Labels: Tested - OK

#3447 [ISSUE #3429] Use proper etherscan URLs
  src/status_im/utils/transactions.cljs
Labels: Tested - OK

#3435 Fix Appium project requirements
  test/appium/requirements.txt
Labels: tests

#3461 [ISSUE #3460] Fixed incorrect style def access
  src/status_im/ui/screens/group/views.cljs
Labels: Tested - OK

#3299 [Fix #3252] Remove dependency on react-native-autolink
  .re-natal
  package-lock.json
  package.json
  react-native/src/status_im/react_native/js_dependencies.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/utils/core.cljc
  test/cljs/status_im/react_native/js_dependencies.cljs
  test/cljs/status_im/test/chat/views/message.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/utils.cljs
Labels: Tested - OK, bounty

#3466 [ISSUE #3331] Allow to configure view compilation
  .env
  .env.jenkins
  .env.prod
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK

#3446 Pass `WhisperConfig.LightClient: true` in node config. Closes #3442
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
Labels: Tested - OK, high-priority

#3468 [ISSUE #3316] Do not avoid keyboard in wallet/fee screen
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#3354 request camera permissions from webview #3003
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  package-lock.json
  package.json
Labels: Tested - OK

#3476 add merge-fx macro
  src/status_im/utils/handlers.clj
  src/status_im/utils/handlers.cljs
Labels: developer-xp
