Repository status-im/status-mobile, pull requests merged in 2018-03, with the labels that each got.

#3471 [ISSUE #3312] Implemented invite friends feature
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/add_new/views.cljs
Labels: Tested - OK

#3332 Use re-frame fork to fix UI freezes
  project.clj
  src/status_im/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
Labels: Tested - OK, performance

#3484 [ISSUE #3224] Click on user picture open profile
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK

#3421 Update de.cljs
  src/status_im/translations/de.cljs
Labels: translations

#3502 bug #3463 - disabled removal and addition of group chat participants
  src/status_im/ui/screens/profile/group_chat/views.cljs
Labels: Tested - OK, bug

#3490 [Tests #3470] updated with new onboarding flow
  test/appium/tests/test_dapps_and_browsing.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_multiple_devices.py
  test/appium/tests/test_networks.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_sanity.py
  test/appium/tests/test_transaction.py
  test/appium/tests/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#3494 Fix #3013 Swipe chat based deletion
  src/status_im/data_store/browser.cljs
  src/status_im/data_store/realm/browser.cljs
  src/status_im/ui/components/animation.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/animations/responder.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK

#3452 Update end-end test report for Github
  .gitignore
  test/appium/support/github_test_report.py
  test/appium/tests/__init__.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
Labels: tests

#3514 [fix 3424] visually indicated when mailserver or all peers are discon…
  src/status_im/chat/screen.cljs
  src/status_im/chat/views/input/result_box.cljs
  src/status_im/protocol/handlers.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/connectivity/styles.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/components/sync_state/offline.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK, high-priority

#3504 Bug/message ordering #2699
  src/status_im/chat/console.cljs
  src/status_im/chat/handlers.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/data_store/realm/chats.cljs
  src/status_im/data_store/realm/messages.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/v23/core.cljs
  src/status_im/data_store/realm/schemas/account/v23/message.cljs
  src/status_im/protocol/handlers.cljs
Labels: Tested - Issues, bounty, bug, fix them all, high-priority

#3515 Fixing fx arguments and event dispatches
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/events.cljs
Labels: blocker, high-priority

#3496 [ISSUE #3051] Links to mobile nofifications settings
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#3523 [fix #3505] Fix account initialization events order
  src/status_im/ui/screens/accounts/login/events.cljs
Labels: Tested - OK, bug, high-priority

#3535 [#3478]: Buttons are to close to status bar on Edit profile for group chat
  src/status_im/ui/screens/profile/group_chat/views.cljs
Labels: Tested - OK

#3480 Whisper v6/geth 1.8.1 migration
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
  src/status_im/constants.cljs
Labels: Tested - OK, high-priority

#3542 [ISSUE #3482] Fixe profile UI regression
  src/status_im/ui/components/qr_code_viewer/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#3518 [Fix #3485] Increase tap zones for rows with checkboxes
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK, bounty

#3540 [#3325]: Transaction fee field is hidden behind keyboard if Amount field had focus
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#2962 [Fix #1785] Handle timeout for network failure in utils.utils/http-get and http-post
  .re-natal
  package-lock.json
  package.json
  react-native/src/status_im/react_native/js_dependencies.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/subs.cljs
  src/status_im/ui/screens/wallet/transactions/subs.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
  src/status_im/utils/utils.cljs
Labels: bounty, medium-priority, tech-debt

#3522 [Fix #3369] Migrate checkboxes to native widget
  android/app/src/main/res/values/colors.xml
  src/status_im/ui/components/checkbox/view.cljs
  src/status_im/ui/components/react.cljs
Labels: bounty

#3556 [#3509 #3544] Fix android permissions
  android/app/src/main/java/im/status/ethereum/MainActivity.java
Labels: Tested - OK, android, bug

#3557 [ISSUE #3511] Fixed incorrect styles on iOS
  src/status_im/ui/components/text_field/styles.cljs
  src/status_im/ui/components/text_field/view.cljs
  src/status_im/ui/screens/add_new/new_public_chat/styles.cljs
Labels: Tested - OK

#3553 Add :elide-asserts compiler option for release builds
  project.clj
Labels: enhancement

#3566 [ISSUE #3559] Fixed regression when sending send request from chat
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#3570 feature #3248 - new contact profile
  resources/icons/add_contact.svg
  resources/icons/in_contacts.svg
  src/status_im/translations/en.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/components/list/styles.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/contact/styles.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#3385 Refactor timestamp
  src/status_im/chat/handlers.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/browser.cljs
  src/status_im/data_store/realm/chats.cljs
  src/status_im/data_store/realm/contact_groups.cljs
  src/status_im/protocol/discoveries.cljs
  src/status_im/protocol/group.cljs
  src/status_im/protocol/handlers.cljs
  src/status_im/protocol/web3/delivery.cljs
  src/status_im/protocol/web3/utils.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/ui/screens/discover/subs.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/group/events.cljs
  src/status_im/utils/datetime.cljs
  src/status_im/utils/gfycat/core.cljs
  src/status_im/utils/random.cljs
  test/cljs/status_im/test/contacts/events.cljs
Labels: Tested - OK, bounty

#3529 [Fix #3472] Add accessibility labels for Profile screens
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/network_settings/network_details/views.cljs
  src/status_im/ui/screens/network_settings/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: bounty

#3528 [Fix #3477] Add accessibility labels for New Chat screens
  src/status_im/ui/components/action_button/action_button.cljs
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/components/text_field/view.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/group/add_contacts/views.cljs
  src/status_im/ui/screens/group/views.cljs
Labels: bounty

#3532 Add setup and full-prod-build targets
  Makefile
Labels: bounty-awaiting-approval

#3517 [Fix #3394] Add accessibility labels for Wallet screens
  src/status_im/ui/components/button/view.cljs
  src/status_im/ui/components/checkbox/view.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/components/qr_code_viewer/views.cljs
  src/status_im/ui/components/toolbar/actions.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/screens/wallet/choose_recipient/views.cljs
  src/status_im/ui/screens/wallet/components.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/transaction_sent/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
  src/status_im/utils/utils.cljs
Labels: bounty

#3547 [#3520] Allow adding/chatting with contacts from public chats
  src/status_im/chat/screen.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/ui/screens/contacts/subs.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/utils/contacts.cljs
  test/cljs/status_im/test/contacts/events.cljs
Labels: Tested - OK

#3437 [FIX #3379] Support platform specific :uppercase as a text prop
  src/status_im/android/platform.cljs
  src/status_im/ios/platform.cljs
  src/status_im/ui/components/button/view.cljs
  src/status_im/ui/components/common/common.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/components/sticky_button.cljs
  src/status_im/ui/components/styles.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/screens/discover/components/views.cljs
  src/status_im/ui/screens/discover/styles.cljs
  src/status_im/ui/screens/network_settings/network_details/views.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/send/transaction_sent/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: bounty

#3576 [Fix #3572] regx parse string bug in formatted texts
  src/status_im/chat/views/message/message.cljs
  test/cljs/status_im/test/chat/views/message.cljs
Labels: Tested - OK

#3428 [TESTS #3360] tests aligned with latest nightly build
  Jenkinsfile
  test/appium/tests/__init__.py
  test/appium/tests/base_test_case.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_transaction.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/console_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/start_new_chat_view.py
  test/appium/views/wallet_view.py
Labels: tests

#3595 Pull username from message or generate when not in contacts
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK

#3584 [#3582] No "Add to contact" button when conversation was started from public chat
  src/status_im/chat/screen.cljs
Labels: Tested - OK

#3602 Feature/profile onboarding
  resources/icons/down.svg
  resources/icons/up.svg
  resources/images/ui/lock.png
  src/status_im/chat/screen.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/toolbar_content.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/v8/account.cljs
  src/status_im/data_store/realm/schemas/base/v8/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/common/common.cljs
  src/status_im/ui/components/common/styles.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/components/text_input/styles.cljs
  src/status_im/ui/components/text_input/view.cljs
  src/status_im/ui/components/toolbar/styles.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/screens/accounts/db.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/recover/events.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/main_tabs/styles.cljs
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/db.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/navigation.cljs
  src/status_im/ui/screens/profile/seed/styles.cljs
  src/status_im/ui/screens/profile/seed/views.cljs
  src/status_im/ui/screens/profile/subs.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/subs.cljs
Labels: Tested - OK

#3507 Replace default keyExtractor with individual key-fns
  src/status_im/chat/screen.cljs
  src/status_im/chat/views/api/choose_contact.cljs
  src/status_im/chat/views/bottom_info.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/accounts/views.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
  src/status_im/ui/screens/contacts/contact_list/views.cljs
  src/status_im/ui/screens/contacts/contact_list_modal/views.cljs
  src/status_im/ui/screens/discover/all_dapps/views.cljs
  src/status_im/ui/screens/discover/popular_hashtags/views.cljs
  src/status_im/ui/screens/discover/views.cljs
  src/status_im/ui/screens/group/add_contacts/views.cljs
  src/status_im/ui/screens/group/edit_contacts/views.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/network_settings/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
Labels: Tested - OK

#3534 Fixes for chat input (#3412, #3481); animations leftovers removed
  src/status_im/chat/screen.cljs
  src/status_im/chat/styles/input/box_header.cljs
  src/status_im/chat/styles/screen.cljs
  src/status_im/chat/views/input/animations/expandable.cljs
  src/status_im/chat/views/input/box_header.cljs
  src/status_im/chat/views/input/input.cljs
  src/status_im/chat/views/input/parameter_box.cljs
  src/status_im/chat/views/input/result_box.cljs
  src/status_im/chat/views/input/suggestions.cljs
Labels: Tested - OK

#3627 [Fix #3588] "There are no messages in this chat yet" is left-aligned instead of centred as in design
  src/status_im/chat/styles/screen.cljs
Labels: Tested - OK

#3596 Use whisper-id when in profile to navigate to chat
  src/status_im/chat/events.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/events.cljs
Labels: Tested - OK

#3628 [Fix #3609] Remove showing users profile from 'Creating New Chat' flow
  src/status_im/ui/screens/add_new/new_chat/views.cljs
Labels: Tested - OK

#3626 [Fix #3319] STT/SNT tokens are not shown by default for recovered account
  src/status_im/constants.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/recover/events.cljs
Labels: Tested - OK

#3597 Send app state changes to status-go.
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/ios/RCTStatus/pom.xml
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/native_module/impl/non_status_go_module.cljs
  src/status_im/native_module/module.cljs
  src/status_im/ui/screens/events.cljs
Labels: Tested - OK

#3605 [ISSUE #3537] Added mixpanel support
  .env
  .env.jenkins
  .env.prod
  src/status_im/chat/events/commands.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/qr_scanner/styles.cljs
  src/status_im/ui/screens/usage_data/events.cljs
  src/status_im/ui/screens/usage_data/views.cljs
  src/status_im/utils/build.clj
  src/status_im/utils/build.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/handlers.cljs
  src/status_im/utils/http.cljs
  src/status_im/utils/mixpanel.cljs
  src/status_im/utils/mixpanel_events.edn
  src/status_im/utils/platform.cljs
  src/status_im/utils/prices.cljs
  src/status_im/utils/styles.clj
  src/status_im/utils/transactions.cljs
  src/status_im/utils/types.cljs
  src/status_im/utils/utils.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/mixpanel.cljs
Labels: Tested - OK

#3607 [FIX #3591] always show full link
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK, bounty

#3657 Feature/introduce desktop
  components/src/status_im/ui/components/react.cljs
  components/src/status_im/ui/components/svg.clj
  env/dev/env/desktop/main.cljs
  env/dev/figwheel.clj
  project.clj
  src/status_im/desktop/core.cljs
  src/status_im/desktop/platform.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/components/desktop/views.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/utils/platform.cljs
  src/status_im/utils/slurp.clj
Labels: desktop

#3659 [fix #3606] Add 0x prefix to address when sharing
  src/status_im/ui/screens/accounts/subs.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
Labels: Tested - OK, bug, fix them all

#3592 Changed xpath locators to accessibility labels in end to end tests
  test/appium/tests/base_test_case.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_sanity.py
  test/appium/tests/test_transaction.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/console_view.py
  test/appium/views/contacts_view.py
  test/appium/views/discover_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_drawer_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/start_new_chat_view.py
  test/appium/views/transactions_view.py
  test/appium/views/wallet_view.py
Labels: tests

#3676 Feature/mixpanel events for profile
  src/status_im/utils/mixpanel.cljs
  src/status_im/utils/mixpanel_events.edn
Labels: Tested - OK

#3688 Fix swipe-based delete-action handler
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK, high-priority

#3693 Dont throw error on empty data
  android/app/src/main/java/im/status/ethereum/MainActivity.java
Labels: Tested - OK

#3608 [Fix #3575] Create clj script
  build.clj
  deps.edn
Labels: bounty

#3697 Make Andy happy again (by fixing debug mode)
  src/status_im/chat/events/commands.cljs
  src/status_im/chat/events/input.cljs
  src/status_im/chat/events/send_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/commands/handlers/jail.cljs
  src/status_im/protocol/web3/delivery.cljs
  src/status_im/protocol/web3/transport.cljs
  src/status_im/utils/handlers.cljs
Labels: Tested - OK

#3704 [#3694] Ignore mixpanel/track http error when offline
  src/status_im/utils/mixpanel.cljs
Labels: Tested - OK, bug

#3710 Remove inactive testflight users with Fastlane + Jenkins
  Gemfile
  Gemfile.lock
  Jenkinsfile.fastlane.clean
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tested - OK

#3680 Feature/show 'opt-in' screen to recovery
  src/status_im/ui/screens/accounts/recover/events.cljs
Labels: Tested - OK

#3695 Added rebase on develop to Jenkinsfile
  Jenkinsfile
Labels: tests

#3687 [FIX #3678] Allow interaction w/edit profile screen while keyboard vi…
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, bounty

#3712 Bug/reverted network details
  src/status_im/ui/screens/network_settings/network_details/views.cljs
  src/status_im/ui/screens/network_settings/views.cljs
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK

#3692 Revert "Fix message ordering for 1-1 chats"
  src/status_im/chat/console.cljs
  src/status_im/chat/handlers.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/data_store/realm/chats.cljs
  src/status_im/data_store/realm/messages.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/v23/core.cljs
  src/status_im/data_store/realm/schemas/account/v23/message.cljs
  src/status_im/protocol/handlers.cljs
Labels: Tested - OK

#3696 [FIX #3573] adding scripts/list-pull-requests.sh
  scripts/generate-pull-request-report.sh
  scripts/list-pull-requests.sh
Labels: bounty, developer-xp

#3668 [FIX #3650] Blue open dapp button
  src/status_im/ui/components/action_button/styles.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
Labels: Tested - OK, bounty

#3731 Fix recent typos and grammar
  src/status_im/translations/en.cljs
Labels: Tested - OK

#3736 bug #3735 - fixed broken send and request commands in chat
  src/status_im/chat/events/send_message.cljs
Labels: Tested - OK

#3725 Update instabug to 2.8.1
  .env
  .env.e2e
  .env.jenkins
  .env.prod
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/status_im/ios/core.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/instabug.cljs
Labels: Tested - OK, enhancement, user-xp

#3728 Link to settings on Android 8
  android/app/src/main/java/im/status/ethereum/MainActivity.java
Labels: Tested - OK

#3714 [ISSUE #3633] Migrated profile lists to latest design
  src/status_im/commands/handlers/jail.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/network_settings/styles.cljs
  src/status_im/ui/screens/network_settings/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/events.cljs
  src/status_im/ui/screens/offline_messaging_settings/styles.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK
