Repository status-im/status-mobile, pull requests merged in 2018-09, with the labels that each got.

#5718 Simplify setup script and fix Android build when setting up from scratch
  Makefile
  scripts/lib/setup/installers.sh
  scripts/setup
Labels: developer-xp, skip-manual-qa

#5708 [#4772] Resolve ENS domains in browser
  deps.edn
  project.clj
  src/status_im/models/browser.cljs
  src/status_im/ui/screens/browser/db.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/navigation.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/utils/ethereum/ens.cljs
  src/status_im/utils/ethereum/resolver.cljs
  src/status_im/utils/multihash.cljs
Labels: Tested - OK

#5712 bug #5542 - fixed errors when no currency selected - using usd as def…
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/ui/screens/currency_settings/events.cljs
  src/status_im/ui/screens/currency_settings/models.cljs
  src/status_im/ui/screens/currency_settings/subs.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/currency_settings/models.cljs
Labels: Tested - OK

#5726 [#5374] upgrade react-native-webview-bridge
  mobile_files/package-lock.json
  mobile_files/package.json
Labels: Tested - OK

#5728 View & preview implemented
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/impl/transactions/styles.cljs
  src/status_im/chat/commands/impl/transactions/subs.cljs
  src/status_im/extensions/registry.cljs
Labels: extensions, skip-manual-qa

#5731 [TESTS] False failures fix
  test/appium/support/api/network_api.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#5732 Only interpret extension universal links if flag is enabled
  src/status_im/utils/universal_links/core.cljs
Labels: skip-manual-qa

#5725 [feature #5422] universal links scannable via QR code scanner
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/add_new/events.cljs
  src/status_im/ui/screens/add_new/models.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/utils.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/add-new/models.cljs
Labels: Tested - OK

#5733 [fix 5715] make generate-sym-key-from-password mergeable
  src/status_im/transport/inbox.cljs
  src/status_im/transport/message/v1/public_chat.cljs
  src/status_im/transport/shh.cljs
  src/status_im/utils/handlers_macro.cljs
  test/cljs/status_im/test/transport/inbox.cljs
Labels: Tested - OK, blocker, bug, high-priority, release

#5727 Bump version to 0.9.28
  mobile_files/VERSION
Labels: Tested - OK

#5692 [fix #5303] Improve amount validation for /send and /request commands
  src/status_im/chat/commands/impl/transactions.cljs
  test/cljs/status_im/test/chat/commands/impl/transactions.cljs
Labels: Tested - Issues, bug, chat, commands, wallet

#5710 remove old jenkinsfiles
  ci/Jenkinsfile
  ci/Jenkinsfile.desktopbuild
  ci/Jenkinsfile.nightly_desktop
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.nightly_fastlane_staging_fleet
  ci/Jenkinsfile.parameters
  ci/Jenkinsfile.release
Labels: skip-manual-qa

#5740 [fix 5738] unread counter disappears after app restart
  src/status_im/data_store/messages.cljs
  src/status_im/init/events.cljs
  src/status_im/models/chat.cljs
Labels: Tested - OK, bug, high-priority, release

#5748 Update desktop dev env setup doc
  doc/desktop/DevEnvSetup.md
Labels: desktop, skip-manual-qa

#5721 Always define request-permissions
  modules/react-native-status/desktop/CMakeLists.txt
  src/status_im/notifications/core.cljs
Labels: Tested - OK, desktop, high-priority

#5763 [TESTS] Updated profile picture, home and signing phrase captures
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/views/elements_templates/sauce_logo.png
Labels: skip-manual-qa, tests

#5610 [fix #4819] update react-native to 0.56
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/build.gradle
  ci/Jenkinsfile.android
  clj-rn.conf.edn
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.m
  ios/StatusIm/Info.plist
  mobile_files/package-lock.json
  mobile_files/package.json
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  rn-cli.config.js
  src/status_im/models/browser.cljs
  src/status_im/notifications/core.cljs
  src/status_im/ui/components/camera.cljs
  src/status_im/ui/components/dialog.cljs
  src/status_im/ui/components/svgimage.cljs
  src/status_im/ui/screens/wallet/choose_recipient/styles.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
Labels: Tested - OK, blocker

#5761 Enhanced receive params
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/protocol.cljs
  src/status_im/chat/commands/receiving.cljs
  src/status_im/chat/commands/sending.cljs
  src/status_im/chat/models/message.cljs
Labels: Tested - OK, clojure, tech-debt

#5769 [fix] update yellowbox ignore warning to new react-native api
  src/status_im/core.cljs
Labels: developer-xp, skip-manual-qa

#5775 Copy log files to crash report directory
  desktop/main.cpp
  desktop/reportApp/main.cpp
  desktop/reportApp/reportpublisher.cpp
  desktop/reportApp/reportpublisher.h
Labels: desktop, skip-manual-qa

#5743 [fix #5063] calculate fiat amount on recipient side
  src/status_im/chat/models/message.cljs
  test/cljs/status_im/test/chat/models/message.cljs
Labels: Tested - OK

#5788 Automate code-signing of macOS bundle
  ci/desktop.groovy
  deployment/macos/macos-developer-id.keychain-db.gpg
  scripts/encrypt-keychain.sh
  scripts/gen-random-passphrase.sh
  scripts/sign-macos-pkg.sh
Labels: desktop, high-priority, security, user-xp

#5742 feature #4747 - ens usernames in wallet send
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/events.cljs
  src/status_im/utils/ethereum/ens.cljs
  src/status_im/utils/ethereum/stateofus.cljs
Labels: Tested - OK

#5641 bug #4590 - scrolling wallet send only after keyboard is open
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#5808 fix refactoring leftover
  src/status_im/notifications/core.cljs
Labels: skip-manual-qa

#5764 [#5593] Disallow decimal wei value for gas price
  src/status_im/models/wallet.cljs
  test/cljs/status_im/test/models/wallet.cljs
Labels: Tested - OK, bug, wallet

#5782 Fix 'Send message' handler in chat profile window
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5795 Change links color in chat header
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5799 Update changelog for 0.9.27
  CHANGELOG.md
Labels: skip-manual-qa

#5826 Fix `make setup` on macOS.
  scripts/lib/setup/installers.sh
Labels: skip-manual-qa

#5642 [fix #5604] Fixed the problem of tooltips being cropped on the android platform.
  src/status_im/ui/screens/accounts/create/styles.cljs
  src/status_im/ui/screens/accounts/login/styles.cljs
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/transaction_fee/views.cljs
Labels: Tested - OK, bounty

#5318 Add system warnings, delivery notifications, general unread messages
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/ui/components/connectivity/styles.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/main_tabs/styles.cljs
Labels: Tested - OK, desktop

#5737 Update status-go to 0.14.0 (Keys Derivation Padding Fix)
  modules/react-native-status/android/build.gradle
  modules/react-native-status/desktop/CMakeLists.txt
  modules/react-native-status/ios/RCTStatus/pom.xml
Labels: Tested - OK

#5762 web3 opt-in updates
  resources/js/web3_init.js
  resources/js/web3_opt_in.js
  resources/js/webview.js
  src/status_im/accounts/core.cljs
  src/status_im/constants.cljs
  src/status_im/events.cljs
  src/status_im/models/browser.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/js_resources.cljs
  translations/en.json
Labels: Tested - OK

#5818 [#5798] change wallet balance tilde color
  src/status_im/ui/screens/wallet/main/styles.cljs
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/subs.cljs
Labels: Tested - OK, wallet

#5734 [fix #5729] ask for PN permissions when account recovered
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/v10/account.cljs
  src/status_im/data_store/realm/schemas/base/v10/core.cljs
  src/status_im/init/core.cljs
Labels: Tested - OK

#5735 [TESTS] Added chatbot for one-to-one chats
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/test_chatbot.py
Labels: skip-manual-qa, tests

#5842 [TESTS] Fixed issue with empty public key input after entering the key
  test/appium/tests/base_test_case.py
  test/appium/views/contacts_view.py
Labels: skip-manual-qa, tests

#5833 translations: Add PT translation for Fastlane
  fastlane/metadata/android/pt/full_description.txt
  fastlane/metadata/android/pt/short_description.txt
  fastlane/metadata/android/pt/title.txt
  fastlane/metadata/android/pt/video.txt
Labels: skip-manual-qa, translations

#5797 [#5745] validate account recover result
  CHANGELOG.md
  src/status_im/accounts/recover/core.cljs
  translations/en.json
Labels: Tested - OK, bug

#5809 [#5474] Handle offline wallet onboarding
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/settings/events.cljs
  src/status_im/ui/screens/wallet/settings/models.cljs
Labels: Tested - OK, bug, offline, wallet

#5770 Fix French Play Store title listing translation
  fastlane/metadata/android/fr-FR/title.txt
Labels: skip-manual-qa

#5867 Default dapps missed translation keys
  src/status_im/ui/screens/browser/default_dapps.cljs
  translations/en.json
Labels: skip-manual-qa

#5855 update developer dependencies
  clj-rn.conf.edn
  deps.edn
  project.clj
Labels: skip-manual-qa

#5874 Fix unit tests
  test/cljs/status_im/test/chat/commands/impl/transactions.cljs
Labels: skip-manual-qa

#5785 Add basic support for custom URL schemes on the desktop
  deployment/macos/Info.plist
Labels: Tested - Issues, desktop, medium-priority

#5229 Username overlaps Done button
  src/status_im/ui/components/toolbar/styles.cljs
  src/status_im/ui/components/toolbar/view.cljs
Labels: Tested - OK, bounty

#5847 Obscure CreateAccount result to put into the log; .re-natal config updated.
  desktop_files/.re-natal
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
Labels: Tested - OK, desktop

#5853 Improve log format in StatusIm.log and add timestamps
  desktop/main.cpp
  scripts/merge-pr.sh
Labels: Tested - OK, desktop

#5881 [FIX 5813] connect to custom mailserver button fix
  src/status_im/data_store/mailservers.cljs
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
  test/cljs/status_im/test/mailserver/core.cljs
Labels: Tested - OK

#5868 Allow numbers in chat topics
  CHANGELOG.md
  src/status_im/ui/screens/add_new/new_public_chat/db.cljs
  translations/en.json
Labels: Tested - OK

#5768 Fixed Play Store German listing formatting
  fastlane/metadata/android/de-DE/full_description.txt
Labels: skip-manual-qa

#5894 [fix 5814] fix custom network
  src/status_im/accounts/update/core.cljs
  src/status_im/bootnodes/core.cljs
  src/status_im/data_store/accounts.cljs
  src/status_im/network/core.cljs
  src/status_im/protocol/core.cljs
  test/cljs/status_im/test/screens/accounts/utils.cljs
Labels: Tested - OK, bug, high-priority

#5901 fix red screen on figwheel reloading
  src/status_im/ui/screens/views.cljs
Labels: skip-manual-qa

#5861 Improve desktop chat ui
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/styles.cljs
Labels: Tested - OK, desktop

#5908 [fix 5903] fix empty screen when navigating back in create-account
  src/status_im/accounts/create/core.cljs
Labels: Tested - OK, high-priority, release

#5893 [#5825] add hardwallet auth method and connect screens
  .env
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  ios/Podfile
  ios/Podfile.lock
  mobile_files/package-lock.json
  mobile_files/package.json
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  resources/icons/hardwallet.svg
  resources/icons/nfc.svg
  resources/icons/password.svg
  resources/icons/wifi.svg
  resources/images/ui/hardwallet-card.png
  resources/images/ui/phone-nfc.png
  src/status_im/accounts/create/core.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/accounts/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/hardwallet/authentication_method/styles.cljs
  src/status_im/ui/screens/hardwallet/authentication_method/views.cljs
  src/status_im/ui/screens/hardwallet/connect/styles.cljs
  src/status_im/ui/screens/hardwallet/connect/subs.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  translations/en.json
Labels: hardwallet, skip-manual-qa

#5911 [#5885] fix Password pop-up 'Sign message' wallet screen overlaps Can…
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK, high-priority, release

#5906 [fix 5705] fix crash when tapping sign in twice in account recovery
  src/status_im/accounts/recover/core.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
Labels: Tested - OK, high-priority, release

#5914 replace all register-event-db by fx and remove trim-v interceptor
  doc/codebase-structure-and-guidelines.md
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/events.cljs
  src/status_im/chat/events/input.cljs
  src/status_im/chat/events/receive_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/dev_server/events.cljs
  src/status_im/events.cljs
  src/status_im/protocol/core.cljs
  src/status_im/transport/filters.cljs
  src/status_im/transport/handlers.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/ui/screens/desktop/main/chat/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/extensions/add/events.cljs
  src/status_im/ui/screens/extensions/events.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
  src/status_im/ui/screens/group/events.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/transactions/events.cljs
  src/status_im/utils/handlers.cljs
  test/cljs/status_im/test/browser/events.cljs
  test/cljs/status_im/test/transport/handlers.cljs
Labels: clojure, skip-manual-qa, tech-debt

#5917 explicitly add react-native-safe-area-view as dependency
  mobile_files/package.json
Labels: developer-xp, skip-manual-qa

#5918 remove deprecated navigate-to function
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/ui/screens/extensions/add/events.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
  src/status_im/ui/screens/navigation.cljs
Labels: clojure, skip-manual-qa, tech-debt

#5916 Bump version of develop to 0.9.29
  mobile_files/VERSION
Labels: skip-manual-qa

#5817 [#5392] disable "sign transaction" button when offline
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  translations/en.json
Labels: Tested - OK, bug, offline, release, wallet

#5872 Lokalise: Chinese Translations update (zh_Hans_CN)
  src/status_im/i18n.cljs
  translations/zh_Hans_CN.json
Labels: Tested - OK

#5924 Feature/5923 move default public chat to json
  resources/default_public_chats.json
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
Labels: skip-manual-qa

#5925 [fix 5921] rename fastlane/metadata/android/pt to pt-PT
  fastlane/metadata/android/pt-PT/full_description.txt
  fastlane/metadata/android/pt-PT/short_description.txt
  fastlane/metadata/android/pt-PT/title.txt
  fastlane/metadata/android/pt-PT/video.txt
Labels: blocker, release, skip-manual-qa

#5926 fix event vector
  src/status_im/transport/filters.cljs
Labels: bug, skip-manual-qa

#5920 Explicitly disable Rendezvous discovery when signing in to the account.
  src/status_im/node/core.cljs
Labels: Tested - OK

#5896 Edit username on desktop
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
Labels: Tested - OK, desktop

#5940 [TESTS] Fix for retrieve passphrase
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#5947 Remove misleading wrap-call-once! fn
  src/status_im/utils/core.cljc
  test/cljs/status_im/test/utils/utils.cljs
Labels: bug, skip-manual-qa, tech-debt

#5943 Fix bad navigation call
  src/status_im/ui/screens/wallet/request/events.cljs
Labels: Tested - OK, bug, high-priority

#5956 [#5898] add HW setup screens
  src/status_im/accounts/create/core.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/hardwallet/connect/styles.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/subs.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/setup/styles.cljs
  src/status_im/ui/screens/hardwallet/setup/subs.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  src/status_im/ui/screens/hardwallet/success/styles.cljs
  src/status_im/ui/screens/hardwallet/success/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/utils.cljs
  test/cljs/status_im/test/hardwallet/core.cljs
  test/cljs/status_im/test/runner.cljs
  translations/en.json
Labels: hardwallet, skip-manual-qa

#5944 [#5942] reduce touching area for Privacy Policy link
  src/status_im/ui/screens/privacy_policy/views.cljs
Labels: Tested - OK, desktop

#5946 [#5934] persist text in message input field after navigating
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, bug, desktop

#5952 [#5938] [desktop] switch editing mode when leaving profile
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
Labels: Tested - OK, bug, desktop

#5932 Upgrade to react-native 0.56
  desktop_files/package-lock.json
  desktop_files/package.json
  patches/metro+0.38.4.patch
Labels: Tested - OK, desktop

#5781 [#5365] Start chatting from the dapp browser
  src/status_im/browser/core.cljs
  src/status_im/chat/events.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/universal_links/core.cljs
Labels: Tested - OK

#5969 hide hardwallet screens from navigation
  src/status_im/ui/screens/views.cljs
Labels: skip-manual-qa

#5961 [#5698] null is not an object .sendToBridge
  resources/js/web3_init.js
  resources/js/web3_opt_in.js
  src/status_im/browser/core.cljs
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#5915 Add pfs flag, installation id and nobackup data directory
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  modules/react-native-status/desktop/rctstatus.cpp
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/db.cljs
  src/status_im/data_store/realm/core.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/v11/account.cljs
  src/status_im/data_store/realm/schemas/base/v11/core.cljs
  src/status_im/events.cljs
  src/status_im/node/core.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/platform.cljs
  src/status_im/utils/random.cljs
  test/cljs/status_im/test/node/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/handlers.cljs
Labels: Tested - OK

#5957 [fix 5950] closing browser redirects to home
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK, browser, bug

#5973 [TESTS] False failures fix
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/elements_templates/sauce_logo_red.png
  test/appium/views/elements_templates/saucelabs_sauce.png
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/web_views/base_web_view.py
Labels: skip-manual-qa, tests

#5974 fix red screen on figwheel reloading when intro screen has been opened
  src/status_im/ui/screens/views.cljs
Labels: skip-manual-qa

#5972 introduce fx/defn macro and fx/merge function
  src/status_im/utils/fx.clj
  src/status_im/utils/fx.cljs
  src/status_im/utils/handlers_macro.clj
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/fx.cljs
Labels: clojure, skip-manual-qa, tech-debt

#5983 fix show-error fx
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
Labels: bug, skip-manual-qa

#5982 [fix 5981] fix "thank you" pop after every login
  src/status_im/accounts/core.cljs
Labels: Tested - OK, bug, high-priority, release

#5986 Fleet settings: use fleet names from the JSON file.
  src/status_im/ui/screens/fleet_settings/views.cljs
Labels: Tested - OK

#5977 Moved wallet under options
  src/status_im/ui/screens/chat/actions.cljs
  src/status_im/ui/screens/chat/views.cljs
  translations/en.json
Labels: Tested - OK

#5987 [#5984] Keyboard overlaps message input in public modal chat screen o…
  components/src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK

#5966 upgrade realm-js to 2.16.1
  ci/mobile.groovy
  mobile_files/package-lock.json
  mobile_files/package.json
  patches/js_realm.hpp
Labels: Tested - OK

#5990 fix CVE-2018-6341
  desktop_files/package-lock.json
  desktop_files/package.json
  mobile_files/package-lock.json
  mobile_files/package.json
Labels: high-priority, security, skip-manual-qa

#5994 remove usage of merge-effects macro and handlers-macro ns
  src/status_im/chat/models/message.cljs
  src/status_im/transport/handlers.cljs
  src/status_im/transport/message/v1/contact.cljs
  src/status_im/utils/handlers_macro.cljs
Labels: bug, skip-manual-qa

#5560 fixes #4846
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/home/styles.cljs
Labels: Tested - OK, bounty

#6008 fix clear history
  src/status_im/chat/events.cljs
Labels: Tested - OK, bug, chat

#6011 fix cofx position
  src/status_im/chat/events.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/utils/universal_links/events.cljs
Labels: Tested - OK, bug, medium-severity

#5879 Unify desktop build
  .gitignore
  Makefile
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/desktop.groovy
  deployment/env
  desktop/CMakeLists.txt
  doc/desktop/DevEnvSetup.md
  doc/desktop/Troubleshooting.md
  scripts/build-desktop.sh
  scripts/create-desktop-mac-bundle.sh
  scripts/lib/setup/installers.sh
  scripts/setup
  src/status_im/node/core.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK, desktop, dev-tools, jenkins

#5993 Run CLJS unit tests when building desktop
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/common.groovy
  ci/mobile.groovy
Labels: desktop, jenkins, skip-manual-qa

#6015 [fix 5857] navigate-to home when deleting chat
  src/status_im/chat/events.cljs
Labels: Tested - OK, desktop

#6010 [#5991] Dapp cant recognise Status as web3 provider with enabled Web3…
  resources/js/web3_opt_in.js
Labels: Tested - OK

#5997 Add back group chats messages
  .env
  .env.e2e
  desktop_files/package-lock.json
  desktop_files/package.json
  mobile_files/package-lock.json
  mobile_files/package.json
  src/status_im/chat/events.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/group_chat.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/core.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/desktop/core.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/node/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/handlers.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/impl/send.cljs
  src/status_im/transport/message/transit.cljs
  src/status_im/transport/message/v1/core.cljs
  src/status_im/transport/message/v1/group_chat.cljs
  src/status_im/transport/message/v1/protocol.cljs
  src/status_im/transport/shh.cljs
  src/status_im/ui/screens/add_new/styles.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/handlers.cljs
Labels: Tested - OK

#5459 Feature/abi spec
  android/app/build.gradle
  clj-rn.conf.edn
  desktop_files/package-lock.json
  desktop_files/package.json
  ios/StatusIm.xcodeproj/project.pbxproj
  mobile_files/package-lock.json
  mobile_files/package.json
  src/status_im/js_dependencies.cljs
  src/status_im/utils/ethereum/abi_spec.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/ethereum/abi_spec.cljs
Labels: tech-debt

#6022 remove unused replace-view function
  src/status_im/chat/events.cljs
  src/status_im/chat/models.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/profile/models.cljs
  src/status_im/utils/navigation.cljs
Labels: skip-manual-qa

#6032 Add web3-utils to desktop re-natal
  desktop_files/.re-natal
Labels: desktop, skip-manual-qa

#6021 [#5451] [desktop] fix flickering topic input
  src/status_im/ui/screens/desktop/main/add_new/styles.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
Labels: Tested - OK, desktop

#6031 Add re-natal commands to make prepare-desktop
  Makefile
Labels: desktop, skip-manual-qa

#5871 [TESTS] Fix for `replacement transaction underpriced`
  test/appium/support/test_rerun.py
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/account_management/test_wallet_modal.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/test_chatbot.py
  test/appium/tests/users.py
  test/appium/views/chat_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
Labels: skip-manual-qa, tests

#5996 Fix chat/topic validation
  src/status_im/ui/screens/add_new/new_chat/db.cljs
  src/status_im/ui/screens/desktop/main/add_new/styles.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  translations/en.json
Labels: Tested - OK, desktop

#6040 Fix ENVFILE variable value for dev desktop builds
  desktop/CMakeLists.txt
Labels: desktop, skip-manual-qa

#6013 [fix 6012] can't open dapps from deeplinks
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/ui/screens/add-new/models.cljs
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: Tested - OK, bug, medium-severity

#6039 [fix 6034] remove "thanks for..." popup on desktop
  src/status_im/accounts/core.cljs
Labels: Tested - OK, desktop

#6048 [fix 6047] fix bridge functions cofx position
  src/status_im/browser/core.cljs
Labels: Tested - OK, browser, bug

#6037 [#5321] chat command messages rendering
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
Labels: Tested - OK, chat, desktop

#6057 fix store-event cofx position
  src/status_im/notifications/core.cljs
Labels: bug, skip-manual-qa

#6024 [#5277] escape html tags in messages
  components/src/status_im/ui/components/react.cljs
Labels: Tested - OK, desktop

#6041 [#4728] make [Enter] button default to proceed during account creation
  src/status_im/ui/screens/accounts/create/views.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
Labels: Tested - OK, desktop, mobile-app

#5992 add python-dev to docker build image
  desktop/docker/Dockerfile
Labels: skip-manual-qa

#5912 Lokalise: Malaysian Translations update
  src/status_im/i18n.cljs
  translations/ms.json
Labels: skip-manual-qa

#6036 feature #6026 - USDC token
  resources/images/tokens/mainnet/USDC.png
  resources/images/tokens/mainnet/USDC@2x.png
  resources/images/tokens/mainnet/USDC@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#6020 Remove unnecessary fonts from our app bundle.
  android/app/src/main/assets/fonts/Avenir-Roman.ttf
  android/app/src/main/assets/fonts/Entypo.ttf
  android/app/src/main/assets/fonts/EvilIcons.ttf
  android/app/src/main/assets/fonts/FontAwesome.ttf
  android/app/src/main/assets/fonts/Foundation.ttf
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/MaterialIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/assets/fonts/Roboto-Bold.ttf
  android/app/src/main/assets/fonts/Roboto-Light.ttf
  android/app/src/main/assets/fonts/Roboto-Medium.ttf
  android/app/src/main/assets/fonts/Roboto-Regular.ttf
  android/app/src/main/assets/fonts/RobotoMono-Medium.ttf
  android/app/src/main/assets/fonts/Zocial.ttf
  ios/RobotoMono-Medium.ttf
  ios/SF-UI-Display-Medium.otf
  ios/SF-UI-Display-Regular.otf
  ios/SF-UI-Display-Semibold.otf
  ios/SF-UI-Display-Thin.otf
  ios/SF-UI-Text-Bold.otf
  ios/SF-UI-Text-Light.otf
  ios/SF-UI-Text-Medium.otf
  ios/SF-UI-Text-Regular.otf
  ios/SF-UI-Text-Semibold.otf
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/Info.plist
  src/status_im/android/platform.cljs
  src/status_im/desktop/platform.cljs
  src/status_im/ios/platform.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/views.cljs
Labels: Tested - OK

#6067 fix make android-ports command for real devices
  Makefile
Labels: skip-manual-qa
