Repository status-im/status-mobile, pull requests merged in 2018-07, with the labels that each got.

#4898 Dont scroll to bottom when content changes
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#4578 Fix key uniqueness in message history and chat list
  env/dev/figwheel.clj
  src/status_im/desktop/core.cljs
  src/status_im/transport/shh.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
Labels: Tested - OK, desktop

#4943 Don't query mailserver when from is greater than to
  src/status_im/transport/inbox.cljs
  test/cljs/status_im/test/transport/inbox.cljs
Labels: Tested - OK, chat

#5001 Use status-go develop branch
  modules/react-native-status/desktop/CMakeLists.txt
  modules/react-native-status/desktop/rctstatus.cpp
Labels: Tested - OK, desktop

#5007 Cleanup disk space after build
  Jenkinsfile.desktopbuild
Labels: desktop, jenkins, skip-manual-qa

#5010 Build macos dmg from locally copied official qt distribution
  Jenkinsfile.desktopbuild
Labels: desktop, jenkins, skip-manual-qa

#4979 bug #4963 - removed balance from asset suggestion box to prevent text…
  src/status_im/chat/views/api/choose_asset.cljs
Labels: Tested - OK

#4933 Chat messages layout fixes
  src/status_im/chat/styles/message/datemark.cljs
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK

#5008 [TESTS] Atomic transaction tests
  test/appium/support/api/network_api.py
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/__init__.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/conftest.py
  test/appium/tests/marks.py
  test/appium/tests/test_transaction.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#5034 [TESTS] Fix for profile and chats tests
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
Labels: tests

#4847 Bug/wallet recovery
  src/status_im/chat/console.cljs
  src/status_im/chat/events/receive_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/models/contact.cljs
  src/status_im/models/mailserver.cljs
  src/status_im/transport/handlers.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/inbox.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/transit.cljs
  src/status_im/transport/message/v1/contact.cljs
  src/status_im/transport/message/v1/group_chat.cljs
  src/status_im/transport/message/v1/protocol.cljs
  src/status_im/ui/screens/accounts/utils.cljs
  src/status_im/ui/screens/contacts/core.cljs
  src/status_im/ui/screens/contacts/events.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/models/contact.cljs
  test/cljs/status_im/test/transport/inbox.cljs
Labels: Tested - OK, chat, post-beta

#4953 Feature/"eth_uninstallFilter" synchronous request error [#4873]
  resources/js/web3_init.js
Labels: Tested - OK

#5017 Wrong number of collectibles in the list and they are mixed up [#4904]
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.prod
  CHANGELOG.md
  src/status_im/ui/components/svgimage.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties/events.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties/views.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptostrikers.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptostrikers/events.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptostrikers/views.cljs
  src/status_im/ui/screens/wallet/collectibles/etheremon.cljs
  src/status_im/ui/screens/wallet/collectibles/etheremon/events.cljs
  src/status_im/ui/screens/wallet/collectibles/etheremon/views.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/ui/screens/wallet/collectibles/subs.cljs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/views.cljs
  src/status_im/utils/ethereum/erc721.cljs
  src/status_im/utils/ethereum/tokens.cljs
  src/status_im/utils/http.cljs
  src/status_im/utils/money.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/http.cljs
Labels: Tested - OK

#5033 0 shown when appropriate asset selected [#4900]
  src/status_im/ui/screens/wallet/settings/views.cljs
Labels: Tested - OK

#5011 downgrade React Native to 0.53.3
  package-lock.json
  package.json
  react-native-patches/RCTUITextView.m
  src/status_im/utils/http.cljs
Labels: Tested - OK

#5045 update mailservers from DO to use Floating IPs
  src/status_im/constants.cljs
Labels: release

#5040 Clean build files
  Jenkinsfile.desktopbuild
Labels: desktop, jenkins, skip-manual-qa

#5055 [#5030 TESTS] added 10 atomic tests from `Smoke tests - phase 1`
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_wallet.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/test_browsing.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
  test/appium/views/start_new_chat_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#5029 bug #4775 - showing spinner when signing transaction
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#4990 bug #4983 - a few workarounds for blinking token transactions in history
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#5044 bug #4926 and #4806 - showing correct fiat value in /send and /reques…
  src/status_im/chat/models/message.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/chat/views/message/request_message.cljs
  src/status_im/ui/screens/currency_settings/events.cljs
  src/status_im/ui/screens/currency_settings/subs.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/utils/money.cljs
Labels: Tested - OK

#5006 Preset keychain username on desktop
  package.json
  src/status_im/utils/keychain/core.cljs
  src/status_im/utils/keychain/events.cljs
Labels: desktop

#5061 updated changelog for 0.9.22
  CHANGELOG.md
Labels: skip-manual-qa

#5065 bug #4930 - atomic navigation after error prevents send screen being …
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#5075 fixes figwheel repl for android builds on linux
  Makefile
Labels: skip-manual-qa

#5069 [#4887] fix lagging keyboard and upgrade RN to 0.55.4
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm.xcodeproj/xcshareddata/xcschemes/StatusIm.xcscheme
  package-lock.json
  package.json
  react-native-patches/RCTUITextView.m
  src/status_im/utils/http.cljs
Labels: Tested - OK

#5077 [TESTS] Fixed selecting of a picture on SauceLabs
  test/appium/views/profile_view.py
Labels: tests

#5067 bug #5057 - automatically converts recovery phrase to lowecase during…
  src/status_im/ui/screens/accounts/recover/views.cljs
Labels: Tested - OK

#5041 [TESTS] Added atomic tests for chats management and DApps
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/browsing/__init__.py
  test/appium/tests/atomic/browsing/test_browsing.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/marks.py
  test/appium/tests/test_chat_management.py
  test/appium/tests/test_transaction.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: tests

#5005 Remove obsolete input handling
  src/status_im/chat/events/input.cljs
  src/status_im/chat/screen.cljs
  src/status_im/chat/specs.cljs
  src/status_im/chat/styles/animations.cljs
  src/status_im/chat/styles/input/input.cljs
  src/status_im/chat/styles/input/parameter_box.cljs
  src/status_im/chat/styles/input/suggestions.cljs
  src/status_im/chat/views/input/input.cljs
  src/status_im/chat/views/input/send_button.cljs
  src/status_im/chat/views/input/suggestions.cljs
  src/status_im/ui/screens/db.cljs
Labels: Tested - OK, tech-debt

#4908 Share contact code
  src/status_im/translations/en.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/ui/screens/profile/events.cljs
Labels: Tested - OK, desktop

#5051 Jenkins now downloads package with correct Info.plist
  Jenkinsfile.desktopbuild
Labels: Tested - OK, desktop

#5092 [TESTS] Fixed repeated testrail ids
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
Labels: tests

#5032 Selectable text in messages
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5096 Revert to old submit behaviour
  src/status_im/chat/views/input/input.cljs
Labels: Tested - OK, bug

#5053 Fix clearing unread counter
  CHANGELOG.md
  src/status_im/chat/models.cljs
  test/cljs/status_im/test/chat/models.cljs
Labels: Tested - OK, bug

#5109 use https instead of ssh in package.json
  package-lock.json
  package.json
Labels: tech-debt

#4720 Make the iOS app Universal 🌏
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/Contents.json
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen-1.png
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen-2.png
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen1125x2436.png
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen1242x2208.png
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen750x1334-1.png
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen_640_960-1.png
  ios/StatusIm/Images.xcassets/LaunchImage.launchimage/LaunchScreen_640_960.png
  ios/StatusIm/Images.xcassets/launch_image.imageset/Contents.json
  ios/StatusIm/Images.xcassets/launch_image.imageset/launch_image.png
  ios/StatusIm/Images.xcassets/launch_image.imageset/launch_image@2x.png
  ios/StatusIm/Images.xcassets/launch_image.imageset/launch_image@3x.png
  ios/StatusIm/Info.plist
  ios/launch-image-universal.storyboard
Labels: Tested - OK

#5108 [TESTS] Added tests for logcat verification
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
Labels: tests

#4752 Add contact code/topic validation
  src/status_im/translations/en.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/add_new/new_chat/db.cljs
  src/status_im/ui/screens/add_new/new_chat/subs.cljs
  src/status_im/ui/screens/add_new/new_public_chat/subs.cljs
  src/status_im/ui/screens/desktop/main/add_new/styles.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/subs.cljs
Labels: Tested - OK, desktop

#5039 Cljs commands proposal
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/impl/transactions/styles.cljs
  src/status_im/chat/commands/protocol.cljs
  src/status_im/ui/screens/events.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
  test/cljs/status_im/test/runner.cljs
Labels: skip-manual-qa, tech-debt

#5076 [#5047] Do not show QR code scanner when camera permissions has not been granted
  src/status_im/ui/components/permissions.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/qr_scanner/events.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK

#5080 [#4931] always show only saved :name and :photo-path in my-profile
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#5121 bug #5120 - fixes crash in wallet send if collectibles are enabled
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/subs.cljs
Labels: Tested - OK

#5119 [#3931] fix Sign in: Cannot paste text within password field
  CHANGELOG.md
  src/status_im/ui/screens/accounts/login/views.cljs
Labels: Tested - OK

#5072 prevent app from crashing on "share data" click
  src/status_im/ui/screens/usage_data/views.cljs
Labels: Tested - OK, desktop

#5101 Bug/#4998 handle wrong key
  CHANGELOG.md
  src/status_im/data_store/core.cljs
  src/status_im/data_store/realm/core.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/keychain/core.cljs
  test/cljs/status_im/test/ui/screens/events.cljs
  test/cljs/status_im/test/utils/keychain/core.cljs
Labels: Tested - OK, chat

#5068 Update transactions when navigate to tx details from chat
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK

#4946 Use correct chain name if custom network added
  src/status_im/chat/events/commands.cljs
  src/status_im/chat/events/shortcuts.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/ethereum/core.cljs
Labels: Tested - OK

#5125 Update docker build to latest sdk
  docker-build/Dockerfile
  docker-build/docker-compose.yml
  project.clj
  scripts/build_no.sh
Labels: skip-manual-qa

#5126 Install gradle archives during setup.
  scripts/lib/setup/installers.sh
  scripts/setup
Labels: skip-manual-qa

#5128 [TESTS #5066] Added more tests and `smoke phase 1` mark
  test/appium/support/test_rerun.py
  test/appium/tests/atomic/__init__.py
  test/appium/tests/atomic/account_management/__init__.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/account_management/test_wallet.py
  test/appium/tests/atomic/browsing/test_browsing.py
  test/appium/tests/atomic/chats/__init__.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/__init__.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/marks.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#5137 [TESTS] Fix for logcat verifications and connection status in e2e tests
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/marks.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#5037 [Fixes #4944] Enable universal/deep links
  .env.prod
  CHANGELOG.md
  src/status_im/chat/events.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/chat/events.cljs
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: Tested - OK

#5054 [#4301] Move message timestamp to the left for right-to-left languages
  CHANGELOG.md
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/views/message/message.cljs
  test/cljs/status_im/test/chat/views/message.cljs
Labels: Tested - OK, bug, chat, design

#5102 [#4073] Fix parse-url regexp
  CHANGELOG.md
  src/status_im/chat/views/message/message.cljs
  test/cljs/status_im/test/chat/views/message.cljs
Labels: Tested - OK, bug, chat

#5090 No browsing history kept on iOS [#5078]
  resources/js/webview.js
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/v8/browser.cljs
  src/status_im/data_store/realm/schemas/account/v8/core.cljs
  src/status_im/models/browser.cljs
  src/status_im/models/browser_history.cljs
  src/status_im/ui/components/list_selection.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
  src/status_im/ui/screens/browser/db.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/navigation.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties/views.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptostrikers/views.cljs
  src/status_im/ui/screens/wallet/collectibles/etheremon/views.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/utils/http.cljs
  test/cljs/status_im/test/browser/events.cljs
  test/cljs/status_im/test/models/browser_history.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK

#5142 Set JVM heap size in gradle.properties so that dex can run in-process
  android/gradle.properties
  scripts/lib/setup/installers.sh
Labels: skip-manual-qa

#5134 Screen cut off when using ERC dEX DApp [#3131]
  CHANGELOG.md
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#5052 bug #4854 - renamed seed or passphrase to recovery phrase in all copies
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/recover/styles.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  src/status_im/ui/screens/profile/seed/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/views/profile_view.py
  test/appium/views/recover_access_view.py
Labels: Tested - OK

#5149 Disable auto backup on IOS and android
  android/app/src/main/AndroidManifest.xml
  src/status_im/data_store/core.cljs
  src/status_im/data_store/realm/core.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/fs.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  test/cljs/status_im/test/data_store/realm/core.cljs
Labels: Tested - OK, chat, security

#5161 bug #5155 - fixed the bug where every token is unknown in send command
  src/status_im/chat/events/commands.cljs
Labels: Tested - OK

#5145 update add-contact handler
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5144 adjust desktop screen dimensions
  desktop/main.cpp
Labels: Tested - OK, desktop

#5003 Introduces label component
  components/src/status_im/ui/components/react.cljs
  src/status_im/chat/screen.cljs
  src/status_im/chat/styles/message/options.cljs
  src/status_im/chat/views/message/options.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/accounts/login/styles.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/accounts/recover/styles.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  src/status_im/ui/screens/add_new/open_dapp/styles.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/intro/styles.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/network_settings/edit_network/views.cljs
  src/status_im/ui/screens/network_settings/network_details/views.cljs
  src/status_im/ui/screens/network_settings/styles.cljs
  src/status_im/ui/screens/network_settings/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/seed/styles.cljs
  src/status_im/ui/screens/profile/seed/views.cljs
  src/status_im/ui/screens/usage_data/styles.cljs
  src/status_im/ui/screens/usage_data/views.cljs
  src/status_im/ui/screens/wallet/components/styles.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/send/transaction_sent/styles.cljs
  src/status_im/ui/screens/wallet/send/transaction_sent/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/styles.cljs
  src/status_im/ui/screens/wallet/transactions/styles.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
Labels: Tested - OK, bounty

#5094 Change copy for browser options from chat link
  src/status_im/translations/en.cljs
  src/status_im/ui/components/list_selection.cljs
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/test_messaging.py
  test/appium/views/chat_view.py
Labels: Tested - OK, bounty

#5176 Complete implementation of the `/send` command + tests
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/impl/transactions/styles.cljs
  src/status_im/chat/commands/protocol.cljs
  src/status_im/chat/commands/styles/validation.cljs
  src/status_im/chat/commands/validation.cljs
  test/cljs/status_im/test/chat/commands/impl/transactions.cljs
  test/cljs/status_im/test/runner.cljs
Labels: skip-manual-qa, tech-debt

#5166 [TESTS] Added new atomic tests for Smoke phase 1 section
  test/appium/support/api/network_api.py
  test/appium/support/test_rerun.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: tests

#4738 fixes #4681
  scripts/merge-pr.sh
Labels: bounty, skip-manual-qa

#5167 update testend enodes to use floating IPs too
  src/status_im/constants.cljs
Labels: Tested - OK, devops

#5087 bug #3441 - considering gas costs when validating send transaction ag…
  CHANGELOG.md
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#5191 Full implementation of the `/request` command + tests
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/impl/transactions/styles.cljs
  test/cljs/status_im/test/chat/commands/impl/transactions.cljs
Labels: skip-manual-qa, tech-debt

#5190 [TESTS] Fixed failed e2e tests - TestFairy warning, recover phrase and others
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#5192 [TESTS] Fix test_offline_status by dismissing the welcome placeholder
  test/appium/tests/atomic/chats/test_one_to_one.py
Labels: skip-manual-qa, tests

#4893 navigate to chat user's profile
  src/status_im/ui/components/desktop/events.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
Labels: Tested - OK, desktop

#5116 [#5023] Dynamically set window window and height
  src/status_im/chat/views/message/message.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/components/qr_code_viewer/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/usage_data/styles.cljs
  src/status_im/ui/screens/usage_data/views.cljs
  src/status_im/ui/screens/wallet/choose_recipient/views.cljs
  src/status_im/utils/dimensions.cljs
Labels: Tested - OK

#5160 Round robin mailserver on failure
  src/status_im/models/mailserver.cljs
  src/status_im/transport/inbox.cljs
  test/cljs/status_im/test/models/mailserver.cljs
Labels: Tested - OK, chat

#5193 [TESTS] Fixed test for transaction message when sending funds from wallet
  test/appium/support/test_rerun.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#5143 include current commit-sha next to desktop app version
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/utils/build.clj
  src/status_im/utils/build.cljs
Labels: Tested - OK, desktop

#5133 realm and status-go generated files location
  desktop/main.cpp
  modules/react-native-status/desktop/rctstatus.cpp
Labels: Tested - OK, desktop

#5208 [TESTS] Fixed tests with relogin
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#5210 No redirect for manually edited links (for webview) [#5201]
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK, release

#5215 bug #5214 - allows empty recipient only in dapp transactions (for con…
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK, high-priority, release

#5220 Update CHANGELOG.md
  CHANGELOG.md
Labels: skip-manual-qa

#5218 [TESTS] Included test for home verification and false failures fix
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#5175 Allow to connect to any node for dev mode [#4817]
  src/status_im/constants.cljs
  src/status_im/models/network.cljs
  src/status_im/protocol/handlers.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/network_settings/edit_network/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/utils/ethereum/core.cljs
  src/status_im/utils/ethereum/eip681.cljs
  src/status_im/utils/ethereum/tokens.cljs
  test/cljs/status_im/test/accounts/events.cljs
  test/cljs/status_im/test/models/network.cljs
  test/cljs/status_im/test/utils/ethereum/core.cljs
Labels: Tested - OK

#5225 Update CHANGELOG.md
  CHANGELOG.md
Labels: release

#5216 [#5211] show welcome screen after account creation
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/recover/events.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
Labels: Tested - OK, high-priority, release

#5231 recover from rebase fail to avoid manual cleanup of git dir
  Jenkinsfile
Labels: devops

#5222 Introduce extended DApp API [#5042]
  resources/js/webview.js
  src/status_im/constants.cljs
  src/status_im/data_store/dapp_permissions.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/v9/core.cljs
  src/status_im/data_store/realm/schemas/account/v9/dapp_permissions.cljs
  src/status_im/models/browser.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/browser/db.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/utils/utils.cljs
  test/cljs/status_im/test/browser/events.cljs
Labels: Tested - OK

#5230 [TESTS] Added new atomic tests for Smoke phase 2
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/start_new_chat_view.py
  test/appium/views/wallet_view.py
Labels: tests

#5221 [#5138 #4851 #4865] periodic transaction state updates
  src/status_im/chat/events/receive_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/transactions.cljs
  src/status_im/wallet/transactions.cljs
  test/cljs/status_im/test/wallet/transactions.cljs
Labels: Tested - OK, chat, wallet

#5240 bug #4826 - fixed the issue when navigating back from sign message wi…
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK

#5252 [TESTS] Added browser refresh button test
  test/appium/tests/atomic/browsing/test_browsing.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#5247 bug #5171 - fixed incorrect amount validation in wallet request
  src/status_im/ui/screens/wallet/db.cljs
  src/status_im/ui/screens/wallet/request/events.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/wallet/db.cljs
Labels: Tested - OK

#5245 disable colors for fastlane to keep jenkins logs cleaner
  Jenkinsfile
  Jenkinsfile.fastlane.clean
  Jenkinsfile.nightly
  Jenkinsfile.nightly_fastlane
  Jenkinsfile.parameters
  Jenkinsfile.release
  Jenkinsfile.upload_release_android
  Jenkinsfile.upload_release_ios
Labels: devops

#5262 [TESTS] Removed old tests and console, added test for faucet from test DApp
  test/appium/tests/atomic/browsing/test_browsing.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/marks.py
  test/appium/tests/test_chat_management.py
  test/appium/tests/test_dapps_and_browsing.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_multiple_devices.py
  test/appium/tests/test_networks.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_sanity.py
  test/appium/tests/test_transaction.py
  test/appium/tests/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/console_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: tests

#5272 Fix fastlane builds
  Jenkinsfile.nightly_fastlane
  Jenkinsfile.release
  Jenkinsfile.upload_release_android
  Jenkinsfile.upload_release_ios
Labels: bug, skip-manual-qa

#5258 [Fix #3604] ui, screens, browser, events: deduplicate browser history
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/utils/http.cljs
  test/cljs/status_im/test/utils/http.cljs
Labels: Tested - OK, bounty

#5196 Remove autofocus from public chat screen
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
Labels: Tested - OK, bounty

#5274 prepare-for-platform.sh script doesn't remove node_modules
  scripts/prepare-for-platform.sh
Labels: skip-manual-qa

#5268 Webview loading indicator
  src/status_im/ui/screens/browser/db.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#5264 Delete obsolete code
  resources/js/bots/console/bot.js
  resources/js/bots/console/test.js
  resources/js/bots/console/translations.js
  resources/js/bots/console/web3_metadata.js
  resources/js/bots/demo_bot/bot.js
  resources/js/bots/transactor/bot.js
  resources/js/bots/transactor/translations.js
  resources/js/status.js
  src/status_im/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/protocol/handlers.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/js_resources.cljs
  test/cljs/status_im/test/utils/transducers.cljs
Labels: Tested - OK, clojure, tech-debt

#5269 Fix sending from wallet
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK, bug, e2e test blocker, high-severity, release, wallet

#5279 upgrade FastLane to 2.100.1
  Gemfile.lock
Labels: devops

#5237 [TESTS] Added error handling tests
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/browsing/test_browsing.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/contacts_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#5197 Added EasyTrade to DApps
  resources/images/contacts/easytrade.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/contacts/default_dapps.cljs
Labels: Tested - OK, dapp

#5228 [#5031] Remove additional # to chat title when it is a public chat
  src/status_im/chat/screen.cljs
Labels: Tested - OK, bounty

#5284 Leftovers from desktop branch since 9th July
  Jenkinsfile.desktopbuild
  desktop/main.cpp
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  src/status_im/ui/components/desktop/events.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/add_new/new_chat/db.cljs
  src/status_im/ui/screens/add_new/new_chat/subs.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/utils/build.clj
  src/status_im/utils/build.cljs
Labels: Tested - OK, desktop

#5289 Release minutae: bump version and update changelog.
  CHANGELOG.md
  mobile_files/VERSION
Labels: skip-manual-qa

#5291 [TESTS] False failures fix
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#5290 Allow only one wallet transactions sync running
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/wallet/transactions.cljs
Labels: Tested - OK, bug

#5256 Modal wallet
  src/status_im/chat/screen.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/styles.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
Labels: Tested - OK, wallet

#5295 Fixed icon fn definition
  src/status_im/ui/components/icons/vector_icons.cljs
Labels: Tested - OK, desktop

#5300 move PR pipeline to macos_pr nodes
  Jenkinsfile
Labels: skip-manual-qa

#5323 remove JSC jail on native side (Android, iOS)
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/JSCJail.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/Jail.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/Jail.h
  modules/react-native-status/ios/RCTStatus/Jail.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.xcodeproj/project.pbxproj
  modules/react-native-status/ios/RCTStatus/TimerJSExport.h
  modules/react-native-status/ios/RCTStatus/TimerJSExport.m
Labels: skip-manual-qa

#5325 remove STUB_STATUS_GO parameter
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.prod
  Jenkinsfile.parameters
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/native_module/impl/non_status_go_module.cljs
  src/status_im/native_module/module.cljs
  src/status_im/utils/config.cljs
Labels: skip-manual-qa

#5257 Update status-go
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
Labels: Tested - OK, status-go

#5333 Desktop switched to the same version of status-go as mobile
  modules/react-native-status/desktop/CMakeLists.txt
Labels: desktop, skip-manual-qa

#5304 [#5226] Migrate clj scripts to latest clj-rn
  Makefile
  build.clj
  clj-rn.conf.edn
  deps.edn
Labels: bounty, developer-xp

#5158 Different date/time format on "Transaction details" screen
  src/status_im/utils/datetime.cljs
  test/cljs/status_im/test/utils/datetime.cljs
Labels: Tested - OK, bounty

#5250 bugs #4724 and #5131 - fixed by adding wallet onboarding for dapp txs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/styles.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#5338 [TESTS] Changed browser refresh button locator, sign transaction method and transactions from DApps
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/send_transaction_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#5331 [#4380] Improve browser security warning
  resources/icons/lock.svg
  resources/icons/lock_opened.svg
  src/status_im/models/browser.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/components/tooltip/views.cljs
  src/status_im/ui/screens/add_new/open_dapp/views.cljs
  src/status_im/ui/screens/browser/db.cljs
  src/status_im/ui/screens/browser/default_dapps.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/utils/http.cljs
  test/cljs/status_im/test/browser/events.cljs
Labels: Tested - OK

#5305 bug #5265 - transaction history populated only with own transactions
  src/status_im/ui/screens/wallet/events.cljs
Labels: Tested - OK

#5328 adding Civitas DApp
  resources/images/contacts/civitas.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/browser/default_dapps.cljs
Labels: Tested - OK, dapp

#5322 bug #4952 - moved the wrong password tooltip a bit up to make the fie…
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK
