Repository status-im/status-mobile, pull requests merged in 2018-08, with the labels that each got.

#5352 Bump mobile version to 0.9.25
  mobile_files/VERSION
Labels: skip-manual-qa

#5351 bug #4404 - removed the 21 char limit from amount field in send and r…
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#5359 remove nfc-react-native module
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  mobile_files/package-lock.json
  mobile_files/package.json
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/ui/components/nfc.cljs
Labels: skip-manual-qa

#5349 [TESTS] Wallet modal tests
  src/status_im/chat/screen.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/wallet/views.cljs
  test/appium/tests/atomic/account_management/test_wallet_modal.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/marks.py
  test/appium/views/base_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#5373 refactor - moved main wallet screen into its own package; merged wall…
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/components.cljs
  src/status_im/ui/screens/wallet/components/styles.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/main/styles.cljs
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/styles.cljs
Labels: skip-manual-qa

#5376 [TESTS] Fixed amount validation in modal value
  test/appium/tests/atomic/account_management/test_wallet_modal.py
Labels: tests

#5370 Added references to new docs.status.im website
  README.md
Labels: skip-manual-qa

#5363 [WIP] Changed location of StatusIm.app.zip (now in git)
  Jenkinsfile.desktopbuild
Labels: Tested - OK, desktop, skip-manual-qa

#5391 Updated address for EthBerlin
  src/status_im/ui/screens/browser/default_dapps.cljs
Labels: release

#5249 added SPANK token
  resources/images/tokens/mainnet/SPANK.png
  resources/images/tokens/mainnet/SPANK@2x.png
  resources/images/tokens/mainnet/SPANK@3x.png
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/ethereum/tokens.cljs
  test/cljs/status_im/test/utils/ethereum/eip681.cljs
Labels: Tested - OK

#5384 refactor - extracted all model functions from accounts events
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/accounts/login/models.cljs
  src/status_im/ui/screens/accounts/models.cljs
  src/status_im/ui/screens/accounts/recover/events.cljs
  src/status_im/ui/screens/accounts/recover/models.cljs
  src/status_im/ui/screens/bootnodes_settings/events.cljs
  src/status_im/ui/screens/currency_settings/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/offline_messaging_settings/events.cljs
  src/status_im/ui/screens/wallet/settings/events.cljs
  test/cljs/status_im/test/ui/screens/accounts/login/events.cljs
Labels: Tested - OK

#5411 Bump `develop` version to 0.9.26 since we are submitting 0.9.25 as a …
  mobile_files/VERSION
Labels: skip-manual-qa

#5346 Improve content
  src/status_im/translations/en.cljs
Labels: Tested - OK

#5413 [TESTS] Fixed public key and chat name inputs and amount for tokens
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
Labels: tests

#5320 bug #5307 - showing new contract as recipient in contract creation tr…
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#5380 refactor - extracted all model functions from profile events
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/models.cljs
Labels: Tested - OK

#5417 [TESTS] Changed run name and TestRail report for PRs
  test/appium/support/testrail_report.py
  test/appium/tests/conftest.py
Labels: tests

#5428 [TESTS] Updated captions in tests
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/profile_view.py
  test/appium/views/transactions_view.py
  test/appium/views/wallet_view.py
Labels: tests

#5412 Update changelog for 0.9.25
  CHANGELOG.md
Labels: skip-manual-qa

#5441 [#4823] AppStoreConnect: Mark our iOS app as encryption-compliant.
  ios/StatusIm/Info.plist
Labels: skip-manual-qa

#5438 Update cljs-rn to new version
  deps.edn
Labels: developer-xp, skip-manual-qa

#4997 Improve message notifications
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/debug/res/raw/message.wav
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/app/src/main/res/raw/message.wav
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  clj-rn.conf.edn
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.h
  ios/StatusIm/AppDelegate.m
  mobile_files/package-lock.json
  mobile_files/package.json
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/android/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/ios/core.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/login/models.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/notifications.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  test/cljs/status_im/test/utils/notifications.cljs
Labels: Tested - OK, chat

#5431 Enable scroll-view rendering optimization for array of children #5012
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5453 [#5440] Add dismiss button to "Add to contacts" badge
  CHANGELOG.md
  src/status_im/chat/screen.cljs
  src/status_im/chat/styles/screen.cljs
  src/status_im/models/contact.cljs
  src/status_im/ui/screens/contacts/events.cljs
Labels: Tested - OK, chat

#5462 Set macos deployment target to 10.9
  desktop/CMakeLists.txt
Labels: desktop, skip-manual-qa

#5476 [TESTS] Fixed password in logcat verification and TestFairy warning text
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/views/base_view.py
Labels: tests

#5319 Update status-go to 0.10.0
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
  src/status_im/protocol/handlers.cljs
  src/status_im/utils/web3_provider.cljs
Labels: Tested - Issues, release

#5479 [#5465] disable realm's mixpanel analytics
  ci/Jenkinsfile.desktopbuild
  ci/Jenkinsfile.fastlane.clean
  ci/Jenkinsfile.nightly
  ci/Jenkinsfile.nightly_desktop
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.parameters
  ci/Jenkinsfile.release
  ci/Jenkinsfile.upload_release_android
  ci/Jenkinsfile.upload_release_ios
Labels: Tested - OK, desktop, mobile-app

#5480 iOS 💛 fastlane
  ci/Jenkinsfile
  ci/Jenkinsfile.fastlane.clean
  ci/Jenkinsfile.nightly
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.parameters
  ci/Jenkinsfile.release
  ci/Jenkinsfile.upload_release_ios
  fastlane/.env
  fastlane/Fastfile
  fastlane/Matchfile
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: skip-manual-qa

#5434 bug #5356 - added snackbar for wallet errors, removed ATT from defaul…
  CHANGELOG.md
  src/status_im/constants.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/v8/account.cljs
  src/status_im/data_store/realm/schemas/base/v8/core.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/main/styles.cljs
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/subs.cljs
Labels: Tested - OK

#5469 Selection color changed for desktop texts and inputs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
Labels: Tested - OK, desktop

#5471 Update changelog for 0.9.25
  CHANGELOG.md
Labels: skip-manual-qa

#5189 [#4848] ui, i18n: Replace currency indicator with ~
  src/status_im/i18n.cljs
  src/status_im/ui/screens/wallet/subs.cljs
Labels: Tested - OK, bounty

#5493 Less magic in setup new CI nodes 🧙‍♂️
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.upload_release_android
  ci/Jenkinsfile.upload_release_ios
  fastlane/Fastfile
Labels: skip-manual-qa

#5492 Fixed problem with adding new contact on desktop
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
Labels: Tested - OK, desktop

#5491 Use fastlane for diawi, slack & github comments 🌤
  ci/Jenkinsfile
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.parameters
  ci/Jenkinsfile.release
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: skip-manual-qa

#5501 Upload apk to Sauce Labs using fastlane.
  ci/Jenkinsfile
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.release
  fastlane/Fastfile
Labels: skip-manual-qa

#5335 [#5278][Android] persist webview state during session
  .env
  .env.jenkins
  mobile_files/package-lock.json
  mobile_files/package.json
  src/status_im/ui/components/webview_bridge.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK

#5460 bug #5058 - aligned words in recovery backup phrase screen
  src/status_im/ui/screens/profile/seed/styles.cljs
Labels: Tested - OK

#5512 Fix diawi upload for nightlies.
  ci/Jenkinsfile
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.parameters
  ci/Jenkinsfile.release
  fastlane/Fastfile
Labels: skip-manual-qa

#5490 Notify github for desktop builds
  ci/Jenkinsfile.desktopbuild
Labels: desktop, jenkins

#5519 Thread safe access to log messages list
  desktop/main.cpp
Labels: desktop, skip-manual-qa

#5502 Post-fastlane cleanup. Remove unnecessary plist files.
  ios/archive-develop.plist
  ios/archive-release.plist
Labels: skip-manual-qa

#5522 Remove jail + Status.js API
  doc/decisions/0010-remove-jail-and-status-api.md
Labels: skip-manual-qa

#5524 Fix Slack messages for builds.
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.parameters
  ci/Jenkinsfile.release
  ci/Jenkinsfile.upload_release_android
  ci/Jenkinsfile.upload_release_ios
Labels: skip-manual-qa

#5530 Don't lock Jenkins nodes for too long if possible (#desktop).
  ci/Jenkinsfile.desktopbuild
Labels: skip-manual-qa

#5532 [TESTS] False failures fix: assets, transaction users
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/wallet_view.py
Labels: tests

#5538 Fix keychain password for PR Jenkinsfiles
  ci/Jenkinsfile
Labels: devops, skip-manual-qa

#5377 Use time format according to 12/24h device settings
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/utils/datetime.cljs
Labels: Tested - OK, bounty

#5455 Wallet refactoring (new tx flow)
  components/src/status_im/ui/components/react.cljs
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/ios/RCTStatus/pom.xml
  resources/js/i18n.js
  resources/js/web3_init.js
  resources/js/webview.js
  src/status_im/constants.cljs
  src/status_im/models/browser.cljs
  src/status_im/models/wallet.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/db.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/send/db.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/transaction_fee/views.cljs
  src/status_im/ui/screens/wallet/transaction_sent/styles.cljs
  src/status_im/ui/screens/wallet/transaction_sent/views.cljs
  src/status_im/ui/screens/wallet/transactions/subs.cljs
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/web3_provider.cljs
  test/cljs/status_im/test/browser/events.cljs
Labels: Tested - OK, wallet

#5533 [#4932] add privacy policy to signup, recover and profile
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/about_app/views.cljs
  src/status_im/ui/screens/accounts/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/privacy_policy/events.cljs
  src/status_im/ui/screens/privacy_policy/styles.cljs
  src/status_im/ui/screens/privacy_policy/views.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/subs.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK

#5553 fixes #4108
  CHANGELOG.md
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, bounty

#5541 less noisy fastlane slack notifications
  fastlane/Fastfile
Labels: devops, skip-manual-qa

#5308 Add advanced settings UI
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/styles.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
Labels: Tested - OK, desktop

#5329 Add remove-chat button next to chat title
  components/src/status_im/ui/components/react.cljs
  components/src/status_im/ui/components/svg.clj
  env/dev/env/config.cljs
  env/dev/env/utils.cljs
  src/status_im/chat/models.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/desktop/events.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
Labels: Tested - OK, desktop

#5534 [#5439] hide passwords from accessibility services
  src/status_im/ui/screens/accounts/create/views.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#5521 [#4732] upgrade react-native-testfairy to 2.14.1
  mobile_files/package-lock.json
  mobile_files/package.json
Labels: Tested - OK

#5552 bug #3911 - fixed balance in asset field when value too long
  src/status_im/ui/screens/wallet/components/styles.cljs
Labels: Tested - OK

#5545 bug #5243 - using correct error code for image picker compononent
  components/src/status_im/ui/components/react.cljs
Labels: Tested - OK

#5555 bug #5224 - showing gas info in unconfirmed transactions
  src/status_im/models/wallet.cljs
Labels: Tested - OK

#5540 [#5467] Make app searchable with Spotlight
  ci/Jenkinsfile.desktopbuild
  ci/Jenkinsfile.nightly_desktop
  deployment/macos/Info.plist
Labels: Tested - OK, desktop

#5572 bug #5568 - correctly passing gasPrice param
  src/status_im/models/wallet.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK, release

#5544 Fixes #5293: Messaging/transacting take too long to be processed if there is a 'Pending...' tx message
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusThreadPoolExecutor.java
Labels: Tested - OK

#5470 Custom fonts loading added to desktop app
  ci/Jenkinsfile.desktopbuild
  desktop/build.bat
  desktop/build.sh
  desktop/main.cpp
  desktop_files/package-lock.json
  desktop_files/package.json
  resources/fonts/SF-Pro-Text-Light.otf
  resources/fonts/SF-Pro-Text-Medium.otf
  resources/fonts/SF-Pro-Text-Regular.otf
  src/status_im/desktop/platform.cljs
  src/status_im/ui/screens/desktop/main/add_new/styles.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/utils/platform.cljs
Labels: Tested - OK, desktop

#5536 Merge desktop and mobile builds into a single job
  .gitignore
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nightly_fastlane
  ci/Jenkinsfile.release
  ci/common.groovy
  ci/desktop.groovy
  ci/mobile.groovy
  fastlane/Fastfile
  scripts/build_no.sh
Labels: devops

#5569 moved wallet transactions ns
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/events/receive_message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/models/transactions.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  test/cljs/status_im/test/wallet/transactions.cljs
Labels: Tested - OK

#5497 [#5260] Implement web3 provider Opt-in access
  resources/icons/settings.svg
  resources/js/web3_init.js
  resources/js/webview.js
  src/status_im/constants.cljs
  src/status_im/models/browser.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/browser/db.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/browser/permissions/views.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
  test/cljs/status_im/test/browser/events.cljs
Labels: Tested - OK

#5577 Do not enable asset if its balance more than 0
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#5579 Fix/use groovy methods [skip ci]
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/android.groovy
  ci/common.groovy
  ci/desktop.groovy
  ci/ios.groovy
  ci/mobile.groovy
  fastlane/Fastfile
  scripts/build_no.sh
Labels: skip-manual-qa

#5600 Fixed desktop api for using fleet
  modules/react-native-status/desktop/CMakeLists.txt
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
Labels: Tested - OK, desktop

#5546 Now user profile can be opened from public chat
  src/status_im/ui/screens/desktop/main/chat/events.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5575 Enable emojis in desktop chat
  src/status_im/constants.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK, desktop

#5494 feature #5310 - improved validation in account recovery screen
  CHANGELOG.md
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/recover/events.cljs
  src/status_im/ui/screens/accounts/recover/models.cljs
  src/status_im/ui/screens/accounts/recover/navigation.cljs
  src/status_im/ui/screens/accounts/recover/styles.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  src/status_im/ui/screens/accounts/subs.cljs
  src/status_im/ui/screens/browser/subs.cljs
  src/status_im/utils/ethereum/core.cljs
  src/status_im/utils/ethereum/mnemonic.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/accounts/login/models.cljs
  test/cljs/status_im/test/ui/screens/accounts/recover/models.cljs
  test/cljs/status_im/test/utils/ethereum/core.cljs
  test/cljs/status_im/test/utils/ethereum/mnemonic.cljs
Labels: Tested - OK

#5614 [#5561] Add SuperRare to DApp list
  resources/images/contacts/superrare.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/browser/default_dapps.cljs
Labels: Tested - OK, dapp

#5622 [#5621] Sign in is not working in Superrare dapp
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK, release

#5615 bug #4476 - fixes reoccurrence of recovery phrase in logs
  src/status_im/ui/screens/accounts/recover/models.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  test/cljs/status_im/test/ui/screens/accounts/recover/models.cljs
Labels: Tested - OK, wallet

#5602 [fix #5599] add semaphore for recurring events
  src/status_im/models/transactions.cljs
  src/status_im/protocol/handlers.cljs
  src/status_im/protocol/models.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/semaphores.cljs
Labels: Tested - OK

#5631 Unify login flow after account recovery
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/login/navigation.cljs
  src/status_im/ui/screens/accounts/models.cljs
  src/status_im/ui/screens/accounts/recover/events.cljs
  src/status_im/ui/screens/accounts/recover/models.cljs
Labels: Tested - OK

#5627 [fix #5612 #5613] improve contact code validation
  src/status_im/ui/screens/add_new/new_chat/db.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/contacts/events.cljs
  src/status_im/utils/db.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: Tested - OK, bug

#5601 feature #5582 - added BRLN coin (mainnet)
  resources/images/tokens/mainnet/BRLN.png
  resources/images/tokens/mainnet/BRLN@2x.png
  resources/images/tokens/mainnet/BRLN@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#5651 Update changelog for 0.9.26
  CHANGELOG.md
Labels: skip-manual-qa

#5617 Implement "Save Password" functionality for iOS
  ios/Podfile.lock
  mobile_files/package-lock.json
  mobile_files/package.json
  src/status_im/i18n.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/text_input/view.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/accounts/login/models.cljs
  src/status_im/ui/screens/accounts/login/navigation.cljs
  src/status_im/ui/screens/accounts/login/styles.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/accounts/models.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/keychain/core.cljs
  test/cljs/status_im/test/ui/screens/accounts/login/models.cljs
Labels: Tested - OK

#5658 [TESTS] [skip ci] False failures fix
  test/appium/support/test_rerun.py
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_modal.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/transactions_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: tests

#5514 [TESTS] [skip ci] Added screenshots for failed tests and device number to errors
  test/appium/support/api/network_api.py
  test/appium/support/base_test_report.py
  test/appium/support/device_apps.py
  test/appium/support/github_report.py
  test/appium/support/test_data.py
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/test_message_reliability.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/transactions_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#5655 [#5449] Activity loading indicator persist staying on Android
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#5647 [FIX 4031] update realm to fix vulnerability in dependencies
  ci/download-realm.js
  fastlane/Fastfile
  mobile_files/package-lock.json
  mobile_files/package.json
Labels: Tested - OK, security

#5663 Fix desktop signin text input field
  src/status_im/ui/components/text_input/view.cljs
Labels: Tested - OK, desktop

#5690 Fix info log on logout process
  test/appium/views/profile_view.py
Labels: tests

#5689 [TESTS] [skip ci] Fixed GH report layout and limited length of errors
  test/appium/support/github_report.py
Labels: tests

#5693 Jenkins: don't build unnecessary platforms for mobile builds.
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/mobile.groovy
Labels: devops, skip-manual-qa

#5628 Fix ens resolution in "start new chat" according to latest dapp developments
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/utils/ethereum/ens.cljs
  src/status_im/utils/ethereum/stateofus.cljs
Labels: Tested - OK, bug

#5675 Feature/remove old flags
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  src/status_im/chat/models/input.cljs
  src/status_im/transport/filters.cljs
  src/status_im/transport/inbox.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/utils/universal_links/events.cljs
  test/cljs/status_im/test/chat/models/input.cljs
Labels: skip-manual-qa

#5672 Add permission descriptions for iOS.
  ios/StatusIm/Info.plist
Labels: skip-manual-qa

#5580 Feature/qtbreakpad integration
  ci/Jenkinsfile.desktopbuild
  ci/desktop.groovy
  deployment/macos/qt.conf
  desktop/CMakeLists.txt
  desktop/main.cpp
  desktop/reportApp/CMakeLists.txt
  desktop/reportApp/main.cpp
  desktop/reportApp/main.qml
  desktop/reportApp/main.qrc
  desktop/reportApp/reportpublisher.cpp
  desktop/reportApp/reportpublisher.h
  desktop_files/package.json
Labels: Tested - OK, desktop

#5696 setup: Run gradlew task even if NDK was just installed
  scripts/lib/setup/installers.sh
Labels: developer-xp, skip-manual-qa

#5697 [TESTS][skip ci] Several fixes for false failures in e2e tests
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/conftest.py
  test/appium/views/base_element.py
  test/appium/views/chat_view.py
  test/appium/views/transactions_view.py
Labels: skip-manual-qa

#5714 Add `clean` makefile target to ensure build leftover state is removed
  Makefile
  ci/desktop.groovy
  ci/mobile.groovy
  scripts/bundle-status-go.sh
Labels: skip-manual-qa

#5668 Make macOS bundle code-signable
  ci/Jenkinsfile.desktopbuild
  ci/Jenkinsfile.nightly_desktop
  ci/desktop.groovy
  deployment/macos/qt-reportApp.conf
Labels: Tested - OK, desktop, macOS

#5713 bug #5694 and #5709 - re-required request events
  src/status_im/ui/screens/events.cljs
Labels: Tested - OK

#5719 Replace `npm prune` with cleaning `node_modules/`
  Makefile
Labels: skip-manual-qa

#5707 [CI] Name of apk for e2e tests is a PR number if build is running for a PR
  ci/android.groovy
  ci/common.groovy
Labels: skip-manual-qa, tests

#5388 Extensions integration
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  deps.edn
  project.clj
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/impl/transactions/styles.cljs
  src/status_im/chat/commands/sending.cljs
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/registry.cljs
  src/status_im/models/chat.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/extensions/add/events.cljs
  src/status_im/ui/screens/extensions/add/styles.cljs
  src/status_im/ui/screens/extensions/add/subs.cljs
  src/status_im/ui/screens/extensions/add/views.cljs
  src/status_im/ui/screens/extensions/events.cljs
  src/status_im/ui/screens/extensions/styles.cljs
  src/status_im/ui/screens/extensions/subs.cljs
  src/status_im/ui/screens/extensions/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
Labels: skip-manual-qa

#5722 cljfmt formatting fix
  src/status_im/ui/screens/extensions/events.cljs
Labels: skip-manual-qa
