Repository status-im/status-mobile, pull requests merged in 2018-06, with the labels that each got.

#4545 Bug/Show onboarding for transaction from chat [#4456]
  src/status_im/chat/events/shortcuts.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/onboarding/setup/views.cljs
  test/appium/support/test_rerun.py
  test/appium/tests/test_chat_management.py
  test/appium/tests/test_transaction.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
Labels: Tested - OK

#4461 Update chat messages styling
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/chat/views/message/request_message.cljs
  src/status_im/ui/components/colors.cljs
Labels: Tested - OK

#4524 [FIX #4362] Updates App Icons
  android/app/src/main/res/ic_launcher-web.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-60@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-60@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-72.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-72@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-76.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-76@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-83.5@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Notification.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Notification@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Notification@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-40.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-40@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-40@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-50.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-50@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon@2x.png
Labels: Tested - OK, bounty

#4553 Improved new chat UI
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/styles.cljs
  src/status_im/ui/screens/add_new/styles.cljs
Labels: Tested - OK

#4575 Restore long tap for long messages
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK, bug, chat

#4562 [#4541] fix versioning on ios
  ios/scripts/set_xcode_version.sh
Labels: devops

#4468 [TESTS] Message reliability tests
  test/appium/requirements.txt
  test/appium/support/message_reliability_chart.py
  test/appium/support/network_api.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/marks.py
  test/appium/tests/test_message_reliability.py
  test/appium/tests/test_messaging.py
  test/appium/views/chat_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#4589 Allow scanning qr codes for custom bootnodes
  src/status_im/models/bootnode.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/events.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/styles.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/events.cljs
  test/cljs/status_im/test/models/bootnode.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/bootnodes_settings/edit_bootnode/events.cljs
Labels: chat, skip-manual-qa

#4560 bug #4539 - error message for failed transactions sent from chat
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#4594 [TESTS] Updated message reliability test report
  test/appium/Jenkinsfile.message_reliability
  test/appium/support/message_reliability_report.py
  test/appium/tests/base_test_case.py
Labels: tests

#4591 Allow editing/deleting custom bootnodes
  src/status_im/models/bootnode.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/events.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/styles.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/bootnodes_settings/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  test/cljs/status_im/test/models/bootnode.cljs
Labels: chat, skip-manual-qa

#4595 [TESTS] Fixed login in e2e tests
  test/appium/tests/__init__.py
  test/appium/tests/test_chat_management.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_transaction.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#4579 [fix 4574] do not send updates to pending contacts
  src/status_im/transport/message/v1/contact.cljs
Labels: Tested - OK, chat

#4599 Fixed figwheel problems in desktop build
  figwheel-bridge.js
Labels: desktop, macOS

#4603 Linux Jenkins parallel build #4352
  Jenkinsfile.desktopbuild
  deployment/linux/.env
  deployment/linux/usr/bin/.keep
  deployment/linux/usr/lib/.keep
  deployment/linux/usr/share/applications/StatusIm.desktop
  deployment/linux/usr/share/icons/hicolor/1024x1024/apps/StatusIm.png
  desktop/main.cpp
  scripts/download-package-files.sh
Labels: desktop

#4620 Added test 'sign message in DApp', increased wait time for a transaction
  test/appium/support/network_api.py
  test/appium/tests/test_dapps_and_browsing.py
  test/appium/tests/test_transaction.py
  test/appium/views/sign_in_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: tests

#4517 Features/allow specify password mailserver
  src/status_im/constants.cljs
  src/status_im/models/mailserver.cljs
  src/status_im/transport/inbox.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/offline_messaging_settings/db.cljs
  src/status_im/utils/inbox.cljs
  test/cljs/status_im/test/models/mailserver.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/inbox.cljs
  test/cljs/status_im/test/utils/inbox.cljs
Labels: Tested - OK

#4626 [TESTS] fix for find_transaction_by_unique_amount
  test/appium/support/network_api.py
Labels: tests

#4577 [fix] show connecting to peers popup when no peers at startup
  src/status_im/ui/screens/events.cljs
Labels: 099-confidence, Tested - OK

#4516 [TESTS] build and trigger for e2e tests added to release builds
  Jenkinsfile.release
Labels: jenkins, tests

#4616 Enable custom mailservers in nightly/releases
  .env.nightly
  .env.prod
Labels: Tested - OK, chat

#4572 [#4535] decode browser's uri
  src/status_im/ui/screens/browser/events.cljs
Labels: Tested - OK

#4617 Enable custom bootnodes for nightly/releases
  .env.nightly
  .env.prod
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, chat

#4618 bug #4593 - fixed gas update after default gas
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#4523 Disable group chats even in dev mode. Closes #4506
  src/status_im/transport/handlers.cljs
  src/status_im/transport/message/transit.cljs
  src/status_im/ui/screens/add_new/views.cljs
Labels: Tested - OK, group-chat

#4645 Use the private RPC client for requests to Status backend
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/JSCJail.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/Jail.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
Labels: high-priority

#4647 Rollback part of 2136fe62ce5505e14fb0eeabaf6a0c925156309c
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/JSCJail.java
  modules/react-native-status/ios/RCTStatus/Jail.m
Labels: skip-manual-qa

#4640 Text for empty chat
  resources/icons/lock.svg
  src/status_im/chat/screen.cljs
  src/status_im/chat/styles/screen.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/contacts/subs.cljs
Labels: Tested - OK, chat, to be automated

#4656 [TESTS] Message reliability tests update
  test/appium/tests/conftest.py
  test/appium/tests/test_message_reliability.py
Labels: tests

#4635 [#4588] Workaround ellipsis issue on public key in the login screen.
  src/status_im/ui/screens/accounts/styles.cljs
Labels: Tested - OK

#4649 Upgrade Instabug to 2.12.0
  package-lock.json
  package.json
Labels: Tested - OK

#4657 Make run-ios accept the simulator name
  Makefile
Labels: skip-manual-qa

#4655 [#4651] Set minimum iOS and Android versions.
  android/app/build.gradle
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: Tested - OK

#4658 Make the information sharing screen usable on tiny screens.
  src/status_im/ui/screens/usage_data/styles.cljs
Labels: Tested - OK

#4634 Add border to profile picture & style chat icon
  src/status_im/chat/models.cljs
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/styles/photos.cljs
  src/status_im/chat/styles/screen.cljs
  src/status_im/chat/views/bottom_info.cljs
  src/status_im/chat/views/photos.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/styles.cljs
  src/status_im/ui/screens/accounts/login/styles.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/accounts/styles.cljs
  src/status_im/ui/screens/accounts/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/utils/identicon.cljs
  test/cljs/status_im/test/chat/views/photos.cljs
  test/cljs/status_im/test/contacts/subs.cljs
  test/cljs/status_im/test/runner.cljs
Labels: chat

#4654 Dont run receive-whisper-messages if the user is logged out
  src/status_im/models/account.cljs
  src/status_im/transport/filters.cljs
  src/status_im/transport/handlers.cljs
  src/status_im/ui/screens/network_settings/events.cljs
  src/status_im/utils/handlers.cljs
  test/cljs/status_im/test/models/account.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/handlers.cljs
Labels: Tested - OK, chat

#4641 [#3732] Added some more mixpanel events
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/profile/subs.cljs
  src/status_im/utils/mixpanel_events.cljs
Labels: Tested - OK

#4659 Revert "Use the private RPC client for requests to Status backend when not coming from Dapps"
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
Labels: skip-manual-qa

#4674 Add DevEnvSetup and Troubleshooting docs for desktop app
  doc/desktop/DevEnvSetup.md
  doc/desktop/Troubleshooting.md
Labels: skip-manual-qa

#4685 [TESTS] Fixed e2e tests
  test/appium/tests/test_profile.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/sauce_logo.png
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#4683 [TESTS] fixed build for e2e tests in release pipeline
  Jenkinsfile.release
Labels: jenkins, tests

#4668 Dont show add-to-contacts if dapp
  src/status_im/chat/screen.cljs
  src/status_im/models/contact.cljs
  test/cljs/status_im/test/models/contact.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK

#4680 [TESTS] Added test for verification tokens data using api.ethplorer.io
  test/appium/support/api/network_api.py
  test/appium/support/api/third_parties_api.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/marks.py
  test/appium/tests/test_api.py
Labels: tests

#4642 Add DO and Ukr mailservers. Closes #4623
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
  src/status_im/constants.cljs
Labels: Tested - OK, chat, p2p

#4661 Update text input styling
  src/status_im/chat/screen.cljs
  src/status_im/chat/styles/animations.cljs
  src/status_im/chat/styles/input/input.cljs
  src/status_im/chat/styles/input/parameter_box.cljs
  src/status_im/chat/styles/input/suggestions.cljs
  src/status_im/chat/views/input/input.cljs
Labels: Tested - OK, chat

#4497 [#1228] Only enable Next button when passphrase is valid
  src/status_im/ui/screens/accounts/recover/db.cljs
  src/status_im/ui/screens/accounts/recover/views.cljs
  src/status_im/utils/ethereum/core.cljs
  test/cljs/status_im/test/utils/ethereum/core.cljs
Labels: Tested - OK

#4644 Faster seen marking
  src/status_im/chat/core.cljs
  src/status_im/chat/events.cljs
  src/status_im/chat/events/receive_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/specs.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/v7/core.cljs
  src/status_im/data_store/realm/schemas/account/v7/message.cljs
  src/status_im/data_store/user_statuses.cljs
  src/status_im/transport/handlers.cljs
  src/status_im/ui/screens/db.cljs
  test/cljs/status_im/test/chat/models/message.cljs
Labels: Tested - OK, clojure, performance

#4706 Fix script so that it works with GNU `sed`
  scripts/update-status-go.sh
Labels: skip-manual-qa

#4613 Ensure valid timestamp for all messages
  src/status_im/chat/models/message.cljs
  test/cljs/status_im/test/chat/models/message.cljs
Labels: Tested - OK, bug, clojure

#4705 Update status-go to include latest bootnodes and static peers
  modules/react-native-status/android/build.gradle
  modules/react-native-status/ios/RCTStatus/pom.xml
Labels: release, skip-manual-qa

#4703 [#4684]: Share data picture is cut on the top
  src/status_im/ui/screens/usage_data/styles.cljs
  src/status_im/ui/screens/usage_data/views.cljs
Labels: Tested - OK, release

#4686 set default ios simulator to empty string
  Makefile
Labels: skip-manual-qa

#4540 Feature/build_no with push
  Jenkinsfile.nightly_fastlane
  Jenkinsfile.release
  Jenkinsfile.upload_release_android
  Jenkinsfile.upload_release_ios
  scripts/build_no.sh
Labels: devops

#4713 [#4707] Updated public chat list
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
Labels: Tested - OK

#4704 [#4490]: Advanced button is not collapsed on Profile tab when switchi…
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#4682 feature #4065 - gas and gas price can be changed for dapp transactions
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/native_module/impl/non_status_go_module.cljs
  src/status_im/native_module/module.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#4731 Retry hash retrieval from i.diawi.com if it returns null. Fixes #3455
  Jenkinsfile
Labels: developer-xp, skip-manual-qa

#4725 Default to value if key is nil
  src/status_im/transport/inbox.cljs
  test/cljs/status_im/test/transport/inbox.cljs
Labels: Tested - OK, chat, release

#4688 Validate rpc-url when creating a custom network
  src/status_im/models/network.cljs
  src/status_im/ui/screens/network_settings/edit_network/events.cljs
  test/cljs/status_im/test/models/network.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/network_settings/edit_network/events.cljs
Labels: Tested - OK, chat

#4715 Update decimals and token names
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#4733 Mark seen when loading more
  src/status_im/chat/events.cljs
Labels: Tested - OK, bug, clojure

#4751 [TESTS] Fixed passphrase input
  test/appium/tests/test_profile.py
Labels: tests

#4742 bug #4737 and #4736 android back button issues with send
  src/status_im/chat/events.cljs
  src/status_im/chat/events/shortcuts.cljs
Labels: Tested - OK, release

#4697 [#4697] Add DAI token to tokens list
  resources/images/tokens/mainnet/DAI.png
  resources/images/tokens/mainnet/DAI@2x.png
  resources/images/tokens/mainnet/DAI@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#4750 bug #4746 - using dapp specified gas limit, but default gas price whe…
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK, release

#4711 [#4504] Sort assets alphabetically (send - asset)
  src/status_im/ui/screens/wallet/subs.cljs
Labels: Tested - OK

#4762 Bump the app version to 0.9.20
  VERSION
Labels: skip-manual-qa

#4712 bug #4402 - showing failed transactions in transaction history
  resources/icons/exclamation_mark.svg
  src/status_im/constants.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/wallet/transactions/styles.cljs
  src/status_im/ui/screens/wallet/transactions/subs.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/transactions.cljs
Labels: Tested - OK

#4761 [#4755] Keep the transaction source intact on errors/discards.
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#4749 Select random ms until users explicitly choose one
  src/status_im/constants.cljs
  src/status_im/models/mailserver.cljs
  src/status_im/models/network.cljs
  src/status_im/protocol/handlers.cljs
  src/status_im/transport/inbox.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/offline_messaging_settings/subs.cljs
  test/cljs/status_im/test/models/mailserver.cljs
  test/cljs/status_im/test/transport/core.cljs
  test/cljs/status_im/test/transport/inbox.cljs
Labels: Tested - OK, chat

#4769 [TESTS] Added message reliability offline 1-1 chat and push notifications tests
  test/appium/tests/base_test_case.py
  test/appium/tests/test_message_reliability.py
  test/appium/views/base_element.py
Labels: tests

#4777 [TESTS] Fixed accept_agreements method
  test/appium/views/base_view.py
Labels: tests

#4723 [#4663] Added collectibles and CK support
  resources/images/tokens/mainnet/CK.png
  resources/images/tokens/mainnet/CK@2x.png
  resources/images/tokens/mainnet/CK@3x.png
  resources/images/tokens/mainnet/EMONA.png
  resources/images/tokens/mainnet/EMONA@2x.png
  resources/images/tokens/mainnet/EMONA@3x.png
  resources/images/tokens/mainnet/STRK.png
  resources/images/tokens/mainnet/STRK@2x.png
  resources/images/tokens/mainnet/STRK@3x.png
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/ui/screens/wallet/collectibles/styles.cljs
  src/status_im/ui/screens/wallet/collectibles/subs.cljs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/styles.cljs
  src/status_im/ui/screens/wallet/views.cljs
  src/status_im/utils/ethereum/erc721.cljs
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#4692 New design for /send and /receive commands
  resources/icons/check.svg
  resources/icons/dots.svg
  resources/js/bots/transactor/bot.js
  src/status_im/chat/events/input.cljs
  src/status_im/chat/events/receive_message.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/chat/views/message/request_message.cljs
  src/status_im/constants.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/wallet/send/db.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/money.cljs
Labels: Tested - OK

#4776 Unit tests for mark seen functionality
  src/status_im/chat/events.cljs
  test/cljs/status_im/test/chat/events.cljs
Labels: clojure, tech-debt

#4774 Update chat messages styles
  src/status_im/chat/styles/message/datemark.cljs
  src/status_im/chat/styles/message/message.cljs
  src/status_im/chat/views/message/message.cljs
Labels: Tested - OK, bug, chat, design

#4465 Fixes #4309: Do not allow empty command to be sent
  src/status_im/chat/views/input/send_button.cljs
Labels: Tested - OK, bounty

#4758 [fix 4417] update toolbar style
  src/status_im/android/platform.cljs
  src/status_im/chat/styles/screen.cljs
  src/status_im/chat/views/toolbar_content.cljs
  src/status_im/ios/platform.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/components/common/common.cljs
  src/status_im/ui/components/common/styles.cljs
  src/status_im/ui/components/toolbar/view.cljs
Labels: Tested - OK, design

#4770 Validate minimum wei & fix decimal issue
  src/status_im/models/wallet.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  test/cljs/status_im/test/models/wallet.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK, wallet

#4576 [fix 4212] update profiles with concurrent contact-requests
  src/status_im/transport/handlers.cljs
  src/status_im/transport/message/v1/contact.cljs
  src/status_im/ui/screens/contacts/core.cljs
Labels: Tested - OK, chat

#4786 Disable geth.log in release builds. Fixes #4782
  .env.prod
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
Labels: high-priority

#4771 [#4763] prevent navigation back to transaction
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/mixpanel_events.cljs
Labels: Tested - OK

#4785 [#4667] Added support for etheremon and cryptostrikers
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptostrikers.cljs
  src/status_im/ui/screens/wallet/collectibles/etheremon.cljs
  src/status_im/ui/screens/wallet/collectibles/events.cljs
  src/status_im/ui/screens/wallet/collectibles/styles.cljs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
  src/status_im/ui/screens/wallet/events.cljs
  src/status_im/ui/screens/wallet/views.cljs
  src/status_im/utils/ethereum/core.cljs
  src/status_im/utils/ethereum/erc721.cljs
  src/status_im/utils/ethereum/tokens.cljs
  src/status_im/utils/http.cljs
Labels: Tested - OK

#4811 [TESTS] transaction tests aligned with new commands design
  test/appium/tests/test_transaction.py
  test/appium/views/chat_view.py
Labels: tests

#4766 [#4754] discard transaction on closing :wallet-send-transaction-modal
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK

#4804 [#4759] Handle back button properly after sending transaction (Android).
  src/status_im/android/core.cljs
Labels: Tested - OK

#4537 Hide send message button in group chat if user tries to spam
  .env
  .env.jenkins
  .env.nightly
  src/status_im/chat/constants.cljs
  src/status_im/chat/events.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/specs.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/input/input.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/chat/models/input.cljs
Labels: Tested - OK

#4791 Chat design implemented
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/main_tabs/styles.cljs
Labels: design, desktop

#4812 Bump version to 0.9.21
  VERSION
Labels: skip-manual-qa

#4828 Add Help Center
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/help_center/styles.cljs
  src/status_im/ui/screens/help_center/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/instabug.cljs
Labels: Tested - OK

#4798 Cap maximum number of days requested to mailserver
  src/status_im/transport/inbox.cljs
  test/cljs/status_im/test/transport/inbox.cljs
Labels: Tested - OK, chat

#4810 Check key is not empty
  src/status_im/data_store/realm/core.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/keychain.cljs
  src/status_im/utils/keychain/core.cljs
  src/status_im/utils/keychain/events.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  test/cljs/status_im/test/data_store/realm/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/keychain/core.cljs
Labels: Tested - OK, chat, security

#4740 [#4671 #4708] mainnet_rpc as default network, no mainnet warning
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.prod
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/network_settings/views.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK, release

#4840 react-native version update
  desktop/run-app.sh
  package.json
  patches/metro+0.30.2.patch
Labels: desktop

#4837 Add a temp patch fixing Korean/Chinese characters input in RN 0.55.x (iOS).
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm.xcodeproj/xcshareddata/xcschemes/StatusIm.xcscheme
  react-native-patches/RCTUITextView.m
Labels: Tested - OK

#4796 /send and /request tokens from chat 3233
  resources/js/bots/transactor/bot.js
  resources/js/bots/transactor/translations.js
  resources/js/status.js
  src/status_im/chat/events/commands.cljs
  src/status_im/chat/events/input.cljs
  src/status_im/chat/events/shortcuts.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/styles/input/input.cljs
  src/status_im/chat/subs.cljs
  src/status_im/chat/views/api/choose_asset.cljs
  src/status_im/chat/views/api/styles.cljs
  src/status_im/chat/views/message/message.cljs
  src/status_im/chat/views/message/request_message.cljs
  src/status_im/commands/utils.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/request/events.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/utils/money.cljs
  test/appium/tests/test_transaction.py
  test/appium/views/chat_view.py
Labels: Tested - OK

#4830 [#4821] send /send command before after sending transaction
  src/status_im/android/core.cljs
  src/status_im/chat/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/mixpanel_events.cljs
Labels: Tested - OK

#4834 Very small fix [#3642]: High quality welcome image
  resources/images/ui/welcome-image.png
Labels: Tested - OK

#4827 Add 6 new languages as public channels in the localized language. Closes #4753
  src/status_im/data_store/browser.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/data_store/mailservers.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/core.cljs
  src/status_im/data_store/transport.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
Labels: Tested - OK, chat

#4859 Tx failed with Out of Gas error [#4855]
  src/status_im/ui/screens/wallet/events.cljs
Labels: Tested - OK

#4833 Support remote SVG images [#4709]
  src/status_im/ui/components/svgimage.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptokitties.cljs
  src/status_im/ui/screens/wallet/collectibles/cryptostrikers.cljs
  src/status_im/ui/screens/wallet/collectibles/etheremon.cljs
  src/status_im/ui/screens/wallet/collectibles/styles.cljs
Labels: Tested - OK

#4886 [#4871] Added some more DApps
  resources/images/contacts/bounties-network.png
  resources/images/contacts/cryptopurr.png
  resources/images/contacts/dai.png
  resources/images/contacts/eth2phone.png
  resources/images/contacts/ethlend.png
  resources/images/contacts/local-ethereum.png
  resources/images/contacts/smartz.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/contacts/default_dapps.cljs
Labels: Tested - OK

#4891 bug #4890 - reverts the quickfix for vertical alignment of chat comma…
  src/status_im/chat/styles/input/input.cljs
Labels: Tested - OK

#4888 bug #4832 - not showing erc721 in transaction history as if it was erc20
  src/status_im/utils/ethereum/erc20.cljs
Labels: Tested - OK

#4872 Show mainnet warning
  .env.jenkins
  .env.nightly
  .env.prod
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/v6/account.cljs
  src/status_im/data_store/realm/schemas/base/v6/core.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/db.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/notifications.cljs
Labels: Tested - OK

#4884 Always try to assert that saved network is the one which node was act…
  src/status_im/protocol/handlers.cljs
  src/status_im/ui/screens/network_settings/events.cljs
Labels: Tested - OK, bug, wallet

#4822 include version number in desktop profile screen
  VERSION
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/utils/build.clj
  src/status_im/utils/build.cljs
Labels: Tested - OK, desktop

#4895 [TESTS] Added atomic tests for chats and sign in
  test/appium/tests/atomic/__init__.py
  test/appium/tests/atomic/chats/__init__.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/test_sign_in.py
  test/appium/tests/marks.py
  test/appium/tests/test_messaging.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#4885 bug #4876 - cleaning up failed transactions and added stricter check …
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#4838 Add token symbol to balance load fail error message
  src/status_im/ui/screens/wallet/events.cljs
Labels: Tested - OK

#4902 Disable collectibles for beta [#4899]
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#4897 [TESTS] Updated profile editing, sending transactions and getting public key in e2e tests
  test/appium/support/test_rerun.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/test_sign_in.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_transaction.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: tests

#4894 [#4874]: Specified gas price is automatically reverted to default one if open Assets or any screen to specify Recipient
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#4896 Allow user to recover unencrypted account
  src/status_im/data_store/realm/core.cljs
  src/status_im/translations/en.cljs
  src/status_im/ui/screens/accounts/events.cljs
  src/status_im/ui/screens/accounts/login/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/fs.cljs
  src/status_im/utils/keychain/events.cljs
Labels: Tested - OK

#4918 bug #4917 and #4914 - not showing message in chat after wallet send
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#4924 bug #4921 - adds a workaround for the conflicting bugs #4876 and #4755
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#4805 fix condition (was always false)
  src/status_im/android/core.cljs
Labels: skip-manual-qa

#4942 remove sent-received tracking
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.prod
  src/status_im/utils/handlers.cljs
  src/status_im/utils/mixpanel.cljs
  src/status_im/utils/mixpanel_events.cljs
Labels: skip-manual-qa

#4947 enable spam button protection setting for release builds
  .env.prod
Labels: skip-manual-qa

#4956 [TESTS] Increased time range for message sending progress bar
  test/appium/tests/atomic/chats/test_one_to_one.py
Labels: tests

#4958 Remove old code which is not used anymore
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
Labels: skip-manual-qa

#4939 Abort git rebase on Jenkins failure
  Jenkinsfile.desktopbuild
Labels: desktop, jenkins, skip-manual-qa

#4973 Add universal links for android
  .env.prod
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  src/status_im/chat/events.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/utils/universal_links/events.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: chat, skip-manual-qa

#4980 Add support for browse dapps
  src/status_im/chat/events.cljs
  src/status_im/ui/components/dialog.cljs
  src/status_im/ui/components/list_selection.cljs
  src/status_im/ui/screens/browser/events.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/events.cljs
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: chat, skip-manual-qa

#4978 don't logout on version # click
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
Labels: Tested - Issues, desktop

#4984 Remove old code which is not used anymore
  resources/js/bots/console/bot.js
  src/status_im/chat/events/commands.cljs
  src/status_im/chat/views/message/request_message.cljs
Labels: skip-manual-qa, tech-debt

#4981 build ReactNative from fork
  Jenkinsfile
  Jenkinsfile.nightly
  Jenkinsfile.nightly_fastlane
  Jenkinsfile.parameters
  Jenkinsfile.release
  Jenkinsfile.upload_release_android
  android/app/build.gradle
  android/build.gradle
  android/settings.gradle
  package-lock.json
  package.json
  scripts/run-osx
Labels: skip-manual-qa

#4985 [TESTS] Added atomic tests for chats
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_console.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/test_sign_in.py
  test/appium/tests/marks.py
  test/appium/tests/test_chat_management.py
  test/appium/tests/test_message_reliability.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_profile.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/console_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#4949 Dont use denormalized name anymore
  src/status_im/chat/screen.cljs
  src/status_im/ui/components/qr_code_viewer/styles.cljs
  src/status_im/ui/screens/home/styles.cljs
Labels: Tested - OK

#5002 [TESTS] Added atomic tests for account management
  test/appium/tests/atomic/account_management/__init__.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/account_management/test_wallet.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/test_sign_in.py
  test/appium/tests/base_test_case.py
  test/appium/tests/marks.py
  test/appium/tests/test_chat_management.py
  test/appium/tests/test_message_reliability.py
  test/appium/tests/test_messaging.py
  test/appium/tests/test_profile.py
  test/appium/tests/test_transaction.py
  test/appium/tests/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/elements_templates/sauce_logo_red.png
  test/appium/views/elements_templates/saucelabs_sauce.png
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/transactions_view.py
  test/appium/views/wallet_view.py
Labels: tests
