Repository status-im/status-mobile, pull requests merged in 2019-08, with the labels that each got.

#8684 Fix minor issues and typos in Android build process
  .gitignore
  Makefile
  android/app/build.gradle
  android/build.gradle
  nix/mobile/android/android-env.nix
  nix/mobile/android/maven-and-npm-deps/default.nix
  nix/mobile/android/maven-and-npm-deps/maven/reactnative-android-native-deps.nix
  nix/status-go/default.nix
  translations/en.json
Labels: skip-manual-qa

#8689 Upgrade gomobile
  nix/status-go/default.nix
  nix/status-go/gomobile/default.nix
  nix/status-go/gomobile/ignore-nullability-error-on-ios.patch
  nix/status-go/gomobile/ndk-search-path.patch
Labels: skip-manual-qa

#8686 ENS names: starting chat, adding own ENS to profile
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/users.py
  test/appium/views/dapps_view.py
Labels: skip-manual-qa, tests

#8692 Skipped some steps due to missing "send taransaction" and commands in 1-1
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
Labels: skip-manual-qa, tests

#8618 keycard login v1
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  resources/images/ui/keycard-key.png
  resources/images/ui/keycard-wrong.png
  resources/images/ui/not-keycard.png
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/setup/subs.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8699 Probot: Change to 1 PR reviewer required
  .github/github-bot.yml
Labels: skip-manual-qa

#8679 Move chats to status-go
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/contact/block.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/pairing/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/utils/pairing.cljs
  status-go-version.json
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/data_store/chats.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  test/cljs/status_im/test/pairing/core.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
  test/cljs/status_im/test/transport/core.cljs
Labels: Tested - OK

#8706 e2e for restoring correct address from seedpharse
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/users.py
Labels: skip-manual-qa, tests

#8695 [TESTS] Added new e2e tests
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/add_custom_token_view.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8714 Skipped some steps in e2e due to deleting commands
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: skip-manual-qa, tests

#8696 Features/move contacts
  src/status_im/contact/block.cljs
  src/status_im/contact/core.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/tribute_to_talk/whitelist.cljs
  test/cljs/status_im/test/data_store/contacts.cljs
  test/cljs/status_im/test/models/contact.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
  test/cljs/status_im/test/tribute_to_talk/whitelist.cljs
Labels: Tested - OK

#8700 Update copy 'About names'
  translations/en.json
Labels: Tested - OK

#8681 Update French, Japanese, and Korean translations
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
Labels: Tested - OK, translations

#8724 fix korean translations
  translations/ko.json
Labels: bug

#8726 disable desktop builds for now
  ci/Jenkinsfile.combined
Labels: jenkins

#8728 forgot to disable desktop stuff in other steps
  ci/Jenkinsfile.combined
Labels: jenkins

#8723 Check version format
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#8733 disable coverage
  ci/Jenkinsfile.android
Labels: skip-manual-qa

#8719 Add datasync confirmations, enable device-to-device by default
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  status-go-version.json
Labels: Tested - OK

#8732 update the Russian, Korean and Chinese translations
  translations/ko.json
  translations/ru.json
  translations/zh_Hans_CN.json
Labels: Tested - OK, translations

#8720 [TESTS] Added test for searching not used translation strings
  test/appium/tests/atomic/test_translations.py
  test/appium/tests/base_test_case.py
  test/appium/tests/marks.py
Labels: skip-manual-qa, tests

#8731 [#8666] Add account via BIP 44
  components/src/status_im/ui/components/react.cljs
  externs.js
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/signing/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/list_item/views.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/ui/screens/wallet/account/styles.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/sheets.cljs
  src/status_im/ui/screens/wallet/accounts/styles.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/custom_tokens/views.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/transactions/styles.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
  src/status_im/wallet/db.cljs
  test/cljs/status_im/test/signing/core.cljs
  translations/en.json
Labels: Tested - OK, v1 audit

#8687 Recovery v1
  .env
  .env.jenkins
  externs.js
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  resources/images/ui/keycard-logo-blue.png
  resources/images/ui/keycard-logo-gray.png
  src/status_im/ethereum/mnemonic.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/components/action_button/action_button.cljs
  src/status_im/ui/components/tooltip/styles.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/multiaccounts/recover/views.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/views.cljs
  test/appium/views/recover_access_view.py
  test/appium/views/sign_in_view.py
  test/cljs/status_im/test/ethereum/mnemonic.cljs
  test/cljs/status_im/test/multiaccounts/recover/core.cljs
  translations/en.json
Labels: Tested - OK, v1 release

#8761 Update .env.nightly
  .env.nightly
Labels: keycard, skip-manual-qa

#8737 [TESTS] Updated tests 5441, 5453, created 6221
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
Labels: skip-manual-qa, tests

#8756 don't allow overrides of TARGET_OS for startdev targets
  Makefile
Labels: skip-manual-qa

#8741 [keycard] fix NFC detection
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/components/tooltip/views.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
Labels: Tested - OK, keycard

#8767 [#8762] Dapp can't derive a wallet balance, "Not enough ETH for gas" …
  src/status_im/signing/core.cljs
Labels: Tested - OK

#8722 [8069] feature - [Profile] My profile edit and share screens
  deps.edn
  nix/lein/lein-project-deps-maven-inputs.txt
  nix/lein/lein-project-deps.nix
  project.clj
  src/status_im/ens/core.cljs
  src/status_im/ethereum/eip55.cljs
  src/status_im/popover/core.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/copyable_text.cljs
  src/status_im/ui/components/large_toolbar.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/chat/photos.cljs
  src/status_im/ui/screens/chat/styles/photos.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/models.cljs
  src/status_im/ui/screens/profile/navigation.cljs
  src/status_im/ui/screens/profile/user/sheet/views.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/identicon.cljs
  translations/en.json
Labels: Tested - OK, community

#8754 Fixed critical e2e in new profile
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/base_view.py
  test/appium/views/elements_templates/default_icon_profile.png
  test/appium/views/elements_templates/sauce_logo.png
  test/appium/views/elements_templates/sauce_logo_profile.png
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#8768 [TESTS] Added tests for multiaccount
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/elements_templates/multi_account_color.png
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8770 [TESTS] Fixed false failed tests
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/users.py
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#8779 nix: Pass target-os to nix-update-gradle script
  nix/mobile/android/maven-and-npm-deps/maven/generate-nix.sh
Labels: nix, skip-manual-qa

#8778 [TESTS] Updated test users public keys and usernames
  test/appium/tests/users.py
Labels: skip-manual-qa, tests

#8777 [TESTS] Added tests for multiaccount (recreated)
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/elements_templates/multi_account_color.png
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8773 [#8729] iOS crashes on personal_sign
  src/status_im/browser/core.cljs
Labels: skip-manual-qa

#8763 Features/move messages status go
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/db.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_content.cljs
  src/status_im/contact/block.cljs
  src/status_im/contact/core.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/message.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/pairing/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/transport/utils.cljs
  src/status_im/tribute_to_talk/whitelist.cljs
  src/status_im/ui/components/list_selection.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/utils/fx.cljs
  status-go-version.json
  test/cljs/status_im/test/chat/db.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/data_store/messages.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/core.cljs
  test/cljs/status_im/test/transport/utils.cljs
Labels: Tested - OK

#8794 [TESTS] Fixed tests with profile picture editing verifications
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/elements_templates/sauce_logo.png
  test/appium/views/elements_templates/sauce_logo_profile.png
  test/appium/views/elements_templates/sauce_logo_red_profile.png
  test/appium/views/elements_templates/saucelabs_sauce_profile.png
Labels: skip-manual-qa, tests

#8780 Fix serialization of group-chats
  src/status_im/data_store/chats.cljs
  test/cljs/status_im/test/data_store/chats.cljs
Labels: Tested - OK

#8789 remove contact-recovery
  src/status_im/contact_recovery/core.cljs
  src/status_im/data_store/contact_recovery.cljs
  src/status_im/events.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/contact-recovery/core.cljs
  test/cljs/status_im/test/i18n.cljs
  test/cljs/status_im/test/runner.cljs
  translations/en.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: skip-manual-qa

#8782 [#8548] No 'Paste' native Android option on longtap in the app input …
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/styles.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/wallet/components/styles.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK

#8785 update Korean, Russian and Chinese translations
  translations/ko.json
  translations/ru.json
  translations/zh_Hans_CN.json
Labels: translations

#8801 [fix 8795] remove mainnet is default alert
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/db.cljs
  src/status_im/notifications/core.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/i18n.cljs
  test/cljs/status_im/test/sign_in/data.cljs
  translations/en.json
  translations/es_419.json
  translations/fa.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ms.json
  translations/ne.json
  translations/pl.json
  translations/ru.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: Tested - OK

#8755 Fix back button issues on Android
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
Labels: Tested - OK

#8627 [#8624] Disable stickers in testnet
  src/status_im/stickers/core.cljs
  src/status_im/ui/screens/chat/input/input.cljs
Labels: Tested - OK, release, v1 release

#8817 ignore nix/clean.sh failures when in CI
  nix/build.sh
Labels: jenkins, nix, skip-manual-qa

#8625 Clear password input value when navigating away from login screen
  components/src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/routing/core.cljs
Labels: Tested - OK, release, v1 release

#8811 [fix 8796] big number error when adding owned ens name
  src/status_im/ens/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/ens/views.cljs
Labels: Tested - OK

#8822 Remove unused android/app/react.gradle
  Makefile
  android/app/build.gradle
  android/app/react.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/ui/components/camera.cljs
Labels: android, skip-manual-qa

#8820 [fix 8786] fix multiaccount recovery and add account
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/multiaccounts/recover/views.cljs
  test/cljs/status_im/test/multiaccounts/recover/core.cljs
Labels: Tested - OK

#8826 [TESTS] False failed tests fix
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#8816 Update Japanese translations
  translations/ja.json
Labels: Tested - OK, translations

#8824 list-item fix
  fiddle/src/fiddle/views/list_items.cljs
  src/status_im/ui/components/list_item/views.cljs
Labels: skip-manual-qa

#8833 [fix 8831] error when unblocking first blocked contact
  src/status_im/contact/block.cljs
Labels: Tested - OK

#8821 [Fix 8635] About showed "Version ()" instead of Version 0.14.0 (2019…)
  android/app/build.gradle
  ci/utils.groovy
  ios/scripts/set_xcode_version.sh
  nix/targets/jsbundle.nix
  scripts/version/build_no.sh
  scripts/version/gen_build_no.sh
  src/status_im/utils/build.clj
Labels: Tested - OK, bounty, community

#8798 datasync persistence
  src/status_im/chat/models/message.cljs
  src/status_im/pairing/core.cljs
  status-go-version.json
  test/cljs/status_im/test/pairing/core.cljs
Labels: Tested - OK

#8815 Add processing indicator when creating multiaccount
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/ui/screens/intro/views.cljs
Labels: Tested - OK

#8836 Use no backup directory
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
Labels: Tested - OK

#8839 don't go into android dir, copy results if not linking
  ci/android.groovy
  ci/nix.groovy
  nix/build.sh
Labels: android, jenkins, nix

#8838 [TESTS] Fixed e2e tests (high/medium)
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8847 [#8321] Change or remove back button from DApp browser screen
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#8855 add missing -r for cp-ing nix-build results
  ci/nix.groovy
Labels: jenkins, nix

#8850 upgrade status-go
  src/status_im/data_store/chats.cljs
  status-go-version.json
Labels: Tested - OK

#8825 [8070] feature - [Profile] My profile screens reorganisation and item…
  fiddle/src/fiddle/views/list_items.cljs
  src/status_im/ui/components/action_button/styles.cljs
  src/status_im/ui/components/common/styles.cljs
  src/status_im/ui/components/copyable_text.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/components/large_toolbar.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/components/list_item/styles.cljs
  src/status_im/ui/components/list_item/views.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/about_app/views.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/browser/open_dapp/views.cljs
  src/status_im/ui/screens/dapps_permissions/views.cljs
  src/status_im/ui/screens/help_center/views.cljs
  src/status_im/ui/screens/language_settings/views.cljs
  src/status_im/ui/screens/notifications_settings/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/signing/styles.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/sync_settings/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  translations/en.json
  translations/es_419.json
  translations/fa.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ms.json
  translations/ne.json
  translations/pl.json
  translations/ru.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: Tested - OK, bounty, community

#8859 Fix critical e2e for new profile
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#8848 validate links before opening
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/utils/security.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/security.cljs
Labels: Tested - OK

#8858 Move from componentWillMount to componentDidMount
  src/status_im/android/core.cljs
  src/status_im/desktop/core.cljs
  src/status_im/ios/core.cljs
  src/status_im/ui/components/bottom_bar/core.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/components/webview_bridge.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#8864 Fix empty contact code string errors
  src/status_im/ethereum/ens.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
Labels: Tested - OK

#8873 Fix push notifications
  src/status_im/notifications/core.cljs
Labels: Tested - OK
