Repository status-im/status-mobile, pull requests merged in 2019-01, with the labels that each got.

#7169 Simplify Linux bundle building
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  desktop/main.cpp
  scripts/build-desktop.sh
Labels: skip-manual-qa

#7038 Add desktop keyboard shortcuts
  clj-rn.conf.edn
  desktop_files/package.json.orig
  modules/react-native-desktop-shortcuts/desktop/CMakeLists.txt
  modules/react-native-desktop-shortcuts/desktop/desktopshortcuts.cpp
  modules/react-native-desktop-shortcuts/desktop/desktopshortcuts.h
  modules/react-native-desktop-shortcuts/index.js
  modules/react-native-desktop-shortcuts/package.json
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  scripts/build-desktop.sh
  src/status_im/desktop/core.cljs
  src/status_im/ui/components/desktop/shortcuts.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
Labels: Tested - OK, desktop

#7207 Fix outdated docs link
  scripts/lib/setup/installers.sh
Labels: skip-manual-qa

#7148 [#6594] Add local chats contacts data in chat command payloads
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/commands/receiving.cljs
  src/status_im/chat/commands/sending.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
Labels: Tested - OK

#7211 fix names of stages to fit what they do better
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/android.groovy
  ci/ios.groovy
Labels: jenkins

#7193 [#7192] Fix autologin switch behaviour on wrong password
  src/status_im/accounts/login/core.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK

#7137 Add send logs command
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/res/xml/file_provider_paths.xml
  desktop/CMakeModules/CompleteBundle.cmake
  desktop/CMakeModules/QtConfiguration.cmake
  desktop/reportApp/CMakeLists.txt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/events.cljs
  src/status_im/log_level/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/node/core.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/styles.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/logging/core.cljs
  translations/en.json
Labels: Tested - OK

#7206 upgrade pyyaml to 4.1 for vuln mitigation
  test/appium/requirements.txt
Labels: Tested - OK

#6616 [ANDROID #5793] enable saving password on android
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  env/dev/env/config.cljs
  ios/Podfile.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/accounts/login/styles.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/utils/keychain/core.cljs
  src/status_im/utils/platform.cljs
  translations/en.json
Labels: Tested - OK

#7232 move gh notification to post, add check for CHANGE_ID
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  ci/common.groovy
Labels: jenkins

#7195 [slow sign in] chats preloading
  src/status_im/chat/models/loading.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/realm/core.cljs
  src/status_im/events.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/filters.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK, release

#7239 [TESTS] Fix group and browser tests
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#7240 fix renaming iOS release builds
  ci/ios.groovy
Labels: jenkins, release

#7249 Fix how we get CHANGE_ID for PRs when uploading to SauceLabs
  ci/android.groovy
Labels: e2e test blocker, jenkins

#7242 [Mobile] Show status-go version on separate line in About.
  src/status_im/ui/screens/about_app/views.cljs
  src/status_im/ui/screens/profile/subs.cljs
Labels: Tested - OK

#7221 Use better label for system browser
  src/status_im/i18n.cljs
  src/status_im/ui/components/list_selection.cljs
  translations/af.json
  translations/cs.json
  translations/da.json
  translations/de.json
  translations/el.json
  translations/en.json
  translations/es.json
  translations/es_419.json
  translations/es_ar.json
  translations/es_mx.json
  translations/fa.json
  translations/fi.json
  translations/fr.json
  translations/fr_ch.json
  translations/fy.json
  translations/he.json
  translations/hi.json
  translations/hu.json
  translations/it.json
  translations/it_ch.json
  translations/ja.json
  translations/ko.json
  translations/lt.json
  translations/lv.json
  translations/ms.json
  translations/nb.json
  translations/ne.json
  translations/nl.json
  translations/pl.json
  translations/pt_br.json
  translations/pt_pt.json
  translations/ro.json
  translations/ru.json
  translations/sl.json
  translations/sr_rs_cyrl.json
  translations/sr_rs_latn.json
  translations/sv.json
  translations/th.json
  translations/tr.json
  translations/uk.json
  translations/ur.json
  translations/vi.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
  translations/zh_hant.json
  translations/zh_hant_hk.json
  translations/zh_hant_sg.json
  translations/zh_hant_tw.json
  translations/zh_wuu.json
  translations/zh_yue.json
Labels: Tested - OK

#7251 Fixed wallet settings hook screen on iphone x
  components/src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
Labels: Tested - OK

#7222 Fix `scripts/start-react-native.sh` so it can handle killing multiple processes listening on port 8081
  scripts/start-react-native.sh
Labels: skip-manual-qa

#7256 Remove misleading comment related to login flow
  src/status_im/accounts/login/core.cljs
Labels: skip-manual-qa

#7257 Kyber extension UI avoiding keyboard
  src/status_im/extensions/core.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
Labels: Tested - OK

#7183 [#7158] EIP1193 (new ethereum provider)
  resources/js/web3_opt_in.js
  src/status_im/browser/core.cljs
Labels: Tested - OK

#7218 [Fixes #7213] Properly handle universal links in status
  src/status_im/browser/core.cljs
  src/status_im/extensions/core.cljs
Labels: Tested - Issues

#7254 Report messages as "processed" to status-go only after they were stored in Realm
  src/status_im/chat/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/core.cljs
  src/status_im/events.cljs
  src/status_im/transport/message/core.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/data_store/core.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK, chat-reliability

#7149 Add ethereum/create-address event
  src/status_im/constants.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
Labels: skip-manual-qa

#7271 [TESTS] Maintenance
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/chat_view.py
Labels: skip-manual-qa, tests

#7260 Sign-in flow docs and tests
  doc/sign_in/readme.md
  doc/sign_in/sign_in_diagram.jpg
  doc/sign_in/sign_in_diagram.xml
  src/status_im/events.cljs
  src/status_im/protocol/core.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/sign_in/data.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
Labels: skip-manual-qa

#7272 ignore keys from /private/var/folders, delete-keychain after use
  scripts/sign-macos-pkg.sh
Labels: macOS, security

#7278 use nvm() wrapper in jenkins for android builds
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  ci/common.groovy
Labels: jenkins

#7241 Add Docker image for building for Android
  .gitignore
  android/app/build.gradle
  ci/Jenkinsfile.android
  ci/android.groovy
  ci/mobile.groovy
  docker/android/Dockerfile
  docker/android/Makefile
  docker/android/README.md
  docker/android/build.sh
  docker/base/Dockerfile
  docker/base/Makefile
  docker/base/README.md
  docker/linux/Dockerfile
  docker/linux/Makefile
  docker/linux/README.md
  docker/windows/Dockerfile
  docker/windows/Makefile
  docker/windows/README.md
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  scripts/build-android.sh
Labels: android

#7264 Switch desktop app to react-native-desktop 0.57.8
  desktop_files/.babelrc
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  mobile_files/.babelrc
  patches/metro+0.38.4.patch
  patches/metro+0.48.5.patch
  patches/metro-config+0.48.5.patch
  scripts/prepare-for-platform.sh
Labels: Tested - OK, desktop

#7283 Fixed incorrect parameters provided to Command#yield-control
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/commands/sending.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
Labels: extensions, skip-manual-qa

#7291 Revert "Fixed incorrect parameters provided to Command#yield-control"
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/commands/sending.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
Labels: Tested - OK, skip-manual-qa

#7268 Fix PN metadata leak, PN navigation to chat, and unexpected PNs from other accounts
  .gitignore
  Makefile
  STATUS_GO_VERSION
  android/app/proguard-rules.pro
  ci/Jenkinsfile.ios
  doc/codebase-structure-and-guidelines.md
  modules/react-native-desktop-notification/desktop/desktopnotification.cpp
  modules/react-native-desktop-notification/desktop/desktopnotification.h
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/android/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/core.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/init/core.cljs
  src/status_im/ios/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/notifications/background.cljs
  src/status_im/notifications/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/notifications/core.cljs
Labels: Tested - OK

#7280 Install nvm if no system nodejs is found
  .gitignore
  docker/linux/Dockerfile
  docker/linux/Makefile
  docker/windows/Dockerfile
  docker/windows/Makefile
  scripts/3rd-party/nvm/0.33.11/install.sh
  scripts/lib/setup/installers.sh
Labels: skip-manual-qa

#7293 Fix generating build number for mobile builds
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/common.groovy
  ci/ios.groovy
  ci/mobile.groovy
  scripts/build_no.sh
Labels: android, jenkins

#7277 Ensure all dependencies are tagged
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: skip-manual-qa

#7297 Fix dependencies reported by package-checker bot
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: skip-manual-qa

#7298 Fix merging of :message/message-persisted event
  src/status_im/chat/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/core.cljs
  src/status_im/events.cljs
Labels: skip-manual-qa

#7296 Comment out outdated dispatching of :send-seen! event
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: skip-manual-qa

#7302 change .TOOLVERSION into csv, add toolversion script
  .TOOLVERSIONS
  Makefile
  ci/common.groovy
  docker/linux/Makefile
  docker/windows/Makefile
  scripts/build-desktop.sh
  scripts/lib/setup/installers.sh
  scripts/lib/setup/packages.sh
  scripts/run-environment-check.sh
  scripts/toolversion
Labels: skip-manual-qa

#7303 Switched keychain to another tag
  desktop_files/package.json.orig
  desktop_files/yarn.lock
Labels: Tested - OK, desktop

#7279 [TESTS] Added simple upgrade test
  ci/android.groovy
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/base_test_case.py
  test/appium/tests/marks.py
  test/appium/tests/test_chatbot.py
  test/appium/tests/test_general_verifications.py
  test/appium/views/about_view.py
Labels: skip-manual-qa, tests

#7308 Moved to new pluto release
  deps.edn
  project.clj
Labels: Tested - OK, extensions

#7312 Disable sending message
  src/status_im/transport/message/protocol.cljs
Labels: skip-manual-qa

#7314 Update pods only if installation fails.
  ci/mobile.groovy
Labels: skip-manual-qa

#7319 fix `:contact.ui/close-contact-pressed` event
  src/status_im/ui/screens/chat/views.cljs
Labels: skip-manual-qa

#7324 Migrate old Infura RPC URLs to the new ones for existing accounts.
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/migrations.cljs
Labels: Tested - OK

#7223 Keycard settings screen
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  resources/icons/logout.svg
  resources/images/ui/hardwallet-card.png
  resources/images/ui/warning-sign.png
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/db.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/migrations.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/init/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/subs.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/subs.cljs
  src/status_im/ui/screens/hardwallet/settings/views.cljs
  src/status_im/ui/screens/hardwallet/setup/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/datetime.cljs
  test/cljs/status_im/test/hardwallet/core.cljs
  translations/en.json
Labels: Tested - OK, keycard

#7300 Fixed incorrect parameters provided to Command#yield-control
  src/status_im/chat/commands/core.cljs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/sending.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
  test/cljs/status_im/test/chat/commands/impl/transactions.cljs
Labels: Tested - OK, extensions

#7294 Use new status-go and rename NotifyUsers
  STATUS_GO_VERSION
  ci/Jenkinsfile.android
  docker/android/Dockerfile
  docker/android/Makefile
  ios/Podfile
  ios/Podfile.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/chat/models/message.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/node/core.cljs
  test/cljs/status_im/test/node/core.cljs
Labels: Tested - OK

#7335 Stop sending seen messages
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/chat/models/message.cljs
Labels: skip-manual-qa

#7301 [fix] remove mnemonic from current-account map
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, security

#7340 [#7274] Address and web3 authorising permission window disappears rig…
  src/status_im/ui/screens/browser/permissions/views.cljs
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK, release

#7210 Stickers market UI
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  resources/icons/clock.svg
  resources/icons/stickers.svg
  resources/icons/stickers_big.svg
  src/status_im/accounts/core.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/accounts.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/stickers/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/styles.cljs
  src/status_im/ui/screens/chat/stickers/subs.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/stickers/styles.cljs
  src/status_im/ui/screens/stickers/subs.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/ui/screens/subs.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
  translations/en.json
Labels: Tested - OK

#7269 Style header group-chats
  src/status_im/chat/db.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/realm/schemas/account/chat.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/node/core.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/ui/screens/group/add_contacts/views.cljs
  src/status_im/ui/screens/group/styles.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/node/core.cljs
  translations/en.json
Labels: Tested - OK

#7334 Get rid of StatusService.
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/ConnectorHandler.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/ServiceConnector.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusNodeEventHandler.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusService.java
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/init/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/utils/logging/core.cljs
Labels: Tested - OK

#7359 Updated support for EIP1577
  src/status_im/browser/core.cljs
Labels: browser

#7366 Enable pairing & contact recovery
  src/status_im/contact_recovery/core.cljs
  src/status_im/data_store/contact_recovery.cljs
  src/status_im/events.cljs
  src/status_im/pairing/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/contact-recovery/core.cljs
  translations/en.json
Labels: Tested - OK, release

#7373 [#7369] Can send tokens in Aragon Dapp in Finance section
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK, release

#7285 Prevent creating chats while status-go is not ready
  src/status_im/accounts/login/core.cljs
  src/status_im/init/core.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK

#7345 [FIX #7344] Update args of eth_getLogs
  src/status_im/extensions/ethereum.cljs
Labels: Tested - OK

#7381 Disable pairing pop-up in e2e
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  src/status_im/pairing/core.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK

#7375 Add pairing docs link, disable pfs toggle in release
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  src/status_im/contact_recovery/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/pairing/styles.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  translations/en.json
Labels: Tested - OK, release

#7343 Bottom sheet component
  src/status_im/ui/components/bottom_sheet/styles.cljs
  src/status_im/ui/components/bottom_sheet/view.cljs
  src/status_im/ui/components/colors.cljs
Labels: Tested - OK

#7386 Add accessibility-label for create group chat button
  src/status_im/ui/components/common/common.cljs
  src/status_im/ui/screens/group/views.cljs
  test/appium/views/chat_view.py
  test/appium/views/start_new_chat_view.py
Labels: skip-manual-qa, tests

#7388 Remove reliance on .nvmrc file and enforce node version check
  .dockerignore
  .gitignore
  scripts/lib/setup/installers.sh
  scripts/run-environment-check.sh
Labels: skip-manual-qa
