Repository status-im/status-mobile, pull requests merged in 2019-02, with the labels that each got.

#7331 Use partitioned topic for discovery
  src/status_im/contact/core.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/data_store/realm/schemas/account/transport.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/transport/chat/core.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/filters.cljs
  src/status_im/transport/impl/send.cljs
  src/status_im/transport/message/contact.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/transport/message/public_chat.cljs
  src/status_im/transport/partitioned_topic.cljs
  src/status_im/transport/shh.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  test/cljs/status_im/test/transport/core.cljs
  test/cljs/status_im/test/transport/partitioned_topic.cljs
Labels: Tested - OK

#7392 Add golang to `.TOOLVERSIONS` and fix md5 calculation
  .TOOLVERSIONS
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.windows
  docker/android/Dockerfile
  docker/android/Makefile
  docker/base/Makefile
  docker/linux/Dockerfile
  docker/linux/Makefile
  docker/windows/Dockerfile
  docker/windows/Makefile
Labels: skip-manual-qa

#7407 feature #7266 - added buff token on xdai sidechain
  resources/images/tokens/xdai/BUFF.png
  resources/images/tokens/xdai/BUFF@2x.png
  resources/images/tokens/xdai/BUFF@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK, release

#7420 fix Filter is nil error after re-login
  src/status_im/transport/core.cljs
Labels: skip-manual-qa

#7423 Update and migrate POA network URLs.
  src/status_im/constants.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/data_store/realm/schemas/base/migrations.cljs
Labels: Tested - OK, release

#7415 Increase mailserver page size 10 times to make initial sync faster.
  src/status_im/mailserver/core.cljs
Labels: release

#7406 Fix blank screen
  desktop_files/package.json.orig
  desktop_files/yarn.lock
Labels: Tested - OK, desktop

#7387 [#6587] IPFS hosted apps should not share cookies/etc
  clj-rn.conf.edn
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  src/status_im/browser/core.cljs
  src/status_im/js_dependencies.cljs
Labels: Tested - OK

#7425 [#7422] Show feedback on mailserver error
  src/status_im/mailserver/core.cljs
  src/status_im/utils/utils.cljs
  translations/en.json
Labels: Tested - OK, high-priority, release

#7341 [#7006] login with keycard
  STATUS_GO_VERSION
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/accounts/login/core.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/accounts/styles.cljs
  src/status_im/ui/screens/accounts/subs.cljs
  src/status_im/ui/screens/accounts/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/hardwallet/connect/subs.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/login/styles.cljs
  src/status_im/ui/screens/hardwallet/login/views.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/subs.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/views.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  src/status_im/ui/screens/views.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
  translations/en.json
Labels: Tested - OK, high-priority, keycard

#7429 Fixed desktop build and tests
  clj-rn.conf.edn
  desktop_files/package.json.orig
  desktop_files/yarn.lock
Labels: skip-manual-qa

#7405 [#5584] Implement Manage permissions screen and option for web3 provi…
  resources/icons/dapp.svg
  src/status_im/browser/permissions.cljs
  src/status_im/data_store/dapp_permissions.cljs
  src/status_im/events.cljs
  src/status_im/ui/components/common/common.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/components/list_item/styles.cljs
  src/status_im/ui/components/list_item/views.cljs
  src/status_im/ui/components/toolbar/styles.cljs
  src/status_im/ui/screens/browser/permissions/views.cljs
  src/status_im/ui/screens/chat/photos.cljs
  src/status_im/ui/screens/dapps_permissions/styles.cljs
  src/status_im/ui/screens/dapps_permissions/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/image.cljs
  test/cljs/status_im/test/chat/views/photos.cljs
  translations/en.json
Labels: Tested - OK, high-priority

#7414 Retry mailserver request with cursor
  src/status_im/mailserver/core.cljs
Labels: release

#7439 Feature/adjust mailserver limit
  src/status_im/mailserver/core.cljs
Labels: Tested - OK

#7434 [#7374] stickers polishing
  src/status_im/events.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/stickers/styles.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/stickers/subs.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/utils/navigation.cljs
Labels: Tested - OK

#7396 [ui only] Mobile network bottom sheet
  src/status_im/network/core.cljs
  src/status_im/ui/components/bottom_sheet/core.cljs
  src/status_im/ui/components/bottom_sheet/db.cljs
  src/status_im/ui/components/bottom_sheet/events.cljs
  src/status_im/ui/components/bottom_sheet/subs.cljs
  src/status_im/ui/components/bottom_sheet/view.cljs
  src/status_im/ui/components/checkbox/view.cljs
  src/status_im/ui/components/lists/cell/styles.cljs
  src/status_im/ui/components/lists/cell/view.cljs
  src/status_im/ui/components/styles.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/mobile_network_settings/style.cljs
  src/status_im/ui/screens/mobile_network_settings/view.cljs
  src/status_im/ui/screens/views.cljs
  translations/en.json
Labels: skip-manual-qa

#7398 Fix null is not an object error for invalid URLs
  src/status_im/browser/core.cljs
Labels: Tested - OK

#7431 fix :request/attempts typo
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/db.cljs
Labels: skip-manual-qa

#7448 Dont setup topic as it resets the discovery filter
  src/status_im/group_chats/core.cljs
  test/cljs/status_im/test/group_chats/core.cljs
Labels: skip-manual-qa

#7443 [fix] public chat icon when following link from private chat
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
Labels: chat

#7450 [fix] show first letter of public chat name in icon instead of #
  src/status_im/ui/components/chat_icon/screen.cljs
Labels: chat

#7261 [#6973] Replace react-native-i18n with react-native-languages
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  scripts/build-desktop.sh
  src/status_im/android/core.cljs
  src/status_im/i18n.cljs
  src/status_im/ios/core.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
Labels: Tested - OK

#7444 Stickers polishing 2
  resources/icons/stickers/recent.svg
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/stickers/views.cljs
Labels: Tested - OK, sticker

#7328 [#6596] Add a component to access local camera
  components/src/status_im/ui/components/react.cljs
  src/status_im/extensions/camera.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/views.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/ui/components/action_sheet.cljs
  src/status_im/ui/components/dialog.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/models.cljs
  src/status_im/ui/screens/profile/photo_capture/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/image_processing.cljs
  translations/en.json
Labels: Tested - OK

#7403 EIP55
  src/status_im/i18n.cljs
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/utils/ethereum/eip55.cljs
  test/appium/tests/users.py
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/ethereum/eip55.cljs
  translations/en.json
Labels: Tested - OK

#7267 Fix chat colors and username display
  resources/icons/tiny/tiny_pending.svg
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/chat/commands/impl/transactions/styles.cljs
  src/status_im/ui/components/icons/vector_icons.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/input/input.cljs
  src/status_im/ui/screens/chat/styles/input/suggestions.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/desktop/main/chat/styles.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - Issues

#7228 bump mobile version to 0.9.34
  mobile_files/VERSION
Labels: skip-manual-qa

#7473 Fix autotest
  test/appium/tests/atomic/chats/test_commands.py
Labels: tests

#7469 [fix] crash with creation and invitation to 1 letter group chat
  src/status_im/ui/components/chat_icon/screen.cljs
Labels: Tested - OK, chat

#7466 [fix] restore large bubble width
  src/status_im/ui/screens/chat/styles/message/message.cljs
Labels: chat

#7442 Change behavior of all-filters-added
  src/status_im/transport/db.cljs
Labels: Tested - OK

#7470 Fixed browser loader
  src/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK

#6914 Use gomobile binaries
  Makefile
  STATUS_GO_VERSION
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusNodeEventHandler.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusService.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
Labels: skip-manual-qa

#7287 Change App ID for PR builds of Android app
  android/app/build.gradle
  android/app/src/debug/res/values/strings.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/pr/AndroidManifest.xml
  android/app/src/pr/google-services.json
  android/app/src/pr/res/values/strings.xml
  android/app/src/release/res/values/strings.xml
  ci/android.groovy
  fastlane/Fastfile
Labels: jenkins, security

#7342 Publish contact updates & contact code periodically
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/update/core.cljs
  src/status_im/accounts/update/publisher.cljs
  src/status_im/chat/models.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact_code/core.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/models/transactions.cljs
  src/status_im/pairing/core.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/filters.cljs
  src/status_im/transport/impl/send.cljs
  src/status_im/transport/shh.cljs
  src/status_im/utils/async.cljs
  src/status_im/utils/fx.cljs
  src/status_im/utils/publisher.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/contact_code/core.cljs
  test/cljs/status_im/test/models/contact.cljs
  test/cljs/status_im/test/pairing/core.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK

#7447 [#7445] Sticker detail view in chat
  src/status_im/chat/models/input.cljs
  src/status_im/events.cljs
  src/status_im/stickers/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/stickers/subs.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK, sticker

#7383 Add sender name in PNs (if db is unlocked)
  deps.edn
  src/status_im/notifications/core.cljs
  translations/en.json
  translations/es_419.json
  translations/fa.json
  translations/ko.json
  translations/ms.json
  translations/ne.json
  translations/pl.json
  translations/ru.json
  translations/zh_Hans_CN.json
Labels: Tested - OK

#7482 [fix] icon and text alignment for group and public chat on home
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: chat, skip-manual-qa

#7480 Added contacts/all event and wallet.settings lifecycle hooks
  src/status_im/extensions/camera.cljs
  src/status_im/extensions/core.cljs
  src/status_im/ui/screens/chat/input/parameter_box.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/utils/ethereum/core.cljs
Labels: Tested - OK

#7284 Expose whisper (shh) events #7076
  src/status_im/constants.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/ethereum.cljs
Labels: Tested - OK

#7457 [fix 6850] add to contact appears briefly when joining public chat
  src/status_im/chat/db.cljs
  src/status_im/chat/subs.cljs
  src/status_im/contact/subs.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/group_chats/db.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  test/cljs/status_im/test/chat/db.cljs
Labels: Tested - OK, chat

#7481 [fix] ios checkbox
  src/status_im/ui/components/checkbox/styles.cljs
  src/status_im/ui/components/checkbox/view.cljs
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/components/contact/styles.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/mobile_network_settings/view.cljs
  src/status_im/ui/screens/network_settings/edit_network/views.cljs
  test/appium/views/wallet_view.py
Labels: Tested - OK, chat, design

#7433 Loading history on mobile network
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/login/core.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/init/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/network/core.cljs
  src/status_im/ui/components/bottom_sheet/events.cljs
  src/status_im/ui/components/bottom_sheet/view.cljs
  src/status_im/ui/components/connectivity/subs.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/components/lists/cell/view.cljs
  src/status_im/ui/screens/mobile_network_settings/events.cljs
  src/status_im/ui/screens/mobile_network_settings/sheets.cljs
  src/status_im/ui/screens/mobile_network_settings/sheets_styles.cljs
  src/status_im/ui/screens/mobile_network_settings/style.cljs
  src/status_im/ui/screens/mobile_network_settings/utils.cljs
  src/status_im/ui/screens/mobile_network_settings/view.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/views.cljs
  translations/en.json
Labels: Tested - OK

#7350 [TESTS] Update e2e tests to run on Android 8
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/base_test_case.py
  test/appium/views/base_view.py
  test/appium/views/elements_templates/sauce_logo.png
  test/appium/views/elements_templates/sauce_logo_red.png
  test/appium/views/elements_templates/saucelabs_sauce.png
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#7389 Fetch messages from mailserver upon PN if db is unlocked. Part of #3451
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/notifications/core.cljs
Labels: Tested - OK

#7382 Communicate with bootnodes, mailservers and whisper nodes by :443 (staging, test, beta)
  resources/config/fleets.json
Labels: Tested - OK

#7496 Routing refactoring, preparations related to new navigation
  .env
  .env.jenkins
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/config.cljs
Labels: skip-manual-qa

#7426 Allow multiple push notifications
  src/status_im/accounts/update/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/device_info.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/data_store/realm/schemas/account/contact.cljs
  src/status_im/data_store/realm/schemas/account/contact_device_info.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/installation.cljs
  src/status_im/events.cljs
  src/status_im/pairing/core.cljs
  src/status_im/transport/message/contact.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/pairing.cljs
  src/status_im/transport/message/transit.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/contacts/device_info.cljs
  test/cljs/status_im/test/models/contact.cljs
  test/cljs/status_im/test/pairing/core.cljs
  test/cljs/status_im/test/runner.cljs
Labels: Tested - OK

#7503 Enable new routing, remove old code
  .env
  .env.jenkins
  src/status_im/models/wallet.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/config.cljs
Labels: skip-manual-qa

#7510 fix mobile-network-stop-syncing-details label
  translations/en.json
Labels: skip-manual-qa

#7514 open-url extension event
  src/status_im/extensions/core.cljs
Labels: extensions

#7494 Do not navigate-back when selecting from gallery
  src/status_im/extensions/camera.cljs
  src/status_im/extensions/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/utils/image_processing.cljs
Labels: Tested - OK, extensions

#7509 fix No second Wallet screen when send two Tx one after another in Dapps
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: skip-manual-qa

#7505 Selecting users when creating group chat e2e tests fix
  test/appium/views/start_new_chat_view.py
Labels: skip-manual-qa, tests

#7475 Use dedup-id instead of raw-object
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  src/status_im/chat/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/protocol.cljs
Labels: skip-manual-qa

#7517 Custom network and seen status autotests fix
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
Labels: skip-manual-qa, tests

#7519 Add tests for send two tx in Dapp
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/users.py
  test/appium/views/send_transaction_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#7452 [#7451] Stickers support on desktop
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
Labels: Tested - OK, desktop, sticker

#7524 Handle mailserver request error
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
Labels: Tested - OK

#7523 Update bundle script
  scripts/bundle-status-go.sh
Labels: skip-manual-qa

#6529 ULC mode for Ropsten
  src/status_im/constants.cljs
  src/status_im/node/core.cljs
Labels: LES, Tested - OK

#7532 Fix block contact db error
  src/status_im/data_store/contacts.cljs
Labels: skip-manual-qa

#7530 Fix 7521
  src/status_im/notifications/core.cljs
Labels: Tested - OK, skip-manual-qa

#7485 [#7455] Added WBTC token
  resources/images/tokens/mainnet/WBTC.png
  resources/images/tokens/mainnet/WBTC@2x.png
  resources/images/tokens/mainnet/WBTC@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK

#7483 new bottom nav (react-navigation)
  src/status_im/accounts/login/core.cljs
  src/status_im/chat/subs.cljs
  src/status_im/ui/components/bottom_bar/core.cljs
  src/status_im/ui/components/bottom_bar/styles.cljs
  src/status_im/ui/components/desktop/tabs.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/transactions/styles.cljs
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/views/base_view.py
Labels: Tested - OK

#7538 Ttt/fix numpad
  src/status_im/ui/screens/profile/tribute_to_talk/styles.cljs
  src/status_im/ui/screens/profile/tribute_to_talk/views.cljs
Labels: chat, skip-manual-qa, ttt

#7535 Don't override denormalized last-clock-value on messages
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/utils/clocks.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/utils/clocks.cljs
Labels: Tested - OK

#7544 Add back :mobile-network-settings route
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
Labels: skip-manual-qa

#7539 [fix 5772] overlap in login screen on small screens
  src/status_im/ui/screens/accounts/login/views.cljs
Labels: Tested - OK, login

#7533 Do not expect messages after join group chat
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
Labels: skip-manual-qa, tests

#7502 renamed deposit to receive on main wallet screen
  src/status_im/ui/screens/wallet/main/views.cljs
Labels: Tested - OK

#7243 Enable mailserver confirmations in all builds.
  .env
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
  STATUS_GO_VERSION
  desktop_files/package.json.orig
  desktop_files/yarn.lock
Labels: Tested - OK, chat-reliability

#7542 attempt to fix status bar
  components/src/status_im/ui/components/react.cljs
  src/status_im/ui/components/status_bar/styles.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK

#7516 [#6703] Stickers UI and contract wedding
  src/status_im/browser/core.cljs
  src/status_im/constants.cljs
  src/status_im/events.cljs
  src/status_im/stickers/core.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/stickers/subs.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/utils/ethereum/abi_spec.cljs
  src/status_im/utils/ethereum/erc20.cljs
  src/status_im/utils/ethereum/stickers.cljs
Labels: Tested - OK, sticker

#7548 remove mounting of /dev/fuse for linux builds
  ci/Jenkinsfile.linux
  scripts/build-desktop.sh
Labels: jenkins

#7567 Keep message list rendered while switching between tabs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, skip-manual-qa

#7569 Set #FFFFFF as default background color on Android
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
Labels: Tested - OK, skip-manual-qa

#7563 remove main-tabs ns
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/main_tabs/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/wallet/main/views.cljs
Labels: Tested - OK, skip-manual-qa

#7460 [#7217] check card state before installation
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  resources/icons/main/keycard.svg
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/init/core.cljs
  src/status_im/ui/screens/hardwallet/components.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/views.cljs
  src/status_im/ui/screens/hardwallet/setup/styles.cljs
  src/status_im/ui/screens/hardwallet/setup/subs.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#7574 Add configurable e2e tests kickoff project board column name
  .github/github-bot.yml
Labels: skip-manual-qa

#7543 Retry mailserver request when initial request fails
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
Labels: Tested - OK, release

#7580 Show status-go version again.
  STATUS_GO_VERSION
  src/status_im/web3/core.cljs
Labels: Tested - OK, release

#7585 fix empty geth.log on iOS and Android
  STATUS_GO_VERSION
Labels: Tested - OK, release

#7576 Convert address to checksum address before testing for eip55
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/utils/ethereum/core.cljs
Labels: Tested - OK, release

#7587 bump version to 0.10.0
  mobile_files/VERSION
Labels: release, skip-manual-qa

#7586 Dont change mailserver if no network
  src/status_im/mailserver/core.cljs
  test/cljs/status_im/test/mailserver/core.cljs
Labels: Tested - OK, release

#7578 [#7537] fix Contact stuck on login screen
  src/status_im/init/core.cljs
Labels: Tested - OK, release

#7526 Confirm pairing messages
  src/status_im/pairing/core.cljs
  test/cljs/status_im/test/pairing/core.cljs
Labels: skip-manual-qa

#7555 Remove separate topic in group chats
  src/status_im/group_chats/core.cljs
  src/status_im/transport/message/public_chat.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/group_chats/core.cljs
Labels: skip-manual-qa

#7556 Add network info in about, with copy to clipboard
  src/status_im/events.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/utils.cljs
  src/status_im/ui/screens/about_app/styles.cljs
  src/status_im/ui/screens/about_app/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/desktop/main/views.cljs
  src/status_im/ui/screens/desktop/views.cljs
  src/status_im/ui/screens/subs.cljs
  translations/en.json
Labels: Tested - OK, release

#7511 [feature] search chats
  src/status_im/search/subs.cljs
  src/status_im/ui/components/list/styles.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/subs.cljs
  src/status_im/ui/screens/home/views.cljs
  test/cljs/status_im/test/search/core.cljs
  translations/en.json
Labels: Tested - OK, chat

#7575 Replace react-navigation-stack with fork without default background color
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: Tested - OK

#7597 Fix separate topic
  src/status_im/group_chats/core.cljs
Labels: skip-manual-qa

#7592 android: don't crash on invalid URLs
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: Tested - OK, android

#7604 settings: fix a typo in dapps permissions label
  translations/en.json
Labels: skip-manual-qa

#7603 [refactor] remove triple import
  src/status_im/ui/components/common/common.cljs
Labels: refactoring, skip-manual-qa

#7602 remove (unused) react-native-level-fs
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: security, skip-manual-qa

#7606 remove print statement
  src/status_im/ui/screens/home/views.cljs
Labels: skip-manual-qa

#7614 avoid running pod while there's another instance running
  Makefile
  ci/mobile.groovy
  scripts/wait-for.sh
Labels: jenkins, skip-manual-qa

#7607 revert Replace react-navigation-stack with fork without default background color
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: skip-manual-qa

#7613 ci: don't rebase release branches on `develop`
  ci/mobile.groovy
Labels: jenkins, skip-manual-qa

#7593 Add tests create acc with special chars pass
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/users.py
  test/appium/views/sign_in_view.py
Labels: skip-manual-qa, tests

#7608 fix arrow alignment
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/chat/styles/input/send_button.cljs
Labels: chat, skip-manual-qa

#7609 fix my name
  .mailmap
Labels: skip-manual-qa

#7601 Fix concurrent retry-request
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
  test/cljs/status_im/test/mailserver/core.cljs
Labels: Tested - OK
