Repository status-im/status-mobile, pull requests merged in 2019-12, with the labels that each got.

#9553 [#9543] Signing phrase popup minor fix
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
Labels: Tested - OK, design-review, request-manual-qa

#9541 [#9354] Unlock keycard account without card
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/nfc.cljs
  src/status_im/multiaccounts/biometric/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/biometric/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/keycard/styles.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/multiaccounts/recover/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/keychain/core.cljs
  translations/en.json
Labels: Tested - OK, design-review, keycard, request-manual-qa

#9567 [#9550] Improve stickers usage experience
  src/status_im/events.cljs
  src/status_im/stickers/core.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/utils/contenthash.cljs
Labels: Tested - OK, request-manual-qa

#9569 add optional TR_CASE_IDS argument to e2e PR tests
  ci/tests/Jenkinsfile.e2e-prs
Labels: jenkins, tests

#9572 Fix keycard account unlocking on disabled bioauth
  src/status_im/multiaccounts/login/core.cljs
Labels: Tested - OK, request-manual-qa

#9582 fixes for RN upgrade
  android/app/build.gradle
  nix/mobile/android/maven-and-npm-deps/default.nix
Labels: nix

#9563 Add ENS name resolution to EIP681 support
  src/status_im/ethereum/eip681.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  test/cljs/status_im/test/ethereum/eip681.cljs
Labels: Tested - OK, community, request-manual-qa

#9587 Fix wallet tests
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#9591 Suppress lifecycle warnings after RN upgrade
  src/status_im/core.cljs
Labels: developer-xp

#9547 Move processing of messages in status-go & introduce protobuf
  externs.js
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NewMessageSignalHandler.java
  src/status_im/chat/models.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_list.cljs
  src/status_im/constants.cljs
  src/status_im/contact/block.cljs
  src/status_im/contact/db.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/ens/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/topics.cljs
  src/status_im/pairing/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/transport/utils.cljs
  src/status_im/tribute_to_talk/whitelist.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/utils/clocks.cljs
  src/status_im/utils/fx.cljs
  src/status_im/utils/utils.cljs
  status-go-version.json
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/data_store/chats.cljs
  test/cljs/status_im/test/data_store/messages.cljs
  test/cljs/status_im/test/group_chats/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/utils.cljs
  test/cljs/status_im/test/tribute_to_talk/whitelist.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#9581 [#9577] Fix keycard account creation after card reconnection
  src/status_im/hardwallet/core.cljs
Labels: Tested - OK, keycard, request-manual-qa

#9594 Waiting for allow_button until checking absence of element
  test/appium/views/home_view.py
Labels: tests

#9595 Fix builds with local status-go override
  Makefile
  nix/status-go/build-mobile-status-go.nix
  nix/status-go/default.nix
Labels: nix

#9438 Calls to gfycat and identicon made async in few places
  externs.js
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  src/status_im/chat/models.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/photos.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/utils/gfycat/core.cljs
  src/status_im/utils/identicon.cljs
Labels: desktop-new

#9603 Another tiny fixes to e2e
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#9623 Formatted text in 'From' field
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
Labels: tests

#9602 fix 9597 mailserver when login offline
  src/status_im/mailserver/core.cljs
Labels: Tested - OK

#9634 Added junitxml report back
  test/appium/pytest.ini
Labels: tests

#9628 [#9573] Fix some password saving bugs
  project.clj
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/biometric/views.cljs
  test/cljs/status_im/test/multiaccounts/login/core.cljs
  test/cljs/status_im/test/runner.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#9645 Refresh token balances after adding custom token
  src/status_im/wallet/core.cljs
Labels: Tested - OK, community, request-manual-qa

#9647 [#9596] Fix biometric auth popover styles
  src/status_im/ui/screens/biometric/views.cljs
  translations/en.json
Labels: design-review

#9642 [#9583] Overlapping with system bar on "Send transaction" screen (LG …
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK, request-manual-qa

#9659 fix failure due to superfluous slashes in path
  nix/tools/mkFilter.nix
Labels: nix

#9656 [#9649] Add "Send" button and a QR icon on the wallet screen
  src/status_im/subs.cljs
  src/status_im/ui/screens/wallet/accounts/styles.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: Tested - OK, request-manual-qa

#9638 [#9636] Remove chat menu item and toggle app switching privacy on by …
  .env.e2e
  src/status_im/constants.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/add_new/db.cljs
  src/status_im/ui/screens/add_new/events.cljs
  src/status_im/ui/screens/add_new/models.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/ui/screens/add-new/models.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#9663 use accounts rpc endpoints
  src/status_im/ethereum/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/db.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/network/net_info.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/account_settings/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/send/sheets.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet/core.cljs
  status-go-version.json
Labels: v1 release

#9673 do not store mnemonic on recovered accounts
  src/status_im/hardwallet/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/db.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/wallet/accounts/sheets.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  test/cljs/status_im/test/multiaccounts/update/core.cljs
  test/cljs/status_im/test/sign_in/data.cljs
Labels: v1 release

#9687 [#9682] Rename the Dapps tab to Browser
  android/app/src/main/res/drawable-hdpi/browser.png
  android/app/src/main/res/drawable-mdpi/browser.png
  android/app/src/main/res/drawable-xhdpi/browser.png
  android/app/src/main/res/drawable-xxhdpi/browser.png
  android/app/src/main/res/drawable-xxxhdpi/browser.png
  ios/StatusIm/Images.xcassets/browser.imageset/browser.png
  ios/StatusIm/Images.xcassets/browser.imageset/browser@2x.png
  ios/StatusIm/Images.xcassets/browser.imageset/browser@3x.png
  src/status_im/ui/components/tabbar/core.cljs
Labels: Tested - OK, request-manual-qa

#9698 Fix e2e update Dapps to Browser
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
Labels: tests

#9691 integrate status-go fix for keycard accounts
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/native_module/core.cljs
  status-go-version.json
Labels: Tested - OK, v1 release

#9711 Topbar. First iteration
  fiddle/deps.edn
  fiddle/src/fiddle/views/main.cljs
  fiddle/src/fiddle/views/toolbar.cljs
  fiddle/src/fiddle/views/topbar.cljs
  src/status_im/network/ui/edit_network/views.cljs
  src/status_im/network/ui/network_details/views.cljs
  src/status_im/network/ui/views.cljs
  src/status_im/ui/components/toolbar/view.cljs
  src/status_im/ui/components/topbar.cljs
  src/status_im/ui/screens/about_app/views.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/bootnodes_settings/views.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/currency_settings/views.cljs
  src/status_im/ui/screens/dapps_permissions/views.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/fleet_settings/views.cljs
  src/status_im/ui/screens/hardwallet/authentication_method/views.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/views.cljs
  src/status_im/ui/screens/help_center/views.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/language_settings/views.cljs
  src/status_im/ui/screens/log_level_settings/views.cljs
  src/status_im/ui/screens/mobile_network_settings/view.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/notifications_settings/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/profile/photo_capture/views.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/ui/screens/sync_settings/views.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/account_settings/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
  src/status_im/ui/screens/wallet/custom_tokens/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK, request-manual-qa

#9718 Watch-only accounts test and additional waiting when signing transaction
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#9726 Extended existing e2e with new checks
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/profile_view.py
Labels: tests

#9721 Remove balances for deleted watch account
  src/status_im/wallet/accounts/core.cljs
Labels: Tested - OK, community

#9727 Fix alert dismiss if it appears
  test/appium/views/base_view.py
Labels: tests

#9729 [#9709] Empty gas when transacting leads to bug
  src/status_im/signing/core.cljs
  src/status_im/signing/gas.cljs
  src/status_im/ui/screens/signing/sheets.cljs
  src/status_im/ui/screens/signing/views.cljs
Labels: request-manual-qa

#9730 Extend e2e about custom mailserver
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/profile_view.py
Labels: tests

#9734 Test reply to messages in chats
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/views/chat_view.py
Labels: tests

#9447 Add pin screen for new wallet accounts for Keycard
  externs.js
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/routing/back_actions.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/wallet/accounts/core.cljs
Labels: Tested - OK, design-review, request-manual-qa

#9731 [#9724] Status is not usable after relogin if add watch-only account …
  src/status_im/subs.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
Labels: Tested - OK

#9732 [#9723] No 'Apply' button appears when updating "Wallet"-> "Account"-…
  src/status_im/ui/components/topbar.cljs
Labels: Tested - OK

#9733 [#9493] No SNT by default after multiaccount creation / restoring
  src/status_im/constants.cljs
  src/status_im/wallet/core.cljs
Labels: Tested - OK, request-manual-qa
