Repository status-im/status-mobile, pull requests merged in 2019-04, with the labels that each got.

#7666 [iOS, Android] Upgrade RN to 0.59.2
  .flowconfig
  .gitignore
  android/app/BUCK
  android/app/build.gradle
  android/app/libs/google-services-4.1.0.jar
  android/app/libs/gradle-download-task-3.1.2.jar
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/res/xml/react_native_config.xml
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm.xcodeproj/xcshareddata/xcschemes/StatusIm.xcscheme
  ios/StatusIm/AppDelegate.h
  ios/StatusIm/AppDelegate.m
  ios/StatusIm/main.m
  ios/StatusImTests/StatusImTests.m
  mobile_files/.babelrc
  mobile_files/metro.config.js
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  resources/images/ui/hold-card-animation.gif
  scripts/lib/setup/nix/mobile/android-ndk/default.nix
  scripts/prepare-for-platform.sh
  src/status_im/react_native/resources.cljs
  src/status_im/ui/components/text_input/view.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/styles/input/input.cljs
  src/status_im/ui/screens/qr_scanner/styles.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  src/status_im/ui/screens/stickers/views.cljs
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: Tested - OK

#7730 Hook pluto extension lifecycle
  src/status_im/extensions/registry.cljs
Labels: Tested - OK

#7867 [Fixed #7864] Removed now irrelevant dapps
  resources/images/contacts/erc-dex.png
  resources/images/contacts/oasis-direct.png
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/browser/default_dapps.cljs
Labels: Tested - OK

#7791 bump develop version to 0.12.0
  mobile_files/VERSION
Labels: Tested - OK

#7865 Fixed missing parameter usage
  src/status_im/extensions/core.cljs
Labels: Tested - OK

#7874 add repo name to ghcmgr url
  ci/ghcmgr.groovy
Labels: jenkins, skip-manual-qa

#7727 add keycard sign method
  STATUS_GO_VERSION
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/models/wallet.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/subs.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/sign_message/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#7877 Revert "[#7133] sign tx with keycard"
  STATUS_GO_VERSION
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/models/wallet.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/subs.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/sign_message/views.cljs
  translations/en.json
Labels: skip-manual-qa

#7868 [feature] contracts namespace
  src/status_im/models/wallet.cljs
  src/status_im/utils/ethereum/contracts.cljs
Labels: Tested - OK, skip-manual-qa

#7741 [#7667]Allow to add/remove custom network from an event
  src/status_im/events.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/network.cljs
  src/status_im/network/core.cljs
  test/cljs/status_im/test/models/network.cljs
  translations/en.json
Labels: Tested - OK

#7725 Open app from deep links tests
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
Labels: skip-manual-qa, tests

#7889 [fix] missing cofx for ipfs/cat call in contenthash/cat
  src/status_im/utils/contenthash.cljs
Labels: skip-manual-qa

#7663 [#7454] Add basic copy to public chat empty screen state
  src/status_im/chat/db.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/db.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/views.cljs
  test/cljs/status_im/test/mailserver/core.cljs
  translations/en.json
Labels: Tested - OK

#7907 [fix] don't lose big number precision above 53 bits in abi-spec
  src/status_im/utils/ethereum/abi_spec.cljs
  test/cljs/status_im/test/utils/ethereum/abi_spec.cljs
Labels: skip-manual-qa

#7873 set maxFontSizeMultiplier for text and text-input components on iOS
  components/src/status_im/ui/components/react.cljs
Labels: Tested - OK

#7888 use auto@status.im Apple account for signing app
  ci/Jenkinsfile.fastlane.clean
  ci/ios.groovy
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
Labels: Tested - OK, jenkins

#7869 Add reading nodes from contract
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  STATUS_GO_VERSION
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  resources/config/fleets.json
  src/status_im/accounts/core.cljs
  src/status_im/accounts/login/core.cljs
  src/status_im/events.cljs
  src/status_im/fleet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/node/core.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/fleet_settings/subs.cljs
  src/status_im/ui/screens/fleet_settings/views.cljs
  src/status_im/utils/config.cljs
  test/cljs/status_im/test/fleet/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/sign_in/data.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
Labels: Tested - OK

#7882 Revert "Revert "[#7133] sign tx with keycard""
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/models/wallet.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/subs.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/subs.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/sign_message/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#7902 Fixed incorrect wallet on-open payload
  src/status_im/ui/screens/wallet/settings/views.cljs
Labels: Tested - OK, extensions

#7802 [#7799] fix chat does not scroll if touch starts on top of datemark
  src/status_im/ui/screens/chat/message/datemark.cljs
  src/status_im/ui/screens/chat/styles/message/datemark.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK

#7929 Added BrowserStack logo to README.md on the main page
  README.md
Labels: skip-manual-qa

#7924 [#7915] fix - Text for empty chat state is shown upside down... by upgrading RN to 0.59.3
  ios/Podfile.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: Tested - OK

#7876 Add Using Pivotal Tracker document
  doc/decisions/0012-using-pivotal-tracker.md
Labels: Tested - OK, skip-manual-qa

#7745 After dismissing error, no redirect to home and new qr can be scanned.
  src/status_im/contact/core.cljs
  src/status_im/events.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/ui/screens/add_new/models.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
Labels: Tested - OK

#7647 [#4158] Fix New messages counter being shown for already seen messages
  src/status_im/chat/models.cljs
  src/status_im/ui/screens/events.cljs
Labels: Tested - OK, bounty

#7932 [#7931] fix - Text for chat name for empty public chat is not centere…
  src/status_im/ui/screens/chat/styles/main.cljs
Labels: Tested - OK

#7943 prevent nix setup running multiple times
  nix/shell.sh
Labels: nix

#7945 Build Android status-go mobile library on macOS
  nix/status-go/default.nix
Labels: skip-manual-qa

#7944 Quick fix: Replace usage of `make setup` on macOS cache builds
  ci/Jenkinsfile.nix.macos
  default.nix
  scripts/lib/setup/installers.sh
  scripts/run-environment-check.sh
Labels: Tested - OK, skip-manual-qa

#7493 Change App ID for PRs on Android to avoid replacing release
  android/app/build.gradle
  android/app/src/debug/res/values/strings.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/pr/AndroidManifest.xml
  android/app/src/pr/google-services.json
  android/app/src/pr/res/values/strings.xml
  android/app/src/release/res/values/strings.xml
  ci/android.groovy
  fastlane/Fastfile
  src/status_im/core.cljs
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
Labels: Tested - Issues

#7866 Clear history via group info
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/views/chat_view.py
Labels: skip-manual-qa, tests

#7939 [#7892] generate keycard mnemonic offline
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, keycard

#7836 [TESTS] Added test sign_typed_message
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#7950 Replace BS logo with a badge
  README.md
Labels: skip-manual-qa

#7951 Do not change user's profile with Nix installation
  scripts/lib/setup/installers.sh
  scripts/setup
Labels: skip-manual-qa

#7925 Fix 'nix build' command by separating out into a shell.nix file
  ci/Jenkinsfile.android
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.nix.linux
  ci/Jenkinsfile.nix.macos
  ci/Jenkinsfile.windows
  ci/docker/nix/Dockerfile
  ci/utils.groovy
  default.nix
  derivation.nix
  nix/desktop/default.nix
  nix/desktop/windows/default.nix
  nix/mobile/default.nix
  nix/shell.sh
  nix/status-go/gomobile/default.nix
  scripts/run-environment-check.sh
  shell.nix
Labels: skip-manual-qa

#7959 Migrate to nodejs v10.15.0
  derivation.nix
Labels: skip-manual-qa

#7938 [#7930] fix - No label is shown for empty chat screen if you open pub…
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK

#7958 modify .env settings using Jenkins params
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/android.groovy
  ci/common.groovy
  ci/ios.groovy
  ci/jenkins.groovy
  ci/utils.groovy
Labels: jenkins, skip-manual-qa

#7862 Beta alert on upgrading
  src/status_im/accounts/core.cljs
  src/status_im/accounts/db.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/events.cljs
Labels: Tested - OK

#7954 don't make e2e builds use modified ID
  ci/android.groovy
Labels: Tested - OK, jenkins

#7962 fix setting of BUILD_TYPE and BRANCH params
  .gitignore
  ci/jenkins.groovy
Labels: jenkins

#7964 Improve makefile to only make Nix install the bare minimum for intended platform
  Makefile
  ci/Jenkinsfile.nix.linux
  ci/Jenkinsfile.nix.macos
  default.nix
  derivation.nix
  nix/desktop/default.nix
  nix/shell.sh
Labels: skip-manual-qa

#7940 [iOS, Android] Upgrade realm-js
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: skip-manual-qa

#7919 Fetch missed range of messages
  src/status_im/chat/db.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/mailserver_topic.cljs
  src/status_im/data_store/realm/schemas/account/message.cljs
  src/status_im/data_store/realm/schemas/account/transport_inbox_topic.cljs
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/subs.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/chat/views.cljs
  test/cljs/status_im/test/chat/db.cljs
  test/cljs/status_im/test/mailserver/core.cljs
  translations/en.json
Labels: Tested - OK, high-priority

#7949 Emoji-only messages can be long-pressed
  src/status_im/ui/screens/chat/message/message.cljs
Labels: Tested - OK

#7955 Fixes and improvements for chat command
  src/status_im/chat/commands/input.cljs
  src/status_im/chat/commands/sending.cljs
  src/status_im/chat/subs.cljs
  src/status_im/ui/screens/chat/input/parameter_box.cljs
  src/status_im/ui/screens/chat/styles/animations.cljs
  test/cljs/status_im/test/chat/commands/input.cljs
Labels: Tested - OK

#7956 New profile hook and capacities
  src/status_im/extensions/core.cljs
  src/status_im/extensions/registry.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
Labels: Tested - OK

#7966 Update ko.json
  translations/ko.json
Labels: Tested - OK, high-priority

#7980 Request to squash commits if the PR has multiple
  scripts/merge-pr.sh
Labels: skip-manual-qa

#7967 Skip fetching 24h of discovery topics on a new account
  src/status_im/accounts/create/core.cljs
  src/status_im/events.cljs
  src/status_im/mailserver/core.cljs
Labels: Tested - OK, high-priority

#7973 Fix endless spinner on Fetch messages
  src/status_im/mailserver/core.cljs
Labels: Tested - OK

#7963 [#7917] fix - Contacts are not synced between 0.11.0 and current nightly
  src/status_im/contact/db.cljs
  src/status_im/pairing/core.cljs
  src/status_im/transport/db.cljs
Labels: Tested - OK, high-priority

#7982 don't use docker containers on linux, nix rules all
  ci/Jenkinsfile.android
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.nix.linux
  ci/Jenkinsfile.windows
  ci/docker/nix/Dockerfile
  ci/docker/nix/Makefile
  ci/docker/nix/README.md
  ci/docker/nix/default.nix
  ci/docker/nix/nix-install-2.2.1.sh
  ci/docker/nix/nix.conf
Labels: jenkins

#7994 Update SimplDapp in e2e to use github url
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#7993 [#6457] Implement extension data persistence
  src/status_im/accounts/update/core.cljs
  src/status_im/data_store/accounts.cljs
  src/status_im/extensions/capacities/camera/events.cljs
  src/status_im/extensions/capacities/camera/views.cljs
  src/status_im/extensions/capacities/components.cljs
  src/status_im/extensions/capacities/ethereum.cljs
  src/status_im/extensions/capacities/events.cljs
  src/status_im/extensions/capacities/map.cljs
  src/status_im/extensions/capacities/network.cljs
  src/status_im/extensions/capacities/subs.cljs
  src/status_im/extensions/core.cljs
  src/status_im/extensions/registry.cljs
  src/status_im/ui/screens/extensions/db.cljs
  src/status_im/ui/screens/routing/screens.cljs
  test/cljs/status_im/test/extensions/ethereum.cljs
Labels: Tested - OK

#7999 merge nix-cache build Jenkinsfiles
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.nix.macos
Labels: jenkins, nix, skip-manual-qa

#7936 [#7933] fix - joining public chat with messages throws error
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/events.cljs
Labels: Tested - OK

#8003 Block user from 1-1 chat header
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/views/chat_view.py
Labels: skip-manual-qa, tests

#8000 Fix running desktop in dev mode
  Makefile
Labels: desktop, skip-manual-qa

#7910 [refactor] send-transaction-message fx/defn
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK

#7901 [feature] implement erc20 get-transaction for SNT and STT
  src/status_im/utils/ethereum/core.cljs
  src/status_im/utils/ethereum/erc20.cljs
Labels: skip-manual-qa

#8005 [fix] fetch wallet token transactions
  src/status_im/models/transactions.cljs
  src/status_im/ui/screens/wallet/events.cljs
Labels: Tested - OK, blocker

#8019 react switch warnings fix
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/ui/screens/profile/components/views.cljs
Labels: Tested - OK

#8017 [#8008] Error "No protocol method IDeref.-deref defined for type unde…
  src/status_im/ui/screens/dapps_permissions/views.cljs
Labels: Tested - OK, high-priority, release

#7827 [#7671] remove ability to change values while signing transaction
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#8006 Fix connection is secure test
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
Labels: skip-manual-qa, tests

#7942 Ensure keycard has applet installed before starting setup
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/hardwallet/success/styles.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8024 fix token transactions
  src/status_im/models/transactions.cljs
Labels: Tested - OK, release

#7997 Multiple messages gaps per chat
  src/status_im/chat/db.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/subs.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact_code/core.cljs
  src/status_im/data_store/mailservers.cljs
  src/status_im/data_store/realm/schemas/account/chat_requests_range.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  src/status_im/data_store/realm/schemas/account/mailserver_requests_gap.cljs
  src/status_im/data_store/realm/schemas/account/mailserver_topic.cljs
  src/status_im/data_store/realm/schemas/account/migrations.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/transport/chat/core.cljs
  src/status_im/transport/filters.cljs
  src/status_im/ui/screens/chat/actions.cljs
  src/status_im/ui/screens/chat/views.cljs
  test/cljs/status_im/test/chat/db.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/mailserver/core.cljs
Labels: Tested - OK, high-priority, release

#8023 [Fixes #7760] Allow copy/paste in browser URL bar
  src/status_im/ui/screens/browser/open_dapp/styles.cljs
  src/status_im/ui/screens/browser/open_dapp/views.cljs
Labels: Tested - OK

#8037 Fix broken contact syncing
  src/status_im/pairing/core.cljs
  src/status_im/transport/impl/send.cljs
  translations/en.json
Labels: Tested - OK, high-priority, release

#8040 upgrade fastlane: 2.117.1 > 2.121.1
  Gemfile.lock
Labels: skip-manual-qa

#8041 upgrade urllib3: 1.24 > 1.24.2
  test/appium/requirements.txt
Labels: skip-manual-qa

#8025 Maintain scroll position after fetching gap
  src/status_im/chat/db.cljs
  src/status_im/ui/screens/chat/actions.cljs
  src/status_im/ui/screens/chat/views.cljs
  test/cljs/status_im/test/chat/db.cljs
Labels: Tested - OK, high-priority, release

#8034 updating dev dependencies
  deps.edn
  project.clj
Labels: skip-manual-qa

#8021 [fix] wallet on-error dispatch
  src/status_im/models/wallet.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/ethereum/contracts.cljs
Labels: skip-manual-qa

#8031 add diawi upload retries
  ci/common.groovy
  ci/ghcmgr.groovy
  ci/github.groovy
  fastlane/Fastfile
Labels: skip-manual-qa

#7720 [TESTS] Add buy/send stickers test
  .env.e2e
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/stickers/views.cljs
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/users.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
Labels: skip-manual-qa, tests

#8048 [Fixes #8044] Do not navigate away after scanning a QR code
  src/status_im/contact/core.cljs
  src/status_im/events.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/ui/screens/add_new/models.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
Labels: Tested - OK, release

#8033 Allow to fetch more history in public chats (up to 30 days)
  src/status_im/chat/db.cljs
  src/status_im/chat/subs.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/chat/actions.cljs
  src/status_im/ui/screens/chat/views.cljs
  test/cljs/status_im/test/chat/db.cljs
  translations/en.json
Labels: Tested - OK

#7977 [#7890] handle wrong keycard when signing
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
Labels: Tested - OK, keycard

#7978 Handle wrong pairing password
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8053 [#8051] TypeError (evaluating 'a.replace') when logging out with wall…
  src/status_im/ui/screens/wallet/send/subs.cljs
Labels: Tested - OK, high-priority, release

#8039 workaround issue with building iOS release builds
  fastlane/Fastfile
Labels: jenkins, skip-manual-qa

#8055 [fix 8054] network in app-db is not always correct
  src/status_im/init/core.cljs
Labels: high-severity, skip-manual-qa

#8062 update :network with proper value
  src/status_im/init/core.cljs
Labels: skip-manual-qa

#8063 Loading indicator animation with useNativeDriver
  src/status_im/ui/components/animation.cljs
  src/status_im/ui/components/connectivity/view.cljs
Labels: Tested - OK, release

#8073 Fix typo in android.nix PATH
  nix/mobile/android.nix
Labels: skip-manual-qa

#8022 Feature fix/ttt settings
  src/status_im/accounts/login/core.cljs
  src/status_im/events.cljs
  src/status_im/ipfs/core.cljs
  src/status_im/tribute_to_talk/core.cljs
  src/status_im/tribute_to_talk/db.cljs
  src/status_im/tribute_to_talk/subs.cljs
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/components/contact/styles.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/components/qr_code_viewer/views.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/profile/contact/styles.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/tribute_to_talk/styles.cljs
  src/status_im/ui/screens/profile/tribute_to_talk/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/utils/ethereum/contracts.cljs
  test/appium/views/profile_view.py
  translations/en.json
Labels: Tested - OK

#8065 Change e2e kickoff column to "E2E Tests"
  .github/github-bot.yml
Labels: developer-xp

#8035 Refactor/move block contact
  src/status_im/contact/block.cljs
  src/status_im/contact/core.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/events.cljs
Labels: tribute-to-talk
