Repository status-im/status-mobile, pull requests merged in 2019-11, with the labels that each got.

#9363 fixes animated gifs on Android
  android/app/build.gradle
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
Labels: Tested - OK

#9258 Fix profile pic bugs (#9234)
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/large_toolbar/view.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/db.cljs
  src/status_im/ui/screens/profile/events.cljs
  src/status_im/ui/screens/profile/models.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, community

#9374 E2e check if seedphrase in new acc is true
  test/appium/tests/atomic/account_management/test_profile.py
Labels: tests

#9338 [#9061] fix fetching balances for keycard acc
  src/status_im/multiaccounts/login/core.cljs
Labels: keycard, request-manual-qa

#9262 include status-go params to set version and commit
  Makefile
  nix/status-go/build-desktop-status-go.nix
  nix/status-go/build-mobile-status-go.nix
  nix/status-go/build-status-go.nix
  nix/status-go/default.nix
  scripts/update-status-go.sh
Labels: nix, status-go, v1 release

#9391 [#9268] fix Multiaccount is currently empty on login
  src/status_im/multiaccounts/login/core.cljs
Labels: Tested - OK

#9397 Fixes to adjust tests to eth.staging
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
Labels: tests

#9340 Increase number on 'unread' messages indicator to +99
  src/status_im/ui/components/badge.cljs
  src/status_im/ui/components/tabbar/core.cljs
  src/status_im/ui/components/tabbar/styles.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  translations/en.json
Labels: Tested - OK, UI tested - OK, community

#9292 fix status bar colors and launch screen
  android/app/src/main/res/drawable-xhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxhdpi/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/colors.xml
Labels: Tested - OK, request-manual-qa

#9286 Patch for 8718
  prod/status_im/i18n_resources.cljs
  translations/fr.json
Labels: Tested - OK, community, request-manual-qa

#9395 don't use SHA1s as status-go version
  ci/utils.groovy
  nix/status-go/default.nix
  scripts/update-status-go.sh
Labels: devops, jenkins, nix

#9398 drop overriding .env values with CI parameters
  ci/utils.groovy
Labels: jenkins

#9257 Local Push Notifications POC
  .env.release
  android/app/src/main/AndroidManifest.xml
  externs.js
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/ForegroundService.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NewMessageSignalHandler.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/android/src/main/res/drawable-hdpi/ic_stat_notify_status.png
  modules/react-native-status/android/src/main/res/drawable-mdpi/ic_stat_notify_status.png
  modules/react-native-status/android/src/main/res/drawable-xhdpi/ic_stat_notify_status.png
  modules/react-native-status/android/src/main/res/drawable-xxhdpi/ic_stat_notify_status.png
  modules/react-native-status/android/src/main/res/drawable-xxxhdpi/ic_stat_notify_status.png
  modules/react-native-status/android/src/main/res/drawable/notification_icon.png
  modules/react-native-status/android/src/main/res/raw/notification_sound.mp3
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/notifications/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK

#9405 [#9342] fix pin-mismatch label
  translations/en.json
Labels: keycard

#9406 [#9350] fix back button on keycard login screen
  src/status_im/subs.cljs
  src/status_im/ui/screens/keycard/views.cljs
Labels: keycard

#9373 Wallet update method
  test/appium/support/api/network_api.py
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/home_view.py
  test/appium/views/wallet_view.py
Labels: tests

#9407 [#9393] fix mnemonic shown during storing account on keycard
  src/status_im/hardwallet/core.cljs
Labels: keycard

#9411 tiny fix to test_send_funds_between_accounts_in_multiaccount_instance
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#9408 [#9256] Remove the "~" from the fiat currency value "~10.4 USD"
  src/status_im/subs.cljs
  src/status_im/ui/screens/profile/tribute_to_talk/views.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: Tested - OK

#9086 keycard pin screen fixes
  src/status_im/hardwallet/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/subs.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/signing/styles.cljs
  src/status_im/ui/screens/signing/views.cljs
  translations/en.json
Labels: design-review, keycard

#9426 fixes ens name wallet address
  src/status_im/ens/core.cljs
Labels: Tested - OK

#9412 remove keycard views with old design
  src/status_im/events.cljs
  src/status_im/ui/screens/hardwallet/components.cljs
  src/status_im/ui/screens/hardwallet/login/styles.cljs
  src/status_im/ui/screens/hardwallet/login/views.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/setup/styles.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  src/status_im/ui/screens/hardwallet/success/styles.cljs
  src/status_im/ui/screens/hardwallet/success/views.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
Labels: keycard

#9414 [#9206] fix wrong ping handling on signing messages
  src/status_im/hardwallet/core.cljs
Labels: keycard

#9434 Fix replies, clear-history, logout bug
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/specs.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/subs.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/db.cljs
  test/cljs/status_im/test/chat/models.cljs
  test/cljs/status_im/test/chat/models/message.cljs
  test/cljs/status_im/test/data_store/chats.cljs
Labels: Tested - OK

#9428 Added more wait time for contract deployment
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
Labels: tests

#9409 Parse in status-go and render markdown
  externs.js
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_content.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/db.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/utils/security.cljs
  status-go-version.json
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/cljs/status_im/test/chat/models/message_content.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/utils/security.cljs
Labels: Tested - OK

#9442 [#8845] Update list of public chats
  components/src/status_im/react_native/resources.cljs
  resources/default_public_chats.json
  resources/images/ui/new-chat-header.png
  resources/images/ui/new-chat-header@2x.png
  resources/images/ui/new-chat-header@3x.png
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/styles.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/add_new/styles.cljs
  src/status_im/ui/screens/desktop/main/add_new/views.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/screens.cljs
  translations/en.json
Labels: Tested - OK, UI tested - OK

#9452 Ensure `STATUS_GO_SRC_OVERRIDE` gets passed to the Nix shell's `config`
  nix/shell.sh
  shell.nix
Labels: nix

#9454 nix: Remove need to pass default values in `--arg config`
  default.nix
  nix/nixpkgs-bootstrap.nix
  nix/shell.sh
  scripts/release-android.sh
  shell.nix
Labels: nix

#9440 upgrade multiple desktop deps
  desktop/js_files/package.json
  desktop/js_files/yarn.lock
Labels: dependencies

#9170 Add new welcome page after generating their key
  components/src/status_im/react_native/resources.cljs
  fiddle/src/status_im/react_native/resources.cljs
  resources/images/ui/empty-chats-header.png
  resources/images/ui/empty-chats-header@2x.png
  resources/images/ui/empty-chats-header@3x.png
  resources/images/ui/welcome.jpg
  resources/images/ui/welcome@2x.jpg
  resources/images/ui/welcome@3x.jpg
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/db.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  translations/en.json
Labels: Tested - OK, UI tested - OK, bounty, community

#9448 Align tests with 9170
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#9441 [#9345] fix some issues on keycard login screen
  src/status_im/hardwallet/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/ui/screens/keycard/views.cljs
  translations/en.json
Labels: Tested - OK

#9486 fix nix-clean for MacOS
  Makefile
  nix/clean.sh
  nix/shell.sh
Labels: nix

#9479 Weak-password disallows confirm code step
  src/status_im/multiaccounts/create/core.cljs
Labels: Tested - OK, community

#9450 [#9446] Resume logging when connection to card is restored
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/native_module/core.cljs
Labels: Tested - OK, keycard

#9506 Markdown test + added waiting for some elements to avoid failures
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/home_view.py
Labels: tests

#9496 Add support for SAI/DAI
  resources/images/tokens/mainnet/DAI.png
  resources/images/tokens/mainnet/DAI@2x.png
  resources/images/tokens/mainnet/DAI@3x.png
  resources/images/tokens/mainnet/SAI.png
  resources/images/tokens/mainnet/SAI@2x.png
  resources/images/tokens/mainnet/SAI@3x.png
  src/status_im/ethereum/tokens.cljs
Labels: Tested - OK, UI tested - OK, community, request-manual-qa

#9378 Set max decimal places at 6 for signing sheet
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/utils/utils.cljs
  test/cljs/status_im/test/utils/utils.cljs
Labels: Tested - OK, bounty, community, request-manual-qa

#9483 bundle of desktop dependency upgrades
  desktop/js_files/package.json
  desktop/js_files/yarn.lock
Labels: dependencies

#9514 New e2e: test_set_primary_ens_custom_domain
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/users.py
  test/appium/views/dapps_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#9530 more wait for lets_go_button
  test/appium/views/sign_in_view.py
Labels: tests

#9536 clj-kondo configuration for Status specific macroses
  .clj-kondo/config.edn
Labels: dev-tools

#9527 nix: Use mkFilter in local status-go source
  fastlane/Gemfile
  nix/derivation.nix
  nix/status-go/default.nix
  nix/tools/mkFilter.nix
Labels: nix

#9502 [#9435] Prevent multiaccount duplication
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/ethereum/core.cljs
  src/status_im/ethereum/ens.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/db.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/hardwallet/settings/subs.cljs
  src/status_im/ui/screens/intro/styles.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/utils/contenthash.cljs
  src/status_im/utils/utils.cljs
  src/status_im/wallet/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#9537 [#9509] Chat onboarding tooltip needs fixes to scroll behaviour
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
Labels: Tested - OK, UI tested - OK, request-manual-qa

#9545 fix for e2e - node version + scroll
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/base_view.py
  translations/en.json
Labels: tests

#9544 [WIP ] Fix wallet send tx tests
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/send/sheets.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#9558 [#9061] Fix balances fetching of a new keycard account
  src/status_im/hardwallet/core.cljs
Labels: keycard
