Repository status-im/status-mobile, pull requests merged in 2019-05, with the labels that each got.

#8012 Gaps on desktop
  src/status_im/ui/components/popup_menu/views.cljs
  src/status_im/ui/screens/chat/message/gap.cljs
  src/status_im/ui/screens/chat/styles/input/gap.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
Labels: Tested - OK

#8092 Update subscriptions codebase structure doc
  doc/codebase-structure-and-guidelines.md
Labels: skip-manual-qa

#7820 [#7819] fix - avoid unnecessary effects when joining/syncing already active public chat
  src/status_im/chat/models.cljs
  src/status_im/pairing/core.cljs
  src/status_im/utils/universal_links/core.cljs
Labels: Tested - OK, community

#8085 [#8064] Fix deletion of a custom mailserver
  src/status_im/data_store/mailservers.cljs
Labels: Tested - OK

#8084 [#7859] Allow to select chat item below plus button
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK

#8094 Make contacts round again
  src/status_im/ui/components/list/styles.cljs
Labels: skip-manual-qa

#8086 [#8072] Fix crash on deleting group chat
  src/status_im/ui/screens/profile/group_chat/views.cljs
Labels: Tested - OK

#8095 small changes in subscriptions
  src/status_im/subs.cljs
Labels: skip-manual-qa

#8101 [#7848] Fix crash on logout with opened transactions details
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK

#8091 [#8080] Prevent extra gap in 1:1 chats on adding group chat
  src/status_im/mailserver/core.cljs
Labels: Tested - OK

#8014 [Fixed #7948] Do not navigate back to chat when in a DApp
  src/status_im/ui/screens/routing/browser_stack.cljs
Labels: Tested - OK

#7986 [#7355]Allow-to-close-wallet.settings-from-an-event
  src/status_im/extensions/capacities/events.cljs
Labels: Tested - OK, bounty, community, extensions

#8113 Make Probot move reviewed PRs to E2E Tests column
  .github/github-bot.yml
Labels: skip-manual-qa

#8109 Add comments to STATUS_GO_VERSION to avoid manual editing
  STATUS_GO_SHA256
  STATUS_GO_VERSION
  modules/react-native-status/android/build.gradle
  modules/react-native-status/desktop/CMakeLists.txt
  nix/status-go/default.nix
  scripts/update-status-go.sh
Labels: skip-manual-qa

#8114 Adopt e2e to new Status.im design
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
Labels: skip-manual-qa, tests

#8061 feature #7104 - adding error property on input extension to support error
  src/status_im/extensions/capacities/components.cljs
Labels: Tested - OK, bounty, community, extensions

#7551 Mobile UI for desktop
  .env
  clj-rn.conf.edn
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  src/status_im/desktop/core.cljs
  src/status_im/ui/components/bottom_bar/core.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/list_selection.cljs
  src/status_im/ui/components/popup_menu/views.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/views.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/chat/actions.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/styles/input/input.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/options.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/navigation.cljs
Labels: Tested - OK, desktop

#8096 [#7898] remove pin from alert message
  src/status_im/hardwallet/core.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8018 Update status-go to v0.24.0-beta.1
  STATUS_GO_SHA256
  STATUS_GO_VERSION
Labels: Tested - OK

#8119 Share checksum address in wallet
  src/status_im/ui/screens/wallet/request/views.cljs
Labels: Tested - OK

#8126 Fix crash on switching to Ropsten (dev mode)
  src/status_im/subs.cljs
Labels: Tested - OK, skip-manual-qa

#8100 [#7871] Handle multiple opened screens with qr code readers
  src/status_im/browser/permissions.cljs
  src/status_im/extensions/capacities/camera/events.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/navigation.cljs
  test/cljs/status_im/test/browser/core.cljs
  test/cljs/status_im/test/mailserver/core.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
Labels: Tested - OK

#8125 [#8123] Show fetch more messages only after sync
  src/status_im/chat/db.cljs
Labels: Tested - OK

#8128 [#1442] Allow only decimal number in send command
  src/status_im/chat/commands/impl/transactions.cljs
Labels: Tested - OK

#8042 Fixed broken EIP1577 support
  src/status_im/browser/core.cljs
  src/status_im/events.cljs
  src/status_im/utils/contenthash.cljs
  src/status_im/utils/ethereum/ens.cljs
  test/cljs/status_im/test/utils/contenthash.cljs
Labels: Tested - OK

#8148 Enable TX history view test on PR level
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/views/base_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#8146 [#8121] Resolved ENS address is not checksummed
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
Labels: Tested - OK

#7937 [#7911 #7894] delete account and logout after keycard reset
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  src/status_im/accounts/login/core.cljs
  src/status_im/data_store/accounts.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/init/core.cljs
  src/status_im/ui/components/bottom_bar/core.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/success/styles.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
Labels: Tested - OK, keycard

#8140 [#8107] Wallet balance is not updated when transaction is received
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK

#8036 Tribute to Talk adr
  doc/decisions/0013-tribute-to-talk.md
Labels: skip-manual-qa

#8155 Fix send tx one by one in dapp test
  test/appium/support/api/network_api.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#8112 [#8082] Some dapps don't work in status when privacy mode is enabled
  src/status_im/ui/components/radio.cljs
  src/status_im/ui/screens/browser/open_dapp/styles.cljs
  src/status_im/ui/screens/browser/open_dapp/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  translations/en.json
Labels: Tested - OK

#8156 don't rebase on canary-branch
  ci/utils.groovy
Labels: jenkins

#8169 nix: Minor cleanup of fastlane expression
  ci/utils.groovy
  fastlane/default.nix
  shell.nix
Labels: nix, skip-manual-qa

#8165 remove unecessary check in update-status-go script
  scripts/update-status-go.sh
Labels: skip-manual-qa

#8172 Fixed failed e2e
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
Labels: skip-manual-qa, tests

#8171 Move status-go imports to where it is actually used
  derivation.nix
  nix/desktop/default.nix
  nix/desktop/linux/default.nix
  nix/desktop/macos/default.nix
  nix/mobile/default.nix
Labels: nix, skip-manual-qa

#8174 Print a friendlier message when Xcode/iPhone SDK are not installed
  nix/status-go/build-desktop-status-go.nix
  nix/status-go/build-mobile-status-go.nix
  nix/status-go/build-status-go.nix
  nix/status-go/default.nix
  nix/status-go/gomobile/default.nix
  nix/utils.nix
  scripts/setup
Labels: nix, skip-manual-qa

#8122 [Android] send logs to error-reports@status.im
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  scripts/prepare-for-platform.sh
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/utils/email.cljs
  src/status_im/utils/logging/core.cljs
Labels: Tested - OK

#8079 fix keycard navigation bugs
  src/status_im/accounts/login/core.cljs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/models/wallet.cljs
  src/status_im/ui/components/bottom_bar/core.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
Labels: Tested - OK, keycard

#8099 [#7887] handle tag lost errors
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/hardwallet/connect/views.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/views.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  test/cljs/status_im/test/hardwallet/core.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8097 [#7927] import keycard account to new device
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8192 [#8160] "this.props.onPress is not a function" on tapping back from t…
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK

#8181 nix: Add add-gcroots target to Makefile to avoid garbage collection
  .gitignore
  Makefile
  nix/shell.sh
  scripts/add-gcroots.sh
  scripts/lib/setup/platform.sh
Labels: nix, skip-manual-qa

#8194 Minor refactoring of the way dependency packages are iterated for shellHook and buildInputs
  derivation.nix
  nix/desktop/default.nix
  nix/desktop/linux/default.nix
  nix/desktop/macos/default.nix
  nix/mobile/default.nix
  nix/status-go/default.nix
  shell.nix
Labels: nix, skip-manual-qa

#8106 [feature] add varint encoding/decoding
  src/status_im/utils/varint.cljs
  test/cljs/status_im/test/utils/varint.cljs
Labels: skip-manual-qa

#8158 [feature] use status-go signal subscriptions for current block
  STATUS_GO_SHA256
  STATUS_GO_VERSION
  src/status_im/accounts/login/core.cljs
  src/status_im/ethereum/decode.cljs
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/events.cljs
  src/status_im/signals/core.cljs
  src/status_im/subs.cljs
  src/status_im/utils/ethereum/core.cljs
Labels: Tested - OK, performance, wallet

#8198 Reworked test_purchase_pack_and_send_sticker
  test/appium/tests/atomic/chats/test_one_to_one.py
Labels: skip-manual-qa, tests

#8124 [iOS] Allow to send email with logs on iOS
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.xcodeproj/project.pbxproj
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK

#7979 [#7371]Add an event to display a view fullscreen
  src/status_im/extensions/capacities/events.cljs
  src/status_im/extensions/capacities/views.cljs
  src/status_im/extensions/registry.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  translations/en.json
  translations/es_419.json
  translations/fa.json
  translations/ko.json
  translations/ms.json
  translations/ne.json
  translations/pl.json
  translations/ru.json
  translations/zh_Hans_CN.json
Labels: Tested - OK, community, extensions

#8175 [fix] ipfs CID
  src/status_im/ipfs/core.cljs
  src/status_im/utils/contenthash.cljs
  test/cljs/status_im/test/utils/contenthash.cljs
Labels: skip-manual-qa

#8204 Ubuntu-server rejects connections not from localhost
  ubuntu-server.js
Labels: skip-manual-qa

#8183 refactor nix_sh to give it optional Map arguments
  ci/Jenkinsfile.android
  ci/Jenkinsfile.fastlane.clean
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.windows
  ci/android.groovy
  ci/common.groovy
  ci/desktop.groovy
  ci/ios.groovy
  ci/nix.groovy
  ci/utils.groovy
  fastlane/Fastfile
  scripts/lib/setup/platform.sh
  scripts/setup
  shell.nix
Labels: nix

#8081 Add js logs to archive
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/utils/logging/core.cljs
Labels: Tested - OK

#8220 use CHANGE_TARGET to rebase on actual PR target
  ci/utils.groovy
Labels: jenkins

#8213 Add auto_assign and CODEOWNERS config
  .github/CODEOWNERS
  .github/auto_assign.yml
Labels: skip-manual-qa

#8182 Move to use Stale Probot instead of status-github-bot
  .github/github-bot.yml
  .github/stale.yml
Labels: devops, skip-manual-qa

#8222 fix missing env prefix for CHANGE_TARGET
  ci/utils.groovy
Labels: jenkins

#8212 Fetch new version of base images with fixed ubuntu-server
  nix/desktop/linux/base-image/default.nix
  nix/desktop/macos/base-image/default.nix
  nix/desktop/windows/base-image/default.nix
Labels: Tested - OK, desktop, high-priority

#8208 [#8145] exclude some chars when generating pairing password
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: Tested - OK, keycard

#8223 [performance] replace reduce by reduce-kv
  src/status_im/chat/db.cljs
  src/status_im/contact/db.cljs
Labels: performance, skip-manual-qa

#8179 remove duplicate entries in en.json
  translations/en.json
Labels: Tested - OK, community

#8201 [#8187] fix keyboard pop-up when logout after keycard setup finished
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/hardwallet/components.cljs
  src/status_im/ui/screens/hardwallet/setup/styles.cljs
  src/status_im/ui/screens/hardwallet/setup/views.cljs
Labels: Tested - OK, keycard

#8133 Add send logs button to exception dialog
  src/status_im/utils/error_handler.cljs
Labels: Tested - OK

#8235 [#7983] Basic user added ERC-20 support
  components/src/status_im/ui/components/react.cljs
  src/status_im/chat/commands/impl/transactions.cljs
  src/status_im/ethereum/decode.cljs
  src/status_im/events.cljs
  src/status_im/models/wallet.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/components/common/common.cljs
  src/status_im/ui/components/common/styles.cljs
  src/status_im/ui/components/list_header/views.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/components/text_input/styles.cljs
  src/status_im/ui/components/text_input/view.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/custom_tokens/views.cljs
  src/status_im/ui/screens/wallet/main/views.cljs
  src/status_im/ui/screens/wallet/navigation.cljs
  src/status_im/ui/screens/wallet/settings/models.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/utils/ethereum/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
  translations/en.json
Labels: Tested - OK, wallet

#8227 Fix deep links tests
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: skip-manual-qa, tests

#8210 [7715] Feature: Contextual bottom sheet on long press
  src/status_im/events.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/bottom_sheet/db.cljs
  src/status_im/ui/components/bottom_sheet/events.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/group/chat_settings/events.cljs
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/views.cljs
  translations/en.json
Labels: Tested - OK, bounty, community

#8237 Align e2e with 8210
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#8238 android: add adaptive icon for non-debug builds
  android/app/src/main/res/drawable-hdpi/ic_background.png
  android/app/src/main/res/drawable-hdpi/ic_foreground.png
  android/app/src/main/res/drawable-mdpi/ic_background.png
  android/app/src/main/res/drawable-mdpi/ic_foreground.png
  android/app/src/main/res/drawable-xhdpi/ic_background.png
  android/app/src/main/res/drawable-xhdpi/ic_foreground.png
  android/app/src/main/res/drawable-xxhdpi/ic_background.png
  android/app/src/main/res/drawable-xxhdpi/ic_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/ic_background.png
  android/app/src/main/res/drawable-xxxhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_background.png
  android/app/src/main/res/mipmap-hdpi/ic_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_background.png
  android/app/src/main/res/mipmap-mdpi/ic_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: release

#8164 Optimized ScrollView instead of FlatList for desktop chat
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/chat/message/gap.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, desktop

#8240 nix: Avoid bad practice of inheriting pkgs
  derivation.nix
  ios/Podfile.lock
  nix/desktop/default.nix
  nix/desktop/linux/default.nix
  nix/desktop/macos/default.nix
  nix/desktop/windows/default.nix
  nix/mobile/android.nix
  nix/mobile/default.nix
  nix/mobile/licensed-android-sdk.nix
  nix/status-go/build-desktop-status-go.nix
  nix/status-go/build-mobile-status-go.nix
  nix/status-go/default.nix
  nix/status-go/gomobile/default.nix
  scripts/prepare-for-platform.sh
Labels: nix, skip-manual-qa

#8250 [#8249] "" when grant access to ens dapp shown, it prevents the name …
  src/status_im/browser/core.cljs
Labels: Tested - OK, high-priority, release

#8205 Added accessibility-label to some pairing components
  src/status_im/ui/screens/pairing/views.cljs
Labels: skip-manual-qa, tests

#8009 [7947] Feature: Blank out app preview screen when switching apps on m…
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  ios/StatusIm/AppDelegate.m
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/accounts/core.cljs
  src/status_im/constants.cljs
  src/status_im/events.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  test/cljs/status_im/test/sign_in/data.cljs
  translations/en.json
Labels: Tested - OK, bounty, community

#8191 [experiment] limit number of rendered messages when open a chat
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, performance

#7928 Add Bloom token
  resources/images/tokens/mainnet/BLT.png
  resources/images/tokens/mainnet/BLT@2x.png
  resources/images/tokens/mainnet/BLT@3x.png
  src/status_im/utils/ethereum/tokens.cljs
Labels: Tested - OK, community

#8260 [#8236] [Wallet] Custom token details and remove
  src/status_im/events.cljs
  src/status_im/ui/components/bottom_sheet/db.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/ui/screens/wallet/custom_tokens/views.cljs
  src/status_im/ui/screens/wallet/settings/models.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/wallet/custom_tokens/core.cljs
  translations/en.json
Labels: Tested - OK, high-priority, release, wallet

#8261 [#8239] App crash when submit cryptokitties with different than it's …
  src/status_im/ui/screens/browser/site_blocked/views.cljs
Labels: Tested - OK, to be automated

#8267 [TESTS] Added test_open_blocked_site
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/conftest.py
Labels: skip-manual-qa, tests

#8270 [fix] remove duplicates of :hardwallet/verify-pin event
  src/status_im/events.cljs
Labels: skip-manual-qa

#8271 add MOBILE_UI_FOR_DESKTOP=0 to other env files
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.nightly.staging.fleet
  .env.prod
Labels: jenkins

#8259 [refactor] use `ethereum` `current-address` and `chain-keyword`
  src/status_im/browser/core.cljs
  src/status_im/ethereum/contracts.cljs
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/transactions/etherscan.cljs
  src/status_im/extensions/capacities/ethereum.cljs
  src/status_im/network/core.cljs
  src/status_im/subs.cljs
  src/status_im/tribute_to_talk/core.cljs
  src/status_im/tribute_to_talk/db.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/ui/screens/wallet/choose_recipient/events.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  src/status_im/ui/screens/wallet/transaction_fee/views.cljs
  src/status_im/utils/ethereum/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
Labels: skip-manual-qa

#8141 Send logs on shaking device
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  ios/StatusIm.xcodeproj/project.pbxproj
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/android/core.cljs
  src/status_im/events.cljs
  src/status_im/ios/core.cljs
  src/status_im/utils/logging/core.cljs
  translations/en.json
Labels: Tested - OK

#8142 App version and more details in logs email
  src/status_im/utils/logging/core.cljs
Labels: Tested - OK

#8265 [#8256] do not call getApplicationInfo every time card connected
  src/status_im/hardwallet/core.cljs
Labels: Tested - OK, keycard

#8281 [#8277] Report a bug template
  src/status_im/utils/logging/core.cljs
  translations/en.json
Labels: Tested - OK, release

#8274 Update the defn macro
  src/status_im/accounts/login/core.cljs
  src/status_im/events.cljs
  src/status_im/tribute_to_talk/core.cljs
  src/status_im/utils/fx.clj
  test/cljs/status_im/test/utils/fx.cljs
Labels: Tested - OK, developer-xp

#8289 Fix custom tokens
  src/status_im/wallet/custom_tokens/core.cljs
Labels: Tested - OK

#8290 Enable asset in Wallet before usage
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8296 [fix] superfluous keyword
  src/status_im/subs.cljs
Labels: skip-manual-qa

#8272 save keycard keyUID and use it for login
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/db.cljs
  src/status_im/accounts/login/core.cljs
  src/status_im/data_store/realm/schemas/base/account.cljs
  src/status_im/data_store/realm/schemas/base/core.cljs
  src/status_im/hardwallet/core.cljs
  test/cljs/status_im/test/hardwallet/core.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
Labels: Tested - OK, keycard

#8303 E2E for pairing devices
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#7734 Add goerli testnet
  src/status_im/constants.cljs
  src/status_im/ethereum/core.cljs
Labels: Tested - OK

#8297 Fix/on result in app transactions
  src/status_im/wallet/core.cljs
Labels: Tested - OK, sticker

#8278 Prepare to use status-go based protocol: 1-1 and public chat management APIs.
  .env
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/signals/core.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/fx.cljs
  test/cljs/status_im/test/chat/models.cljs
Labels: Tested - OK

#8316 bump version to 0.14.0
  desktop_files/VERSION
  mobile_files/VERSION
Labels: skip-manual-qa

#8305 Add scroll on wallet
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8319 [feature] allow internal transaction to specify asset
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: skip-manual-qa

#8320 [feature] support for new CIDv1
  src/status_im/ethereum/ens.cljs
  src/status_im/utils/contenthash.cljs
  test/cljs/status_im/test/utils/contenthash.cljs
Labels: Tested - OK

#8322 [feature] add transaction watch
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/transactions/core.cljs
Labels: developer-xp, skip-manual-qa, user-xp

#8324 [fix] destructuring in events for fx/defn macro
  src/status_im/utils/fx.clj
  test/cljs/status_im/test/utils/fx.cljs
Labels: developer-xp, skip-manual-qa

#8285 advanced cljs compilation
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  externs.js
  project.clj
  src/status_im/ethereum/abi_spec.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/i18n.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/wallet/send/events.cljs
  src/status_im/utils/datetime.cljs
  test/cljs/status_im/test/utils/datetime.cljs
Labels: Tested - OK, performance

#8127 [#6573]Have the ability to use fingerprint log in to the app (including Touch ID)
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm/Info.plist
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/accounts/core.cljs
  src/status_im/accounts/login/core.cljs
  src/status_im/biometric_auth/core.cljs
  src/status_im/constants.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/keychain/core.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  translations/en.json
Labels: Tested - OK, bounty, community

#8323 E2E for sync public, group chats and profile details: username and photo
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/profile_view.py
Labels: skip-manual-qa, tests

#8328 [fix] event transfer hash turned into a function
  src/status_im/constants.cljs
Labels: skip-manual-qa

#8315 Remove unused chat fields
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/realm/schemas/account/chat.cljs
  src/status_im/data_store/realm/schemas/account/core.cljs
  test/cljs/status_im/test/sign_in/data.cljs
Labels: Tested - OK
