Repository status-im/status-mobile, pull requests merged in 2019-10, with the labels that each got.

#9078 [#9055] fix keycard restore
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
Labels: keycard

#9082 fix which APK is published for e2e builds
  ci/Jenkinsfile.android
  ci/android.groovy
  ci/ghcmgr.groovy
Labels: jenkins

#9089 Fix api request to etherscan
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#8959 Fix small UI problems with the compose reply screen
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/styles/input/input.cljs
  src/status_im/ui/screens/chat/utils.cljs
Labels: bounty, community, design-review

#9092 Fixed desktop excessive logging
  nix/desktop/base-image/default.nix
Labels: desktop-new

#9083 Update the Korean translations
  translations/ko.json
Labels: skip-manual-qa, translations

#9085 e2e for mobile data sync
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/base_element.py
  test/appium/views/profile_view.py
Labels: tests

#9033 biometric
  CHANGELOG.md
  ICONS.md
  android/app/src/main/res/drawable-mdpi/faceid.png
  android/app/src/main/res/drawable-mdpi/print.png
  android/app/src/main/res/drawable-xhdpi/faceid.png
  android/app/src/main/res/drawable-xhdpi/print.png
  android/app/src/main/res/drawable-xxhdpi/faceid.png
  android/app/src/main/res/drawable-xxhdpi/print.png
  ios/StatusIm/Images.xcassets/faceid.imageset/Contents.json
  ios/StatusIm/Images.xcassets/faceid.imageset/faceid@1x.png
  ios/StatusIm/Images.xcassets/faceid.imageset/faceid@2x.png
  ios/StatusIm/Images.xcassets/faceid.imageset/faceid@3x.png
  ios/StatusIm/Images.xcassets/print.imageset/Contents.json
  ios/StatusIm/Images.xcassets/print.imageset/print@1x.png
  ios/StatusIm/Images.xcassets/print.imageset/print@2x.png
  ios/StatusIm/Images.xcassets/print.imageset/print@3x.png
  src/status_im/biometric_auth/core.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/biometric/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/popover/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/button.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/biometric/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/multiaccounts/login/styles.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/utils/keychain/core.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  translations/en.json
Labels: Tested - OK, design-review, request-manual-qa

#9096 [Fixes #9088] Store eip1581 path
  src/status_im/constants.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/wallet/accounts/core.cljs
Labels: security, v1 audit, v1 release

#9103 Fix for 2 failed e2e
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
Labels: tests

#9063 Add currency conversions for signing sheet - Fixes #8027
  src/status_im/ui/screens/signing/views.cljs
Labels: Tested - OK, bounty, community, design-review, request-manual-qa

#9104 Test to check cryptokitty in wallet collectibles
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/users.py
  test/appium/views/dapps_view.py
  test/appium/views/wallet_view.py
Labels: tests

#9056 upgrade status-go with geth 1.9.5
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#9105 Suppress back-up-seed prompt when already done (fixes #8938)
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
Labels: Tested - OK, bounty, community, design-review, request-manual-qa

#9052 [#9025] fix keycard pairings persistence
  src/status_im/hardwallet/core.cljs
Labels: keycard, v1 release

#9053 keycard bugfixes
  src/status_im/hardwallet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: keycard

#9077 [#8937] Recent stickers are shown when stickers tab is highlighted
  src/status_im/ui/screens/chat/stickers/views.cljs
Labels: Tested - OK, request-manual-qa

#9132 Fixed e2e: return boolean instead of string
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/base_element.py
Labels: tests

#9145 [#9139] Can not purchase sticker pack (too low no sign with password …
  src/status_im/ui/screens/signing/views.cljs
Labels: v1 release

#9146 [#9138] Missing translation in "Need help" section ("Ask a question")
  translations/en.json
Labels: v1 release

#9147 [#9107] Collectibles (except CryptoKitties) are not loaded (endless s…
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/wallet/collectibles/core.cljs
Labels: v1 release

#9075 Fix ENS input when starting a new chat
  components/src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
Labels: Tested - OK, request-manual-qa

#9151 Test if recover seedphrase button disabled on Profile
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
Labels: skip-manual-qa, tests

#9087 [#8657] Keyboard overlaps sign button if you tap on sign after changing "Recipient" or "Asset" field on Send Transaction screen
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK, bounty, community, request-manual-qa

#9156 Fix stickers \ collectibles
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
Labels: tests

#9160 [#8997] Error 'Hzb.checkViodeoAuthorizationStatus in not a function' …
  src/status_im/ui/components/permissions.cljs
Labels: v1 release

#9161 Add dependabot config file
  .dependabot/config.yml
Labels: devops

#8903 Onboarding ui touchups
  components/src/status_im/react_native/resources.cljs
  externs.js
  resources/images/ui/intro1.jpg
  resources/images/ui/intro1.png
  resources/images/ui/intro2.jpg
  resources/images/ui/intro2.png
  resources/images/ui/intro3.jpg
  resources/images/ui/intro3.png
  resources/images/ui/sample-key.jpg
  resources/images/ui/sample-key.png
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/text_input/styles.cljs
  src/status_im/ui/components/text_input/view.cljs
  src/status_im/ui/screens/about_app/views.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/intro/styles.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/multiaccounts/recover/views.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/views.cljs
  test/appium/views/sign_in_view.py
  test/cljs/status_im/test/i18n.cljs
  test/cljs/status_im/test/multiaccounts/recover/core.cljs
  translations/en.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: Tested - Issues, Tested - OK, design-review, request-manual-qa, v1 release

#9175 [#8662] No chats on 'Chats' view if to clear entered search term in '…
  src/status_im/ui/screens/home/views.cljs
Labels: v1 release

#9171 Enable high priority tests in PRs
  .github/github-bot.yml
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
Labels: tests

#9202 Small fix to e2e: deleting dapps
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/dapps_view.py
Labels: tests

#9211 Fixed several case ids and add test for checking log_level and fleet
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/profile_view.py
Labels: tests

#9209 Fix #8960
  src/status_im/wallet/choose_recipient/core.cljs
Labels: Tested - OK, bounty, community, request-manual-qa

#9172 Upgrade xcode version to 11.1
  .dependabot/config.yml
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.macos
  nix/mobile/default.nix
  scripts/sign-macos-pkg.sh
Labels: nix

#9218 add info about MacOS Catalina workaround
  nix/README.md
Labels: docs

#9223 resolve ENS in wallet
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/users.py
  test/appium/views/send_transaction_view.py
Labels: tests

#9182 [fix 8853] fix change of whisper id in ens registration
  src/status_im/ens/core.cljs
  src/status_im/ens/db.cljs
  src/status_im/ethereum/core.cljs
  src/status_im/ethereum/ens.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/stateofus.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/button.cljs
  src/status_im/ui/components/list_item/views.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/cljs/status_im/test/i18n.cljs
  translations/en.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: UI tested - OK, v1 release

#9137 Bumps galore
  Makefile
  desktop/js_files/yarn.lock
  fastlane/Gemfile.lock
  fastlane/gemset.nix
  ios/Podfile.lock
  mobile/js_files/yarn.lock
Labels: Tested - OK, dependencies, request-manual-qa

#9150 Clean /tmp and $TMPDIR in make clean
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.fastlane.clean
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  ci/common.groovy
  nix/build.sh
  shell.nix
Labels: developer-xp

#9239 e2e - switching accounts in DApp
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/views/dapps_view.py
  test/appium/views/home_view.py
Labels: tests

#9215 [#8940] Redesign Back, swipe-to-the-left and hardware device Back but…
  android/build.gradle
  src/status_im/android/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/routing/back_actions.cljs
  src/status_im/ui/screens/routing/core.cljs
Labels: v1 release

#9237 New e2e tests and fix
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/base_test_case.py
  test/appium/views/dapps_view.py
  test/appium/views/wallet_view.py
Labels: tests

#9254 E2E Fixes
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/test_translations.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/dapps_view.py
Labels: tests

#9178 Verify ENS names
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/ens/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/utils/fx.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/cljs/status_im/test/contacts/db.cljs
  test/cljs/status_im/test/models/contact.cljs
  test/cljs/status_im/test/transport/core.cljs
Labels: blocked

#9278 Mailserver e2e
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/profile_view.py
Labels: tests

#9273 Add unblock user test
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#9267 avoid spawning too many Nix shells
  Makefile
Labels: devops

#9265 fix matching deps with only one dependency
  nix/mobile/android/maven-and-npm-deps/maven/fetch-maven-deps.sh
Labels: nix

#9287 E2E account settings
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/wallet_view.py
Labels: tests

#9279 Test sent transaction appears in history
  src/status_im/ui/screens/profile/components/sheets.cljs
  src/status_im/ui/screens/wallet/accounts/sheets.cljs
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/chat_view.py
Labels: tests

#9157 FIxes #8951
  src/status_im/network/net_info.cljs
Labels: Tested - OK, bounty, community, request-manual-qa

#9291 Fix #9180
  src/status_im/wallet/choose_recipient/core.cljs
Labels: Tested - OK, community, request-manual-qa

#9293 [#9205] "Resend" option doesn't resend message on Android
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/options.cljs
  src/status_im/ui/screens/chat/message/sheets.cljs
  src/status_im/ui/screens/chat/styles/message/options.cljs
  src/status_im/ui/screens/chat/styles/message/sheets.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, community, request-manual-qa

#9310 To isolate soft error handling per test
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/base_test_case.py
  test/appium/tests/test_performance.py
Labels: tests

#9343 Remove Maybe later after deleting PN
  test/appium/views/sign_in_view.py
Labels: tests

#9272 Combined desktop dependency upgrades
  desktop/js_files/package.json
  desktop/js_files/yarn.lock
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
Labels: dependencies

#9271 [#9233, #9173] fix overlapping on some screens
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#9362 Followup e2e fix after PN remove
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#9369 fix recovery with mnemonic on keycard
  src/status_im/hardwallet/core.cljs
Labels: keycard
