Repository status-im/status-mobile, pull requests merged in 2019-07, with the labels that each got.

#8449 Use react-native-screens
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  clj-rn.conf.edn
  externs.js
  ios/StatusIm.xcodeproj/project.pbxproj
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/android/core.cljs
  src/status_im/ios/core.cljs
Labels: Tested - OK

#8505 Fix for nightly e2e - 1 part
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8501 [fix] missing icons in wallet
  android/app/src/main/res/drawable-mdpi/token.png
  android/app/src/main/res/drawable-mdpi/watch.png
  android/app/src/main/res/drawable-xhdpi/token.png
  android/app/src/main/res/drawable-xhdpi/watch.png
  android/app/src/main/res/drawable-xxhdpi/watch.png
  android/app/src/main/res/drawable-xxxhdpi/token.png
  ios/StatusIm/Images.xcassets/token.imageset/Contents.json
  ios/StatusIm/Images.xcassets/token.imageset/token.png
  ios/StatusIm/Images.xcassets/token.imageset/token@2x.png
  ios/StatusIm/Images.xcassets/token.imageset/token@3x.png
  ios/StatusIm/Images.xcassets/watch.imageset/Contents.json
  ios/StatusIm/Images.xcassets/watch.imageset/watch.png
  ios/StatusIm/Images.xcassets/watch.imageset/watch@2x.png
  ios/StatusIm/Images.xcassets/watch.imageset/watch@3x.png
Labels: skip-manual-qa

#8451 add a Jenkinsfile for nightly end-to-end tests
  ci/Jenkinsfile.nightly-end-to-end
  ci/android.groovy
  test/appium/support/testrail_report.py
Labels: jenkins

#8513 Fix for 4 e2e
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#8510 [#8509] Assets list is not fully scrollable on iOS
  src/status_im/ui/screens/chat/input/animations/expandable.cljs
  src/status_im/ui/screens/chat/styles/animations.cljs
Labels: Tested - OK

#8487 Resolve ENS name in chats and profiles
  src/status_im/accounts/core.cljs
  src/status_im/accounts/update/core.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/contact/core.cljs
  src/status_im/ens/core.cljs
  src/status_im/ethereum/ens.cljs
  src/status_im/notifications/core.cljs
  src/status_im/transport/message/contact.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK

#8494 Move installations to status-go
  STATUS_GO_SHA256
  STATUS_GO_VERSION
  externs.js
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/desktop/rctstatus.h
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/accounts/login/core.cljs
  src/status_im/data_store/installations.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/native_module/impl/module.cljs
  src/status_im/pairing/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/utils/fx.cljs
  test/cljs/status_im/test/pairing/core.cljs
Labels: Tested - OK

#8511 Don't provide --apk=, it's already there
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.nightly-end-to-end
  ci/android.groovy
  ci/ios.groovy
Labels: jenkins

#8522 don't raise exception on testrail api errors
  test/appium/support/testrail_report.py
Labels: jenkins, tests

#8453 [8452] remove scroll-view hack
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, community

#8520 [#8507] fixed unknown recipient
  src/status_im/ui/screens/signing/views.cljs
Labels: Tested - OK

#8523 Disable e2e until 8234 merged
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
Labels: skip-manual-qa, tests

#8514 Use a signal for messages
  STATUS_GO_SHA256
  STATUS_GO_VERSION
  src/status_im/accounts/logout/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/transport/message/core.cljs
  test/cljs/status_im/test/transport/core.cljs
  test/cljs/status_im/test/transport/filters/core.cljs
Labels: Tested - OK

#8444 Two-pane UI on large screens
  clj-rn.conf.edn
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
  react-native/src/desktop/status_im/react_native/js_dependencies.cljs
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/constants.cljs
  src/status_im/events.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/utils/dimensions.cljs
  src/status_im/utils/navigation.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
  translations/en.json
Labels: Tested - OK

#8517 upgrade react-native: 0.59.9 > 0.59.10
  ios/Podfile.lock
  mobile_files/package.json.orig
  mobile_files/yarn.lock
Labels: Tested - OK, react-native

#8524 new wallet sign with keycard flow
  resources/images/ui/keycard-logo.png
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/signing/core.cljs
  src/status_im/signing/keycard.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/signing/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8536 add missing android sdk license acceptance in nix
  default.nix
Labels: jenkins, nix

#8539 [#8506] [#8408] fixes signing panel
  src/status_im/ui/screens/signing/styles.cljs
  src/status_im/ui/screens/signing/views.cljs
Labels: Tested - OK

#8350 [TESTS] Performance: time to load sign in screen (no save password)
  test/appium/tests/base_test_case.py
  test/appium/tests/marks.py
  test/appium/tests/test_performance.py
Labels: skip-manual-qa, tests

#8547 Fix onboarding notifications request
  src/status_im/accounts/create/core.cljs
Labels: Tested - OK

#8542 Onboarding sign-in
  env/dev/env/config.cljs
  src/status_im/accounts/create/core.cljs
  src/status_im/accounts/login/core.cljs
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/ui/components/text_input/styles.cljs
  src/status_im/ui/screens/accounts/login/styles.cljs
  src/status_im/ui/screens/accounts/login/views.cljs
  src/status_im/ui/screens/accounts/styles.cljs
  src/status_im/ui/screens/accounts/views.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/utils/utils.cljs
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/cljs/status_im/test/notifications/core.cljs
  translations/en.json
Labels: Tested - OK

#8543 Enable stickers on all envs. Use contenthash to identify stickers
  .env
  .env.jenkins
  .env.nightly
  .env.prod
  src/status_im/chat/models/input.cljs
  src/status_im/events.cljs
  src/status_im/stickers/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/db.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/stickers/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/contenthash.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/stickers/core.cljs
Labels: Tested - OK

#8518 [#8502] recover key to keycard
  src/status_im/events.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/ui/screens/hardwallet/setup/subs.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
Labels: Tested - OK, keycard

#8559 e2e fix after new onboarding
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
Labels: skip-manual-qa, tests

#8565 Fix repeated key generation
  src/status_im/accounts/create/core.cljs
Labels: Tested - OK

#8562 Fixed `make startdev-desktop` issue
  desktop_files/package.json.orig
  desktop_files/yarn.lock
  src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
Labels: Tested - OK, desktop

#8571 E2e nightly fixes
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/test_performance.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8553 Update ko.json
  translations/ko.json
Labels: Tested - OK, translations

#8575 Fix Hide 'add account' option in wallet
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: Tested - OK, bounty, community, release

#8587 fix release builds by renaming .env.prod to .env.release
  .env.nightly.staging.fleet
  .env.release
  ci/utils.groovy
  fastlane/Fastfile
Labels: jenkins, release

#8576 [DO NOT MERGE!][8570] Fix Hide 'Chat settings' from ENS usernames section
  src/status_im/ui/screens/ens/views.cljs
Labels: Tested - OK, bounty, community, release

#8592 Fixed e2e tests
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/send_transaction_view.py
Labels: skip-manual-qa, tests

#8420 Update zh_Hans_CN.json and zh_hans.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: translations

#8611 fix caching od status-go, improve update-status-go.sh script
  ci/Jenkinsfile.nix-cache
  default.nix
  nix/README.md
  nix/derivation.nix
  nix/nix.conf
  nix/status-go/default.nix
  scripts/update-status-go.sh
  status-go-version.json
Labels: jenkins, nix

#8599 [DO NOT MERGE!][8566] Feature - Build v1.0 banner & modal to highlight breaking change
  resources/images/ui/large-badge.png
  resources/images/ui/large-badge@2x.png
  resources/images/ui/large-badge@3x.png
  resources/images/ui/small-badge.png
  resources/images/ui/small-badge@2x.png
  resources/images/ui/small-badge@3x.png
  src/status_im/constants.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/ui/components/status_bar/view.cljs
  src/status_im/ui/screens/announcements/views.cljs
  src/status_im/ui/screens/browser/open_dapp/styles.cljs
  src/status_im/ui/screens/browser/open_dapp/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/modals.cljs
  src/status_im/ui/screens/routing/screens.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  test/cljs/status_im/test/sign_in/data.cljs
  translations/en.json
Labels: Tested - OK, bounty, community, release

#8557 Import keycard account to new phone
  resources/images/ui/keycard-empty.png
  resources/images/ui/status-logo.png
  src/status_im/events.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/ui/screens/hardwallet/setup/subs.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/keycard/styles.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/routing/intro_login_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  translations/en.json
Labels: Tested - OK, keycard

#8613 [TESTS] Updated test_home_view with new onboarding flow
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/views/sign_in_view.py
Labels: skip-manual-qa, tests

#8607 [#7723] Stickers are not tappable right after install
  src/status_im/stickers/core.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
Labels: Tested - OK, release

#8621 add --reset-cache to stop metro-cache from growing
  scripts/build-desktop.sh
Labels: desktop, jenkins

#8619 rename prod-build to jsbundle so it means something
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.windows
  ci/desktop.groovy
  nix/derivation.nix
  nix/mobile/android/default.nix
  nix/mobile/android/targets/release-android.nix
  nix/mobile/default.nix
  nix/targets/jsbundle.nix
  project.clj
  scripts/build-desktop.sh
  scripts/release-android.sh
Labels: clojure, jenkins, nix

#8620 [TESTS] Fixed false failed tests
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/views/base_element.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
Labels: skip-manual-qa, tests

#8615 Integrate status-go protocol library
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/pairing/core.cljs
  src/status_im/ui/screens/pairing/views.cljs
  status-go-version.json
Labels: Tested - OK

#8589 [8556] fix - Last message jumps up after chat is opened
  src/status_im/chat/models.cljs
  src/status_im/ui/components/connectivity/styles.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/desktop/main/chat/views.cljs
  src/status_im/ui/screens/home/filter/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK, community, release

#8614 nix: fix target OS for add-nix-gcroots.sh
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  scripts/add-nix-gcroots.sh
Labels: nix, skip-manual-qa

#8634 [TESTS] False failed tests fixed - chat, browsing, deeps links, transactions
  test/appium/support/utilities.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#8594 Status go/integrate permissions api
  src/status_im/browser/core.cljs
  src/status_im/browser/permissions.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/data_store/browser.cljs
  src/status_im/data_store/core.cljs
  src/status_im/data_store/dapp_permissions.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/node/core.cljs
  src/status_im/protocol/core.cljs
  src/status_im/utils/fx.cljs
  test/cljs/status_im/test/sign_in/flow.cljs
Labels: Tested - OK

#8628 [#8626] Term 'Recovery phrase' should be used instead of 'seed phrase'
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/views/profile_view.py
  translations/en.json
Labels: Tested - OK, release

#8637 [#8631] Fix sticker price UI
  android/app/src/main/res/drawable-mdpi/price.png
  android/app/src/main/res/drawable-xhdpi/price.png
  android/app/src/main/res/drawable-xxhdpi/price.png
  ios/StatusIm/Images.xcassets/price.imageset/Contents.json
  ios/StatusIm/Images.xcassets/price.imageset/price.png
  ios/StatusIm/Images.xcassets/price.imageset/price@2x.png
  ios/StatusIm/Images.xcassets/price.imageset/price@3x.png
  src/status_im/ui/screens/stickers/views.cljs
Labels: Tested - OK, release

#8642 fix #8639
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK, release

#8641 fix #8636
  src/status_im/ui/components/connectivity/view.cljs
Labels: Tested - OK

#8643 fix #8580 typo in ios permission dialog
  ios/StatusIm/Info.plist
Labels: skip-manual-qa

#8640 [fix #8638] issues with wallet transaction list
  src/status_im/ethereum/transactions/core.cljs
Labels: Tested - OK

#8649 [#8648] Packs aren't shown in mainnet but we have them in the contract
  src/status_im/events.cljs
  src/status_im/stickers/core.cljs
Labels: Tested - OK, release

#8574 nix: Use build.sh for release-android make target
  .gitignore
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nix-cache
  ci/android.groovy
  ci/nix.groovy
  fastlane/Fastfile
  nix/build.sh
  nix/clean.sh
  nix/mobile/android/maven-and-npm-deps/default.nix
  nix/mobile/android/targets/release-android.nix
  nix/mobile/ios/default.nix
  nix/shell.sh
  nix/targets/jsbundle.nix
  scripts/release-android.sh
  shell.nix
Labels: nix, skip-manual-qa

#8654 [TESTS] Re-enabled and updated e2e tests
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/base_test_case.py
  test/appium/views/base_view.py
  test/appium/views/wallet_view.py
Labels: skip-manual-qa, tests

#8669 [TESTS] E2E tests false failures fixes
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/home_view.py
Labels: skip-manual-qa, tests

#8668 nix: use sha1 for status-go output filename
  modules/react-native-status/android/build.gradle
  nix/status-go/default.nix
Labels: nix, skip-manual-qa

#8644 Add datasync,v1messages & disable discovery topic
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/node/core.cljs
  src/status_im/ui/screens/desktop/main/tabs/profile/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#8674 [#8673] Temporay hide commands from chat and extensions
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.release
  src/status_im/chat/commands/core.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  test/cljs/status_im/test/chat/commands/core.cljs
  test/cljs/status_im/test/chat/commands/input.cljs
Labels: Tested - OK

#8652 use nix shell for nix-update-* targets, fix nix-cache
  Makefile
  ci/Jenkinsfile.nix-cache
  nix/README.md
  nix/desktop/realm-node/generate-nix.sh
  nix/mobile/android/maven-and-npm-deps/default.nix
  nix/mobile/android/maven-and-npm-deps/maven/generate-nix.sh
  nix/shell.sh
  nix/tools/lein/generate-nix.sh
  scripts/add-nix-gcroots.sh
  shell.nix
Labels: jenkins, nix

#8671 Fix loading of filters
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/transport/filters/core.cljs
  test/cljs/status_im/test/transport/filters/core.cljs
Labels: skip-manual-qa
