Repository status-im/status-mobile, pull requests merged in 2020-08, with the labels that each got.

#10620 Add referral share link ui
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.release
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  src/mocks/js_dependencies.cljs
  src/quo/components/text.cljs
  src/quo/design_system/colors.cljs
  src/status_im/acquisition/advertiser.cljs
  src/status_im/acquisition/chat.cljs
  src/status_im/acquisition/claim.cljs
  src/status_im/acquisition/core.cljs
  src/status_im/acquisition/gateway.cljs
  src/status_im/acquisition/install_referrer.cljs
  src/status_im/acquisition/persistance.cljs
  src/status_im/chat/models.cljs
  src/status_im/ethereum/contracts.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/tokens.cljs
  src/status_im/events.cljs
  src/status_im/keycard/fx.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/notifications/core.cljs
  src/status_im/ui/components/invite/advertiser.cljs
  src/status_im/ui/components/invite/chat.cljs
  src/status_im/ui/components/invite/events.cljs
  src/status_im/ui/components/invite/style.cljs
  src/status_im/ui/components/invite/utils.cljs
  src/status_im/ui/components/invite/views.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/profile/models.cljs
  src/status_im/ui/screens/routing/main.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/http.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  translations/en.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#11028 Switch to WebView version that doesn't silently grant camera permission
  package.json
  yarn.lock
Labels: 1.5, Tested - OK, request-manual-qa

#11030 upgrade Gems, Fastlane from 2.146.1 to 2.154.0
  fastlane/Gemfile.lock
  fastlane/gemset.nix
Labels: dependencies, nix

#11049 Regression e2e fix
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/profile_view.py
Labels: tests

#11040 Home show search when input is focused or has content
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK

#11057 eip-1193 fix
  resources/js/provider.js
Labels: blocker, high-priority, high-severity, request-manual-qa

#11063 ci: fix Android release builds not splitting ABIs
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
Labels: jenkins, release

#11033 Fix text input animations lags
  src/status_im/ui/screens/chat/components/accessory.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/components/style.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, request-manual-qa

#11016 replace camera library
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  src/status_im/ui/components/camera.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  yarn.lock
Labels: Tested - OK

#11014 Add universal qr scanner
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/status_im/events.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/router/core.cljs
  src/status_im/router/core_test.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/ui/screens/wallet/send/sheets.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/utils/universal_links/core_test.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet/core.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#11067 [WIP] e2e fixes + new tests
  src/status_im/ui/screens/home/sheet/views.cljs
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/elements_templates/url_1.png
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: tests

#11065 Clear home filter when opening chats
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: Tested - OK, request-manual-qa

#11083 e2e fixes + emoji test
  src/status_im/ui/screens/chat/message/reactions_picker.cljs
  src/status_im/ui/screens/chat/message/reactions_row.cljs
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/message_image_receiver.png
  test/appium/views/elements_templates/message_image_sender.png
Labels: tests

#11007 [#9986] Allow to disable fetching of tx history on mobile network
  .env.jenkins
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/i18n_test.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/network/net_info.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/mobile_network_settings/events.cljs
  src/status_im/ui/screens/sync_settings/views.cljs
  src/status_im/wallet/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#11088 [TESTS] nightly fixes
  src/status_im/ui/screens/wallet/accounts/views.cljs
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/views/wallet_view.py
Labels: tests

#11094 upgrade status-go & always call start/stop methods
  src/status_im/wallet/core.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#11079 Update translations
  translations/ar.json
  translations/de.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#11093 Fix topbar in new contact
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/intro/password.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
Labels: Tested - OK

#11090 Use the new intent link for private chat
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NewMessageSignalHandler.java
Labels: Tested - OK

#11095 Fix crash when passcode disabled
  src/status_im/multiaccounts/login/core.cljs
Labels: Tested - OK

#11097 [TESTS] remaining fixes
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/views/wallet_view.py
Labels: tests

#11082 Subheader generation performance improved
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: Tested - OK

#11104 [TESTS] e2e false failures fixes
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/base_view.py
Labels: tests

#11107 Simplify tabbar animation
  src/quo/animated.cljs
  src/status_im/ui/components/tabbar/core.cljs
  src/status_im/ui/components/tabbar/styles.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/views.cljs
Labels: Tested - OK

#11114 e2e for sync in group chat and for starting chat from search input
  src/status_im/ui/screens/chat/message/message.cljs
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/url_1.png
Labels: tests

#11112 Restrict amount of characters in typed message
  src/status_im/chat/constants.cljs
  src/status_im/ui/screens/chat/components/input.cljs
Labels: Tested - OK, request-manual-qa

#11099 Update translations
  translations/ar.json
  translations/de.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#11096 Use monospace font for address and public-key
  src/status_im/ui/components/profile_header/view.cljs
  src/status_im/ui/components/typography.cljs
  src/status_im/ui/screens/add_new/new_chat/styles.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/multiaccounts/login/styles.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/account_settings/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/ui/screens/wallet/custom_tokens/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im/ui/screens/wallet/transactions/styles.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK, request-manual-qa
