Repository status-im/status-mobile, pull requests merged in 2020-07, with the labels that each got.

#10894 Add autoscroll and animation to intro carousel
  src/quo/animated.cljs
  src/quo/react_native.cljs
  src/status_im/ui/screens/intro/carousel.cljs
  src/status_im/ui/screens/intro/styles.cljs
  src/status_im/ui/screens/intro/views.cljs
Labels: UI tested - OK

#10887 [#10868] ENS name is pending when tx has failed
  src/status_im/ens/core.cljs
  src/status_im/ui/screens/ens/views.cljs
Labels: Tested - OK, request-manual-qa

#10879 Update translations
  translations/ar.json
  translations/de.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10861 Disable Register button if not enough SNT for ENS name
  src/status_im/ethereum/tokens.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/ens/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#10900 Onboarding headers style
  src/status_im/ui/screens/intro/styles.cljs
Labels: Tested - OK

#10877 [#10105] Add set max to Send transaction
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/goog/i18n.cljs
  src/status_im/signing/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/wallet/core.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#10903 Use new user instead recovered because message may not be received quick
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/views/base_element.py
Labels: tests

#10906 [keycard] Fix assets message signature
  src/status_im/hardwallet/sign.cljs
Labels: Tested - OK

#10907 ci: fix what version is set for iOS PR builds
  .gitignore
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.windows
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/scripts/set_xcode_version.sh
Labels: ios

#10909 Update translations
  translations/ar.json
  translations/fil.json
  translations/ko.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10918 Fix keycard e2e
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
Labels: tests

#10896 [#10891] Add 'Add new contact' and 'Invite friends' button to Contact…
  src/status_im/events.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/routing/main.cljs
  translations/en.json
Labels: Tested - OK, UI tested - OK, request-manual-qa

#10916 Followup fixes after Quo integration
  src/quo/animated.cljs
  src/quo/components/animated/pressable.cljs
  src/quo/components/bottom_sheet/view.cljs
  src/quo/components/list/item.cljs
  src/quo/components/text_input.cljs
Labels: Tested - OK

#10926 Update ethro key in e2e
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/views/wallet_view.py
Labels: tests

#10847 [#10195] Separate keystore dir per multiacc
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/hardwallet/common.cljs
  src/status_im/hardwallet/real_keycard.cljs
  src/status_im/hardwallet/simulated_keycard.cljs
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/login/flow_test.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/node/core.cljs
  src/status_im/wallet/accounts/core.cljs
  status-go-version.json
Labels: Tested - OK

#10929 Quo left over components in ens screen
  src/quo/animated.cljs
  src/quo/components/animated/pressable.cljs
  src/quo/components/controls/view.cljs
  src/status_im/ui/screens/ens/views.cljs
  test/appium/views/dapps_view.py
  test/appium/views/wallet_view.py
Labels: Tested - OK

#10920 [keycard] Allow to restore kk multiacc using pairing
  src/status_im/hardwallet/sign.cljs
  src/status_im/hardwallet/simulated_keycard.cljs
  src/status_im/hardwallet/test_menu.cljs
  src/status_im/signing/keycard.cljs
  src/status_im/ui/screens/hardwallet/setup/subs.cljs
Labels: Tested - OK

#10927 [#10784] Fix kk multiacc creation after closing app
  src/status_im/hardwallet/common.cljs
Labels: Tested - OK

#10933 Update scroll to element
  test/appium/views/base_element.py
  test/appium/views/base_view.py
Labels: tests

#10931 upgrade shadow
  package.json
  shadow-cljs.edn
  src/shadow/cljs/devtools/client/react_native.cljs
  src/status_im/android/platform.cljs
  src/status_im/ios/platform.cljs
  src/status_im/reloader.cljs
  src/status_im/utils/platform.cljs
  yarn.lock
Labels: Tested - OK

#10939 Logcat grep, new templates e2e fix
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/elements_templates/url_1.png
  test/appium/views/elements_templates/url_2.png
  test/appium/views/elements_templates/url_3.png
  test/appium/views/wallet_view.py
Labels: tests

#10930 bump status-react-jenkins to 1.2.0
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  fastlane/Fastfile
  nix/mobile/android/release.nix
Labels: Tested - OK, jenkins

#10946 [New e2e] separate keystore
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10944 [WIP] Start scroll from 25% of page height
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_keycard_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/views/base_element.py
  test/appium/views/wallet_view.py
Labels: tests

#10951 Don't re-open bottom sheet if now closing
  src/quo/components/bottom_sheet/view.cljs
Labels: Tested - OK, request-manual-qa

#10959 [#10914] Show proper username in chat on opening from background
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: 1.5, Tested - OK

#10960 nix: fix conditional that selects .env.e2e for ABI=x86 builds
  nix/mobile/android/release.nix
Labels: Tested - OK, android, nix, tests

#10962 [New e2e] e2e for contact view
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/contacts_view.py
  test/appium/views/profile_view.py
Labels: tests

#10958 [#10928] Always show blocked users
  src/status_im/ui/screens/contacts_list/views.cljs
Labels: 1.5, Tested - OK

#10950 Disable by default list item animations on android
  src/mocks/js_dependencies.cljs
  src/quo/components/list/item.cljs
  src/quo/gesture_handler.cljs
Labels: Tested - OK

#10956 Update translations
  translations/ar.json
  translations/de.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10970 Fix images issues
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  src/status_im/chat/models/images.cljs
  src/status_im/ui/screens/chat/image/views.cljs
  src/status_im/utils/image_processing.cljs
  test/appium/tests/atomic/chats/test_one_to_one.py
  yarn.lock
Labels: Tested - OK, request-manual-qa

#10873 New UI for chat input
  package.json
  resources/images/icons/keyboard@2x.png
  resources/images/icons/keyboard@3x.png
  src/mocks/js_dependencies.cljs
  src/quo/animated.cljs
  src/quo/components/bottom_sheet/view.cljs
  src/quo/design_system/colors.cljs
  src/quo/gesture_handler.cljs
  src/quo/react_native.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/animation.cljs
  src/status_im/ui/screens/chat/components/accessory.cljs
  src/status_im/ui/screens/chat/components/hooks.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/components/reply.cljs
  src/status_im/ui/screens/chat/components/style.cljs
  src/status_im/ui/screens/chat/extensions/views.cljs
  src/status_im/ui/screens/chat/image/views.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/chat/message/datemark.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/styles/input/input.cljs
  src/status_im/ui/screens/chat/styles/input/send_button.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/views.cljs
  src/status_im/wallet/core.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/message_image_receiver.png
  test/appium/views/elements_templates/message_image_sender.png
  translations/en.json
  yarn.lock
Labels: Tested - OK, UI tested - OK, request-manual-qa

#10971 Add e2e test for PN
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#10966 Allow nested touchable in list item
  src/mocks/js_dependencies.cljs
  src/quo/gesture_handler.cljs
  src/status_im/ui/screens/signing/views.cljs
Labels: Tested - OK, request-manual-qa

#10984 [TESTS] fix 22.07.20 nightly failures
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10989 sign_in keycard e2e fix
  test/appium/views/sign_in_view.py
Labels: tests

#10981 Fix parens on intro screens
  src/status_im/ui/screens/intro/views.cljs
Labels: Tested - OK

#10987 Update translations
  translations/ar.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/it.json
  translations/ko.json
  translations/pt_BR.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10998 set max button in dark mode
  src/status_im/ui/screens/wallet/send/styles.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK

#10955 [#10195] Delete multiaccount
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/quo/components/separator.cljs
  src/quo/core.cljs
  src/quo/design_system/colors.cljs
  src/status_im/events.cljs
  src/status_im/native_module/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/privacy_and_security_settings/delete_profile.cljs
  src/status_im/ui/screens/privacy_and_security_settings/events.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  status-go-version.json
  translations/en.json
Labels: request-manual-qa

#11002 image reply fix
  src/status_im/ui/screens/chat/components/reply.cljs
Labels: 1.5

#10810 audio messages
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm/Info.plist
  ios/StatusImPR/Info.plist
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  resources/images/icons/pause@2x.png
  resources/images/icons/pause@3x.png
  resources/images/icons/play@2x.png
  resources/images/icons/play@3x.png
  resources/images/icons/speech@2x.png
  resources/images/icons/speech@3x.png
  src/status_im/audio/core.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/events.cljs
  src/status_im/native_module/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/components/permissions.cljs
  src/status_im/ui/components/slider.cljs
  src/status_im/ui/screens/chat/audio_message/styles.cljs
  src/status_im/ui/screens/chat/audio_message/views.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/components/style.cljs
  src/status_im/ui/screens/chat/message/audio.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/audio.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/utils/fs.cljs
  status-go-version.json
  translations/en.json
  yarn.lock
Labels: Tested - OK, UI tested - OK

#11005 [TESTS] updated e2e - PNs, set max
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/elements_templates/enabled_toggle.png
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#10997 [#10988] Add entry point to start new chat from search results
  resources/images/icons/private_chat@2x.png
  resources/images/icons/private_chat@3x.png
  src/status_im/ui/components/toolbar.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/home/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#11009 Update translations
  translations/ar.json
  translations/de.json
  translations/en.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#11019 nix: allow XCode versions 11.5 and higher
  nix/overlay.nix
  nix/pkgs/xcodeenv/compose-xcodewrapper.nix
  nix/tools/utils.nix
Labels: ios, nix

#10912 Add reactions picker UI
  package.json
  resources/images/reactions/angry.png
  resources/images/reactions/angry@2x.png
  resources/images/reactions/angry@3x.png
  resources/images/reactions/laugh.png
  resources/images/reactions/laugh@2x.png
  resources/images/reactions/laugh@3x.png
  resources/images/reactions/love.png
  resources/images/reactions/love@2x.png
  resources/images/reactions/love@3x.png
  resources/images/reactions/sad.png
  resources/images/reactions/sad@2x.png
  resources/images/reactions/sad@3x.png
  resources/images/reactions/thumbs-down.png
  resources/images/reactions/thumbs-down@2x.png
  resources/images/reactions/thumbs-down@3x.png
  resources/images/reactions/thumbs-up.png
  resources/images/reactions/thumbs-up@2x.png
  resources/images/reactions/thumbs-up@3x.png
  src/quo/animated.cljs
  src/quo/components/controls/view.cljs
  src/quo/components/list/item.cljs
  src/quo/components/text_input.cljs
  src/quo/gesture_handler.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/reactions.cljs
  src/status_im/constants.cljs
  src/status_im/core.cljs
  src/status_im/data_store/reactions.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/subs.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/message/audio.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/reactions.cljs
  src/status_im/ui/screens/chat/message/reactions_picker.cljs
  src/status_im/ui/screens/chat/message/reactions_row.cljs
  src/status_im/ui/screens/chat/message/styles.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/chat/styles/photos.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/utils/profiler.clj
  src/status_im/utils/profiler.cljs
  status-go-version.json
  translations/en.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#11018 [TESTS] align e2e with reactions
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/message_image_receiver.png
  test/appium/views/elements_templates/message_image_sender.png
Labels: tests
