Repository status-im/status-mobile, pull requests merged in 2020-10, with the labels that each got.

#11275 fix availability of INFURA_TOKEN for Android build
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  nix/mobile/android/jsbundle/default.nix
  nix/mobile/android/release.nix
Labels: android, jenkins

#11008 add F-Droid update README file
  doc/FDROID.md
Labels: docs

#11267 [TESTS] Set recipient e2e
  .github/CODEOWNERS
  src/status_im/ui/screens/wallet/recipient/views.cljs
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/users.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#11274 [#11263] Entering "0x" in the Recipient throws an error
  src/status_im/ui/screens/wallet/recipient/views.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet/recipient/core.cljs
Labels: Tested - OK, request-manual-qa

#11284 [#11283] Blank view when open yearn.finance in Status WebView
  resources/js/provider.js
Labels: Tested - OK

#11053 Add dinamically toggling webview debug on android
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
Labels: Tested - OK, request-manual-qa

#11277 nix: add support for INFURA_TOKEN var for Android build
  nix/lib/checkEnvVarSet.nix
  nix/lib/default.nix
  nix/mobile/android/jsbundle/default.nix
  nix/mobile/android/release.nix
  scripts/release-android.sh
Labels: android, nix

#11266 Use regular react-native-webview
  package.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#11289 Fix the wrong Playstore title and description in Spanish
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/es-ES/short_description.txt
  fastlane/metadata/android/es-ES/title.txt
Labels: translations

#11294 Upate translation
  translations/ar.json
  translations/de.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: 1.8, translations

#11287 Disable backup faucet in some tests
  test/appium/tests/__init__.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/home_view.py
Labels: tests

#11293 Nightly fixes
  src/status_im/ui/screens/privacy_and_security_settings/delete_profile.cljs
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/base_test_case.py
  test/appium/views/dapps_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#11279 [#11192] Prevent replacing of mention with pubkey inside markdown
  src/status_im/chat/models/mentions.cljs
  src/status_im/chat/models/mentions_test.cljs
Labels: request-manual-qa

#11292 [Fixes: #11290] Increase group size to 20
  src/status_im/constants.cljs
Labels: Tested - OK, request-manual-qa

#11298 Fix webview toggle crash ios
  src/status_im/multiaccounts/core.cljs
Labels: Tested - OK, request-manual-qa

#11302 Group chat invitation actions
  src/status_im/constants.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/group.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
Labels: Tested - OK, request-manual-qa

#11303 [#11041] Hardly visible username on replies in dark mode
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/utils.cljs
Labels: 1.8, Tested - OK, request-manual-qa

#11304 nix: add info about NDK bundle download issues
  nix/KNOWN_ISSUES.md
Labels: android, docs, nix

#11306 Fix coming back from offline
  src/status_im/chat/models.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/core_test.cljs
Labels: Tested - OK

#11308 Update translation for v1.8
  translations/ar.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/id.json
  translations/ko.json
  translations/pt.json
  translations/pt_BR.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: 1.8, translations

#11300 e2e mentions
  src/status_im/ui/components/search_input/view.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/contacts_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#11307 Markdown updates
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  status-go-version.json
Labels: Tested - OK

#11315 Add test to send Max tokens from wallet
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/users.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#11330 [TESTS] collectible e2e
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/views/wallet_view.py
Labels: tests

#11331 nix: make status-go matching regex more lax
  nix/tools/utils.nix
Labels: nix, release, status-go

#11260 My status
  src/quo/components/list/item.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message_list.cljs
  src/status_im/chat/models_test.cljs
  src/status_im/contact/block.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/events.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/ui/components/plus_button.cljs
  src/status_im/ui/components/profile_header/view.cljs
  src/status_im/ui/components/tabbar/core.cljs
  src/status_im/ui/components/tabs.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/chat/styles/input/gap.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/profile/contact/styles.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/my_status/views.cljs
  src/status_im/ui/screens/profile/status.cljs
  src/status_im/ui/screens/profile/user/styles.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/main.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/utils/datetime.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#11318 profile settings e2e fix
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
Labels: tests

#11339 [TESTS] small fixes nightly
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/wallet_view.py
Labels: tests

#11244 Feature local notifications
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  ios/Podfile.lock
  ios/StatusIm/AppDelegate.m
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/LocalNotificationsService.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotification.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationActions.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationJsDelivery.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationPackage.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationPicturesAggregator.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/mocks/js_dependencies.cljs
  src/status_im/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/tokens.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/navigation.cljs
  src/status_im/node/core.cljs
  src/status_im/notifications/android.cljs
  src/status_im/notifications/core.cljs
  src/status_im/notifications/local.cljs
  src/status_im/router/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/notifications_settings/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/profile_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#11320 Use ens for referrals rinkeby contract
  src/status_im/ethereum/contracts.cljs
Labels: Tested - OK

#11316 Allow sending multiple images at once
  ios/Podfile.lock
  src/quo/design_system/colors.cljs
  src/status_im/chat/models/images.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui/components/permissions.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/components/reply.cljs
  src/status_im/ui/screens/chat/image/views.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
Labels: Tested - OK

#11342 e2e refactoring
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/users.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests
