Repository status-im/status-mobile, pull requests merged in 2020-01, with the labels that each got.

#9739 Fix tabbar notification badge position
  src/status_im/ui/components/badge.cljs
  src/status_im/ui/components/tabbar/styles.cljs
Labels: Tested - OK, UI tested - OK, request-manual-qa

#9708 Move multiaccount data
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/bootnodes/core.cljs
  src/status_im/browser/core.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/settings.cljs
  src/status_im/ens/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/fleet/core.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/log_level/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/db.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/network/core.cljs
  src/status_im/node/core.cljs
  src/status_im/pairing/core.cljs
  src/status_im/stickers/core.cljs
  src/status_im/subs.cljs
  src/status_im/tribute_to_talk/core.cljs
  src/status_im/tribute_to_talk/db.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/bootnodes_settings/views.cljs
  src/status_im/ui/screens/currency_settings/models.cljs
  src/status_im/ui/screens/fleet_settings/views.cljs
  src/status_im/ui/screens/log_level_settings/views.cljs
  src/status_im/ui/screens/mobile_network_settings/events.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/profile/models.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet/collectibles/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
  status-go-version.json
  test/cljs/status_im/test/i18n.cljs
  test/cljs/status_im/test/mailserver/core.cljs
  test/cljs/status_im/test/models/bootnode.cljs
  test/cljs/status_im/test/multiaccounts/update/core.cljs
  test/cljs/status_im/test/network/core.cljs
  test/cljs/status_im/test/sign_in/data.cljs
  test/cljs/status_im/test/tribute_to_talk/core.cljs
  test/cljs/status_im/test/tribute_to_talk/whitelist.cljs
  test/cljs/status_im/test/ui/screens/currency_settings/models.cljs
  translations/ar.json
  translations/en.json
  translations/fr.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
  translations/zh.json
  translations/zh_Hans_CN.json
Labels: Tested - OK, v1 release

#9745 Reviewed TODO in e2e
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/chat_view.py
Labels: tests

#9750 Fix Align the text in the 'Add contact' snackbar to the middle
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: UI tested - OK

#9648 Add mnemonic validation
  externs.js
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/ethereum/mnemonic.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/ui/screens/multiaccounts/recover/views.cljs
  test/cljs/status_im/test/multiaccounts/recover/core.cljs
  translations/ar.json
  translations/en.json
  translations/fr.json
  translations/it.json
  translations/ko.json
  translations/zh.json
Labels: Tested - OK, community, request-manual-qa, v1 release

#9747 [#9700] toolbar-title-container minor css fix
  src/status_im/ui/components/toolbar/styles.cljs
Labels: UI tested - OK

#9753 Change safe-area from position to padding
  src/status_im/ui/components/tabbar/core.cljs
  src/status_im/ui/components/tabbar/styles.cljs
Labels: UI tested - OK, request-manual-qa

#9760 Align e2e with new translations
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#9756 Correct assets for recent stickers panel
  src/status_im/ui/screens/chat/stickers/views.cljs
Labels: UI tested - OK

#9736 Hide "[#9592]Searching Message History Coming Soon" On Chat Search And "Blocked Users" When Empty
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/home/filter/views.cljs
  test/cljs/status_im/test/i18n.cljs
  translations/ar.json
  translations/en.json
  translations/fr.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
  translations/zh.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: Tested - OK

#9765 Update invalid seed phrase copy
  translations/en.json
Labels: Tested - OK, community

#9775 upgrade fastlane: 2.133.0 > 2.139.0
  fastlane/Gemfile.lock
  fastlane/gemset.nix
Labels: dependencies

#9776 Tests/browser tests
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
Labels: tests

#9555 Make tooltips visible in page xml
  .env.e2e
  src/status_im/ui/components/tooltip/styles.cljs
  src/status_im/utils/config.cljs
Labels: request-manual-qa, tests

#9784 Changed translation for OK got it
  test/appium/views/base_view.py
Labels: tests

#9781 Fix accounts clipped on the wallet screen
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: UI tested - OK

#9791 fix #9758
  src/status_im/constants.cljs
  src/status_im/node/core.cljs
Labels: v1 release

#9793 fix 9792 custom tokens
  src/status_im/events.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
Labels: v1 release

#9797 fix pending transactions
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/events.cljs
  src/status_im/signing/core.cljs
  src/status_im/wallet/db.cljs
Labels: v1 release

#9798 normalize token addresses
  src/status_im/ethereum/tokens.cljs
Labels: v1 release

#9794 fix stickers persistence
  src/status_im/data_store/settings.cljs
  status-go-version.json
Labels: v1 release

#9796 Minor cleanup
  Makefile
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/desktop/rctstatus.cpp
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  nix/default.nix
  nix/mobile/default.nix
  nix/mobile/ios/status-go-shell.nix
  nix/scripts/shell.sh
  nix/shells.nix
  nix/status-go/default.nix
  scripts/release-android.sh
  src/status_im/native_module/core.cljs
Labels: skip-manual-qa

#9799 update Korean and Chinese translations
  translations/ko.json
  translations/zh.json
Labels: translations

#9783 add new eth.prod fleet to configuration
  .env
  .env.jenkins
  .env.nightly
  .env.release
  Makefile
  resources/config/fleets.json
  test/cljs/status_im/test/fleet/core.cljs
Labels: devops

#9807 [#9666] Missing translations on "Lock app with fingerprint", "Save wi…
  src/status_im/ui/screens/biometric/views.cljs
Labels: Tested - OK

#9780 Enable test checking tooltips
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#9827 [#9820] Tap on ENS name in public chats of other users shows own ENS …
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, request-manual-qa

#9822 fix password confirmation when restoring account
  src/status_im/multiaccounts/recover/core.cljs
Labels: Tested - OK, v1 release

#9787 move contact requests & installations to protobuf
  externs.js
  src/status_im/chat/models.cljs
  src/status_im/contact/core.cljs
  src/status_im/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/multiaccounts/update/publisher.cljs
  src/status_im/pairing/core.cljs
  src/status_im/transport/impl/receive.cljs
  src/status_im/transport/impl/send.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  test/cljs/status_im/test/pairing/core.cljs
  test/cljs/status_im/test/runner.cljs
  test/cljs/status_im/test/transport/core.cljs
Labels: Tested - OK, v1 release

#9795 Add glossary view
  src/status_im/ui/screens/glossary/view.cljs
  src/status_im/ui/screens/help_center/views.cljs
  src/status_im/ui/screens/routing/back_actions.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/routing/screens.cljs
  translations/en.json
Labels: UI tested - OK

#9757 Change ui of chat message
  android/app/src/main/assets/fonts/Inter-Bold.ttf
  android/app/src/main/assets/fonts/Inter-BoldItalic.ttf
  android/app/src/main/assets/fonts/Inter-ExtraBold.ttf
  android/app/src/main/assets/fonts/Inter-ExtraLight-BETA.ttf
  android/app/src/main/assets/fonts/Inter-ExtraLightItalic-BETA.ttf
  android/app/src/main/assets/fonts/Inter-Italic.ttf
  android/app/src/main/assets/fonts/Inter-Light-BETA.ttf
  android/app/src/main/assets/fonts/Inter-LightItalic-BETA.ttf
  android/app/src/main/assets/fonts/Inter-Medium.ttf
  android/app/src/main/assets/fonts/Inter-MediumItalic.ttf
  android/app/src/main/assets/fonts/Inter-Regular.ttf
  android/app/src/main/assets/fonts/Inter-SemiBold.ttf
  android/app/src/main/assets/fonts/Inter-SemiBoldItalic.ttf
  android/app/src/main/assets/fonts/Inter-Thin-BETA.ttf
  android/app/src/main/assets/fonts/Inter-ThinItalic-BETA.ttf
  android/app/src/main/res/drawable-hdpi/tiny_reply.png
  android/app/src/main/res/drawable-mdpi/tiny_reply.png
  android/app/src/main/res/drawable-xhdpi/tiny_reply.png
  android/app/src/main/res/drawable-xxhdpi/tiny_reply.png
  android/app/src/main/res/drawable-xxxhdpi/tiny_reply.png
  desktop/js_files/package.json
  desktop/resources/tiny_reply.png
  ios/StatusIm/Images.xcassets/tiny-reply.imageset/Contents.json
  ios/StatusIm/Images.xcassets/tiny-reply.imageset/tiny-reply.png
  ios/StatusIm/Images.xcassets/tiny-reply.imageset/tiny-reply@2x.png
  ios/StatusIm/Images.xcassets/tiny-reply.imageset/tiny-reply@3x.png
  resources/fonts/Inter-Black.otf
  resources/fonts/Inter-BlackItalic.otf
  resources/fonts/Inter-Bold.otf
  resources/fonts/Inter-BoldItalic.otf
  resources/fonts/Inter-ExtraBold.otf
  resources/fonts/Inter-ExtraBoldItalic.otf
  resources/fonts/Inter-ExtraLight-BETA.otf
  resources/fonts/Inter-ExtraLightItalic-BETA.otf
  resources/fonts/Inter-Italic.otf
  resources/fonts/Inter-Light-BETA.otf
  resources/fonts/Inter-LightItalic-BETA.otf
  resources/fonts/Inter-Medium.otf
  resources/fonts/Inter-MediumItalic.otf
  resources/fonts/Inter-Regular.otf
  resources/fonts/Inter-SemiBold.otf
  resources/fonts/Inter-SemiBoldItalic.otf
  resources/fonts/Inter-Thin-BETA.otf
  resources/fonts/Inter-ThinItalic-BETA.otf
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/ens/views.cljs
  test/appium/views/chat_view.py
Labels: Tested - OK, UI tested - OK

#9830 Align e2e with 'snackbar' animation behavior
  test/appium/tests/atomic/account_management/test_profile.py
Labels: tests

#9568 [#9288]Improve 'snackbar' animation behavior
  src/status_im/init/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/screens/db.cljs
  src/status_im/ui/screens/events.cljs
  translations/en.json
Labels: Tested - OK, UI tested - OK, community

#9834 update status-go to fix empty-account bug
  status-go-version.json
Labels: v1 release

#9837 nix: bump stalled-download-timeout to 10 minutes
  nix/README.md
  nix/nix.conf
Labels: nix, skip-manual-qa

#9825 Replace static onboarding to animated
  clj-rn.conf.edn
  components/src/status_im/react_native/resources.cljs
  fiddle/src/status_im/react_native/resources.cljs
  ios/Podfile.lock
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  nix/mobile/android/maven-and-npm-deps/maven/generate-nix.sh
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
  resources/images/ui/intro1.jpg
  resources/images/ui/intro2.jpg
  resources/images/ui/intro3.jpg
  resources/videos/browser.mp4
  resources/videos/chat.mp4
  resources/videos/keys.mp4
  resources/videos/wallet.mp4
  resources/videos/welcome.mp4
  src/status_im/ui/components/video.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/intro/views.cljs
Labels: Tested - OK, UI tested - OK, request-manual-qa

#9838 Fix android elevation in wallet card
  src/status_im/ui/screens/wallet/accounts/styles.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: design-review

#9841 Update e2e and fleet in e2e env
  .env.e2e
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/multi_account_color.png
  test/appium/views/sign_in_view.py
Labels: tests

#9836 Fix ens names & group chat add-members
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/node/core.cljs
  src/status_im/subs.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#9773 UI corrections in stickers panel
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/extensions/views.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
Labels: Tested - OK, UI tested - OK, request-manual-qa

#9743 New searchbar design
  externs.js
  src/status_im/subs.cljs
  src/status_im/ui/components/list/views.cljs
  src/status_im/ui/screens/home/filter/views.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  test/cljs/status_im/test/search/core.cljs
Labels: Tested - OK, UI tested - OK

#9854 update Korean, Russian and Chinese translations
  translations/ko.json
  translations/ru.json
  translations/zh.json
Labels: translations

#9814 send commands works directly with usernames
  src/status_im/signing/core.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/wallet/core.cljs
  status-go-version.json
  test/cljs/status_im/test/signing/core.cljs
Labels: Tested - OK, v1 release

#9858 disable waiting for iOS build processing on upload
  fastlane/Fastfile
Labels: jenkins

#9828 Leverage Nimbus Android API
  .env
  .env.jenkins
  Makefile
  nix/README.md
  nix/mobile/android/targets/release-android.nix
  nix/scripts/shell.sh
  nix/status-go/build-mobile-status-go.nix
  nix/status-go/build-status-go.nix
  nix/status-go/default.nix
  nix/status-go/nimbus/default.nix
  scripts/release-android.sh
  src/status_im/mailserver/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/core.cljs
  src/status_im/utils/config.cljs
Labels: skip-manual-qa

#9860 Rebase Android branch in Nimbus
  nix/status-go/nimbus/default.nix
Labels: nix

#9863 disable local notifications for release
  .env.release
Labels: v1 release

#9861 ci: fix GitHub upload by not changing dir when uploading
  ci/github.groovy
Labels: jenkins

#9864 transparent modals
  components/src/status_im/ui/components/react.cljs
Labels: v1 release

#9867 New fleet + current fixes
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#9862 fastlane: debug failed Diawi uploads
  ci/ios.groovy
  fastlane/Fastfile
  fastlane/Gemfile.lock
  fastlane/Pluginfile
  fastlane/gemset.nix
Labels: jenkins

#9869 Revert "Add animated onboarding videos"
  clj-rn.conf.edn
  components/src/status_im/react_native/resources.cljs
  fiddle/src/status_im/react_native/resources.cljs
  ios/Podfile.lock
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  nix/mobile/android/maven-and-npm-deps/maven/generate-nix.sh
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
  resources/images/ui/intro1.jpg
  resources/images/ui/intro2.jpg
  resources/images/ui/intro3.jpg
  resources/videos/browser.mp4
  resources/videos/chat.mp4
  resources/videos/keys.mp4
  resources/videos/wallet.mp4
  resources/videos/welcome.mp4
  src/status_im/ui/components/video.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/intro/views.cljs
Labels: Tested - OK, v1 release

#9880 Fix bug reporting
  src/status_im/transport/utils.cljs
  src/status_im/utils/logging/core.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#9881 remove chaos mode checking
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/network/net_info.cljs
Labels: Tested - OK, v1 release

#9842 Remove outdated assets
  android/app/src/main/assets/fonts/Inter-ExtraBold.ttf
  android/app/src/main/assets/fonts/Inter-ExtraBoldItalic.ttf
  android/app/src/main/assets/fonts/Inter-ExtraLight-BETA.ttf
  android/app/src/main/assets/fonts/Inter-ExtraLightItalic-BETA.ttf
  android/app/src/main/assets/fonts/Inter-Light-BETA.ttf
  android/app/src/main/assets/fonts/Inter-LightItalic-BETA.ttf
  android/app/src/main/assets/fonts/Inter-Thin-BETA.ttf
  android/app/src/main/assets/fonts/Inter-ThinItalic-BETA.ttf
  components/src/status_im/react_native/resources.cljs
  fiddle/src/status_im/react_native/resources.cljs
  ios/StatusIm.xcodeproj/project.pbxproj
  resources/fonts/Inter-Black.otf
  resources/fonts/Inter-BlackItalic.otf
  resources/fonts/Inter-ExtraBold.otf
  resources/fonts/Inter-ExtraBoldItalic.otf
  resources/fonts/Inter-ExtraLight-BETA.otf
  resources/fonts/Inter-ExtraLightItalic-BETA.otf
  resources/fonts/Inter-Light-BETA.otf
  resources/fonts/Inter-LightItalic-BETA.otf
  resources/fonts/Inter-Thin-BETA.otf
  resources/fonts/Inter-ThinItalic-BETA.otf
  resources/images/ui/analytics-image.png
  resources/images/ui/empty-hashtags.png
  resources/images/ui/empty-recent.png
  resources/images/ui/secret-keys.png
  resources/images/ui/wallet-welcome.png
  resources/images/ui/welcome-image.png
  src/status_im/ui/screens/ens/views.cljs
Labels: Tested - OK

#9744 tx fetching with less requests
  src/status_im/constants.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/node/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, v1 release

#9891 Add back missing `arm` status-go target
  nix/status-go/default.nix
Labels: nix

#9889 Remove react/modal view from android navigation
  components/src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/routing/core.cljs
Labels: Tested - OK, UI tested - OK, v1 release

#9892 ci: use full timestamp for iOS CFBundleVersion
  ci/android.groovy
  ci/utils.groovy
  scripts/version/gen_build_no.sh
Labels: ios, jenkins

#9908 nix: throw error if 'make nix-purge' is called on NixOS
  Makefile
Labels: nix

#9910 [#9280] Add retries on error when fetching balances
  src/status_im/wallet/core.cljs
Labels: v1 release

#9913 Fire request once network status changes & periodically check connection
  src/status_im/mailserver/core.cljs
  src/status_im/ui/screens/mobile_network_settings/events.cljs
  src/status_im/utils/publisher.cljs
  test/cljs/status_im/test/mailserver/core.cljs
Labels: Tested - OK, v1 release

#9916 [9853] add missing translatable labels
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  translations/en.json
Labels: v1 release

#9812 Use default keyboard for username input
  src/status_im/ui/screens/ens/views.cljs
Labels: Tested - OK

#9894 disable custom picture
  src/status_im/ui/screens/profile/user/views.cljs
Labels: v1 release

#9919 [Fixes: #9900] Use component-did-update
  src/status_im/ui/screens/chat/views.cljs
Labels: v1 release

#9921 Fix e2e after removed custom pic
  test/appium/views/profile_view.py
Labels: tests

#9923 add Augur token (REP) images
  resources/images/tokens/mainnet/REP.png
  resources/images/tokens/mainnet/REP@2x.png
  resources/images/tokens/mainnet/REP@3x.png
Labels: Tested - OK, v1 release

#9811 Open app by ens name
  src/status_im/events.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/universal_links/core.cljs
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: Tested - OK, request-manual-qa

#9935 Correctly dispatch on updates & disable them
  src/status_im/multiaccounts/update/publisher.cljs
  src/status_im/utils/publisher.cljs
Labels: v1 release

#9934 fastlane: disable oldest_build_allowed for TestFlight clean
  ci/Jenkinsfile.fastlane.clean
  fastlane/Fastfile
Labels: ios, jenkins

#9946 Explicitly start messenger
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/topics.cljs
  src/status_im/protocol/core.cljs
  src/status_im/transport/core.cljs
  status-go-version.json
Labels: v1 release

#9899 update Itanlian, Arabic, Spanish, Chinese and Korean
  prod/status_im/i18n_resources.cljs
  translations/ar.json
  translations/es_419.json
  translations/it.json
  translations/ko.json
  translations/zh.json
Labels: translations, v1 release

#9942 [#9927] Fast blocks sync after being offline
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/transactions/core.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, v1 release

#9925 fix #9903 hide buttons of actions that are not yet implemented
  src/status_im/ens/core.cljs
  src/status_im/ethereum/stateofus.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  translations/ar.json
  translations/en.json
  translations/fr.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/ru.json
  translations/zh.json
  translations/zh_Hans_CN.json
  translations/zh_hans.json
Labels: request-manual-qa, v1 release

#9951 fix hardcoded value in spanish translation
  translations/es_419.json
Labels: v1 release

#9944 Remove contact indicator from userpic
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  test/appium/views/home_view.py
  translations/en.json
Labels: UI tested - OK
