Repository status-im/status-mobile, pull requests merged in 2020-09, with the labels that each got.

#11129 Aligning react versions
  package.json
  yarn.lock
Labels: request-manual-qa

#11128 [#10974] ENS resolving for IPNS names.
  src/status_im/browser/core.cljs
  src/status_im/browser/core_test.cljs
  src/status_im/ipfs/core.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/utils/contenthash.cljs
  src/status_im/utils/contenthash_test.cljs
  src/status_im/utils/http.cljs
Labels: Tested - OK, request-manual-qa

#11121 Add Orchid ERC-20 Token (OXT)
  resources/images/tokens/mainnet/OXT.png
  resources/images/tokens/mainnet/OXT@2x.png
  resources/images/tokens/mainnet/OXT@3x.png
  src/status_im/ethereum/tokens.cljs
Labels: Tested - OK, request-manual-qa

#11119 nix: upgrade nixpkgs
  nix/overlay.nix
  nix/pkgs.nix
  nix/pkgs/gomobile/default.nix
  nix/pkgs/gomobile/deps.nix
  nix/status-go/mobile/build.nix
Labels: dependencies, nix

#11132 [TESTS] ids of failed tests + e2e fixes + new e2e
  test/appium/support/github_report.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/elements_templates/url_1.png
  test/appium/views/sign_in_view.py
Labels: tests

#11081 E2e test for audiomessages
  src/status_im/ui/screens/chat/audio_message/views.cljs
  test/appium/tests/__init__.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
Labels: tests

#11123 Update translations for the referral program
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/it.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
Labels: translations

#11134 [TESTS] new e2e + pytest marks change
  test/appium/pytest.ini
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/test_translations.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/atomic/transactions/test_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/marks.py
  test/appium/tests/test_api.py
  test/appium/tests/test_chatbot.py
  test/appium/tests/test_performance.py
  test/appium/views/base_element.py
Labels: tests

#11106 [#11046] Add local contact names
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/contact/db_test.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/reloader.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/routing/main.cljs
  translations/en.json
Labels: Tested - OK

#10937 [#10179] Create invite link for group chat
  src/status_im/acquisition/install_referrer.cljs
  src/status_im/chat/models.cljs
  src/status_im/constants.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/invitations.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/router/core.cljs
  src/status_im/router/core_test.cljs
  src/status_im/subs.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/chat/group.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/utils/http.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#11141 [TESTS] e2e for group chat links and fixes
  src/status_im/ui/screens/chat/group.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  test/appium/support/api/network_api.py
  test/appium/support/test_rerun.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/url_1.png
  test/appium/views/elements_templates/url_2.png
  test/appium/views/elements_templates/url_3.png
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#10935 IOS PNs
  .env
  .env.e2e
  .env.jenkins
  ios/Podfile.lock
  ios/StatusIm/AppDelegate.h
  ios/StatusIm/AppDelegate.m
  package.json
  resources/images/icons/tiny_muted@2x.png
  resources/images/icons/tiny_muted@3x.png
  src/mocks/js_dependencies.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models_test.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/notifications/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/notifications_settings/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/routing/main.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/utils/config.cljs
  status-go-version.json
  test/appium/views/profile_view.py
  translations/en.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#11122 Mentions suggestions
  src/quo/components/list/item.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/chat/models/mentions_test.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_test.cljs
  src/status_im/contact/core.cljs
  src/status_im/events.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/components/style.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/photos.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: Tested - OK

#11153 [TESTS] e2e false failure
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10923 fix tokens validation
  resources/images/tokens/mainnet/OST.png
  resources/images/tokens/mainnet/OST@2x.png
  resources/images/tokens/mainnet/OST@3x.png
  resources/images/tokens/mainnet/VGX.png
  resources/images/tokens/mainnet/VGX@2x.png
  resources/images/tokens/mainnet/VGX@3x.png
  resources/images/tokens/mainnet/WaBi.png
  resources/images/tokens/mainnet/WaBi@2x.png
  resources/images/tokens/mainnet/WaBi@3x.png
  resources/images/tokens/mainnet/cDAI.png
  resources/images/tokens/mainnet/cDAI@2x.png
  resources/images/tokens/mainnet/cDAI@3x.png
  resources/images/tokens/mainnet/sUSD.png
  resources/images/tokens/mainnet/sUSD@2x.png
  resources/images/tokens/mainnet/sUSD@3x.png
  src/status_im/ethereum/tokens.cljs
  src/status_im/wallet/core.cljs
Labels: request-manual-qa

#11155 Update translation
  translations/ar.json
  translations/de.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: 1.7, translations

#11157 Force transparent color for timestamp android
  src/status_im/ui/screens/chat/styles/message/message.cljs
Labels: Tested - OK, request-manual-qa

#11165 [#11150] Chat icons are black in dark mode
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: 1.7

#11167 [TESTS] nicknames e2e
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/chat_view.py
Labels: tests

#11034 Dialog added to ask permissions for webpage
  src/status_im/constants.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, design-review, request-manual-qa

#11169 Update test to copy formatted text messages
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
Labels: tests

#11162 Always use waku
  src/status_im/acquisition/gateway.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/reactions.cljs
  src/status_im/commands/core.cljs
  src/status_im/constants.cljs
  src/status_im/contact/core.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/reactions.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/mailserver/core.cljs
  src/status_im/mailserver/core_test.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/multiaccounts/update/publisher.cljs
  src/status_im/node/core.cljs
  src/status_im/notifications/core.cljs
  src/status_im/pairing/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/core.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/transport/filters/core_test.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/transport/shh.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/waku/core.cljs
  src/status_im/wallet/core.cljs
  status-go-version.json
  translations/ar.json
  translations/de.json
  translations/en.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: Tested - OK, request-manual-qa

#11188 [TESTS] nightly e2e fix
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/views/chat_view.py
Labels: tests

#11177 [mentions] highlighted mentions in input
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/components/input.cljs
Labels: 1.7, Tested - OK

#11164 [#9484] Reintroduce back collapsing of long messages in chats
  package.json
  src/mocks/js_dependencies.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_content.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  yarn.lock
Labels: 1.7, request-manual-qa

#11183 e2e wallet fixes
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#11201 Update mention suggestions on selection change
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/components/input.cljs
Labels: Tested - OK

#11195 [#10060] Wrong ERC20 decimal rounding in "Set max"
  status-go-version.json
Labels: 1.7, Tested - OK, request-manual-qa

#11199 [#11185] Add UNI, COMP, AAVE, BAL, AKRO tokens
  resources/images/tokens/mainnet/AKRO.png
  resources/images/tokens/mainnet/AKRO@2x.png
  resources/images/tokens/mainnet/AKRO@3x.png
  resources/images/tokens/mainnet/BAL.png
  resources/images/tokens/mainnet/BAL@2x.png
  resources/images/tokens/mainnet/BAL@3x.png
  resources/images/tokens/mainnet/COMP.png
  resources/images/tokens/mainnet/COMP@2x.png
  resources/images/tokens/mainnet/COMP@3x.png
  resources/images/tokens/mainnet/UNI.png
  resources/images/tokens/mainnet/UNI@2x.png
  resources/images/tokens/mainnet/UNI@3x.png
  src/status_im/ethereum/tokens.cljs
Labels: 1.7, Tested - OK

#11204 [#11136] Warning to users sending ERC20 directly to smart contract
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/wallet/recipient/core.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#11207 Parse childrens in reply text
  src/status_im/ui/screens/chat/components/reply.cljs
Labels: 1.7, request-manual-qa

#11208 [TESTS]e2e fixes
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#11206 [#11179] Nicknames in mention suggestions
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_test.cljs
  src/status_im/contact/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/components/input.cljs
Labels: 1.7, Tested - OK

#11198 Update translation for v1.7
  translations/ar.json
  translations/de.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: 1.7, translations

#11217 [#10667] Upgrade eth-phishing-detect library
  yarn.lock
Labels: 1.7, Tested - OK, request-manual-qa

#11223 override custom tokens
  src/status_im/wallet/core.cljs
Labels: 1.7, Tested - OK, request-manual-qa

#11225 ci: use more buckets for different builds
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
Labels: jenkins

#11243 [#11212] Mention suggestions based on names parts
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_test.cljs
  src/status_im/subs.cljs
Labels: Tested - OK
