Repository status-im/status-mobile, pull requests merged in 2020-04, with the labels that each got.

#10258 fix ens contenthash resolution
  src/status_im/ethereum/ens.cljs
  src/status_im/utils/contenthash.cljs
Labels: bug

#10263 Fix camera usage description
  ios/StatusIm/Info.plist
Labels: Tested - OK, request-manual-qa

#10222 Handle new universal links
  src/status_im/events.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/utils/universal_links/core.cljs
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
  test/cljs/status_im/test/utils/universal_links/core.cljs
Labels: Tested - OK, request-manual-qa, v1.3 release

#10262 Commands e2e
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/users.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#10268 E2E to receive message while in different tab
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
Labels: tests

#10267 Keycard e2e for sign up
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/views/base_view.py
  test/appium/views/keycard_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10256 Update translations
  dev/status_im/i18n_resources.cljs
  prod/status_im/i18n_resources.cljs
  translations/de.json
  translations/fr.json
  translations/it.json
  translations/ko.json
  translations/ru.json
  translations/tr.json
  translations/zh_TW.json
Labels: translations

#10269 Validate enode url when blank
  src/status_im/mailserver/core.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/cljs/status_im/test/mailserver/core.cljs
Labels: Tested - OK

#10282 Mark all as read in public and e2e fix
  test/appium/support/test_rerun.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/home_view.py
  test/appium/views/keycard_view.py
Labels: tests

#10284 fix missing asset images
  nix/mobile/android/jsbundle/default.nix
  nix/mobile/android/targets/release-android.nix
Labels: Tested - OK, android, nix

#10273 Update react-native-webview to 8.0.7_5
  ios/Podfile.lock
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
Labels: Tested - OK, request-manual-qa

#10271 Fix incorrect loading of messages
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/ui/screens/chat/state.cljs
  src/status_im/ui/screens/chat/views.cljs
  test/cljs/status_im/test/chat/models/message.cljs
Labels: Tested - OK, request-manual-qa

#10289 Tooltips e2e
  test/appium/tests/atomic/account_management/test_sign_in.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10291 Load messages on will-focus
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/ui/screens/events.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
Labels: Tested - OK

#10299 include VERSION file in jsbundle derivation source
  nix/mobile/android/jsbundle/default.nix
  nix/tools/mkFilter.nix
  src/status_im/utils/build.clj
Labels: nix

#10264 [#10199] fix No message when sending funds in 1-1 chat with keycard
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/sign.cljs
  src/status_im/signing/core.cljs
  src/status_im/signing/keycard.cljs
  src/status_im/ui/screens/chat/message/command.cljs
  src/status_im/wallet/core.cljs
Labels: Tested - OK, request-manual-qa

#10099 Update UI for group chat creation and profile
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/group_chats/db.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/button.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/components/contact/contact.cljs
  src/status_im/ui/components/contact/styles.cljs
  src/status_im/ui/components/keyboard_avoid_presentation.cljs
  src/status_im/ui/components/popup_menu/views.cljs
  src/status_im/ui/components/search_input/view.cljs
  src/status_im/ui/screens/add_new/styles.cljs
  src/status_im/ui/screens/chat/group.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/group/styles.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/group_chat/styles.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/routing/chat_stack.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/routing/main.cljs
  src/status_im/ui/screens/views.cljs
  status-go-version.json
  test/cljs/status_im/test/contacts/db.cljs
  translations/en.json
Labels: Tested - OK, design-review, request-manual-qa, v1.3 release

#10315 Refactoring of group chat tests
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_recover.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/dapps_view.py
  test/appium/views/home_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10281 Add minor improvments to text input
  src/status_im/ui/components/text_input/styles.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/styles.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK, request-manual-qa

#10280 qr testing mode, fixed qr pure address and EIP681 issues
  .env
  .env.e2e
  src/status_im/ethereum/eip681.cljs
  src/status_im/ethereum/macros.clj
  src/status_im/ethereum/subscriptions.cljs
  src/status_im/ethereum/tokens.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/message/command.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  src/status_im/ui/screens/wallet/send/sheets.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet/collectibles/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
  test/cljs/status_im/test/ethereum/eip681.cljs
Labels: Tested - OK, request-manual-qa

#10298 Add profile screen in profile stack
  src/status_im/ui/screens/routing/profile_stack.cljs
Labels: request-manual-qa

#10323 Logging in networks
  test/appium/support/api/network_api.py
Labels: tests

#10322 Update Russian, Korean, and Chinese translation
  prod/status_im/i18n_resources.cljs
  translations/ko.json
  translations/ru.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10324 update help messages in Makefile targets
  Makefile
  STARTING_GUIDE.md
Labels: docs

#9390 Add web3.keycard.signTypedData
  android/app/src/main/res/drawable-hdpi/nfc.png
  android/app/src/main/res/drawable-mdpi/nfc.png
  android/app/src/main/res/drawable-xhdpi/nfc.png
  android/app/src/main/res/drawable-xxhdpi/nfc.png
  android/app/src/main/res/drawable-xxxhdpi/nfc.png
  externs.js
  ios/StatusIm/Images.xcassets/nfc.imageset/Contents.json
  ios/StatusIm/Images.xcassets/nfc.imageset/nfc-1.png
  ios/StatusIm/Images.xcassets/nfc.imageset/nfc-2.png
  ios/StatusIm/Images.xcassets/nfc.imageset/nfc.png
  src/status_im/browser/core.cljs
  src/status_im/constants.cljs
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/common.cljs
  src/status_im/hardwallet/fx.cljs
  src/status_im/hardwallet/keycard.cljs
  src/status_im/hardwallet/real_keycard.cljs
  src/status_im/hardwallet/sign.cljs
  src/status_im/hardwallet/simulated_keycard.cljs
  src/status_im/signing/core.cljs
  src/status_im/signing/keycard.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/signing/styles.cljs
  src/status_im/ui/screens/signing/views.cljs
  translations/en.json
Labels: Tested - OK

#10308 fix #10058 wrong domain name shown when connecting .eth
  src/status_im/ethereum/stateofus.cljs
  src/status_im/ui/screens/ens/views.cljs
  test/cljs/status_im/test/ethereum/stateofus.cljs
Labels: Tested - OK

#10337 Scanning EIP links e2e
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10311 Add wallet header animation
  clj-rn.conf.edn
  ios/Podfile.lock
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
  react-native/src/mobile/status_im/react_native/js_dependencies.cljs
  src/status_im/ui/components/button/haptic.cljs
  src/status_im/ui/components/reanimated.cljs
  src/status_im/ui/components/tabbar/core.cljs
  src/status_im/ui/components/topbar.cljs
  src/status_im/ui/screens/routing/wallet_stack.cljs
  src/status_im/ui/screens/wallet/accounts/styles.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  test/cljs/status_im/react_native/js_dependencies.cljs
Labels: Tested - OK, design-review, request-manual-qa

#10307 fix #10039
  src/status_im/ui/screens/add_new/new_chat/views.cljs
Labels: v1.3 release

#10339 fix Gradle permission errors during build
  nix/mobile/android/targets/release-android.nix
Labels: android, nix

#10332 fix: strip leading and trailing whitespace from QR Code data
  src/status_im/ui/components/camera.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
Labels: Tested - OK

#10341 upgrade to Xcode 11.4
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.macos
  nix/mobile/default.nix
Labels: ios, jenkins

#10207 fix #10052 make finding the public key easier in profile
  android/app/src/main/res/drawable-hdpi/share.png
  android/app/src/main/res/drawable-mdpi/share.png
  android/app/src/main/res/drawable-xhdpi/share.png
  android/app/src/main/res/drawable-xxhdpi/share.png
  android/app/src/main/res/drawable-xxxhdpi/share.png
  src/status_im/ui/screens/profile/components/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
Labels: Tested - OK, v1.3 release

#10304 Get replies directly from status-go
  src/status_im/chat/models/message.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  status-go-version.json
  test/cljs/status_im/test/chat/models/message.cljs
Labels: request-manual-qa

#10350 upgrade Xcode to 11.4.1
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.macos
  nix/mobile/default.nix
Labels: ios, jenkins

#10343 fix #8717 change ens welcome screen
  src/status_im/ui/screens/ens/views.cljs
  test/cljs/status_im/test/i18n.cljs
  translations/ar.json
  translations/de.json
  translations/en.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/nl.json
  translations/pt.json
  translations/pt_br.json
  translations/ru.json
  translations/th.json
  translations/tr.json
  translations/zh.json
  translations/zh_Hans_CN.json
  translations/zh_TW.json
  translations/zh_hans.json
Labels: v1.3 release

#10347 [#10203] Endless spinner when sending two TX in a batch in Dapp
  src/status_im/events.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/ui/screens/currency_settings/models.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/custom_tokens/core.cljs
  src/status_im/wallet/prices.cljs
  test/appium/tests/atomic/transactions/test_daaps_transactions.py
Labels: Tested - OK, v1.3 release

#10351 fix: show message when loading new transactions instead of no tx msg
  src/status_im/ui/screens/wallet/transactions/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#10317 signals processing performance improvements [#10287]
  src/status_im/chat/models.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/pairing/core.cljs
  src/status_im/transport/filters/core.cljs
  src/status_im/transport/message/core.cljs
Labels: performance, request-manual-qa, v1.3 release

#10340 upgrade Nix packages, and a lot of dependencies
  nix/mobile/android/android-env.nix
  nix/mobile/android/default.nix
  nix/mobile/android/gradle.nix
  nix/patched-go/default.nix
  nix/pkgs.nix
  nix/status-go/default.nix
  nix/status-go/gomobile/default.nix
  nix/status-go/gomobile/deps.nix
Labels: android, dependencies, ios, nix, request-manual-qa

#10368 [#10366] App Dark mode: signing phrase+message not visible when Signi…
  src/status_im/ui/screens/signing/styles.cljs
  src/status_im/ui/screens/signing/views.cljs
Labels: v1.3 release

#10370 [#10369] App freezes on transaction signing after entering wrong pass…
  src/status_im/signing/core.cljs
Labels: Tested - OK, v1.3 release

#10374 Fix replies messages
  src/status_im/ui/screens/chat/message/message.cljs
Labels: Tested - OK

#10387 gradle: upgrade plugin to 3.6.0
  android/gradle.properties
  nix/mobile/android/maven-and-npm-deps/maven/default.nix
  nix/mobile/android/maven-and-npm-deps/maven/maven-inputs.txt
  nix/mobile/android/maven-and-npm-deps/maven/maven-sources.nix
Labels: android, dependencies, nix

#10361 Update translations
  translations/ar.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ko.json
  translations/ru.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10397 upgrade fastlane and plugins
  fastlane/Fastfile
  fastlane/Gemfile.lock
  fastlane/gemset.nix
Labels: dependencies, nix

#10401 nix: upgrade nodejs to 12.16.2
  nix/pkgs.nix
Labels: dependencies, nix

#10406 [#10396] Quoted text (using markdown) in dark mode is hardly visible
  src/status_im/ui/components/chat_icon/styles.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
Labels: Tested - OK, v1.3 release

#10405 Handle when message confirmations arrive out of order.
  src/status_im/events.cljs
  src/status_im/transport/message/core.cljs
  test/cljs/status_im/test/transport/core.cljs
Labels: request-manual-qa

#10403 bump re-frame and remove 16ms delay for reagent tick
  deps.edn
  env/dev/env/android/main.cljs
  env/dev/env/ios/main.cljs
  env/prod/env/android/main.cljs
  env/prod/env/ios/main.cljs
  nix/lein/lein-project-deps-maven-inputs.txt
  nix/lein/lein-project-deps.nix
  project.clj
Labels: performance

#10412 Bootnodes e2e
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/bootnodes_settings/views.cljs
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/zh.json
  translations/zh_Hans_CN.json
  translations/zh_TW.json
  translations/zh_hans.json
Labels: tests

#10408 fix(wallet/accounts): don't store derived account when it exists in app db
  src/status_im/wallet/accounts/core.cljs
Labels: Tested - OK, request-manual-qa

#10391 fix: prevent multiple taps on Register button from opening several tx during ENS registration
  src/status_im/ui/screens/ens/views.cljs
Labels: Tested - OK

#10354 Refactor delete account algorithm to properly remove deleted account
  src/status_im/wallet/accounts/core.cljs
Labels: Tested - OK, request-manual-qa

#10421 [#10385] [perfromance][chat] Optimize input field in chat
  src/status_im/android/core.cljs
  src/status_im/chat/models.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/specs.cljs
  src/status_im/ios/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/input/input.cljs
  src/status_im/ui/screens/chat/input/send_button.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/styles/input/input.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/db.cljs
Labels: Tested - OK, request-manual-qa

#10441 [#10418] Can login to account just via tap upon it from `Your keys` view
  src/status_im/init/core.cljs
Labels: Tested - OK, request-manual-qa

#10394 fix: add debounce to "Done" button in the recipient selection dialog
  src/status_im/ui/screens/wallet/components/views.cljs
Labels: Tested - OK

#10453 [#10432] Fix adding watch-only acc in keycard multiacc
  src/status_im/ui/screens/wallet/add_new/views.cljs
Labels: request-manual-qa

#10413 fix: display the value to sign as a bytes32 hex string if the data is 66 chars long
  src/status_im/ethereum/core.cljs
  src/status_im/signing/core.cljs
Labels: Tested - OK, request-manual-qa

#10437 nix: use overlays instead of packageOverrides
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.fastlane.clean
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.windows
  default.nix
  nix/DETAILS.md
  nix/mobile/android/default.nix
  nix/mobile/android/jsbundle/default.nix
  nix/mobile/android/maven-and-npm-deps/default.nix
  nix/mobile/android/targets/release-android.nix
  nix/mobile/default.nix
  nix/mobile/ios/default.nix
  nix/mobile/ios/pod-shell.nix
  nix/mobile/ios/status-go-shell.nix
  nix/overlay.nix
  nix/patched-go/default.nix
  nix/pkgs.nix
  nix/pkgs/gomobile/default.nix
  nix/pkgs/gomobile/deps.nix
  nix/pkgs/gomobile/resolve-nix-android-sdk.patch
  nix/pkgs/patched-go/default.nix
  nix/scripts/shell.sh
  nix/shells.nix
  nix/status-go/default.nix
  nix/status-go/mobile/default.nix
  nix/tools/envParser.nix
  nix/tools/utils.nix
  scripts/release-android.sh
  shell.nix
Labels: nix

#10458 [#10444] Fix keycard pin changing when card is not tapped
  src/status_im/hardwallet/common.cljs
Labels: Tested - OK, request-manual-qa

#10459 [#10431] Show pending txs in keycard multiacc
  src/status_im/signing/core.cljs
Labels: Tested - OK, request-manual-qa

#10457 [#10443] Remove sensitive information from keycard logs
  src/status_im/hardwallet/card.cljs
Labels: Tested - OK, request-manual-qa

#10450 [#10377] [perfromance] Improve sign in flow
  mobile/js_files/yarn.lock
  src/status_im/browser/core.cljs
  src/status_im/ui/screens/mobile_network_settings/events.cljs
  src/status_im/ui/screens/navigation.cljs
  src/status_im/ui/screens/routing/main.cljs
  src/status_im/wallet/core.cljs
  test/cljs/status_im/test/browser/core.cljs
Labels: performance, request-manual-qa

#10466 Fix e2e tests
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
Labels: Tested - OK, tests

#10330 Use a single in-progress? flag for signing
  src/status_im/signing/core.cljs
  src/status_im/ui/screens/db.cljs
  test/cljs/status_im/test/signing/core.cljs
Labels: Tested - OK, keycard, wallet
