Repository status-im/status-mobile, pull requests merged in 2020-06, with the labels that each got.

#10726 Remove inline require for json files
  src/mocks/js_dependencies.cljs
  src/status_im/i18n.clj
  src/status_im/i18n_resources.cljs
  src/status_im/i18n_test.cljs
  src/status_im/node/core.cljs
Labels: v1.4 release

#10655 Keycard: updated PUK flow
  src/status_im/hardwallet/card.cljs
  src/status_im/hardwallet/change_pin.cljs
  src/status_im/hardwallet/common.cljs
  src/status_im/hardwallet/core.cljs
  src/status_im/hardwallet/export_key.cljs
  src/status_im/hardwallet/login.cljs
  src/status_im/hardwallet/real_keycard.cljs
  src/status_im/hardwallet/sign.cljs
  src/status_im/hardwallet/simulated_keycard.cljs
  src/status_im/hardwallet/wallet.cljs
  src/status_im/i18n_test.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/navigation.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/bottom_panel/views.cljs
  src/status_im/ui/screens/hardwallet/frozen_card/view.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/hardwallet/pin/subs.cljs
  src/status_im/ui/screens/hardwallet/pin/views.cljs
  src/status_im/ui/screens/hardwallet/settings/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/keycard/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  translations/en.json
Labels: Tested - OK, v1.4 release

#10735 nix: improve nix/scripts/node_modules.sh
  nix/mobile/android/jsbundle/default.nix
  nix/scripts/node_modules.sh
  nix/shells.nix
  scripts/colors.sh
Labels: nix

#10639 Quo move bottom sheet component
  .clj-kondo/config.edn
  ios/Podfile.lock
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  src/mocks/js_dependencies.cljs
  src/quo/animated.cljs
  src/quo/components/bottom_sheet/style.cljs
  src/quo/components/bottom_sheet/view.cljs
  src/quo/components/safe_area.cljs
  src/quo/core.cljs
  src/quo/design_system/colors.cljs
  src/quo/previews/bottom_sheet.cljs
  src/quo/previews/main.cljs
  src/quo/react.clj
  src/quo/react.cljs
  src/quo/react_native.cljs
  src/status_im/ui/components/react.cljs
  src/status_im/ui/screens/views.cljs
Labels: UI tested - OK

#10333 Show redeem text for Keycard redeem txs
  src/status_im/browser/core.cljs
  src/status_im/hardwallet/common.cljs
  src/status_im/hardwallet/sign.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/keycard/keycard_interaction.cljs
  src/status_im/ui/screens/signing/views.cljs
  translations/en.json
Labels: Tested - OK, keycard

#10730 Update translations
  src/status_im/i18n_resources.cljs
  translations/ar.json
  translations/de.json
  translations/es.json
  translations/es_419.json
  translations/fil.json
  translations/ko.json
  translations/pt_br.json
  translations/tr.json
  translations/zh.json
  translations/zh_TW.json
Labels: Tested - OK, translations, v1.4 release

#10729 Handle links in profile qr code scanner
  src/status_im/events.cljs
  src/status_im/navigation.cljs
  src/status_im/ui/screens/add_new/new_chat/events.cljs
Labels: Tested - OK, request-manual-qa, v1.4 release

#10753 [Fixes #10751] Remove messages & list when blocking
  src/status_im/contact/block.cljs
Labels: Tested - OK, v1.4 release

#10749 [Fixes #10746] Correctly show reply symbol
  src/status_im/ui/screens/chat/utils.cljs
Labels: Tested - OK, v1.4 release

#10748 enable group chats
  .env.release
Labels: v1.4 release

#10752 Fix searching name of ens contacts
  src/status_im/subs.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: Tested - OK, v1.4 release

#10750 [#10744] Error at attempt to set custom-domain ENS as main
  src/status_im/subs.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
Labels: Tested - OK, request-manual-qa, v1.4 release

#10422 Show ENS name only when confirmed
  src/status_im/ens/core.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/ens/views.cljs
  translations/en.json
Labels: Tested - OK, design-review, request-manual-qa, v1.4 release

#10760 restart reader according to Activity's lifecycle
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
Labels: request-manual-qa, v1.4 release

#10763 nix: minor cleanup and documentation updates
  default.nix
  nix/DETAILS.md
  nix/README.md
  nix/lib/getConfig.nix
  nix/mobile/android/release.nix
  nix/shell.nix
  nix/shells.nix
  shell.nix
Labels: docs, nix

#10767 Restore missing asset for iOs splash screen
  ios/StatusIm/Images.xcassets/launch_image.imageset/Contents.json
  ios/StatusIm/Images.xcassets/launch_image.imageset/launch_image.png
  ios/StatusIm/Images.xcassets/launch_image.imageset/launch_image@2x.png
  ios/StatusIm/Images.xcassets/launch_image.imageset/launch_image@3x.png
Labels: v1.4 release

#10731 [#10722] Change learn about keycard link
  src/status_im/constants.cljs
  src/status_im/hardwallet/onboarding.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/keycard/views.cljs
Labels: v1.4 release

#10778 Change status-bar color on theme change
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/res/values/styles.xml
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/theme/core.cljs
Labels: Tested - OK, v1.4 release

#10792 Small fixes for nightly e2e
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/chat_view.py
Labels: tests

#10781 Webview test
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/dapps_view.py
Labels: tests

#10797 Use text inputs from Quo
  src/mocks/js_dependencies.cljs
  src/quo/components/text.cljs
  src/quo/components/text_input.cljs
  src/quo/components/tooltip.cljs
  src/status_im/network/ui/edit_network/styles.cljs
  src/status_im/network/ui/edit_network/views.cljs
  src/status_im/ui/components/search_input/styles.cljs
  src/status_im/ui/components/search_input/view.cljs
  src/status_im/ui/components/text_input/styles.cljs
  src/status_im/ui/components/text_input/view.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/styles.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/add_new/styles.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/styles.cljs
  src/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/currency_settings/views.cljs
  src/status_im/ui/screens/group/styles.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/hardwallet/pin/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/intro/views.cljs
  src/status_im/ui/screens/keycard/onboarding/views.cljs
  src/status_im/ui/screens/keycard/recovery/views.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/styles.cljs
  src/status_im/ui/screens/offline_messaging_settings/edit_mailserver/views.cljs
  src/status_im/ui/screens/pairing/styles.cljs
  src/status_im/ui/screens/pairing/views.cljs
  src/status_im/ui/screens/profile/components/styles.cljs
  src/status_im/ui/screens/profile/seed/styles.cljs
  src/status_im/ui/screens/profile/seed/views.cljs
  src/status_im/ui/screens/routing/core.cljs
  src/status_im/ui/screens/signing/sheets.cljs
  src/status_im/ui/screens/signing/styles.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/account_settings/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
  src/status_im/ui/screens/wallet/components/views.cljs
  src/status_im/ui/screens/wallet/custom_tokens/views.cljs
  src/status_im/ui/screens/wallet/settings/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#10800 e2e images
  src/status_im/ui/screens/chat/image/views.cljs
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/message_image_receiver.png
  test/appium/views/elements_templates/message_image_sender.png
Labels: tests

#10815 [#10808] Can't recover keys from keycard
  src/status_im/ui/screens/keycard/recovery/views.cljs
Labels: Tested - OK

#10816 Override padding in search text input
  src/status_im/ui/components/search_input/view.cljs
Labels: Tested - OK

#10818 [#10694] Amount is not accessible on "Send Transaction" screen when t…
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: 1.4.1, Tested - OK

#10819 [#10658] "connection is secure" tooltip is not aligned with URL field
  src/status_im/ui/components/tooltip/views.cljs
Labels: 1.4.1, Tested - OK

#10826 [#10634] Image of 'Get started' view changes height/width if navigate…
  src/status_im/ui/screens/intro/views.cljs
Labels: 1.4.1, Tested - OK

#10820 [#10424] "Offline, waiting for WiFi" chat status when Mobile network …
  translations/en.json
Labels: 1.4.1

#10821 [#10761] Copy change for iOS only
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  translations/en.json
Labels: 1.4.1, Tested - OK

#10814 e2e: fix for nightly 16/06
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#10823 [#10646] "No protocol method iMap" error when recover the same seed p…
  src/status_im/multiaccounts/recover/core.cljs
Labels: 1.4.1, Tested - OK

#10822 [#10233] Web-page splits in 2 frames when contains errors
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/views.cljs
Labels: 1.4.1, Tested - OK

#10824 Disable reload button on unsafe sites
  src/status_im/ui/screens/browser/views.cljs
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
Labels: Tested - OK

#10831 Show search cancel on android
  src/quo/components/text_input.cljs
  src/status_im/ui/components/search_input/view.cljs
Labels: Tested - OK, request-manual-qa

#10829 Update translations
  translations/ar.json
  translations/fil.json
  translations/it.json
  translations/ko.json
  translations/pt_BR.json
  translations/tr.json
Labels: translations

#10835 Fix chats search input
  src/status_im/ui/components/search_input/view.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: Tested - OK, request-manual-qa

#10837 Additional logging to etherscan response
  test/appium/support/api/network_api.py
Labels: tests

#10839 make go-maven-resolver fail when any resolution fails
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/pkgs/go-maven-resolver/default.nix
Labels: android, dependencies, nix

#10799 Update webview to 10.2.3
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
Labels: Tested - OK, security, webview

#10846 [#10253] Bottom system panel is white on dark mode on Android
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
  src/mocks/js_dependencies.cljs
  src/status_im/init/core.cljs
  src/status_im/theme/core.cljs
Labels: 1.4.1, Tested - OK

#10438 fix(multiaccounts/login): ensure log-level is updated correctly
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/subs.cljs
  src/status_im/utils/logging/core.cljs
Labels: 1.4.1, Tested - OK, request-manual-qa

#10848 Update translations
  translations/ar.json
  translations/it.json
  translations/pt_BR.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#10830 Add accessability label to Quo tooltip
  src/quo/components/text_input.cljs
  src/quo/components/tooltip.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
Labels: Tested - OK

#10393 fix: change amount-input field keyboard type and autocapitalization to display decimal separator
  src/status_im/ui/screens/wallet/send/views.cljs
Labels: Tested - OK, request-manual-qa

#10856 Add check for xss in webview
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
Labels: tests

#10859 e2e for scanning qr with chat key
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#10851 Handle encoded urls
  src/status_im/utils/security.cljs
  src/status_im/utils/security_html.cljs
  src/status_im/utils/security_html_test.cljs
  src/status_im/utils/security_test.cljs
Labels: Tested - OK

#10857 [#9037] Error states for new Tx overview: contract & network fees
  src/status_im/signing/gas.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/signing/views.cljs
  translations/en.json
Labels: 1.4.1, Tested - OK

#10858 Merge webview.js into provider.js
  resources/js/provider.js
  resources/js/webview.js
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/utils/js_resources.cljs
Labels: 1.4.1, Tested - OK

#10852 Use RN's OkHttp in webview lib
  mobile/js_files/package.json
  mobile/js_files/yarn.lock
Labels: 1.4.1, Tested - OK, request-manual-qa

#10863 Tests/transaction fee
  src/status_im/ui/screens/signing/views.cljs
  test/appium/tests/atomic/transactions/test_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/send_transaction_view.py
Labels: tests

#10866 Update translations
  translations/de.json
  translations/ko.json
  translations/pt_BR.json
Labels: translations

#10869 fixes nightly e2e
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_commands.py
Labels: tests

#10864 Quo add control components
  src/quo/animated.cljs
  src/quo/components/controls/styles.cljs
  src/quo/components/controls/view.cljs
  src/quo/components/list/item.cljs
  src/quo/core.cljs
  src/quo/previews/controls.cljs
  src/quo/previews/main.cljs
  src/quo/react.cljs
  src/quo/react_native.cljs
Labels: design-review

#10878 [#10870] "Invalid timbre logging level" after upgrade from 1.4 to 1.4…
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.release
  src/status_im/constants.cljs
  src/status_im/core.cljs
  src/status_im/desktop/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/utils/config.cljs
  src/status_im/utils/logging/core.cljs
Labels: 1.4.1, Tested - OK, request-manual-qa

#10883 nix: upgrade xcode 11.4.1 to 11.5
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.macos
  nix/overlay.nix
Labels: ios, nix

#10867 Add separate target/scheme for ios pr build
  .gitignore
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.windows
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm.xcodeproj/xcshareddata/xcschemes/StatusImPR.xcscheme
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/Contents.json
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-1024@1x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-20@2x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-20@3x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-29@2x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-29@3x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-40@2x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-40@3x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-60@2x.png
  ios/StatusIm/Images.xcassets/AppIconPR.appiconset/icon-ios-60@3x.png
  ios/StatusImPR/Info.plist
  ios/StatusImPR/StatusImPR.entitlements
Labels: request-manual-qa

#10885 use eth.staging fleet for e2e builds
  .env.e2e
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
Labels: tests
