Repository status-im/status-mobile, pull requests merged in 2021-04, with the labels that each got.

#11945 [wallet #11944] Watch confirmation of sent tx when syncing is disabled
  src/status_im/wallet/core.cljs
Labels: Tested - OK

#11941 Feature/anon metrics
  src/status_im/anon_metrics/interceptors.cljs
  src/status_im/anon_metrics/transformers.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/navigation.cljs
Labels: Tested - OK

#11939 🧽 🚿 Add missing seed phrase sanitation to key storage flow
  src/status_im/multiaccounts/key_storage/core.cljs
Labels: Tested - OK, request-manual-qa

#11969 Jenkins URL to rerun tests
  test/appium/support/base_test_report.py
  test/appium/support/github_report.py
Labels: tests

#11973 add change PUK functionality
  package.json
  src/status_im/keycard/card.cljs
  src/status_im/keycard/change_pin.cljs
  src/status_im/keycard/core.cljs
  src/status_im/keycard/fx.cljs
  src/status_im/keycard/keycard.cljs
  src/status_im/keycard/real_keycard.cljs
  src/status_im/keycard/simulated_keycard.cljs
  src/status_im/ui/screens/keycard/pin/views.cljs
  src/status_im/ui/screens/keycard/settings/views.cljs
  translations/en.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#11942 Improved Start New Private Chat interface
  src/quo/components/list/item.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  test/appium/tests/atomic/chats/test_chats_management.py
  translations/en.json
Labels: Tested - OK, UI/UX improvements, request-manual-qa

#11975 Fixed error on login with attempt to save wrong key into account
  src/status_im/chat/models/link_preview.cljs
  src/status_im/db.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/message/link_preview.cljs
  src/status_im/ui/screens/link_previews_settings/views.cljs
Labels: Tested - OK, request-manual-qa

#11919 Add Polish and update translations
  src/status_im/i18n/i18n_resources.cljs
  translations/ar.json
  translations/en.json
  translations/es.json
  translations/es_419.json
  translations/es_AR.json
  translations/fil.json
  translations/fr.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/nl.json
  translations/pl.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/zh.json
  translations/zh_TW.json
Labels: 1.13, translations

#11989 add change pairing code functionality
  ios/Podfile.lock
  src/status_im/keycard/card.cljs
  src/status_im/keycard/change_pin.cljs
  src/status_im/keycard/fx.cljs
  src/status_im/keycard/keycard.cljs
  src/status_im/keycard/real_keycard.cljs
  src/status_im/keycard/simulated_keycard.cljs
  src/status_im/ui/screens/keycard/pairing/views.cljs
  src/status_im/ui/screens/keycard/settings/views.cljs
  src/status_im/ui/screens/routing/profile_stack.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#11963 🗂️ Anon metrics batching
  src/quo/previews/main.cljs
  src/status_im/anon_metrics/core.cljs
  src/status_im/anon_metrics/interceptors.cljs
  src/status_im/anon_metrics/transformers.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/navigation.cljs
  src/status_im/utils/async.cljs
Labels: Tested - OK, request-manual-qa

#11983 align e2e with activity center
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/home_view.py
  test/appium/views/wallet_view.py
Labels: tests

#11998 CI: Generalize release functions for desktop
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/README.md
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
Labels: jenkins

#11933 Prevent incorrect usage of fx/defn inside fx/merge
  src/status_im/utils/fx.clj
Labels: Tested - OK

#11950 community link unfurling
  src/status_im/chat/models/link_preview.cljs
  src/status_im/constants.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/router/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/chat/message/link_preview.cljs
  src/status_im/ui/screens/chat/message/styles.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#11985 Add support for SOCKS token
  resources/images/tokens/mainnet/SOCKS.png
  resources/images/tokens/mainnet/SOCKS@2x.png
  resources/images/tokens/mainnet/SOCKS@3x.png
  src/status_im/ethereum/tokens.cljs
Labels: Tested - OK, feature, request-manual-qa, wallet

#11996 Add permission handling & enable HW acceleration on webview
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/wallet/buy_crypto/views.cljs
Labels: Tested - OK

#12002 e2e: align with 11988
  test/appium/requirements.txt
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
  test/appium/views/transactions_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#12005 Load message on-component-did-mount
  src/status_im/notifications_center/core.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/notifications_center/views.cljs
Labels: Tested - OK

#12019 [#12014] Skip 'Accept and join' view when navigating back from public…
  src/status_im/acquisition/chat.cljs
  src/status_im/ui/screens/chat/toolbar_content.cljs
  src/status_im/ui/screens/referrals/public_chat.cljs
Labels: 1.13, request-manual-qa

#12021 [#12011] Invisible messages in public and group chats if they were re…
  src/status_im/chat/models.cljs
Labels: 1.13, request-manual-qa

#12001 Status-go refactoring
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12039 e2e fix PNs
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/base_view.py
Labels: tests

#12037 [#12033] Can't open Status tab after upgrade from 1.12 to 1.13 if the…
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
Labels: 1.13, Tested - OK

#12032 [wallet] Store pending transactions
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/utils/money.cljs
  src/status_im/wallet/core.cljs
  status-go-version.json
Labels: Tested - OK

#12044 Include a 'My Profile' button in the Start New Chat dialogue
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#12015 ci: nicer artifact filenames for release builds
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
Labels: jenkins, release

#12057 Tests activity center for trusted contacts
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/views/profile_view.py
Labels: tests
