Repository status-im/status-mobile, pull requests merged in 2021-09, with the labels that each got.

#12522 add bump version to release doc
  .github/ISSUE_TEMPLATE/release-issue.md
Labels: docs

#12495 [#12332] Shown PNs on message with mention in community chats (iOS)
  status-go-version.json
Labels: Tested - OK

#12516 request permissions before saving images
  ios/StatusIm/Info.plist
  ios/StatusImPR/Info.plist
  src/status_im/chat/models/images.cljs
Labels: Tested - OK, request-manual-qa

#12484 e2e: delete messages
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/chat_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#12537 [#12476] Re-enable amount/fee validation on tx signing
  src/status_im/subs.cljs
  src/status_im/ui/screens/signing/sheets.cljs
Labels: Tested - OK

#12497 Fix browser history sorting
  src/status_im/subs.cljs
Labels: bug, Tested - OK, request-manual-qa

#12510 Fix unread indicator in activity center when delete message
  src/status_im/chat/models/message.cljs
Labels: bug, Tested - OK, request-manual-qa, Activity center

#12544 Small UI Design Improvements
  src/status_im/navigation/core.cljs
  src/status_im/ui/components/connectivity/view.cljs
  src/status_im/ui/screens/mobile_network_settings/sheets.cljs
Labels: Tested - OK, request-manual-qa

#12536 Fix show/hide password on Android
  src/quo/components/text_input.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
  src/status_im/ui/screens/onboarding/phrase/view.cljs
  src/status_im/ui/screens/profile/seed/views.cljs
  src/status_im/ui/screens/wallet/add_new/views.cljs
Labels: Tested - OK, request-manual-qa

#12529 [#12526] Connecting autofarm.network dapps with status wallet freezes…
  resources/js/provider.js
Labels: Tested - OK, request-manual-qa

#12552 Tx fee e2e
  test/appium/support/api/network_api.py
  test/appium/support/api/web3_api.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/transactions/test_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/atomic/zzz_multiple_drivers_tests/test_multiple_driver_tests.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#12570 fdroid: fix adding GOOGLE_FREE=1 with missing newline
  .env.release
  Makefile
Labels: release

#12542 target Android 30, support scoped storage
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/pkgs/aapt2/default.nix
  nix/pkgs/android-sdk/compose.nix
  nix/pkgs/go-maven-resolver/default.nix
  package.json
  src/status_im/chat/models/images.cljs
  src/status_im/ui/components/permissions.cljs
  src/status_im/ui/screens/status/new/views.cljs
  src/status_im/utils/logging/core.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#12579 opening group chat clears related activity center entries
  src/status_im/group_chats/core.cljs
  src/status_im/utils/universal_links/core.cljs
Labels: Tested - OK, request-manual-qa

#12561 [Fixes: #12486] Fix delete of messages
  .env.release
  status-go-version.json
Labels: Tested - OK

#12577 e2e: some fixes and start collectibles e2e
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#12591 Tests: ens on ropsten
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/atomic/transactions/test_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/atomic/zzz_multiple_drivers_tests/test_multiple_driver_tests.py
  test/appium/tests/users.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/mentioned.png
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#12584 Add option to Mark all read a community
  src/status_im/chat/models/loading.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/communities/views.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12602 e2e: handling updated get_milestone response
  test/appium/support/testrail_report.py
Labels: tests

#12604 Update testrailreport and threads
  test/appium/support/testrail_report.py
  test/appium/tests/__init__.py
Labels: tests

#12554 chats list performance
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models_test.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/chats_test.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/db.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/login/data_test.cljs
  src/status_im/navigation/roots.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/invite/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/home/styles.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/notifications_center/views.cljs
  src/status_im/ui/screens/notifications_center/views/notification.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#12610 drop scripts/generate-pull-request-report.sh
  scripts/generate-pull-request-report.sh
Labels: security

#12528 Add ability to Share image from Status
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  package.json
  resources/images/icons/share_default@2x.png
  resources/images/icons/share_default@3x.png
  src/status_im/ui/screens/chat/image/preview/views.cljs
  src/status_im/utils/fs.cljs
  src/status_im/utils/share.cljs
  yarn.lock
Labels: Tested - OK, feature, request-manual-qa

#12541 [#12517] Ensure that all necessary contact fields are synced
  src/status_im/contact/block.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  status-go-version.json
Labels: Tested - OK

#12645 Contacts syncing
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/atomic/zzz_multiple_drivers_tests/test_multiple_driver_tests.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
Labels: tests

#12647 [#12585] Clear modal's dissmissing state after reopening app with ena…
  src/status_im/navigation/core.cljs
Labels: Tested - OK, request-manual-qa

#12581 [#12563] Allow retrieving of profile updates after removing contact
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12644 [#12568] Fetch history on receiving pubchat installation
  status-go-version.json
Labels: Tested - OK

#12648 [#12642] Can't send funds to multisig - Out of gas
  src/status_im/ethereum/core.cljs
  src/status_im/signing/gas.cljs
  src/status_im/wallet/choose_recipient/core.cljs
Labels: Tested - OK, request-manual-qa

#12376 Use go-waku's connection status updates
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/node/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/wakuv2_settings/edit_node/styles.cljs
  src/status_im/ui/screens/wakuv2_settings/edit_node/views.cljs
  src/status_im/ui/screens/wakuv2_settings/styles.cljs
  src/status_im/ui/screens/wakuv2_settings/views.cljs
  src/status_im/waku/core.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#12665 e2e: fixes
  test/appium/pytest.ini
  test/appium/tests/atomic/chats/test_communities.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/home_view.py
Labels: tests

#11768 Private Profile Photos
  src/status_im/constants.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/appearance/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/utils/config.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa
