Repository status-im/status-mobile, pull requests merged in 2021-11, with the labels that each got.

#12698 [#12531 pairing] Sync read messages
  src/status_im/transport/message/core.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12758 Community categories reorder and persist open/close state
  src/status_im/communities/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/components/accordion.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/communities/reorder_categories.cljs
  src/status_im/ui/screens/communities/select_category.cljs
  src/status_im/ui/screens/communities/styles.cljs
  src/status_im/ui/screens/communities/views.cljs
  src/status_im/ui/screens/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#12796 nix: avoid nesting of Nix shells, show errors
  Makefile
  nix/DETAILS.md
  nix/README.md
  nix/scripts/shell.sh
Labels: nix

#12803 fix activity center community invite preview
  src/status_im/ui/screens/notifications_center/views/notification.cljs
Labels: Tested - OK, request-manual-qa

#12804 fix community category reset on edit channel
  src/status_im/communities/core.cljs
  src/status_im/ui/screens/communities/channel_details.cljs
Labels: Tested - OK, request-manual-qa

#12795 e2e testrail + new checks
  test/appium/support/base_test_report.py
  test/appium/support/test_data.py
  test/appium/support/testrail_report.py
  test/appium/tests/__init__.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/base_test_case.py
  test/appium/views/base_view.py
  test/appium/views/elements_templates/group_logo.png
  test/appium/views/elements_templates/logo_chats_view.png
  test/appium/views/elements_templates/logo_new.png
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#12784 Update zh_TW.json
  translations/zh_TW.json
Labels: translations, request-manual-qa, external

#12736 [#11889] Allow sending messages offline (1-1 chats and private groups)
  src/status_im/subs.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12773 Bug reporting and logs sharing improvements
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/subs.cljs
  src/status_im/ui/screens/bug_report.cljs
  src/status_im/ui/screens/help_center/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/utils/error_handler.cljs
  src/status_im/utils/logging/core.cljs
  src/status_im/utils/utils.cljs
  translations/ar.json
  translations/bn.json
  translations/de.json
  translations/el.json
  translations/en.json
  translations/es.json
  translations/es_419.json
  translations/es_AR.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/ms.json
  translations/nl.json
  translations/pl.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tl.json
  translations/tr.json
  translations/vi.json
  translations/zh.json
  translations/zh_Hans_CN.json
  translations/zh_TW.json
  translations/zh_hans.json
Labels: Tested - OK

#12755 🖋 SVG support for NFTs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
Labels: Tested - OK, request-manual-qa

#12809 [#12760] Add Binance Smart chain as main network
  resources/images/tokens/bsc/0-native.png
  src/status_im/ethereum/core.cljs
  src/status_im/ethereum/macros.clj
  src/status_im/ethereum/tokens.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK, request-manual-qa

#12745 Backup of contacts through waku
  src/status_im/acquisition/chat.cljs
  src/status_im/add_new/core.cljs
  src/status_im/backup/core.cljs
  src/status_im/chat/models.cljs
  src/status_im/contact/block.cljs
  src/status_im/contact/chat.cljs
  src/status_im/contact/core.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/data_store/contacts_test.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/backup_settings/view.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/sync_settings/views.cljs
  src/status_im/utils/datetime.cljs
  src/status_im/utils/universal_links/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#12811 use a default pairing password Keycard
  package.json
  src/status_im/keycard/common.cljs
  src/status_im/keycard/onboarding.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#12756 e2e: waku align
  test/appium/views/home_view.py
Labels: tests

#12815 Remove chat from activity center after opening from public chat
  src/status_im/contact/chat.cljs
Labels: Tested - OK, request-manual-qa

#12826 Handle Keycard timeout on iOS 15
  ios/Podfile.lock
  package.json
  src/status_im/keycard/core.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#12823 New e2e
  test/appium/support/base_test_report.py
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_communities.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/atomic/transactions/test_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/atomic/zzz_multiple_drivers_tests/test_multiple_driver_tests.py
  test/appium/tests/base_test_case.py
  test/appium/tests/marks.py
  test/appium/tests/test_api.py
  test/appium/tests/test_performance.py
  test/appium/tests/users.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/dapps_view.py
  test/appium/views/home_view.py
  test/appium/views/keycard_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/transactions_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/base_web_view.py
  test/appium/views/web_views/status_test_dapp.py
Labels: tests

#12814 Allow user to be reinvited to the same group after leaving
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12833 e2e: catch keyerror in testrail results
  test/appium/requirements.txt
  test/appium/support/testrail_report.py
Labels: tests

#12824 Handle confirmations from mailservers
  status-go-version.json
Labels: Tested - OK

#12831 [#12827] Can't send transaction with custom nonce as it is overlapped…
  src/quo/components/bottom_sheet/view.cljs
  src/status_im/signing/core.cljs
  src/status_im/ui/screens/signing/sheets.cljs
Labels: Tested - OK, request-manual-qa

#12835 Decline pending group invitations from user, when user is banned
  src/status_im/chat/models.cljs
  src/status_im/communities/core.cljs
  src/status_im/notifications/core.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12845 [#12819] Fix network fee calculation on xDai chain
  src/status_im/signing/gas.cljs
Labels: Tested - OK, request-manual-qa

#12836 e2e: highligted chats
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_communities.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_element.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/highligted_preview.png
  test/appium/views/elements_templates/highligted_preview_group.png
  test/appium/views/elements_templates/sauce_logo_profile_2.png
  test/appium/views/elements_templates/url1.png
  test/appium/views/elements_templates/url2.png
  test/appium/views/elements_templates/url3.png
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#12843 [#12818] Support tx history (in a way) when on BSC chains
  src/status_im/ethereum/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/tokens.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/subs.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/utils/config.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/transactions_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12856 [#12848] Add an option to submit error report to GH
  src/status_im/ui/screens/bug_report.cljs
  src/status_im/utils/logging/core.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa
