Repository status-im/status-mobile, pull requests merged in 2021-07, with the labels that each got.

#12227 Add mention notifications to activity center & empty state
  resources/images/icons/chevron_down@2x.png
  resources/images/icons/chevron_down@3x.png
  resources/images/icons/tiny_community@2x.png
  resources/images/icons/tiny_community@3x.png
  src/status_im/constants.cljs
  src/status_im/data_store/activities.cljs
  src/status_im/notifications_center/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/notifications_center/styles.cljs
  src/status_im/ui/screens/notifications_center/views.cljs
  src/status_im/ui/screens/notifications_center/views/notification.cljs
  translations/en.json
Labels: Activity center, Tested - OK, request-manual-qa

#11952 Pinned messages in chats
  resources/images/icons/pin@2x.png
  resources/images/icons/pin@3x.png
  src/status_im/chat/models.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/pin_message.cljs
  src/status_im/constants.cljs
  src/status_im/contact/chat.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/pin_messages.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/subs.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/components/colors.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/pinned_message.cljs
  src/status_im/ui/screens/chat/pinned_messages.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#12269 Update tests to check ToS link
  src/status_im/ui/screens/onboarding/intro/views.cljs
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/views/base_element.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#12275 [#12260] Keycard UI issues after RNN
  src/status_im/keycard/change_pin.cljs
  src/status_im/keycard/common.cljs
  src/status_im/keycard/login.cljs
  src/status_im/keycard/recovery.cljs
  src/status_im/navigation.cljs
  src/status_im/navigation/core.cljs
  src/status_im/ui/screens/keycard/pairing/views.cljs
  src/status_im/ui/screens/keycard/pin/views.cljs
  src/status_im/ui/screens/keycard/settings/views.cljs
  src/status_im/ui/screens/screens.cljs
Labels: Tested - OK, request-manual-qa

#12197 Wakuv2
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  resources/config/fleets.json
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/node/core.cljs
  src/status_im/subs.cljs
  src/status_im/waku/core.cljs
Labels: Tested - OK, request-manual-qa

#12278 Update translations for v1.15
  translations/ar.json
  translations/bn.json
  translations/de.json
  translations/el.json
  translations/es.json
  translations/es_419.json
  translations/es_AR.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/ms.json
  translations/nl.json
  translations/pl.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/vi.json
  translations/zh.json
  translations/zh_TW.json
Labels: 1.15, request-manual-qa, translations

#12280 Edit message in chat test
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
Labels: tests

#12245 ✅ 🗝️ Enable password reset UI
  .env
  .env.e2e
  .env.jenkins
  .env.release
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  src/status_im/multiaccounts/reset_password/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/onboarding/intro/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/status_im/ui/screens/reset_password/views.cljs
  src/status_im/utils/config.cljs
  translations/en.json
Labels: Tested - OK

#12272 properly sync command messages
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12295 [#12294] "Unknown" if tap "Pinned messages" on user profile from publ…
  src/status_im/chat/models.cljs
  src/status_im/ui/screens/chat/pinned_messages.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
Labels: 1.15, Tested - OK

#12300 copy full address when signing tx
  src/status_im/ui/screens/signing/views.cljs
Labels: 1.15, Tested - OK

#12298 [#12297] Fix error for replies activity center while not implemented in status-react
  src/status_im/subs.cljs
Labels: 1.15, Activity center, Tested - OK, bug

#12303 e2e: fix 13/07
  test/appium/tests/atomic/chats/test_communities.py
  test/appium/tests/atomic/chats/test_group_chat.py
  test/appium/views/home_view.py
  test/appium/views/wallet_view.py
Labels: tests

#12307 e2e: delete low category
  test/appium/support/testrail_report.py
Labels: tests

#12314 e2e: reset password+fix
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_communities.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
Labels: tests

#12316 e2e: kk settings
  src/status_im/ui/screens/keycard/pin/views.cljs
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/views/keycard_view.py
  test/appium/views/profile_view.py
  translations/en.json
Labels: tests

#12284 Pin message in chat
  src/status_im/ui/screens/profile/contact/views.cljs
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#12306 allow migration to Keycard keeping the db
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/keycard/recovery.cljs
  src/status_im/multiaccounts/key_storage/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im/ui/screens/bottom_sheets/views.cljs
  src/status_im/ui/screens/multiaccounts/key_storage/styles.cljs
  src/status_im/ui/screens/multiaccounts/key_storage/views.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#12325 e2e: frozen kk 1 part
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/views/keycard_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#12322 fix notification screen displayed twice
  src/status_im/keycard/recovery.cljs
  src/status_im/multiaccounts/key_storage/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/multiaccounts/key_storage/views.cljs
Labels: Tested - OK, request-manual-qa

#12264 Add category to communities
  resources/images/icons/channel_category@2x.png
  resources/images/icons/channel_category@3x.png
  resources/images/icons/delete_circle@2x.png
  resources/images/icons/delete_circle@3x.png
  src/status_im/communities/core.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/subs.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/components/accordion.cljs
  src/status_im/ui/components/icons/icons.cljs
  src/status_im/ui/screens/communities/channel_details.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/communities/create.cljs
  src/status_im/ui/screens/communities/create_category.cljs
  src/status_im/ui/screens/communities/create_channel.cljs
  src/status_im/ui/screens/communities/select_category.cljs
  src/status_im/ui/screens/communities/styles.cljs
  src/status_im/ui/screens/screens.cljs
  translations/en.json
Labels: Tested - OK

#12327 Fix factory reset and unblock PIN in simulated keycard
  src/status_im/keycard/simulated_keycard.cljs
Labels: Tested - OK, request-manual-qa

#12335 PN and reactions for messages
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/status/views.cljs
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/views/chat_view.py
Labels: tests

#12348 [ #12338] "Reset with mnemonic" and "Access exisiting keys" are overl…
  src/status_im/ui/screens/keycard/views.cljs
Labels: Tested - OK, request-manual-qa

#12341 [#12310] "Unknown" screen if press a tag in timeline of another user …
  src/status_im/chat/models.cljs
Labels: Tested - OK, request-manual-qa

#12343 [#12317] Gaps on 'recipient' screen in Wallet, 'add and edit favourit…
  src/status_im/ui/screens/browser/bookmarks/views.cljs
  src/status_im/ui/screens/browser/options/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/wallet/recipient/views.cljs
Labels: Tested - OK

#12339 e2e: frozen kk + migration + blocked kk flows
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#12266 📝 Show replies in activity center
  resources/images/icons/tiny_reply@2x.png
  resources/images/icons/tiny_reply@3x.png
  src/status_im/constants.cljs
  src/status_im/data_store/activities.cljs
  src/status_im/notifications_center/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/notifications_center/styles.cljs
  src/status_im/ui/screens/notifications_center/views/notification.cljs
Labels: Activity center, Tested - OK, request-manual-qa

#12349 [#12321] No redirect from "Confirm the passcode" screen while resetti…
  src/status_im/keycard/backup_key.cljs
  src/status_im/keycard/login.cljs
Labels: Tested - OK, request-manual-qa

#12345 [#12329] No redirect to 1-1 chat when starting chat via "Chat" button…
  src/status_im/navigation.cljs
Labels: Tested - OK

#12342 [#12318] Bottom sheet doesn't close when opening gallery and camera t…
  src/status_im/ui/screens/profile/user/edit_picture.cljs
Labels: Tested - OK

#12346 [#12319] User's statuses are not displayed in Profile if it is opened…
  src/status_im/qr_scanner/core.cljs
Labels: Tested - OK

#12347 don't move accepted invitations to activity center
  status-go-version.json
  test/appium/tests/atomic/zzz_multiple_drivers_tests/test_multiple_driver_tests.py
Labels: Tested - OK, request-manual-qa

#12391 e2e: remaining fixes
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/profile_view.py
Labels: tests

#12383 reset text input after editing message
  src/status_im/chat/models/input.cljs
Labels: Tested - OK, request-manual-qa

#12392 Add pinned messages option in community channel info
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/communities/channel_details.cljs
Labels: Tested - OK, bug, request-manual-qa
