Repository status-im/status-mobile, pull requests merged in 2021-08, with the labels that each got.

#12395 trigger migration to Keycard from logged in state
  src/status_im/init/core.cljs
  src/status_im/multiaccounts/key_storage/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/privacy_and_security_settings/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#12403 Add quick way to permanently hide android background service notification
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/ForegroundService.java
  modules/react-native-status/android/src/main/res/values/strings.xml
Labels: Tested - OK, community

#12384 Remove clear history from non-public chats
  src/status_im/group_chats/core.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  test/appium/tests/atomic/chats/test_chats_management.py
  translations/en.json
Labels: Tested - OK

#12380 Fix for group chat invites icon in activity center
  src/status_im/ui/screens/notifications_center/views/notification.cljs
Labels: Activity center, Tested - OK, bug

#12401 e2e: fix for offline fetching balance e2e + new e2e
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
Labels: tests

#12399 Fix error when opening 1-1 chat in activity center for blocked user
  src/status_im/subs.cljs
Labels: Activity center, Tested - OK, bug

#12409 update react-native-webview for better SSL handling
  package.json
  src/status_im/ui/screens/browser/views.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#12417 tolerate chainID either as integer or string in JSON
  status-go-version.json
Labels: Tested - OK

#12420 emit url event when recreating Activity with link
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  src/status_im/events.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/utils/universal_links/core_test.cljs
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: Tested - OK, request-manual-qa

#12424 don't carry card status on logout
  src/status_im/init/core.cljs
Labels: request-manual-qa

#12248 Communities Sync
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12411 Fix pinned edited messages not updating in communities
  src/status_im/ui/screens/chat/sheets.cljs
Labels: bug, Tested - OK, communities

#12431 [#12418] Error when declining membership request
  src/status_im/transport/message/core.cljs
Labels: request-manual-qa

#12456 [#12451] Fix copy icon in message actions
  src/status_im/ui/screens/status/views.cljs
Labels: Tested - OK

#12445 [#12443] long press is long and it makes the message disappear entirely
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/reactions.cljs
  src/status_im/ui/screens/chat/message/styles.cljs
Labels: Tested - OK, request-manual-qa

#12455 always start PIN/PUK/Pairing change with PIN prompt
  src/status_im/keycard/change_pin.cljs
  src/status_im/keycard/delete_key.cljs
  src/status_im/keycard/unpair.cljs
  src/status_im/ui/screens/keycard/pin/views.cljs
Labels: Tested - OK, request-manual-qa

#12402 Sort pinned messages by time of pinning
  src/status_im/subs.cljs
  src/status_im/ui/screens/chat/message/pinned_message.cljs
  src/status_im/ui/screens/chat/pinned_messages.cljs
Labels: bug, Tested - OK, request-manual-qa

#12463 e2e: hide/delete
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
  test/appium/tests/atomic/chats/test_chats_management.py
  test/appium/tests/atomic/chats/test_commands.py
  test/appium/tests/atomic/chats/test_keycard_commands.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_dapps.py
  test/appium/tests/atomic/test_upgrade.py
  test/appium/tests/atomic/transactions/test_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/wallet_view.py
Labels: tests

#12457 Fix last message deletion
  src/status_im/chat/models/input.cljs
  status-go-version.json
Labels: Tested - OK

#12447 preload chats
  src/status_im/chat/models/loading.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/home/views.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12465 [#12450] Hide deleted message from PNs (Android)
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
Labels: Tested - OK

#12466 [#12460] Allow assets name collision
  src/status_im/wallet/custom_tokens/core.cljs
Labels: Tested - OK

#12470 [#12467] Remove default action icon in message actions list
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/reactions_picker.cljs
Labels: Tested - OK

#12471 [#12446] Screens with overlapping long usernames
  src/quo/components/list/item.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im/ui/screens/communities/requests_to_join.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
Labels: Tested - OK, request-manual-qa

#12458 Hide deleted messages in activity center
  src/status_im/chat/models/message.cljs
  src/status_im/subs.cljs
  status-go-version.json
Labels: bug, Tested - OK, request-manual-qa, Activity center

#12478 e2e: small nightly fix
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/tests/atomic/transactions/test_wallet.py
Labels: tests

#12473 handle multiple calls to frozen-keycard-popup
  src/status_im/keycard/common.cljs
Labels: Tested - OK, request-manual-qa

#12488 Update translations
  translations/ar.json
  translations/bn.json
  translations/de.json
  translations/el.json
  translations/es.json
  translations/es_419.json
  translations/es_AR.json
  translations/fil.json
  translations/fr.json
  translations/id.json
  translations/it.json
  translations/ja.json
  translations/ko.json
  translations/ms.json
  translations/nl.json
  translations/pl.json
  translations/pt.json
  translations/pt_BR.json
  translations/ru.json
  translations/tr.json
  translations/vi.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations, 1.16

#12464 clear notifications on message read
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotification.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/events.cljs
  src/status_im/notifications/android.cljs
  src/status_im/notifications/core.cljs
Labels: Tested - OK, request-manual-qa

#12491 🙈 Hide delete message button behind a feature flag
  .env.release
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK

#12439 Check notifications in AC for mentions in community and group
  test/appium/tests/atomic/chats/test_communities.py
  test/appium/tests/atomic/dapps_and_browsing/test_browsing.py
  test/appium/views/home_view.py
Labels: tests

#12479 [#11849] Move pull to refresh to the account overview screen
  src/quo/components/animated_header.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
Labels: Tested - OK, request-manual-qa

#12492 fix handling of retry counter on iOS and e2e
  src/status_im/keycard/change_pin.cljs
  src/status_im/keycard/common.cljs
  src/status_im/keycard/core.cljs
  src/status_im/keycard/export_key.cljs
  src/status_im/keycard/sign.cljs
  src/status_im/keycard/simulated_keycard.cljs
  src/status_im/keycard/unpair.cljs
Labels: Tested - OK, request-manual-qa

#12521 [#12519] Add $RARE token to our default list
  resources/images/tokens/mainnet/RARE.png
  src/status_im/ethereum/tokens.cljs
Labels: Tested - OK, request-manual-qa

#12506 [#12494] Update unviewed messages counter on message deletion
  src/status_im/chat/models.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#12505 don't show notifications from self
  src/status_im/notifications/local.cljs
Labels: Tested - OK, request-manual-qa
