Repository status-im/status-mobile, pull requests merged in 2022-08, with the labels that each got.

#13717 Switcher blurred background view
  ios/Podfile.lock
  src/quo2/foundations/colors.cljs
  src/quo2/screens/main.cljs
  src/status_im/navigation2/core.cljs
  src/status_im/navigation2/roots.cljs
  src/status_im/switcher/constants.cljs
  src/status_im/switcher/styles.cljs
  src/status_im/switcher/switcher.cljs
  src/status_im/ui/screens/home/views.cljs
Labels: new-design [quo2]

#13714 feat: lottie splash screen
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/raw/launching_animation.json
  doc/DEPENDENCIES.md
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  yarn.lock
Labels: Tested - OK, request-manual-qa, external

#13751 e2e: removed messages under today check in 5315
  test/appium/tests/critical/chats/test_1_1_public_chats.py
Labels: tests

#13602 Move automatic status updates timeout to status-go
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/profile/visibility_status/utils.cljs
  src/status_im/visibility_status_updates/core.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#13742 [#13647] Update all settings on pairing with a new wallet account
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#13733 fix: set max option not work when send from qrcode
  src/status_im/wallet/choose_recipient/core.cljs
Labels: Tested - OK, request-manual-qa, external

#13754 feat: add repl support for cljs test
  shadow-cljs.edn
  src/status_im/integration_test.cljs
  src/status_im/test_runner.cljs
Labels: external

#13747 [#13690] Fix visibility status color
  src/status_im/db.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/communities/members.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui/screens/profile/visibility_status/styles.cljs
  src/status_im/ui/screens/profile/visibility_status/utils.cljs
  src/status_im/ui/screens/profile/visibility_status/views.cljs
Labels: Tested - OK, request-manual-qa, external

#13759 fix error when switching dark/light mode while splash screen is shown
  src/status_im/events.cljs
Labels: Tested - OK, request-manual-qa

#13760 fix visibility dropdown alignment in new ui
  src/status_im/subs.cljs
  src/status_im/switcher/constants.cljs
  src/status_im/ui/screens/profile/visibility_status/views.cljs
Labels: Tested - OK, request-manual-qa

#13761 nix: pass OPENSEA_API_KEY via saveAccountAndLogin
  nix/mobile/android/default.nix
  nix/mobile/android/release.nix
  nix/mobile/ios/status-go-shell.nix
  nix/status-go/mobile/build.nix
  shadow-cljs.edn
  src/status_im/keycard/simulated_keycard.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/node/core.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK, clojure, request-manual-qa, nix

#13765 [#13766] custom networkid fix
  src/status_im/multiaccounts/login/core.cljs
Labels: Tested - OK, request-manual-qa

#13772 fix: quo haptic impact light key
  src/quo/haptic.cljs
Labels: external

#13774 fix send button remains active in chats after sending reply containing a mention
  src/status_im/ui/screens/chat/components/input.cljs
Labels: Tested - OK, request-manual-qa

#13782 Remove contact request notification from activity center when request is canceled
  src/status_im/constants.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/notifications_center/views/notification.cljs
Labels: Tested - OK

#13737 Editing message UI redesign
  resources/images/icons/edit_connector@2x.png
  resources/images/icons/edit_connector@3x.png
  src/status_im/ui/screens/chat/components/edit.cljs
  src/status_im/ui/screens/chat/views.cljs
Labels: Tested - OK, request-manual-qa, new-design [quo2]

#13798 [#13791] Extend integration tests to create a new wallet account
  src/status_im/integration_test.cljs
  src/status_im/utils/test.cljs
Labels: tests

#13799 Add session management for wallet connect
  resources/images/icons/manage_connections@2x.png
  resources/images/icons/manage_connections@3x.png
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/wallet/accounts/sheets.cljs
  src/status_im/ui/screens/wallet/manage_connections/styles.cljs
  src/status_im/ui/screens/wallet/manage_connections/views.cljs
  src/status_im/ui/screens/wallet_connect/session_proposal/views.cljs
  src/status_im/utils/utils.cljs
  src/status_im/utils/wallet_connect_legacy.cljs
  src/status_im/wallet_connect/core.cljs
  src/status_im/wallet_connect_legacy/core.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK

#13764 refactor copyable-text component to accept background-color property
  src/status_im/ui/components/copyable_text.cljs
Labels: Tested - OK, request-manual-qa

#13767 feat: add token overview component (status-im#13555)
  resources/images/icons/price_decrease12@2x.png
  resources/images/icons/price_decrease12@3x.png
  resources/images/icons/price_increase12@2x.png
  resources/images/icons/price_increase12@3x.png
  src/quo2/components/token_overview.cljs
  src/quo2/screens/main.cljs
  src/quo2/screens/token_overview.cljs
  translations/en.json
Labels: new-design [quo2]

#13846 upgrade async storage version
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  package.json
  src/mocks/js_dependencies.cljs
  src/status_im/async_storage/core.cljs
  src/status_im/keycard/fx.cljs
  src/status_im/utils/wallet_connect.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#13776 [#13672] Sync contact request decision
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#13827 Issue-13813: Use new endpoints for browser
  src/status_im/browser/core.cljs
  src/status_im/multiaccounts/login/core.cljs
Labels: Tested - OK, request-manual-qa

#13841 [#13835] Fix Generate keys button
  src/status_im/keycard/recovery.cljs
Labels: Tested - OK, request-manual-qa

#13851 e2e: get back to home view
  test/appium/tests/critical/wallet_and_tx/test_wallet.py
  test/appium/tests/medium/test_single_device.py
  test/appium/views/base_view.py
Labels: tests

#13644 feat: add token tag component (#13599)
  resources/images/icons/purchasable12@2x.png
  resources/images/icons/purchasable12@3x.png
  resources/images/icons/required_checkmark12@2x.png
  resources/images/icons/required_checkmark12@3x.png
  src/quo2/components/tag.cljs
  src/quo2/components/token_tag.cljs
  src/quo2/screens/main.cljs
  src/quo2/screens/token_tag.cljs
Labels: new-design [quo2]

#13862 ci: extrac Lint and Tests to separate job
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
Labels: tests

#13850 ci: use different IPFS gateway for release builds
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/tests/Jenkinsfile.e2e-prs
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  nix/config.nix
  nix/status-go/default.nix
  status-go-version.json
Labels: Tested - OK, status-go, request-manual-qa

#13863 drop unused coveralls configuration and CI steps
  Makefile
  package.json
  scripts/run-coverage.sh
  yarn.lock
Labels: android, tests

#13692 [13565] icon-avatar component
  src/quo2/components/avatar/avatar_themes.cljs
  src/quo2/components/icon_avatar.cljs
  src/quo2/foundations/colors.cljs
  src/quo2/screens/icon_avatar.cljs
  src/quo2/screens/main.cljs
Labels: new-design [quo2]

#13681 [13562] Wallet user avatar component
  src/quo2/components/wallet_user_avatar.cljs
  src/quo2/foundations/colors.cljs
  src/quo2/screens/main.cljs
  src/quo2/screens/wallet_user_avatar.cljs
Labels: new-design [quo2]

#13729 Update translation for 1.20
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/es-419/short_description.txt
  fastlane/metadata/android/es-419/title.txt
  fastlane/metadata/android/es-AR/short_description.txt
  fastlane/metadata/android/es-AR/title.txt
  fastlane/metadata/android/es-ES/short_description.txt
  fastlane/metadata/android/es-ES/title.txt
  fastlane/metadata/android/fil/title.txt
  fastlane/metadata/android/fr-FR/short_description.txt
  fastlane/metadata/android/fr-FR/title.txt
  fastlane/metadata/android/it-IT/short_description.txt
  fastlane/metadata/android/it-IT/title.txt
  fastlane/metadata/android/pt-BR/title.txt
  fastlane/metadata/android/ru-RU/short_description.txt
  fastlane/metadata/android/tr-TR/title.txt
  fastlane/metadata/android/uk/short_description.txt
  fastlane/metadata/android/uk/title.txt
  translations/hi.json
  translations/ja.json
  translations/ru.json
  translations/zh.json
  translations/zh_TW.json
Labels: translations

#13879 e2e: enable stickers and update release notes
  RELEASES.md
  test/appium/tests/critical/chats/test_1_1_public_chats.py
Labels: tests

#13901 fix old stickers
  src/status_im/chat/models/input.cljs
  src/status_im/multiaccounts/update/core.cljs
Labels: Tested - OK, request-manual-qa

#13898 fix no icon for ETH in 1-1 transaction messages
  src/status_im/ethereum/macros.clj
Labels: Tested - OK, request-manual-qa

#13900 [#13889] Ignore group chat color when not specified
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#13896 [13857] Extend integration tests to recover multiaccount from seed ph…
  src/mocks/js_dependencies.cljs
  src/status_im/integration_test.cljs
  src/status_im/utils/test.cljs
Labels: tests
