Repository status-im/status-mobile, pull requests merged in 2022-02, with the labels that each got.

#13029 [#13007] Move ENS logic to status-go
  .carve_ignore
  src/status_im/acquisition/core.cljs
  src/status_im/add_new/core.cljs
  src/status_im/browser/core.cljs
  src/status_im/ens/core.cljs
  src/status_im/ethereum/ens.cljs
  src/status_im/ethereum/ens_test.cljs
  src/status_im/ethereum/json_rpc.cljs
  src/status_im/ethereum/resolver.cljs
  src/status_im/ethereum/stateofus.cljs
  src/status_im/router/core.cljs
  src/status_im/utils/multihash.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/recipient/core.cljs
Labels: Tested - OK, request-manual-qa

#13058 [#12783] Improve order of mailserver requests
  status-go-version.json
Labels: Tested - OK

#13071 e2e: fixed missing geth
  test/appium/tests/base_test_case.py
Labels: tests

#13072 e2e: more groups
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/account_management/test_wallet_management.py
Labels: tests

#13080 fix ens resolve issue while following deep link
  src/status_im/add_new/core.cljs
  src/status_im/chat/models.cljs
  src/status_im/contact/chat.cljs
  src/status_im/contact/db.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/router/core.cljs
  src/status_im/subs.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/utils/universal_links/core.cljs
Labels: Tested - OK, request-manual-qa

#13039 Use HTTPs for image loading with self-signed certs
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/app/src/main/java/im/status/ethereum/StatusOkHttpClientFactory.java
  ios/StatusIm/AppDelegate.m
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  src/status_im/chat/models/images.cljs
  src/status_im/ui/screens/chat/image/preview/views.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/photos.cljs
  src/status_im/ui/screens/status/views.cljs
  status-go-version.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#13092 e2e: fixes ens
  test/appium/requirements.txt
  test/appium/support/api/network_api.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/dapps_and_browsing/test_deep_links.py
  test/appium/tests/atomic/transactions/test_wallet.py
  test/appium/tests/atomic/zzz_multiple_drivers_tests/test_multiple_driver_tests.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
Labels: tests

#13028 Implementation of remote android notifications
  Makefile
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-mdpi/ic_stat_status_notification.png
  android/app/src/main/res/drawable-mdpi/notification_icon.png
  android/app/src/main/res/drawable-xhdpi/ic_stat_status_notification.png
  android/app/src/main/res/drawable-xhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxhdpi/ic_stat_status_notification.png
  android/app/src/main/res/drawable-xxhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxxhdpi/ic_stat_status_notification.png
  android/app/src/main/res/drawable-xxxhdpi/notification_icon.png
  android/app/src/main/res/values/colors.xml
  android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotification.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  scripts/google-free.sh
  scripts/release-android.sh
  shadow-cljs.edn
  src/mocks/js_dependencies.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/notifications/android.cljs
  src/status_im/notifications/android_remote.cljc
  src/status_im/notifications/core.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/notifications_settings/views.cljs
  src/status_im/ui/screens/onboarding/notifications/views.cljs
  status-go-version.json
  translations/en.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#13100 e2e: fix accesibility for 13028
  test/appium/views/profile_view.py
Labels: tests

#13112 e2e: backup of contacts
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/views/profile_view.py
Labels: tests

#13111 WIP: test_gap_in_public_chat
  test/appium/tests/atomic/chats/test_public.py
Labels: tests

#13110 e2e: fix communities
  test/appium/views/home_view.py
Labels: tests

#13125 Tests/kk refactoring
  test/appium/support/testrail_report.py
  test/appium/tests/atomic/account_management/test_create_account.py
  test/appium/tests/atomic/account_management/test_keycard.py
  test/appium/tests/atomic/account_management/test_profile.py
  test/appium/tests/atomic/chats/test_one_to_one.py
  test/appium/tests/atomic/chats/test_public.py
  test/appium/tests/atomic/transactions/test_keycard_dapps_transactions.py
  test/appium/tests/atomic/transactions/test_keycard_wallet.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#13128 [#13104] Fix deadlock on syncing all data
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#13119 stop showing notifications for muted chats
  VERSION
  src/status_im/ui/screens/profile/contact/views.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#13129 add remote notifications preferences
  src/status_im/ui/screens/notifications_settings/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa
