Repository status-im/status-mobile, pull requests merged in 2023-04, with the labels that each got.

#15485 Add accessibility id for community unread indicators
  src/quo2/components/common/unread_grey_dot/view.cljs
  src/quo2/components/community/community_list_view.cljs
  src/quo2/components/list_items/channel.cljs
Labels: Tested - OK, request-manual-qa

#15559 Revert "set signing to auto for debug builds (#15420)"
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: ios, infra

#15542 fix: add min 5 characters validation for display names
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  translations/en.json
Labels: bug, Tested - OK, request-manual-qa

#15562 fix: image desktop
  src/status_im2/contexts/chat/lightbox/zoomable_image/constants.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/contexts/chat/messages/composer/controls/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
Labels: Tested - OK, request-manual-qa

#15576 fix: images 1.22
  src/status_im2/contexts/chat/lightbox/zoomable_image/constants.cljs
  src/status_im2/contexts/chat/messages/composer/controls/view.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
Labels: request-manual-qa

#15585 fix chat layout breaking when combining normal text with code blocks
  src/status_im2/contexts/chat/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa

#15568 [Fix] QR Viewfinder overlap with segmented tabs in Sign in
  src/status_im2/contexts/onboarding/sign_in/view.cljs
Labels: bug, Tested - OK, onboarding, request-manual-qa

#15586 [Fix] Remove AC request to join notification on community request cancellation
  status-go-version.json
Labels: bug, Tested - OK, request-manual-qa, communities

#15574 [Update] Checks for Syncing completed signal
  src/status_im/events.cljs
  src/status_im/keycard/recovery.cljs
  src/status_im/mobile_sync_settings/core.cljs
  src/status_im/multiaccounts/key_storage/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/model.cljs
  src/status_im/multiaccounts/model_test.cljs
  src/status_im/signals/core.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/subs/general.cljs
Labels: Tested - OK, onboarding, request-manual-qa

#15487 [15383] Add the album count attribute to message body
  src/status_im/data_store/messages.cljs
  src/status_im/ui2/screens/chat/components/reply/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15601 nix: bump nixpkgs to include fix for apksigner
  nix/pkgs.nix
Labels: android, devops, nix

#15498 navigate to community home screen
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
Labels: Tested - OK, request-manual-qa

#15554 feat: support ens profile name in lock screen
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/multiaccounts/update/core_test.cljs
  src/status_im/pairing/core.cljs
Labels: Tested - OK, request-manual-qa

#15607 New component - URL Preview
  src/quo2/components/links/url_preview/component_spec.cljs
  src/quo2/components/links/url_preview/style.cljs
  src/quo2/components/links/url_preview/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/links/url_preview.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/test_helpers/component.cljs
Labels: new-design [quo2], url-preview

#15614 Bump go version to work with latest status-go changes
  nix/overlay.nix
  status-go-version.json
Labels: request-manual-qa

#15557 [15504, 15408] Nickname flow
  src/status_im2/common/home/actions/view.cljs
  src/status_im2/contexts/contacts/drawers/nickname_drawer/style.cljs
  src/status_im2/contexts/contacts/drawers/nickname_drawer/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15486 Upgrade `react-native` from 0.63.3 to 0.67.5
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/build.gradle
  android/gradle.properties
  ci/Jenkinsfile.combined
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.m
  ios/StatusIm/main.m
  ios/StatusImTests/StatusImTests.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/nodejs-patched/default.nix
  nix/overlay.nix
  nix/pkgs/aapt2/default.nix
  nix/pkgs/android-sdk/compose.nix
  nix/status-go/mobile/build.nix
  package.json
  resources/images/icons2/12x12/thumb-dark@2x.png
  resources/images/icons2/12x12/thumb-dark@3x.png
  resources/images/icons2/12x12/thumb-light@2x.png
  resources/images/icons2/12x12/thumb-light@3x.png
  src/quo2/components/inputs/input/view.cljs
  src/quo2/components/record_audio/record_audio/view.cljs
  src/status_im2/contexts/chat/messages/composer/controls/style.cljs
  src/status_im2/contexts/chat/messages/link_preview/view.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#15625 e2e: fix xpath for link preview
  test/appium/views/chat_view.py
Labels: tests

#15541 Selector component improvements
  src/quo2/components/list_items/user_list.cljs
  src/quo2/components/selectors/__tests__/selectors_component_spec.cljs
  src/quo2/components/selectors/disclaimer/view.cljs
  src/quo2/components/selectors/selectors.cljs
  src/quo2/components/selectors/selectors/component_spec.cljs
  src/quo2/components/selectors/selectors/style.cljs
  src/quo2/components/selectors/selectors/view.cljs
  src/quo2/components/selectors/styles.cljs
  src/quo2/components/settings/privacy_option.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
  src/status_im2/contexts/quo_preview/selectors/selectors.cljs
Labels: Tested - OK, request-manual-qa, new-design [quo2]

#15633 ios: provide explicit NODE_ARGS in Nix shell
  ios/StatusIm.xcodeproj/project.pbxproj
  nix/mobile/ios/shells/nodejs.nix
Labels: ios, devops

#15620 New component - URL Preview List
  src/quo2/components/links/url_preview_list/component_spec.cljs
  src/quo2/components/links/url_preview_list/style.cljs
  src/quo2/components/links/url_preview_list/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/links/url_preview_list.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/test_helpers/component.cljs
Labels: new-design [quo2], url-preview

#15647 fix jump-to in the community screen is navigating to home screen instead of shell
  src/status_im2/contexts/shell/events.cljs
Labels: Tested - OK, request-manual-qa

#15253 [15128] Introduce muting for a specific duration
  src/quo2/components/list_items/menu_item.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/integration_test.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im2/common/home/actions/view.cljs
  src/status_im2/common/mute_chat_drawer/style.cljs
  src/status_im2/common/mute_chat_drawer/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/group_details/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/subs/shell.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15650 [#15518]Show disclaimer during password creation
  src/status_im2/contexts/onboarding/create_password/view.cljs
Labels: Tested - OK, request-manual-qa, external

#15596 fix status-bar font color
  src/status_im/multiaccounts/login/core.cljs
  src/status_im2/navigation/options.cljs
  src/status_im2/navigation/roots.cljs
Labels: Tested - OK, request-manual-qa

#15667 Fix for "Pending requests" label not being shown in light mode
  src/status_im2/contexts/chat/home/contact_request/view.cljs
Labels: Tested - OK, request-manual-qa

#15670 fix app theme changes with PN enabled and the app closed
  src/status_im2/navigation/core.cljs
Labels: Tested - OK, request-manual-qa

#15666 Use static background screen for onboarding screens with dark overlay
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/common/carousel/animation.cljs
  src/status_im2/contexts/onboarding/common/carousel/style.cljs
  src/status_im2/contexts/onboarding/common/carousel/view.cljs
Labels: Tested - OK, request-manual-qa

#15526 Update contact screen to new design
  src/status_im2/contexts/add_new_contact/style.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#15637 Allow running debug iOS builds on physical device via CLI and Enable Automatic code signing for Debug builds
  Makefile
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: ios, developer-xp

#15640 Fix for multiple header spacings on onboarding screens
  src/status_im2/contexts/onboarding/common/navigation_bar/view.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
  src/status_im2/contexts/onboarding/create_profile/style.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/style.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/view.cljs
  src/status_im2/contexts/onboarding/generating_keys/style.cljs
  src/status_im2/contexts/onboarding/generating_keys/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/style.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/style.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/view.cljs
Labels: Tested - OK, request-manual-qa

#15636 Change view-id as per the selected bottom tab and refactor subscriptions
  src/status_im/search/core.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/shell/animation.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/general.cljs
  src/status_im2/subs/home.cljs
  src/status_im2/subs/search.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#15581 ci: upgrade Xcode from 14.2 to 14.3
  ci/Jenkinsfile.ios
  nix/overlay.nix
Labels: ios, devops, dependencies, infra

#15604 [15569] Select recent tab on messages home when double tapping messages icon
  src/status_im/events.cljs
  src/status_im2/contexts/chat/home/events.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/shell/bottom_tabs.cljs
  src/status_im2/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#15579 fix: remove contact from mutual contact list after contact is blocked
  src/status_im/contact/block.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15699 nix: add ios-deploy package to ios shell
  nix/mobile/ios/default.nix
  nix/mobile/ios/shells/nodejs.nix
  nix/overlay.nix
  nix/shells.nix
Labels: ios, nix, dependencies

#15499 Add accessibility-id for buttons 'Enable Biometrics' page
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
Labels: Tested - OK, request-manual-qa

#15627 Community request to join changes
  src/status_im/communities/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im2/contexts/activity_center/notification/common/view.cljs
  src/status_im2/contexts/activity_center/notification/community_request/view.cljs
  src/status_im2/contexts/activity_center/notification_types.cljs
  src/status_im2/contexts/activity_center/view.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, feature, request-manual-qa, communities

#15223 [#15210] Show user avatar in contact request toast
  src/quo2/components/notifications/toast/view.cljs
  src/status_im2/contexts/activity_center/events.cljs
Labels: Tested - OK, request-manual-qa

#15711 feat: step component
  src/quo2/components/counter/counter.cljs
  src/quo2/components/counter/step/component_spec.cljs
  src/quo2/components/counter/step/style.cljs
  src/quo2/components/counter/step/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/counter/step.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/utils/number_test.cljs
Labels: new-design [quo2]

#15572 [15550] Allow unpinning of deleted-for-me messages
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
Labels: Tested - OK, request-manual-qa

#15712 move image-server out of status-im namespace
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/contact.cljs
  src/status_im2/subs/multiaccount.cljs
  src/utils/image_server.cljs
Labels: Tested - OK, request-manual-qa

#15691 Integrate support for SVG icons and fix clear icon
  src/mocks/js_dependencies.cljs
  src/quo2/components/icon.cljs
  src/quo2/components/icons/icons.clj
  src/quo2/components/icons/icons.cljs
  src/quo2/components/icons/svg.cljs
  src/quo2/components/inputs/search_input/style.cljs
  src/quo2/components/links/url_preview/style.cljs
  src/quo2/components/links/url_preview/view.cljs
  src/react_native/svg.cljs
  src/status_im/ui2/screens/chat/composer/images/style.cljs
  src/status_im/ui2/screens/chat/composer/images/view.cljs
Labels: bug, new-design [quo2]

#15740 ci: fix missing SSH key for fetching ios certs
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: ios, security, infra

#15689 Fix replies & pinned messages
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/pin_messages.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui2/screens/chat/components/reply/view.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/view.cljs
  src/status_im2/contexts/chat/messages/avatar/view.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/content/pin/style.cljs
  src/status_im2/contexts/chat/messages/content/pin/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/pin/events.cljs
  src/status_im2/contexts/chat/messages/pin/events_test.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15723 Fixed styling issues for mention in the chat text
  src/status_im2/contexts/chat/messages/content/text/style.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa, external

#15732 New component: Link Preview
  src/quo2/components/links/link_preview/component_spec.cljs
  src/quo2/components/links/link_preview/style.cljs
  src/quo2/components/links/link_preview/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/links/link_preview.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: new-design [quo2], url-preview

#15738 [#15655] Resolve messages with markdown on Jump To screen
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/shell/cards/view.cljs
  src/status_im2/subs/shell.cljs
  src/status_im2/utils/message_resolver.cljs
  src/status_im2/utils/message_resolver_test.cljs
Labels: Tested - OK, request-manual-qa

#15724 fix device theme change listener in ios
  src/react_native/navigation.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im2/common/theme/core.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#15750 Request to join community screen is not scrollable on Android #15748
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  test/appium/views/base_view.py
Labels: Tested - OK, request-manual-qa

#15744 fix status bar font color
  src/quo2/components/inputs/title_input/style.cljs
  src/status_im2/navigation/options.cljs
Labels: Tested - OK, request-manual-qa

#15749 move status native module
  .carve_ignore
  src/native_module/core.cljs
  src/native_module/core_test.cljs
  src/react_native/core.cljs
  src/status_im/add_new/db.cljs
  src/status_im/browser/core.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/ethereum/core.cljs
  src/status_im/ethereum/eip55.cljs
  src/status_im/ethereum/encode.cljs
  src/status_im/ethereum/ens.cljs
  src/status_im/events.cljs
  src/status_im/keycard/fx.cljs
  src/status_im/keycard/real_keycard.cljs
  src/status_im/keycard/recovery.cljs
  src/status_im/keycard/simulated_keycard.cljs
  src/status_im/multiaccounts/biometric/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/key_storage/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/multiaccounts/reset_password/core.cljs
  src/status_im/network/net_info.cljs
  src/status_im/node/core.cljs
  src/status_im/notifications/local.cljs
  src/status_im/router/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/signing/core_test.cljs
  src/status_im/signing/keycard.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/network_info/views.cljs
  src/status_im/ui/screens/privacy_and_security_settings/events.cljs
  src/status_im/utils/gfycat/core.cljs
  src/status_im/utils/identicon.cljs
  src/status_im/utils/keychain/core.cljs
  src/status_im/utils/logging/core.cljs
  src/status_im/utils/react_native.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im2/common/json_rpc/events.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/resolver/message_resolver.cljs
  src/status_im2/contexts/chat/messages/resolver/message_resolver_test.cljs
  src/status_im2/contexts/onboarding/events.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/contexts/shell/cards/view.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/core.cljs
  src/status_im2/events.cljs
  src/utils/validators.cljs
  src/utils/validators_test.cljs
Labels: tech-debt

#15622 fix Sometimes mentions list does not appear after typing @ in chat input filed
  src/status_im/chat/models/mentions.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui2/screens/chat/composer/input.cljs
  status-go-version.json
Labels: Tested - Issues, blocked, request-manual-qa

#15684 feat: add identifiers screen to onboarding-flow
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/common/carousel/animation.cljs
  src/status_im2/contexts/onboarding/common/carousel/style.cljs
  src/status_im2/contexts/onboarding/common/carousel/view.cljs
  src/status_im2/contexts/onboarding/events.cljs
  src/status_im2/contexts/onboarding/identifiers/style.cljs
  src/status_im2/contexts/onboarding/identifiers/view.cljs
  src/status_im2/navigation/screens.cljs
  test/appium/views/sign_in_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15736 Reimplement composer: add reply
  resources/images/icons2/16x16/connector@2x.png
  resources/images/icons2/16x16/connector@3x.png
  src/status_im/chat/models/input.cljs
  src/status_im2/config.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/actions/view.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/constants.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/effects.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/handlers.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/reply/style.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/reply/view.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/style.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/utils.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/view.cljs
  src/status_im2/contexts/chat/messages/list/new_temp_view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: composer

#15765 remove unused code relate to old text-input component
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/mentions.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/ui/screens/chat/components/accessory.cljs
  src/status_im/ui/screens/chat/components/contact_request.cljs
  src/status_im/ui/screens/chat/components/edit.cljs
  src/status_im/ui/screens/chat/components/hooks.cljs
  src/status_im/ui/screens/chat/components/input.cljs
  src/status_im/ui/screens/chat/components/reply.cljs
  src/status_im/ui/screens/chat/components/style.cljs
  src/status_im2/subs/chat/chats.cljs
Labels: Tested - OK, request-manual-qa

#15774 nix: disable sandboxing for xcodewrapper
  nix/pkgs/xcodeenv/compose-xcodewrapper.nix
Labels: ios, nix

#15766 clean old code, remove public chat, implement drawers for home screens
  src/status_im/add_new/core.cljs
  src/status_im/add_new/db.cljs
  src/status_im/bottom_sheet/sheets.cljs
  src/status_im/chat/models.cljs
  src/status_im/communities/core.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/events.cljs
  src/status_im/http/core.cljs
  src/status_im/integration_test.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/react_native/resources.cljs
  src/status_im/router/core.cljs
  src/status_im/router/core_test.cljs
  src/status_im/ui/screens/add_new/new_chat/views.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui/screens/browser/options/views.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/communities/views.cljs
  src/status_im/ui/screens/help_center/views.cljs
  src/status_im/ui/screens/home/sheet/styles.cljs
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/utils/universal_links/utils.cljs
  src/status_im2/common/home/actions/view.cljs
  src/status_im2/contexts/chat/actions/view.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/chat/sheets/view.cljs
  src/status_im2/contexts/communities/actions/community_options/component_spec.cljs
  src/status_im2/contexts/communities/actions/community_options/view.cljs
  src/status_im2/contexts/communities/actions/community_rules_list/style.cljs
  src/status_im2/contexts/communities/actions/community_rules_list/view.cljs
  src/status_im2/contexts/communities/actions/generic_menu/style.cljs
  src/status_im2/contexts/communities/actions/generic_menu/view.cljs
  src/status_im2/contexts/communities/actions/home_plus/view.cljs
  src/status_im2/contexts/communities/actions/leave/style.cljs
  src/status_im2/contexts/communities/actions/leave/view.cljs
  src/status_im2/contexts/communities/actions/request_to_join/style.cljs
  src/status_im2/contexts/communities/actions/request_to_join/view.cljs
  src/status_im2/contexts/communities/actions/see_rules/view.cljs
  src/status_im2/contexts/communities/actions/view.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/menus/see_rules/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/core_spec.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/shell_test.cljs
Labels: Tested - OK, request-manual-qa

#15704 e2e: cleanup
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/onboarding/test_onboarding_flows.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/critical/wallet_and_tx/test_send_tx_dapp_keycard.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_browser_profile.py
  test/appium/tests/medium/test_chats_m.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
  test/appium/tests/medium/test_pairing_devices_sync_m.py
  test/appium/tests/medium/test_permissions_scan_qr.py
  test/appium/tests/medium/test_profile_m.py
  test/appium/tests/medium/test_single_device.py
  test/appium/tests/upgrade/test_upgrade.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#15773 Improve dissmiss all overlays
  src/react_native/navigation.cljs
  src/status_im2/common/toasts/events.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/events.cljs
Labels: Tested - OK, request-manual-qa
