Repository status-im/status-mobile, pull requests merged in 2023-06, with the labels that each got.

#15677 [15660] Show who sent message reaction
  resources/images/icons2/20x20/add-reaction@2x.png
  resources/images/icons2/20x20/add-reaction@3x.png
  src/quo2/components/reactions/reaction.cljs
  src/quo2/components/tabs/tabs.cljs
  src/status_im/chat/models/reactions.cljs
  src/status_im/profile/core.cljs
  src/status_im2/common/bottom_sheet/styles.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/drawers/style.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#16065 Local Pairing Updates
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signals/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/pairing.cljs
  status-go-version.json
Labels: Tested - OK, pairing, request-manual-qa

#15975 adjust padding for QR Images
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16053 improve photo-selector and adjust according to the latest designs
  src/quo2/components/buttons/button.cljs
  src/quo2/components/dropdowns/dropdown.cljs
  src/react_native/cameraroll.cljs
  src/react_native/core.cljs
  src/react_native/gesture.cljs
  src/status_im/chat/models/images.cljs
  src/status_im/events.cljs
  src/status_im/ui/components/permissions.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im2/contexts/chat/events_test.cljs
  src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs
  src/status_im2/contexts/chat/photo_selector/events.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/contexts/quo_preview/dropdowns/dropdown.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#15946 [#15759] - Onboarding recovery phrase screen
  src/quo2/components/buttons/predictive_keyboard/view.cljs
  src/quo2/components/inputs/recovery_phrase/component_spec.cljs
  src/quo2/components/inputs/recovery_phrase/view.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/style.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/view.cljs
  translations/en.json
Labels: Tested - OK, onboarding, request-manual-qa

#16126 fix #16043
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16103 Disable translations - only use English for the moment until designs are stable and translations are correct
  src/status_im2/setup/i18n_resources.cljs
Labels: Tested - OK, request-manual-qa

#15933 Feature/15776 slideshow styles
  src/quo2/components/drawers/drawer_buttons/style.cljs
  src/quo2/components/drawers/drawer_buttons/view.cljs
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/intro/style.cljs
  src/status_im2/contexts/onboarding/intro/view.cljs
Labels: Tested - OK, request-manual-qa

#16096 Lightbox refactoring
  src/status_im2/contexts/chat/lightbox/utils.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/utils.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/navigation/options.cljs
Labels: refactoring

#16136 [Fix] Open app on push notification tap
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
Labels: android, Tested - OK, push-notifications, request-manual-qa

#16165 e2e: fixes for emoji and xfails added
  test/appium/support/testrail_report.py
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/image_sent_in_community.png
Labels: tests

#16131 [#16094] Messaging - In Chat - Implement Options Menu for 1-1 and com…
  src/status_im2/common/home/actions/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#16040 Support unfurling more websites
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16162 [#16077] Add community illustrations
  resources/images/ui2/no-communities-dark@2x.png
  resources/images/ui2/no-communities-dark@3x.png
  resources/images/ui2/no-communities-light@2x.png
  resources/images/ui2/no-communities-light@3x.png
  resources/images/ui2/no-contacts-dark.png
  resources/images/ui2/no-contacts-dark@2x.png
  resources/images/ui2/no-contacts-dark@3x.png
  resources/images/ui2/no-contacts-light.png
  resources/images/ui2/no-contacts-light@2x.png
  resources/images/ui2/no-contacts-light@3x.png
  resources/images/ui2/no-contacts-to-invite-dark@2x.png
  resources/images/ui2/no-contacts-to-invite-dark@3x.png
  resources/images/ui2/no-contacts-to-invite-light@2x.png
  resources/images/ui2/no-contacts-to-invite-light@3x.png
  resources/images/ui2/no-group-chats-dark@2x.png
  resources/images/ui2/no-group-chats-dark@3x.png
  resources/images/ui2/no-group-chats-light@2x.png
  resources/images/ui2/no-group-chats-light@3x.png
  resources/images/ui2/no-messages-light@2x.png
  resources/images/ui2/no-messages-light@3x.png
  resources/images/ui2/no-notifications-dark@2x.png
  resources/images/ui2/no-notifications-dark@3x.png
  resources/images/ui2/no-notifications-light@2x.png
  resources/images/ui2/no-notifications-light@3x.png
  resources/images/ui2/no-opened-communities-dark@2x.png
  resources/images/ui2/no-opened-communities-dark@3x.png
  resources/images/ui2/no-opened-communities-light@2x.png
  resources/images/ui2/no-opened-communities-light@3x.png
  resources/images/ui2/no-pending-communities-dark@2x.png
  resources/images/ui2/no-pending-communities-dark@3x.png
  resources/images/ui2/no-pending-communities-light@2x.png
  resources/images/ui2/no-pending-communities-light@3x.png
  resources/images/ui2/no-received-requests-dark@2x.png
  resources/images/ui2/no-received-requests-dark@3x.png
  resources/images/ui2/no-received-requests-light@2x.png
  resources/images/ui2/no-received-requests-light@3x.png
  resources/images/ui2/no-sent-requests-dark@2x.png
  resources/images/ui2/no-sent-requests-dark@3x.png
  resources/images/ui2/no-sent-requests-light@2x.png
  resources/images/ui2/no-sent-requests-light@3x.png
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/communities/home/style.cljs
  src/status_im2/contexts/communities/home/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16168 [16166] The reaction are not matched to the designs into the 'who sent' bottom sheet
  src/status_im2/contexts/chat/messages/drawers/style.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
Labels: Tested - OK, request-manual-qa

#16171 [16147] Fix margin left for community icon when long pressing community
  src/quo2/components/community/community_list_view.cljs
Labels: Tested - OK, request-manual-qa

#16192 Fixes for Request to Join Community bottom sheet
  src/quo2/components/selectors/disclaimer/view.cljs
  src/status_im2/common/bottom_sheet/styles.cljs
  src/status_im2/common/bottom_sheet_screen/style.cljs
  src/status_im2/contexts/communities/actions/community_rules_list/style.cljs
  src/status_im2/contexts/communities/actions/community_rules_list/view.cljs
  src/status_im2/contexts/communities/actions/request_to_join/style.cljs
  src/status_im2/contexts/communities/actions/request_to_join/view.cljs
  translations/en.json
Labels: bug

#16000 Design note fixes (#15781)
  src/quo2/components/info/info_message.cljs
  src/quo2/components/inputs/profile_input/style.cljs
  src/quo2/components/inputs/profile_input/view.cljs
  src/quo2/components/inputs/title_input/view.cljs
  src/status_im2/contexts/onboarding/create_profile/style.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16186 Messages read back button
  src/status_im2/contexts/chat/messages/content/legacy_view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/communities/actions/community_options/component_spec.cljs
  src/status_im2/contexts/communities/actions/community_options/view.cljs
Labels: Tested - OK, request-manual-qa

#16128 [#16086] Messaging - Composer - Show current message for user context…
  src/status_im2/common/bottom_sheet/styles.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#16194 Add Images count to reply
  src/status_im/data_store/messages.cljs
  src/status_im2/contexts/chat/composer/reply/style.cljs
  src/status_im2/contexts/chat/composer/reply/view.cljs
  status-go-version.json
  test/appium/views/chat_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16187 e2e: Fixes for nightly failures
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
Labels: tests

#16177 fix #16099
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16200 [#16078] - Add empty state component to messaging tabs
  src/status_im2/contexts/chat/home/style.cljs
  src/status_im2/contexts/chat/home/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16223 e2e: Updated report
  test/appium/support/base_test_report.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/chat_view.py
Labels: tests

#16218 [Fix] Incorrect navigation to message reaction bottom sheet
  src/status_im/chat/models/reactions.cljs
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
Labels: Tested - OK, request-manual-qa, E:Bugfixes, reactions

#16179 Layout updates/fixes for pinned messages bar
  src/quo2/components/banners/banner/style.cljs
  src/quo2/components/banners/banner/view.cljs
  src/status_im2/contexts/chat/messages/content/pin/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/style.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/style.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#16132 chore: remove mock data from syncing
  src/quo2/components/settings/settings_list/component_spec.cljs
  src/quo2/components/settings/settings_list/style.cljs
  src/quo2/components/settings/settings_list/view.cljs
  src/quo2/components/text_combinations/title/style.cljs
  src/quo2/components/text_combinations/title/view.cljs
  src/quo2/core_spec.cljs
  src/status_im2/common/syncing/style.cljs
  src/status_im2/common/syncing/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/style.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/onboarding/syncing/results/style.cljs
  src/status_im2/contexts/onboarding/syncing/results/view.cljs
  src/status_im2/contexts/onboarding/welcome/style.cljs
  src/status_im2/contexts/onboarding/welcome/view.cljs
  src/status_im2/contexts/quo_preview/settings/settings_list.cljs
  src/status_im2/contexts/syncing/device/style.cljs
  src/status_im2/contexts/syncing/device/view.cljs
  src/status_im2/contexts/syncing/syncing_devices_list/style.cljs
  src/status_im2/contexts/syncing/syncing_devices_list/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16170 [16082] Adjust height between messages to match designs
  src/status_im2/contexts/chat/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa

#16001 fix hole view usage for create profile picture
  src/quo2/components/inputs/profile_input/component_spec.cljs
  src/quo2/components/inputs/profile_input/view.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
Labels: Tested - OK, request-manual-qa

#16150 [iOS] Perform preflight check for local network permission
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/native_module/core.cljs
  src/status_im/signals/core.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  translations/en.json
Labels: ios, Tested - OK, pairing, request-manual-qa

#16190 fix: shell button position in chat screen
  src/status_im2/contexts/chat/composer/style.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
Labels: Tested - OK, request-manual-qa

#16234 fix: chat top bar iOS
  src/status_im2/contexts/chat/composer/view.cljs
Labels: Tested - OK, request-manual-qa

#16180 fix: fixes error message on login page
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: bug, Tested - OK, request-manual-qa

#16210 Prevent overflowing of chat name and message preview in the Chat List
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
Labels: Tested - OK, request-manual-qa

#16255 e2e: Fixes for jump-to
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
Labels: tests

#16246 Fix slow scrolling on chat screen
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#16256 [#15836] Images not displayed in chat when received by user with app …
  src/status_im/utils/http.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/audio/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
Labels: Tested - OK, request-manual-qa

#16262 e2e: false failures fixes
  test/appium/support/testrail_report.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#16016 Upgrade `react native` from `0.67.5` to `0.69.10`
  .gitignore
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/app/src/main/java/im/status/ethereum/StatusOkHttpClientFactory.java
  android/app/src/main/java/im/status/ethereum/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/im/status/ethereum/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/im/status/ethereum/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/build.gradle
  android/gradle.properties
  android/settings.gradle
  ci/Jenkinsfile.ios
  ios/.xcode.env
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.mm
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/deps/gradle/gradle_parser.awk
  nix/deps/nodejs-patched/default.nix
  nix/mobile/android/release.nix
  nix/overlay.nix
  nix/pkgs/aapt2/default.nix
  nix/pkgs/android-sdk/compose.nix
  nix/pkgs/android-sdk/shell.nix
  nix/shells.nix
  package.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#16258 [#15626] Bottom sheets stop opening if close the app with a bottom sh…
  src/status_im2/navigation/core.cljs
Labels: Tested - OK, request-manual-qa

#16224 feat: Lightbox share images
  ios/Podfile.lock
  package.json
  src/react_native/fs.cljs
  src/react_native/share.cljs
  src/status_im/chat/models/images.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/lightbox/utils.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa, images

#16272 Various fixes for the Information Box component
  src/quo2/components/info/information_box.cljs
  src/quo2/components/info/information_box/component_spec.cljs
  src/quo2/components/info/information_box/style.cljs
  src/quo2/components/info/information_box/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/info/information_box.cljs
Labels: bug, new-design [quo2]

#16267 [#16156] Top bar flashing
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#16281 fix the activity center crash when replying with an image
  src/status_im/utils/http.cljs
Labels: Tested - OK, request-manual-qa

#16259 Slide button component (bounty)
  src/quo2/components/buttons/slide_button/animations.cljs
  src/quo2/components/buttons/slide_button/component_spec.cljs
  src/quo2/components/buttons/slide_button/constants.cljs
  src/quo2/components/buttons/slide_button/style.cljs
  src/quo2/components/buttons/slide_button/utils.cljs
  src/quo2/components/buttons/slide_button/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/react_native/gesture.cljs
  src/status_im2/contexts/quo_preview/buttons/slide_button.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/test_helpers/component.cljs
Labels: external

#16280 Added PR Review Policy
  doc/README.md
  doc/merging-pr-process.md
  doc/pr-review-policy.md
Labels: docs

#16206 onboarding syncing updates
  src/quo2/components/buttons/button.cljs
  src/status_im2/contexts/onboarding/sign_in/style.cljs
  src/status_im2/contexts/syncing/scan_sync_code/style.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
Labels: Tested - OK, request-manual-qa

#16270 Disable audio messages
  src/status_im2/contexts/chat/composer/actions/view.cljs
Labels: Tested - OK, request-manual-qa

#16277 feat: add parallax component
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  src/js/worklets/parallax.js
  src/mocks/js_dependencies.cljs
  src/react_native/transparent_video.cljs
  src/status_im2/common/parallax/component_spec.cljs
  src/status_im2/common/parallax/style.cljs
  src/status_im2/common/parallax/view.cljs
  src/utils/worklets/parallax.cljs
  test-resources/override.js
  yarn.lock
Labels: Tested - OK, request-manual-qa

#16225 Add reorder-item component
  resources/images/mock2/contact.png
  resources/images/mock2/diamond.png
  resources/images/mock2/monkey.png
  resources/images/mock2/pinterest.png
  resources/images/mock2/verified.png
  src/quo2/components/settings/reorder_item/component_spec.cljs
  src/quo2/components/settings/reorder_item/items/item.cljs
  src/quo2/components/settings/reorder_item/items/item_placeholder.cljs
  src/quo2/components/settings/reorder_item/items/item_skeleton.cljs
  src/quo2/components/settings/reorder_item/items/item_tabs.cljs
  src/quo2/components/settings/reorder_item/style.cljs
  src/quo2/components/settings/reorder_item/types.cljs
  src/quo2/components/settings/reorder_item/view.cljs
  src/quo2/components/tabs/segmented_tab.cljs
  src/quo2/components/tabs/tab/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/settings/reorder_item.cljs
Labels: Tested - OK, external

#16265 Fix for two separate sections with different colors shown on the chat screen (dark mode)
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#16290 temporary hide mutual update's messages
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#16292 Fix clipped tags in Community Overview screen
  src/quo2/components/community/community_card_view.cljs
  src/quo2/components/community/community_view.cljs
  src/status_im2/contexts/communities/overview/style.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  translations/en.json
Labels: bug, communities

#16236 [#16118] bottom nav tab notification color
  src/quo2/components/navigation/bottom_nav_tab/styles.cljs
  src/quo2/components/navigation/bottom_nav_tab/view.cljs
  src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs
  src/status_im2/contexts/shell/components/bottom_tabs/view.cljs
Labels: Tested - OK, request-manual-qa

#16285 [#16066] bottom sheet height
  src/quo2/components/drawers/documentation_drawers/view.cljs
  src/status_im2/common/bottom_sheet/style.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#16095 Make profile photos visible by default
  src/status_im2/config.cljs
Labels: Tested - OK, request-manual-qa

#16314 Fix incorrect channel option
  src/status_im2/contexts/communities/actions/chat/view.cljs
Labels: bug

#16308 e2e: tests fixes
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#16323 tests: fix type of shell used for linting
  Makefile
Labels: tests

#16248 Upgrade `react-native-camera-kit` library to resolve camera issues in Sign In screen
  android/build.gradle
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  package.json
  src/mocks/js_dependencies.cljs
  src/react_native/camera_kit.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  src/status_im2/contexts/syncing/scan_sync_code/style.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  yarn.lock
Labels: Tested - OK, pairing, request-manual-qa

#16013 Use new login endpoint
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/native_module/core.cljs
  src/status_im/multiaccounts/login/core.cljs
Labels: Tested - OK, request-manual-qa

#16298 [16247] Make reactions row scrollable
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
Labels: Tested - OK, request-manual-qa

#16320 [15524] Support mentioning non Latin nicknames
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16343 nix: use builtins to not depend on channels
  nix/pkgs.nix
Labels: nix

#16232 Add featured-community data #16015
  src/status_im/multiaccounts/login/core.cljs
  src/status_im2/contexts/communities/discover/events.cljs
  src/status_im2/contexts/communities/discover/events_test.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
  src/status_im2/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#16337 [#16335] - Add space before "Forgot password?"
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: Tested - OK, request-manual-qa

#16325 init status-go logging once app start up
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/nodejs/status.cpp
  src/native_module/core.cljs
  src/status_im/utils/test.cljs
  src/status_im2/common/log.cljs
  status-go-version.json
Labels: request-manual-qa

#15128 [14556, 14259] Allow users to mute community channels and to mute chats for specific duration
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/drawers/action_drawers/view.cljs
  src/quo2/components/list_items/channel.cljs
  src/status_im/data_store/chats.cljs
  src/status_im2/common/home/actions/view.cljs
  src/status_im2/common/mute_chat_drawer/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/home/chat_list_item/style.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/communities/actions/chat/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
  src/utils/chats.cljs
  src/utils/datetime.cljs
  src/utils/datetime_test.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16188 Updated styles and layouts for messages
  src/quo2/components/dividers/date.cljs
  src/quo2/components/messages/author/style.cljs
  src/quo2/components/messages/author/view.cljs
  src/quo2/components/messages/system_message.cljs
  src/status_im2/contexts/chat/composer/reply/style.cljs
  src/status_im2/contexts/chat/composer/reply/view.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/pin/style.cljs
  src/status_im2/contexts/chat/messages/content/pin/view.cljs
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
  src/status_im2/contexts/chat/messages/content/style.cljs
  src/status_im2/contexts/chat/messages/content/text/style.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#16348 Fix incorrect background color in Community Overview screen
  src/quo2/components/navigation/page_nav.cljs
  src/status_im2/common/scroll_page/style.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: bug

#16347 nix: downgrade from 2.14.1 to 2.13.4
  nix/scripts/version.sh
Labels: nix

#16291 Jc/1 profile
  src/quo2/components/colors/color_picker/component_spec.cljs
  src/quo2/components/colors/color_picker/style.cljs
  src/quo2/components/colors/color_picker/view.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/onboarding/create_profile/style.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16339 fix: close keyboard when start scrolling on chat
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: bug, request-manual-qa

#16363 e2e: updated test_restore_multiaccount_with_waku_backup_remove_switch
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/base_element.py
  test/appium/views/dbs/waku_backup/user.py
Labels: tests

#16369 android: fix Gradle deps, drop Flipper, upgrade Fresco
  android/app/build.gradle
  android/app/src/debug/java/im/status/ethereum/ReactNativeFlipper.java
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/gradle.properties
  ios/Podfile
  ios/StatusIm/AppDelegate.mm
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
Labels: android, nix, dependencies

#16368 Redirect to onboarding welcome screen if all profiles are removed
  src/status_im2/contexts/onboarding/events.cljs
Labels: Tested - OK, request-manual-qa

#16355 [#16157] Pinned list button is absent when user is located at the top…
  ios/Podfile.lock
  src/quo2/components/community/channel_actions.cljs
  src/quo2/components/community/style.cljs
  src/quo2/components/icon.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/contexts/quo_preview/community/channel_actions.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/subs/chat/messages.cljs
Labels: Tested - OK, request-manual-qa

#16191 feat: add new theming mechanism
  package.json
  src/quo2/components/buttons/button.cljs
  src/quo2/components/dividers/divider_label.cljs
  src/quo2/components/tabs/tab/style.cljs
  src/quo2/components/tabs/tab/view.cljs
  src/quo2/components/tabs/tabs.cljs
  src/quo2/theme.cljs
  src/react_native/core.cljs
  src/status_im/bottom_sheet/sheets.cljs
  src/status_im2/contexts/activity_center/view.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/contexts/shell/components/shell_screen/view.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/navigation/options.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/navigation/view.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#16361 chore:move jump-to functionality inside namespace for shell
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/quo_preview/switcher/switcher_cards.cljs
  src/status_im2/contexts/shell/jump_to/animation.cljs
  src/status_im2/contexts/shell/jump_to/components/bottom_tabs/style.cljs
  src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs
  src/status_im2/contexts/shell/jump_to/components/floating_screens/style.cljs
  src/status_im2/contexts/shell/jump_to/components/floating_screens/view.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/style.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/view.cljs
  src/status_im2/contexts/shell/jump_to/components/jump_to_screen/style.cljs
  src/status_im2/contexts/shell/jump_to/components/jump_to_screen/view.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/style.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
  src/status_im2/contexts/shell/jump_to/constants.cljs
  src/status_im2/contexts/shell/jump_to/events.cljs
  src/status_im2/contexts/shell/jump_to/shared_values.cljs
  src/status_im2/contexts/shell/jump_to/state.cljs
  src/status_im2/contexts/shell/jump_to/utils.cljs
  src/status_im2/contexts/shell/jump_to/view.cljs
  src/status_im2/core.cljs
  src/status_im2/navigation/events.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#16366 nix: fix cache usage by modifying global config
  nix/scripts/lib.sh
  nix/scripts/setup.sh
  nix/scripts/upgrade.sh
Labels: nix

#16359 fix `make test` on macOS
  nix/shell.nix
Labels: nix

#16381 scripts: disable pipefail when greping for SHA
  scripts/update-status-go.sh
Labels: status-go

#16383 nix: build derivation from sources if cache fails
  nix/nix.conf
Labels: nix

#16370 [#16092] Auto-rotate breaks UI on Android
  src/status_im2/navigation/core.cljs
Labels: Tested - OK, tests, request-manual-qa

#16376 e2e: added attempts for MaxRetryError handling
  test/appium/tests/__init__.py
  test/appium/tests/base_test_case.py
Labels: tests

#16364 Add "Find sync code" bottom sheet
  resources/images/ui2/find-sync-code-desktop@2x.png
  resources/images/ui2/find-sync-code-desktop@3x.png
  resources/images/ui2/find-sync-code-mobile@2x.png
  resources/images/ui2/find-sync-code-mobile@3x.png
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/syncing/find_sync_code/view.cljs
  src/status_im2/contexts/syncing/how_to_pair/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/contexts/syncing/syncing_instructions/style.cljs
  src/status_im2/contexts/syncing/syncing_instructions/view.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/navigation/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#16372 js: remove unused visual tests and detox package
  .detoxrc.js
  Makefile
  package.json
  visual-test/config.json
  visual-test/environment.js
  visual-test/global-setup.js
  visual-test/global-teardown.js
  visual-test/setup.js
  yarn.lock
Labels: javascript

#16385 fix deleted message remains in preview at Jump to section #16374
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#16391 Update broken `Status development` link in ide-setup.md
  doc/ide-setup.md
Labels: docs

#16260 Fix race condition on sending messages
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16319 feat: add blur effect on scroll for buttons inside gallery view
  src/quo2/components/buttons/button.cljs
  src/quo2/components/buttons/style.cljs
  src/quo2/components/dropdowns/dropdown.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/common/bottom_sheet_screen/view.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
Labels: Tested - OK, request-manual-qa

#16049 fix: send user to settings if audio permission is rejected
  src/react_native/permissions.cljs
  src/status_im2/common/alert/events.cljs
  src/status_im2/contexts/chat/composer/actions/view.cljs
Labels: Tested - OK, request-manual-qa

#15543 fix: calibrate duration calculation of recorded audio
  src/quo2/components/record_audio/record_audio/__tests__/record_audio_component_spec.cljs
  src/quo2/components/record_audio/record_audio/buttons/record_button_big.cljs
  src/quo2/components/record_audio/record_audio/view.cljs
  src/quo2/components/record_audio/soundtrack/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/messages/content/audio/view.cljs
  src/status_im2/contexts/quo_preview/record_audio/record_audio.cljs
Labels: bug, Tested - OK, request-manual-qa

#16237 nix: fix Android SDK on Darwin with nixpkgs system override
  nix/pkgs.nix
  nix/pkgs/android-sdk/compose.nix
  nix/scripts/build.sh
  nix/scripts/shell.sh
Labels: nix

#16338 [#16322] - Carousel tap gesture
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/common/carousel/animation.cljs
  src/status_im2/contexts/onboarding/common/carousel/style.cljs
  src/status_im2/contexts/onboarding/common/carousel/view.cljs
  src/status_im2/contexts/onboarding/identifiers/view.cljs
Labels: Tested - OK, request-manual-qa

#16392 improve: enable collect logs before login
  src/status_im/utils/logging/core.cljs
Labels: Tested - OK, request-manual-qa

#16388 e2e: Updated error message in 702783
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#16268 feat: save image
  src/react_native/cameraroll.cljs
  src/status_im/chat/models/images.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, images

#16176 [15902] BUGFIX - Resolve public keys into the user's name in the confirmation drawer
  src/status_im2/common/confirmation_drawer/view.cljs
  src/status_im2/contexts/chat/lightbox/bottom_view.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa

#16296 feat: add parallax to biometrics page for whitelisted devices
  resources/images/ui2/biometrics@2x.png
  resources/images/ui2/biometrics@3x.png
  resources/videos2/biometrics_01.mp4
  resources/videos2/biometrics_02.mp4
  resources/videos2/biometrics_03.mp4
  resources/videos2/biometrics_04.mp4
  src/js/worklets/parallax.js
  src/react_native/core.cljs
  src/status_im2/common/parallax/style.cljs
  src/status_im2/common/parallax/whitelist.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
Labels: Tested - OK, request-manual-qa

#16407 nix: use Darwin stat command explicitly
  nix/scripts/lib.sh
Labels: nix

#16375 Onboarding: Identifiers page highlighting animation
  src/js/worklets/identifiers_highlighting.js
  src/mocks/js_dependencies.cljs
  src/react_native/reanimated.cljs
  src/status_im2/contexts/onboarding/identifiers/profile_card/style.cljs
  src/status_im2/contexts/onboarding/identifiers/profile_card/view.cljs
  src/status_im2/contexts/onboarding/identifiers/style.cljs
  src/status_im2/contexts/onboarding/identifiers/view.cljs
  src/utils/worklets/identifiers_highlighting.cljs
Labels: Tested - OK, request-manual-qa

#16358 chore: small refactor to remove some uses of status-im in status-im2
  src/status_im/chat/models/input.cljs
  src/status_im/ui/screens/wallet/recipient/views.cljs
  src/status_im/utils/utils.cljs
  src/status_im/wallet/recipient/core.cljs
  src/status_im2/common/toasts/view.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/utils/string.cljs
Labels: Tested - OK, request-manual-qa

#16294 Update animation for onboarding carousel.
  src/js/worklets/onboarding_carousel.js
  src/react_native/gesture.cljs
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/common/carousel/animation.cljs
  src/status_im2/contexts/onboarding/common/carousel/view.cljs
  src/status_im2/contexts/onboarding/identifiers/view.cljs
  src/utils/worklets/onboarding_carousel.cljs
Labels: Tested - OK, request-manual-qa

#16416 e2e: updated wait_for_status_to_be
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/views/chat_view.py
Labels: tests

#16426 fix: ROW_NUMBER() not work on ios for some reason
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16439 Tests/nightly 29 07
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/member3.png
Labels: tests

#16431 fix App crashes when jump-to has group chat card
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#16428 [Fixes: #16203] Fix delete for me replies images
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16419 feat: allow navigation within different stacks
  src/react_native/navigation.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/events.cljs
Labels: Tested - OK, request-manual-qa, navigation

#16399 chore: use with theme for step component
  src/quo2/components/counter/step/style.cljs
  src/quo2/components/counter/step/view.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: Tested - OK, request-manual-qa
