Repository status-im/status-mobile, pull requests merged in 2023-10, with the labels that each got.

#17470 [#17288] refactor: migrate previews to new api
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/profile/collectible.cljs
  src/status_im2/contexts/quo_preview/profile/profile_card.cljs
  src/status_im2/contexts/quo_preview/profile/select_profile.cljs
  src/status_im2/contexts/quo_preview/profile/showcase_nav.cljs
  src/status_im2/contexts/quo_preview/reactions/react.cljs
  src/status_im2/contexts/quo_preview/record_audio/record_audio.cljs
  src/status_im2/contexts/quo_preview/selectors/disclaimer.cljs
  src/status_im2/contexts/quo_preview/selectors/filter.cljs
  src/status_im2/contexts/quo_preview/selectors/reactions.cljs
  src/status_im2/contexts/quo_preview/selectors/selectors.cljs
Labels: followup required

#17424 Show links inside activity-center mention
  src/status_im2/contexts/shell/activity_center/notification/mentions/view.cljs
Labels: Tested - OK, request-manual-qa

#17374 Fix show the hashtag in chat when replying/copying status-tag
  src/status_im2/contexts/chat/composer/reply/view.cljs
Labels: Tested - OK, request-manual-qa

#17477 Tests/go wait
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/sign_in_view.py
Labels: tests

#17459 Only count images in an album in photo selector
  src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs
  src/status_im2/contexts/chat/photo_selector/events.cljs
Labels: Tested - OK, request-manual-qa

#17003 [16845] Wrong buttons background color on community home screen's page nav
  package.json.gpg
  src/quo2/components/navigation/page_nav/view.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#17461 [#17396] fix: Mention is displayed as public key in PNs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#17400 feat: implement saved contact address list item component
  src/quo2/components/icons/svg.cljs
  src/quo2/components/list_items/saved_contact_address/component_spec.cljs
  src/quo2/components/list_items/saved_contact_address/style.cljs
  src/quo2/components/list_items/saved_contact_address/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/list_items/saved_contact_address.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  translations/en.json
Labels: feature, followup required

#17472 Filter debugging 2
  nix/status-go/library/default.nix
  nix/status-go/mobile/build.nix
  status-go-version.json
Labels: Tested - OK

#17386 fix(identifier): emoji hash line height
  src/status_im2/contexts/onboarding/identifiers/profile_card/style.cljs
Labels: :eyes: design-input-required

#17495 Remove options to create community from mobile from release and nightly builds
  .env
  .env.release
  src/status_im2/contexts/communities/actions/home_plus/view.cljs
Labels: Tested - OK

#17484 fix: typos
  README.md
  doc/export-icons.md
  doc/how-to-launch-e2e.md
  doc/ide-setup.md
  doc/starting-guide.md
Labels: external

#17491 Reduce Clojure linter warning noise
  Makefile
  ci/Jenkinsfile.tests
  shadow-cljs.edn
Labels: E:Mobile Developer XP

#17268 updated selected item view
  src/status_im2/common/bottom_sheet/style.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#17519 Fix: onboarding
  src/quo2/components/inputs/input/view.cljs
  src/quo2/components/inputs/profile_input/view.cljs
  src/quo2/components/inputs/title_input/view.cljs
  src/status_im2/contexts/wallet/address_watch/view.cljs
Labels: Tested - OK, request-manual-qa

#17487 Copy update to change text from skip to continue
  src/status_im2/contexts/onboarding/identifiers/view.cljs
Labels: Tested - OK, request-manual-qa

#16852 Enter scan code tab in Syncing
  doc/decisions/UI-related/7-august-2023-paste-button-ux.md
  src/status_im2/contexts/syncing/enter_sync_code/style.cljs
  src/status_im2/contexts/syncing/enter_sync_code/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/style.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#17442 Update waku nodes
  src/status_im2/config.cljs
  src/status_im2/contexts/profile/create/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17543 Upgrade clj-kondo and configure new linters
  .clj-kondo/config.edn
  nix/overlay.nix
  src/quo2/components/buttons/composer_button/style.cljs
  src/quo2/components/buttons/wallet_button/style.cljs
  src/quo2/components/calendar/calendar/utils.cljs
  src/quo2/components/graph/wallet_graph/view.cljs
  src/quo2/components/settings/reorder_item/view.cljs
  src/status_im/data_store/activities.cljs
  src/status_im/ui/screens/chat/message/legacy_view.cljs
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im/wallet/db_test.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/composer/reply/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/utils.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/emoji_picker/constants.cljs
  src/status_im2/contexts/onboarding/common/carousel/animation.cljs
  src/status_im2/contexts/profile/profiles/view.cljs
  src/status_im2/contexts/quo_preview/switcher/switcher_cards.cljs
  src/status_im2/contexts/shell/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/contact_requests/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/shell/activity_center/view.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
  src/status_im2/contexts/shell/jump_to/events.cljs
  src/utils/datetime_test.cljs
  src/utils/ethereum/eip/eip55_test.cljs
Labels: E:Mobile Linting

#17451 Migrate away from rf/defn and rf/merge (first step)
  .zprintrc
  doc/new-guidelines.md
  src/status_im/communities/core.cljs
  src/status_im/events.cljs
  src/status_im/stickers/core.cljs
  src/status_im/test_runner.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im/wallet/swap/core.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/shell/activity_center/events.cljs
  src/status_im2/contexts/shell/activity_center/events_test.cljs
  src/status_im2/core.cljs
  src/status_im2/navigation/events.cljs
  src/status_im2/setup/dev.cljs
  src/status_im2/setup/interceptors.cljs
  src/utils/re_frame.clj
  src/utils/re_frame.cljs
Labels: Tested - OK, request-manual-qa, E:Tech Debt, E:Mobile Developer XP, E:Mobile Linting

#17253 chats 1-1 reviews
  src/quo2/components/messages/author/style.cljs
  src/status_im2/contexts/chat/messages/avatar/view.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/contexts/chat/messages/navigation/style.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
Labels: request-manual-qa

#17548 fix: several bugs in 1.25 design feedback
  src/status_im2/contexts/chat/messages/avatar/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/onboarding/identifiers/profile_card/style.cljs
Labels: Tested - OK, request-manual-qa

#17544 fix: back button on 1:1 chat
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, :eyes: design-input-required, request-manual-qa

#17575 e2e: some fixes and moved old ui tests to a separate dir
  test/appium/support/testrail_report.py
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/old_ui/chats/test_1_1_public_chats.py
  test/appium/tests/old_ui/chats/test_group_chat.py
  test/appium/tests/old_ui/chats/test_public_chat_browsing.py
  test/appium/tests/old_ui/medium/test_browser_profile.py
  test/appium/tests/old_ui/medium/test_chats_m.py
  test/appium/tests/old_ui/medium/test_deeplink_chat_share_profile.py
  test/appium/tests/old_ui/medium/test_pairing_devices_sync_m.py
  test/appium/tests/old_ui/medium/test_permissions_scan_qr.py
  test/appium/tests/old_ui/medium/test_profile_m.py
  test/appium/tests/old_ui/medium/test_single_device.py
  test/appium/tests/old_ui/medium/test_wallet_keycard_m.py
  test/appium/tests/old_ui/onboarding/test_onboarding_flows.py
  test/appium/tests/old_ui/test_pairing_devices_sync.py
  test/appium/tests/old_ui/wallet_and_tx/test_send_tx_dapp_keycard.py
  test/appium/tests/old_ui/wallet_and_tx/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/elements_templates/discovery_join_button.png
  test/appium/views/home_view.py
Labels: tests

#17561 [Fix] SVG Icon color
  src/quo2/components/icon.cljs
Labels: Tested - OK, request-manual-qa

#17489 Faded first line of composer
  src/status_im2/contexts/chat/composer/handlers.cljs
Labels: Tested - OK, request-manual-qa

#17221 [#16329] QR code variants
  package.json
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/avatars/wallet_user_avatar.cljs
  src/quo2/components/share/qr_code/style.cljs
  src/quo2/components/share/qr_code/view.cljs
  src/quo2/components/share/share_qr_code/view.cljs
  src/quo2/core.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/wallet/request/views.cljs
  src/status_im2/common/qr_code_viewer/style.cljs
  src/status_im2/common/qr_code_viewer/view.cljs
  src/status_im2/common/qr_codes/view.cljs
  src/status_im2/contexts/quo_preview/avatars/wallet_user_avatar.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/share/qr_code.cljs
  src/status_im2/contexts/quo_preview/share/share_qr_code.cljs
  src/status_im2/contexts/shell/share/view.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#17562 Changes to onboarding/new-to-status (quo/fonts/spacings/copy)
  resources/images/ui2/generate-keys@2x.png
  resources/images/ui2/generate-keys@3x.png
  src/quo2/components/onboarding/small_option_card/style.cljs
  src/quo2/components/onboarding/small_option_card/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/style.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/quo_preview/onboarding/small_option_card.cljs
  test/appium/views/sign_in_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#17466 Disable scroll to the bottom button when composer is active.
  src/status_im2/contexts/chat/composer/handlers.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
  src/status_im2/contexts/chat/composer/view.cljs
Labels: Tested - OK, request-manual-qa

#17556 Wallet: About Tab
  src/quo2/components/settings/data_item/style.cljs
  src/quo2/components/settings/data_item/view.cljs
  src/status_im2/contexts/quo_preview/settings/data_item.cljs
  src/status_im2/contexts/wallet/account/style.cljs
  src/status_im2/contexts/wallet/account/tabs/about/style.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
  src/status_im2/contexts/wallet/account/tabs/style.cljs
  src/status_im2/contexts/wallet/account/tabs/view.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  translations/en.json
Labels: E:Mobile Wallet Accounts Page MVP, followup required

#17591 [#17446] fix: Display name is not shown in chats after sync
  src/status_im/multiaccounts/core.cljs
Labels: Tested - OK, request-manual-qa

#17607 e2e: fixed issue with naming
  test/appium/tests/old_ui/chats/test_1_1_public_chats_old.py
  test/appium/tests/old_ui/chats/test_group_chat_old.py
  test/appium/tests/old_ui/chats/test_public_chat_browsing_old.py
Labels: tests

#17473 chore: slider button - add error type, blur variant and fix small ui bug
  src/quo2/components/buttons/slide_button/animations.cljs
  src/quo2/components/buttons/slide_button/component_spec.cljs
  src/quo2/components/buttons/slide_button/style.cljs
  src/quo2/components/buttons/slide_button/utils.cljs
  src/quo2/components/buttons/slide_button/view.cljs
  src/status_im2/common/standard_authentication/standard_auth/view.cljs
  src/status_im2/contexts/quo_preview/buttons/slide_button.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
Labels: Tested - OK, request-manual-qa

#17547 remove unnecessary logs
  src/status_im2/common/bottom_sheet/view.cljs
Labels: Tested - OK, request-manual-qa

#17609 Bottom Sheet Fixes
  src/quo2/components/gradient/gradient_cover/style.cljs
  src/quo2/components/gradient/gradient_cover/view.cljs
  src/status_im2/common/bottom_sheet/style.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/quo_preview/gradient/gradient_cover.cljs
  src/status_im2/contexts/shell/activity_center/header/view.cljs
Labels: Tested - OK, request-manual-qa

#17610 Add custom linter for i18n/label translation keywords
  .clj-kondo/babashka/fs/config.edn
  .clj-kondo/babashka/sci/config.edn
  .clj-kondo/babashka/sci/sci/core.clj
  .clj-kondo/config.edn
  .clj-kondo/status-im/config.edn
  .clj-kondo/status-im/hooks/core.clj
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/quo2/components/messages/system_message.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/ui/components/copyable_text.cljs
  src/status_im/ui/screens/mobile_network_settings/sheets.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/wallet/buy_crypto/views.cljs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
  src/status_im2/common/biometric/events.cljs
  src/status_im2/contexts/chat/messages/content/audio/view.cljs
  src/status_im2/contexts/chat/messages/link_preview/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/overview/utils.cljs
  src/status_im2/contexts/profile/profiles/view.cljs
  src/status_im2/contexts/quo_preview/messages/gap.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/wallet/transactions.cljs
Labels: E:Mobile Linting

#17545 fix: image preview padding
  src/status_im2/contexts/chat/composer/images/style.cljs
  src/status_im2/contexts/chat/composer/images/view.cljs
  src/status_im2/contexts/chat/composer/style.cljs
Labels: Tested - OK, :eyes: design-input-required, request-manual-qa

#17617 feat: implement address list item component
  src/quo2/components/avatars/wallet_user_avatar.cljs
  src/quo2/components/list_items/address/component_spec.cljs
  src/quo2/components/list_items/address/style.cljs
  src/quo2/components/list_items/address/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/list_items/address.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: feature, followup required

#17603 [#17435] migrate status-im.notifications
  src/mocks/js_dependencies.cljs
  src/native_module/core.cljs
  src/native_module/push_notifications.cljs
  src/react_native/push_notification_ios.cljs
  src/status_im/chat/models/loading.cljs
  src/status_im/communities/core.cljs
  src/status_im/contact/block.cljs
  src/status_im/events.cljs
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/notifications/android.cljs
  src/status_im/notifications/core.cljs
  src/status_im/notifications/local.cljs
  src/status_im/notifications/wallet.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/notifications_settings/events.cljs
  src/status_im/ui/screens/notifications_settings/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/push_notifications/effects.cljs
  src/status_im2/contexts/push_notifications/events.cljs
  src/status_im2/contexts/push_notifications/local/effects.cljs
  src/status_im2/contexts/push_notifications/local/events.cljs
  src/status_im2/core.cljs
  src/status_im2/subs/root.cljs
  src/status_im2/subs/wallet/transactions.cljs
  src/utils/re_frame.cljs
Labels: Tested - OK, request-manual-qa

#17568 fix: chat over scroll
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#17612 Wallet: Account Options
  src/quo2/components/drawers/drawer_top/component_spec.cljs
  src/quo2/components/drawers/drawer_top/view.cljs
  src/quo2/components/list_items/account/view.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  translations/en.json
Labels: E:Mobile Wallet Accounts Page MVP, followup required

#17573 Composer - Link previews - Adjust for upcoming API breaking changes in status-go
  src/status_im2/contexts/chat/composer/link_preview/events.cljs
  src/status_im2/contexts/chat/composer/link_preview/events_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, E:Mobile URL Preview MVP, status-go

#17567 remove custom-color-by-theme method, add resolve-color method
  src/quo2/components/avatars/account_avatar/component_spec.cljs
  src/quo2/components/avatars/account_avatar/style.cljs
  src/quo2/components/avatars/channel_avatar/style.cljs
  src/quo2/components/avatars/channel_avatar/view.cljs
  src/quo2/components/avatars/icon_avatar.cljs
  src/quo2/components/avatars/user_avatar/style.cljs
  src/quo2/components/avatars/wallet_user_avatar.cljs
  src/quo2/components/calendar/calendar_day/style.cljs
  src/quo2/components/code/common/style.cljs
  src/quo2/components/code/common/view.cljs
  src/quo2/components/dividers/new_messages.cljs
  src/quo2/components/list_items/account_list_card/view.cljs
  src/quo2/components/list_items/address/view.cljs
  src/quo2/components/list_items/channel/style.cljs
  src/quo2/components/list_items/community/style.cljs
  src/quo2/components/list_items/token_value/style.cljs
  src/quo2/components/record_audio/record_audio/buttons/lock_button.cljs
  src/quo2/components/selectors/selectors/style.cljs
  src/quo2/components/selectors/selectors/view.cljs
  src/quo2/components/settings/accounts/style.cljs
  src/quo2/components/settings/accounts/view.cljs
  src/quo2/components/wallet/keypair/view.cljs
  src/quo2/components/wallet/network_bridge/style.cljs
  src/quo2/components/wallet/network_bridge/view.cljs
  src/quo2/components/wallet/network_link/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/colors.cljs
  src/quo2/foundations/colors_test.cljs
  src/status_im2/contexts/quo_preview/avatars/channel_avatar.cljs
  src/status_im2/contexts/quo_preview/common.cljs
  src/status_im2/contexts/quo_preview/dividers/new_messages.cljs
  src/status_im2/contexts/quo_preview/list_items/channel.cljs
  src/status_im2/contexts/quo_preview/list_items/community_list.cljs
  src/status_im2/contexts/quo_preview/preview.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
Labels: Tested - OK, request-manual-qa

#17642 remove SQLCipher dependency for ios
  ios/Podfile
  ios/Podfile.lock
Labels: Tested - OK

#17190 Implement bottom-actions component
  src/quo2/components/buttons/button/properties.cljs
  src/quo2/components/drawers/bottom_actions/component_spec.cljs
  src/quo2/components/drawers/bottom_actions/style.cljs
  src/quo2/components/drawers/bottom_actions/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/drawers/bottom_actions.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: followup required

#17608 [#17533] fix: 'Sign in' page overlaps 'Main' page
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
Labels: request-manual-qa

#17643 Wallet: Activity Tab
  src/status_im2/contexts/wallet/account/tabs/view.cljs
  src/status_im2/contexts/wallet/common/activity_tab/view.cljs
  src/status_im2/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/home/view.cljs
Labels: E:Mobile Wallet Accounts Page MVP, followup required

#17428 fix: long press & bg color animation for deleted message
  src/quo2/components/messages/system_message/style.cljs
  src/quo2/components/messages/system_message/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/view.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa

#17645 [#17507] fix: image placeholder issue in create-profile
  src/status_im2/contexts/onboarding/create_profile/view.cljs
Labels: Tested - OK, request-manual-qa

#17604 Test ping peers fix for filter
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17657 nix: pin Ruby at 3.1, fastlane shell for nix-update-gems
  Makefile
  nix/overlay.nix
Labels: ios, nix

#17464 feat: scan account from QR
  src/quo/components/inputs/address_input/component_spec.cljs
  src/quo/components/inputs/address_input/view.cljs
  src/quo/components/navigation/page_nav/view.cljs
  src/status_im/ui/screens/qr_scanner/views.cljs
  src/status_im2/common/scan_qr_code/style.cljs
  src/status_im2/common/scan_qr_code/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/quo_preview/inputs/address_input.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/contexts/wallet/events_test.cljs
  src/status_im2/contexts/wallet/scan_account/view.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/root.cljs
  translations/en.json
Labels: Tested - OK, feature, request-manual-qa, followup required

#17670 e2e: updated GH report and fixed 2 tests
  test/appium/support/base_test_report.py
  test/appium/support/github_report.py
  test/appium/support/testrail_report.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/chat_view.py
Labels: tests

#17637 Implement Edit Wallet Account Screen (base)
  src/quo/components/drawers/action_drawers/style.cljs
  src/quo/components/inputs/title_input/view.cljs
  src/quo/components/settings/data_item/component_spec.cljs
  src/quo/components/settings/data_item/view.cljs
  src/quo/components/settings/section_label/view.cljs
  src/status_im2/contexts/quo_preview/settings/data_item.cljs
  src/status_im2/contexts/wallet/account/style.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/screen_base/create_or_edit_account/style.cljs
  src/status_im2/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/edit_account/style.cljs
  src/status_im2/contexts/wallet/edit_account/view.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: followup required

#17414 Fix: Messages/Author component overflow
  src/quo/components/inputs/input/view.cljs
  src/quo/components/list_items/user_list.cljs
  src/quo/components/messages/author/style.cljs
  src/quo/components/messages/author/view.cljs
  src/quo/core.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/contacts/drawers/nickname_drawer/style.cljs
  src/status_im2/contexts/contacts/drawers/nickname_drawer/view.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: Tested - OK, request-manual-qa, followup required

#17685 nix: do not exclude module files from Gradle deps
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/deps/gradle/url2json.sh
Labels: android, nix

#17488 [#17395] Temporarily disables image options in edit mode
  src/status_im2/contexts/chat/composer/actions/view.cljs
Labels: Tested - OK, request-manual-qa, external

#17638 e2e: join community when node owner is offline
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/chat_view.py
Labels: tests

#17681 e2e: added test for Add contact validation
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#17691 Fix crash when selecting photos from cameraroll [iOS]
  src/status_im2/contexts/chat/photo_selector/events.cljs
Labels: Tested - OK, request-manual-qa

#17690 Upgrade Clojure libraries
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/status_im2/common/log.cljs
  src/status_im2/contexts/chat/messages/list/events_test.cljs
  src/utils/re_frame.clj
Labels: nix, dependencies

#17480 feat: support new universal/deep link format
  android/app/src/main/AndroidManifest.xml
  ios/StatusIm/Info.plist
  ios/StatusIm/StatusIm.entitlements
  ios/StatusImPR/Info.plist
  ios/StatusImPR/StatusImPR.entitlements
  src/status_im/router/core.cljs
  src/status_im/router/core_test.cljs
  src/status_im/ui/screens/browser/site_blocked/views.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/utils/universal_links/core_test.cljs
  src/status_im/utils/universal_links/utils.cljs
  src/status_im/utils/universal_links/utils_test.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/status_im2/contexts/add_new_contact/events_test.cljs
  src/status_im2/contexts/chat/messages/link_preview/events.cljs
  src/utils/address.cljs
  src/utils/address_test.cljs
  src/utils/image_server.cljs
Labels: Tested - OK, request-manual-qa

#17715 e2e: new link format
  test/appium/tests/activity_center/test_activity_center.py
Labels: tests

#17594 fix: remove qa-only features(unicorn, skull)
  src/quo/components/navigation/top_nav/view.cljs
  src/status_im/bottom_sheet/sheets.cljs
  src/status_im/mobile_sync_settings/core.cljs
  src/status_im/ui/screens/mobile_network_settings/sheets.cljs
  src/status_im/ui/screens/mobile_network_settings/view.cljs
  src/status_im2/common/home/top_nav/view.cljs
Labels: Tested - Issues, request-manual-qa, E:Mobile Bug MVP, E:Design Feedback 1.25

#17708 Update `react-native-camera-kit` to latest beta to enable programmitcal zooming
  android/gradle.properties
  ios/Podfile
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  package.json
  src/status_im2/contexts/chat/camera/view.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#17697 old wallet fixes
  src/status_im/ui/components/button/view.cljs
  src/status_im/ui/components/text.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/styles.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
Labels: Tested - OK, request-manual-qa

#17498 Fix recent album not showing count
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  package.json
  package.json.gpg
  src/mocks/js_dependencies.cljs
  src/react_native/cameraroll.cljs
  src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs
  src/status_im2/contexts/chat/photo_selector/events.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/subs/chats.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#17549 Refactor tag preview screens to new api
  src/quo/components/community/token_gating.cljs
  src/quo/components/tags/token_tag.cljs
  src/quo/components/tags/token_tag/style.cljs
  src/quo/components/tags/token_tag/view.cljs
  src/quo/core.cljs
  src/status_im2/contexts/quo_preview/drawers/permission_drawers.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
  src/status_im2/contexts/quo_preview/tags/network_tags.cljs
  src/status_im2/contexts/quo_preview/tags/number_tag.cljs
  src/status_im2/contexts/quo_preview/tags/permission_tag.cljs
  src/status_im2/contexts/quo_preview/tags/status_tags.cljs
  src/status_im2/contexts/quo_preview/tags/tag.cljs
  src/status_im2/contexts/quo_preview/tags/tags.cljs
  src/status_im2/contexts/quo_preview/tags/token_tag.cljs
Labels: Tested - OK, request-manual-qa

#17710 Wallet: Network Preferences drawer
  src/quo/components/avatars/icon_avatar.cljs
  src/quo/components/drawers/bottom_actions/component_spec.cljs
  src/quo/components/drawers/bottom_actions/view.cljs
  src/quo/components/settings/category/settings/view.cljs
  src/quo/components/settings/category/style.cljs
  src/quo/components/settings/settings_item/view.cljs
  src/status_im2/contexts/wallet/common/network_preferences/style.cljs
  src/status_im2/contexts/wallet/common/network_preferences/view.cljs
  src/status_im2/contexts/wallet/edit_account/view.cljs
  src/test_helpers/component.cljs
  translations/en.json
Labels: E:Mobile Wallet MVP

#17704 Don't display "Add Unknown as contact to send a Message" if chat is not loaded
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#17730 wallet: token value drawer
  resources/images/icons2/20x20/hide-password@2x.png
  resources/images/icons2/20x20/hide-password@3x.png
  resources/images/icons2/20x20/hide@2x-1.png
  resources/images/icons2/20x20/hide@2x.png
  resources/images/icons2/20x20/hide@3x-1.png
  resources/images/icons2/20x20/hide@3x.png
  src/quo/components/inputs/input/view.cljs
  src/quo/components/list_items/token_value/view.cljs
  src/status_im2/contexts/wallet/account/tabs/view.cljs
  src/status_im2/contexts/wallet/common/token_value/view.cljs
  src/status_im2/contexts/wallet/home/view.cljs
  translations/en.json
Labels: E:Mobile Wallet MVP

#17726 [#17230] fix: fetch group member info
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17667 Token network component #17369
  src/quo/components/list_items/token_network/component_spec.cljs
  src/quo/components/list_items/token_network/style.cljs
  src/quo/components/list_items/token_network/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im2/contexts/quo_preview/list_items/token_network.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: external

#17719 Document how to auto-format Clojure files in VSCode and using zprint
  .vscode/settings.example.json
  doc/ide-setup.md
Labels: E:Mobile Developer XP

#17640 Fix Composer not focusing on edit/reply
  src/status_im2/contexts/chat/composer/effects.cljs
Labels: Tested - OK, request-manual-qa

#17600 Don't sync AC notifications, only decisions/state
  src/status_im2/contexts/shell/activity_center/notification/contact_requests/view.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17496 create wallet account
  ios/Podfile.lock
  src/status_im2/common/standard_authentication/enter_password/view.cljs
  src/status_im2/common/standard_authentication/standard_auth/view.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/contexts/wallet/create_account/view.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/subs/root.cljs
  src/utils/re_frame.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#17694 [#17534] fix: Add contact scan QR screen back handler issue
  src/status_im/ui/screens/qr_scanner/views.cljs
Labels: Tested - OK, request-manual-qa

#17465 Make color selector take full device width to match Figma
  src/quo/components/colors/color/constants.cljs
  src/quo/components/colors/color/style.cljs
  src/quo/components/colors/color/view.cljs
  src/quo/components/colors/color_picker/view.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
Labels: Tested - OK, request-manual-qa

#17457 [#16755] - Network routing component
  src/quo/components/wallet/network_routing/animation.cljs
  src/quo/components/wallet/network_routing/style.cljs
  src/quo/components/wallet/network_routing/view.cljs
  src/quo/core.cljs
  src/quo2/components/wallet/network_routing/component_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/network_routing.cljs
Labels: request-manual-qa

#17731 [#17423] fix: update sync flow
  resources/images/ui2/welcome_illustration@2x.png
  resources/images/ui2/welcome_illustration@3x.png
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/onboarding/welcome/style.cljs
  src/status_im2/contexts/onboarding/welcome/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#17650 chore: add sub to get network info
  src/quo/foundations/resources.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/contexts/wallet/home/view.cljs
  src/status_im2/data_store/wallet.cljs
  src/status_im2/subs/root.cljs
  src/status_im2/subs/wallet/networks.cljs
  src/status_im2/subs/wallet/networks_test.cljs
Labels: Tested - OK, request-manual-qa

#17732 Wallet: Address Text
  src/quo/components/drawers/drawer_top/component_spec.cljs
  src/quo/components/drawers/drawer_top/view.cljs
  src/quo/components/list_items/account/view.cljs
  src/quo/components/list_items/account_list_card/view.cljs
  src/quo/components/wallet/address_text/style.cljs
  src/quo/components/wallet/address_text/view.cljs
  src/quo/components/wallet/keypair/component_spec.cljs
  src/quo/core.cljs
  src/status_im2/contexts/quo_preview/drawers/drawer_top.cljs
  src/status_im2/contexts/quo_preview/gradient/gradient_cover.cljs
  src/status_im2/contexts/quo_preview/list_items/account_list_card.cljs
  src/status_im2/contexts/quo_preview/list_items/address.cljs
  src/status_im2/contexts/quo_preview/wallet/keypair.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/edit_account/view.cljs
  src/utils/address.cljs
Labels: E:Mobile Wallet MVP

#17768 e2e: test fixes
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/elements_templates/member3.png
  test/appium/views/home_view.py
Labels: tests

#17774 e2e: fix for app closed after closing gallery
  test/appium/tests/critical/chats/test_group_chat.py
Labels: tests

#17447 Connect Wallet Home Page to backend - Accounts card
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/wallet/account/style.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/contexts/wallet/home/view.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/root.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#17736 [#17023] Share qr code variants
  src/quo/components/list_items/preview_list/view.cljs
  src/quo/components/share/share_qr_code/component_spec.cljs
  src/quo/components/share/share_qr_code/style.cljs
  src/quo/components/share/share_qr_code/view.cljs
  src/status_im2/common/qr_code_viewer/style.cljs
  src/status_im2/common/qr_codes/view.cljs
  src/status_im2/contexts/quo_preview/share/share_qr_code.cljs
  src/status_im2/contexts/shell/share/style.cljs
  src/status_im2/contexts/shell/share/view.cljs
  src/test_helpers/component.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#17705 e2e: test for sending image with camera
  src/status_im2/contexts/chat/composer/actions/view.cljs
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/views/chat_view.py
Labels: tests
