Repository status-im/status-mobile, pull requests merged in 2023-05, with the labels that each got.

#15772 feat: composer - edit message
  ios/Podfile.lock
  resources/images/icons2/16x16/connector-dotted@2x.png
  resources/images/icons2/16x16/connector-dotted@3x.png
  src/status_im/chat/models/input.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/actions/view.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/constants.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/edit/style.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/edit/view.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/effects.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/handlers.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/reply/view.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/style.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/utils.cljs
  src/status_im2/contexts/chat/bottom_sheet_composer/view.cljs
  src/status_im2/contexts/chat/messages/list/new_temp_view.cljs
Labels: Tested - OK, request-manual-qa

#15757 On password creation screen make the password disclaimer tappable
  src/quo2/components/selectors/disclaimer/view.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
Labels: Tested - OK, request-manual-qa

#15717 fix: quo2 title-input component selection color fix for android
  src/quo2/components/inputs/title_input/style.cljs
Labels: Tested - OK, request-manual-qa

#15804 Fix community disclaimer checkbox
  src/status_im2/contexts/communities/actions/request_to_join/view.cljs
Labels: Tested - OK, request-manual-qa

#15778 Fix for mention text overlaying message text when mention is added during message editing (Android)
  src/status_im2/contexts/chat/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa

#15674 quo2 documentation drawer component
  src/quo2/components/drawers/documentation_drawers/component_spec.cljs
  src/quo2/components/drawers/documentation_drawers/style.cljs
  src/quo2/components/drawers/documentation_drawers/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/common/bottom_sheet/styles.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/quo_preview/drawers/documentation_drawers.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: Tested - OK, request-manual-qa

#15594 feat: implement audio message component
  resources/images/icons2/20x20/pause-audio@2x.png
  resources/images/icons2/20x20/pause-audio@3x.png
  resources/images/icons2/20x20/play-audio@2x.png
  resources/images/icons2/20x20/play-audio@3x.png
  src/quo2/components/record_audio/record_audio/view.cljs
  src/quo2/components/record_audio/soundtrack/__tests__/soundtrack_component_spec.cljs
  src/quo2/components/record_audio/soundtrack/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/chat/messages/content/audio/component_spec.cljs
  src/status_im2/contexts/chat/messages/content/audio/style.cljs
  src/status_im2/contexts/chat/messages/content/audio/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/core_spec.cljs
  src/test_helpers/component.cljs
  test/jest/jestSetup.js
  translations/en.json
Labels: Tested - OK, request-manual-qa, new-design [quo2]

#15806 quo2 predictive keyboard component
  src/quo2/components/buttons/predictive_keyboard/component_spec.cljs
  src/quo2/components/buttons/predictive_keyboard/style.cljs
  src/quo2/components/buttons/predictive_keyboard/view.cljs
  src/quo2/components/info/info_message.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/buttons/predictive_keyboard.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: Tested - OK

#15835 nix: fix handling POMs without JARs
  nix/deps/gradle/url2json.sh
Labels: android, nix, dependencies

#15613 Improve last message preview
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/messages.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15786 [15612] Only allow showing universal links after clicking start using status
  src/status_im/events.cljs
  src/status_im/transport/core.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im2/contexts/onboarding/welcome/view.cljs
Labels: Tested - OK, request-manual-qa

#15833 'Unpin' option in 1-1 chat for deleted message
  src/status_im2/contexts/chat/messages/drawers/view.cljs
Labels: Tested - OK, request-manual-qa

#15831 [#15663] Recovery phrase onboarding
  src/quo2/components/inputs/recovery_phrase/component_spec.cljs
  src/quo2/components/inputs/recovery_phrase/view.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/style.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/view.cljs
  src/test_helpers/component.cljs
Labels: onboarding

#15858 ci: bump timeout for tests to 15 minutes
  ci/Jenkinsfile.tests
Labels: tests, infra

#15850 ci: add Alchemy and Infura credentials in CI
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  scripts/build-android.sh
Labels: security, nix, infra

#15865 fix: maximized composer incorrect bottom padding
  src/status_im2/contexts/chat/composer/style.cljs
  src/status_im2/contexts/chat/composer/view.cljs
Labels: refactoring

#15867 nix: use SRI hashes for Gradle dependencies
  nix/deps/gradle/deps.json
  nix/deps/gradle/url2json.sh
Labels: android, nix, dependencies

#15845 Show correct error message while unlocking app
  src/status_im/signals/core.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: Tested - OK

#15697 feat: doc info boxes while onboarding
  src/quo2/components/counter/step/style.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/onboarding/profiles/style.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15840 [Fix] Tapable area of user avatar in chat
  src/status_im2/contexts/chat/messages/avatar/view.cljs
Labels: bug, Tested - OK, request-manual-qa, E:MobileMessagingRD

#15876 chore: restore label on im new to status page
  src/status_im2/contexts/onboarding/new_to_status/style.cljs
Labels: Tested - OK, request-manual-qa

#15844 Double-tap for communities & fix for 'Recent' tab not being shown as selected if message icon is double tapped
  src/status_im/events.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/home/events.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/shell/bottom_tabs.cljs
  src/status_im2/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#15710 Add 'How to scan' syncing screens
  resources/images/ui2/desktop-how-to-pair-logged-in@2x.png
  resources/images/ui2/desktop-how-to-pair-logged-in@3x.png
  resources/images/ui2/desktop-how-to-pair-sign-in@2x.png
  resources/images/ui2/desktop-how-to-pair-sign-in@3x.png
  resources/images/ui2/mobile-how-to-pair-logged-in@2x.png
  resources/images/ui2/mobile-how-to-pair-logged-in@3x.png
  resources/images/ui2/mobile-how-to-pair-sign-in@2x.png
  resources/images/ui2/mobile-how-to-pair-sign-in@3x.png
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/syncing/how_to_pair/style.cljs
  src/status_im2/contexts/syncing/how_to_pair/view.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15880 fix: audio issues when sending app to background on Android
  src/quo2/components/record_audio/record_audio/view.cljs
  src/react_native/audio_toolkit.cljs
  src/status_im2/contexts/chat/messages/content/audio/component_spec.cljs
  src/status_im2/contexts/chat/messages/content/audio/view.cljs
Labels: Tested - OK, request-manual-qa

#15894 Fix: Suggested list of mentions does not appear initially when '@' is typed in the editing message composer
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15623 Update UI for Sign In by Syncing and Add Scan or Enter pairing Code to in app syncing flow
  src/status_im2/contexts/onboarding/sign_in/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/style.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code_page/style.cljs
  src/status_im2/contexts/syncing/scan_sync_code_page/view.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/contexts/syncing/utils.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#15903 ci: fix missing Alchemy and Infura env vars
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: android, security, infra

#15892 feat: new keycard component
  resources/images/ui2/keycard-chip-dark@2x.png
  resources/images/ui2/keycard-chip-dark@3x.png
  resources/images/ui2/keycard-chip-light@2x.png
  resources/images/ui2/keycard-chip-light@3x.png
  resources/images/ui2/keycard-logo@2x.png
  resources/images/ui2/keycard-logo@3x.png
  resources/images/ui2/keycard-watermark@2x.png
  resources/images/ui2/keycard-watermark@3x.png
  src/quo2/components/keycard/component_spec.cljs
  src/quo2/components/keycard/style.cljs
  src/quo2/components/keycard/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/resources.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/quo_preview/keycard/keycard.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/setup/i18n_test.cljs
  translations/en.json
Labels: external

#15913 Add Accessiblity for Image Container in Chat
  src/status_im2/contexts/chat/messages/content/album/view.cljs
Labels: bug, e2e test blocker

#15863 Design Feedbacks on "Create profile password" screen
  resources/images/icons2/16x16/info@2x.png
  resources/images/icons2/16x16/info@3x.png
  resources/images/icons2/20x20/hide@2x.png
  resources/images/icons2/20x20/hide@3x.png
  resources/images/icons2/20x20/reveal@2x.png
  resources/images/icons2/20x20/reveal@3x.png
  src/quo2/components/inputs/input/style.cljs
  src/status_im2/contexts/onboarding/create_password/style.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
  test/appium/views/sign_in_view.py
Labels: Tested - OK, onboarding, request-manual-qa, design-review

#15915 [15611] Lock orientation
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/options.cljs
Labels: Tested - OK, request-manual-qa

#15782 Add share tab in shell
  src/quo2/components/share/qr_code/view.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/share/events.cljs
  src/status_im2/contexts/share/style.cljs
  src/status_im2/contexts/share/view.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/screens.cljs
  src/utils/image_server.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15874 [#15779] Disable input after login
  src/status_im2/contexts/onboarding/events.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: Tested - OK, request-manual-qa

#15929 fix: composer opacity on Android when recording
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/composer/handlers.cljs
Labels: Tested - OK

#15907 Activity Center Empty Community Image
  src/quo2/components/tags/context_tag/view.cljs
  src/status_im/ui/screens/communities/icon.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification/common/view.cljs
  src/status_im2/contexts/activity_center/notification/community_kicked/view.cljs
  src/status_im2/contexts/activity_center/notification/community_request/view.cljs
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
Labels: bug, Tested - OK, request-manual-qa, Activity center

#15914 fix #15899 : failed to reset password
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15936 Make json-rpc/call effect more in line with re-frame standards
  doc/new-guidelines.md
  src/status_im2/common/json_rpc/events.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
Labels: tests, refactoring

#15891 New link previews (initial implementation)
  src/quo2/components/links/link_preview/component_spec.cljs
  src/quo2/components/links/link_preview/view.cljs
  src/quo2/components/links/url_preview/component_spec.cljs
  src/quo2/components/links/url_preview/view.cljs
  src/quo2/components/links/url_preview_list/view.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/data_store/activities_test.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/messages_test.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
  src/status_im2/contexts/chat/composer/constants.cljs
  src/status_im2/contexts/chat/composer/effects.cljs
  src/status_im2/contexts/chat/composer/handlers.cljs
  src/status_im2/contexts/chat/composer/link_preview/events.cljs
  src/status_im2/contexts/chat/composer/link_preview/events_test.cljs
  src/status_im2/contexts/chat/composer/link_preview/style.cljs
  src/status_im2/contexts/chat/composer/link_preview/view.cljs
  src/status_im2/contexts/chat/composer/mentions/view.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
  src/status_im2/contexts/chat/composer/utils.cljs
  src/status_im2/contexts/chat/composer/view.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/messages/content/link_preview/view.cljs
  src/status_im2/contexts/chat/messages/content/link_preview/view_test.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/quo_preview/links/link_preview.cljs
  src/status_im2/contexts/quo_preview/links/url_preview.cljs
  src/status_im2/contexts/quo_preview/links/url_preview_list.cljs
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/root.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa, url-preview

#15941 Fix: nickname modal iOS bottom space
  src/status_im2/contexts/contacts/drawers/nickname_drawer/style.cljs
Labels: Tested - OK, request-manual-qa

#15928 fix: permission tag component locked state
  resources/images/icons2/16x16/locked@2x.png
  resources/images/icons2/16x16/locked@3x.png
  resources/images/icons2/20x20/locked@2x.png
  resources/images/icons2/20x20/locked@3x.png
  src/quo2/components/tags/permission_tag.cljs
  src/status_im2/contexts/quo_preview/drawers/permission_drawers.cljs
Labels: Tested - OK

#15956 Update hooks lib
  package.json
  yarn.lock
Labels: package-upgrade

#15927 App locked screen - design review changes
  resources/images/icons2/16x16/unlocked@2x.png
  resources/images/icons2/16x16/unlocked@3x.png
  resources/images/icons2/20x20/unlocked@2x.png
  resources/images/icons2/20x20/unlocked@3x.png
  src/quo2/components/buttons/button.cljs
  src/quo2/components/inputs/input/view.cljs
  src/quo2/components/inputs/recovery_phrase/view.cljs
  src/quo2/components/inputs/search_input/view.cljs
  src/quo2/components/inputs/title_input/view.cljs
  src/quo2/theme.cljs
  src/status_im2/contexts/chat/composer/view.cljs
  src/status_im2/contexts/onboarding/profiles/style.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/contexts/quo_preview/preview.cljs
Labels: Tested - OK

#15964 [Fix] Accessibility for single image in chat
  src/status_im2/contexts/chat/messages/content/image/view.cljs
Labels: Tested - OK

#15860 home screen updates
  resources/images/icons2/20x20/activity-center@2x.png
  resources/images/icons2/20x20/activity-center@3x.png
  resources/images/icons2/24x24/browser@2x.png
  resources/images/icons2/24x24/browser@3x.png
  resources/images/icons2/24x24/messages@2x.png
  resources/images/icons2/24x24/messages@3x.png
  resources/images/icons2/24x24/wallet@2x.png
  resources/images/icons2/24x24/wallet@3x.png
  resources/images/ui2/discover@2x.png
  resources/images/ui2/discover@3x.png
  resources/images/ui2/invite-friends@2x.png
  resources/images/ui2/invite-friends@3x.png
  src/quo2/components/avatars/user_avatar/style.cljs
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/buttons/button.cljs
  src/quo2/components/community/banner/style.cljs
  src/quo2/components/community/banner/view.cljs
  src/quo2/components/community/discover_card.cljs
  src/quo2/components/tabs/segmented_tab.cljs
  src/quo2/components/tabs/tab/style.cljs
  src/quo2/core.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/common/plus_button/view.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/home/style.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/onboarding/welcome/view.cljs
  src/status_im2/contexts/quo_preview/community/discover_card.cljs
  src/status_im2/contexts/shell/view.cljs
  src/status_im2/subs/chat/chats.cljs
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/home_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15922 #15665 Settings list component
  resources/images/icons2/20x20/browser-context@2x.png
  resources/images/icons2/20x20/browser-context@3x.png
  resources/images/mock2/decentraland.png
  resources/images/mock2/decentraland@2x.png
  resources/images/mock2/decentraland@3x.png
  resources/images/mock2/rarible.png
  resources/images/mock2/rarible@2x.png
  resources/images/mock2/rarible@3x.png
  src/quo2/components/settings/settings_list/style.cljs
  src/quo2/components/settings/settings_list/view.cljs
  src/quo2/core.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/settings/settings_list.cljs
Labels: external

#15658 sync devices after sign in
  src/status_im/signals/core.cljs
  src/status_im2/common/syncing/style.cljs
  src/status_im2/common/syncing/view.cljs
  src/status_im2/contexts/onboarding/syncing/progress/style.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/onboarding/syncing/results/style.cljs
  src/status_im2/contexts/onboarding/syncing/results/view.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/style.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/view.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  src/status_im2/contexts/syncing/syncing_devices_list/style.cljs
  src/status_im2/contexts/syncing/syncing_devices_list/view.cljs
  src/status_im2/navigation/roots.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/pairing.cljs
  src/status_im2/subs/root.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15938 Fix UX issue while spamming the copy button on share shell tab.
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/share/events.cljs
  src/status_im2/contexts/share/view.cljs
Labels: Tested - OK, request-manual-qa

#15814 [#15756] Token gated communities
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  resources/images/icons2/20x20/checktoken@2x.png
  resources/images/icons2/20x20/checktoken@3x.png
  shadow-cljs.edn
  src/quo2/components/buttons/button.cljs
  src/quo2/components/community/style.cljs
  src/quo2/components/community/token_gating.cljs
  src/quo2/components/tags/context_tag/style.cljs
  src/quo2/components/tags/context_tag/view.cljs
  src/quo2/components/tags/token_tag.cljs
  src/quo2/core.cljs
  src/status_im/communities/core.cljs
  src/status_im/ui/screens/communities/requests_to_join.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im2/common/password_authentication/events.cljs
  src/status_im2/common/password_authentication/view.cljs
  src/status_im2/config.cljs
  src/status_im2/contexts/communities/actions/community_options/component_spec.cljs
  src/status_im2/contexts/communities/actions/community_options/view.cljs
  src/status_im2/contexts/communities/actions/token_gating/view.cljs
  src/status_im2/contexts/communities/overview/events.cljs
  src/status_im2/contexts/communities/overview/style.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/onboarding/events.cljs
  src/status_im2/contexts/quo_preview/community/token_gating.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/tags/token_tag.cljs
  src/status_im2/events.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/root.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15924 nix: use jsbundle derivation for iOS as well
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  index.js
  nix/DETAILS.md
  nix/mobile/android/default.nix
  nix/mobile/android/release.nix
  nix/mobile/default.nix
  nix/mobile/jsbundle/default.nix
  shadow-cljs.edn
Labels: ios, infra

#15971 e2e: gallery test + links preview
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/gallery_1.png
Labels: tests

#15968 [Fix] Keyboard Close on "Forgot Password" tap
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: bug, Tested - OK, request-manual-qa

#15974 [Fix] Sorting of Chat list items
  src/status_im2/contexts/chat/home/view.cljs
Labels: Tested - OK, request-manual-qa

#15966 Design fixes for profile options
  resources/images/icons2/20x20/delete@2x.png
  resources/images/icons2/20x20/delete@3x.png
  src/quo2/components/drawers/action_drawers/view.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#15984 Animate link previews entering/leaving the Composer
  src/status_im2/contexts/chat/composer/link_preview/view.cljs
  src/status_im2/contexts/chat/composer/view.cljs
Labels: url-preview

#15942 feat: add ident ring for login profile picture
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/subs/multiaccount.cljs
  src/status_im2/subs/onboarding.cljs
  src/status_im2/subs/onboarding_test.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
Labels: Tested - OK, request-manual-qa

#15990 fix: display name/nickname/ens which includes dash is not resolved in the chat when mentioned
  src/status_im/chat/models/mentions.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15985 fix profile picture on login screen
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/profile/profile_card/view.cljs
Labels: Tested - OK, request-manual-qa

#15989 Fix composer height overflow with extra content
  src/status_im2/contexts/chat/composer/effects.cljs
  src/status_im2/contexts/chat/composer/handlers.cljs
Labels: bug

#15993 new chat fixes and improvements, sheet modal screen improvements
  resources/images/ui2/no-contacts-dark.png
  resources/images/ui2/no-contacts-light.png
  src/quo2/components/buttons/button.cljs
  src/quo2/components/drawers/action_drawers/style.cljs
  src/quo2/components/drawers/action_drawers/view.cljs
  src/status_im/events.cljs
  src/status_im/ui/components/invite/events.cljs
  src/status_im/ui/components/invite/views.cljs
  src/status_im2/common/bottom_sheet_screen/style.cljs
  src/status_im2/common/bottom_sheet_screen/view.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/chat/new_chat/styles.cljs
  src/status_im2/contexts/chat/new_chat/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/options.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15986 fix: audio recording bugs while scroll in chat
  src/quo2/components/record_audio/record_audio/__tests__/record_audio_component_spec.cljs
  src/quo2/components/record_audio/record_audio/view.cljs
  src/status_im/chat/models/input.cljs
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/subs/root.cljs
Labels: bug, Tested - OK

#15987 Show number of unread messages
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
Labels: Tested - OK, request-manual-qa

#15959 ios: replace Diawi Fastlane plugin that disappeared
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.nix-cache
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  fastlane/Fastfile
  fastlane/Gemfile.lock
  fastlane/Pluginfile
  fastlane/gemset.nix
  scripts/diawi-upload.mjs
Labels: ios, infra

#15994 clean old onboarding and communities
  src/status_im/bottom_sheet/sheets.cljs
  src/status_im/chat/models/reactions.cljs
  src/status_im/chat/models/transport.cljs
  src/status_im/communities/core.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/communities/channel_details.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/communities/community_emoji_thumbnail_picker.cljs
  src/status_im/ui/screens/communities/create.cljs
  src/status_im/ui/screens/communities/create_category.cljs
  src/status_im/ui/screens/communities/create_channel.cljs
  src/status_im/ui/screens/communities/edit.cljs
  src/status_im/ui/screens/communities/edit_channel.cljs
  src/status_im/ui/screens/communities/icon.cljs
  src/status_im/ui/screens/communities/profile.cljs
  src/status_im/ui/screens/communities/reorder_categories.cljs
  src/status_im/ui/screens/communities/requests_to_join.cljs
  src/status_im/ui/screens/communities/select_category.cljs
  src/status_im/ui/screens/multiaccounts/key_storage/styles.cljs
  src/status_im/ui/screens/multiaccounts/key_storage/views.cljs
  src/status_im/ui/screens/multiaccounts/login/styles.cljs
  src/status_im/ui/screens/multiaccounts/login/views.cljs
  src/status_im/ui/screens/multiaccounts/recover/views.cljs
  src/status_im/ui/screens/multiaccounts/sheets.cljs
  src/status_im/ui/screens/multiaccounts/styles.cljs
  src/status_im/ui/screens/multiaccounts/views.cljs
  src/status_im/ui/screens/onboarding/keys/views.cljs
  src/status_im/ui/screens/onboarding/notifications/views.cljs
  src/status_im/ui/screens/onboarding/password/views.cljs
  src/status_im/ui/screens/onboarding/phrase/view.cljs
  src/status_im/ui/screens/onboarding/storage/views.cljs
  src/status_im/ui/screens/onboarding/styles.cljs
  src/status_im/ui/screens/onboarding/views.cljs
  src/status_im/ui/screens/onboarding/welcome/styles.cljs
  src/status_im/ui/screens/onboarding/welcome/views.cljs
  src/status_im/ui/screens/popover/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/messages/content/legacy_view.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/quo_preview/community/community_card_view.cljs
  src/status_im2/subs/chat/chats.cljs
Labels: Tested - OK, request-manual-qa

#16003 ios: drop fastlane-plugin-clean_testflight_testers
  fastlane/Fastfile
  fastlane/Gemfile
  fastlane/Gemfile.lock
  fastlane/Pluginfile
  fastlane/default.nix
  fastlane/gemset.nix
Labels: ios, tests, dependencies

#15996 refactor: lightbox screen
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/chat/lightbox/bottom_view.cljs
  src/status_im2/contexts/chat/lightbox/constants.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/lightbox/utils.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
Labels: refactoring

#16009 Bottom sheet background on Android changed to overcome issues with blur
  src/status_im2/common/bottom_sheet/styles.cljs
Labels: Tested - OK, request-manual-qa

#16017 fix pin image in community leads to error
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
Labels: Tested - OK, request-manual-qa

#16026 Add default customization color
  src/status_im2/subs/chat/chats.cljs
Labels: request-manual-qa

#15852 Setup syncing timer fix
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
Labels: Tested - Issues, request-manual-qa

#15978 [Fix] "View Profile" button behaviour on keyboard open in "Add a contact" modal
  src/status_im2/contexts/add_new_contact/style.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
Labels: bug, Tested - OK, request-manual-qa

#15822 Old wallet
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signing/gas.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/account/styles.cljs
  src/status_im/ui/screens/wallet/accounts/common.cljs
  src/status_im/ui/screens/wallet/accounts/styles.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im/ui/screens/wallet/collectibles/views.cljs
  src/status_im/ui/screens/wallet/send/sheets.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/utils/money.cljs
  src/status_im/utils/prices.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im/wallet/core.cljs
  src/status_im2/contexts/shell/home_stack.cljs
  src/status_im2/subs/wallet/signing.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
  status-go-version.json
Labels: request-manual-qa

#16014 [Fix] Nav bar overlap in "Syncing" screen
  src/status_im2/contexts/syncing/setup_syncing/style.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/navigation/options.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#16033 [Fix] Error on opening "How to scan" bottom sheet
  src/quo2/components/tags/context_tag/view.cljs
  src/status_im2/common/bottom_sheet_screen/style.cljs
  src/status_im2/common/bottom_sheet_screen/view.cljs
  src/status_im2/contexts/syncing/how_to_pair/view.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
Labels: Tested - OK, request-manual-qa

#16035 disable chat swipe back navigation in ios
  src/status_im2/navigation/screens.cljs
Labels: request-manual-qa

#16041 fix emoji pin in community
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
Labels: Tested - OK, request-manual-qa

#16030 fix: quo2 floating-shell-button click through
  src/quo2/components/buttons/dynamic_button.cljs
  src/quo2/components/navigation/floating_shell_button.cljs
  src/status_im2/contexts/chat/composer/utils.cljs
  src/status_im2/contexts/shell/view.cljs
Labels: Tested - OK, request-manual-qa

#16037 Align to latest accounts changes
  src/status_im/wallet/accounts/core.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16012 [Fix] QR scanner scanning QR when user moved to next screen
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
Labels: Tested - OK, pairing, request-manual-qa

#16042 Show a profile image on communities and contacts screen
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
Labels: Tested - OK, request-manual-qa

#16051 Fix: jumpy composer
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/composer/effects.cljs
  src/status_im2/contexts/chat/composer/gesture.cljs
  src/status_im2/contexts/chat/composer/handlers.cljs
  src/status_im2/contexts/chat/composer/images/view.cljs
  src/status_im2/contexts/chat/composer/link_preview/view.cljs
  src/status_im2/contexts/chat/composer/style.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
  src/status_im2/contexts/chat/composer/utils.cljs
  src/status_im2/contexts/chat/composer/view.cljs
Labels: Tested - OK, request-manual-qa, composer
