Repository status-im/status-mobile, pull requests merged in 2023-08, with the labels that each got.

#16816 fixed: getting stuck on the "Keys saved" randomly
  status-go-version.json
Labels: Tested - OK, request-manual-qa, followup required

#16793 Quo2 Wallet: network bridge
  resources/images/icons2/12x12/add-circle@2x.png
  resources/images/icons2/12x12/add-circle@3x.png
  resources/images/tokens/mainnet/ARB@2x.png
  resources/images/tokens/mainnet/ARB@3x.png
  resources/images/tokens/mainnet/ETH@2X.png
  resources/images/tokens/mainnet/OP@2x.png
  resources/images/tokens/mainnet/OP@3x.png
  src/quo2/components/wallet/network_bridge/component_spec.cljs
  src/quo2/components/wallet/network_bridge/style.cljs
  src/quo2/components/wallet/network_bridge/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/colors.cljs
  src/quo2/foundations/resources.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/network_bridge.cljs
Labels: E:Mobile Wallet Foundations MVP

#16789 Implement Wallet Graph component
  package.json
  src/mocks/js_dependencies.cljs
  src/quo2/components/graph/wallet_graph/component_spec.cljs
  src/quo2/components/graph/wallet_graph/style.cljs
  src/quo2/components/graph/wallet_graph/utils.cljs
  src/quo2/components/graph/wallet_graph/utils_test.cljs
  src/quo2/components/graph/wallet_graph/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/react_native/charts.cljs
  src/status_im2/contexts/quo_preview/graph/wallet_graph.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  test/jest/jest.config.js
  yarn.lock
Labels: feature, E:Mobile Wallet MVP, E:Mobile Wallet Foundations MVP

#16826 ci: fix use of release Infura key for E2E runs
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: tests, infra

#16801 Implement account_card and variants
  src/quo2/components/wallet/account_card/component_spec.cljs
  src/quo2/components/wallet/account_card/style.cljs
  src/quo2/components/wallet/account_card/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/account_card.cljs
Labels: followup required

#16723 Implement Quo2 Numbered-Keyboard / Keyboard Key component
  resources/images/icons2/32x32/derivation-path@2x.png
  resources/images/icons2/32x32/derivation-path@3x.png
  src/quo2/components/numbered_keyboard/keyboard_key/component_spec.cljs
  src/quo2/components/numbered_keyboard/keyboard_key/style.cljs
  src/quo2/components/numbered_keyboard/keyboard_key/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/numbered_keyboard/keyboard_key.cljs
Labels: followup required

#16522 ci: create e2e nightly run on ci.status.im
  ci/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-nightly-build-number
Labels: infra

#16842 Revert "Set initial block range for a newly created account"
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/profile/recover/events.cljs
Labels: Tested - OK

#16838 e2e: group chat unread messages
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_profile_m.py
  test/appium/tests/upgrade/test_upgrade.py
  test/appium/views/home_view.py
Labels: tests

#16847 e2e: added test for markdown support (702809)
  test/appium/tests/critical/test_public_chat_browsing.py
Labels: tests

#16806 Add method for fast creation of communities
  .env.e2e
  .env.jenkins
  .env.nightly
  src/status_im/communities/core.cljs
  src/status_im2/config.cljs
  src/status_im2/contexts/communities/actions/home_plus/view.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16819 Quo2: Token Input
  resources/images/tokens/mainnet/SNT@2x.png
  resources/images/tokens/mainnet/SNT@3x.png
  src/quo2/components/wallet/token_input/component_spec.cljs
  src/quo2/components/wallet/token_input/style.cljs
  src/quo2/components/wallet/token_input/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/common.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/token_input.cljs
Labels: E:Mobile Wallet Foundations MVP

#16799 chore: adjust counter to use customization-color internally
  src/quo2/components/banners/banner/view.cljs
  src/quo2/components/community/channel_actions.cljs
  src/quo2/components/community/community_list_view.cljs
  src/quo2/components/counter/counter.cljs
  src/quo2/components/counter/counter/component_spec.cljs
  src/quo2/components/counter/counter/style.cljs
  src/quo2/components/counter/counter/view.cljs
  src/quo2/components/list_items/channel.cljs
  src/quo2/components/list_items/community/view.cljs
  src/quo2/components/navigation/bottom_nav_tab/view.cljs
  src/quo2/components/notifications/info_count.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/style.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/home/contact_request/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/quo_preview/counter/counter.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
Labels: Tested - OK, request-manual-qa

#16832 Enable layout animations by default
  src/react_native/reanimated.cljs
  src/status_im2/core.cljs
Labels: Tested - OK, request-manual-qa

#16823 16709 chat home banner animation
  src/react_native/section_list.cljs
  src/status_im2/common/home/banner/style.cljs
  src/status_im2/common/home/banner/view.cljs
  src/status_im2/common/home/style.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/chat/home/style.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/home/style.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/view.cljs
Labels: Tested - OK, request-manual-qa

#16822 e2e: updated tests with new communitites creation flow
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_browser_profile.py
  test/appium/tests/medium/test_pairing_devices_sync_m.py
  test/appium/tests/medium/test_profile_m.py
  test/appium/views/home_view.py
Labels: tests

#16884 [Fix] Crash on onboarding due to nil value
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Bug MVP

#16855 add wallet overview
  resources/images/icons2/16x16/positive-right@2x.png
  resources/images/icons2/16x16/positive-right@3x.png
  src/quo2/components/wallet/wallet_overview/component_spec.cljs
  src/quo2/components/wallet/wallet_overview/style.cljs
  src/quo2/components/wallet/wallet_overview/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/wallet_overview.cljs
  translations/en.json
Labels: followup required

#16880 Quo2 Wallet: Token Value
  src/quo2/components/list_items/token_value/component_spec.cljs
  src/quo2/components/list_items/token_value/style.cljs
  src/quo2/components/list_items/token_value/view.cljs
  src/quo2/components/wallet/token_input/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/colors.cljs
  src/quo2/foundations/common.cljs
  src/status_im2/contexts/quo_preview/list_items/token_value.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: E:Mobile Wallet Foundations MVP, E:Mobile Wallet Main Page MVP

#16775 [#16254] Add new system messages in chat history when accepting a con…
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/drawers/permission_context/style.cljs
  src/quo2/components/drawers/permission_context/view.cljs
  src/quo2/components/messages/system_message.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/content/pin/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/contacts/events.cljs
  src/status_im2/contexts/quo_preview/messages/system_message.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
  src/status_im2/subs/shell.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#16409 nix: switch status-im config to env vars, cleanup
  Makefile
  android/app/build.gradle
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-nightly-build-number
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  nix/DETAILS.md
  nix/README.md
  nix/config.nix
  nix/lib/default.nix
  nix/lib/getConfig.nix
  nix/lib/getEnvWithDefault.nix
  nix/lib/sanitizeVersion.nix
  nix/mobile/android/release.nix
  nix/overlay.nix
  nix/pkgs.nix
  nix/scripts/shell.sh
  nix/status-go/default.nix
  nix/status-go/mobile/build.nix
  nix/status-go/mobile/enforceXCodeAvailable.nix
  nix/status-go/source.nix
  nix/tools/envParser.nix
  nix/tools/gradlePropParser.nix
  nix/tools/utils.nix
  scripts/build-android.sh
Labels: nix

#16829 Fetching featured communities
  src/quo2/components/community/community_card_view.cljs
  src/quo2/components/community/community_list_view.cljs
  src/quo2/components/community/style.cljs
  src/quo2/components/community/token_gating.cljs
  src/quo2/core.cljs
  src/status_im/signals/core.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/quo_preview/community/community_card_view.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16851 Implement Quo2 Numbered-Keyboard / Numbered Keyboard component #16606
  src/quo2/components/numbered_keyboard/keyboard_key/component_spec.cljs
  src/quo2/components/numbered_keyboard/keyboard_key/view.cljs
  src/quo2/components/numbered_keyboard/numbered_keyboard/style.cljs
  src/quo2/components/numbered_keyboard/numbered_keyboard/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/numbered_keyboard/numbered_keyboard.cljs
Labels: followup required

#16881 Quo2 Wallet: Summary Info
  src/quo2/components/wallet/summary_info/component_spec.cljs
  src/quo2/components/wallet/summary_info/style.cljs
  src/quo2/components/wallet/summary_info/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/resources.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/summary_info.cljs
Labels: E:Mobile Wallet Foundations MVP

#16879 fix: process backup messages when recovering account from seed phrase
  status-go-version.json
Labels: Tested - Issues, request-manual-qa

#16863 Add fallback letter on channel on the community card
  src/quo2/components/avatars/channel_avatar/view.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
Labels: Tested - OK, request-manual-qa

#16746 [#16437] fix sync qr code not recognized after trying again
  src/react_native/navigation.cljs
  src/status_im2/contexts/onboarding/sign_in/view.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/animation.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code_page/view.cljs
  src/status_im2/navigation/util.cljs
Labels: Tested - OK, request-manual-qa

#16432 show button background on scroll
  ios/Podfile.lock
  src/status_im2/contexts/onboarding/create_profile/style.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#16896 ci: cleanup e2e tests and builds from jenkins combined job
  ci/Jenkinsfile.combined
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-nightly-build-number
Labels: tests

#16915 chore: add basic flow for wallet development to begin
  src/quo2/components/navigation/bottom_nav_tab/view.cljs
  src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/view.cljs
  src/status_im2/contexts/shell/jump_to/state.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/collectible/view.cljs
  src/status_im2/contexts/wallet/create_account/view.cljs
  src/status_im2/contexts/wallet/home/view.cljs
  src/status_im2/contexts/wallet/saved_address/view.cljs
  src/status_im2/contexts/wallet/saved_addresses/view.cljs
  src/status_im2/contexts/wallet/send/view.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#16923 "Your name" input field is dispositioned to the bottom on Create profile screen (Android)
  src/quo2/components/inputs/profile_input/style.cljs
Labels: Tested - OK, request-manual-qa

#16901 Add docs specifically for quo2
  doc/images/figma-properties.png
  doc/images/quo-component.png
  doc/new-guidelines.md
  scripts/lint-re-frame-in-quo-components.sh
  src/quo2/README.md
Labels: docs

#16944 Align text left in lightbox
  src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs
Labels: Tested - OK, request-manual-qa

#16817 Refactor some quo2 components to use best practices
  src/quo2/components/avatars/group_avatar/style.cljs
  src/quo2/components/avatars/group_avatar/view.cljs
  src/quo2/components/banners/banner/component_spec.cljs
  src/quo2/components/banners/banner/view.cljs
  src/quo2/components/browser/browser_input/component_spec.cljs
  src/quo2/components/browser/browser_input/view.cljs
  src/quo2/components/buttons/dynamic_button.cljs
  src/quo2/components/buttons/dynamic_button/style.cljs
  src/quo2/components/buttons/dynamic_button/view.cljs
  src/quo2/components/counter/step/component_spec.cljs
  src/quo2/components/counter/step/view.cljs
  src/quo2/components/markdown/list/view.cljs
  src/quo2/components/navigation/floating_shell_button.cljs
  src/quo2/components/tabs/tabs/style.cljs
  src/quo2/components/tabs/tabs/view.cljs
  src/quo2/components/tags/context_tag/view.cljs
  src/quo2/core.cljs
  src/status_im/ui/screens/wallet/account/views.cljs
  src/status_im/ui/screens/wallet/accounts/views.cljs
  src/status_im2/contexts/quo_preview/avatars/group_avatar.cljs
  src/status_im2/contexts/quo_preview/buttons/dynamic_button.cljs
  src/status_im2/contexts/quo_preview/counter/step.cljs
Labels: Tested - OK, request-manual-qa

#16902 chore: add composer button to quo2 and use in app
  src/quo2/components/buttons/composer_button/component_spec.cljs
  src/quo2/components/buttons/composer_button/style.cljs
  src/quo2/components/buttons/composer_button/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/quo_preview/buttons/composer_button.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: Tested - OK, request-manual-qa

#16961 e2e: pulling geth log in teardown if setup is failed
  test/appium/tests/base_test_case.py
  test/appium/views/base_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#16938 revert identity ring colours
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16984 fix app crash during key generation
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16965 Wallet Empty Home UI
  resources/images/tokens/mainnet/DAI.png
  resources/images/tokens/mainnet/DAI@2x.png
  resources/images/tokens/mainnet/DAI@3x.png
  resources/images/tokens/mainnet/ETH-network@2x.png
  resources/images/tokens/mainnet/ETH-network@3x.png
  resources/images/tokens/mainnet/ETH-token@2x.png
  resources/images/tokens/mainnet/ETH-token@3x.png
  resources/images/tokens/mainnet/ETH.png
  resources/images/tokens/mainnet/ETH@3x.png
  src/quo2/components/graph/wallet_graph/view.cljs
  src/quo2/components/list_items/token_value/component_spec.cljs
  src/quo2/components/list_items/token_value/style.cljs
  src/quo2/components/list_items/token_value/view.cljs
  src/quo2/components/wallet/account_card/view.cljs
  src/quo2/components/wallet/wallet_overview/style.cljs
  src/quo2/components/wallet/wallet_overview/view.cljs
  src/quo2/foundations/common.cljs
  src/quo2/foundations/resources.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/quo_preview/list_items/token_value.cljs
  src/status_im2/contexts/quo_preview/wallet/wallet_overview.cljs
  src/status_im2/contexts/wallet/home/style.cljs
  src/status_im2/contexts/wallet/home/temp.cljs
  src/status_im2/contexts/wallet/home/view.cljs
  translations/en.json
Labels: E:Mobile Wallet Main Page MVP, followup required

#16969 Add preview and counters for CR system messages #16898
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/subs/shell.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16976 Pull images from status-go
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16893 Quo2 Wallet: Account list card
  src/quo2/components/list_items/account_list_card/component_spec.cljs
  src/quo2/components/list_items/account_list_card/style.cljs
  src/quo2/components/list_items/account_list_card/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/quo_preview/list_items/account_list_card.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: E:Mobile Wallet Foundations MVP

#16193 feat: render all avatars using media server
  .carve_ignore
  src/mocks/js_dependencies.cljs
  src/quo2/components/avatars/user_avatar/component_spec.cljs
  src/quo2/components/avatars/user_avatar/style.cljs
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/common/no_flicker_image.cljs
  src/quo2/components/inputs/profile_input/component_spec.cljs
  src/quo2/components/inputs/profile_input/view.cljs
  src/quo2/components/list_items/user_list.cljs
  src/quo2/components/profile/select_profile/view.cljs
  src/quo2/components/tags/context_tag/view.cljs
  src/react_native/fs.cljs
  src/status_im/contact/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/multiaccounts/update/core.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/contacts_list/views.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/utils/pixel_ratio.cljs
  src/status_im2/common/confirmation_drawer/view.cljs
  src/status_im2/common/font.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/common/toasts/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  src/status_im2/contexts/chat/composer/reply/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/messages/avatar/view.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/contacts/drawers/nickname_drawer/view.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/onboarding/identifiers/profile_card/style.cljs
  src/status_im2/contexts/onboarding/identifiers/profile_card/view.cljs
  src/status_im2/contexts/profile/profiles/view.cljs
  src/status_im2/contexts/profile/rpc.cljs
  src/status_im2/contexts/quo_preview/avatars/user_avatar.cljs
  src/status_im2/contexts/quo_preview/notifications/notification.cljs
  src/status_im2/contexts/shell/activity_center/events.cljs
  src/status_im2/contexts/shell/activity_center/notification/common/view.cljs
  src/status_im2/events.cljs
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/contact.cljs
  src/status_im2/subs/contact_test.cljs
  src/status_im2/subs/profile.cljs
  src/status_im2/subs/root.cljs
  src/status_im2/subs/shell.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#16999 Fix jump to button showing inside composer
  src/status_im2/contexts/chat/composer/sub_view.cljs
Labels: Tested - OK, request-manual-qa

#16996 Refactor Quo preview
  src/status_im2/contexts/quo_preview/colors/color_picker.cljs
  src/status_im2/contexts/quo_preview/dividers/divider_label.cljs
  src/status_im2/contexts/quo_preview/links/link_preview.cljs
  src/status_im2/contexts/quo_preview/links/url_preview.cljs
  src/status_im2/contexts/quo_preview/links/url_preview_list.cljs
  src/status_im2/contexts/quo_preview/list_items/community_list.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/preview.cljs
  src/status_im2/contexts/quo_preview/style.cljs
Labels: E:Mobile Design Components MVP

#17014 chore: update group-avatar component
  src/quo2/components/avatars/group_avatar/style.cljs
  src/quo2/components/avatars/group_avatar/view.cljs
  src/status_im2/contexts/quo_preview/avatars/group_avatar.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
  src/status_im2/contexts/shell/activity_center/notification/common/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/membership/view.cljs
Labels: E:Mobile Design Components MVP

#17020 e2e: starting to-dos
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/dbs/waku_backup/user.py
  test/appium/views/elements_templates/member3.png
  test/appium/views/home_view.py
Labels: tests

#17039 Revert "chore: update group-avatar component (#17014)"
  src/quo2/components/avatars/group_avatar/style.cljs
  src/quo2/components/avatars/group_avatar/view.cljs
  src/status_im2/contexts/quo_preview/avatars/group_avatar.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
  src/status_im2/contexts/shell/activity_center/notification/common/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/membership/view.cljs
Labels: Tested - OK, request-manual-qa

#17007 update empty state image illustrations to reflect the applied theme
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/view.cljs
Labels: Tested - OK, request-manual-qa

#16917 add members to open community
  src/status_im/communities/core.cljs
  src/status_im2/contexts/communities/actions/request_to_join/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/community_request/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#17047 e2e: updated test_group_chat_mute_chat to unmute by time
  test/appium/tests/critical/chats/test_group_chat.py
Labels: tests

#17053 Add design review to pipeline process doc
  doc/pipeline_process.md
Labels: docs

#17044 Background shown for [Continue] button on iOS when it shouldn't overlap the color picker
  src/status_im2/contexts/onboarding/create_profile/view.cljs
Labels: Tested - OK, request-manual-qa

#17000 [16827] Disable transparent video looping
  package.json
  src/status_im2/common/parallax/view.cljs
  src/status_im2/contexts/onboarding/generating_keys/view.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#16986 Add gradient background support in bottom sheet
  src/status_im2/common/bottom_sheet/style.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/quo_preview/gradient/gradient_cover.cljs
Labels: Tested - OK, feature, request-manual-qa, E:Mobile Wallet Foundations MVP

#17006 Quo2: Wallet Button and Wallet CTAs components
  src/quo2/components/buttons/wallet_button/component_spec.cljs
  src/quo2/components/buttons/wallet_button/style.cljs
  src/quo2/components/buttons/wallet_button/view.cljs
  src/quo2/components/buttons/wallet_ctas/component_spec.cljs
  src/quo2/components/buttons/wallet_ctas/style.cljs
  src/quo2/components/buttons/wallet_ctas/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/buttons/wallet_button.cljs
  src/status_im2/contexts/quo_preview/buttons/wallet_ctas.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  translations/en.json
Labels: E:Mobile Wallet Foundations MVP

#17019 Quo2 Wallet: Keypair component
  resources/images/icons2/16x16/keycard-card@2x.png
  resources/images/icons2/16x16/keycard-card@3x.png
  src/quo2/components/avatars/icon_avatar.cljs
  src/quo2/components/wallet/keypair/component_spec.cljs
  src/quo2/components/wallet/keypair/style.cljs
  src/quo2/components/wallet/keypair/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/keypair.cljs
  translations/en.json
Labels: E:Mobile Wallet Foundations MVP, followup required

#17054 e2e: fix for navigation issue
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/onboarding/test_onboarding_flows.py
  test/appium/tests/critical/test_pairing_devices_sync.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_browser_profile.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: tests

#17046 wallet overview: design review fixes
  src/quo2/components/wallet/wallet_overview/style.cljs
  src/quo2/components/wallet/wallet_overview/view.cljs
Labels: followup required

#17064 [16594] Make unread-indicator as last child of view
  src/status_im2/common/home/view.cljs
Labels: request-manual-qa

#17041 fix: group-avatar component usage
  src/quo2/components/avatars/group_avatar/style.cljs
  src/quo2/components/avatars/group_avatar/view.cljs
  src/status_im2/common/confirmation_drawer/view.cljs
  src/status_im2/contexts/chat/group_details/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/quo_preview/avatars/group_avatar.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
  src/status_im2/contexts/shell/activity_center/notification/common/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/membership/view.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Bug MVP

#17075 e2e: updated community tests 703086 and 702786
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/home_view.py
Labels: tests

#17083 Audio button does not disappear when changed to 'Send' button #17082
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/composer/view.cljs
Labels: Tested - OK, request-manual-qa

#17049 Quo2 Wallet: Network Link
  src/mocks/js_dependencies.cljs
  src/quo2/components/wallet/network_link/view.cljs
  src/quo2/core.cljs
  src/react_native/svg.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/network_link.cljs
Labels: E:Mobile Wallet Foundations MVP, followup required

#17040 nix: map android arch to status-go builds
  nix/mobile/android/default.nix
  nix/mobile/android/release.nix
  nix/shells.nix
  nix/status-go/mobile/default.nix
Labels: nix

#17033 [16866] Action Drawer design review
  src/quo2/components/drawers/action_drawers/style.cljs
  src/quo2/components/drawers/action_drawers/view.cljs
  src/status_im2/common/home/actions/view.cljs
Labels: followup required

#17090 e2e: nightly fixes 23.08
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#17050 [#16864] Design review: messages home
  src/quo2/components/messages/author/style.cljs
  src/quo2/components/messages/author/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/style.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/quo_preview/messages/author.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/home_view.py
Labels: Tested - OK, request-manual-qa, followup required

#17035 Refactor divider label component
  src/quo2/components/dividers/divider_label.cljs
  src/quo2/components/dividers/divider_label/component_spec.cljs
  src/quo2/components/dividers/divider_label/style.cljs
  src/quo2/components/dividers/divider_label/view.cljs
  src/quo2/components/dividers/divider_label_component_spec.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/common/contact_list/view.cljs
  src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/quo_preview/dividers/divider_label.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
Labels: request-manual-qa, followup required

#17085 fix Jump to button not responding in chat after app returns from background
  src/status_im2/contexts/chat/composer/style.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
Labels: Tested - OK, request-manual-qa

#17111 e2e: fixes 25.08
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/home_view.py
Labels: tests

#17001 e2e: appium upgrade
  test/appium/requirements.txt
  test/appium/tests/base_test_case.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/base_element.py
  test/appium/views/home_view.py
Labels: tests

#17051 Update "Preview list" component
  resources/images/dapps/1inch@2x.png
  resources/images/dapps/1inch@3x.png
  resources/images/dapps/Aave@2x.png
  resources/images/dapps/Aave@3x.png
  resources/images/dapps/CoinGecko@2x.png
  resources/images/dapps/CoinGecko@3x.png
  resources/images/dapps/Uniswap@2x.png
  resources/images/dapps/Uniswap@3x.png
  resources/images/dapps/Zapper@2x.png
  resources/images/dapps/Zapper@3x.png
  resources/images/dapps/Zerion@2x.png
  resources/images/dapps/Zerion@3x.png
  resources/images/mock2/coin-gecko@2x.png
  resources/images/mock2/coin-gecko@3x.png
  resources/images/networks/Arbitrum@2x.png
  resources/images/networks/Arbitrum@3x.png
  resources/images/networks/Ethereum@2x.png
  resources/images/networks/Ethereum@3x.png
  resources/images/networks/Gnosis@2x.png
  resources/images/networks/Gnosis@3x.png
  resources/images/networks/Hermez@2x.png
  resources/images/networks/Hermez@3x.png
  resources/images/networks/Optimism@2x.png
  resources/images/networks/Optimism@3x.png
  resources/images/networks/Polygon@2x.png
  resources/images/networks/Polygon@3x.png
  resources/images/networks/Scroll@2x.png
  resources/images/networks/Scroll@3x.png
  resources/images/networks/Taiko@2x.png
  resources/images/networks/Taiko@3x.png
  resources/images/networks/Unknown@2x.png
  resources/images/networks/Unknown@3x.png
  resources/images/networks/xDAI@2x.png
  resources/images/networks/xDAI@3x.png
  resources/images/networks/zkSync@2x.png
  resources/images/networks/zkSync@3x.png
  resources/images/tokens/mainnet/ARB@2x.png
  resources/images/tokens/mainnet/ARB@3x.png
  resources/images/tokens/mainnet/ETH-network@2x.png
  resources/images/tokens/mainnet/ETH-network@3x.png
  resources/images/tokens/mainnet/OP@2x.png
  resources/images/tokens/mainnet/OP@3x.png
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/dropdowns/network_dropdown/view.cljs
  src/quo2/components/list_items/preview_list.cljs
  src/quo2/components/list_items/preview_list/properties.cljs
  src/quo2/components/list_items/preview_list/view.cljs
  src/quo2/components/list_items/token_value/view.cljs
  src/quo2/components/wallet/network_amount/view.cljs
  src/quo2/components/wallet/network_bridge/view.cljs
  src/quo2/components/wallet/summary_info/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/resources.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/quo_preview/list_items/dapp.cljs
  src/status_im2/contexts/quo_preview/list_items/preview_lists.cljs
  src/status_im2/contexts/quo_preview/settings/reorder_item.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#17099 fix: composer cursor hidden
  src/status_im2/contexts/chat/composer/constants.cljs
  src/status_im2/contexts/chat/composer/gradients/style.cljs
Labels: Tested - OK, request-manual-qa

#16960 Implement Data Item component
  src/quo2/components/common/not_implemented/style.cljs
  src/quo2/components/common/not_implemented/view.cljs
  src/quo2/components/settings/data_item/component_spec.cljs
  src/quo2/components/settings/data_item/style.cljs
  src/quo2/components/settings/data_item/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/settings/data_item.cljs
  translations/en.json
Labels: request-manual-qa

#17031 [#16963] Refactor page nav and fix its API
  src/quo2/components/navigation/page_nav.cljs
  src/quo2/components/navigation/page_nav/style.cljs
  src/quo2/components/navigation/page_nav/view.cljs
  src/quo2/core.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/onboarding/common/navigation_bar/view.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/onboarding/welcome/view.cljs
  src/status_im2/contexts/quo_preview/browser/browser_input.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/navigation/page_nav.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/contexts/syncing/syncing_devices_list/view.cljs
Labels: Tested - OK, request-manual-qa

#16865 FF/animate-loading-skeleton
  src/quo2/components/loaders/skeleton/view.cljs
  src/quo2/components/loaders/skeleton_list/component_spec.cljs
  src/quo2/components/loaders/skeleton_list/constants.cljs
  src/quo2/components/loaders/skeleton_list/style.cljs
  src/quo2/components/loaders/skeleton_list/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/quo_preview/loaders/skeleton.cljs
  src/status_im2/contexts/quo_preview/loaders/skeleton_list.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: Tested - OK, request-manual-qa

#17105 fix: resolve activity centre design feedback
  src/quo2/components/notifications/activity_log/style.cljs
  src/quo2/components/notifications/activity_log/view.cljs
  src/quo2/components/selectors/filter/style.cljs
  src/quo2/components/tags/status_tags.cljs
Labels: Tested - OK, request-manual-qa

#17091 Fix contract call for communities
  src/status_im/communities/core.cljs
  src/status_im2/contexts/communities/actions/request_to_join/view.cljs
  src/status_im2/contexts/communities/discover/events.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17113 fix Chat input overlaps the last message on IPhone 14
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#17133 [#16550] fix: device type indicators in syncing screen
  src/quo2/components/settings/settings_list/style.cljs
  src/quo2/components/tags/status_tags.cljs
  src/status_im2/contexts/syncing/device/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#16985 [Fixes: #16219] Correctly handle removal event when out of order
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#16997 Design notes for pinned message
  resources/images/icons2/20x20/pin@2x.png
  resources/images/icons2/20x20/pin@3x.png
  src/quo2/components/avatars/icon_avatar.cljs
  src/quo2/components/messages/author/view.cljs
  src/quo2/components/messages/system_message.cljs
  src/status_im2/contexts/chat/composer/reply/style.cljs
  src/status_im2/contexts/chat/composer/reply/view.cljs
Labels: Tested - OK, request-manual-qa

#16998 Pinned messages drawer comments
  src/status_im2/contexts/chat/menus/pinned_messages/style.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/view.cljs
  src/status_im2/subs/communities.cljs
Labels: followup required

#17135 fix: Rounded edges of color sections of identity rings
  status-go-version.json
Labels: request-manual-qa, status-go

#17042 Remove 3 words alias
  src/status_im/integration_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17143 e2e: split community and activity center tests to reduce time
  test/appium/pytest.ini
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#17117 [16728] Allow message editing to save link previews
  src/status_im/chat/models/input.cljs
  src/status_im/data_store/messages.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17130 [IMPORTED] Tags-network(bounty)
  src/quo2/components/tabs/tab/view.cljs
  src/quo2/components/tags/network_tags/component_spec.cljs
  src/quo2/components/tags/network_tags/style.cljs
  src/quo2/components/tags/network_tags/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/tags/network_tags.cljs
Labels: external

#17106 Connected android devices abis
  Makefile
  scripts/adb_devices_abis.sh
Labels: infra

#17145 [#17140] fix: AC tabs are flickering while scrolling them
  src/quo2/components/tabs/tabs/view.cljs
Labels: Tested - OK, Tested - Issues, request-manual-qa

#17029 feat: implement interactive graphs
  package.json
  src/quo2/components/graph/interactive_graph/component_spec.cljs
  src/quo2/components/graph/interactive_graph/style.cljs
  src/quo2/components/graph/interactive_graph/view.cljs
  src/quo2/components/graph/utils.cljs
  src/quo2/components/graph/utils_test.cljs
  src/quo2/components/graph/wallet_graph/utils.cljs
  src/quo2/components/graph/wallet_graph/utils_test.cljs
  src/quo2/components/graph/wallet_graph/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/quo_preview/graph/interactive_graph.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  yarn.lock
Labels: feature
