Repository status-im/status-mobile, pull requests merged in 2023-09, with the labels that each got.

#17034 fix: support new design ident ring width
  src/quo2/components/avatars/user_avatar/style.cljs
  src/quo2/components/avatars/user_avatar/view.cljs
  src/quo2/components/tags/context_tag/view.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im2/common/pixel_ratio.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17146 fix: use custom color for send button
  src/status_im2/contexts/chat/composer/actions/view.cljs
Labels: Tested - OK, request-manual-qa

#17159 Fix: missing community logo in Activity Center
  src/react_native/core.cljs
Labels: Tested - OK, request-manual-qa

#17164 fix: remove hole view code with error
  src/quo2/components/navigation/top_nav/view.cljs
Labels: Tested - OK, request-manual-qa

#17158 Don't display "Add Unknown as contact to send a Message" if chat is not loaded
  src/status_im/chat/models/loading.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#17167 Docs update: required e2e
  doc/merging-pr-process.md
  doc/pipeline_process.md
Labels: docs

#17141 Wallet activity component
  resources/images/icons2/12x12/diamond@2x.png
  resources/images/icons2/12x12/diamond@3x.png
  src/quo2/components/wallet/wallet_activity/component_spec.cljs
  src/quo2/components/wallet/wallet_activity/style.cljs
  src/quo2/components/wallet/wallet_activity/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui/screens/wallet/send/views.cljs
  src/status_im/ui/screens/wallet/transactions/views.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/wallet_activity.cljs
  src/status_im2/subs/wallet/transactions.cljs
  translations/en.json
Labels: followup required

#17150 e2e: fixes navigation, long press and so on
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/discovery_general_channel.png
  test/appium/views/home_view.py
Labels: tests

#17070 Refactor quo channel component
  src/quo2/components/counter/counter/style.cljs
  src/quo2/components/list_items/channel.cljs
  src/quo2/components/list_items/channel/component_spec.cljs
  src/quo2/components/list_items/channel/style.cljs
  src/quo2/components/list_items/channel/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/quo_preview/list_items/channel.cljs
Labels: request-manual-qa

#17172 e2e: updated community channel element
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/home_view.py
Labels: tests

#17180 Improve `make show-ios-devices`
  Makefile
Labels: E:Tech Debt, E:Mobile Developer XP, nix

#17165 Onboarding screens
  src/quo2/components/text_combinations/style.cljs
  src/status_im2/common/parallax/view.cljs
  src/status_im2/contexts/onboarding/common/overlay/events.cljs
  src/status_im2/contexts/onboarding/common/overlay/view.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/intro/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/onboarding/sign_in/view.cljs
  src/status_im2/contexts/profile/profiles/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/navigation/util.cljs
Labels: Tested - OK, request-manual-qa

#17178 [#16859] fix: community channel design review
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
Labels: followup required

#17149 feat: add customization color to wallet graph
  src/quo2/components/graph/wallet_graph/view.cljs
  src/status_im2/contexts/quo_preview/graph/wallet_graph.cljs
Labels: feature

#17166 Fix for Android error `route ip+net: netlinkrib: permission denied`
  src/status_im/utils/universal_links/core.cljs
Labels: Tested - OK, request-manual-qa

#17201 e2e: updated join communities flow
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/chat_view.py
Labels: tests

#17197 e2e: split 1-1 chat test group
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
Labels: tests

#17198 e2e: removed deprecated metods usage
  test/appium/support/appium_container.py
  test/appium/tests/__init__.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/onboarding/test_onboarding_flows.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/critical/wallet_and_tx/test_send_tx_dapp_keycard.py
  test/appium/tests/critical/wallet_and_tx/test_wallet.py
  test/appium/tests/medium/test_browser_profile.py
  test/appium/tests/medium/test_chats_m.py
  test/appium/tests/medium/test_permissions_scan_qr.py
  test/appium/tests/medium/test_profile_m.py
  test/appium/tests/medium/test_single_device.py
  test/appium/tests/medium/test_wallet_keycard_m.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/dapps_view.py
  test/appium/views/home_view.py
  test/appium/views/keycard_view.py
  test/appium/views/profile_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#17174 Don't parse unused identicon in android pn
  Makefile
  babel.config.js
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotification.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationActions.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
  modules/react-native-status/android/src/test/java/android/util/Log.java
  modules/react-native-status/android/src/test/java/im/status/ethereum/pushnotifications/PushNotificationHelperTest.java
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  package.json
  yarn.lock
Labels: Tested - OK

#17205 e2e: fixes 6.09
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_chats_m.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#17078 Handle long names in system messages
  src/quo2/components/messages/system_message.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
Labels: Tested - OK, followup required

#17210 Profile input field position fix - Android
  src/quo2/components/inputs/profile_input/component_spec.cljs
  src/quo2/components/inputs/profile_input/style.cljs
  src/quo2/components/inputs/profile_input/view.cljs
  src/status_im2/contexts/quo_preview/inputs/profile_input.cljs
Labels: Tested - OK, request-manual-qa

#17170 Top bar stability & animation improvements
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
  src/status_im2/contexts/chat/composer/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/style.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#17215 Community logo and title are not aligned on the channels screen #17214
  src/quo2/components/text_combinations/style.cljs
  src/quo2/components/text_combinations/view.cljs
  src/status_im2/common/scroll_page/style.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/generating_keys/view.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/onboarding/syncing/results/view.cljs
  src/status_im2/contexts/onboarding/welcome/view.cljs
Labels: Tested - OK, request-manual-qa

#17171 chore: add transparent outline to notification in top-nav component
  src/quo2/components/counter/counter/style.cljs
  src/quo2/components/list_items/channel/style.cljs
  src/quo2/components/list_items/channel/view.cljs
  src/quo2/components/navigation/top_nav/view.cljs
  src/status_im2/contexts/quo_preview/navigation/top_nav.cljs
Labels: Tested - OK, request-manual-qa

#17169 Follow up replacing old skeleton loader with the latest version
  src/quo2/components/loaders/skeleton.cljs
  src/quo2/core.cljs
  src/status_im/ui/screens/chat/message/gap.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK

#17110 fix: user-avatar indicator size and position
  src/quo2/components/avatars/user_avatar/style.cljs
  src/quo2/components/avatars/user_avatar/view.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17108 fix: icon size in system message add new :size/s-24 icon-avatar
  src/quo2/components/avatars/icon_avatar.cljs
  src/quo2/components/messages/system_message.cljs
  src/quo2/components/wallet/keypair/view.cljs
  src/status_im2/contexts/quo_preview/avatars/icon_avatar.cljs
Labels: Tested - OK, request-manual-qa

#17209 Title input component - edit icon
  src/quo2/components/inputs/profile_input/view.cljs
  src/quo2/components/inputs/title_input/component_spec.cljs
  src/quo2/components/inputs/title_input/style.cljs
  src/quo2/components/inputs/title_input/view.cljs
  src/quo2/core.cljs
Labels: Tested - OK, request-manual-qa

#17238 Fix: composer is separated from the footer
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, E:Mobile React Native, request-manual-qa

#17226 fix: Sync is hanging in "syncing devices" stage
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#17196 Implement "Drawer top" component
  src/quo2/components/drawers/drawer_top/component_spec.cljs
  src/quo2/components/drawers/drawer_top/style.cljs
  src/quo2/components/drawers/drawer_top/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/quo_preview/drawers/drawer_top.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: request-manual-qa

#17163 Transaction summary component
  src/quo2/components/tags/context_tag/view.cljs
  src/quo2/components/wallet/transaction_summary/component_spec.cljs
  src/quo2/components/wallet/transaction_summary/style.cljs
  src/quo2/components/wallet/transaction_summary/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/transaction_summary.cljs
  translations/en.json
Labels: followup required

#17260 e2e: fixes 12.09
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/elements_templates/member3.png
  test/appium/views/home_view.py
Labels: tests

#17259 fix unable to reset pwd on ios
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#17191 feat: implement address input
  src/quo2/components/inputs/address_input/component_spec.cljs
  src/quo2/components/inputs/address_input/style.cljs
  src/quo2/components/inputs/address_input/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/quo_preview/inputs/address_input.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/test_helpers/component.cljs
  translations/en.json
Labels: feature

#17195 Implement Emoji Picker
  resources/data/emojis/en.json
  resources/images/icons2/20x20/activity@2x.png
  resources/images/icons2/20x20/activity@3x.png
  resources/images/icons2/20x20/faces@2x.png
  resources/images/icons2/20x20/faces@3x.png
  resources/images/icons2/20x20/flags@2x.png
  resources/images/icons2/20x20/flags@3x.png
  resources/images/icons2/20x20/food@2x.png
  resources/images/icons2/20x20/food@3x.png
  resources/images/icons2/20x20/nature@2x.png
  resources/images/icons2/20x20/nature@3x.png
  resources/images/icons2/20x20/objects@2x.png
  resources/images/icons2/20x20/objects@3x.png
  resources/images/icons2/20x20/symbols@2x.png
  resources/images/icons2/20x20/symbols@3x.png
  resources/images/icons2/20x20/travel@2x.png
  resources/images/icons2/20x20/travel@3x.png
  src/mocks/js_dependencies.cljs
  src/quo2/components/dividers/divider_label/style.cljs
  src/quo2/components/profile/showcase_nav/style.cljs
  src/quo2/components/profile/showcase_nav/view.cljs
  src/react_native/flat_list.cljs
  src/status_im2/contexts/emoji_picker/constants.cljs
  src/status_im2/contexts/emoji_picker/data.cljs
  src/status_im2/contexts/emoji_picker/events.cljs
  src/status_im2/contexts/emoji_picker/style.cljs
  src/status_im2/contexts/emoji_picker/utils.cljs
  src/status_im2/contexts/emoji_picker/utils_test.cljs
  src/status_im2/contexts/emoji_picker/view.cljs
  src/status_im2/contexts/quo_preview/avatars/account_avatar.cljs
  src/status_im2/contexts/wallet/create_account/view.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/screens.cljs
  src/utils/debounce.cljs
  translations/en.json
Labels: feature

#17224 Quo2: fix reaction styles
  src/quo2/components/reactions/reaction.cljs
  src/quo2/components/reactions/style.cljs
  src/status_im2/contexts/quo_preview/reactions/react.cljs
Labels: Tested - OK, request-manual-qa, followup required

#17291 Community fetching performance
  src/status_im/signals/core.cljs
  src/status_im2/contexts/communities/discover/events.cljs
  src/status_im2/contexts/communities/discover/events_test.cljs
Labels: Tested - OK, request-manual-qa

#17262 [#17218] fix: android channel name ellipsis completely
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#16257 Address design feedback on Profile share tab Screen
  src/quo2/components/tabs/segmented_tab.cljs
  src/status_im2/contexts/shell/share/style.cljs
  src/status_im2/contexts/shell/share/view.cljs
  src/utils/address.cljs
  src/utils/address_test.cljs
  src/utils/image_server.cljs
Labels: Tested - OK, request-manual-qa

#17127 use new API for ens name registration
  .env
  src/status_im/ens/core.cljs
  src/status_im/ethereum/ens.cljs
  src/status_im/ethereum/transactions/core.cljs
  src/status_im/node/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/ens/views.cljs
  src/status_im/wallet/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/subs/ens.cljs
  status-go-version.json
Labels: Tested - Issues, request-manual-qa, status-go

#17248 feat: wallet select address screen UI in empty state
  src/quo2/components/dividers/divider_line/style.cljs
  src/quo2/components/dividers/divider_line/view.cljs
  src/quo2/components/inputs/address_input/view.cljs
  src/quo2/components/navigation/page_nav/view.cljs
  src/quo2/components/tabs/tabs/view.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/send/select_address/style.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  src/status_im2/contexts/wallet/send/view.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: feature

#17269 fix: intro screen carousel
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/common/carousel/style.cljs
Labels: Tested - OK, request-manual-qa

#17293 fix: carousel text overflow
  src/status_im2/contexts/onboarding/common/carousel/style.cljs
Labels: Tested - OK, request-manual-qa, followup required

#17297 Update Cython / PyYAML
  test/appium/requirements.txt
Labels: tests

#17306 process backedup(profile/settings) signal
  src/status_im/signals/core.cljs
  src/status_im2/contexts/profile/events.cljs
Labels: Tested - OK, request-manual-qa

#17329 [#17309] fix: wrong cursor position in a pre-filled composer
  src/status_im2/contexts/chat/composer/effects.cljs
Labels: Tested - OK, request-manual-qa

#17199 chore: updating theming in quo2 components and chat
  src/quo2/components/animated_header_flatlist/style.cljs
  src/quo2/components/animated_header_flatlist/view.cljs
  src/quo2/components/header.cljs
  src/quo2/components/loaders/skeleton.cljs
  src/quo2/components/loaders/skeleton_list/view.cljs
  src/quo2/components/settings/privacy_option/style.cljs
  src/quo2/components/settings/privacy_option/view.cljs
  src/quo2/components/wallet/keypair/view.cljs
  src/quo2/components/wallet/network_bridge/style.cljs
  src/quo2/components/wallet/network_bridge/view.cljs
  src/quo2/core.cljs
  src/status_im/ui/components/search_input/view.cljs
  src/status_im2/contexts/chat/composer/style.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
  src/status_im2/contexts/chat/composer/view.cljs
  src/status_im2/contexts/chat/home/contact_request/style.cljs
  src/status_im2/contexts/chat/home/contact_request/view.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/shell/jump_to/components/floating_screens/style.cljs
  src/status_im2/contexts/shell/jump_to/components/floating_screens/view.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/style.cljs
  src/status_im2/contexts/shell/jump_to/components/home_stack/view.cljs
Labels: Tested - OK, request-manual-qa

#17339 adjust colors resolver to handle communities color
  src/quo2/foundations/colors.cljs
  src/quo2/foundations/colors_test.cljs
  src/status_im2/contexts/shell/jump_to/utils.cljs
Labels: Tested - OK, request-manual-qa

#17342 Prevent Logged In Account Local Pairing / Syncing With Another Account
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#17363 fix unread badges behavior on Jump-to screen
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/style.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#17365 remove messages screen global states
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#17346 Fix/identifier rings are displayed on avatars for users with a set ENS
  src/quo2/components/avatars/user_avatar/view.cljs
  src/status_im2/subs/profile.cljs
Labels: Tested - OK, request-manual-qa

#17340 [#17300] fix: syncing device indicator color and some alignment
  src/quo2/components/settings/settings_item/style.cljs
  src/quo2/components/settings/settings_item/view.cljs
  src/status_im2/contexts/syncing/device/style.cljs
  src/status_im2/contexts/syncing/device/view.cljs
Labels: Tested - OK, request-manual-qa

#17366 [#17288] refactor: migrate previews to new api
  src/quo2/components/list_items/token_value/view.cljs
  src/quo2/components/navigation/bottom_nav_tab/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/browser/browser_input.cljs
  src/status_im2/contexts/quo_preview/list_items/token_value.cljs
  src/status_im2/contexts/quo_preview/list_items/user_list.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/messages/gap.cljs
  src/status_im2/contexts/quo_preview/messages/system_message.cljs
  src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs
  src/status_im2/contexts/quo_preview/navigation/floating_shell_button.cljs
  src/status_im2/contexts/quo_preview/navigation/page_nav.cljs
  src/status_im2/contexts/quo_preview/navigation/top_nav.cljs
  src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs
Labels: request-manual-qa

#17279 chore: add docs with size
  src/quo2/README.md
  src/quo2/components/avatars/group_avatar/view.cljs
  src/quo2/components/avatars/icon_avatar.cljs
  src/quo2/components/dropdowns/network_dropdown/view.cljs
  src/quo2/components/list_items/preview_list/properties.cljs
  src/quo2/components/list_items/preview_list/view.cljs
  src/quo2/components/messages/system_message.cljs
  src/quo2/components/settings/data_item/view.cljs
  src/quo2/components/tags/context_tag/view.cljs
  src/quo2/components/tags/network_tags/component_spec.cljs
  src/quo2/components/tags/network_tags/view.cljs
  src/quo2/components/tags/number_tag/component_spec.cljs
  src/quo2/components/tags/number_tag/style.cljs
  src/quo2/components/tags/number_tag/view.cljs
  src/quo2/components/wallet/keypair/view.cljs
  src/status_im2/common/confirmation_drawer/view.cljs
  src/status_im2/contexts/chat/group_details/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/quo_preview/avatars/group_avatar.cljs
  src/status_im2/contexts/quo_preview/avatars/icon_avatar.cljs
  src/status_im2/contexts/quo_preview/list_items/preview_lists.cljs
  src/status_im2/contexts/quo_preview/tags/number_tag.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
Labels: Tested - OK, request-manual-qa

#17417 fix group card remains in shell after leaving the group
  src/status_im/group_chats/core.cljs
Labels: Tested - OK, request-manual-qa

#17219 Quo2: section label
  src/quo2/components/settings/section_label/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/settings/section_label.cljs
Labels: followup required

#17405 Quo2: Color picker
  src/quo2/components/colors/color/style.cljs
  src/quo2/components/colors/color/view.cljs
  src/quo2/components/colors/color_picker/component_spec.cljs
  src/quo2/components/colors/color_picker/style.cljs
  src/quo2/components/colors/color_picker/view.cljs
  src/quo2/core.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/quo_preview/colors/color.cljs
  src/status_im2/contexts/quo_preview/colors/color_picker.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/preview.cljs
  src/status_im2/contexts/quo_preview/wallet/account_overview.cljs
  src/status_im2/contexts/wallet/create_account/view.cljs
Labels: request-manual-qa, followup required

#16916 Standardized in-app authentication
  src/quo2/components/buttons/slide_button/animations.cljs
  src/quo2/components/buttons/slide_button/component_spec.cljs
  src/quo2/components/buttons/slide_button/style.cljs
  src/quo2/components/buttons/slide_button/utils.cljs
  src/quo2/components/buttons/slide_button/view.cljs
  src/react_native/touch_id.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/common/standard_authentication/enter_password/style.cljs
  src/status_im2/common/standard_authentication/enter_password/view.cljs
  src/status_im2/common/standard_authentication/forgot_password_doc/style.cljs
  src/status_im2/common/standard_authentication/forgot_password_doc/view.cljs
  src/status_im2/common/standard_authentication/password_input/style.cljs
  src/status_im2/common/standard_authentication/password_input/view.cljs
  src/status_im2/common/standard_authentication/standard_auth/view.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/profile/profiles/style.cljs
  src/status_im2/contexts/profile/profiles/view.cljs
  src/status_im2/contexts/quo_preview/buttons/slide_button.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/contexts/syncing/setup_syncing/style.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/contexts/syncing/sheets/enter_password/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#17398 feat: implement saved address list item component
  src/quo2/components/list_items/saved_address/component_spec.cljs
  src/quo2/components/list_items/saved_address/style.cljs
  src/quo2/components/list_items/saved_address/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/list_items/saved_address.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: feature

#17303 feat: implement account list item component
  src/quo2/components/list_items/account/component_spec.cljs
  src/quo2/components/list_items/account/style.cljs
  src/quo2/components/list_items/account/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/list_items/account.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: feature

#17404 Remove old quo code from status_im2 namespace
  Makefile
  scripts/lint-old-quo-usage.sh
  src/status_im2/common/qr_code_viewer/style.cljs
  src/status_im2/contexts/chat/messages/content/text/style.cljs
  src/status_im2/contexts/quo_preview/community/community_card_view.cljs
  src/status_im2/contexts/quo_preview/community/data.cljs
  src/status_im2/contexts/quo_preview/inputs/profile_input.cljs
  src/status_im2/contexts/quo_preview/tags/tag.cljs
Labels: Tested - OK

#17454 fix bottom tabs unread badge for group chats
  src/status_im2/subs/shell.cljs
  src/status_im2/subs/shell_test.cljs
Labels: Tested - OK, request-manual-qa

#16802 Implement switcher group messaging card
  ios/Podfile.lock
  src/quo2/components/avatars/group_avatar/view.cljs
  src/quo2/components/counter/counter/style.cljs
  src/quo2/components/switchers/base_card/component_spec.cljs
  src/quo2/components/switchers/base_card/style.cljs
  src/quo2/components/switchers/base_card/view.cljs
  src/quo2/components/switchers/card_content/style.cljs
  src/quo2/components/switchers/card_content/view.cljs
  src/quo2/components/switchers/card_main_info/style.cljs
  src/quo2/components/switchers/card_main_info/view.cljs
  src/quo2/components/switchers/group_messaging_card/component_spec.cljs
  src/quo2/components/switchers/group_messaging_card/style.cljs
  src/quo2/components/switchers/group_messaging_card/view.cljs
  src/quo2/components/switchers/utils.cljs
  src/quo2/components/tags/context_tag/style.cljs
  src/quo2/components/tags/context_tag/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/switcher/group_messaging_card.cljs
  translations/en.json
Labels: followup required
