Repository status-im/status-mobile, pull requests merged in 2023-12, with the labels that each got.

#18042 e2e: updated data for waku backup test
  test/appium/views/dbs/waku_backup/user.py
Labels: tests

#17868 add ability to add watch-only account
  src/quo/components/avatars/account_avatar/view.cljs
  src/quo/components/avatars/channel_avatar/view.cljs
  src/quo/components/avatars/wallet_user_avatar/view.cljs
  src/quo/components/wallet/account_overview/view.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/add_address_to_watch/confirm_address/component_spec.cljs
  src/status_im2/contexts/wallet/add_address_to_watch/confirm_address/view.cljs
  src/status_im2/contexts/wallet/add_address_to_watch/style.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/core_spec.cljs
  src/status_im2/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#17939 [#17923] text combinations - standard title component
  src/quo/components/tags/base_tag.cljs
  src/quo/components/tags/tag.cljs
  src/quo/components/text_combinations/standard_title/component_spec.cljs
  src/quo/components/text_combinations/standard_title/style.cljs
  src/quo/components/text_combinations/standard_title/view.cljs
  src/quo/core.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/text_combinations/standard_title.cljs
Labels: Tested - OK, request-manual-qa

#18029 fix: Cannot mark as read messages in communities
  src/status_im/chat/models/loading.cljs
Labels: Tested - OK, request-manual-qa, status-go

#17989 fix: change system time backward break image server
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#18003 Implement Wallet - Account Switcher
  src/quo/components/ios/drawer_bar/style.cljs
  src/quo/components/ios/drawer_bar/view.cljs
  src/quo/components/list_items/account/component_spec.cljs
  src/quo/components/list_items/account/style.cljs
  src/quo/components/list_items/account/view.cljs
  src/quo/components/wallet/account_origin/view.cljs
  src/quo/core.cljs
  src/status_im2/common/bottom_sheet/style.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/quo_preview/ios/drawer_bar.cljs
  src/status_im2/contexts/quo_preview/list_items/account.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
  src/status_im2/contexts/wallet/common/account_switcher/view.cljs
  src/status_im2/contexts/wallet/common/sheets/account_options/style.cljs
  src/status_im2/contexts/wallet/common/sheets/account_options/view.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18056 update deps and fix compile warnings
  package.json
  shadow-cljs.edn
  yarn.lock
Labels: E:Mobile Developer Experience 2023

#17767 update scan qr code page
  src/status_im2/common/scan_qr_code/style.cljs
  src/status_im2/common/scan_qr_code/view.cljs
  src/status_im2/contexts/add_new_contact/scan/scan_profile_qr_page.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#17821 Wallet: account real data
  src/status_im2/constants.cljs
  src/status_im2/contexts/wallet/account/tabs/view.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Wallet Accounts Page MVP, test cases are required

#18061 Style fixes for pinned messages
  src/status_im2/contexts/chat/menus/pinned_messages/style.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#18079 e2e: skipped checks with bugs
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
Labels: tests

#18049 Improve test failure readability
  .clj-kondo/config.edn
  doc/new-guidelines.md
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/status_im2/contexts/add_new_contact/events_test.cljs
  src/status_im2/contexts/chat/composer/link_preview/events_test.cljs
  src/status_im2/contexts/communities/discover/events_test.cljs
  src/status_im2/contexts/communities/overview/events_test.cljs
  src/status_im2/contexts/shell/activity_center/events_test.cljs
  src/status_im2/contexts/wallet/events_test.cljs
Labels: tests, E:Mobile Developer XP

#18001 chore: group ens names with chain-id
  src/status_im/ens/core.cljs
  src/status_im/subs/ens.cljs
  src/status_im2/subs/profile.cljs
Labels: Tested - OK, request-manual-qa

#18068 fix: use custom color for confirm select
  src/status_im2/contexts/chat/photo_selector/view.cljs
Labels: Tested - OK, E:Design Feedback 1.25

#17933 Implement transaction progress component
  resources/images/icons2/16x16/diamond@2x.png
  resources/images/icons2/16x16/diamond@3x.png
  src/quo/components/wallet/confirmation_progress/component_spec.cljs
  src/quo/components/wallet/confirmation_progress/style.cljs
  src/quo/components/wallet/confirmation_progress/view.cljs
  src/quo/components/wallet/progress_bar/component_spec.cljs
  src/quo/components/wallet/progress_bar/style.cljs
  src/quo/components/wallet/progress_bar/view.cljs
  src/quo/components/wallet/transaction_progress/component_spec.cljs
  src/quo/components/wallet/transaction_progress/style.cljs
  src/quo/components/wallet/transaction_progress/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/wallet/confirmation_progress.cljs
  src/status_im2/contexts/quo_preview/wallet/progress_bar.cljs
  src/status_im2/contexts/quo_preview/wallet/transaction_progress.cljs
  translations/en.json
Labels: request-manual-qa

#18082 Feature/display Community Rules on Request to Join
  src/status_im/communities/core.cljs
  src/status_im2/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im2/contexts/communities/actions/community_rules/style.cljs
  src/status_im2/contexts/communities/actions/community_rules/view.cljs
  src/status_im2/subs/communities.cljs
Labels: feature, E:Mobile Communities MVP, E:Mobile Release 1.27

#18091 Add missing clj-kondo linter for library nubank/matcher-combinators
  .clj-kondo/config.edn
  .clj-kondo/nubank/matcher-combinators/config.edn
Labels: E:Mobile Linting

#18077 Communities - Show modal title and community context tag
  src/status_im2/contexts/communities/actions/accounts_selection/style.cljs
  src/status_im2/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  translations/en.json
Labels: E:Mobile Communities MVP, E:Mobile Release 1.27

#18093 e2e: added test for edit/delete message when offline
  test/appium/tests/critical/chats/test_public_chat_browsing.py
Labels: tests

#17812 feat: transaction confirmation page ui
  src/quo/components/wallet/summary_info/style.cljs
  src/status_im2/contexts/wallet/send/transaction_confirmation/style.cljs
  src/status_im2/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: feature, request-manual-qa, followup required

#18000 Wallet: ENS
  src/quo/components/inputs/address_input/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/contexts/wallet/send/select_address/style.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  src/status_im2/contexts/wallet/send/select_asset/view.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Wallet Send Page MVP

#18045 Wallet: generate new keypair UI
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/create_account/backup_recovery_phrase/style.cljs
  src/status_im2/contexts/wallet/create_account/backup_recovery_phrase/view.cljs
  src/status_im2/contexts/wallet/create_account/select_keypair/view.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: E:Mobile Wallet MVP, followup required

#18108 Upgrade clang and patch Glog for fixing iOS builds on MacOS Sonoma, Xcode 15
  nix/deps/nodejs-patched/default.nix
  nix/overlay.nix
Labels: ios, nix, E:Mobile Developer Experience 2023

#17992 feat: enable biometrics for standard-auth
  src/status_im/events.cljs
  src/status_im2/common/standard_authentication/core.cljs
  src/status_im2/common/standard_authentication/enter_password/view.cljs
  src/status_im2/common/standard_authentication/events.cljs
  src/status_im2/common/standard_authentication/password_input/style.cljs
  src/status_im2/common/standard_authentication/password_input/view.cljs
  src/status_im2/common/standard_authentication/standard_auth/authorize.cljs
  src/status_im2/common/standard_authentication/standard_auth/button/view.cljs
  src/status_im2/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/events.cljs
  src/status_im2/contexts/profile/profiles/view.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/contexts/syncing/setup_syncing/view.cljs
  src/status_im2/contexts/wallet/add_address_to_watch/confirm_address/view.cljs
  src/status_im2/contexts/wallet/create_account/view.cljs
  src/status_im2/contexts/wallet/events.cljs
Labels: Tested - OK, request-manual-qa

#18101 fix sometimes add contact screen is closed by itself after scanning QR code
  src/status_im2/common/scan_qr_code/view.cljs
Labels: Tested - OK, request-manual-qa

#18117 move blob to rn, remove unused code, move images events to status-im2
  src/mocks/js_dependencies.cljs
  src/react_native/blob.cljs
  src/status_im/chat/models/gaps.cljs
  src/status_im/chat/models/images.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/chat/models/message_content.cljs
  src/status_im/events.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/subs/root.cljs
  src/status_im/ui/components/chat_icon/screen.cljs
  src/status_im/ui/screens/chat/group.cljs
  src/status_im/ui/screens/chat/message/gap.cljs
  src/status_im/ui/screens/chat/message/legacy_style.cljs
  src/status_im/ui/screens/chat/message/legacy_view.cljs
  src/status_im/ui/screens/chat/photos.cljs
  src/status_im/ui/screens/chat/sheets.cljs
  src/status_im/ui/screens/chat/stickers/styles.cljs
  src/status_im/ui/screens/chat/stickers/views.cljs
  src/status_im/ui/screens/chat/styles/input/gap.cljs
  src/status_im/ui/screens/chat/styles/main.cljs
  src/status_im/ui/screens/chat/styles/message/sheets.cljs
  src/status_im/ui/screens/chat/styles/photos.cljs
  src/status_im/ui/screens/chat/utils.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im/ui/screens/wallet/accounts/sheets.cljs
  src/status_im/ui/screens/wallet/manage_connections/styles.cljs
  src/status_im/ui/screens/wallet/manage_connections/views.cljs
  src/status_im/ui/screens/wallet_connect/session_proposal/styles.cljs
  src/status_im/ui/screens/wallet_connect/session_proposal/views.cljs
  src/status_im2/common/signals/events.cljs
  src/status_im2/config.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/lightbox/effects.cljs
  src/status_im2/contexts/chat/lightbox/events.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/events.cljs
  src/status_im2/navigation/view.cljs
  src/status_im2/subs/messages.cljs
Labels: E:Mobile Tech Debt

#17920 [#17896] Raw balances using big number
  src/quo/components/wallet/account_card/view.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
  src/utils/money.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18018 [#17965] Create token component
  resources/images/tokens/mainnet/ETH@2x.png
  resources/images/tokens/mainnet/ETH@3x.png
  src/quo/components/community/token_gating.cljs
  src/quo/components/icon.cljs
  src/quo/components/list_items/preview_list/view.cljs
  src/quo/components/list_items/token_network/component_spec.cljs
  src/quo/components/list_items/token_network/style.cljs
  src/quo/components/list_items/token_network/view.cljs
  src/quo/components/list_items/token_value/view.cljs
  src/quo/components/tags/context_tag/style.cljs
  src/quo/components/tags/context_tag/view.cljs
  src/quo/components/tags/summary_tag/component_spec.cljs
  src/quo/components/tags/summary_tag/style.cljs
  src/quo/components/tags/summary_tag/view.cljs
  src/quo/components/tags/token_tag/style.cljs
  src/quo/components/tags/token_tag/view.cljs
  src/quo/components/utilities/token/loader.clj
  src/quo/components/utilities/token/loader.cljs
  src/quo/components/utilities/token/view.cljs
  src/quo/components/wallet/network_amount/view.cljs
  src/quo/components/wallet/token_input/style.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/quo/components/wallet/transaction_summary/component_spec.cljs
  src/quo/core.cljs
  src/quo/foundations/resources.cljs
  src/status_im2/contexts/quo_preview/community/token_gating.cljs
  src/status_im2/contexts/quo_preview/drawers/permission_drawers.cljs
  src/status_im2/contexts/quo_preview/list_items/preview_lists.cljs
  src/status_im2/contexts/quo_preview/list_items/token_network.cljs
  src/status_im2/contexts/quo_preview/settings/category.cljs
  src/status_im2/contexts/quo_preview/settings/reorder_item.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
  src/status_im2/contexts/quo_preview/tags/summary_tag.cljs
  src/status_im2/contexts/quo_preview/tags/token_tag.cljs
  src/status_im2/contexts/quo_preview/wallet/transaction_summary.cljs
  src/status_im2/contexts/quo_preview/wallet/wallet_activity.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/contexts/wallet/send/select_asset/view.cljs
  src/status_im2/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa

#17941 Community requests to join when admin is offline
  status-go-version.json
Labels: request-manual-qa, status-go

#18123 Community Request to Join - Show Addresses to share Cards
  src/status_im2/contexts/communities/actions/accounts_selection/style.cljs
  src/status_im2/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im2/contexts/communities/actions/community_rules/style.cljs
  src/status_im2/contexts/communities/actions/community_rules/view.cljs
  translations/en.json
Labels: E:Mobile Communities MVP, E:Mobile Release 1.27, skip-manual-qa

#18019 feat: add encoded data for profile sharing url
  src/schema/common.cljs
  src/schema/re_frame.cljs
  src/status_im/profile/core.cljs
  src/status_im/ui/components/invite/events.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im2/common/universal_links.cljs
  src/status_im2/common/universal_links_test.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/quo_preview/share/share_qr_code.cljs
  src/status_im2/contexts/shell/share/view.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/setup/schema.cljs
  src/utils/address.cljs
  src/utils/address_test.cljs
  src/utils/image_server.cljs
Labels: Tested - OK, request-manual-qa

#17241 PR to upgrade `react-native` to 0.72.5 and many other things
  .eslintrc.js
  .gitignore
  Makefile
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/app/src/main/java/im/status/ethereum/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/im/status/ethereum/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/im/status/ethereum/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/build.gradle
  android/gradle.properties
  android/settings.gradle
  babel.config.js
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.h
  ios/StatusIm/AppDelegate.mm
  metro.config.js
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/deps/gradle/gradle_parser.awk
  nix/deps/gradle/proj.list
  nix/deps/nodejs-patched/default.nix
  nix/overlay.nix
  nix/pkgs/aapt2/default.nix
  nix/pkgs/android-sdk/compose.nix
  nix/scripts/node_modules.sh
  package.json
  react-native.config.js
  scripts/start-react-native.sh
  src/mocks/js_dependencies.cljs
  src/react_native/keychain.cljs
  src/react_native/permissions.cljs
  src/react_native/platform.cljs
  src/status_im2/common/toasts/animation.cljs
  src/status_im2/contexts/chat/composer/actions/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/photo_selector/effects.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/select_photo/method_menu/view.cljs
  src/status_im2/core.cljs
  test/jest/jest.config.js
  test/jest/jestSetup.js
  yarn.lock
Labels: Tested - OK, E:Mobile React Native, request-manual-qa, E:Mobile Tech Debt, E:Mobile Developer XP

#18150 move reactions events
  src/status_im/chat/models/loading.cljs
  src/status_im/chat/models/reactions.cljs
  src/status_im/data_store/reactions.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/messages/content/reactions/events.cljs
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/contexts/chat/messages/transport/events.cljs
  src/status_im2/subs/messages.cljs
  src/status_im2/subs/root.cljs
Labels: E:Mobile Tech Debt

#18099 fix: no avatar for the first message in 1-1 chat
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
  src/status_im2/contexts/chat/messages/list/events.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Bug MVP

#17879 Add 'Test Networks Enabled' option in settings
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/profile/settings/events.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#18134 Remove toggle for disabling shell navigation (#18133)
  src/status_im2/config.cljs
  src/status_im2/contexts/chat/composer/sub_view.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/contexts/shell/jump_to/components/switcher_cards/view.cljs
  src/status_im2/contexts/shell/jump_to/effects.cljs
  src/status_im2/contexts/shell/jump_to/events.cljs
  src/status_im2/contexts/shell/jump_to/utils.cljs
  src/status_im2/contexts/shell/jump_to/view.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#17862 Wallet - Implement Network Configuration #17840
  src/status_im2/contexts/wallet/common/sheets/account_options/view.cljs
  src/status_im2/contexts/wallet/common/sheets/network_preferences/view.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/contexts/wallet/edit_account/view.cljs
  src/status_im2/subs/wallet/networks.cljs
  src/status_im2/subs/wallet/networks_test.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, external, test cases are required

#18071 chore(wallet): add flow for selecting own accounts in send flows
  src/status_im2/contexts/wallet/send/events.cljs
  src/status_im2/contexts/wallet/send/select_address/style.cljs
  src/status_im2/contexts/wallet/send/select_address/tabs/style.cljs
  src/status_im2/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  src/status_im2/events.cljs
  src/status_im2/subs/root.cljs
  src/status_im2/subs/wallet/send.cljs
  src/status_im2/subs/wallet/send_test.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18128 e2e: skipped universal links test + some fixes
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/saucelabs_sauce_chat.png
  test/appium/views/home_view.py
Labels: tests

#18136 Wallet: Token item fixes
  src/quo/components/list_items/token_value/component_spec.cljs
  src/quo/components/list_items/token_value/view.cljs
  src/quo/components/utilities/token/view.cljs
  src/quo/foundations/common.cljs
  src/status_im2/contexts/quo_preview/list_items/token_value.cljs
  src/status_im2/contexts/wallet/common/temp.cljs
  src/status_im2/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Wallet MVP

#17957 #17945 Scanned address persists in ETH address textbox after reopening 'Add address to watch' screen
  src/status_im2/contexts/wallet/add_address_to_watch/view.cljs
Labels: Tested - OK, request-manual-qa

#17890 [#17518] fix: try again when sync has error outside the onboarding flow
  src/status_im2/common/pairing/events.cljs
  src/status_im2/contexts/onboarding/syncing/progress/view.cljs
  src/status_im2/contexts/syncing/scan_sync_code/view.cljs
Labels: Tested - OK, request-manual-qa

#18100 Account switcher for send flow
  src/quo/components/drawers/drawer_top/view.cljs
  src/status_im2/common/data_store/wallet.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
  src/status_im2/contexts/wallet/account/tabs/view.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/account_switcher/view.cljs
  src/status_im2/contexts/wallet/common/sheets/select_account/style.cljs
  src/status_im2/contexts/wallet/common/sheets/select_account/view.cljs
  src/status_im2/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im2/contexts/wallet/send/input_amount/view.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  src/status_im2/contexts/wallet/send/select_asset/view.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#18059 Chat fixes based on design feedback
  src/quo/components/messages/system_message/style.cljs
  src/status_im2/contexts/chat/composer/view.cljs
  src/status_im2/contexts/chat/messages/content/style.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#18175 Display component name in quo preview header
  src/status_im2/contexts/quo_preview/preview.cljs
Labels: E:Mobile Developer XP

#18078 Added support for different currencies in token price calculation
  src/status_im/currency/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/wallet/account/view.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/contexts/wallet/send/select_asset/view.cljs
  src/status_im2/subs/profile.cljs
  src/status_im2/subs/profile_test.cljs
  src/status_im2/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#18121 Wallet: share address
  src/react_native/share.cljs
  src/status_im2/contexts/wallet/account/tabs/about/view.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18131 Share community via URL with any privileges
  status-go-version.json
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/chat_view.py
Labels: Tested - OK, e2e test blocker, request-manual-qa, status-go

#18111 Fix empty chat in opened on pressing hashtag in a community channel
  src/status_im/browser/core.cljs
  src/status_im/group_chats/core.cljs
  src/status_im2/common/universal_links.cljs
  src/status_im2/contexts/chat/effects.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/shell/activity_center/notification/membership/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs
  src/status_im2/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#18180 Community: Request to join - Show addresses shared
  src/status_im2/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im2/contexts/communities/actions/addresses_for_permissions/style.cljs
  src/status_im2/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: E:Mobile Communities MVP, skip-manual-qa

#18149 Close chat when closing group chat details
  src/status_im2/contexts/chat/group_details/view.cljs
Labels: Tested - OK, request-manual-qa

#18140 fix: App gets stuck on syncing process screen when scanning QR code v…
  src/status_im/multiaccounts/create/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im2/contexts/profile/create/events.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/profile/recover/events.cljs
Labels: Tested - OK, request-manual-qa

#18119 chore(wallet): add images to select address page
  resources/images/ui2/angry-man-dark@2x.png
  resources/images/ui2/angry-man-dark@3x.png
  resources/images/ui2/angry-man-light@2x.png
  resources/images/ui2/angry-man-light@3x.png
  resources/images/ui2/cat-in-box-dark@2x.png
  resources/images/ui2/cat-in-box-dark@3x.png
  resources/images/ui2/cat-in-box-light@2x.png
  resources/images/ui2/cat-in-box-light@3x.png
  resources/images/ui2/sweating-man-dark@2x.png
  resources/images/ui2/sweating-man-dark@3x.png
  resources/images/ui2/sweating-man-light@2x.png
  resources/images/ui2/sweating-man-light@3x.png
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/quo_preview/empty_state/empty_state.cljs
  src/status_im2/contexts/shell/activity_center/tabs/empty_tab/view.cljs
  src/status_im2/contexts/wallet/home/style.cljs
  src/status_im2/contexts/wallet/home/view.cljs
  src/status_im2/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#18190 Wallet - Watched Account UI Updates
  src/quo/components/drawers/drawer_top/style.cljs
  src/quo/components/drawers/drawer_top/view.cljs
  src/quo/components/list_items/account/component_spec.cljs
  src/quo/components/list_items/account/style.cljs
  src/quo/components/list_items/account/view.cljs
  src/quo/components/navigation/page_nav/view.cljs
  src/status_im2/contexts/quo_preview/list_items/account.cljs
  src/status_im2/contexts/wallet/common/account_switcher/view.cljs
  src/status_im2/contexts/wallet/common/sheets/account_options/view.cljs
Labels: Tested - OK, request-manual-qa

#18124 Invite friends (#17570)
  src/status_im2/contexts/chat/home/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#18055 Optimize chat screen navigation view
  src/js/worklets/chat/lightbox.js
  src/js/worklets/chat/messages.js
  src/mocks/js_dependencies.cljs
  src/quo/components/banners/banner/style.cljs
  src/react_native/reanimated.cljs
  src/status_im2/contexts/chat/composer/utils.cljs
  src/status_im2/contexts/chat/composer/view.cljs
  src/status_im2/contexts/chat/lightbox/utils.cljs
  src/status_im2/contexts/chat/messages/constants.cljs
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer/style.cljs
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer/view.cljs
  src/status_im2/contexts/chat/messages/list/style.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/navigation/style.cljs
  src/status_im2/contexts/chat/messages/navigation/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/style.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/contexts/chat/placeholder/style.cljs
  src/status_im2/contexts/chat/placeholder/view.cljs
  src/utils/worklets/chat/lightbox.cljs
  src/utils/worklets/chat/messages.cljs
  src/utils/worklets/lightbox.cljs
Labels: Tested - OK, request-manual-qa

#18104 Implement getSuggestedRoutes endpoint in the Send Flow for wallet
  src/status_im/multiaccounts/create/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/wallet/common/utils.cljs
  src/status_im2/contexts/wallet/events.cljs
  src/status_im2/contexts/wallet/events_test.cljs
  src/status_im2/contexts/wallet/send/events.cljs
  src/status_im2/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im2/contexts/wallet/send/input_amount/view.cljs
  src/status_im2/contexts/wallet/send/select_address/view.cljs
  src/status_im2/contexts/wallet/send/select_asset/view.cljs
  src/status_im2/subs/root.cljs
  src/status_im2/subs/wallet/wallet.cljs
  src/utils/money.cljs
Labels: Tested - OK, feature, request-manual-qa

#17773 Fix crash on x86_64 emulators
  android/gradle.properties
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
Labels: Tested - OK, request-manual-qa, status-go

#18218 move community code to status-im2
  src/status_im/communities/core.cljs
  src/status_im/communities/e2e.cljs
  src/status_im/ui/screens/communities/create.cljs
  src/status_im/ui/screens/communities/import.cljs
  src/status_im/ui/screens/communities/invite.cljs
  src/status_im/ui/screens/communities/members.cljs
  src/status_im/ui/screens/communities/membership.cljs
  src/status_im/ui/screens/group/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im2/common/home/title_column/view.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/messages/link_preview/events.cljs
  src/status_im2/contexts/chat/messages/transport/events.cljs
  src/status_im2/contexts/communities/actions/community_options/events.cljs
  src/status_im2/contexts/communities/actions/community_options/view.cljs
  src/status_im2/contexts/communities/actions/home_plus/view.cljs
  src/status_im2/contexts/communities/actions/leave/events.cljs
  src/status_im2/contexts/communities/events.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/overview/events.cljs
  src/status_im2/contexts/profile/login/events.cljs
  src/status_im2/contexts/shell/activity_center/notification/admin/view.cljs
  src/status_im2/events.cljs
  src/status_im2/integration_test/community_test.cljs
  src/status_im2/subs/chats.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Tech Debt, E:Mobile Migrate Old Ui Code

#18130 e2e: moving to android14
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/old_ui/medium/test_pairing_devices_sync_m.py
  test/appium/tests/old_ui/medium/test_profile_m.py
  test/appium/tests/old_ui/test_pairing_devices_sync.py
  test/appium/tests/upgrade/test_upgrade.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/elements_templates/member3.png
  test/appium/views/elements_templates/saucelabs_sauce_chat.png
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#18020 fix: universal link regex
  src/status_im/common/router.cljs
  src/status_im/constants.cljs
  src/utils/universal_links_test.cljs
  src/utils/validators.cljs
  test/appium/tests/critical/test_deep_and_universal_links.py
Labels: Tested - OK, request-manual-qa

#18252 move keycard native module, removed outdated code
  src/keycard/keycard.cljs
  src/keycard/real_keycard.cljs
  src/legacy/status_im/bottom_sheet/sheets.cljs
  src/legacy/status_im/keycard/card.cljs
  src/legacy/status_im/keycard/common.cljs
  src/legacy/status_im/keycard/simulated_keycard.cljs
  src/legacy/status_im/ui/screens/home/styles.cljs
  src/legacy/status_im/ui/screens/home/views/inner_item.cljs
  src/legacy/status_im/ui/screens/keycard/authentication_method/styles.cljs
  src/legacy/status_im/ui/screens/keycard/authentication_method/views.cljs
  src/legacy/status_im/ui/screens/keycard/components/description.cljs
  src/legacy/status_im/ui/screens/keycard/components/keycard_animation.cljs
  src/legacy/status_im/ui/screens/keycard/components/style.cljs
  src/legacy/status_im/ui/screens/keycard/components/turn_nfc.cljs
  src/legacy/status_im/ui/screens/keycard/frozen_card/view.cljs
  src/legacy/status_im/ui/screens/keycard/keycard_interaction.cljs
  src/legacy/status_im/ui/screens/keycard/onboarding/views.cljs
  src/legacy/status_im/ui/screens/keycard/pairing/views.cljs
  src/legacy/status_im/ui/screens/keycard/pin/styles.cljs
  src/legacy/status_im/ui/screens/keycard/pin/views.cljs
  src/legacy/status_im/ui/screens/keycard/recovery/views.cljs
  src/legacy/status_im/ui/screens/keycard/settings/views.cljs
  src/legacy/status_im/ui/screens/keycard/styles.cljs
  src/legacy/status_im/ui/screens/keycard/views.cljs
  src/legacy/status_im/ui/screens/popover/views.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/legacy/status_im/ui/screens/signing/views.cljs
  src/legacy/status_im/ui/screens/wallet/add_new/views.cljs
Labels: E:Mobile Tech Debt, E:Mobile Migrate Old Ui Code

#18115 Set fleet to shards.test
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/nodejs/status.cpp
  src/legacy/status_im/fleet/core.cljs
  src/legacy/status_im/keycard/card.cljs
  src/legacy/status_im/keycard/recovery.cljs
  src/legacy/status_im/log_level/core.cljs
  src/legacy/status_im/multiaccounts/create/core.cljs
  src/legacy/status_im/network/core.cljs
  src/legacy/status_im/node/core.cljs
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
  src/legacy/status_im/ui/screens/fleet_settings/views.cljs
  src/legacy/status_im/utils/test.cljs
  src/legacy/status_im/waku/core.cljs
  src/native_module/core.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/config.cljs
  src/status_im/contexts/chat/actions/view.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/communities/actions/chat/view.cljs
  src/status_im/contexts/profile/rpc.cljs
  src/status_im/subs/profile.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, E:Mobile Release 1.26

#18118 [#17393] feat: add new setting ui
  resources/images/icons2/20x20/automatic@2x.png
  resources/images/icons2/20x20/automatic@3x.png
  resources/images/icons2/20x20/offline@2x.png
  resources/images/icons2/20x20/offline@3x.png
  src/legacy/status_im/browser/core_test.cljs
  src/quo/components/buttons/logout_button/component_spec.cljs
  src/quo/components/buttons/logout_button/style.cljs
  src/quo/components/buttons/logout_button/view.cljs
  src/quo/components/drawers/action_drawers/style.cljs
  src/quo/components/drawers/action_drawers/view.cljs
  src/quo/components/dropdowns/dropdown/view.cljs
  src/quo/components/settings/category/settings/view.cljs
  src/quo/components/settings/category/style.cljs
  src/quo/components/settings/settings_item/style.cljs
  src/quo/components/settings/settings_item/view.cljs
  src/quo/components/text_combinations/style.cljs
  src/quo/components/text_combinations/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/common/home/top_nav/view.cljs
  src/status_im/contexts/profile/settings/header/avatar.cljs
  src/status_im/contexts/profile/settings/header/utils.cljs
  src/status_im/contexts/profile/settings/header/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/profile/settings/style.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/contexts/profile/settings/visibility_sheet/view.cljs
Labels: Tested - OK, followup required

#18106 Biometrics button on login screen
  src/status_im/common/biometric/events.cljs
  src/status_im/common/standard_authentication/password_input/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/profiles/view.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18203 e2e: profile view changes
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
Labels: tests

#18197 Added assets skeleton in wallet home and account screen
  src/quo/components/loaders/skeleton_list/component_spec.cljs
  src/quo/components/loaders/skeleton_list/constants.cljs
  src/quo/components/loaders/skeleton_list/style.cljs
  src/quo/components/loaders/skeleton_list/view.cljs
  src/status_im/contexts/quo_preview/loaders/skeleton_list.cljs
  src/status_im/contexts/wallet/account/tabs/assets/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/common/temp.cljs
  src/status_im/contexts/wallet/home/style.cljs
  src/status_im/contexts/wallet/home/tabs/assets/style.cljs
  src/status_im/contexts/wallet/home/tabs/assets/view.cljs
  src/status_im/contexts/wallet/home/tabs/style.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/contexts/wallet/home/view.cljs
Labels: Tested - OK, request-manual-qa

#18189 Communities: Share airdrop address in non token-gated community
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/style.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: E:Mobile Communities MVP, skip-manual-qa

#18217 chore: add outline for transaction-progress page
  resources/images/ui2/transaction-progress@2x.png
  resources/images/ui2/transaction-progress@3x.png
  src/quo/components/buttons/wallet_ctas/view.cljs
  src/quo/components/utilities/token/loader.cljs
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/common/resources.cljs
  src/status_im/contexts/status_im_preview/common/floating_button_page/view.cljs
  src/status_im/contexts/wallet/send/transaction_progress/style.cljs
  src/status_im/contexts/wallet/send/transaction_progress/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: E:Mobile Wallet Release 1.27

#18263 e2e: added validation of encoded data in community and profile urls
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/tests/non_func/test_api.py
  test/appium/views/home_view.py
Labels: tests

#18249 move status-im from utils
  scripts/lint/re-frame-in-quo-components.sh
  src/legacy/status_im/browser/core.cljs
  src/legacy/status_im/wallet/choose_recipient/core.cljs
  src/status_im/common/font/effects.cljs
  src/status_im/common/router.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/common/universal_links_test.cljs
  src/status_im/common/validators.cljs
  src/status_im/common/validators_test.cljs
  src/status_im/contexts/add_new_contact/events.cljs
  src/status_im/subs/contact.cljs
  src/status_im/subs/profile.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
  src/utils/universal_links.cljs
  src/utils/universal_links_test.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Tech Debt

#18213 [#17964] emoji screen performance
  src/quo/components/utilities/token/view.cljs
  src/status_im/common/bottom_sheet_screen/style.cljs
  src/status_im/common/bottom_sheet_screen/view.cljs
  src/status_im/contexts/emoji_picker/data.cljs
  src/status_im/contexts/emoji_picker/utils.cljs
  src/status_im/contexts/emoji_picker/view.cljs
Labels: Tested - OK, request-manual-qa

#18070 feat: spectate community before join
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/chat/messages/link_preview/events.cljs
  src/status_im/contexts/chat/messages/link_preview/events_test.cljs
  src/status_im/contexts/chat/messages/link_preview/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#18266 Wallet: best route UI
  src/quo/components/wallet/network_bridge/style.cljs
  src/quo/components/wallet/network_bridge/view.cljs
  src/quo/components/wallet/network_link/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/receive/view.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/style.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/core_spec.cljs
  translations/en.json
Labels: E:Mobile Wallet MVP

#18283 apk name updated in e2e nightly jenkins file
  ci/tests/Jenkinsfile.e2e-nightly
Labels: tests

#17918 fix: theming toast component
  src/quo/components/notifications/toast/style.cljs
  src/quo/components/notifications/toast/view.cljs
  src/quo/core_spec.cljs
  src/status_im/common/device_permissions.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/common/pairing/events.cljs
  src/status_im/common/scan_qr_code/view.cljs
  src/status_im/contexts/chat/composer/actions/view.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/lightbox/top_view.cljs
  src/status_im/contexts/chat/messages/delete_message/events.cljs
  src/status_im/contexts/chat/messages/delete_message_for_me/events.cljs
  src/status_im/contexts/chat/messages/pin/events.cljs
  src/status_im/contexts/chat/photo_selector/view.cljs
  src/status_im/contexts/communities/actions/community_options/events.cljs
  src/status_im/contexts/communities/actions/leave/events.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/contacts/drawers/nickname_drawer/view.cljs
  src/status_im/contexts/quo_preview/notifications/toast.cljs
  src/status_im/contexts/shell/share/events.cljs
  src/status_im/contexts/syncing/enter_sync_code/view.cljs
  src/status_im/contexts/syncing/events.cljs
  src/status_im/contexts/syncing/scan_sync_code/view.cljs
  src/status_im/contexts/syncing/setup_syncing/view.cljs
  src/status_im/contexts/wallet/common/sheets/account_options/view.cljs
  src/status_im/contexts/wallet/edit_account/view.cljs
  src/status_im/contexts/wallet/events.cljs
Labels: Tested - OK, feature, request-manual-qa

#18259 Import of https://github.com/status-im/status-mobile/pull/18256
  src/quo/components/wallet/account_card/view.cljs
Labels: Tested - OK

#18281 improve profile screen performance
  src/quo/components/settings/category/settings/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/utils/re_frame.cljs
Labels: E:Mobile Performance MVP

#18253 Log some message information in debug mode to investigate delivery issues
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#18290 e2e: fix for getting public key
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
Labels: tests

#18276 Fix component tests, upgrade Jest & friends, and a few other goodies
  .clj-kondo/status-im/config.edn
  .zprintrc
  Makefile
  nix/deps/nodejs-patched/default.nix
  package.json
  scripts/lint/require-i18n-resource-first.sh
  shadow-cljs.edn
  src/quo/components/buttons/slide_button/component_spec.cljs
  src/quo/components/colors/color_picker/component_spec.cljs
  src/quo/components/colors/color_picker/view.cljs
  src/quo/components/dividers/strength_divider/component_spec.cljs
  src/quo/components/drawers/drawer_buttons/component_spec.cljs
  src/quo/components/drawers/drawer_top/component_spec.cljs
  src/quo/components/graph/wallet_graph/component_spec.cljs
  src/quo/components/inputs/address_input/component_spec.cljs
  src/quo/components/inputs/title_input/component_spec.cljs
  src/quo/components/keycard/component_spec.cljs
  src/quo/components/list_items/account/component_spec.cljs
  src/quo/components/list_items/address/component_spec.cljs
  src/quo/components/record_audio/record_audio/component_spec.cljs
  src/quo/components/record_audio/soundtrack/component_spec.cljs
  src/quo/components/tags/permission_tag.cljs
  src/quo/components/wallet/account_origin/component_spec.cljs
  src/quo/components/wallet/network_bridge/view.cljs
  src/quo/components/wallet/network_routing/view.cljs
  src/quo/components/wallet/transaction_progress/view.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/chat/messages/content/audio/component_spec.cljs
  src/status_im/contexts/communities/actions/community_options/component_spec.cljs
  src/status_im/contexts/wallet/add_address_to_watch/component_spec.cljs
  src/status_im/contexts/wallet/add_address_to_watch/confirm_address/component_spec.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/core_spec.cljs
  src/status_im/setup/schema.cljs
  src/test_helpers/component.clj
  src/test_helpers/component.cljs
  src/test_helpers/component_tests_preload.cljs
  test/jest/jest.config.js
  test/jest/jestSetup.js
  yarn.lock
Labels: E:Mobile Fixes After React Native Upgrade

#18302 Add `:wallet/accounts-with-customization-color` subscription
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: skip-manual-qa

#18303 e2e: tests fixes
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/chat_view.py
  test/appium/views/dbs/waku_backup/user.py
  test/appium/views/sign_in_view.py
Labels: tests

#18298 Wallet: about tab fixes
  src/status_im/contexts/wallet/account/tabs/about/view.cljs
Labels: Tested - OK, request-manual-qa

#18288 [#18280] Fix token images not being displayed
  src/quo/components/utilities/token/loader.cljs
Labels: Tested - OK, request-manual-qa

#18293 PR to add `Kotlin` support and to Kotlinifiy `MainApplication.java`, `MainActivity.java`
  android/app/build.gradle
  android/app/src/main/java/im/status/ethereum/MainActivity.java
  android/app/src/main/java/im/status/ethereum/MainActivity.kt
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  android/app/src/main/java/im/status/ethereum/MainApplication.kt
  android/build.gradle
  android/gradle.properties
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
Labels: Tested - OK, request-manual-qa

#18316 e2e: wait for Join button to be available
  test/appium/views/chat_view.py
Labels: tests

#17839 keep chat screen loaded
  src/status_im/contexts/chat/messages/view.cljs
  src/status_im/contexts/shell/jump_to/animation.cljs
  src/status_im/contexts/shell/jump_to/components/floating_screens/view.cljs
  src/status_im/contexts/shell/jump_to/events.cljs
Labels: Tested - OK, request-manual-qa

#18292 Fix no message preview on long press on the reaction
  src/status_im/contexts/chat/messages/content/reactions/view.cljs
Labels: Tested - OK, request-manual-qa
