Repository status-im/status-mobile, pull requests merged in 2023-02, with the labels that each got.

#14768 feat: support deleted by xxx
  src/quo2/components/messages/system_message.cljs
  src/quo2/core.cljs
  src/status_im/chat/models/message.cljs
  src/status_im/data_store/messages.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/delete_message/events.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#14925 Animated Header Flatlist
  src/quo2/components/animated_header_flatlist/style.cljs
  src/quo2/components/animated_header_flatlist/view.cljs
  src/quo2/components/separator.cljs
  src/react_native/reanimated.cljs
  src/status_im2/contexts/quo_preview/animated_header_list/animated_header_list.cljs
  src/status_im2/contexts/quo_preview/main.cljs
Labels: new-design [quo2], Animations

#14867 Photo selector and album selector screens
  src/quo2/components/dividers/divider_label.cljs
  src/quo2/components/notifications/toast.cljs
  src/status_im/chat/models/images.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/events.cljs
  src/status_im/ui/screens/communities/create.cljs
  src/status_im/ui2/screens/chat/composer/images/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/messages/composer/controls/view.cljs
  src/status_im2/contexts/chat/messages/content/album/style.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/photo_selector/album_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/root.cljs
  translations/en.json
Labels: request-manual-qa

#14941 Update style namespaces to follow guidelines
  doc/new-guidelines.md
  src/status_im2/contexts/add_new_contact/style.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  src/status_im2/contexts/shell/home_stack.cljs
  src/status_im2/contexts/shell/style.cljs
Labels: chore

#14954 Lightbox screen animations
  src/react_native/core.cljs
  src/react_native/gesture.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  status-go-version.json
Labels: Animations

#14948 e2e: get rid of workarounds + saucelab client update
  test/appium/requirements.txt
  test/appium/support/base_test_report.py
  test/appium/tests/__init__.py
  test/appium/tests/base_test_case.py
  test/appium/tests/cloudbase_test_api.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/home_view.py
Labels: tests

#14960 Unread indicator on community channel
  src/quo2/components/common/unread_grey_dot/style.cljs
  src/quo2/components/common/unread_grey_dot/view.cljs
  src/quo2/components/community/community_list_view.cljs
  src/quo2/components/list_items/channel.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
Labels: Tested - OK

#14936 fix: Unable to add new contact on receiver device after local pairing…
  src/status_im/signals/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/navigation/core.cljs
Labels: Tested - OK, request-manual-qa

#14949 feat: style delivery states
  resources/images/icons2/12x12/delivered@2x.png
  resources/images/icons2/12x12/delivered@3x.png
  resources/images/icons2/12x12/sent@2x.png
  resources/images/icons2/12x12/sent@3x.png
  src/status_im/ui/screens/chat/styles/message/message.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/contexts/chat/messages/content/status/style.cljs
  src/status_im2/contexts/chat/messages/content/status/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  translations/en.json
Labels: Tested - OK, feature

#14825 Scrolling discover screen
  ios/Podfile.lock
  src/quo2/components/buttons/button.cljs
  src/quo2/components/community/community_card_view.cljs
  src/status_im2/common/scroll_page/style.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/discover/style.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/overview/style.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#14991 fix selected members are not shown on the group creation screen
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/ui2/screens/chat/components/new_chat/view.cljs
Labels: Tested - OK, request-manual-qa

#14993 ci: fetch E2E APK from android-e2e jobs
  ci/Jenkinsfile.combined
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
Labels: android, tests

#14964 Support join.status.im links for adding a contact (#14814)
  src/status_im/integration_test.cljs
  src/status_im/utils/test.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/status_im2/contexts/add_new_contact/events_test.cljs
  translations/en.json
Labels: Tested - OK

#14929 Community home scrolling
  src/quo2/components/navigation/page_nav.cljs
  src/status_im2/common/home/style.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/home/style.cljs
  src/status_im2/contexts/communities/home/view.cljs
Labels: Tested - OK, request-manual-qa

#15001 Fix segmented tab component
  src/quo2/components/tabs/segmented_tab.cljs
  src/quo2/components/tabs/tab/style.cljs
  src/quo2/components/tabs/tab/view.cljs
Labels: new-design [quo2]

#15008 Improve guidelines
  doc/new-guidelines.md
Labels: docs

#14986 added unread mentions counter
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
Labels: Tested - OK

#14988 [#14962] Update AC notification on EditMessage
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15044 ci: add cleanup step to all e2e Jenkins jobs
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
Labels: bug, tests

#14985 Better handling of contact request state & fix on go-waku panic
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#14996 fix: image actions
  shadow-cljs.edn
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/messages/content/album/style.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
Labels: Tested - OK

#15051 [#15046] Contacts in contact list are sorted by 3-random name
  src/status_im/contact/db.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/core_test.cljs
  src/status_im2/subs/contact.cljs
  src/status_im2/subs/contact_test.cljs
Labels: Tested - OK, release, request-manual-qa

#14987 fetch emoji hash for profile
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/native_module/core.cljs
  src/status_im2/contexts/emoji_hash/events.cljs
Labels: request-manual-qa

#14971 The [Cancel] and [Join] buttons are hidden within 'Join Community' overlay
  src/quo2/components/selectors/disclaimer/style.cljs
  src/status_im2/common/bottom_sheet/styles.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/communities/menus/request_to_join/style.cljs
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, release, request-manual-qa

#15060 communities home header flickering when user scrolls
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
Labels: request-manual-qa

#15081 ci: update ITSEncryptionExportComplianceCode
  ios/StatusIm/Info.plist
  ios/StatusImPR/Info.plist
Labels: ios, release

#15079 fix new chat button is not visible in small screen devices
  src/status_im/ui2/screens/chat/components/new_chat/styles.cljs
  src/status_im/ui2/screens/chat/components/new_chat/view.cljs
  src/status_im2/common/contact_list/view.cljs
Labels: Tested - OK, release, request-manual-qa

#15077 [#15019] small option card component
  resources/images/mock/small_opt_card_icon.png
  resources/images/mock/small_opt_card_main.png
  src/quo2/components/onboarding/small_option_card/component_spec.cljs
  src/quo2/components/onboarding/small_option_card/style.cljs
  src/quo2/components/onboarding/small_option_card/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im/react_native/resources.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/onboarding/small_option_card.cljs
  src/test_helpers/component.cljs
Labels: new-design [quo2]

#15089 fix deep links to user profiles don't do anything on tap
  src/status_im/router/core.cljs
  src/status_im/utils/universal_links/core.cljs
Labels: Tested - Issues, release, request-manual-qa

#15100 Get community-id from notification data for mentions and replies
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
Labels: chore, Activity center

#15083 display-name -> preferred-name
  src/status_im/multiaccounts/core.cljs
  status-go-version.json
Labels: Tested - OK, release

#14977 fix: delete message action logic
  src/quo2/components/messages/system_message.cljs
  src/status_im/ui2/screens/chat/components/reply/view.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/config.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/delete_message/events.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/pin/events.cljs
  src/status_im2/contexts/chat/messages/pin/list/view.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
Labels: Tested - OK

#15111 Updated pytest and pytest-xdist versions
  test/appium/requirements.txt
Labels: tests

#15109 Fix for connection error
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
Labels: tests

#15072 Feat: pass node config and kdf when local pairing
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/node/core.cljs
  src/status_im2/config.cljs
  src/status_im2/contexts/syncing/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15124 fix new chat selected contact
  src/status_im/ui2/screens/chat/components/new_chat/view.cljs
Labels: Tested - OK, release, request-manual-qa

#15122 Fix for empty display-name
  src/status_im/multiaccounts/core.cljs
Labels: Tested - OK, release, request-manual-qa

#15126 Add display name/ens to activity center
  src/status_im2/contexts/activity_center/utils.cljs
Labels: Tested - OK, release

#15005 feat: new text message (1)
  src/status_im2/contexts/chat/messages/content/text/style.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
Labels: request-manual-qa, E:MobileMessagingRD

#14952 Introduce marking all notifications as read in Activity Center
  src/quo2/components/drawers/action_drawers/view.cljs
  src/quo2/components/notifications/toast.cljs
  src/status_im/data_store/activities.cljs
  src/status_im2/common/bottom_sheet/styles.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/style.cljs
  src/status_im2/contexts/activity_center/view.cljs
  src/status_im2/subs/activity_center.cljs
  translations/en.json
Labels: Tested - OK, Tested - Issues, feature, request-manual-qa, Activity center

#15094 [Fixes: #15093] Add support for mention @everyone
  src/status_im/ui/screens/chat/components/contact_request.cljs
  src/status_im/ui/screens/chat/components/reply.cljs
  src/status_im/ui/screens/home/views/inner_item.cljs
  src/status_im/ui2/screens/chat/components/reply/view.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/subs/chat/messages.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15002 Paste button
  src/status_im2/contexts/add_new_contact/style.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
Labels: Tested - OK, request-manual-qa

#14853 Outgoing contact requests
  src/quo2/components/notifications/activity_log/style.cljs
  src/quo2/components/notifications/activity_log/view.cljs
  src/quo2/components/notifications/toast.cljs
  src/quo2/components/tags/status_tags.cljs
  src/status_im/contact/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification/common/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_request/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/events.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs
  src/status_im2/contexts/activity_center/notification/membership/view.cljs
  src/status_im2/contexts/activity_center/view.cljs
  src/status_im2/contexts/contacts/events.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15047 Community display picture & cover image style fixes
  src/status_im2/common/scroll_page/style.cljs
  src/status_im2/common/scroll_page/view.cljs
Labels: Tested - OK, request-manual-qa, external

#15155 ci: add Xcode cleanup Jenkinsfile
  ci/tools/Jenkinsfile.xcode-clean
Labels: devops

#15105 feat: quo2 color-picker component
  src/quo2/components/colors/color_picker/component_spec.cljs
  src/quo2/components/colors/color_picker/style.cljs
  src/quo2/components/colors/color_picker/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/quo_preview/colors/color_picker.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/test_helpers/component.cljs
Labels: external

#15157 quo2 password-tips component
  src/quo2/components/password/tips/component_spec.cljs
  src/quo2/components/password/tips/style.cljs
  src/quo2/components/password/tips/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/password/tips.cljs
Labels: external

#15132 quo2 profile-select component
  src/quo2/components/profile/select_profile/component_spec.cljs
  src/quo2/components/profile/select_profile/style.cljs
  src/quo2/components/profile/select_profile/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/profile/select_profile.cljs
Labels: external

#15078 Zoomable Image
  src/react_native/gesture.cljs
  src/react_native/reanimated.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/subs/root.cljs
Labels: Tested - OK, feature, images

#15098 fix community overview screen bannner height
  src/quo2/components/navigation/page_nav.cljs
  src/status_im2/common/scroll_page/style.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/discover/style.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/home/style.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/overview/style.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK

#15160 Tests: fixes
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#15106 Allow users to swipe to delete or swipe to toggle unread notification status
  src/mocks/js_dependencies.cljs
  src/quo2/components/notifications/activity_log/view.cljs
  src/quo2/components/tabs/tabs.cljs
  src/react_native/core.cljs
  src/react_native/gesture.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification/common/style.cljs
  src/status_im2/contexts/activity_center/notification/common/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/view.cljs
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/activity_center/view.cljs
  src/status_im2/contexts/chat/home/view.cljs
  src/status_im2/subs/activity_center.cljs
  src/status_im2/subs/activity_center_test.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, feature, Activity center

#15171 fix: no delete-by ui for delete for me message
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
Labels: Tested - OK

#15196 Navigation code cleanup
  src/status_im/add_new/core.cljs
  src/status_im/browser/core.cljs
  src/status_im/communities/core.cljs
  src/status_im/contact/block.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/keycard/backup_key.cljs
  src/status_im/keycard/login.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/recover/core.cljs
  src/status_im/navigation/core.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im/wallet/accounts/core.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/shell/animation.cljs
  src/status_im2/contexts/shell/events.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/events.cljs
  src/status_im2/navigation/state.cljs
Labels: Tested - OK, request-manual-qa

#15131 chore: add old edit option to communities options
  src/status_im/communities/core.cljs
  src/status_im2/contexts/communities/menus/community_options/view.cljs
Labels: Tested - OK

#15211 fix: image dimensions on Android
  src/status_im/chat/models/images.cljs
Labels: images

#15136 support local pairing after logged in as receiver
  src/status_im2/contexts/syncing/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15214 nix: fix Gradle nodeps JAR symlink filename
  nix/deps/gradle/default.nix
Labels: nix
