Repository status-im/status-mobile, pull requests merged in 2023-01, with the labels that each got.

#14694 cleanup and i18n revert
  src/i18n/i18n.cljs
  src/status_im/test_runner.cljs
  src/status_im/ui/screens/add_new/new_public_chat/view.cljs
  src/status_im/ui2/screens/chat/pin_limit_popover/view.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/view.cljs
  src/status_im2/setup/config.cljs
  src/status_im2/setup/core.cljs
  src/status_im2/setup/db.cljs
  src/status_im2/setup/events.cljs
  src/status_im2/setup/i18n_resources.cljs
  src/status_im2/setup/i18n_test.cljs
  src/status_im2/subs/chat/chats.cljs
Labels: Tested - Issues, request-manual-qa

#14652 Profile UI
  resources/images/icons2/20x20/keycard@2x.png
  resources/images/icons2/20x20/keycard@3x.png
  src/quo2/components/avatars/user_avatar.cljs
  src/quo2/components/buttons/button.cljs
  src/quo2/components/profile/profile_card/style.cljs
  src/quo2/components/profile/profile_card/view.cljs
  src/quo2/core.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/preview.cljs
  src/status_im2/contexts/quo_preview/profile/profile_card.cljs
Labels: external, new-design [quo2]

#14707 e2e: new groups
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
Labels: tests

#14690 abstract running code in separate thread for native java modules
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
Labels: Tested - OK, request-manual-qa

#14715 Fix clojure.set and clojure.walk inconsistent namespace aliases
  .clj-kondo/config.edn
  src/status_im/communities/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/data_store/chats.cljs
  src/status_im/data_store/contacts.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/data_store/pin_messages.cljs
  src/status_im/data_store/reactions.cljs
  src/status_im/data_store/visibility_status_updates.cljs
  src/status_im/navigation/core.cljs
  src/status_im/signing/core.cljs
  src/status_im/ui/screens/communities/reorder_categories.cljs
  src/status_im/utils/views.clj
  src/status_im/wallet/core.cljs
  src/status_im2/subs/multiaccount.cljs
Labels: chore

#14716 Move unit test helper namespaces to `src/test_helpers/`
  .clj-kondo/config.edn
  doc/new-guidelines.md
  src/status_im2/contexts/activity_center/events_test.cljs
  src/status_im2/subs/activity_center_test.cljs
  src/status_im2/subs/communities_test.cljs
  src/status_im2/subs/wallet/wallet_test.cljs
  src/test_helpers/unit.clj
  src/test_helpers/unit.cljs
Labels: chore

#14701 Persist switcher cards
  src/status_im/data_store/switcher_cards.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im2/contexts/shell/events.cljs
  src/status_im2/contexts/shell/view.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#14709 e2e: fixes
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
Labels: tests

#14658 e2e: new ui 1-1
  test/appium/tests/__init__.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#14717 Switcher button in chat is back
  src/status_im2/contexts/chat/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#14618 feat: undo delete with toast
  src/mocks/js_dependencies.cljs
  src/quo2/components/notifications/toast.cljs
  src/react_native/core.cljs
  src/react_native/reanimated.cljs
  src/status_im/chat/models/message_list.cljs
  src/status_im2/common/toasts/view.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/delete_message/events.cljs
  src/status_im2/contexts/chat/messages/delete_message/events_test.cljs
  src/status_im2/contexts/chat/messages/delete_message_for_me/events.cljs
  src/status_im2/contexts/chat/messages/delete_message_for_me/events_test.cljs
  src/status_im2/setup/db.cljs
  src/status_im2/subs/toasts.cljs
  translations/en.json
Labels: Tested - OK

#14734 fix Error: No matching clause: large
  src/status_im/ui2/screens/chat/messages/message.cljs
Labels: Tested - OK

#14739 New chat fix
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui2/screens/chat/components/new_chat/view.cljs
  src/status_im/ui2/screens/common/contact_list/view.cljs
  src/status_im2/subs/contact.cljs
Labels: Tested - OK, request-manual-qa

#14735 Communities join screens - add toast after joining/leaving
  src/status_im/communities/core.cljs
  src/status_im2/common/toasts/events.cljs
  src/status_im2/contexts/chat/messages/delete_message/events.cljs
  src/status_im2/contexts/chat/messages/delete_message_for_me/events.cljs
  src/status_im2/contexts/quo_preview/notifications/toast.cljs
  translations/en.json
Labels: request-manual-qa

#14737 Fix for tapping on new contact from contact list
  src/status_im2/common/contact_list_item/view.cljs
Labels: request-manual-qa

#14629 chore: use banner from quo library
  src/quo2/components/banners/banner/component_spec.cljs
  src/quo2/components/banners/banner/style.cljs
  src/quo2/components/banners/banner/view.cljs
  src/quo2/core_spec.cljs
  src/status_im/ui2/screens/chat/pin_limit_popover/style.cljs
  src/status_im/ui2/screens/chat/pin_limit_popover/view.cljs
  src/status_im/ui2/screens/chat/pinned_banner/view.cljs
  src/status_im2/common/not_implemented.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/contexts/quo_preview/banners/banner.cljs
Labels: Tested - OK, new-design [quo2]

#14749 e2e: failed tests
  test/appium/support/base_test_report.py
  test/appium/support/github_report.py
  test/appium/support/testrail_report.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#14751 Improve switcher cards lifecycle
  src/react_native/reanimated.cljs
  src/status_im/chat/models.cljs
  src/status_im/communities/core.cljs
  src/status_im/contact/block.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/integration_test.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/communities/views.cljs
  src/status_im/ui/screens/home/views.cljs
  src/status_im/utils/universal_links/core.cljs
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#14747 [Fixes: #14623] Enable mutual contacts by default and show banner
  src/quo2/components/drawers/permission_context/__tests__/permission_context_component_spec.cljs
  src/quo2/components/drawers/permission_context/style.cljs
  src/quo2/components/drawers/permission_context/view.cljs
  src/quo2/core_spec.cljs
  src/status_im/contact/core.cljs
  src/status_im/contact/db.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/chat/views.cljs
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/chat/chats_test.cljs
  src/status_im2/subs/contact.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#14512 fleets.json: drop decomissioned eth.test fleet
  Makefile
  resources/config/fleets.json
  src/status_im/node/core.cljs
  src/status_im/utils/config.cljs
Labels: Tested - OK, request-manual-qa

#14759 ci: upgrade Xcode from 13.4 to 14.2
  ci/Jenkinsfile.ios
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: ios, Tested - OK

#14750 [#14574] Update chat clock on group event
  status-go-version.json
Labels: Tested - OK

#14700 Communities Join Screens - Implement all permutations of Context Drawer options
  shadow-cljs.edn
  src/quo2/components/community/token_gating.cljs
  src/quo2/components/icons/icons.clj
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/home/actions/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/menus/community_options/component_spec.cljs
  src/status_im2/contexts/communities/menus/community_options/view.cljs
  src/status_im2/contexts/communities/menus/leave/style.cljs
  src/status_im2/contexts/communities/menus/leave/view.cljs
  src/status_im2/contexts/communities/menus/request_to_join/style.cljs
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/core_spec.cljs
  src/test_helpers/component.cljs
  test/jest/jest.config.js
  test/jest/jestSetup.js
  translations/en.json
Labels: Tested - OK, request-manual-qa

#14772 Tests/revert failed
  test/appium/support/base_test_report.py
  test/appium/support/github_report.py
  test/appium/support/testrail_report.py
  test/appium/tests/conftest.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#12849 ci: use arm64 macos hosts for iOS builds
  ci/Jenkinsfile.ios
Labels: ios

#14748 [#14713] Show Admin Notifications in Activity Center
  src/status_im/data_store/activities.cljs
  src/status_im2/common/constants.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification_types.cljs
  src/status_im2/contexts/activity_center/view.cljs
  translations/en.json
Labels: Tested - OK, feature, request-manual-qa, Activity center

#14778 e2e fix
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/medium/test_activity_center.py
Labels: tests

#14779 [Fixes: #14777] Set dns nameserver to cloudflare
  src/status_im/node/core.cljs
Labels: Tested - OK

#14810 Fix all type hint warnings
  src/quo2/components/tags/tags.cljs
  src/status_im/audio/core.cljs
  src/status_im/contact/block.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/transport/message/core.cljs
  src/status_im/ui/components/bottom_panel/views.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/status/views.cljs
  src/status_im/ui2/screens/chat/composer/input.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im/utils/money.cljs
  src/status_im/wallet_connect/core.cljs
  src/status_im/wallet_connect_legacy/core.cljs
Labels: chore

#14802 Small fix for 702838 + temp change for geth pulling
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  test/appium/support/testrail_report.py
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/chat_view.py
Labels: tests

#14803 Add Collectible ui component
  resources/images/mock/collectible.png
  src/quo2/components/profile/collectible/style.cljs
  src/quo2/components/profile/collectible/view.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/contexts/quo_preview/profile/collectible.cljs
Labels: external

#14771 [#14689] Link previews in chat
  ios/Podfile.lock
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/react_native/reanimated.cljs
  src/status_im/chat/models/link_preview.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signals/core.cljs
  src/status_im/ui/screens/chat/message/message.cljs
  src/status_im/ui/screens/chat/message/styles.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im/ui/screens/link_previews_settings/views.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/link_preview/events.cljs
  src/status_im2/contexts/chat/messages/link_preview/style.cljs
  src/status_im2/contexts/chat/messages/link_preview/view.cljs
  src/status_im2/subs/multiaccount.cljs
  src/utils/collection.cljs
Labels: Tested - OK

#14695 Scroll page animations
  src/js/worklet_factory.js
  src/react_native/reanimated.cljs
  src/status_im2/common/scroll_page/style.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: request-manual-qa, Animations

#14762 e2e: edit message + statuses
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/chat_view.py
Labels: tests

#14755 Images Album (2)
  src/status_im/chat/models/images.cljs
  src/status_im/chat/models/input.cljs
  src/status_im/data_store/messages.cljs
  src/status_im/transport/message/protocol.cljs
  src/status_im/ui2/screens/chat/composer/images/view.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/images_horizontal/style.cljs
  src/status_im2/contexts/chat/images_horizontal/view.cljs
  src/status_im2/contexts/chat/messages/content/album/style.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
  src/status_im2/subs/root.cljs
Labels: Tested - OK, feature

#14842 [Fixes: #14794] Use toast instead of old pin modal
  src/status_im/ui2/screens/chat/pin_limit_popover/style.cljs
  src/status_im/ui2/screens/chat/pin_limit_popover/view.cljs
  src/status_im2/common/home/actions/view.cljs
  src/status_im2/contexts/chat/messages/pin/events.cljs
  src/status_im2/contexts/chat/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#14824 [Fix] Admin Notification marked unread after closing and reopening AC
  src/status_im/communities/core.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
Labels: Tested - OK, request-manual-qa, Activity center

#14765 chore: get community img from real data
  src/status_im2/contexts/communities/menus/leave/style.cljs
  src/status_im2/contexts/communities/menus/leave/view.cljs
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK

#14856 Implement unread badge for bottom tabs
  src/quo2/components/tags/context_tags.cljs
  src/status_im2/contexts/shell/bottom_tabs.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#14785 Show "Added to group chat" notifications
  src/status_im/chat/models/loading.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_request/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs
  src/status_im2/contexts/activity_center/notification/membership/view.cljs
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/activity_center/notification_types.cljs
  src/status_im2/contexts/activity_center/view.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, feature, request-manual-qa, Activity center

#14634 Record audio flow
  resources/images/icons2/12x12/thumb-dark@2x.android.png
  resources/images/icons2/12x12/thumb-dark@2x.ios.png
  resources/images/icons2/12x12/thumb-dark@3x.android.png
  resources/images/icons2/12x12/thumb-dark@3x.ios.png
  resources/images/icons2/12x12/thumb-light@2x.android.png
  resources/images/icons2/12x12/thumb-light@2x.ios.png
  resources/images/icons2/12x12/thumb-light@3x.android.png
  resources/images/icons2/12x12/thumb-light@3x.ios.png
  src/quo2/components/record_audio/record_audio/__tests__/record_audio_component_spec.cljs
  src/quo2/components/record_audio/record_audio/buttons/delete_button.cljs
  src/quo2/components/record_audio/record_audio/buttons/lock_button.cljs
  src/quo2/components/record_audio/record_audio/buttons/record_button.cljs
  src/quo2/components/record_audio/record_audio/buttons/record_button_big.cljs
  src/quo2/components/record_audio/record_audio/buttons/send_button.cljs
  src/quo2/components/record_audio/record_audio/helpers.cljs
  src/quo2/components/record_audio/record_audio/style.cljs
  src/quo2/components/record_audio/record_audio/view.cljs
  src/quo2/components/record_audio/soundtrack/__tests__/soundtrack_component_spec.cljs
  src/quo2/components/record_audio/soundtrack/style.cljs
  src/quo2/components/record_audio/soundtrack/view.cljs
  src/quo2/core_spec.cljs
  src/react_native/core.cljs
  src/react_native/permissions.cljs
  src/react_native/slider.cljs
  src/status_im2/contexts/quo_preview/record_audio/record_audio.cljs
  src/test_helpers/component.clj
  src/test_helpers/component.cljs
  test/jest/jest.config.js
  test/jest/jestSetup.js
Labels: Tested - OK, feature, request-manual-qa, new-design [quo2]

#14860 [#14728] Fix sender avatar in reply
  src/status_im2/contexts/chat/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa

#14811 fix some buttons are not responding after theme change
  src/react_native/status.cljs
  src/status_im/add_new/core.cljs
  src/status_im/contact/block.cljs
  src/status_im/events.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/ui/screens/appearance/views.cljs
  src/status_im2/config.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/shell/animation.cljs
  src/status_im2/contexts/shell/events.cljs
  src/status_im2/contexts/shell/view.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/events.cljs
  src/status_im2/navigation/roots.cljs
  src/status_im2/subs/home.cljs
Labels: Tested - OK, request-manual-qa

#14868 Tests/pinned mess previews
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_chats_m.py
  test/appium/tests/medium/test_single_device.py
  test/appium/views/chat_view.py
Labels: tests

#14799 Refactor mock data out of community page
  src/quo2/components/avatars/channel_avatar.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/communities/overview/style.cljs
  src/status_im2/contexts/communities/overview/utils.cljs
  src/status_im2/contexts/communities/overview/utils_test.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
  translations/en.json
Labels: e2e test blocker, refactoring, request-manual-qa

#14783 Add blur overlay for bottom tabs and shell top nav
  android/app/src/main/java/im/status/ethereum/MainApplication.java
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  package.json
  src/quo2/components/navigation/bottom_nav_tab.cljs
  src/status_im2/contexts/shell/animation.cljs
  src/status_im2/contexts/shell/bottom_tabs.cljs
  src/status_im2/contexts/shell/cards/view.cljs
  src/status_im2/contexts/shell/style.cljs
  src/status_im2/contexts/shell/view.cljs
  src/status_im2/subs/shell.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#14873 [#14718] Fix profile photo in several places
  src/react_native/fast_image.cljs
Labels: Tested - OK, request-manual-qa

#14895 fix home-screen half-width
  src/status_im2/contexts/shell/view.cljs
Labels: Tested - OK, request-manual-qa

#14910 chore: add accesibility label
  src/quo2/components/list_items/channel.cljs
Labels: Tested - OK

#14914 e2e: fix communities
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
Labels: tests

#14913 [Fix][#14890] Added support for pinned message notification in reply notification
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
Labels: Tested - OK, request-manual-qa, Activity center

#14911 [#14877] No ability to type the text into textbox if image is added [#14881] Input field is hidden in composer
  src/quo2/components/record_audio/record_audio/buttons/record_button_big.cljs
  src/quo2/components/record_audio/record_audio/view.cljs
  src/react_native/core.cljs
  src/status_im2/contexts/chat/messages/composer/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/pin/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
Labels: Tested - OK, request-manual-qa

#14916 Update empty state in Activity Center
  src/status_im2/contexts/activity_center/style.cljs
  src/status_im2/contexts/activity_center/view.cljs
  translations/en.json
Labels: Activity center

#14885 fix pinned message for community channels
  src/status_im/chat/models/input.cljs
  src/status_im/ui/screens/communities/channel_details.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im/ui/screens/profile/group_chat/views.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/messages/pin/list/view.cljs
Labels: Tested - OK, request-manual-qa

#14930 e2e: fix for compressed key
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
Labels: tests

#14931 fix: crashed after local pairing
  src/status_im/utils/keychain/core.cljs
Labels: request-manual-qa

#14933 Documentation updates
  doc/README.md
  doc/TESTING.md
  doc/codebase-structure-and-guidelines.md
  doc/component-tests-overview.md
  doc/dependencies.md
  doc/export-icons.md
  doc/fdroid.md
  doc/github_badge.png
  doc/how-to-launch-e2e.md
  doc/ide-setup.md
  doc/images/codebase-structure-and-guidelines/log-settings.png
  doc/images/export-icons/export-icons.gif
  doc/images/how-to-launch-e2e/how-to-launch-e2e-1.png
  doc/images/how-to-launch-e2e/how-to-launch-e2e-2.png
  doc/images/how-to-launch-e2e/how-to-launch-e2e-3.png
  doc/images/how-to-launch-e2e/how-to-launch-e2e-4.png
  doc/images/ide-setup/10_REPL_8.png
  doc/images/ide-setup/11_REPL_9.png
  doc/images/ide-setup/12_REPL_10.png
  doc/images/ide-setup/1_fake_project_file.png
  doc/images/ide-setup/2_resolve.jpeg
  doc/images/ide-setup/3_REPL_1.png
  doc/images/ide-setup/4_REPL_2.png
  doc/images/ide-setup/5_REPL_3.png
  doc/images/ide-setup/6_REPL_4.png
  doc/images/ide-setup/7_REPL_5.png
  doc/images/ide-setup/8_REPL_6.png
  doc/images/ide-setup/9_REPL_7.png
  doc/images/pipeline-process/automation-checks.png
  doc/merging-pr-process.md
  doc/new-guidelines.md
  doc/pipeline_process.md
  doc/post-mortem.md
  doc/release-checklist.md
  doc/release-guide.md
  doc/starting-guide.md
  doc/testing.md
  doc/troubleshooting.md
Labels: docs

#14935 fix some of the app elements periodically stop responding on the android
  src/quo/components/list/item.cljs
  src/quo/gesture_handler.cljs
  src/status_im/ui/screens/signing/views.cljs
  src/status_im/ui2/screens/chat/components/edit/view.cljs
Labels: Tested - OK, request-manual-qa

#14874 chore: fix sorting of pinned messages
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
Labels: Tested - OK, request-manual-qa

#14878 [Fixes: #14834] Fix backup of contacts
  src/status_im/transport/message/core.cljs
  src/status_im/ui/screens/profile/contact/views.cljs
  src/status_im2/contexts/activity_center/notification/contact_request/view.cljs
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  status-go-version.json
Labels: Tested - Issues, request-manual-qa

#14761 fix community join buttons hiding after joining
  src/status_im/communities/core.cljs
  src/status_im/ui/screens/communities/community.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa
