Repository status-im/status-mobile, pull requests merged in 2023-03, with the labels that each got.

#15168 Improve QR code Handler mobile side PR
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15130 feat: add bottom sheet to see community rules
  src/status_im2/contexts/communities/menus/community_options/view.cljs
  src/status_im2/contexts/communities/menus/community_rules_list/style.cljs
  src/status_im2/contexts/communities/menus/community_rules_list/view.cljs
  src/status_im2/contexts/communities/menus/generic_menu/style.cljs
  src/status_im2/contexts/communities/menus/generic_menu/view.cljs
  src/status_im2/contexts/communities/menus/leave/style.cljs
  src/status_im2/contexts/communities/menus/leave/view.cljs
  src/status_im2/contexts/communities/menus/request_to_join/style.cljs
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  src/status_im2/contexts/communities/menus/see_rules/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#15177 quo2 strength divider component
  src/mocks/js_dependencies.cljs
  src/quo2/components/dividers/strength_divider/component_spec.cljs
  src/quo2/components/dividers/strength_divider/style.cljs
  src/quo2/components/dividers/strength_divider/view.cljs
  src/quo2/core.cljs
  src/quo2/core_spec.cljs
  src/react_native/svg.cljs
  src/status_im2/contexts/communities/menus/community_options/component_spec.cljs
  src/status_im2/contexts/quo_preview/dividers/strength_divider.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/test_helpers/component.cljs
  test/jest/jestSetup.js
  translations/en.json
Labels: external

#15036 14861 improve chat avatar
  resources/images/mock/ring.png
  src/quo2/components/avatars/user_avatar.cljs
  src/quo2/components/list_items/user_list.cljs
  src/quo2/components/profile/profile_card/view.cljs
  src/quo2/components/profile/select_profile/view.cljs
  src/status_im/react_native/resources.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/chat/home/chat_list_item/view.cljs
  src/status_im2/contexts/chat/messages/content/deleted/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/contexts/quo_preview/avatars/user_avatar.cljs
  src/status_im2/contexts/shell/cards/view.cljs
Labels: Tested - OK

#15224 move profile tab
  src/status_im/browser/core.cljs
  src/status_im/ui/screens/browser/stack.cljs
  src/status_im/ui/screens/browser/styles.cljs
  src/status_im/ui/screens/browser/tabs/views.cljs
  src/status_im/ui/screens/browser/views.cljs
  src/status_im/ui/screens/profile/user/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im2/common/home/view.cljs
  src/status_im2/contexts/shell/home_stack.cljs
  src/status_im2/subs/root.cljs
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
  test/appium/views/base_view.py
Labels: request-manual-qa

#15197 feat: support community that all members allowed to pin
  src/status_im/communities/core.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/subs/chat/messages.cljs
Labels: Tested - OK

#15225 Make popover delay configurable
  src/status_im/popover/core.cljs
  src/status_im2/contexts/activity_center/events.cljs
Labels: UI/UX improvements, Activity center

#15189 [15127] Make reply react on edit
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/contexts/chat/messages/content/pin/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/pin/banner/view.cljs
Labels: Tested - OK, request-manual-qa

#15108 chore: separate resources for old and new ui
  resources/images/mock2/coinbase@2x.png
  resources/images/mock2/collectible.png
  resources/images/mock2/community-banner@2x.png
  resources/images/mock2/community-cover.png
  resources/images/mock2/community-logo@2x.png
  resources/images/mock2/gif@2x.png
  resources/images/mock2/photo1@2x.png
  resources/images/mock2/photo2@2x.png
  resources/images/mock2/photo3@2x.png
  resources/images/mock2/ring.png
  resources/images/mock2/small_opt_card_icon.png
  resources/images/mock2/small_opt_card_main.png
  resources/images/mock2/status-logo.png
  resources/images/mock2/sticker@2x.png
  resources/images/mock2/user_picture_female2@2x.png
  resources/images/mock2/user_picture_male4@2x.png
  resources/images/mock2/user_picture_male5@2x.png
  resources/images/ui2/add-contact@2x.png
  resources/images/ui2/add-contact@3x.png
  resources/images/ui2/lifestyle@2x.png
  resources/images/ui2/lifestyle@3x.png
  resources/images/ui2/music@2x.png
  resources/images/ui2/music@3x.png
  resources/images/ui2/podcasts@2x.png
  resources/images/ui2/podcasts@3x.png
  resources/images/ui2/sync-new-device-cover-background@2x.png
  resources/images/ui2/sync-new-device-cover-background@3x.png
  resources/images/ui2/welcome-1.png
  resources/images/ui2/welcome-1@2x.png
  src/status_im/react_native/resources.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/quo_preview/avatars/user_avatar.cljs
  src/status_im2/contexts/quo_preview/community/community_card_view.cljs
  src/status_im2/contexts/quo_preview/community/data.cljs
  src/status_im2/contexts/quo_preview/community/token_gating.cljs
  src/status_im2/contexts/quo_preview/drawers/permission_drawers.cljs
  src/status_im2/contexts/quo_preview/list_items/preview_lists.cljs
  src/status_im2/contexts/quo_preview/messages/system_message.cljs
  src/status_im2/contexts/quo_preview/onboarding/small_option_card.cljs
  src/status_im2/contexts/quo_preview/profile/collectible.cljs
  src/status_im2/contexts/quo_preview/profile/profile_card.cljs
  src/status_im2/contexts/quo_preview/profile/select_profile.cljs
  src/status_im2/contexts/quo_preview/switcher/switcher_cards.cljs
  src/status_im2/contexts/quo_preview/tags/context_tags.cljs
  src/status_im2/contexts/quo_preview/tags/permission_tag.cljs
  src/status_im2/contexts/quo_preview/tags/tag.cljs
  src/status_im2/contexts/quo_preview/tags/tags.cljs
  src/status_im2/contexts/quo_preview/tags/token_tag.cljs
  src/status_im2/contexts/quo_preview/wallet/token_overview.cljs
  src/status_im2/contexts/syncing/sheets/sync_device_notice/view.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#15232 Fix freeze to open AC
  src/status_im2/contexts/activity_center/events.cljs
Labels: bug, Activity center

#15208 Album Reactions
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/contexts/chat/messages/content/reactions/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
Labels: Tested - OK, images

#15226 ios: fix xcode using system Node.js version
  ios/StatusIm.xcodeproj/project.pbxproj
  nix/mobile/ios/default.nix
  nix/mobile/ios/shells/nodejs.nix
Labels: ios, nix

#15010 feat: remove wallet connect 1.0
  package.json
  src/status_im/events.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/multiaccounts/logout/core.cljs
  src/status_im/qr_scanner/core.cljs
  src/status_im/ui/screens/wallet/manage_connections/views.cljs
  src/status_im/ui/screens/wallet_connect/session_proposal/views.cljs
  src/status_im/utils/wallet_connect_legacy.cljs
  src/status_im/wallet/choose_recipient/core.cljs
  src/status_im/wallet_connect_legacy/core.cljs
  src/status_im2/subs/root.cljs
Labels: feature

#15216 Redesign and simplify Activity Center app db
  src/status_im/data_store/activities.cljs
  src/status_im/data_store/activities_test.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/view.cljs
  src/status_im2/contexts/activity_center/view.cljs
  src/status_im2/contexts/contacts/events.cljs
  src/status_im2/subs/activity_center.cljs
  src/status_im2/subs/activity_center_test.cljs
Labels: Tested - OK, performance, refactoring, request-manual-qa, Activity center

#15175 Landscape Mode
  package.json
  src/mocks/js_dependencies.cljs
  src/react_native/gesture.cljs
  src/react_native/orientation.cljs
  src/react_native/reanimated.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/lightbox/bottom_view.cljs
  src/status_im2/contexts/chat/lightbox/common.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/constants.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/style.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/utils.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/subs/root.cljs
  yarn.lock
Labels: Tested - OK, feature, images, Animations

#15239 Fix Activity Center popover not opening
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
Labels: bug, Tested - OK, request-manual-qa

#15245 Use new RPC endpoints to fetch and count unread notifications
  src/status_im/data_store/activities.cljs
  src/status_im/data_store/activities_test.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
  status-go-version.json
  yarn.lock
Labels: performance, chore

#15234 [Fix] Community Context for Mention or Replies Notification in Activi…
  status-go-version.json
Labels: bug, Tested - OK, request-manual-qa, Activity center

#15250 nix: refactor Gradle deps to be more generic
  nix/deps/gradle/README.md
  nix/deps/gradle/add_package.sh
  nix/deps/gradle/default.nix
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/deps/gradle/get_deps.sh
  nix/deps/gradle/get_projects.sh
  nix/deps/gradle/proj.list
  nix/deps/gradle/url2json.sh
Labels: android, nix, dependencies

#15252 nix: patch all Gradle configs of nodejs deps
  nix/deps/nodejs-patched/default.nix
  nix/pkgs/patch-maven-srcs/default.nix
Labels: android, nix, dependencies

#15243 Lightbox improvements
  src/status_im2/constants.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/lightbox/bottom_view.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/style.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/utils.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/navigation/screens.cljs
  src/status_im2/subs/root.cljs
Labels: images

#15095 replaced mocked community-tags and banner data with real data
  src/quo2/components/community/community_card_view.cljs
  src/quo2/components/community/community_view.cljs
  src/quo2/components/community/style.cljs
  src/quo2/components/tags/base_tag.cljs
  src/quo2/components/tags/tag.cljs
  src/quo2/components/tags/tags.cljs
  src/status_im2/common/scroll_page/view.cljs
  src/status_im2/contexts/communities/discover/style.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/contexts/quo_preview/tags/tags.cljs
Labels: Tested - OK, request-manual-qa

#15127 New intro screen
  resources/images/ui2/intro-1@2x.png
  resources/images/ui2/intro-1@3x.png
  resources/images/ui2/intro-2@2x.png
  resources/images/ui2/intro-2@3x.png
  resources/images/ui2/intro-3@2x.png
  resources/images/ui2/intro-3@3x.png
  resources/images/ui2/intro-4@2x.png
  resources/images/ui2/intro-4@3x.png
  src/quo2/components/drawers/drawer_buttons/style.cljs
  src/quo2/components/drawers/drawer_buttons/view.cljs
  src/status_im/ui/screens/onboarding/intro/styles.cljs
  src/status_im/ui/screens/onboarding/intro/views.cljs
  src/status_im/ui/screens/screens.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/onboarding/common/intro/style.cljs
  src/status_im2/contexts/onboarding/common/intro/view.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/roots.cljs
  src/status_im2/navigation/screens.cljs
  test/appium/views/sign_in_view.py
  translations/en.json
Labels: Tested - OK

#15273 [#15241] Proper system message on being not a member of a group
  src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  translations/en.json
Labels: Tested - OK

#15256 feat: allow group admin to delete others message
  status-go-version.json
Labels: request-manual-qa

#15190 [15166] Show message edited status
  src/status_im2/contexts/chat/messages/content/text/style.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/contexts/chat/messages/content/view.cljs
  src/status_im2/contexts/chat/messages/link_preview/view.cljs
Labels: Tested - OK, request-manual-qa

#15278 e2e: block contact
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_chats_m.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: tests

#15285 fix mention turns into unknown in community
  src/status_im/multiaccounts/core.cljs
  src/status_im/ui/screens/chat/components/input.cljs
Labels: Tested - OK

#15295 e2e: nightly fix
  test/appium/support/testrail_report.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/base_view.py
Labels: tests

#15296 ios: direct logs to ios/logs, archive on failure
  .gitignore
  ci/Jenkinsfile.ios
  fastlane/Fastfile
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: ios, devops

#15294 e2e: test_community_mentions_push_notification
  test/appium/tests/base_test_case.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/views/base_element.py
  test/appium/views/chat_view.py
Labels: tests

#15282 Status Tag UI and usage update
  resources/images/icons2/12x12/negative-state@2x.png
  resources/images/icons2/12x12/negative-state@3x.png
  resources/images/icons2/12x12/pending-dark-blur@2x.png
  resources/images/icons2/12x12/pending-dark-blur@3x.png
  resources/images/icons2/12x12/pending-dark@2x.png
  resources/images/icons2/12x12/pending-dark@3x.png
  resources/images/icons2/12x12/pending-light@2x.png
  resources/images/icons2/12x12/pending-light@3x.png
  resources/images/icons2/12x12/positive-state@2x.png
  resources/images/icons2/12x12/positive-state@3x.png
  resources/images/icons2/20x20/negative-state@2x.png
  resources/images/icons2/20x20/negative-state@3x.png
  resources/images/icons2/20x20/pending-dark-blur@2x.png
  resources/images/icons2/20x20/pending-dark-blur@3x.png
  resources/images/icons2/20x20/pending-dark@2x.png
  resources/images/icons2/20x20/pending-dark@3x.png
  resources/images/icons2/20x20/pending-light@2x.png
  resources/images/icons2/20x20/pending-light@3x.png
  resources/images/icons2/20x20/positive-state@2x.png
  resources/images/icons2/20x20/positive-state@3x.png
  src/quo2/components/notifications/activity_log/view.cljs
  src/quo2/components/tags/__tests__/status_tags_component_spec.cljs
  src/quo2/components/tags/status_tags.cljs
  src/quo2/core_spec.cljs
  src/quo2/foundations/colors.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/view.cljs
  src/status_im2/contexts/quo_preview/notifications/activity_logs.cljs
  src/status_im2/contexts/quo_preview/preview.cljs
  src/status_im2/contexts/quo_preview/tags/status_tags.cljs
Labels: Tested - OK, feature, request-manual-qa, Activity center, new-design [quo2]

#15110 15018 im new to status screen
  resources/images/ui2/ethereum_address@2x.png
  resources/images/ui2/ethereum_address@3x.png
  resources/images/ui2/generate_keys@3x.png
  resources/images/ui2/keycard@2x.png
  resources/images/ui2/keycard@3x.png
  resources/images/ui2/onboarding_blur_bg@2x.png
  resources/images/ui2/onboarding_blur_bg@3x.png
  src/quo2/components/navigation/page_nav.cljs
  src/quo2/components/onboarding/small_option_card/style.cljs
  src/quo2/components/onboarding/small_option_card/view.cljs
  src/status_im2/common/resources.cljs
  src/status_im2/contexts/onboarding/common/intro/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/style.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/navigation/roots.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
Labels: Tested - Issues, request-manual-qa

#15135 Prevent #links to work except in community chats and allow redirection from channel to another when clicked
  src/status_im/communities/core.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
  src/status_im2/subs/chat/chats.cljs
Labels: Tested - OK, request-manual-qa

#15315 feat: improve lightbox transition
  src/react_native/reanimated.cljs
  src/react_native/safe_area.cljs
  src/status_im2/contexts/chat/lightbox/animations.cljs
  src/status_im2/contexts/chat/lightbox/bottom_view.cljs
  src/status_im2/contexts/chat/lightbox/common.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/style.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/utils.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/navigation/screens.cljs
Labels: ios, images

#15070 Fetch details of user when adding a contact
  src/status_im/integration_test.cljs
  src/status_im/profile/core.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/status_im2/contexts/add_new_contact/style.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15284 Swipe gestures for Activity Center notifications with CTA
  src/quo2/components/notifications/activity_log/view.cljs
  src/status_im/events.cljs
  src/status_im2/common/bottom_sheet/view.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/activity_center/events_test.cljs
  src/status_im2/contexts/activity_center/notification/admin/view.cljs
  src/status_im2/contexts/activity_center/notification/common/style.cljs
  src/status_im2/contexts/activity_center/notification/common/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/events.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/view.cljs
  src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs
  src/status_im2/contexts/activity_center/notification/membership/view.cljs
  src/status_im2/contexts/activity_center/notification/mentions/view.cljs
  src/status_im2/contexts/activity_center/notification/reply/view.cljs
  src/status_im2/contexts/activity_center/view.cljs
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/home_view.py
Labels: bug, Tested - OK, feature, request-manual-qa, Activity center

#15280 [#15152] Show ENS name on adding contact via ENS name
  src/status_im/profile/core.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  src/status_im2/contexts/contacts/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#14973 Add ability to cancel a request to join a community
  src/status_im/communities/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/communities/menus/community_options/component_spec.cljs
  src/status_im2/contexts/communities/menus/community_options/view.cljs
  src/status_im2/contexts/communities/menus/generic_menu/view.cljs
  src/status_im2/contexts/communities/menus/leave/view.cljs
  src/status_im2/contexts/communities/menus/request_to_join/view.cljs
  src/status_im2/contexts/communities/menus/see_rules/view.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
  src/status_im2/subs/root.cljs
  translations/en.json
Labels: Tested - OK

#15307 Spacing between codeblocks and regular text + fixes for "edited at" message
  src/status_im2/contexts/chat/messages/content/text/style.cljs
  src/status_im2/contexts/chat/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa

#15349 feat: drag to dismiss lightbox
  src/js/worklets/lightbox.js
  src/mocks/js_dependencies.cljs
  src/react_native/gesture.cljs
  src/status_im2/contexts/chat/lightbox/bottom_view.cljs
  src/status_im2/contexts/chat/lightbox/constants.cljs
  src/status_im2/contexts/chat/lightbox/style.cljs
  src/status_im2/contexts/chat/lightbox/top_view.cljs
  src/status_im2/contexts/chat/lightbox/view.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/utils.cljs
  src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
  src/status_im2/navigation/screens.cljs
  src/utils/worklets/lightbox.cljs
Labels: images

#15361 e2e: minor fixes
  test/appium/requirements.txt
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/home_view.py
Labels: tests

#15353 Bugfixes for the style of "New to Status" screen
  src/quo2/components/onboarding/small_option_card/style.cljs
  src/quo2/components/onboarding/small_option_card/view.cljs
  src/status_im2/contexts/onboarding/common/intro/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/quo_preview/drawers/drawer_buttons.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15313 refactor: chat message list context related
  src/status_im2/contexts/chat/messages/drawers/view.cljs
  src/status_im2/contexts/chat/messages/list/view.cljs
  src/status_im2/contexts/chat/messages/pin/list/view.cljs
  src/status_im2/contexts/chat/messages/view.cljs
  src/status_im2/subs/chat/chats.cljs
  src/status_im2/subs/chat/chats_test.cljs
Labels: Tested - OK

#15317 ios: upgrade Cocoapods to 1.12.0, drop ancient fix
  fastlane/Gemfile.lock
  fastlane/gemset.nix
  ios/Podfile
  ios/Podfile.lock
  nix/pkgs.nix
Labels: ios, dependencies

#15306 Add collapsing of categories
  src/quo2/components/dividers/divider_label.cljs
  src/status_im/communities/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/ui/screens/communities/views.cljs
  src/status_im/ui/screens/home/sheet/views.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/config.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/communities/overview/view.cljs
  src/status_im2/subs/communities.cljs
  src/status_im2/subs/communities_test.cljs
  src/status_im2/subs/root.cljs
  status-go-version.json
Labels: Tested - OK

#15286 fix: mark :albumize? true when rebuild message
  src/status_im/chat/models/loading.cljs
  src/status_im2/contexts/chat/messages/list/events.cljs
Labels: Tested - OK, request-manual-qa

#15382 Long quoted message in the reply box is not cut, goes beyond reply box and overlapped by cancel button
  src/status_im/ui2/screens/chat/components/reply/style.cljs
  src/status_im/ui2/screens/chat/components/reply/view.cljs
Labels: Tested - OK

#15163 [#14622] Show ugly network state icons and connection bottom sheet
  src/status_im2/common/home/view.cljs
Labels: Tested - OK

#15334 chore: add skeleton flow for onboarding
  src/quo2/components/onboarding/small_option_card/view.cljs
  src/status_im2/contexts/onboarding/common/background/style.cljs
  src/status_im2/contexts/onboarding/common/background/view.cljs
  src/status_im2/contexts/onboarding/create_password/style.cljs
  src/status_im2/contexts/onboarding/create_password/view.cljs
  src/status_im2/contexts/onboarding/create_profile/style.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im2/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im2/contexts/onboarding/enable_notifications/style.cljs
  src/status_im2/contexts/onboarding/enable_notifications/view.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
  src/status_im2/navigation/screens.cljs
  test/appium/views/sign_in_view.py
Labels: Tested - OK, request-manual-qa

#15148 Messages don't get "sent" status when sent while internet is off
  status-go-version.json
Labels: Tested - OK

#15394 e2e: mentions, replies, accept on swipe, filters, mark all as read
  test/appium/tests/medium/test_activity_center.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#15420 set signing to auto for IOS debug builds [Xcode]
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: Tested - OK

#15404 chore: add skeleton for sign in with syncing flow
  src/status_im2/contexts/onboarding/common/intro/view.cljs
  src/status_im2/contexts/onboarding/sign_in/style.cljs
  src/status_im2/contexts/onboarding/sign_in/view.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/style.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/view.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK

#15422 Remove 100ms delay when opening image
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/messages/content/album/view.cljs
  src/status_im2/contexts/chat/messages/content/image/view.cljs
Labels: Tested - OK, performance

#15411 nix: unpatched Node modules for Gradle deps update
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.urls
  nix/deps/gradle/gradle_parser.awk
  nix/shells.nix
Labels: android, nix, dependencies

#15415 Remove support for cancelling outgoing contact requests
  src/status_im2/contexts/activity_center/notification/contact_requests/events.cljs
  src/status_im2/contexts/activity_center/notification/contact_requests/view.cljs
  status-go-version.json
Labels: Tested - OK, feature, Activity center, E:MutualContacts

#15424 fix: reply with album
  src/status_im/chat/models/input.cljs
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
Labels: Tested - OK, request-manual-qa

#15439 fix: still need this fix to run-ios on m1 mac
  ios/Podfile
Labels: ios, developer-xp

#15399 feat: bottom sheet screen
  src/quo2/foundations/colors.cljs
  src/react_native/hooks.cljs
  src/react_native/reanimated.cljs
  src/status_im2/common/bottom_sheet_screen/style.cljs
  src/status_im2/common/bottom_sheet_screen/view.cljs
  src/status_im2/contexts/chat/messages/composer/controls/view.cljs
  src/status_im2/contexts/chat/photo_selector/style.cljs
  src/status_im2/contexts/chat/photo_selector/view.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, navigation

#15192 Add validation for when adding a contact
  src/status_im/mobile_sync_settings/core.cljs
  src/status_im2/contexts/add_new_contact/events.cljs
  src/status_im2/contexts/add_new_contact/events_test.cljs
  src/status_im2/contexts/add_new_contact/style.cljs
  src/status_im2/contexts/add_new_contact/views.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#15449 e2e: activity center adjstments and minor improvements
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
Labels: tests

#15426 Fix for sender's name, profile icon, chat key, timestamp being lost for messages that contain images
  src/status_im2/subs/chat/messages.cljs
  src/status_im2/subs/chat/messages_test.cljs
Labels: Tested - OK

#15412 changes corresponding to refactor of local pair of status-go (PR #3248)
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im2/contexts/syncing/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15454 remove navigate-to-nav2 event
  src/status_im/communities/core.cljs
  src/status_im/group_chats/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/ui/screens/communities/views.cljs
  src/status_im/ui2/screens/chat/messages/message.cljs
  src/status_im2/contexts/chat/events.cljs
  src/status_im2/contexts/chat/events_test.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/communities/home/view.cljs
  src/status_im2/contexts/shell/animation.cljs
  src/status_im2/core.cljs
  src/status_im2/navigation/events.cljs
  src/status_im2/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#15460 e2e: communities fixes
  test/appium/support/testrail_report.py
  test/appium/tests/critical/test_public_chat_browsing.py
  test/appium/tests/medium/test_activity_center.py
  test/appium/tests/medium/test_deeplink_chat_share_profile.py
  test/appium/views/chat_view.py
Labels: tests

#15452 Add restore from seed phrase new flow
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  src/status_im/ethereum/mnemonic.cljs
  src/status_im/native_module/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/onboarding/create_profile/view.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/style.cljs
  src/status_im2/contexts/onboarding/enter_seed_phrase/view.cljs
  src/status_im2/contexts/onboarding/events.cljs
  src/status_im2/contexts/onboarding/new_to_status/view.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/screens.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15416 Onboarding - Sign in by scanning sync QR code
  package.json
  src/quo2/components/tabs/segmented_tab.cljs
  src/quo2/components/tabs/tab/view.cljs
  src/quo2/core.cljs
  src/react_native/camera_kit.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/signals/core.cljs
  src/status_im2/constants.cljs
  src/status_im2/contexts/onboarding/sign_in/style.cljs
  src/status_im2/contexts/onboarding/sign_in/view.cljs
  src/status_im2/contexts/onboarding/syncing/syncing_devices/view.cljs
  src/status_im2/contexts/quo_preview/tabs/segmented_tab.cljs
  src/status_im2/contexts/syncing/events.cljs
  src/status_im2/navigation/roots.cljs
  src/status_im2/navigation/screens.cljs
  translations/en.json
  yarn.lock
Labels: Tested - OK, feature, onboarding

#15455 Refactor app theme management
  src/status_im/events.cljs
  src/status_im/multiaccounts/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/theme/core.cljs
  src/status_im2/common/theme/core.cljs
  src/status_im2/contexts/quo_preview/main.cljs
  src/status_im2/events.cljs
  src/status_im2/navigation/core.cljs
  src/status_im2/navigation/roots.cljs
Labels: Tested - OK

#15474 Fix necessity to tap twice in mentions suggestion list component
  src/status_im2/contexts/chat/messages/composer/view.cljs
Labels: Tested - OK, request-manual-qa

#15468 Improve REPL-Driven Development with Component tests
  shadow-cljs.edn
  src/test_helpers/component.cljs
Labels: chore

#15488 fix login/forget password button overlaps password input
  src/status_im2/contexts/onboarding/profiles/style.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: Tested - OK, request-manual-qa

#15472 Center input value within the field
  src/quo2/components/inputs/input/style.cljs
Labels: Tested - OK

#15464 fix: App crashes on syncing QR of the account
  status-go-version.json
Labels: Tested - OK

#15484 Add accessibility label for community options button
  src/quo2/components/navigation/page_nav.cljs
  src/status_im2/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#15496 fix: disable edit image message until it's implemented
  src/status_im2/contexts/chat/messages/drawers/view.cljs
Labels: Tested - OK

#15517 Add guidelines for defining styles with apply-animations-to-style
  doc/new-guidelines.md
Labels: docs

#15506 Scrollable list of pinned messages
  src/status_im2/common/bottom_sheet/sheets.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/style.cljs
  src/status_im2/contexts/chat/menus/pinned_messages/view.cljs
  src/status_im2/contexts/chat/messages/pin/list/view.cljs
  test/appium/views/chat_view.py
Labels: Tested - OK

#15502 fix: crash on wallet view
  src/status_im2/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#15503 fix #15478
  src/status_im/node/core.cljs
  src/status_im2/contexts/syncing/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15495 Profile biometrics
  src/status_im/multiaccounts/biometric/core.cljs
  src/status_im/multiaccounts/login/core.cljs
  src/status_im/utils/keychain/core.cljs
  src/status_im2/contexts/onboarding/events.cljs
Labels: Tested - OK, request-manual-qa

#15407 Allow/Add mobile link previews for YouTube and Twitter
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#15537 fix display name issues
  src/status_im/multiaccounts/core.cljs
  src/status_im2/contexts/activity_center/events.cljs
  src/status_im2/contexts/onboarding/profiles/view.cljs
Labels: Tested - OK

#15450 chore: update to new ui on intro screen of syncing
  src/quo2/components/tags/status_tags.cljs
  src/status_im2/contexts/syncing/style.cljs
  src/status_im2/contexts/syncing/styles.cljs
  src/status_im2/contexts/syncing/view.cljs
  src/status_im2/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#15342 Bug/communities missing data
  src/quo2/components/community/community_card_view.cljs
  src/quo2/components/community/community_list_view.cljs
  src/quo2/components/community/community_view.cljs
  src/quo2/components/community/style.cljs
  src/status_im2/contexts/communities/discover/style.cljs
  src/status_im2/contexts/communities/discover/view.cljs
  src/status_im2/contexts/quo_preview/tags/tag.cljs
Labels: Tested - OK, request-manual-qa
