Repository status-im/status-mobile, pull requests merged in 2024-03, with the labels that each got.

#18930 Fix account edit confirmation button
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/contexts/wallet/add_address_to_watch/confirm_address/view.cljs
  src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/style.cljs
  src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs
  src/status_im/contexts/wallet/edit_account/view.cljs
Labels: Tested - OK, request-manual-qa

#19028 [#18963] feat: actions UI for stranger contact profile
  src/status_im/contexts/profile/contact/actions/view.cljs
  src/status_im/contexts/profile/contact/view.cljs
  translations/en.json
Labels: skip-manual-qa

#18887 feat: update transaction confirmation page to support bridging txs
  src/quo/components/wallet/summary_info/view.cljs
  src/quo/foundations/resources.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/account/bridge_send/view.cljs
  src/status_im/contexts/wallet/common/utils/send.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/subs/wallet/networks.cljs
  src/status_im/subs/wallet/networks_test.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases added

#19080 fix settings navigation
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
  src/legacy/status_im/ui/screens/profile/user/views.cljs
  src/status_im/contexts/shell/jump_to/view.cljs
  src/status_im/contexts/syncing/setup_syncing/style.cljs
  src/status_im/contexts/syncing/setup_syncing/view.cljs
  src/status_im/contexts/syncing/syncing_devices_list/view.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#18767 Add Promesa to simplify working with promises
  .clj-kondo/funcool/promesa/config.edn
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/react_native/core.cljs
  src/react_native/image_resizer.cljs
  src/status_im/contexts/chat/messenger/photo_selector/effects.cljs
Labels: Tested - OK, request-manual-qa

#18919 Account selection: Use bottom sheet component
  src/quo/components/settings/category/reorder/view.cljs
  src/status_im/common/bottom_sheet/style.cljs
  src/status_im/common/bottom_sheet/view.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/style.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Bug MVP, E:Mobile [Crew] Account Selection MVP

#18731 Added destructuring section to new-guidelines.md
  src/quo/README.md
Labels: external, E:Mobile Developer XP

#18897 Fix collectible/token icon and name on addresses for permissions screen
  src/quo/components/wallet/account_permissions/view.cljs
  src/quo/components/wallet/required_tokens/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
Labels: Tested - OK, request-manual-qa

#18895 chore(wallet): some minor cleanups, move sheets to appropriate level,…
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/common/sheets/select_account/style.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/contexts/wallet/edit_account/view.cljs
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/share_address/view.cljs
  src/status_im/contexts/wallet/sheets/account_options/style.cljs
  src/status_im/contexts/wallet/sheets/account_options/view.cljs
  src/status_im/contexts/wallet/sheets/account_origin/style.cljs
  src/status_im/contexts/wallet/sheets/account_origin/view.cljs
  src/status_im/contexts/wallet/sheets/network_filter/view.cljs
  src/status_im/contexts/wallet/sheets/network_preferences/style.cljs
  src/status_im/contexts/wallet/sheets/network_preferences/view.cljs
  src/status_im/contexts/wallet/sheets/remove_account/style.cljs
  src/status_im/contexts/wallet/sheets/remove_account/view.cljs
  src/status_im/contexts/wallet/sheets/select_account/style.cljs
  src/status_im/contexts/wallet/sheets/select_account/view.cljs
Labels: Tested - OK, request-manual-qa

#19025 Make integration tests more enjoyable to use
  .clj-kondo/config.edn
  .zprintrc
  src/test_helpers/integration.cljs
  src/tests/integration_test/chat_test.cljs
  src/tests/integration_test/core_test.cljs
  src/tests/integration_test/profile_test.cljs
  src/utils/re_frame.cljs
Labels: E:Mobile Developer XP, E:Mobile Integration Tests, skip-manual-qa

#18922 Fix: slide button
  src/quo/components/buttons/slide_button/view.cljs
  src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
Labels: request-manual-qa, test cases required

#19083 fix multiple set view-id events dispatched
  src/status_im/core.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/effects.cljs
Labels: skip-manual-qa

#18998 [#18964] Support custom message when sending contact request
  src/status_im/contexts/chat/contacts/events.cljs
  src/status_im/contexts/chat/contacts/events_test.cljs
Labels: Tested - OK, request-manual-qa

#18906 Add peer syncing toggle in "Advanced settings"
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/subs/profile.cljs
Labels: Tested - OK, request-manual-qa, status-go

#18923 Updated placeholder for no pinned messages in chat
  src/status_im/contexts/chat/messenger/menus/pinned_messages/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#19075 Add status tag for pending contact request to contact profile
  src/status_im/contexts/profile/contact/header/style.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  translations/en.json
Labels: skip-manual-qa

#19076 fix the mention highlighted area is only updated after reopening the chat
  src/status_im/contexts/chat/messenger/messages/content/text/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa

#19104 fix Blink of shell screen occurs when the Scan sync button is tapped
  src/status_im/contexts/syncing/setup_syncing/view.cljs
Labels: Tested - OK, request-manual-qa

#18914 fix(style): :resize-method is not avaliable on ios
  src/react_native/core.cljs
Labels: Tested - OK, request-manual-qa

#19040 [Chore] Remove POKT Sepolia and Goerli RPC URL
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#18812 Sort communities by currently active tab
  src/status_im/contexts/chat/messenger/messages/link_preview/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/subs/communities.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#18955 chore(wallet): remove legacy network settings options
  src/legacy/status_im/browser/core.cljs
  src/legacy/status_im/browser/eip3085.cljs
  src/legacy/status_im/network/core.cljs
  src/legacy/status_im/network/core_test.cljs
  src/legacy/status_im/subs/networks.cljs
  src/legacy/status_im/subs/root.cljs
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
  src/legacy/status_im/ui/screens/network/edit_network/styles.cljs
  src/legacy/status_im/ui/screens/network/edit_network/views.cljs
  src/legacy/status_im/ui/screens/network/network_details/views.cljs
  src/legacy/status_im/ui/screens/network/styles.cljs
  src/legacy/status_im/ui/screens/network/views.cljs
  src/legacy/status_im/ui/screens/network_info/views.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  test/appium/views/profile_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#18850 [Feature] Wallet - Handle blockchain status
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/signals.cljs
  src/utils/money.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19032 [#18985] Polish group details view
  src/legacy/status_im/contact/db.cljs
  src/quo/components/community/channel_actions.cljs
  src/quo/components/community/style.cljs
  src/quo/components/gradient/gradient_cover/style.cljs
  src/quo/components/navigation/page_nav/view.cljs
  src/quo/components/share/share_qr_code/view.cljs
  src/status_im/common/bottom_sheet/view.cljs
  src/status_im/contexts/chat/group_details/style.cljs
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/communities/actions/share_community_channel/style.cljs
  src/status_im/contexts/preview/quo/gradient/gradient_cover.cljs
  src/status_im/contexts/preview/quo/preview.cljs
  src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/style.cljs
  src/status_im/contexts/wallet/create_account/style.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/contexts/wallet/sheets/account_options/view.cljs
Labels: Tested - OK, request-manual-qa, design-review-required

#19085 [#19037] feat: new design for manage nickname
  src/status_im/common/validation/profile.cljs
  src/status_im/contexts/profile/contact/actions/view.cljs
  src/status_im/contexts/profile/contact/add_nickname/style.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
  src/status_im/contexts/profile/contact/view.cljs
  translations/en.json
Labels: skip-manual-qa

#18921 [#18608] Collectibles fetching performance
  src/quo/components/profile/collectible/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events/collectibles.cljs
  src/status_im/contexts/wallet/events_test.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/subs/wallet/collectibles.cljs
  src/utils/transforms.cljs
Labels: Tested - OK, request-manual-qa

#19127 Update `status-go` version to fix the issue with peer syncing migration
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#18987 [#18929] fix: no bottom space under the join button
  src/status_im/contexts/communities/actions/accounts_selection/style.cljs
Labels: Tested - OK, request-manual-qa

#19043 [#18736] add address to watch using an ENS
  src/status_im/contexts/wallet/accounts/add_account/address_to_watch/events.cljs
  src/status_im/contexts/wallet/add_address_to_watch/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/subs/wallet/add_account/address_to_watch.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#19139 [#19048] feat: show contact QR code
  src/quo/components/share/share_qr_code/schema.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/profile/contact/actions/view.cljs
  src/status_im/contexts/profile/contact/share/style.cljs
  src/status_im/contexts/profile/contact/share/view.cljs
  src/status_im/navigation/screens.cljs
Labels: skip-manual-qa

#19154 [#19101] feat: share contact profile
  src/react_native/core.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/profile/contact/actions/view.cljs
Labels: skip-manual-qa

#19119 Implement reviewal of contact requests from contact profile
  src/quo/components/inputs/locked_input/style.cljs
  src/quo/components/inputs/locked_input/view.cljs
  src/status_im/contexts/profile/contact/contact_request/view.cljs
  src/status_im/contexts/profile/contact/contact_review/style.cljs
  src/status_im/contexts/profile/contact/contact_review/view.cljs
  src/status_im/contexts/profile/contact/header/style.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  src/status_im/subs/activity_center.cljs
  src/status_im/subs/activity_center_test.cljs
  translations/en.json
Labels: skip-manual-qa

#18756 Clean up biometrics and standard-auth and add tests
  src/legacy/status_im/events.cljs
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/react_native/biometrics.cljs
  src/schema/common.cljs
  src/status_im/common/biometric/effects.cljs
  src/status_im/common/biometric/events.cljs
  src/status_im/common/biometric/events_test.cljs
  src/status_im/common/biometric/utils.cljs
  src/status_im/common/standard_authentication/events.cljs
  src/status_im/common/standard_authentication/events_schema.cljs
  src/status_im/common/standard_authentication/password_input/view.cljs
  src/status_im/common/standard_authentication/standard_auth/authorize.cljs
  src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/onboarding/welcome/style.cljs
  src/status_im/contexts/onboarding/welcome/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/settings/screens/password/view.cljs
  src/status_im/events.cljs
  src/status_im/subs/biometrics.cljs
  src/status_im/subs/root.cljs
  src/tests/integration_test/standard_auth_test.cljs
Labels: Tested - OK, request-manual-qa

#18778 chore: qualify screen keywords
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/wallet/account/bridge/view.cljs
  src/status_im/contexts/wallet/account/bridge_send/view.cljs
  src/status_im/contexts/wallet/account/bridge_to/view.cljs
  src/status_im/contexts/wallet/account/tabs/about/view.cljs
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/add_address_to_watch/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/create_account/new_keypair/check_your_backup/view.cljs
  src/status_im/contexts/wallet/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events/collectibles.cljs
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/sheets/account_options/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#19168 Add action to remove contact inside contact action menu
  src/status_im/contexts/profile/contact/actions/view.cljs
  translations/en.json
Labels: skip-manual-qa

#19166 Feature: Ignore / Dismiss contact requests from contact profile
  src/status_im/contexts/profile/contact/contact_review/view.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  translations/en.json
Labels: skip-manual-qa

#19115 Fraschetti/18343- Add contract test for wallet_getDerivedAddresses
  modules/react-native-status/nodejs/status.cpp
  src/mocks/js_dependencies.cljs
  src/test_helpers/integration.clj
  src/test_helpers/integration.cljs
  src/tests/contract_test/core_test.cljs
  src/tests/contract_test/wallet_test.cljs
  src/tests/integration_test/constants.cljs
  src/tests/integration_test/core_test.cljs
  src/tests/integration_test/profile_test.cljs
  src/tests/test_utils.cljs
Labels: E:Mobile Wallet MVP, skip-manual-qa

#19030 [#18962] Add emoji-hash and bio contact profile data
  src/status_im/contexts/chat/contacts/events.cljs
Labels: Tested - OK, request-manual-qa

#18484 feat: Add internal link preview for communities
  src/legacy/status_im/data_store/activities_test.cljs
  src/legacy/status_im/data_store/messages.cljs
  src/legacy/status_im/data_store/messages_test.cljs
  src/legacy/status_im/subs/root.cljs
  src/legacy/status_im/ui/screens/communities/invite.cljs
  src/quo/components/links/internal_link_card/community/style.cljs
  src/quo/components/links/link_preview/component_spec.cljs
  src/quo/components/links/link_preview/view.cljs
  src/quo/components/links/url_preview/style.cljs
  src/quo/components/links/url_preview/view.cljs
  src/quo/components/links/url_preview_list/view.cljs
  src/status_im/common/biometric/events_test.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/chat/messenger/composer/events.cljs
  src/status_im/contexts/chat/messenger/composer/link_preview/events.cljs
  src/status_im/contexts/chat/messenger/composer/link_preview/events_test.cljs
  src/status_im/contexts/chat/messenger/composer/link_preview/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/link_preview/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/status_link_preview/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/text/view.cljs
  src/status_im/contexts/chat/messenger/messages/transport/events.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/messages.cljs
  src/status_im/subs/messages_test.cljs
  src/tests/integration_test/standard_auth_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, followup required, test cases added

#18937 The wrong validation is applied for entered amount within send assets page #18751
  src/status_im/contexts/wallet/send/input_amount/view.cljs
Labels: Tested - OK, request-manual-qa

#19208 Migrate contract tests to new API based on promises
  .zprintrc
  src/test_helpers/integration.clj
  src/test_helpers/integration.cljs
  src/tests/contract_test/core_test.cljs
  src/tests/contract_test/profile_test.cljs
  src/tests/contract_test/utils.cljs
  src/tests/contract_test/wallet_test.cljs
  src/tests/integration_test/chat_test.cljs
  src/tests/integration_test/core_test.cljs
  src/tests/integration_test/profile_test.cljs
Labels: E:Mobile Integration Tests

#19153 cache processed description
  src/legacy/status_im/data_store/communities.cljs
  src/legacy/status_im/data_store/communities_test.cljs
  src/status_im/contexts/communities/discover/events.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/root.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#19112 fix: remove biometric button in the login screen when disabled biomet…
  src/status_im/contexts/profile/profiles/view.cljs
Labels: Tested - OK, request-manual-qa

#19068 Refactor navigation files
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
  src/status_im/navigation/options.cljs
  src/status_im/navigation/roots.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#18890 fix: duplicate sub key :communities/fetching-community
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/style.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#19005 Partial handlers update (re-frame/reg-event-fx instead of rf/defn)
  src/legacy/status_im/browser/core.cljs
  src/legacy/status_im/communities/core.cljs
  src/legacy/status_im/contact/block.cljs
  src/legacy/status_im/data_store/chats.cljs
  src/legacy/status_im/data_store/switcher_cards.cljs
  src/legacy/status_im/data_store/visibility_status_updates.cljs
  src/legacy/status_im/ethereum/transactions/core.cljs
  src/legacy/status_im/events.cljs
  src/legacy/status_im/group_chats/core.cljs
  src/legacy/status_im/mailserver/core.cljs
  src/legacy/status_im/mobile_sync_settings/core.cljs
  src/legacy/status_im/network/net_info.cljs
  src/legacy/status_im/stickers/core.cljs
  src/legacy/status_im/subs/mailservers.cljs
  src/legacy/status_im/ui/screens/default_sync_period_settings/view.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/legacy/status_im/ui/screens/profile/user/edit_picture.cljs
  src/legacy/status_im/utils/logging/core.cljs
  src/legacy/status_im/utils/mobile_sync.cljs
  src/status_im/common/log.cljs
  src/status_im/common/signals/events.cljs
  src/status_im/contexts/chat/contacts/events.cljs
  src/status_im/contexts/chat/home/add_new_contact/events.cljs
  src/status_im/contexts/chat/messenger/messages/link_preview/events.cljs
  src/status_im/contexts/profile/config.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/push_notifications/events.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/contexts/shell/activity_center/events.cljs
  src/status_im/events.cljs
  src/test_helpers/integration.cljs
Labels: Tested - OK, request-manual-qa

#19031 Fix channel-action component
  src/quo/components/community/channel_action/style.cljs
  src/quo/components/community/channel_action/view.cljs
  src/quo/components/community/channel_actions.cljs
  src/quo/components/community/channel_actions/view.cljs
  src/quo/components/community/style.cljs
  src/quo/core.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/preview/quo/community/channel_action.cljs
  src/status_im/contexts/preview/quo/community/channel_actions.cljs
  src/status_im/contexts/preview/quo/main.cljs
Labels: Tested - OK, request-manual-qa

#19241 re add progress root and popover overlay
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/roots.cljs
  src/status_im/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#19066 fix: handle limit event
  src/status_im/contexts/chat/home/new_chat/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#19248 Display discord bridged posts #19233
  src/legacy/status_im/data_store/activities_test.cljs
  src/legacy/status_im/data_store/messages.cljs
  src/legacy/status_im/data_store/messages_test.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa

#19054 fix: polish new chat
  src/quo/components/list_items/user.cljs
  src/react_native/gesture.cljs
  src/status_im/common/contact_list/style.cljs
  src/status_im/common/contact_list/view.cljs
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/chat/home/new_chat/styles.cljs
  src/status_im/contexts/chat/home/new_chat/view.cljs
  src/status_im/contexts/chat/home/view.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile [Crew] Chat Polish v2.28, design-review-required

#19275 fix keycard crash
  src/status_im/contexts/onboarding/new_to_status/view.cljs
Labels: skip-manual-qa

#19125 chore(quo): add profile - collectibles list item component
  src/quo/components/avatars/collection_avatar/style.cljs
  src/quo/components/avatars/collection_avatar/view.cljs
  src/quo/components/counter/collectible_counter/view.cljs
  src/quo/components/list_items/preview_list/view.cljs
  src/quo/components/profile/collectible_list_item/component_spec.cljs
  src/quo/components/profile/collectible_list_item/style.cljs
  src/quo/components/profile/collectible_list_item/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/quo/foundations/gradients.cljs
  src/status_im/contexts/preview/quo/avatars/collection_avatar.cljs
  src/status_im/contexts/preview/quo/foundations/gradients.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/preview/quo/profile/collectible_list_item.cljs
  translations/en.json
Labels: skip-manual-qa

#19121 feat(wallet): add ability to remove wallet account
  src/status_im/contexts/wallet/edit_account/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/contexts/wallet/sheets/account_options/view.cljs
  src/status_im/contexts/wallet/sheets/remove_account/view.cljs
  src/status_im/feature_flags.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19155 [Fix] Chain down toast shown for chains unrelated to the current network
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/events.cljs
Labels: Tested - OK, request-manual-qa

#19097 Fix chat navigation buttons when scrolling to top
  src/js/worklets/chat/messenger/messages.js
  src/js/worklets/chat/messenger/navigation.js
  src/status_im/contexts/chat/messenger/messages/navigation/style.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
  src/utils/worklets/chat/messenger/messages.cljs
  src/utils/worklets/chat/messenger/navigation.cljs
Labels: Tested - OK, request-manual-qa

#19189 chore: remove repetitive words
  src/status_im/contexts/shell/share/wallet/component_spec.cljs
  test/appium/tests/old_ui/medium/test_pairing_devices_sync_m.py
Labels: external

#19245 Fix pinned messages context tag style
  src/quo/components/tags/context_tag/schema.cljs
  src/quo/components/tags/context_tag/style.cljs
  src/quo/components/tags/context_tag/view.cljs
  src/status_im/contexts/chat/messenger/menus/pinned_messages/style.cljs
  src/status_im/contexts/chat/messenger/menus/pinned_messages/view.cljs
Labels: Tested - OK, request-manual-qa

#19293 fix bio-metric login
  src/status_im/contexts/profile/login/events.cljs
Labels: Tested - OK, request-manual-qa

#19177 Account selection: Implement features related to editing shared addresses
  src/quo/components/drawers/bottom_actions/component_spec.cljs
  src/quo/components/drawers/bottom_actions/view.cljs
  src/schema/re_frame.cljs
  src/status_im/contexts/communities/actions/accounts_selection/effects.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events_test.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/events_test.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/style.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/events.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/events_test.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/communities/actions/leave/events.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/contexts/preview/quo/drawers/bottom_actions.cljs
  src/status_im/feature_flags.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/community/account_selection.cljs
  src/status_im/subs/community/account_selection_test.cljs
  src/status_im/subs/root.cljs
  translations/en.json
Labels: Tested - OK, feature, request-manual-qa, E:Mobile [Crew] Community Permissions v2.28

#19105 feat: show pinned messages bottom sheet in channel home
  src/status_im/contexts/chat/messenger/menus/pinned_messages/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/contexts/chat/messenger/messages/pin/events.cljs
  src/status_im/contexts/communities/actions/chat/view.cljs
Labels: Tested - OK, request-manual-qa

#19287 JC-Fraschetti/[Wallet] Add fixtures to recovered accounts and refactor wallet_getDerivedAddresses test
  src/test_helpers/integration.cljs
  src/tests/contract_test/wallet_recovered_account_test.cljs
  src/tests/contract_test/wallet_test.cljs
  src/tests/integration_test/constants.cljs
Labels: E:Mobile Wallet MVP, skip-manual-qa

#19321 Fix subs leak and fix schema error
  src/legacy/status_im/subs/root.cljs
  src/status_im/contexts/chat/messenger/composer/utils.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/subs/chats.cljs
Labels: skip-manual-qa

#19134 feat: add jump-to button in group-detail screen
  src/status_im/contexts/chat/group_details/style.cljs
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
Labels: Tested - OK, request-manual-qa

#19056 Fix drawer message according to desings
  src/status_im/common/bottom_sheet/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/subs/profile.cljs
  src/status_im/subs/profile_test.cljs
Labels: Tested - OK, request-manual-qa, design-review-required

#19274 Improve navigation code
  src/status_im/contexts/onboarding/create_password/view.cljs
  src/status_im/contexts/onboarding/create_profile/view.cljs
  src/status_im/contexts/onboarding/enable_notifications/view.cljs
  src/status_im/contexts/onboarding/enter_seed_phrase/view.cljs
  src/status_im/contexts/onboarding/welcome/view.cljs
  src/status_im/contexts/shell/jump_to/events.cljs
  src/status_im/contexts/shell/jump_to/view.cljs
  src/status_im/contexts/wallet/account/bridge_send/view.cljs
  src/status_im/contexts/wallet/account/bridge_to/view.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
  src/status_im/navigation/state.cljs
  src/status_im/subs/navigation.cljs
  src/status_im/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#19315 Prevent profiles list from disappearing after onboarding and logging out
  src/status_im/contexts/profile/profiles/view.cljs
Labels: Tested - OK, request-manual-qa

#19246 [#19247] feat: migrate to new contact profile
  .env
  src/legacy/status_im/contact/block.cljs
  src/quo/components/text_combinations/page_top/view.cljs
  src/quo/components/text_combinations/username/view.cljs
  src/status_im/common/scroll_page/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/profile/contact/actions/view.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
  src/status_im/contexts/profile/contact/block_contact/view.cljs
  src/status_im/contexts/profile/contact/contact_request/view.cljs
  src/status_im/contexts/profile/contact/header/style.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  src/status_im/contexts/profile/contact/view.cljs
  src/status_im/feature_flags.cljs
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#19070 Wallet: selecting keypair
  src/quo/components/wallet/keypair/style.cljs
  src/quo/components/wallet/keypair/view.cljs
  src/status_im/contexts/wallet/create_account/events.cljs
  src/status_im/contexts/wallet/create_account/events_test.cljs
  src/status_im/contexts/wallet/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events_test.cljs
  src/status_im/events.cljs
  src/status_im/feature_flags.cljs
  src/status_im/subs/profile.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#19329 fix: revert removal of key in profile settings view
  src/status_im/contexts/profile/settings/view.cljs
Labels: skip-manual-qa

#18986 feat: make bridging transactions work after sliding to confirm the transaction
  src/quo/components/wallet/summary_info/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/account/bridge_to/view.cljs
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/feature_flags.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#19217 fix incorrect unread counter is displayed when a message is removed
  src/legacy/status_im/chat/models/message.cljs
  src/status_im/contexts/chat/events.cljs
Labels: Tested - OK, request-manual-qa

#19033 fix: unable to swipe b/w activity center tabs
  src/quo/components/tabs/tabs/view.cljs
Labels: Tested - OK, request-manual-qa

#19203 fix duplicate mention
  src/status_im/contexts/chat/messenger/messages/content/text/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/text/view.cljs
Labels: Tested - OK, request-manual-qa

#19185 fix: unresponsive add watched address screen when entering a multi-chain address
  src/status_im/contexts/wallet/add_address_to_watch/view.cljs
Labels: Tested - OK, request-manual-qa

#19339 Fix issue with allowing users to post on channel
  src/legacy/status_im/data_store/communities.cljs
  src/status_im/subs/communities.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#19214 e2e: changed build name and added wait for session id
  ci/Jenkinsfile.e2e-nightly
  test/appium/tests/__init__.py
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#19223 fix: Long community name not split into two lines
  src/quo/components/text_combinations/style.cljs
  src/quo/components/text_combinations/view.cljs
Labels: Tested - OK, request-manual-qa

#19187 fix: show pubkey in add contact input when available
  src/status_im/contexts/chat/home/add_new_contact/views.cljs
Labels: Tested - OK, request-manual-qa

#19210 Fraschetti - Add tests for wallet_getWalletToken
  src/tests/contract_test/utils.cljs
  src/tests/contract_test/wallet_recovered_account_test.cljs
  src/tests/contract_test/wallet_test.cljs
  src/tests/integration_test/constants.cljs
Labels: tests, E:Mobile Wallet MVP, skip-manual-qa

#18988 18638- [Communities] Implement Permissions Drawer
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/permissions_sheet/style.cljs
  src/status_im/contexts/communities/actions/permissions_sheet/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/root.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, E:Mobile Communities MVP

#19318 Fix for "Jump to" button overlapping Logout button on the Profile screen
  src/status_im/contexts/profile/settings/style.cljs
  src/status_im/contexts/profile/settings/view.cljs
Labels: skip-manual-qa, design-review-required

#19297 chore(quo): add profile/extended collectible component
  src/quo/components/profile/collectible_list_item/view.cljs
  src/quo/components/profile/expanded_collectible/component_spec.cljs
  src/quo/components/profile/expanded_collectible/style.cljs
  src/quo/components/profile/expanded_collectible/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/preview/quo/profile/expanded_collectible.cljs
Labels: skip-manual-qa, design-review-required

#19100 [#18740] Increase debounce timing for fetching routes
  src/status_im/contexts/wallet/send/input_amount/view.cljs
Labels: skip-manual-qa

#19340 Fraschetti - Add wallet-get-address-details-contract-test
  src/tests/contract_test/wallet_test.cljs
Labels: E:Mobile Wallet MVP, skip-manual-qa

#19333 Wallet: Keypair feature flag
  src/quo/components/list_items/quiz_item/style.cljs
  src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im/contexts/wallet/create_account/events.cljs
  src/status_im/contexts/wallet/create_account/new_keypair/backup_recovery_phrase/style.cljs
  src/status_im/contexts/wallet/create_account/new_keypair/backup_recovery_phrase/view.cljs
  src/status_im/contexts/wallet/create_account/new_keypair/check_your_backup/style.cljs
  src/status_im/contexts/wallet/create_account/new_keypair/keypair_name/style.cljs
  src/status_im/contexts/wallet/create_account/new_keypair/keypair_name/view.cljs
  src/status_im/contexts/wallet/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/feature_flags.cljs
Labels: Tested - OK, request-manual-qa

#19088 Feature/allow user to select a color for the group chat #18982
  src/legacy/status_im/data_store/chats.cljs
  src/legacy/status_im/data_store/chats_test.cljs
  src/legacy/status_im/group_chats/core.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/quo/components/avatars/group_avatar/view.cljs
  src/quo/components/colors/color_picker/view.cljs
  src/react_native/core.cljs
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/common/standard_authentication/password_input/view.cljs
  src/status_im/common/validation/profile.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/group_create/events.cljs
  src/status_im/contexts/chat/group_create/style.cljs
  src/status_im/contexts/chat/group_create/view.cljs
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/chat/home/new_chat/view.cljs
  src/status_im/contexts/preview/quo/preview.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/navigation/view.cljs
  src/utils/emojilib.cljs
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa, design-review-required

#18563 Upgrade `react native` to 0.73.5
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/status/ethereum/MainActivity.kt
  android/app/src/main/java/im/status/ethereum/MainApplication.kt
  android/build.gradle
  android/gradle.properties
  babel.config.js
  fastlane/Gemfile
  fastlane/Gemfile.lock
  fastlane/gemset.nix
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  ios/StatusIm/AppDelegate.mm
  ios/StatusIm/Info.plist
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/ForegroundService.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/deps/gradle/proj.list
  nix/deps/nodejs-patched/default.nix
  nix/mobile/fastlane/default.nix
  nix/overlay.nix
  nix/pkgs.nix
  nix/pkgs/aapt2/default.nix
  nix/pkgs/android-sdk/compose.nix
  nix/pkgs/xcbeautify/default.nix
  nix/scripts/node_modules.sh
  package.json
  src/legacy/status_im/ui/components/react.cljs
  src/mocks/js_dependencies.cljs
  src/quo/components/profile/profile_card/view.cljs
  src/react_native/clipboard.cljs
  test/jest/jestSetup.js
  yarn.lock
Labels: Tested - OK, request-manual-qa

#19123 Create Navigation mechanism for wizard type flows #19059
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/common/wizard.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/flow_config.cljs
  src/status_im/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/events.cljs
Labels: Tested - OK, request-manual-qa

#19364 e2e: temp fix for jump to
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
Labels: tests

#19335 Prevent a full nix derivation build for android when cljs code is updated and improve debug build speed
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  nix/mobile/android/build.nix
Labels: skip-manual-qa

#19341 fix input issues
  src/quo/components/inputs/address_input/component_spec.cljs
  src/quo/components/inputs/address_input/view.cljs
  src/quo/components/inputs/input/view.cljs
  src/status_im/common/emoji_picker/view.cljs
  src/status_im/contexts/onboarding/create_profile/view.cljs
  src/status_im/contexts/wallet/scan_account/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa

#19337 Tweak UI for contact request notifications
  src/quo/components/notifications/notification/style.cljs
  src/quo/components/notifications/notification/view.cljs
  src/status_im/contexts/preview/quo/notifications/notification.cljs
  src/status_im/contexts/shell/activity_center/events.cljs
Labels: skip-manual-qa, design-review-required

#19349 fix: very small token values are being displayed in scientific format
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
Labels: Tested - OK, request-manual-qa

#19186 [#18833] Confirm button disappearing while editing address
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/contexts/wallet/add_address_to_watch/confirm_address/view.cljs
  src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs
  src/status_im/contexts/wallet/create_account/style.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/contexts/wallet/edit_account/view.cljs
  translations/en.json
Labels: request-manual-qa

#19390 Error when marking a community notification as read in the activity center #19388
  src/legacy/status_im/data_store/chats.cljs
Labels: Tested - OK, request-manual-qa

#19379 All addresses text is not updated when changing accounts
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19242 add empty check for keychain credentials server
  src/react_native/keychain.cljs
Labels: Tested - OK, request-manual-qa

#19255 Remove not-implemented box from sticker/emoji messages
  src/legacy/status_im/ui/screens/chat/message/legacy_view.cljs
  src/status_im/contexts/chat/messenger/messages/content/emoji_message/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/emoji_message/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/sticker_message/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/contexts/shell/activity_center/notification/reply/view.cljs
Labels: Tested - OK, skip-manual-qa

#19015 Fix chat spacings
  src/quo/components/community/channel_action/style.cljs
  src/quo/components/dividers/date.cljs
  src/status_im/contexts/chat/messenger/messages/content/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/style.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#19361 Remove 'Community admins will review your request' text from community overview screen
  src/status_im/contexts/communities/overview/view.cljs
  test/appium/tests/critical/test_deep_and_universal_links.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19378 Hide community channels when hide channels option is enabled
  src/legacy/status_im/data_store/chats.cljs
  src/legacy/status_im/data_store/communities.cljs
  src/status_im/subs/communities.cljs
Labels: Tested - OK, request-manual-qa

#19285 qualify onboarding screens keys
  src/legacy/status_im/keycard/login.cljs
  src/legacy/status_im/keycard/recovery.cljs
  src/status_im/common/pairing/events.cljs
  src/status_im/contexts/onboarding/common/background/view.cljs
  src/status_im/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im/contexts/onboarding/enable_notifications/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/onboarding/identifiers/view.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
  src/status_im/contexts/onboarding/new_to_status/view.cljs
  src/status_im/contexts/onboarding/syncing/progress/view.cljs
  src/status_im/contexts/preview/quo/common.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/profiles/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/contexts/syncing/scan_sync_code/view.cljs
  src/status_im/navigation/roots.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/general.cljs
  src/test_helpers/integration.cljs
Labels: Tested - OK, request-manual-qa

#19389 fix: re-route a user's own profile link to their settings page
  src/status_im/common/universal_links.cljs
Labels: Tested - OK

#19365 [Feature] Enable Test Networks by default on E2E and PR builds
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.release
  src/status_im/config.cljs
  src/status_im/contexts/profile/config.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#19352 [#19117] fix: setting over scroll shows gap
  src/status_im/contexts/profile/settings/view.cljs
Labels: Tested - OK, request-manual-qa

#19415 ci: bump jenkins-lib to fix sepolia token typo
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: infra

#19409 [#18934] universal scanner in wallet receive
  src/quo/components/gradient/gradient_cover/view.cljs
  src/quo/components/wallet/account_overview/view.cljs
  src/status_im/contexts/shell/qr_reader/view.cljs
  src/status_im/contexts/wallet/share_address/view.cljs
Labels: Tested - OK, skip-manual-qa

#19402 Disable button when request is in flight
  src/legacy/status_im/data_store/communities.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/discover/events.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/community/account_selection.cljs
Labels: Tested - OK, request-manual-qa

#19073 fix: avatar alignment
  resources/images/icons2/32x32/group@2x.png
  resources/images/icons2/32x32/group@3x.png
  src/status_im/contexts/chat/messenger/messages/list/style.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
  src/status_im/contexts/chat/messenger/placeholder/view.cljs
Labels: Tested - OK, request-manual-qa

#19289 [19159] Implement drawer action component #19159
  src/quo/components/drawers/drawer_action/component_spec.cljs
  src/quo/components/drawers/drawer_action/schema.cljs
  src/quo/components/drawers/drawer_action/style.cljs
  src/quo/components/drawers/drawer_action/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/drawers/drawer_action.cljs
  src/status_im/contexts/preview/quo/main.cljs
Labels: external, skip-manual-qa, design-review-required

#19424 Add toggle instead of checkbox for addresses for permissions sheet
  src/quo/components/settings/page_setting/view.cljs
Labels: skip-manual-qa

#19332 chore: rename alias of promesa to be more verbose
  .clj-kondo/config.edn
  src/quo/components/profile/expanded_collectible/view.cljs
  src/react_native/core.cljs
  src/status_im/common/log.cljs
  src/status_im/contexts/chat/messenger/photo_selector/effects.cljs
  src/status_im/contexts/communities/actions/accounts_selection/effects.cljs
  src/test_helpers/integration.cljs
  src/tests/contract_test/profile_test.cljs
  src/tests/contract_test/utils.cljs
  src/tests/contract_test/wallet_recovered_account_test.cljs
  src/tests/contract_test/wallet_test.cljs
  src/tests/integration_test/chat_test.cljs
  src/tests/integration_test/profile_test.cljs
Labels: skip-manual-qa

#19439 Check permissions even if there's an inflight request
  src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/events_test.cljs
Labels: Tested - OK, request-manual-qa

#19414 chore(wallet): move bridge to its own folder
  src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs
  src/status_im/contexts/wallet/account/bridge_send/style.cljs
  src/status_im/contexts/wallet/account/bridge_to/style.cljs
  src/status_im/contexts/wallet/bridge/bridge_to/style.cljs
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/bridge/input_amount/style.cljs
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/bridge/select_asset/style.cljs
  src/status_im/contexts/wallet/bridge/select_asset/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/navigation/screens.cljs
Labels: skip-manual-qa

#19359 Link preview follow up bug fixes
  src/status_im/contexts/chat/messenger/composer/link_preview/events.cljs
Labels: Tested - OK, request-manual-qa

#19445 ci: use new Alchemy API tokens from env file
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: Tested - OK, infra

#19417 chore(wallet): clean up root folder
  src/status_im/contexts/wallet/account/edit_account/style.cljs
  src/status_im/contexts/wallet/account/edit_account/view.cljs
  src/status_im/contexts/wallet/account/share_address/style.cljs
  src/status_im/contexts/wallet/account/share_address/view.cljs
  src/status_im/contexts/wallet/common/scan_account/view.cljs
  src/status_im/contexts/wallet/saved_address/view.cljs
  src/status_im/contexts/wallet/saved_addresses/view.cljs
  src/status_im/contexts/wallet/share_address/style.cljs
  src/status_im/navigation/screens.cljs
Labels: skip-manual-qa

#19342 fix: token requirements margin issues
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/communities/actions/token_gating/view.cljs
Labels: skip-manual-qa, design-review-required
