Repository status-im/status-mobile, pull requests merged in 2024-08, with the labels that each got.

#20941 fix Mobile app doesn't allow taking screenshots when the 'Block Screenshots' toggle is turned off
  src/native_module/core.cljs
Labels: request-manual-qa

#20945 fix 'Usage data' bottom sheet reappears after reopening the app if you swipe it down on onboarding
  src/status_im/contexts/centralized_metrics/events.cljs
  src/status_im/contexts/profile/events.cljs
Labels: Tested - OK, request-manual-qa

#20942 fix: remove mobile-data sync setting inside legacy settings
  src/legacy/status_im/ui/screens/sync_settings/views.cljs
Labels: Tested - OK, request-manual-qa

#20943 Fix typed-data chainid check
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/processing_events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/signing.cljs
Labels: Tested - OK, request-manual-qa

#20852 fix(wallet): Fix input amount step skipped while sending a token
  src/status_im/contexts/wallet/send/events.cljs
Labels: Tested - OK, request-manual-qa

#20926 📈 Capture onboarding funnel
  src/status_im/contexts/centralized_metrics/events.cljs
  src/status_im/contexts/centralized_metrics/tracking.cljs
  src/status_im/contexts/centralized_metrics/tracking_test.cljs
Labels: Tested - OK, request-manual-qa

#20960 e2e: update for deep links tests
  test/appium/support/api/network_api.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/chat_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#20955 chore(wallet): feature flag adding watch only accounts
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/feature_flags.cljs
  test/appium/tests/critical/test_wallet.py
Labels: Tested - OK, request-manual-qa

#20931 enable status proxy
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  shadow-cljs.edn
  src/status_im/config.cljs
  src/status_im/contexts/profile/config.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#20966 e2e: fixes for community link and welcome button error
  test/appium/views/chat_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#20976 Token-gated permissions are not displayed on community's homepage #20965
  src/legacy/status_im/data_store/communities.cljs
Labels: Tested - OK, request-manual-qa

#20979 fix(wallet): Remove redirection to "send flow" when the user scans an address QR code
  src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs
  src/test_helpers/unit.cljs
Labels: Tested - OK, request-manual-qa

#20978 e2e: fixes for welcome button and more
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#20984 Improve theme switch
  src/legacy/status_im/events.cljs
  src/status_im/common/theme/effects.cljs
  src/status_im/common/theme/events.cljs
  src/status_im/common/theme/utils.cljs
  src/status_im/contexts/preview/quo/common.cljs
  src/status_im/contexts/preview/quo/gradient/gradient_cover.cljs
  src/status_im/contexts/preview/quo/preview.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/settings/effects.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/events.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/roots.cljs
Labels: Tested - OK, request-manual-qa

#20992 [#20971] fix: app crash when collectible max limit is nan
  src/status_im/contexts/wallet/collectible/utils.cljs
Labels: Tested - OK, request-manual-qa

#21033 wallet(account): disable send and bridge options for assets with a 0 balance
  src/status_im/contexts/wallet/common/token_value/view.cljs
Labels: Tested - OK, request-manual-qa

#21042 Fix enable light client after sync
  src/status_im/contexts/syncing/events.cljs
Labels: request-manual-qa

#21018 chore: add beta tags to communities and chat home screen titles
  src/status_im/common/home/title_column/view.cljs
  src/status_im/contexts/chat/home/view.cljs
  src/status_im/contexts/communities/home/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21010 feature: require manual acceptance of terms-of-use and privacy-statement
  resources/privacy.mdwn
  resources/terms-of-use.mdwn
  src/quo/components/drawers/bottom_actions/view.cljs
  src/status_im/contexts/onboarding/intro/style.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
  src/status_im/contexts/onboarding/privacy/view.cljs
  test/appium/views/sign_in_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21055 👓 Hide chain down toasts
  src/status_im/contexts/wallet/events.cljs
Labels: Tested - OK

#20853 feat(swap): setup swap ui
  src/quo/components/wallet/swap_input/view.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/style.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/status_im/contexts/wallet/swap/swap_proposal/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/swap.cljs
  src/status_im/subs/wallet/swap_test.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
  translations/en.json
Labels: skip-manual-qa

#21067 feat(wallet): Make wallet behave well when device is offline
  src/status_im/contexts/network/data_store.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/db.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/signals.cljs
  src/status_im/subs/general.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#21075 chore_: fix APK selection for run-android script
  scripts/run-android.sh
Labels: skip-manual-qa

#21073 e2e: fixes for communities tests
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/elements_templates/image_sent_in_community.png
Labels: tests

#21068 Remove redundant visibility status update call
  src/status_im/contexts/onboarding/welcome/view.cljs
Labels: skip-manual-qa

#21086 Fix dApp tx crashing before showing modal
  src/status_im/subs/wallet/wallet_connect.cljs
Labels: request-manual-qa

#21093 Rename utils.navigation to events-helper and add docstring to clarify namespace use case
  src/status_im/common/data_confirmation_sheet/view.cljs
  src/status_im/common/events_helper.cljs
  src/status_im/contexts/profile/settings/screens/messages/view.cljs
  src/status_im/contexts/profile/settings/screens/syncing/view.cljs
  src/status_im/contexts/settings/privacy_and_security/view.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
Labels: skip-manual-qa

#21104 Fix: app upgrade issues in wallet
  src/status_im/contexts/wallet/sheets/account_options/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#21087 [#21081] Privacy Policy and metrics modal in settings while sharing usage data
  resources/privacy.mdwn
  resources/terms-of-use.mdwn
  src/status_im/common/metrics_confirmation_modal/view.cljs
  src/status_im/common/privacy/view.cljs
  src/status_im/common/terms/view.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
  src/status_im/contexts/settings/privacy_and_security/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21107 Improve app theme naming and doc strings
  src/legacy/status_im/events.cljs
  src/status_im/common/theme/events.cljs
  src/status_im/common/theme/utils.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/profile/settings/events.cljs
Labels: skip-manual-qa

#21105 fixes Not visible status bar on light theme
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/onboarding/welcome/view.cljs
  src/status_im/contexts/preview/quo/common.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
Labels: request-manual-qa

#21111 chore: update icons for iOS and iPadOS release apps
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-60@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-60@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-72.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-72@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-76.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-76@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-83.5@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Notification.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Notification@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Notification@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-40.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-40@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-40@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-50.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small-50@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon-Small@3x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/Icon@2x.png
  ios/StatusIm/Images.xcassets/AppIcon.appiconset/ios-marketing.png
  resources/images/mock2/status-logo.png
  resources/images/ui/status-logo.png
Labels: Tested - OK

#21112 Chore: update icons for android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/ic_background.png
  android/app/src/main/res/drawable-hdpi/ic_foreground.png
  android/app/src/main/res/drawable-hdpi/splash_logo.png
  android/app/src/main/res/drawable-mdpi/ic_background.png
  android/app/src/main/res/drawable-mdpi/ic_foreground.png
  android/app/src/main/res/drawable-mdpi/launch_logo.png
  android/app/src/main/res/drawable-mdpi/logo.png
  android/app/src/main/res/drawable-mdpi/notification_icon.png
  android/app/src/main/res/drawable-mdpi/splash_logo.png
  android/app/src/main/res/drawable-xhdpi/ic_background.png
  android/app/src/main/res/drawable-xhdpi/ic_foreground.png
  android/app/src/main/res/drawable-xhdpi/launch_logo.png
  android/app/src/main/res/drawable-xhdpi/logo.png
  android/app/src/main/res/drawable-xhdpi/notification_icon.png
  android/app/src/main/res/drawable-xhdpi/splash_logo.png
  android/app/src/main/res/drawable-xxhdpi/ic_background.png
  android/app/src/main/res/drawable-xxhdpi/ic_foreground.png
  android/app/src/main/res/drawable-xxhdpi/launch_logo.png
  android/app/src/main/res/drawable-xxhdpi/logo.png
  android/app/src/main/res/drawable-xxhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxhdpi/splash_logo.png
  android/app/src/main/res/drawable-xxxhdpi/ic_background.png
  android/app/src/main/res/drawable-xxxhdpi/ic_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/launch_logo.png
  android/app/src/main/res/drawable-xxxhdpi/logo.png
  android/app/src/main/res/drawable-xxxhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxxhdpi/splash_logo.png
  android/app/src/main/res/ic_launcher-web.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_background.png
  android/app/src/main/res/mipmap-hdpi/ic_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_background.png
  android/app/src/main/res/mipmap-mdpi/ic_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: Tested - OK

#21119 [#21117] More privacy policy links
  src/status_im/common/metrics_confirmation_modal/style.cljs
  src/status_im/common/metrics_confirmation_modal/view.cljs
  src/status_im/contexts/onboarding/intro/style.cljs
Labels: Tested - OK, request-manual-qa, followup required

#21083 fix: onboarding terms-of-use and privacy-statement checkbox spacing when line wrapping
  src/status_im/contexts/onboarding/intro/style.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
Labels: request-manual-qa

#21128 fix: change verbiage from privacy statement to privacy policy
  src/status_im/contexts/onboarding/intro/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21002 chore_: Remove passing emoji on profile creation
  src/status_im/contexts/profile/create/events.cljs
  src/status_im/contexts/profile/recover/events.cljs
Labels: Tested - OK, request-manual-qa

#20915 Fix rounding of fiat and crypto on send page
  src/quo/components/wallet/token_input/component_spec.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/contexts/preview/quo/wallet/token_input.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/test_helpers/unit.cljs
  src/utils/money.cljs
Labels: Tested - OK, request-manual-qa

#20772 [#20720] feat: add ability to set currency from account Settings
  resources/images/tokens/mainnet/BTC.png
  resources/images/tokens/mainnet/BTC@2x.png
  resources/images/tokens/mainnet/BTC@3x.png
  resources/images/ui2/no-assets-dark@2x.png
  resources/images/ui2/no-assets-dark@3x.png
  resources/images/ui2/no-assets-light@2x.png
  resources/images/ui2/no-assets-light@3x.png
  src/legacy/status_im/data_store/settings.cljs
  src/legacy/status_im/multiaccounts/update/core.cljs
  src/legacy/status_im/utils/currency.cljs
  src/quo/components/settings/settings_item/view.cljs
  src/status_im/common/json_rpc/events.cljs
  src/status_im/common/resources.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/settings/language_and_currency/currency/style.cljs
  src/status_im/contexts/settings/language_and_currency/currency/utils.cljs
  src/status_im/contexts/settings/language_and_currency/currency/view.cljs
  src/status_im/contexts/settings/language_and_currency/data_store.cljs
  src/status_im/contexts/settings/language_and_currency/data_store_test.cljs
  src/status_im/contexts/settings/language_and_currency/events.cljs
  src/status_im/contexts/settings/language_and_currency/events_test.cljs
  src/status_im/contexts/settings/language_and_currency/view.cljs
  src/status_im/contexts/settings/privacy_and_security/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/db.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/general.cljs
  src/status_im/subs/general_test.cljs
  src/status_im/subs/profile.cljs
  src/status_im/subs/profile_test.cljs
  src/status_im/subs/root.cljs
  src/status_im/subs/wallet/swap_test.cljs
  src/status_im/subs/wallet/wallet_test.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa, status-go

#20844 Metamask address support
  src/status_im/common/router.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs
  src/status_im/contexts/shell/qr_reader/view.cljs
  src/status_im/contexts/wallet/add_account/add_address_to_watch/view.cljs
  src/status_im/contexts/wallet/common/scan_account/view.cljs
  src/status_im/contexts/wallet/common/validation.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/utils/address.cljs
  src/utils/address_test.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#21147 chore: bump blur view lib to 4.4.1
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  package.json
  yarn.lock
Labels: skip-manual-qa

#21082 Admin cannot re-add users to the group chat after removing them using…
  src/legacy/status_im/group_chats/core.cljs
  src/status_im/contexts/chat/group_details/view.cljs
Labels: Tested - OK, request-manual-qa

#21052 Improve and Fix Unmute Behavior for Chats and Communities
  src/status_im/common/muting/helpers.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#21121 [#20803] fix: dapp session proposal reject
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
Labels: Tested - OK, request-manual-qa

#21003 Profile with ENS fixes
  src/legacy/status_im/data_store/settings.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/common/universal_links_test.cljs
  src/status_im/contexts/profile/edit/list_items.cljs
  src/status_im/contexts/wallet/common/validation.cljs
Labels: Tested - Issues, request-manual-qa

#20961 fix(wallet): Collectibles not fetched for new and recovered accounts
  src/quo/components/profile/collectible_list_item/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/collectible/events_test.cljs
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events_test.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/contexts/wallet/signals.cljs
  src/status_im/subs/wallet/collectibles.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go
