Repository status-im/status-mobile, pull requests merged in 2024-04, with the labels that each got.

#19437 fix jump-to community card animation
  src/status_im/contexts/communities/events.cljs
Labels: skip-manual-qa

#19369 upgrade nixpkgs to 23-11
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  logs/README.md
  nix/overlay.nix
  nix/pkgs.nix
  nix/pkgs/idb-companion/default.nix
  nix/pkgs/xcbeautify/default.nix
  scripts/run-ios.sh
  src/legacy/status_im/bottom_sheet/view.cljs
  src/legacy/status_im/chat/models/loading.cljs
  src/legacy/status_im/chat/models/message_test.cljs
  src/legacy/status_im/ens/core.cljs
  src/legacy/status_im/keycard/fx.cljs
  src/legacy/status_im/popover/core.cljs
  src/legacy/status_im/ui/components/action_sheet.cljs
  src/legacy/status_im/ui/components/colors.cljs
  src/legacy/status_im/ui/components/list/item.cljs
  src/legacy/status_im/ui/components/text_input.cljs
  src/legacy/status_im/ui/components/topbar.cljs
  src/legacy/status_im/ui/screens/browser/permissions/views.cljs
  src/legacy/status_im/ui/screens/reset_password/views.cljs
  src/legacy/status_im/utils/random_test.cljs
  src/quo/components/animated_header_flatlist/view.cljs
  src/quo/components/avatars/user_avatar/view.cljs
  src/quo/components/gradient/gradient_cover/view.cljs
  src/quo/components/graph/utils_test.cljs
  src/quo/components/navigation/bottom_nav_tab/view.cljs
  src/quo/components/navigation/top_nav/style.cljs
  src/quo/components/record_audio/record_audio/buttons/record_button_big.cljs
  src/react_native/keychain.cljs
  src/status_im/common/scan_qr_code/view.cljs
  src/status_im/contexts/chat/messenger/composer/selection.cljs
  src/status_im/contexts/chat/messenger/messages/content/deleted/view.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
  src/status_im/contexts/profile/contact/block_contact/view.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  src/status_im/contexts/profile/contact/view.cljs
  src/status_im/contexts/profile/utils.cljs
  src/status_im/contexts/shell/activity_center/notification/contact_verification/view.cljs
  src/status_im/contexts/shell/jump_to/components/floating_screens/style.cljs
  src/status_im/subs/shell.cljs
Labels: Tested - OK, request-manual-qa

#19458 don't kill metro server when its already running
  scripts/run-metro.sh
Labels: skip-manual-qa

#19338 Fraschetti - Add wallet-search-ens-test
  src/test_helpers/integration.cljs
  src/tests/contract_test/wallet_test.cljs
Labels: E:Mobile Wallet MVP, skip-manual-qa

#19432 fix 1-1 Chat not removed after user is blocked
  src/legacy/status_im/contact/block.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/profile/contact/block_contact/view.cljs
Labels: Tested - OK, request-manual-qa

#19089 fix status and nav bar color
  src/status_im/common/alert_banner/events.cljs
  src/status_im/common/toasts/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/settings/effects.cljs
  src/status_im/contexts/shell/jump_to/animation.cljs
  src/status_im/contexts/shell/jump_to/events.cljs
  src/status_im/contexts/shell/jump_to/utils.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/navigation/state.cljs
Labels: Tested - OK, request-manual-qa

#19425 [#19401] Wallet share QR code multiple fixes
  src/quo/components/share/share_qr_code/view.cljs
  src/status_im/contexts/shell/share/profile/view.cljs
  src/status_im/contexts/shell/share/style.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/subs/general.cljs
Labels: Tested - OK

#19468 Truncate secondary names in username and author components
  src/quo/components/messages/author/style.cljs
  src/quo/components/messages/author/view.cljs
  src/quo/components/text_combinations/username/style.cljs
  src/quo/components/text_combinations/username/view.cljs
  src/status_im/contexts/chat/home/chat_list_item/style.cljs
  src/status_im/contexts/chat/home/chat_list_item/view.cljs
Labels: skip-manual-qa

#19362 Add debug logs to wait-for in integration tests
  src/test_helpers/integration.cljs
Labels: skip-manual-qa

#19456 clean up unused npm deps
  doc/dependencies.md
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  nix/deps/nodejs/README.md
  package.json
  src/mocks/js_dependencies.cljs
  src/react_native/languages.cljs
  test/jest/jest.config.js
  test/jest/jestSetup.js
  yarn.lock
Labels: Tested - OK, request-manual-qa

#19398 [#19264] fix: add contact bottom margin
  src/status_im/contexts/chat/home/add_new_contact/style.cljs
  src/status_im/contexts/chat/home/add_new_contact/views.cljs
Labels: Tested - OK, request-manual-qa

#19348 [Feature] Show "Testnet mode enabled" banner if testnet enabled
  src/status_im/contexts/onboarding/welcome/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19074 Allow to undo muting the chat/channel from toast
  src/status_im/constants.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/communities/actions/community_options/events.cljs
  src/tests/integration_test/chat_test.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases added

#19486 fix failing iOS nightly build
  ios/StatusIm.xcodeproj/project.pbxproj
Labels: skip-manual-qa

#19250 Bottom sheet with save and send options not displayed after scanning wallet QR using universal scanner #18928
  src/quo/components/drawers/drawer_top/component_spec.cljs
  src/quo/components/drawers/drawer_top/view.cljs
  src/quo/components/list_items/token_network/schema.cljs
  src/quo/components/share/share_qr_code/style.cljs
  src/quo/components/share/share_qr_code/view.cljs
  src/quo/components/wallet/address_text/schema.cljs
  src/quo/components/wallet/address_text/view.cljs
  src/quo/components/wallet/token_input/schema.cljs
  src/quo/foundations/colors.cljs
  src/status_im/contexts/shell/qr_reader/events.cljs
  src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs
  src/status_im/contexts/shell/qr_reader/view.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/flow_config.cljs
  src/status_im/contexts/wallet/send/from/style.cljs
  src/status_im/contexts/wallet/send/from/view.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#19087 feat: contact CustomizationColor
  src/legacy/status_im/multiaccounts/update/core.cljs
  src/quo/components/avatars/user_avatar/view.cljs
  src/quo/components/profile/profile_card/view.cljs
  src/schema/quo.cljs
  src/status_im/contexts/chat/contacts/events.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
  src/status_im/contexts/profile/contact/block_contact/view.cljs
  src/status_im/contexts/profile/contact/contact_request/view.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  src/status_im/contexts/profile/contact/view.cljs
  src/status_im/contexts/profile/edit/accent_colour/view.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/subs/contact.cljs
  src/status_im/subs/profile.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go, test cases required

#19429 updated leave button background color to community color
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/communities/actions/leave/view.cljs
Labels: design-review-required

#19044 updated community rules to display the actual rules
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/communities/actions/community_rules_list/style.cljs
  src/status_im/contexts/communities/actions/generic_menu/style.cljs
  src/status_im/contexts/communities/actions/generic_menu/view.cljs
  src/status_im/contexts/communities/actions/see_rules/view.cljs
Labels: Tested - OK, request-manual-qa, followup required, design-review-required

#19498 e2e: fixes after testet mode enabled changes
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/elements_templates/saucelabs_sauce_chat.png
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: tests

#19522 Use correct schema keyword
  src/utils/image_server.cljs
Labels: skip-manual-qa

#19430 fix top bar disappearing when removing or blocking contact
  src/status_im/contexts/chat/messenger/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#19370 [#19351] fix: animate username in profile
  src/js/worklets/profile_header.js
  src/mocks/js_dependencies.cljs
  src/quo/components/navigation/page_nav/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/utils/worklets/profile_header.cljs
Labels: Tested - OK, request-manual-qa, followup required

#19520 Fix background color on communities/chat home
  src/status_im/common/home/banner/style.cljs
  src/status_im/common/home/banner/view.cljs
Labels: Tested - OK, request-manual-qa

#19508 🖇️ Connect getSavedAddresses RPC to show or hide save address button
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events/saved_addresses.cljs
  src/status_im/contexts/wallet/send/save_address/view.cljs
  src/status_im/contexts/wallet/send/transaction_progress/view.cljs
  src/status_im/subs/root.cljs
  src/status_im/subs/wallet/saved_addresses.cljs
Labels: skip-manual-qa

#19403 fix: dismiss keyboard when opening a modal
  src/status_im/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#19383 Use scrollable multiline text-input in contact request form
  src/quo/components/inputs/input/view.cljs
  src/status_im/common/bottom_sheet/view.cljs
  src/status_im/contexts/profile/contact/contact_request/style.cljs
  src/status_im/contexts/profile/contact/contact_request/view.cljs
  src/status_im/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#19487 Fix legacy settings seed backup
  src/status_im/subs/general.cljs
Labels: Tested - OK, request-manual-qa

#19434 Improve navigate-to-jump-to
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/chat/messenger/messages/contact_requests/bottom_drawer/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/contexts/shell/jump_to/events.cljs
  src/status_im/contexts/shell/jump_to/utils.cljs
Labels: request-manual-qa

#19477 e2e: wallet tests added
  test/appium/support/api/network_api.py
  test/appium/support/testrail_report.py
  test/appium/tests/critical/test_wallet.py
  test/appium/tests/old_ui/wallet_and_tx/test_wallet_old.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
  test/appium/views/wallet_view_old_ui.py
Labels: tests

#19517 [#19406] fix: add min char validation for nickname
  src/status_im/common/validation/profile.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
Labels: Tested - OK, request-manual-qa

#19489 Tweak layout of quo/author component to use flex-baseline
  src/quo/components/messages/author/style.cljs
  src/quo/components/messages/author/view.cljs
Labels: skip-manual-qa

#19536 e2e: false failures fixes for wallet and image
  test/appium/tests/critical/test_wallet.py
  test/appium/views/elements_templates/saucelabs_sauce_chat.png
Labels: tests

#19150 [Feature] Wallet - Network based assets and fiat balance calculation
  resources/images/tokens/mainnet/STT.png
  resources/images/tokens/mainnet/STT@2x.png
  resources/images/tokens/mainnet/STT@3x.png
  src/status_im/constants.cljs
  src/status_im/contexts/shell/jump_to/components/bottom_tabs/view.cljs
  src/status_im/contexts/shell/jump_to/components/home_stack/view.cljs
  src/status_im/contexts/shell/share/profile/view.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/contexts/wallet/account/share_address/view.cljs
  src/status_im/contexts/wallet/account/tabs/assets/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/common/temp.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/db.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events_test.cljs
  src/status_im/contexts/wallet/home/tabs/assets/view.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im/contexts/wallet/sheets/network_filter/view.cljs
  src/status_im/contexts/wallet/sheets/network_preferences/view.cljs
  src/status_im/db.cljs
  src/status_im/feature_flags.cljs
  src/status_im/subs/wallet/collectibles.cljs
  src/status_im/subs/wallet/networks.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19556 e2e: fix for passwrod input
  test/appium/views/sign_in_view.py
Labels: tests

#19548 Fix invalid schemas
  src/quo/components/wallet/token_input/schema.cljs
  src/status_im/contexts/communities/actions/accounts_selection/effects.cljs
Labels: skip-manual-qa

#19492 fix android composer background shadow not visible when image is attached
  src/js/worklets/chat/messenger/composer.js
  src/status_im/contexts/chat/messenger/composer/actions/view.cljs
  src/status_im/contexts/chat/messenger/composer/effects.cljs
  src/status_im/contexts/chat/messenger/composer/gesture.cljs
  src/status_im/contexts/chat/messenger/composer/handlers.cljs
  src/status_im/contexts/chat/messenger/composer/style.cljs
  src/status_im/contexts/chat/messenger/composer/sub_view.cljs
  src/status_im/contexts/chat/messenger/composer/utils.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
  src/utils/worklets/chat/messenger/composer.cljs
Labels: Tested - OK, request-manual-qa

#19499 Truncate text inside contact request notifications
  src/quo/components/notifications/notification/view.cljs
  src/status_im/contexts/shell/activity_center/notification/contact_requests/view.cljs
Labels: Tested - OK, request-manual-qa, test cases added

#19482 Wallet: Derivation Path - Scanning for Activity
  resources/images/icons2/12x12/face-id@2x.png
  resources/images/icons2/12x12/face-id@3x.png
  resources/images/icons2/16x16/scanning@2x.png
  resources/images/icons2/16x16/scanning@3x.png
  src/status_im/contexts/wallet/add_address_to_watch/view.cljs
  src/status_im/contexts/wallet/create_account/edit_derivation_path/component_spec.cljs
  src/status_im/contexts/wallet/create_account/edit_derivation_path/style.cljs
  src/status_im/contexts/wallet/create_account/edit_derivation_path/view.cljs
  src/status_im/contexts/wallet/create_account/events.cljs
  src/status_im/contexts/wallet/create_account/events_test.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/core_spec.cljs
  src/status_im/subs/wallet/wallet.cljs
  translations/en.json
Labels: skip-manual-qa

#19284 Fix chat permission-context
  doc/dependencies.md
  package.json
  src/mocks/js_dependencies.cljs
  src/quo/components/drawers/permission_context/component_spec.cljs
  src/quo/components/drawers/permission_context/schema.cljs
  src/quo/components/drawers/permission_context/style.cljs
  src/quo/components/drawers/permission_context/view.cljs
  src/quo/foundations/colors.cljs
  src/react_native/shadow.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
  src/status_im/contexts/chat/messenger/messages/contact_requests/bottom_drawer/view.cljs
  src/status_im/contexts/preview/quo/drawers/permission_drawers.cljs
  src/status_im/subs/chats.cljs
  test/jest/jest.config.js
  translations/en.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#19394 Token gated documentation drawer UI fix
  src/quo/components/drawers/documentation_drawers/style.cljs
  src/quo/components/drawers/documentation_drawers/view.cljs
  src/status_im/contexts/communities/overview/view.cljs
Labels: skip-manual-qa, design-review-required

#19451 apply patches with patch files
  Makefile
  ios/Podfile.lock
  nix/deps/nodejs-patched/default.nix
  patches/react-native-android.patch
  patches/react-native-keychain.patch
  patches/react-native-navigation-button-presenter.patch
  patches/react-native-navigation.patch
  patches/react-native-script.patch
  patches/react-native.patch
  scripts/patch-npm-lib.sh
Labels: nix, skip-manual-qa

#19393 [#16953] Implement change asset action in wallet send flow
  src/quo/components/drawers/drawer_top/view.cljs
  src/quo/components/list_items/token_network/schema.cljs
  src/quo/components/tags/network_tags/view.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19502 Support for multiple collectibles transaction on confirmation page
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: skip-manual-qa

#19295 Account selection sheet design review comments
  src/quo/components/settings/settings_item/view.cljs
  src/status_im/contexts/communities/actions/accounts_selection/style.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
Labels: skip-manual-qa, design-review-required

#19461 [Android] The text within buttons is slightly visible when buttons ar…
  src/quo/components/buttons/button/style.cljs
  src/quo/components/buttons/button/view.cljs
Labels: request-manual-qa

#19319 [iOS] Wrong bottom sheet opacity on onboarding and in the activity center
  src/status_im/common/bottom_sheet/view.cljs
Labels: skip-manual-qa, design-review-required

#19462 Fix the channel-action when the text is too long
  src/quo/components/community/channel_action/style.cljs
  src/quo/components/community/channel_action/view.cljs
  src/status_im/contexts/preview/quo/community/channel_actions.cljs
Labels: Tested - OK, request-manual-qa

#18489 [16315] Implement Community Channel option: view channel members and details
  src/quo/components/avatars/channel_avatar/style.cljs
  src/quo/components/avatars/user_avatar/style.cljs
  src/quo/components/avatars/user_avatar/view.cljs
  src/quo/components/text_combinations/style.cljs
  src/quo/components/text_combinations/view.cljs
  src/status_im/common/contact_list/view.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/contexts/communities/actions/channel_view_details/style.cljs
  src/status_im/contexts/communities/actions/channel_view_details/view.cljs
  src/status_im/contexts/communities/actions/chat/view.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/chat/utils.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/general.cljs
  src/utils/image_server.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19460 Drawer in the chat is not fully expanded when reply message is closed…
  src/status_im/contexts/chat/messenger/composer/utils.cljs
Labels: Tested - OK, request-manual-qa

#19570 Fix the "Choose profile" button in the profile #19551
  src/status_im/contexts/profile/settings/view.cljs
Labels: skip-manual-qa

#19571 Remove the bottom context from "Sign in by syncing" #19549
  src/status_im/contexts/onboarding/sign_in/view.cljs
Labels: skip-manual-qa

#19128 Feature/allow user to select a picture for a group chat #18983
  resources/images/icons2/32x32/group@2x.png
  resources/images/icons2/32x32/group@3x.png
  resources/images/icons2/32x32/members@2x.png
  resources/images/icons2/32x32/members@3x.png
  src/legacy/status_im/data_store/chats.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/quo/components/text_combinations/page_top/view.cljs
  src/react_native/image_crop_picker.cljs
  src/status_im/common/avatar_picture_picker/view.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/common/image_crop_picker/events.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/group_create/events.cljs
  src/status_im/contexts/chat/group_create/view.cljs
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/chat/home/chat_list_item/view.cljs
  src/status_im/contexts/onboarding/create_profile/view.cljs
  src/status_im/contexts/profile/edit/header/events.cljs
  src/status_im/contexts/profile/edit/header/events_test.cljs
  src/status_im/contexts/profile/edit/header/view.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/root.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#19557 Sometimes toast about old join community notification starts appearing on every login
  fastlane/Gemfile.lock
  src/status_im/constants.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/profile/push_notifications/local/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#19577 point statusgo to gomobile xcode 15 patch
  status-go-version.json
Labels: Tested - OK, status-go

#19426 kotlinify account, database, Log & Network Manager
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/AccountManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/AccountManager.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/DatabaseManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/DatabaseManager.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/LogManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/LogManager.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NetworkManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NetworkManager.kt
Labels: Tested - OK, request-manual-qa

#19530 Remove unused subs
  src/legacy/status_im/subs/keycard.cljs
  src/legacy/status_im/subs/mailservers.cljs
  src/legacy/status_im/subs/stickers.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/contact.cljs
  src/status_im/subs/general.cljs
  src/status_im/subs/messages.cljs
  src/status_im/subs/pairing.cljs
  src/status_im/subs/profile.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#19495 fix alert banner flicker in ios
  src/status_im/common/alert_banner/view.cljs
Labels: Tested - OK, request-manual-qa

#19560 🧰 Update `GetSuggestedRoutes` call
  src/status_im/contexts/wallet/send/events.cljs
Labels: high-priority, Tested - OK, request-manual-qa

#19448 Add Options to all collectibles entry points
  src/quo/components/profile/collectible/view.cljs
  src/status_im/config.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/options/view.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/common/utils/external_links.cljs
  src/status_im/contexts/wallet/events/collectibles.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19238 [#18739] Fix ENS resolution
  src/status_im/contexts/wallet/accounts/add_account/address_to_watch/events.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa

#19467 chore: remove old wallet code, signing code and keycard code
  src/legacy/status_im/bootnodes/core.cljs
  src/legacy/status_im/bootnodes/core_test.cljs
  src/legacy/status_im/browser/core.cljs
  src/legacy/status_im/browser/eip3085.cljs
  src/legacy/status_im/browser/eip3326.cljs
  src/legacy/status_im/data_store/settings.cljs
  src/legacy/status_im/events.cljs
  src/legacy/status_im/keycard/backup_key.cljs
  src/legacy/status_im/keycard/card.cljs
  src/legacy/status_im/keycard/change_pin.cljs
  src/legacy/status_im/keycard/common.cljs
  src/legacy/status_im/keycard/common_test.cljs
  src/legacy/status_im/keycard/core.cljs
  src/legacy/status_im/keycard/core_test.cljs
  src/legacy/status_im/keycard/delete_key.cljs
  src/legacy/status_im/keycard/export_key.cljs
  src/legacy/status_im/keycard/fx.cljs
  src/legacy/status_im/keycard/login.cljs
  src/legacy/status_im/keycard/mnemonic.cljs
  src/legacy/status_im/keycard/nfc.cljs
  src/legacy/status_im/keycard/onboarding.cljs
  src/legacy/status_im/keycard/recovery.cljs
  src/legacy/status_im/keycard/sign.cljs
  src/legacy/status_im/keycard/simulated_keycard.cljs
  src/legacy/status_im/keycard/test_menu.cljs
  src/legacy/status_im/keycard/unpair.cljs
  src/legacy/status_im/node/core.cljs
  src/legacy/status_im/signing/core.cljs
  src/legacy/status_im/signing/core_test.cljs
  src/legacy/status_im/signing/eip1559.cljs
  src/legacy/status_im/signing/gas.cljs
  src/legacy/status_im/signing/gas_test.cljs
  src/legacy/status_im/signing/keycard.cljs
  src/legacy/status_im/subs/bootnodes.cljs
  src/legacy/status_im/subs/keycard.cljs
  src/legacy/status_im/subs/root.cljs
  src/legacy/status_im/ui/screens/bootnodes_settings/edit_bootnode/styles.cljs
  src/legacy/status_im/ui/screens/bootnodes_settings/edit_bootnode/views.cljs
  src/legacy/status_im/ui/screens/bootnodes_settings/styles.cljs
  src/legacy/status_im/ui/screens/bootnodes_settings/views.cljs
  src/legacy/status_im/ui/screens/browser/eip3085/sheet.cljs
  src/legacy/status_im/ui/screens/browser/options/views.cljs
  src/legacy/status_im/ui/screens/popover/views.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/delete_profile.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/legacy/status_im/ui/screens/profile/user/views.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/legacy/status_im/ui/screens/signing/sheets.cljs
  src/legacy/status_im/ui/screens/signing/styles.cljs
  src/legacy/status_im/ui/screens/signing/views.cljs
  src/status_im/config.cljs
  src/status_im/contexts/profile/config.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/syncing/events.cljs
  src/status_im/events.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19529 Show token requirements only for token gated channels
  src/status_im/contexts/communities/actions/chat/view.cljs
  src/status_im/contexts/communities/actions/community_options/component_spec.cljs
  src/status_im/contexts/communities/actions/community_options/view.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19605 warning fixes
  src/legacy/status_im/stickers/core.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/shell/activity_center/events.cljs
  src/status_im/subs/profile.cljs
Labels: skip-manual-qa

#19591 Chore: setup feature-flag for not-implemented settings
  .env
  .env.e2e
  .env.jenkins
  src/status_im/config.cljs
  src/status_im/contexts/profile/edit/list_items.cljs
  src/status_im/contexts/profile/edit/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
Labels: Tested - OK, request-manual-qa

#19270 migrate reagent part6
  src/quo/components/notifications/activity_log/view.cljs
  src/quo/components/notifications/count_down_circle.cljs
  src/quo/components/notifications/toast/view.cljs
  src/quo/components/selectors/filter/view.cljs
  src/quo/components/selectors/reactions_selector/view.cljs
  src/quo/components/selectors/selectors/view.cljs
  src/quo/components/tags/collectible_tag/schema.cljs
  src/quo/components/tags/collectible_tag/view.cljs
  src/quo/components/tags/tags.cljs
  src/quo/components/tags/token_tag/view.cljs
  src/status_im/common/toasts/view.cljs
  src/status_im/navigation/view.cljs
Labels: Tested - OK, request-manual-qa

#18989 [18979] Implement context action Invite contacts to community
  src/legacy/status_im/communities/core.cljs
  src/quo/components/list_items/user.cljs
  src/quo/foundations/resources.cljs
  src/status_im/common/contact_list/view.cljs
  src/status_im/common/contact_list_item/view.cljs
  src/status_im/contexts/chat/home/new_chat/view.cljs
  src/status_im/contexts/communities/actions/invite_contacts/style.cljs
  src/status_im/contexts/communities/actions/invite_contacts/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/sharing/events.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/profile.cljs
  test/appium/views/chat_view.py
  translations/en.json
Labels: Tested - OK, request-manual-qa

#19459 Community channel avatar is missing on Channel screen
  src/quo/components/avatars/group_avatar/style.cljs
  src/quo/components/avatars/group_avatar/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/style.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/subs/chats.cljs
Labels: Tested - OK, request-manual-qa, followup required, design-review-required

#19558 feat: send button and system messge icon based on chat/contact customization color
  src/status_im/contexts/chat/messenger/composer/actions/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/pin/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/contact.cljs
Labels: Tested - OK, request-manual-qa, test cases required, E:Mobile [Crew] Anothers Profile v2.28

#19316 migrate reagent part 7
  src/quo/components/wallet/account_card/schema.cljs
  src/quo/components/wallet/account_card/view.cljs
  src/quo/components/wallet/amount_input/schema.cljs
  src/quo/components/wallet/amount_input/view.cljs
  src/quo/components/wallet/keypair/view.cljs
  src/quo/components/wallet/network_routing/schema.cljs
  src/quo/components/wallet/network_routing/style.cljs
  src/quo/components/wallet/network_routing/view.cljs
  src/quo/components/wallet/token_input/schema.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/quo/components/wallet/wallet_activity/schema.cljs
  src/quo/components/wallet/wallet_activity/view.cljs
Labels: Tested - OK, request-manual-qa

#19613 Composer-photo selection drawer issues
  src/status_im/contexts/chat/messenger/photo_selector/album_selector/style.cljs
  src/status_im/contexts/chat/messenger/photo_selector/album_selector/view.cljs
  src/status_im/contexts/chat/messenger/photo_selector/style.cljs
Labels: skip-manual-qa, design-review-required

#19343 fix: community spacing issues in token gating community page
  src/quo/components/community/style.cljs
  src/status_im/contexts/communities/overview/style.cljs
  src/status_im/contexts/communities/overview/view.cljs
Labels: skip-manual-qa, design-review-required

#19523 updated standard auth drawer title size and weight
  src/status_im/common/standard_authentication/enter_password/view.cljs
Labels: skip-manual-qa, design-review-required

#19622 fix: rewire legacy community share button to send invites
  src/legacy/status_im/ui/screens/communities/invite.cljs
Labels: Tested - OK, request-manual-qa

#19618 e2e: fix for sharing community flow
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/chat_view.py
Labels: tests

#19601 fix error is shown after scan button is tapped on the browser page
  src/legacy/status_im/ui/screens/browser/views.cljs
Labels: Tested - OK, request-manual-qa

#19392 feat: add ability to tap to disable from networks in send & bridge flow
  src/quo/components/wallet/network_link/helpers.cljs
  src/quo/components/wallet/network_link/style.cljs
  src/quo/components/wallet/network_link/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/preview/quo/wallet/network_link.cljs
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/common/utils/networks.cljs
  src/status_im/contexts/wallet/common/utils/send.cljs
  src/status_im/contexts/wallet/common/utils/send_test.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/style.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/send/utils_test.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/utils/vector.cljs
  src/utils/vector_test.cljs
Labels: Tested - OK, request-manual-qa

#19593 Prevent exception when viewing contact QR code
  src/utils/address.cljs
  src/utils/address_test.cljs
Labels: Tested - OK, request-manual-qa

#19637 ci: use virtualenv to avoid race conditions
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
Labels: tests, infra, dependencies

#19652 fix error on long tap on token-gated channel from the join community screen
  src/status_im/contexts/communities/overview/view.cljs
Labels: Tested - OK, request-manual-qa

#19559 Implement share button inside profile settings
  src/react_native/core.cljs
  src/react_native/share.cljs
  src/status_im/common/lightbox/effects.cljs
  src/status_im/contexts/chat/home/view.cljs
  src/status_im/contexts/communities/sharing/events.cljs
  src/status_im/contexts/profile/contact/actions/view.cljs
  src/status_im/contexts/profile/contact/share/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/contexts/shell/share/profile/view.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/contexts/wallet/account/share_address/view.cljs
  src/status_im/contexts/wallet/effects.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/events.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#19566 Redirect to community channel when following universal link
  src/status_im/common/router.cljs
  src/status_im/common/router_test.cljs
  src/status_im/common/shared_urls/data_store.cljs
  src/status_im/common/shared_urls/events.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/events.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19583 Wallet: Token Options should be specific to watch only account #18543
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/sheets/buy_token/style.cljs
  src/status_im/contexts/wallet/sheets/buy_token/view.cljs
  src/status_im/feature_flags.cljs
Labels: skip-manual-qa

#19673 Update `doc/troubleshooting.md`
  doc/troubleshooting.md
Labels: skip-manual-qa

#19532 Implement community-detail-token-gating component & use it in permissions sheet
  src/quo/components/community/community_detail_token_gating/component_spec.cljs
  src/quo/components/community/community_detail_token_gating/style.cljs
  src/quo/components/community/community_detail_token_gating/view.cljs
  src/quo/components/tags/collectible_tag/schema.cljs
  src/quo/components/tags/collectible_tag/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/communities/actions/permissions_sheet/style.cljs
  src/status_im/contexts/communities/actions/permissions_sheet/view.cljs
  src/status_im/contexts/preview/quo/community/community_detail_token_gating.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
Labels: Tested - OK, request-manual-qa, design-review-required

#19569 Remove watch-only accounts from bridging
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/bridge/select_asset/view.cljs
Labels: skip-manual-qa

#19672 Fix: nil pointer exception due to dynamic data being treated as a function
  src/status_im/contexts/wallet/events.cljs
Labels: E:Mobile Integration Tests

#19574 fix: pinned messages empty state drawer margin issues
  src/quo/components/empty_state/empty_state/styles.cljs
  src/quo/components/empty_state/empty_state/view.cljs
  src/status_im/contexts/chat/messenger/menus/pinned_messages/style.cljs
  src/status_im/contexts/chat/messenger/messages/pin/events.cljs
Labels: skip-manual-qa, design-review-required

#19507 Update QR code scanner to handle channel and community links
  src/status_im/contexts/shell/qr_reader/view.cljs
Labels: request-manual-qa, test cases required

#19636 fix role is not updated correctly when unselecting accounts
  src/status_im/common/json_rpc/events.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs
Labels: Tested - OK, request-manual-qa

#19686 Show the users that the keycard feature will be coming soon
  src/status_im/contexts/onboarding/new_to_status/view.cljs
Labels: skip-manual-qa

#19647 fix: add external icon to OpenSea button in collectible page
  src/quo/components/buttons/button/view.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
Labels: Tested - OK, request-manual-qa

#19664 swap @react-native-camera-roll/camera-roll fork with patches & upgrade to 7.5.2
  ios/Podfile.lock
  package.json
  patches/CameraRoll.ts.patch
  patches/NativeCameraRollModule.ts.patch
  patches/RNCCameraRoll.mm.patch
  yarn.lock
Labels: Tested - OK, request-manual-qa

#19563 fix: missing author info in reply messages
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa

#19684 e2e: GH report: rerun tests link update
  test/appium/support/base_test_report.py
  test/appium/support/github_report.py
  test/appium/support/test_data.py
  test/appium/support/testrail_report.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/test_wallet.py
  test/appium/tests/marks.py
Labels: tests

#19612 Fix timestamp for restored accounts
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#19688 swap react-native-mail fork with patch
  package.json
  patches/react-native-mail-build.gradle.patch
  yarn.lock
Labels: skip-manual-qa

#19528 Wallet (collectibles) - integrate new Collectible list item component into designs #19140
  src/quo/components/avatars/collection_avatar/view.cljs
  src/quo/components/profile/collectible_list_item/component_spec.cljs
  src/quo/components/profile/collectible_list_item/style.cljs
  src/quo/components/profile/collectible_list_item/view.cljs
  src/quo/components/profile/expanded_collectible/component_spec.cljs
  src/quo/components/profile/expanded_collectible/view.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/profile/collectible_list_item.cljs
  src/status_im/contexts/preview/quo/profile/expanded_collectible.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/send/select_collectible_amount/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#19690 JC/Fraschetti - Feature flag descoped features from MVP to streamline initial release
  src/status_im/contexts/wallet/add_account/add_address_to_watch/confirm_address/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/feature_flags.cljs
  src/tests/contract_test/wallet_test.cljs
Labels: skip-manual-qa

#19638 fix: page top is rendering empty avatar icon if no avatar props are sent
  src/quo/components/text_combinations/page_top/view.cljs
Labels: skip-manual-qa

#19603 fix: fix fees calculation and add support for L1 fees for Optimism transactions
  src/status_im/contexts/wallet/common/utils/send.cljs
  src/status_im/contexts/wallet/common/utils/send_test.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
Labels: Tested - OK, request-manual-qa

#19617 [#19182] fix: shell share design feedback
  src/quo/components/share/share_qr_code/view.cljs
  src/status_im/contexts/shell/share/style.cljs
  src/status_im/contexts/shell/share/wallet/component_spec.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  test/appium/tests/critical/test_wallet.py
Labels: skip-manual-qa

#19564 upgrade go to 1.20
  nix/overlay.nix
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#19705 fix: `backup-recovery-phrase` check item pressability
  src/status_im/contexts/wallet/add_account/create_account/new_keypair/backup_recovery_phrase/view.cljs
Labels: skip-manual-qa

#19667 Remove Identity Verification tab in Activity Center
  .env
  src/quo/components/tabs/tabs/view.cljs
  src/status_im/contexts/shell/activity_center/tabs/view.cljs
Labels: skip-manual-qa

#19719 Fix: category settings item separator line color
  src/quo/components/settings/category/settings/view.cljs
  src/quo/components/settings/category/style.cljs
Labels: skip-manual-qa

#19723 [19576] Fix group avatar not showing group picture
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/chats_test.cljs
Labels: skip-manual-qa

#19681 move blur lib fork to a patch
  ios/Podfile.lock
  package.json
  patches/BlurView-build.gradle.patch
  patches/BlurView.ios.tsx.patch
  patches/BlurView.mm.patch
  patches/BlurViewNativeComponent.ts.patch
  patches/VibrancyViewNativeComponent.ts.patch
  yarn.lock
Labels: Tested - OK, request-manual-qa

#19675 Display private permissions only when the requirements are met
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#19751 fix: location of logs generated by fastlane
  fastlane/Fastfile
Labels: ios, infra

#19677 fix channel header is broken when opening channel with chat history after joining the community
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
Labels: Tested - OK, request-manual-qa, design-review-required

#19742 e2e: TR error info and fix for tests rerun
  test/appium/support/base_test_report.py
  test/appium/support/testrail_report.py
Labels: tests

#19505 [Fix] Wallet - Keypair name in the about tab
  src/quo/components/wallet/account_origin/schema.cljs
  src/quo/components/wallet/account_origin/view.cljs
  src/status_im/contexts/wallet/account/tabs/about/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#19679 UI in the upper section of the chat differs from the lower section
  src/status_im/contexts/chat/messenger/messages/list/style.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa, design-review-required

#19755 e2e: false failure fixes 22.04
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/tests/critical/test_wallet.py
Labels: tests

#19695 upgrade react-native-permissions library
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#19761 skip share wallet component test
  src/status_im/contexts/shell/share/wallet/component_spec.cljs
Labels: skip-manual-qa

#19698 [#19183] fix: scan qr design issues
  src/status_im/common/home/top_nav/view.cljs
  src/status_im/common/scan_qr_code/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: skip-manual-qa, design-review-required

#19683 Log signals from the Clojure layer instead of native code
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.kt
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/nodejs/status.cpp
  src/status_im/common/signals/events.cljs
Labels: E:Mobile Developer XP

#19623 Remove support for editing shared addresses while request to join is pending approval
  src/status_im/contexts/communities/actions/accounts_selection/events.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events_test.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/subs/community/account_selection.cljs
  src/status_im/subs/community/account_selection_test.cljs
  translations/en.json
Labels: Tested - OK, blocked, request-manual-qa

#19763 App crashes after sync #19655
  src/legacy/status_im/node/core.cljs
  src/status_im/contexts/chat/home/add_new_contact/events.cljs
  src/status_im/contexts/chat/home/add_new_contact/events_test.cljs
  src/status_im/subs/profile_test.cljs
  src/utils/ethereum/chain.cljs
Labels: Tested - OK, request-manual-qa

#19767 e2e: fixes 23.04
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/tests/critical/test_wallet.py
Labels: tests

#19616 Implement blocked contacts setting inside profile messages settings #…
  src/legacy/status_im/contact/block.cljs
  src/legacy/status_im/contact/db.cljs
  src/legacy/status_im/contact/db_test.cljs
  src/legacy/status_im/events.cljs
  src/legacy/status_im/ui/screens/profile/components/sheets.cljs
  src/legacy/status_im/ui/screens/profile/contact/views.cljs
  src/quo/components/list_items/user.cljs
  src/quo/components/overlay/view.cljs
  src/quo/components/text_combinations/page_top/component_spec.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/common/toasts/events.cljs
  src/status_im/contexts/chat/contacts/events.cljs
  src/status_im/contexts/contact/blocking/events.cljs
  src/status_im/contexts/profile/contact/block_contact/view.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  src/status_im/contexts/profile/contact/unblock_contact/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/profile/settings/screens/messages/blocked_users/view.cljs
  src/status_im/contexts/profile/settings/screens/messages/view.cljs
  src/status_im/contexts/profile/settings/screens/password/view.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/contact.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#19625 [#18816] Import private key main screen UI
  src/quo/components/settings/section_label/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/add_account/create_account/import_private_key/style.cljs
  src/status_im/contexts/wallet/add_account/create_account/import_private_key/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/common/validation.cljs
  src/status_im/feature_flags.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: external, skip-manual-qa

#19668 fix: suggested routes are not calculated with preferred receiver networks
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, test cases added

#19750 Refactoring of token input screen in send flow
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/common/controlled_input/utils.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
Labels: skip-manual-qa

#19771 ⛵ Add menu to reach saved addresses and show empty state
  src/quo/components/text_combinations/standard_title/style.cljs
  src/quo/components/text_combinations/standard_title/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/style.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/view.cljs
  src/status_im/contexts/settings/wallet/wallet_options/style.cljs
  src/status_im/contexts/settings/wallet/wallet_options/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: E:Mobile Wallet Save Address Page MVP, skip-manual-qa

#19760 nuke react-native-mail and move over the logic to our native modules
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/MailManager.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NetworkManager.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/Utils.kt
  modules/react-native-status/android/src/main/res/xml/provider_paths.xml
  modules/react-native-status/ios/RCTStatus/MailManager.h
  modules/react-native-status/ios/RCTStatus/MailManager.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.xcodeproj/project.pbxproj
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
  nix/deps/gradle/proj.list
  package.json
  patches/react-native-mail-build.gradle.patch
  src/legacy/status_im/utils/logging/core.cljs
  src/native_module/core.cljs
  src/react_native/mail.cljs
  yarn.lock
Labels: skip-manual-qa

#19735 Reagent atom from theme regression #19729
  src/legacy/status_im/multiaccounts/create/core.cljs
  src/quo/components/inputs/recovery_phrase/style.cljs
  src/quo/components/inputs/recovery_phrase/view.cljs
  src/quo/components/notifications/notification/view.cljs
  src/quo/components/notifications/toast/view.cljs
  src/quo/components/tags/context_tag/view.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/quo/components/wallet/wallet_overview/view.cljs
  src/status_im/common/emoji_picker/view.cljs
  src/status_im/common/scroll_page/view.cljs
  src/status_im/contexts/communities/discover/view.cljs
  src/status_im/contexts/shell/jump_to/events.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#19562 [#19303] fix: edit profile design feedbacks
  src/status_im/common/validation/profile.cljs
  src/status_im/contexts/profile/edit/bio/events.cljs
  src/status_im/contexts/profile/edit/header/events.cljs
  src/status_im/contexts/profile/edit/style.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa, status-go

#19712 Log revealed addresses in status-go
  status-go-version.json
Labels: status-go, skip-manual-qa

#19700 Implement context action share community QR code
  src/quo/components/gradient/gradient_cover/view.cljs
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/communities/actions/share_community/style.cljs
  src/status_im/contexts/communities/actions/share_community/view.cljs
  src/status_im/navigation/screens.cljs
Labels: followup required, skip-manual-qa, design-review-required

#19789 Fix for "no routes found" on transaction confirmation page
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
Labels: Tested - OK, request-manual-qa

#19702 Wallet: create account using recovery phrase
  src/status_im/common/enter_seed_phrase/style.cljs
  src/status_im/common/enter_seed_phrase/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/events_test.cljs
  src/status_im/contexts/wallet/add_account/create_account/new_keypair/backup_recovery_phrase/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/new_keypair/check_your_backup/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/new_keypair/keypair_name/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/effects.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#19692 Add pairing/unpairing of devices
  src/status_im/contexts/syncing/device/view.cljs
  src/status_im/contexts/syncing/events.cljs
  src/status_im/contexts/syncing/syncing_devices_list/style.cljs
  src/status_im/contexts/syncing/syncing_devices_list/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#19805 fix composer misses shadow and swipe rectangle element
  src/status_im/contexts/chat/messenger/composer/effects.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
Labels: Tested - OK, request-manual-qa

#19800 [#19176] fix: onboarding illustration design issue
  src/status_im/contexts/onboarding/enable_notifications/style.cljs
  src/status_im/contexts/onboarding/enable_notifications/view.cljs
  src/status_im/contexts/onboarding/welcome/style.cljs
  src/status_im/contexts/onboarding/welcome/view.cljs
Labels: skip-manual-qa, design-review-required

#19808 Collectible spinner always shown for users without collectibles #19757
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
Labels: Tested - OK, request-manual-qa

#19814 The 'apply changes' button is enabled in all networks are disabling if 'edit receiver networks' drawer #19778
  src/quo/components/wallet/network_link/schema.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
Labels: Tested - OK, request-manual-qa

#19716 Watch-only address balance should not be included in the overall balance by default #19657
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#19579 Wallet - add opensea link to collecibles overview call to action button
  src/status_im/config.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/contexts/wallet/account/share_address/view.cljs
  src/status_im/contexts/wallet/add_account/add_address_to_watch/events.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/collectible/utils_test.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils/networks.cljs
  src/status_im/contexts/wallet/common/utils/networks_test.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#19773 fix alert banner issues
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  src/legacy/status_im/events.cljs
  src/legacy/status_im/ui/components/react.cljs
  src/legacy/status_im/ui/screens/profile/user/edit_picture.cljs
  src/react_native/image_crop_picker.cljs
  src/status_im/common/alert_banner/events.cljs
  src/status_im/common/alert_banner/view.cljs
  src/status_im/common/floating_button_page/component_spec.cljs
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/common/image_crop_picker/events.cljs
  src/status_im/common/lightbox/view.cljs
  src/status_im/config.cljs
  src/status_im/contexts/chat/messenger/composer/actions/view.cljs
  src/status_im/contexts/chat/messenger/composer/keyboard.cljs
  src/status_im/contexts/chat/messenger/composer/utils.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
  src/status_im/contexts/profile/edit/bio/view.cljs
  src/status_im/contexts/profile/edit/name/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/shell/jump_to/shared_values.cljs
  src/status_im/contexts/shell/jump_to/view.cljs
  src/status_im/contexts/wallet/add_account/add_address_to_watch/component_spec.cljs
  src/status_im/contexts/wallet/add_account/add_address_to_watch/confirm_address/component_spec.cljs
  src/status_im/subs/alert_banner.cljs
  src/status_im/subs/alert_banner_test.cljs
  src/status_im/subs/root.cljs
Labels: request-manual-qa

#19795 Feature/remove old screens and code
  src/legacy/status_im/currency/core.cljs
  src/legacy/status_im/currency/core_test.cljs
  src/legacy/status_im/events.cljs
  src/legacy/status_im/ui/components/connectivity/view.cljs
  src/legacy/status_im/ui/screens/about_app/views.cljs
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
  src/legacy/status_im/ui/screens/appearance/views.cljs
  src/legacy/status_im/ui/screens/bug_report.cljs
  src/legacy/status_im/ui/screens/contacts_list/views.cljs
  src/legacy/status_im/ui/screens/currency_settings/styles.cljs
  src/legacy/status_im/ui/screens/currency_settings/views.cljs
  src/legacy/status_im/ui/screens/ens/views.cljs
  src/legacy/status_im/ui/screens/glossary/view.cljs
  src/legacy/status_im/ui/screens/group/styles.cljs
  src/legacy/status_im/ui/screens/group/views.cljs
  src/legacy/status_im/ui/screens/help_center/views.cljs
  src/legacy/status_im/ui/screens/link_previews_settings/views.cljs
  src/legacy/status_im/ui/screens/log_level_settings/views.cljs
  src/legacy/status_im/ui/screens/notifications_settings/views.cljs
  src/legacy/status_im/ui/screens/popover/views.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/legacy/status_im/ui/screens/profile/contact/styles.cljs
  src/legacy/status_im/ui/screens/profile/contact/views.cljs
  src/legacy/status_im/ui/screens/profile/group_chat/views.cljs
  src/legacy/status_im/ui/screens/profile/user/views.cljs
  src/legacy/status_im/ui/screens/qr_scanner/styles.cljs
  src/legacy/status_im/ui/screens/qr_scanner/views.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/legacy/status_im/ui/screens/stickers/styles.cljs
  src/legacy/status_im/ui/screens/stickers/views.cljs
  src/legacy/status_im/ui/screens/sync_settings/views.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/syncing/syncing_devices_list/view.cljs
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
Labels: Tested - OK, request-manual-qa

#19669 fix: community permission context not passing community-id
  src/status_im/contexts/chat/messenger/messages/contact_requests/bottom_drawer/view.cljs
Labels: Tested - OK, request-manual-qa

#19748 [iOS Only] Enable new architecture for react-native
  ios/Podfile
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  nix/mobile/ios/shells/cocoapods.nix
  patches/CameraRollModule.java.patch
  patches/NativeCameraRollModuleSpec.java.patch
Labels: request-manual-qa

#19823 fix: "key pair" spacing
  translations/en.json
Labels: skip-manual-qa

#19829 tidy: remove extra event handler for `:communities/set-airdrop-address`
  src/status_im/contexts/communities/events.cljs
Labels: skip-manual-qa

#19792 Fix QR share screen for community channel
  src/quo/components/share/share_qr_code/schema.cljs
  src/quo/components/share/share_qr_code/view.cljs
  src/status_im/contexts/communities/actions/share_community/view.cljs
  src/status_im/contexts/communities/actions/share_community_channel/style.cljs
  src/status_im/contexts/communities/actions/share_community_channel/view.cljs
  src/status_im/contexts/preview/quo/share/share_qr_code.cljs
Labels: Tested - OK, request-manual-qa
