Repository status-im/status-mobile, pull requests merged in 2024-11, with the labels that each got.

#21467 [#21316] Keycard - Allow user to migrate existing Profile to the new …
  resources/images/ui2/keycard-buy.png
  resources/images/ui2/keycard-migration-failed.png
  resources/images/ui2/keycard-migration-succeeded.png
  resources/images/ui2/keycard-migration.png
  resources/images/ui2/not-keycard.png
  src/keycard/keycard.cljs
  src/native_module/core.cljs
  src/quo/components/keycard/view.cljs
  src/quo/components/markdown/list/style.cljs
  src/quo/components/markdown/list/view.cljs
  src/quo/components/text_combinations/page_top/style.cljs
  src/quo/components/text_combinations/standard_title/view.cljs
  src/status_im/common/metrics_confirmation_modal/style.cljs
  src/status_im/common/resources.cljs
  src/status_im/common/standard_authentication/enter_password/view.cljs
  src/status_im/common/standard_authentication/password_input/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/keycard/authorise/view.cljs
  src/status_im/contexts/keycard/check/view.cljs
  src/status_im/contexts/keycard/effects.cljs
  src/status_im/contexts/keycard/empty/view.cljs
  src/status_im/contexts/keycard/error/view.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/login/events.cljs
  src/status_im/contexts/keycard/migrate/events.cljs
  src/status_im/contexts/keycard/migrate/fail/view.cljs
  src/status_im/contexts/keycard/migrate/re_encrypting/events.cljs
  src/status_im/contexts/keycard/migrate/re_encrypting/view.cljs
  src/status_im/contexts/keycard/migrate/sheets/view.cljs
  src/status_im/contexts/keycard/migrate/success/view.cljs
  src/status_im/contexts/keycard/migrate/view.cljs
  src/status_im/contexts/keycard/nfc/effects.cljs
  src/status_im/contexts/keycard/nfc/events.cljs
  src/status_im/contexts/keycard/nfc/sheets/events.cljs
  src/status_im/contexts/keycard/nfc/sheets/view.cljs
  src/status_im/contexts/keycard/not_keycard/view.cljs
  src/status_im/contexts/keycard/pin/create/view.cljs
  src/status_im/contexts/keycard/pin/events.cljs
  src/status_im/contexts/keycard/pin/view.cljs
  src/status_im/contexts/keycard/sign/events.cljs
  src/status_im/contexts/keycard/utils.cljs
  src/status_im/contexts/profile/login/effects.cljs
  src/status_im/contexts/profile/profiles/view.cljs
  src/status_im/contexts/settings/keycard/view.cljs
  src/status_im/contexts/settings/privacy_and_security/share_usage/view.cljs
  src/status_im/navigation/options.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/navigation/view.cljs
  translations/en.json
Labels: request-manual-qa, keycard

#21504 fix(wallet)_: Chain prefix for ENS resolved address
  src/status_im/contexts/wallet/events.cljs
Labels: Tested - OK, request-manual-qa

#21523 fix(wallet)_: Bridging tx improvements
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#21471 e2e: fixes and skipping waku staging failures
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/sign_in_view.py
Labels: tests

#21472 Github: added Type
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: infra

#21514 Fix wallet action buttons alignment
  resources/images/icons2/20x20/bridge@2x.png
  resources/images/icons2/20x20/bridge@3x.png
  src/quo/components/buttons/wallet_ctas/style.cljs
Labels: Tested - OK, request-manual-qa

#21544 Fix appearance of Create Password and Change Password forms
  src/status_im/contexts/onboarding/create_password/view.cljs
  src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs
Labels: skip-manual-qa, mobile-core

#21553 Improve push notification service initialization
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
Labels: Tested - OK, request-manual-qa

#21558 Keycard - enter pin screen
  src/status_im/contexts/keycard/migrate/events.cljs
  src/status_im/contexts/keycard/migrate/profile_keys/view.cljs
  src/status_im/contexts/keycard/migrate/view.cljs
  src/status_im/contexts/keycard/pin/create/view.cljs
  src/status_im/contexts/keycard/pin/enter/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/keycard.cljs
  translations/en.json
Labels: skip-manual-qa, keycard

#21548 Fix: only display spectated communities in opened tab
  src/status_im/subs/communities.cljs
Labels: Tested - OK, request-manual-qa, community, test cases required, mobile-core

#21518 fix(swap): refetch swap proposal when switching account
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/sheets/select_account/view.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/subs/wallet/swap.cljs
Labels: Tested - OK, request-manual-qa

#21604 chore(perf): Do not convert response from wakuext_startMessenger to CLJS
  src/status_im/contexts/profile/login/events.cljs
Labels: performance

#21597 [#18554] incorrect drawer for non community members
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/contexts/chat/messenger/messages/drawers/view.cljs
  src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs
  src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/view.cljs
Labels: Tested - OK, request-manual-qa

#21608 Remove onboarding generating keys screen
  src/status_im/constants.cljs
  src/status_im/contexts/onboarding/common/background/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/onboarding/generating_keys/style.cljs
  src/status_im/contexts/onboarding/generating_keys/view.cljs
  src/status_im/contexts/onboarding/preparing_status/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21534 [#20828] feat: display toast for all wallet connect actions
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs
  src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/data_store.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/data_store_test.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#21588 [#21587] Unsupported light theme on Keycard profile key pair migration
  src/status_im/contexts/keycard/migrate/events.cljs
  src/status_im/contexts/profile/backup_recovery_phrase/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, keycard

#21593 feature!: add maximum character limit to password length
  src/status_im/common/password_with_hint/style.cljs
  src/status_im/common/password_with_hint/view.cljs
  src/status_im/common/validation/password.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/onboarding/create_password/view.cljs
  src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs
  src/utils/string.cljs
  translations/en.json
Labels: Tested - OK, onboarding, request-manual-qa, profile, mobile-core

#21621 e2e: fix for fallback tests
  test/appium/views/sign_in_view.py
Labels: tests

#21532 Swap: use correct fee on spending cap screen
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/sheets/select_asset/asset_list/view.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/status_im/subs/wallet/dapps/transactions.cljs
  src/status_im/subs/wallet/swap.cljs
  src/status_im/subs/wallet/swap_test.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#21542 Wallet design review fixes
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils/networks.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/sheets/slippage_settings/view.cljs
  src/utils/money.cljs
Labels: Tested - OK, request-manual-qa

#21589 Fix keycard L1-L1 transaction failing
  src/status_im/contexts/keycard/sign/events.cljs
Labels: Tested - OK, request-manual-qa

#21484 Wallet status badge for offline RPC handling
  src/quo/components/navigation/top_nav/view.cljs
  src/quo/components/tags/network_status_tag/component_spec.cljs
  src/quo/components/tags/network_status_tag/style.cljs
  src/quo/components/tags/network_status_tag/view.cljs
  src/quo/core.cljs
  src/status_im/common/home/top_nav/view.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/preview/quo/tags/network_status_tag.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/signals.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/utils/datetime.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21635 fix(wallet)_: Paraswap contract address
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/subs/wallet/swap.cljs
Labels: Tested - OK, request-manual-qa

#21612 [#21559] Keycard - Fresh install sign in
  src/status_im/contexts/keycard/check/view.cljs
  src/status_im/contexts/keycard/effects.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/login/events.cljs
  src/status_im/contexts/keycard/nfc/events.cljs
  src/status_im/contexts/keycard/pin/view.cljs
  src/status_im/contexts/keycard/utils.cljs
  src/status_im/contexts/onboarding/create_or_sync_profile/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/settings/keycard/view.cljs
  src/status_im/feature_flags.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup-required, status-go, keycard

#21546 Use latest watchman
  .watchmanconfig
  nix/overlay.nix
  nix/pkgs/watchman/README.md
  nix/pkgs/watchman/default.nix
Labels: skip-manual-qa

#21643 fix Unable to tap on chats/channels after opening profile link
  src/legacy/status_im/qr_scanner/core.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#21657 Custom Option Menu for TX Parameters on SEND Flow
  src/quo/components/settings/settings_item/view.cljs
  src/status_im/contexts/preview/quo/settings/settings_item.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/transaction_settings/style.cljs
  src/status_im/contexts/wallet/send/transaction_settings/view.cljs
  src/status_im/feature_flags.cljs
Labels: Tested - OK, request-manual-qa

#21611 [#21557] feat: show from account page in swap flow
  src/quo/components/list_items/account/schema.cljs
  src/quo/components/list_items/account/style.cljs
  src/quo/components/list_items/account/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils/networks.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/select_account/style.cljs
  src/status_im/contexts/wallet/swap/select_account/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/networks.cljs
  src/status_im/subs/wallet/swap.cljs
Labels: Tested - OK, request-manual-qa, test cases added

#21666 e2e: false failures fixes
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_fallback.py
  test/appium/views/sign_in_view.py
Labels: tests

#21623 [#21573] Keycard - Sign up with a new Keycard
  src/status_im/contexts/keycard/create/events.cljs
  src/status_im/contexts/keycard/create/view.cljs
  src/status_im/contexts/keycard/empty/view.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/onboarding/create_or_sync_profile/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required, keycard

#21594 fix: add spacing between wrong-password error and forgot-password link
  src/status_im/common/standard_authentication/password_input/style.cljs
Labels: skip-manual-qa, mobile-core

#21625 Replace `GetWalletToken` endpoint with `FetchOrGetCachedWalletBalances`
  src/legacy/status_im/utils/prices.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events_test.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/contexts/wallet/sheets/select_asset/asset_list/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/tokens/events.cljs
  src/status_im/subs/wallet/dapps/transactions.cljs
  src/status_im/subs/wallet/send.cljs
  src/status_im/subs/wallet/send_test.cljs
  src/status_im/subs/wallet/swap.cljs
  src/status_im/subs/wallet/swap_test.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
  src/tests/contract_test/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#21694 e2e: fix for fallback tests
  test/appium/views/sign_in_view.py
Labels: tests

#21691 fix: ensure keycard pin error message is visible
  src/quo/components/pin_input/view.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/pin/enter/view.cljs
  src/status_im/contexts/keycard/pin/view.cljs
  src/status_im/contexts/preview/quo/pin_input/pin_input.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, mobile-core, keycard

#21641 [#21436] List of users overlap composer input
  src/status_im/contexts/chat/messenger/composer/mentions/style.cljs
  src/status_im/contexts/chat/messenger/composer/mentions/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#21541 Update sending transaction end point (#21480)
  src/status_im/common/signals/events.cljs
  src/status_im/common/standard_authentication/events.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/effects.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/rpc.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/events_test.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/status_im/contexts/wallet/swap/swap_proposal/style.cljs
  src/status_im/contexts/wallet/swap/swap_proposal/view.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/rpc.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/signing.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/transactions.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/typed_data.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/swap.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - Issues, request-manual-qa, status-go

#21695 fix(wallet)_: error on tapping from/to section in tx confirmation screen
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa

#21697 [#21644] fix: display zero for empty balances asset
  src/status_im/contexts/wallet/common/utils.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21549 fix(swap): optimize endpoints calls
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
Labels: Tested - OK, request-manual-qa

#21690 feat(wallet)_: Show buy and receive CTAs on zero balance
  resources/images/ui2/buy@2x.png
  resources/images/ui2/buy@3x.png
  resources/images/ui2/receive@2x.png
  resources/images/ui2/receive@3x.png
  src/quo/components/cards/wallet_card/component_spec.cljs
  src/quo/components/cards/wallet_card/schema.cljs
  src/quo/components/cards/wallet_card/style.cljs
  src/quo/components/cards/wallet_card/view.cljs
  src/quo/core.cljs
  src/status_im/common/resources.cljs
  src/status_im/contexts/preview/quo/cards/wallet_card.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/wallet/home/tabs/assets/style.cljs
  src/status_im/contexts/wallet/home/tabs/assets/view.cljs
  src/status_im/subs/wallet/wallet.cljs
  translations/en.json
Labels: request-manual-qa, wallet-core
