Repository status-im/status-mobile, pull requests merged in 2024-01, with the labels that each got.

#18148 Share screen design review
  src/status_im/contexts/shell/share/events.cljs
  src/status_im/contexts/shell/share/style.cljs
Labels: Tested - OK, request-manual-qa

#18267 Wallet: crypto max decimals
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, E:Mobile Wallet MVP, test cases are required

#18379 e2e: enabled tests for pinning messages
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
Labels: tests

#18320 Kotlinify some of react-native-status android module
  modules/react-native-status/android/build.gradle
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/RNSelectableTextInputModule.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/RNSelectableTextInputModule.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/RNSelectableTextInputViewManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/RNSelectableTextInputViewManager.kt
Labels: Tested - OK, request-manual-qa

#18326 fix: error is shown when asset is selected on select assets screen
  src/status_im/contexts/wallet/send/input_amount/view.cljs
Labels: Tested - OK, request-manual-qa

#18399 e2e: added checks for non-token gated community channels
  test/appium/tests/critical/chats/test_public_chat_browsing.py
Labels: tests

#18384 Use text-combinations/page-top component in request to join sheet.
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
Labels: skip-manual-qa

#18364 fix: generate_profile_url crash when login
  src/schema/core.clj
  src/status_im/common/universal_links.cljs
  src/status_im/common/universal_links_test.cljs
  src/status_im/contexts/chat/messages/link_preview/events.cljs
  src/status_im/contexts/chat/messages/link_preview/events_test.cljs
Labels: skip-manual-qa

#18382 Communities: Share Selective Account
  src/quo/components/wallet/account_permissions/view.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/style.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/subs/root.cljs
  translations/en.json
Labels: followup required, skip-manual-qa

#18324 fix: fix navigation after creating an account or watch only account
  src/status_im/contexts/wallet/events.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#18330 fix: increase numbered keyboard touchable area
  src/quo/components/numbered_keyboard/keyboard_key/view.cljs
Labels: Tested - OK, request-manual-qa

#18392 fix: community buttons
  src/status_im/contexts/communities/actions/community_rules_list/style.cljs
  src/status_im/contexts/communities/actions/community_rules_list/view.cljs
  src/status_im/contexts/communities/actions/request_to_join/style.cljs
  src/status_im/contexts/communities/actions/request_to_join/view.cljs
  src/status_im/navigation/screens.cljs
Labels: :eyes: design-input-required

#18329 fix: fix height on account card component
  src/quo/components/wallet/account_card/style.cljs
  src/quo/components/wallet/account_card/view.cljs
Labels: Tested - OK, request-manual-qa

#18304 Run integration tests separately from unit tests
  Makefile
  ci/Jenkinsfile.tests
  doc/testing.md
  shadow-cljs.edn
Labels: E:Mobile Integration Tests, skip-manual-qa

#18275 [Feature] Show aggregated tokens and balance in Wallet home
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/common/temp.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/home/tabs/assets/view.cljs
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#18401 ci: upgrade CI hosts to Xcode 15.1
  ci/Jenkinsfile.ios
  nix/overlay.nix
  nix/status-go/mobile/default.nix
Labels: ios, infra, dependencies

#18300 fix delayed display of top bar in chat after sending messages
  src/js/worklets/chat/messages.js
  src/status_im/contexts/chat/messenger/messages/constants.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
Labels: Tested - OK, request-manual-qa

#18372 fix onboarding screens overlap
  src/status_im/contexts/chat/actions/view.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
  src/status_im/contexts/onboarding/new_to_status/view.cljs
  src/status_im/contexts/profile/profiles/view.cljs
Labels: Tested - OK, request-manual-qa

#18270 feat: implement edit profile and change name
  src/quo/components/inputs/input/view.cljs
  src/quo/components/overlay/view.cljs
  src/quo/components/settings/category/settings/view.cljs
  src/quo/components/settings/settings_item/style.cljs
  src/quo/components/settings/settings_item/view.cljs
  src/status_im/common/validation/profile.cljs
  src/status_im/common/validation/profile_test.cljs
  src/status_im/contexts/onboarding/create_profile/view.cljs
  src/status_im/contexts/profile/edit/header/view.cljs
  src/status_im/contexts/profile/edit/list_items.cljs
  src/status_im/contexts/profile/edit/name/events.cljs
  src/status_im/contexts/profile/edit/name/events_test.cljs
  src/status_im/contexts/profile/edit/name/style.cljs
  src/status_im/contexts/profile/edit/name/view.cljs
  src/status_im/contexts/profile/edit/style.cljs
  src/status_im/contexts/profile/edit/view.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/integration_test/profile_test.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup required

#18434 fix: boost checksum issue due to jfrog
  ios/Podfile.lock
  nix/deps/nodejs-patched/default.nix
Labels: skip-manual-qa

#18403 e2e: added check for deleted 1-1 chat history
  src/status_im/contexts/chat/messenger/messages/content/text/view.cljs
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/views/chat_view.py
  test/appium/views/profile_view.py
Labels: tests

#18258 Biometrics in new settings
  resources/images/icons2/20x20/touch-id@2x.png
  resources/images/icons2/20x20/touch-id@3x.png
  src/status_im/common/biometric/events.cljs
  src/status_im/common/keychain/events.cljs
  src/status_im/common/standard_authentication/events.cljs
  src/status_im/common/standard_authentication/standard_auth/authorize.cljs
  src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/profile/settings/screens/password/style.cljs
  src/status_im/contexts/profile/settings/screens/password/view.cljs
  src/status_im/contexts/syncing/events.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - Issues, request-manual-qa, followup required, test cases are required

#18366 Kotlinify: StatusThreadPoolExecutor
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusThreadPoolExecutor.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusThreadPoolExecutor.kt
Labels: Tested - OK, request-manual-qa

#18109 Add internal-link component for #17116
  src/quo/components/community/community_stat/view.cljs
  src/quo/components/links/internal_link_card/channel/style.cljs
  src/quo/components/links/internal_link_card/channel/view.cljs
  src/quo/components/links/internal_link_card/community/style.cljs
  src/quo/components/links/internal_link_card/community/view.cljs
  src/quo/components/links/internal_link_card/component_spec.cljs
  src/quo/components/links/internal_link_card/schema.cljs
  src/quo/components/links/internal_link_card/user/style.cljs
  src/quo/components/links/internal_link_card/user/view.cljs
  src/quo/components/links/internal_link_card/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/links/internal_link_card.cljs
  src/status_im/contexts/preview/quo/main.cljs
Labels: :eyes: design-input-required

#18426 fix: profile screen initial avatar alignment
  src/status_im/subs/profile.cljs
  src/utils/image_server.cljs
  src/utils/image_server_test.cljs
Labels: Tested - OK, request-manual-qa

#18430 Move selected addresses for permissions to app db
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/subs/root.cljs
Labels: skip-manual-qa

#18337 Refactor: kotlinify log
  modules/react-native-status/android/src/test/java/android/util/Log.java
  modules/react-native-status/android/src/test/java/android/util/Log.kt
Labels: Tested - OK, request-manual-qa

#18339 Refactor composer
  src/js/worklets/chat/messages.js
  src/status_im/common/home/actions/view.cljs
  src/status_im/contexts/chat/effects.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/messenger/composer/actions/view.cljs
  src/status_im/contexts/chat/messenger/composer/handlers.cljs
  src/status_im/contexts/chat/messenger/composer/sub_view.cljs
  src/status_im/contexts/chat/messenger/composer/utils.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/state.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
  src/utils/worklets/chat/messages.cljs
Labels: Tested - OK, request-manual-qa

#18269 Implement about tab on collectible page
  src/quo/components/profile/link_card/view.cljs
  src/status_im/contexts/wallet/collectible/style.cljs
  src/status_im/contexts/wallet/collectible/tabs/about/style.cljs
  src/status_im/contexts/wallet/collectible/tabs/about/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/activity/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/overview/style.cljs
  src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/temp.cljs
  src/status_im/subs/wallet/collectibles.cljs
  src/status_im/subs/wallet/collectibles_test.cljs
  translations/en.json
Labels: skip-manual-qa

#18325 fix: route not found when attempting to transfer assets to own accounts
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa

#18446 fix: random local `make run-ios` failures
  Makefile
Labels: skip-manual-qa

#18381 [#18362] Add support Reanimated inline styles
  src/quo/components/buttons/slide_button/style.cljs
  src/react_native/reanimated.cljs
  src/status_im/contexts/chat/messenger/composer/images/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/album/view.cljs
  src/status_im/contexts/profile/settings/header/style.cljs
  src/status_im/contexts/shell/jump_to/components/bottom_tabs/style.cljs
  src/utils/transforms.cljs
Labels: Tested - OK, request-manual-qa

#18464 fix: don't show trace message when default is set
  Makefile
  nix/lib/getEnvWithDefault.nix
Labels: nix, skip-manual-qa

#18389 fix improper use of current-chat-id and rename subs
  src/legacy/status_im/group_chats/core.cljs
  src/legacy/status_im/ui/screens/chat/group.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/contexts/chat/group_details/view.cljs
  src/status_im/contexts/chat/home/view.cljs
  src/status_im/contexts/chat/messenger/menus/pinned_messages/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/communities/actions/chat/view.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/contact.cljs
Labels: Tested - OK, request-manual-qa

#18435 Fix: incorrect props passed to RN's style prop
  src/status_im/contexts/onboarding/common/background/view.cljs
  src/status_im/contexts/onboarding/intro/style.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
Labels: E:Mobile Bug MVP, skip-manual-qa

#18472 Fix: add back missing clj-kondo config files
  .zprintrc
  Makefile
Labels: E:Mobile Developer XP

#18475 fix: resolve to metro version 0.79.1
  package.json
  yarn.lock
Labels: E:Mobile Developer XP, skip-manual-qa

#18404 #[16978] Select collectible to send
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/subs/wallet/collectibles.cljs
  src/status_im/subs/wallet/wallet.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#18314 fixed dark border around the community logo
  src/status_im/common/scroll_page/style.cljs
  src/status_im/common/scroll_page/view.cljs
Labels: Tested - OK, request-manual-qa

#18385 Refactor native modules into separate modules
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/AccountManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/DatabaseManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/EncryptionUtils.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/LogManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/NetworkManager.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/UIHelper.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/Utils.java
  modules/react-native-status/ios/RCTStatus/AccountManager.h
  modules/react-native-status/ios/RCTStatus/AccountManager.m
  modules/react-native-status/ios/RCTStatus/DatabaseManager.h
  modules/react-native-status/ios/RCTStatus/DatabaseManager.m
  modules/react-native-status/ios/RCTStatus/EncryptionUtils.h
  modules/react-native-status/ios/RCTStatus/EncryptionUtils.m
  modules/react-native-status/ios/RCTStatus/LogManager.h
  modules/react-native-status/ios/RCTStatus/LogManager.m
  modules/react-native-status/ios/RCTStatus/NetworkManager.h
  modules/react-native-status/ios/RCTStatus/NetworkManager.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.xcodeproj/project.pbxproj
  modules/react-native-status/ios/RCTStatus/UIHelper.h
  modules/react-native-status/ios/RCTStatus/UIHelper.m
  modules/react-native-status/ios/RCTStatus/Utils.h
  modules/react-native-status/ios/RCTStatus/Utils.m
  scripts/lint/trailing-newline.sh
  src/legacy/status_im/utils/test.cljs
  src/mocks/js_dependencies.cljs
  src/native_module/core.cljs
  src/status_im/constants.cljs
Labels: Tested - OK, request-manual-qa

#18511 Pf share
  .clj-kondo/rewrite-clj/rewrite-clj/config.edn
  .clj-kondo/taoensso/encore/config.edn
  .clj-kondo/taoensso/encore/taoensso/encore.clj
  src/status_im/contexts/shell/share/profile/view.cljs
  src/status_im/contexts/shell/share/view.cljs
  src/status_im/contexts/shell/share/wallet/component_spec.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/contexts/wallet/receive/view.cljs
  src/status_im/core_spec.cljs
  test/jest/jestSetup.js
Labels: Tested - OK, external-c

#18429 Wallet: send token from drawer
  src/quo/components/list_items/token_network/style.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18516 import of https://github.com/status-im/status-mobile/pull/18271
  src/legacy/status_im/data_store/chats.cljs
  src/legacy/status_im/data_store/chats_test.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/communities/actions/chat/view.cljs
  src/status_im/contexts/communities/events.cljs
  translations/en.json
Labels: external

#18363 fix: handle deep link too early when onboarding
  src/status_im/contexts/profile/login/events.cljs
Labels: Tested - OK, request-manual-qa

#18473 feat: add ability to send collectibles from wallet
  src/quo/components/wallet/summary_info/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/preview/quo/wallet/summary_info.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/select_address/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/style.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/transaction_progress/view.cljs
  src/status_im/subs/wallet/send.cljs
Labels: Tested - OK, feature, request-manual-qa, test cases are required

#18481 feat: add ability to send erc20 tokens
  src/status_im/contexts/wallet/send/events.cljs
Labels: Tested - OK, feature, request-manual-qa, test cases are required

#18487 chore: upgrade `kotlinPluginVersion` to `1.9.0`
  android/gradle.properties
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/generate.sh
Labels: Tested - OK, request-manual-qa

#18521 fix double @@ in `component-test-watch` and don't do `yarn install` for component tests
  Makefile
Labels: E:Mobile Developer XP, skip-manual-qa

#18402 fixed spacing between the header and illustration on biometrics page
  src/status_im/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im/contexts/onboarding/enable_biometrics/view.cljs
Labels: Tested - OK, request-manual-qa

#18444 Wallet - Account switcher - add Share Account functionality #18376
  src/status_im/contexts/wallet/account/tabs/about/view.cljs
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/common/sheets/account_options/view.cljs
  src/status_im/contexts/wallet/effects.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/share_address/style.cljs
  src/status_im/contexts/wallet/share_address/view.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#18089 Composer size when re-entering with unfinished multiline message
  src/status_im/contexts/chat/messenger/composer/effects.cljs
  src/status_im/contexts/chat/messenger/composer/gradients/style.cljs
  src/status_im/contexts/chat/messenger/composer/gradients/view.cljs
  src/status_im/contexts/chat/messenger/composer/handlers.cljs
Labels: request-manual-qa

#18437 fixed incorrect space between name and message card in selected messa…
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa

#18398 Wallet - Add token filter and prices fallback for fiat amount calculation
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/data_store.cljs
Labels: Tested - OK, request-manual-qa

#18465 feat: re-fetch community info in community overview and channel
  src/legacy/status_im/events.cljs
  src/legacy/status_im/ui/screens/chat/message/legacy_view.cljs
  src/status_im/common/router.cljs
  src/status_im/common/serialization.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/chat/home/add_new_contact/effects.cljs
  src/status_im/contexts/chat/home/add_new_contact/events.cljs
  src/status_im/contexts/chat/home/add_new_contact/events_test.cljs
  src/status_im/contexts/chat/messenger/messages/link_preview/events.cljs
  src/status_im/contexts/chat/messenger/messages/link_preview/events_test.cljs
  src/status_im/contexts/chat/messenger/messages/link_preview/view.cljs
  src/status_im/contexts/communities/actions/token_gating/view.cljs
  src/status_im/contexts/communities/discover/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/home/view.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/contexts/shell/activity_center/notification/community_request/view.cljs
  src/status_im/contexts/shell/jump_to/components/switcher_cards/view.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/root.cljs
Labels: Tested - OK, request-manual-qa

#18191 Messages — design review
  resources/images/ui2/no-contacts-to-chat-dark@2x.png
  resources/images/ui2/no-contacts-to-chat-dark@3x.png
  resources/images/ui2/no-contacts-to-chat-light@2x.png
  resources/images/ui2/no-contacts-to-chat-light@3x.png
  src/quo/components/list_items/user.cljs
  src/quo/components/messages/author/style.cljs
  src/quo/components/messages/author/view.cljs
  src/quo/core.cljs
  src/react_native/section_list.cljs
  src/status_im/common/contact_list/style.cljs
  src/status_im/common/contact_list/view.cljs
  src/status_im/common/contact_list_item/view.cljs
  src/status_im/common/resources.cljs
  src/status_im/contexts/chat/actions/view.cljs
  src/status_im/contexts/chat/home/add_new_contact/style.cljs
  src/status_im/contexts/chat/home/new_chat/view.cljs
  src/status_im/contexts/chat/home/view.cljs
  src/status_im/contexts/communities/discover/view.cljs
  src/status_im/contexts/preview/quo/community/list_item.cljs
  src/status_im/contexts/preview/quo/list_items/user_list.cljs
  src/status_im/contexts/preview/quo/main.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#18541 fix: crash when selecting a collectible
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
Labels: Tested - OK, request-manual-qa

#18570 fix: do not show community view until it's loaded
  src/status_im/contexts/communities/overview/view.cljs
Labels: skip-manual-qa

#18571 refactor: move perm/airdrop addrs into community
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/root.cljs
Labels: skip-manual-qa

#18433 [Fix] Currency on recovered profile
  src/legacy/status_im/data_store/settings.cljs
  src/status_im/contexts/profile/events.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18551 Remove the last remaining reagent atom from the messages/view file
  src/status_im/contexts/chat/messenger/composer/effects.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
  src/status_im/contexts/chat/messenger/placeholder/view.cljs
  src/utils/worklets/chat/messenger/navigation.cljs
  src/utils/worklets/chat/messenger/placeholder.cljs
Labels: Tested - OK, request-manual-qa

#18174 [#17873] - Add support to display token images in token gated communities
  src/quo/components/community/token_gating.cljs
  src/quo/components/tags/token_tag/view.cljs
  src/quo/components/utilities/token/view.cljs
Labels: Tested - OK, request-manual-qa

#18539 Wallet: token input conversion
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
Labels: Tested - OK, request-manual-qa

#18503 QR code background gradient
  src/quo/components/gradient/gradient_cover/style.cljs
  src/quo/components/gradient/gradient_cover/view.cljs
  src/quo/components/share/share_qr_code/style.cljs
  src/quo/components/share/share_qr_code/view.cljs
  src/status_im/contexts/shell/share/profile/view.cljs
  src/status_im/contexts/shell/share/style.cljs
  src/status_im/contexts/shell/share/view.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
  src/status_im/contexts/wallet/share_address/view.cljs
Labels: Tested - OK, external

#18506 feat(wallet): connect backend to transaction progress page
  src/legacy/status_im/ethereum/subscriptions.cljs
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/transaction_progress/view.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/send/utils_test.cljs
  src/status_im/contexts/wallet/signals.cljs
  src/status_im/core.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/send.cljs
  src/status_im/subs/wallet/send_test.cljs
  src/status_im/subs/wallet/wallet.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases are required

#18556 fix: remove quo preview from nightly builds
  src/quo/components/settings/category/settings/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
Labels: Tested - OK, request-manual-qa

#18518 [#18421] Wallet - remove account confirmation
  src/quo/components/drawers/drawer_top/view.cljs
  src/quo/components/settings/data_item/view.cljs
  src/status_im/contexts/wallet/common/sheets/account_options/view.cljs
  src/status_im/contexts/wallet/common/sheets/remove_account/style.cljs
  src/status_im/contexts/wallet/common/sheets/remove_account/view.cljs
  src/status_im/contexts/wallet/edit_account/view.cljs
  translations/en.json
Labels: Tested - OK, external

#18567 fix cannot add existing ENS owned by user
  src/legacy/status_im/ens/core.cljs
Labels: Tested - OK, request-manual-qa

#18520 [#18458] Token input fixes
  src/quo/components/wallet/token_input/style.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/contexts/preview/quo/preview.cljs
  src/status_im/contexts/preview/quo/wallet/token_input.cljs
Labels: Tested - OK, request-manual-qa

#18448 Add scroll view to profile tab
  src/status_im/contexts/shell/share/profile/view.cljs
Labels: Tested - OK, request-manual-qa

#18515 fix: make identifier carousel swipe-able
  src/status_im/contexts/onboarding/identifiers/profile_card/view.cljs
  src/status_im/contexts/onboarding/identifiers/style.cljs
  src/status_im/contexts/onboarding/identifiers/view.cljs
Labels: Tested - OK, :eyes: design-input-required, request-manual-qa

#18456 Wallet - Refresh tokens and prices
  src/legacy/status_im/ethereum/subscriptions.cljs
  src/status_im/contexts/wallet/events.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18397 [17514] Use OS emojis in emoji picker
  src/quo/components/selectors/react_selector/view.cljs
  src/quo/components/selectors/reaction_resource.cljs
  src/quo/components/selectors/reactions_selector/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/reactions/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/contexts/chat/messenger/messages/drawers/style.cljs
  src/status_im/contexts/chat/messenger/messages/drawers/view.cljs
  test/appium/views/chat_view.py
Labels: Tested - OK, request-manual-qa

#18547 quo network_list_item
  src/quo/components/list_items/network_list/component_spec.cljs
  src/quo/components/list_items/network_list/style.cljs
  src/quo/components/list_items/network_list/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/list_items/network_list.cljs
  src/status_im/contexts/preview/quo/main.cljs
Labels: external

#18509 Update default wallet name
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#18580 fixed: mute-icon when channel is muted
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#18605 fix: xcbeautify but without omitting crucial logs
  Makefile
Labels: E:Mobile Developer XP, skip-manual-qa

#18599 No ability to enter/paste assets exceeds the users's balance #18526
  src/quo/components/wallet/token_input/style.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/contexts/preview/quo/wallet/token_input.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
Labels: Tested - OK, request-manual-qa

#18572 fix: fix button color on input amount screen
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa

#18585 fix: fix slide button padding on transaction confirmation page
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/contexts/wallet/add_address_to_watch/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/transaction_progress/view.cljs
Labels: Tested - OK, request-manual-qa

#18562 The collectibles are not supported on Optimism and Arbitrum #18507
  src/status_im/contexts/wallet/events/collectibles.cljs
  src/status_im/subs/wallet/networks_test.cljs
  src/utils/ethereum/chain.cljs
  src/utils/ethereum/chain_test.cljs
Labels: Tested - OK, request-manual-qa

#18449 Implement collectible image preview
  src/status_im/common/lightbox/animations.cljs
  src/status_im/common/lightbox/bottom_view.cljs
  src/status_im/common/lightbox/constants.cljs
  src/status_im/common/lightbox/effects.cljs
  src/status_im/common/lightbox/events.cljs
  src/status_im/common/lightbox/style.cljs
  src/status_im/common/lightbox/text_sheet/style.cljs
  src/status_im/common/lightbox/text_sheet/utils.cljs
  src/status_im/common/lightbox/text_sheet/view.cljs
  src/status_im/common/lightbox/top_view.cljs
  src/status_im/common/lightbox/utils.cljs
  src/status_im/common/lightbox/view.cljs
  src/status_im/common/lightbox/zoomable_image/constants.cljs
  src/status_im/common/lightbox/zoomable_image/style.cljs
  src/status_im/common/lightbox/zoomable_image/utils.cljs
  src/status_im/common/lightbox/zoomable_image/view.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/messenger/lightbox/events.cljs
  src/status_im/contexts/chat/messenger/messages/content/album/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/image/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/lightbox/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/lightbox/utils.cljs
  src/status_im/contexts/chat/messenger/messages/content/lightbox/view.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/root.cljs
Labels: Tested - OK, request-manual-qa, test cases are required

#18523 Share Screen -> Share Wallet Address -> Indicators
  src/status_im/contexts/shell/share/wallet/style.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
Labels: Tested - OK, request-manual-qa, external

#18629 e2e: updated deep/universal links tests
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/views/chat_view.py
Labels: tests

#18569 chore: remove mock data from wallet and feature flag incomplete features
  src/status_im/config.cljs
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/about/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/activity/view.cljs
  src/status_im/contexts/wallet/create_account/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/temp.cljs
Labels: Tested - OK, request-manual-qa

#18621 fix bottom tabs blur overlay color
  src/status_im/contexts/shell/jump_to/components/bottom_tabs/style.cljs
Labels: skip-manual-qa

#18497 feat: show highest permission role when join community
  src/legacy/status_im/data_store/communities.cljs
  src/quo/components/utilities/token/view.cljs
  src/status_im/contexts/chat/messenger/messages/transport/events.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/style.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/overview/view.cljs
  src/status_im/contexts/communities/utils.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  translations/en.json
Labels: skip-manual-qa

#18577 [#18512] incomplete list of collectibles
  src/quo/components/profile/collectible/view.cljs
  src/quo/components/tabs/tab/view.cljs
  src/react_native/fast_image.cljs
  src/react_native/svg.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/events/collectibles.cljs
  src/status_im/subs/wallet/collectibles.cljs
Labels: Tested - OK, request-manual-qa

#18598 Wallet: Disable long-press feature on tokens in watch-only accounts. #18597
  src/status_im/contexts/wallet/common/token_value/view.cljs
Labels: Tested - OK, request-manual-qa

#18646 e2e: remived xfail marks
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
Labels: tests

#18531 Replace unmaintained biometrics package
  doc/dependencies.md
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/get_projects.sh
  nix/deps/gradle/proj.list
  package.json
  src/mocks/js_dependencies.cljs
  src/react_native/biometrics.cljs
  src/react_native/keychain.cljs
  src/react_native/touch_id.cljs
  src/status_im/common/biometric/events.cljs
  src/status_im/common/keychain/events.cljs
  src/status_im/common/standard_authentication/standard_auth/authorize.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/profile/login/events.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#18643 Fix profile image & customization color for share-qr-code
  src/status_im/contexts/shell/share/profile/view.cljs
Labels: Tested - OK, request-manual-qa

#18656 Remove hacks from darwin nix purge script
  nix/scripts/kill_proc_prompt.sh
  nix/scripts/purge.sh
Labels: nix, skip-manual-qa

#18662 🐰 Fix #18375 - Disappearing tabs when sending assets
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: skip-manual-qa

#18560 Create bridge token page
  src/quo/components/list_items/network_list/view.cljs
  src/status_im/contexts/wallet/account/bridge/view.cljs
  src/status_im/contexts/wallet/account/bridge_to/style.cljs
  src/status_im/contexts/wallet/account/bridge_to/view.cljs
  src/status_im/contexts/wallet/common/temp.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: external

#18620 fix(ios): button overlap
  src/status_im/common/scroll_page/view.cljs
  src/status_im/contexts/communities/discover/style.cljs
  src/status_im/contexts/communities/discover/view.cljs
Labels: :eyes: design-input-required, request-manual-qa

#18633 Account selection: Fix community logo/name not rendered correctly
  src/quo/components/drawers/drawer_top/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs
Labels: E:Mobile Bug MVP

#18504 fix: android shadow
  src/quo/foundations/shadows.cljs
  src/react_native/platform.cljs
Labels: Tested - OK, :eyes: design-input-required, request-manual-qa

#18682 [Fix] Wallet - Route not fetching
  src/status_im/contexts/wallet/send/events.cljs
Labels: Tested - OK, request-manual-qa

#18654 Bring back enable-notifications onboarding screen static image
  src/status_im/common/resources.cljs
Labels: Tested - OK, request-manual-qa
