Repository status-im/status-mobile, pull requests merged in 2024-07, with the labels that each got.

#20555 fix: use "Biometric" instead of Touch ID when no Biometric found
  src/legacy/status_im/events.cljs
  src/status_im/common/biometric/utils.cljs
  translations/en.json
Labels: Tested - OK, Tested - Issues, request-manual-qa, test cases added

#20600 fix can't pair with dApp on android with WalletConnect
  package.json
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/core.cljs
  yarn.lock
Labels: skip-manual-qa

#20603 feat(ci): use s5cmd instead of obsolete s3cmd
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: infra

#20614 fix: Make BigNumber comparator safe against nils and unsupported data types
  src/utils/money.cljs
  src/utils/money_test.cljs
Labels: skip-manual-qa, mobile-core

#20517 fix(communities)_: Buggy scroll behavior in community channel member …
  src/quo/components/list_items/user.cljs
  src/status_im/common/contact_list_item/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/communities/actions/channel_view_details/view.cljs
Labels: Tested - OK, request-manual-qa

#20613 e2e: fixes for community, wallet and removed outdated xfails
  test/appium/support/api/network_api.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
Labels: tests

#20504 feat: add check before syncing doc
  doc/ui-guidelines.md
  src/status_im/common/check_before_syncing/style.cljs
  src/status_im/common/check_before_syncing/view.cljs
  src/status_im/contexts/onboarding/create_or_sync_profile/view.cljs
  src/status_im/contexts/profile/profiles/view.cljs
  src/status_im/contexts/syncing/syncing_devices_list/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, design-review-required

#20546 feat(wallet): sync saved addresses
  src/status_im/contexts/chat/messenger/messages/transport/events.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/events.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/events_test.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/sheets/address_options/view.cljs
  src/status_im/contexts/wallet/data_store.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#20551 Refactor - Info/Info Message component
  src/quo/components/buttons/predictive_keyboard/view.cljs
  src/quo/components/info/info_message.cljs
  src/quo/components/info/info_message/component_spec.cljs
  src/quo/components/info/info_message/style.cljs
  src/quo/components/info/info_message/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/common/password_authentication/view.cljs
  src/status_im/common/standard_authentication/password_input/view.cljs
  src/status_im/contexts/chat/group_create/view.cljs
  src/status_im/contexts/onboarding/create_password/view.cljs
  src/status_im/contexts/onboarding/create_profile/view.cljs
  src/status_im/contexts/preview/quo/info/info_message.cljs
  src/status_im/contexts/preview/quo/notifications/notification.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
  src/status_im/contexts/profile/edit/bio/view.cljs
  src/status_im/contexts/profile/edit/name/view.cljs
  src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs
  src/status_im/contexts/profile/settings/screens/password/change_password/old_password_form.cljs
  src/status_im/contexts/settings/wallet/keypairs_and_accounts/missing_keypairs/import_private_key/view.cljs
  src/status_im/contexts/settings/wallet/keypairs_and_accounts/rename/view.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs
  src/status_im/contexts/wallet/add_account/add_address_to_watch/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/edit_derivation_path/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/key_pair_name/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/view.cljs
  src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa

#20576 Wallet Connect session establish networks
  src/quo/components/settings/data_item/style.cljs
  src/status_im/contexts/preview/quo/settings/data_item.cljs
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/view.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
  src/status_im/subs/wallet/wallet_connect_test.cljs
  translations/en.json
Labels: skip-manual-qa

#20630 e2e: update for Syncing view
  test/appium/views/base_view.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#20570 [#20448] - Fix validation of addresses in send-to screen
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
Labels: Tested - OK, request-manual-qa

#20501 perf_: Remove integrations with signal wakuv2.peerstats
  src/legacy/status_im/subs/root.cljs
  src/legacy/status_im/ui/components/connectivity/view.cljs
  src/legacy/status_im/ui/screens/peers_stats.cljs
  src/legacy/status_im/utils/logging/core.cljs
  src/legacy/status_im/visibility_status_updates/core.cljs
  src/status_im/common/peer_stats/events.cljs
  src/status_im/common/signals/events.cljs
  src/status_im/contexts/profile/settings/visibility_sheet/view.cljs
  src/status_im/db.cljs
  src/status_im/events.cljs
  src/status_im/subs/general.cljs
  src/status_im/subs/profile.cljs
  src/status_im/subs/root.cljs
Labels: Tested - OK, E:Mobile Performance MVP, request-manual-qa

#20621 fix chat screen design issues
  src/status_im/contexts/chat/home/chat_list_item/view.cljs
  src/status_im/contexts/chat/home/view.cljs
Labels: skip-manual-qa, design-review-required

#20602 fix endless loading skeleton for some empty channels on IOS
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#20608 Fix WalletConnect transactions
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/processing_events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/transactions.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
Labels: skip-manual-qa

#20634 fix(ci): add missing import for JsonBuilder
  ci/Jenkinsfile.combined
Labels: infra

#20627 Re-hide connected dapps screen behind a feature flag
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
Labels: skip-manual-qa

#20589 Fix auth slider resetting when wallet connect signing is finished
  src/quo/components/buttons/slide_button/view.cljs
  src/status_im/common/standard_authentication/events.cljs
  src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im/contexts/preview/quo/buttons/slide_button.cljs
Labels: Tested - OK, request-manual-qa

#20519 Fixes for screen where user locks network amounts to send
  src/quo/components/selectors/disclaimer/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/routes/style.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#20400 feat: collectibles details loading
  src/quo/components/profile/collectible_list_item/view.cljs
  src/quo/components/profile/expanded_collectible/style.cljs
  src/quo/components/profile/expanded_collectible/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/collectible/style.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/subs/wallet/collectibles.cljs
Labels: Tested - OK, request-manual-qa

#20569 [#19375] Fix remove modal for seed accounts
  src/status_im/contexts/wallet/sheets/remove_account/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#20641 chore: add Xcode 15.4 to allowed versions
  nix/overlay.nix
Labels: skip-manual-qa

#20642 Added possibility to edit networks list when routes not found
  src/status_im/contexts/wallet/send/events.cljs
Labels: request-manual-qa

#20607 chore(docs)_: include new status-go tagging command in the merging PR process
  doc/merging-pr-process.md
Labels: docs

#20639 Disable possibility to change amounts to send via specific networks
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/feature_flags.cljs
Labels: Tested - OK, request-manual-qa

#20611 fix: ensure the key pair action button opens bottom-sheet inside key pairs and accounts
  src/quo/components/wallet/keypair/view.cljs
Labels: Tested - OK, request-manual-qa

#20550 feat: add support for updating key-pairs and accounts from app signal
  src/status_im/contexts/chat/messenger/messages/transport/events.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/data_store_test.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events_test.cljs
Labels: Tested - OK, request-manual-qa

#20554 Swap: Edit Slippage Drawer
  resources/images/icons2/20x20/percentage@2x.png
  resources/images/icons2/20x20/percentage@3x.png
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/sheets/slippage_settings/style.cljs
  src/status_im/contexts/wallet/sheets/slippage_settings/view.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/swap_proposal/style.cljs
  src/status_im/contexts/wallet/swap/swap_proposal/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/swap.cljs
  src/utils/number.cljs
  src/utils/number_test.cljs
  translations/en.json
Labels: skip-manual-qa

#20640 [#20638] fix: Scan missing keypair keep scanning after success attempt
  src/status_im/common/scan_qr_code/view.cljs
  src/status_im/contexts/settings/wallet/events.cljs
  src/status_im/contexts/settings/wallet/keypairs_and_accounts/missing_keypairs/scan_qr/view.cljs
Labels: Tested - OK, request-manual-qa

#19756 Other checkboxes are unselected when one checkbox is selected on the network preferences bottom sheet #19543
  src/status_im/contexts/wallet/sheets/network_preferences/view.cljs
Labels: Tested - OK, request-manual-qa

#20653 e2e: false failures fixes
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/views/chat_view.py
Labels: tests

#20662 fix wallet send flow wrong status bar color on select assets screen
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#20668 chore(settings): Add boilerplate for the new Privacy and security screen
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/settings/privacy_and_security/style.cljs
  src/status_im/contexts/settings/privacy_and_security/view.cljs
  src/status_im/navigation/screens.cljs
Labels: skip-manual-qa

#20605 fix fail to open database error message when user enters the wrong password
  src/status_im/common/standard_authentication/password_input/view.cljs
Labels: Tested - OK, request-manual-qa

#20663 chore: remove hot reload while theme changing
  src/legacy/status_im/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/settings/effects.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/navigation/events.cljs
Labels: Tested - OK, request-manual-qa

#20647 Add QR scanner to connect Dapps through Connected Dapps screen
  resources/images/dapps/WalletConnect@2x.png
  resources/images/dapps/WalletConnect@3x.png
  src/quo/components/tags/context_tag/schema.cljs
  src/quo/components/tags/context_tag/view.cljs
  src/quo/foundations/resources.cljs
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/connected_dapps/scan_dapp/style.cljs
  src/status_im/contexts/wallet/connected_dapps/scan_dapp/view.cljs
  src/status_im/contexts/wallet/connected_dapps/view.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: skip-manual-qa

#20657 [#20463] Multiple fixes on Collectibles
  src/quo/components/profile/collectible_list_item/style.cljs
  src/quo/components/profile/collectible_list_item/view.cljs
  src/quo/components/profile/expanded_collectible/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/collectible/events_test.cljs
  src/status_im/contexts/wallet/collectible/tabs/about/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs
  src/status_im/contexts/wallet/collectible/tabs/view.cljs
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/subs/wallet/collectibles.cljs
  src/status_im/subs/wallet/collectibles_test.cljs
Labels: Tested - OK, request-manual-qa

#20423 [19759] Import private key - backend integration
  src/status_im/contexts/wallet/add_account/create_account/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/events_test.cljs
  src/status_im/contexts/wallet/add_account/create_account/import_private_key/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/key_pair_name/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/utils.cljs
  src/status_im/contexts/wallet/add_account/create_account/view.cljs
  src/status_im/contexts/wallet/effects.cljs
Labels: external, skip-manual-qa

#20585 [#20543] fix: incorrect black background behind floating button
  src/status_im/common/floating_button_page/floating_container/view.cljs
Labels: Tested - OK, request-manual-qa

#20659 Wallet: fix asset sorting
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#20709 e2e: adding android.gpu.mode capability to fix emulators crash
  test/appium/tests/base_test_case.py
Labels: tests

#20503 chore: remove identifiers screens
  src/status_im/contexts/onboarding/enable_notifications/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/navigation/screens.cljs
  test/appium/views/sign_in_view.py
Labels: Tested - OK, request-manual-qa

#20655 Add centralized metrics
  Makefile
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/AccountManager.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.kt
  modules/react-native-status/ios/RCTStatus/AccountManager.m
  modules/react-native-status/ios/RCTStatus/RCTStatus.m
  modules/react-native-status/nodejs/status.cpp
  scripts/build-android.sh
  shadow-cljs.edn
  src/legacy/status_im/utils/test.cljs
  src/native_module/core.cljs
  src/status_im/config.cljs
  src/status_im/contexts/centralized_metrics/effects.cljs
  src/status_im/contexts/centralized_metrics/events.cljs
  src/status_im/contexts/centralized_metrics/events_test.cljs
  src/status_im/contexts/centralized_metrics/tracking.cljs
  src/status_im/contexts/centralized_metrics/tracking_test.cljs
  src/status_im/contexts/communities/actions/community_options/view.cljs
  src/status_im/contexts/profile/config.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/contexts/settings/privacy_and_security/view.cljs
  src/status_im/setup/interceptors.cljs
  src/status_im/subs/root.cljs
  src/tests/test_utils.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa, status-go

#20648 2️⃣ Use v2 api for persisting sessions
  src/status_im/contexts/wallet/wallet_connect/events.cljs
Labels: skip-manual-qa

#20649 🙅 Gracefully reject proposals and requests
  src/react_native/wallet_connect.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/page_nav/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/send_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_message/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/view.cljs
Labels: skip-manual-qa

#20612 fix(wallet): error message on scanning different key pair QR
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/Utils.kt
  modules/react-native-status/ios/RCTStatus/Utils.m
  src/native_module/core.cljs
  src/status_im/common/pairing/events.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/settings/wallet/events.cljs
  src/status_im/contexts/settings/wallet/events_test.cljs
  src/status_im/contexts/settings/wallet/keypairs_and_accounts/actions/view.cljs
  src/status_im/contexts/syncing/utils.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#20699 fix(saved-addresses): clean QR scanned address
  src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs
Labels: Tested - OK, request-manual-qa

#20671 Revamp legacy Privacy and security settings
  .env
  .env.release
  src/legacy/status_im/events.cljs
  src/legacy/status_im/multiaccounts/update/core.cljs
  src/legacy/status_im/ui/screens/dapps_permissions/styles.cljs
  src/legacy/status_im/ui/screens/dapps_permissions/views.cljs
  src/legacy/status_im/ui/screens/link_previews_settings/styles.cljs
  src/legacy/status_im/ui/screens/link_previews_settings/views.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/delete_profile.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/events.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/messages_from_contacts_only.cljs
  src/legacy/status_im/ui/screens/privacy_and_security_settings/views.cljs
  src/legacy/status_im/ui/screens/profile/user/views.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/quo/components/settings/settings_item/style.cljs
  src/status_im/config.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/contexts/profile/settings/screens/messages/view.cljs
  src/status_im/contexts/settings/privacy_and_security/profile_picture/view.cljs
  src/status_im/contexts/settings/privacy_and_security/view.cljs
  src/status_im/feature_flags.cljs
  src/status_im/subs/profile.cljs
  src/status_im/subs/root.cljs
  src/utils/navigation.cljs
  translations/en.json
Labels: Tested - OK, feature, request-manual-qa, design-review-required

#20619 Fix missing avatar and name in members of the community channels and group chats
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/EncryptionUtils.java
  modules/react-native-status/ios/RCTStatus/EncryptionUtils.m
  modules/react-native-status/nodejs/status.cpp
  src/native_module/core.cljs
  src/status_im/subs/chats.cljs
  src/status_im/subs/contact.cljs
  src/status_im/subs/contact/utils.cljs
  src/tests/test_utils.cljs
Labels: Tested - OK, request-manual-qa

#20665 🎣 Fix wallet connect init issue in release bundles
  src/react_native/wallet_connect.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
Labels: skip-manual-qa

#20558 [#20434] Allow users from v1 to login with keycard
  resources/images/ui2/nfc-prompt@2x.png
  resources/images/ui2/nfc-prompt@3x.png
  resources/images/ui2/nfc-success@2x.png
  resources/images/ui2/nfc-success@3x.png
  src/keycard/keycard.cljs
  src/keycard/real_keycard.cljs
  src/legacy/status_im/utils/keychain/core.cljs
  src/mocks/js_dependencies.cljs
  src/native_module/core.cljs
  src/quo/components/pin_input/pin/view.cljs
  src/quo/components/pin_input/view.cljs
  src/quo/core.cljs
  src/status_im/common/bottom_sheet/view.cljs
  src/status_im/common/keychain/events.cljs
  src/status_im/common/resources.cljs
  src/status_im/common/standard_authentication/events.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/keycard/effects.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/login/events.cljs
  src/status_im/contexts/keycard/pin/events.cljs
  src/status_im/contexts/keycard/pin/view.cljs
  src/status_im/contexts/keycard/sheet/events.cljs
  src/status_im/contexts/keycard/sheet/view.cljs
  src/status_im/contexts/keycard/utils.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/preview/quo/pin_input/pin_input.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/profiles/view.cljs
  src/status_im/db.cljs
  src/status_im/events.cljs
  src/status_im/navigation/core.cljs
  src/status_im/navigation/effects.cljs
  src/status_im/navigation/events.cljs
  src/status_im/navigation/view.cljs
  src/status_im/subs/keycard.cljs
  src/status_im/subs/root.cljs
  src/utils/re_frame.cljs
Labels: Tested - OK, request-manual-qa

#20636 fix: remove non operable accounts in the selection of sharing addresses with the community
  src/status_im/contexts/communities/actions/accounts_selection/events.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events_test.cljs
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/events_test.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/utils.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/data_store_test.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/events_test.cljs
  src/status_im/contexts/wallet/sheets/account_options/view.cljs
  src/status_im/contexts/wallet/sheets/select_account/view.cljs
  src/status_im/subs/community/account_selection.cljs
  src/status_im/subs/community/account_selection_test.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#20656 Settings/Data Item - Subtitle Type: editable
  src/quo/components/settings/data_item/component_spec.cljs
  src/quo/components/settings/data_item/style.cljs
  src/quo/components/settings/data_item/view.cljs
  src/status_im/contexts/preview/quo/settings/data_item.cljs
  src/status_im/contexts/wallet/account/tabs/about/view.cljs
Labels: Tested - OK, request-manual-qa, design-review-required

#20733 fix peer count invisible in Light mode
  src/legacy/status_im/ui/screens/peers_stats.cljs
Labels: skip-manual-qa

#20317 List Items/Approval Info Component
  src/quo/components/avatars/collection_avatar/style.cljs
  src/quo/components/list_items/approval_info/component_spec.cljs
  src/quo/components/list_items/approval_info/style.cljs
  src/quo/components/list_items/approval_info/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/list_items/approval_info.cljs
  src/status_im/contexts/preview/quo/main.cljs
Labels: followup required, skip-manual-qa

#20676 Fix: navigation after transaction from settings
  src/status_im/contexts/settings/wallet/saved_addresses/sheets/address_options/view.cljs
Labels: Tested - OK, request-manual-qa

#20183 fix: hardware induced back actions
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/import_private_key/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/view.cljs
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/from/view.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/send/select_asset/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs
  src/status_im/subs/wallet/send.cljs
Labels: Tested - OK, request-manual-qa

#20689 fix(saved-addresses): grouping and sorting of saved addresses
  src/status_im/subs/wallet/saved_addresses.cljs
Labels: Tested - OK, request-manual-qa

#20669 feat: swap confirmation screen
  src/quo/components/wallet/summary_info/schema.cljs
  src/quo/components/wallet/summary_info/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/style.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/status_im/contexts/wallet/swap/swap_proposal/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/swap.cljs
  translations/en.json
Labels: skip-manual-qa

#20743 e2e: separated tests to run in PRs
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  test/appium/pytest.ini
  test/appium/support/testrail_report.py
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/tests/critical/test_wallet.py
  test/appium/tests/marks.py
  test/appium/views/elements_templates/status_community_join_button.png
  test/appium/views/elements_templates/status_community_logo.png
Labels: tests

#20533 Cover wallet send events with tests #20411
  src/status_im/contexts/wallet/send/events_test.cljs
Labels: skip-manual-qa

#20714 [#20463] Fix iOS can't fetch collectible error
  src/quo/components/profile/expanded_collectible/view.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
Labels: Tested - OK, request-manual-qa

#20615 [#18942] Slideshow/slider bar component
  src/quo/components/slideshow/slider_bar/component_spec.cljs
  src/quo/components/slideshow/slider_bar/schema.cljs
  src/quo/components/slideshow/slider_bar/style.cljs
  src/quo/components/slideshow/slider_bar/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/preview/quo/slideshow/slider_bar.cljs
  src/status_im/contexts/shell/share/wallet/style.cljs
  src/status_im/contexts/shell/share/wallet/view.cljs
Labels: external, skip-manual-qa

#20693 Wallet Connect message signing
  ios/Podfile.lock
  src/legacy/status_im/utils/hex.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/rpc.cljs
  src/status_im/contexts/wallet/wallet_connect/signing.cljs
  src/status_im/contexts/wallet/wallet_connect/transactions.cljs
  src/status_im/subs/wallet/activities.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
  src/utils/hex.cljs
Labels: Tested - OK, request-manual-qa

#20692 Adjust on-boarding illustrations position and scale
  src/quo/components/drawers/bottom_actions/style.cljs
  src/quo/components/drawers/bottom_actions/view.cljs
  src/status_im/contexts/onboarding/common/background/style.cljs
  src/status_im/contexts/onboarding/common/background/view.cljs
  src/status_im/contexts/onboarding/common/carousel/style.cljs
  src/status_im/contexts/onboarding/common/carousel/view.cljs
  src/status_im/contexts/onboarding/enable_biometrics/style.cljs
  src/status_im/contexts/onboarding/generating_keys/style.cljs
  src/status_im/contexts/onboarding/generating_keys/view.cljs
  src/status_im/contexts/onboarding/intro/style.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
Labels: Tested - OK, request-manual-qa

#20703 Improvements on activity tab
  src/quo/components/tags/context_tag/schema.cljs
  src/quo/components/tags/context_tag/style.cljs
  src/quo/components/tags/context_tag/view.cljs
  src/quo/components/wallet/wallet_activity/style.cljs
  src/quo/components/wallet/wallet_activity/view.cljs
  src/status_im/contexts/wallet/common/activity_tab/events.cljs
  src/status_im/contexts/wallet/common/activity_tab/view.cljs
  src/status_im/contexts/wallet/signals.cljs
  src/status_im/subs/wallet/activities.cljs
  src/status_im/subs/wallet/activities_test.cljs
  src/status_im/subs/wallet/send.cljs
  src/status_im/subs/wallet/send_test.cljs
Labels: skip-manual-qa

#20770 Token value shows fiat value on the transaction confirmation page #20734
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa

#20754 [#20742] fix: blue background behind the "Save address" button
  src/status_im/common/floating_button_page/floating_container/style.cljs
  src/status_im/common/floating_button_page/floating_container/view.cljs
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/save_address/view.cljs
Labels: Tested - OK, request-manual-qa

#20690 chore(activity-center): Performance improvements and various superficial refactors
  src/status_im/constants.cljs
  src/status_im/contexts/shell/activity_center/context.cljs
  src/status_im/contexts/shell/activity_center/events.cljs
  src/status_im/contexts/shell/activity_center/notification/admin/view.cljs
  src/status_im/contexts/shell/activity_center/notification/common/style.cljs
  src/status_im/contexts/shell/activity_center/notification/common/view.cljs
  src/status_im/contexts/shell/activity_center/notification/community_kicked/view.cljs
  src/status_im/contexts/shell/activity_center/notification/community_request/view.cljs
  src/status_im/contexts/shell/activity_center/notification/contact_requests/view.cljs
  src/status_im/contexts/shell/activity_center/notification/contact_verification/view.cljs
  src/status_im/contexts/shell/activity_center/notification/membership/view.cljs
  src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs
  src/status_im/contexts/shell/activity_center/notification/reply/view.cljs
  src/status_im/contexts/shell/activity_center/view.cljs
  src/status_im/subs/communities.cljs
Labels: Tested - OK, E:Mobile Performance MVP, request-manual-qa, E:Mobile Activity Center MVP

#20790 e2e: fixes for wallet and deep/universal links tests
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/tests/critical/test_wallet.py
  test/appium/views/wallet_view.py
Labels: tests

#20549 "Share all addresses" for communities
  src/status_im/contexts/communities/actions/accounts_selection/effects.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events_test.cljs
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/overview/events.cljs
  src/status_im/contexts/communities/overview/events_test.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#20711 WC: Persistance update + a bunch of visual bugfixes
  src/quo/components/drawers/bottom_actions/style.cljs
  src/quo/components/drawers/bottom_actions/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/shell/qr_reader/view.cljs
  src/status_im/contexts/wallet/connected_dapps/view.cljs
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/header/view.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/style.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/view.cljs
  src/status_im/contexts/wallet/wallet_connect/utils.cljs
  src/status_im/subs/root.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
Labels: Tested - OK, request-manual-qa

#20810 e2e: disabled activity verification in wallet tests
  test/appium/tests/critical/test_wallet.py
Labels: tests

#20792 fix: button width
  src/quo/components/drawers/bottom_actions/style.cljs
  src/quo/components/drawers/bottom_actions/view.cljs
Labels: skip-manual-qa

#20318 Wallet/Swap Input Component
  src/quo/components/avatars/token_avatar/view.cljs
  src/quo/components/wallet/swap_input/component_spec.cljs
  src/quo/components/wallet/swap_input/style.cljs
  src/quo/components/wallet/swap_input/view.cljs
  src/quo/core.cljs
  src/quo/core_spec.cljs
  src/status_im/contexts/preview/quo/main.cljs
  src/status_im/contexts/preview/quo/wallet/swap_input.cljs
Labels: followup required, skip-manual-qa

#20755 Wallet Connect transactions
  src/quo/components/settings/data_item/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/common/utils/networks.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/fees_data_item/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/send_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_message/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/processing_events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/rpc.cljs
  src/status_im/contexts/wallet/wallet_connect/transactions.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
  src/utils/money.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases required

#20756 Do not update disabled networks when receiver network updated
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/events_test.cljs
Labels: Tested - OK, request-manual-qa

#20785 chore(style): Sort JSON keys in translations/en.json
  .prettierignore
  .prettierrc.js
  Makefile
  package.json
  translations/en.json
  yarn.lock
Labels: E:Mobile Developer XP, skip-manual-qa

#20813 fix: assets sort order on bridge and assets screen
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: skip-manual-qa

#20815 Only show the Wallet Connect requests for the logged in user
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
Labels: Tested - OK, request-manual-qa

#20817 WC: Proper handling of disconnection, both from the dapp itself and from the list of connected dapps
  src/react_native/wallet_connect.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/connected_dapps/view.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
Labels: Tested - OK, request-manual-qa

#20838 fix Missing 'Mark as read' option on community channels
  src/status_im/contexts/communities/actions/chat/view.cljs
Labels: Tested - OK, request-manual-qa

#20837 fix UI elements are misplaced on the 'Sign in by syncing' screen when adding a new profile
  src/status_im/contexts/syncing/scan_sync_code/view.cljs
Labels: Tested - OK, request-manual-qa

#20811 🦁 Fix issues with missing dapp images and dapp names
  src/quo/components/list_items/dapp/style.cljs
  src/quo/components/list_items/dapp/view.cljs
  src/status_im/contexts/preview/quo/list_items/dapp.cljs
  src/status_im/contexts/wallet/connected_dapps/view.cljs
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/header/view.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/style.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/view.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
  src/status_im/subs/wallet/wallet_connect_test.cljs
  src/utils/string.cljs
  src/utils/string_test.cljs
Labels: Tested - OK, request-manual-qa

#20761 Watch-only collectibles should not be included on the main wallet page by default #20735
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/common/collectibles_tab/view.cljs
  src/status_im/contexts/wallet/home/tabs/view.cljs
  src/status_im/subs/wallet/collectibles.cljs
Labels: Tested - OK, request-manual-qa

#20725 fix onboarding navigation to enable notification screen and blur issues
  src/status_im/contexts/onboarding/enable_notifications/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/navigation/roots.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#20818 Remove dApps tab from Wallet
  src/status_im/contexts/wallet/account/tabs/dapps/style.cljs
  src/status_im/contexts/wallet/account/tabs/dapps/view.cljs
  src/status_im/contexts/wallet/account/tabs/view.cljs
  src/status_im/contexts/wallet/account/view.cljs
Labels: Tested - OK, request-manual-qa

#20773 [#20479] - Skip "From" page on wallet home
  src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/home/tabs/assets/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/from/view.cljs
  src/status_im/contexts/wallet/send/select_address/view.cljs
  src/status_im/contexts/wallet/sheets/select_account/view.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/view.cljs
  src/status_im/subs/community/account_selection.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/status_im/subs/wallet/wallet_test.cljs
Labels: Tested - OK, request-manual-qa

#20691 chore(docs): Document some of our existing testing practices
  doc/README.md
  doc/pipeline_process.md
  doc/tests/component-tests-overview.md
  doc/tests/how-to-launch-e2e.md
  doc/tests/how-to-run-local-tests.md
  doc/tests/tests-overview.md
Labels: E: Mobile Documentation, skip-manual-qa, mobile-core

#20827 chore(tests): Allow test-watch-for-repl target to run while the app is running
  Makefile
Labels: E:Mobile Developer XP, skip-manual-qa

#20604 fix(wallet): adjust max amount to not include network being bridged to
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/status_im/subs/wallet/send.cljs
Labels: Tested - OK, request-manual-qa

#20821 Reject typeddata request when wrong chainId inside typed data
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/page_nav/view.cljs
  src/status_im/contexts/wallet/wallet_connect/processing_events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/signing.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#20864 Fix WalletConnect declining proposal error
  src/react_native/wallet_connect.cljs
Labels: Tested - OK

#20839 fix_: Adding own wallet address as saved addresses
  src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs
  src/status_im/contexts/settings/wallet/saved_addresses/save_address/view.cljs
Labels: Tested - OK, request-manual-qa

#20825 chore(tests): New match-strict? cljs.test directive
  .clj-kondo/config.edn
  nix/deps/clojure/deps.json
  nix/deps/clojure/deps.list
  shadow-cljs.edn
  src/status_im/contexts/wallet/data_store_test.cljs
  src/test_helpers/matchers.clj
  src/test_helpers/matchers.cljs
  src/test_helpers/unit.cljs
Labels: E:Mobile Developer XP

#20826 WalletConnect no internet edge-cases
  src/legacy/status_im/events.cljs
  src/legacy/status_im/network/net_info.cljs
  src/legacy/status_im/subs/root.cljs
  src/legacy/status_im/utils/logging/core.cljs
  src/mocks/js_dependencies.cljs
  src/react_native/wallet_connect.cljs
  src/status_im/contexts/networks/events.cljs
  src/status_im/contexts/wallet/wallet_connect/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/send_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_transaction/view.cljs
  src/status_im/events.cljs
  src/status_im/subs/general.cljs
  src/status_im/subs/root.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#20860 Fix WalletConnect header alignment on Android
  src/quo/components/tags/summary_tag/style.cljs
  src/quo/components/tags/summary_tag/view.cljs
  src/quo/components/text_combinations/standard_title/style.cljs
  src/quo/components/text_combinations/standard_title/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/header/style.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/header/view.cljs
Labels: Tested - OK, request-manual-qa

#20867 fix Issue with scrolling WalletConnect transaction on Android
  src/status_im/common/raw_data_block/view.cljs
Labels: Tested - OK, request-manual-qa

#20857 WalletConnect show expired toast
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#20836 Reject wallet-connect request by dragging the modal down (#20763)
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/page_nav/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/send_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_message/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_transaction/view.cljs
  src/status_im/contexts/wallet/wallet_connect/processing_events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/contexts/wallet/wallet_connect/session_proposal/view.cljs
Labels: Tested - OK, request-manual-qa

#20886 Fix WalletConnect initialisation after logout
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
Labels: Tested - OK, request-manual-qa

#20873 feat(wallet)_: Add beta info box in activity tab
  src/status_im/contexts/wallet/common/activity_tab/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#20875 chore(settings)_: Remove testnet toggle from old advanced settings
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
Labels: skip-manual-qa

#20854 [#20804] linear gradient exception
  src/quo/components/links/internal_link_card/user/view.cljs
  src/quo/foundations/colors.cljs
  src/react_native/linear_gradient.cljs
  src/status_im/contexts/communities/actions/accounts_selection/events_test.cljs
  src/status_im/contexts/preview/quo/list_items/saved_address.cljs
  src/status_im/contexts/preview/quo/tags/summary_tag.cljs
Labels: Tested - OK, request-manual-qa

#20889 e2e: updated testnet switching and added one test into smoke
  test/appium/support/testrail_report.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/profile_view.py
Labels: tests

#20729 perf: Fix app freeze after login
  src/legacy/status_im/data_store/communities.cljs
  src/legacy/status_im/ui/screens/communities/members.cljs
  src/native_module/core.cljs
  src/status_im/contexts/chat/messenger/messages/link_preview/events.cljs
  src/status_im/contexts/chat/messenger/messages/transport/events.cljs
  src/status_im/contexts/communities/actions/channel_view_details/view.cljs
  src/status_im/contexts/communities/actions/invite_contacts/view.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/communities/home/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/setup/dev.cljs
  src/status_im/setup/oops.cljs
  src/status_im/setup/test_preload.cljs
  src/status_im/subs/communities.cljs
  src/status_im/subs/communities_test.cljs
  src/status_im/subs/contact.cljs
  src/status_im/subs/contact/utils.cljs
  src/status_im/subs/contact_test.cljs
  src/utils/transforms.cljs
  src/utils/transforms_test.cljs
Labels: Tested - OK, E:Mobile Performance MVP

#20868 fix_: crash when requesting to join community
  src/status_im/contexts/communities/actions/accounts_selection/view.cljs
Labels: Tested - OK, request-manual-qa

#20631 feat: wallet router v2
  src/status_im/common/signals/events.cljs
  src/status_im/contexts/wallet/bridge/input_amount/view.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/events_test.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa

#20799 🥅 Filter connected dapps based on testnet mode, reject proposals and requests gracefully
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/connected_dapps/view.cljs
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/responding_events.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
Labels: test cases required, skip-manual-qa

#20887 fix broken screen and navigation when syncing fails
  resources/images/ui2/syncing_devices@2x.png
  resources/images/ui2/syncing_devices@3x.png
  resources/images/ui2/syncing_wrong@2x.png
  resources/images/ui2/syncing_wrong@3x.png
  src/status_im/common/pairing/events.cljs
  src/status_im/common/resources.cljs
  src/status_im/contexts/onboarding/syncing/progress/style.cljs
  src/status_im/contexts/onboarding/syncing/progress/view.cljs
  src/status_im/navigation/options.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, followup required

#20888 [#20524] fix: the missed keypairs are shown in the key pair list screen
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#20845 Ensure keycard account can send transaction after upgrading from v1 to v2
  src/status_im/common/signals/events.cljs
  src/status_im/common/standard_authentication/events.cljs
  src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs
  src/status_im/contexts/keycard/effects.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/login/events.cljs
  src/status_im/contexts/keycard/pin/events.cljs
  src/status_im/contexts/keycard/pin/view.cljs
  src/status_im/contexts/keycard/sign/events.cljs
  src/status_im/contexts/keycard/utils.cljs
  src/status_im/contexts/profile/profiles/view.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa, status-go, test cases required

#20683 android: build split apks
  Makefile
  android/app/build.gradle
  android/gradle.properties
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  nix/mobile/android/build.nix
  scripts/run-android.sh
Labels: skip-manual-qa

#20787 display group chat system message using new ui
  src/quo/components/messages/system_message/style.cljs
  src/quo/components/messages/system_message/view.cljs
  src/status_im/contexts/chat/messenger/messages/content/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
Labels: Tested - OK, request-manual-qa, followup required

#20881 chore(settings): Disable telemetry option behind feature flag
  src/legacy/status_im/ui/screens/advanced_settings/views.cljs
  src/status_im/feature_flags.cljs
Labels: skip-manual-qa

#20862 Wallet Activity: transactions are not sorted by time #20808
  src/status_im/subs/wallet/activities.cljs
  src/status_im/subs/wallet/activities_test.cljs
Labels: request-manual-qa

#20645 fix: create password for small screen
  src/react_native/hooks.cljs
  src/status_im/common/floating_button_page/floating_container/style.cljs
  src/status_im/common/floating_button_page/floating_container/view.cljs
  src/status_im/common/floating_button_page/style.cljs
  src/status_im/common/floating_button_page/view.cljs
  src/status_im/contexts/onboarding/create_password/style.cljs
  src/status_im/contexts/onboarding/create_password/view.cljs
Labels: Tested - OK, request-manual-qa

#20730 Add toggle in advanced settings for mobile data
  .env.e2e
  src/legacy/status_im/events.cljs
  src/legacy/status_im/mailserver/core.cljs
  src/legacy/status_im/mobile_sync_settings/core.cljs
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/legacy/status_im/ui/screens/mobile_network_settings/sheets.cljs
  src/legacy/status_im/ui/screens/mobile_network_settings/sheets_styles.cljs
  src/legacy/status_im/ui/screens/mobile_network_settings/style.cljs
  src/legacy/status_im/ui/screens/mobile_network_settings/view.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/quo/components/drawers/drawer_action/style.cljs
  src/react_native/net_info.cljs
  src/status_im/common/data_confirmation_sheet/style.cljs
  src/status_im/common/data_confirmation_sheet/view.cljs
  src/status_im/common/signals/events.cljs
  src/status_im/config.cljs
  src/status_im/contexts/communities/events.cljs
  src/status_im/contexts/communities/events_test.cljs
  src/status_im/contexts/network/effects.cljs
  src/status_im/contexts/network/events.cljs
  src/status_im/contexts/networks/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/profile/settings/screens/syncing/view.cljs
  src/status_im/contexts/syncing/syncing_devices_list/view.cljs
  src/status_im/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/pairing.cljs
  src/status_im/subs/profile.cljs
  src/utils/navigation.cljs
  src/utils/network/core.cljs
  src/utils/network/core_test.cljs
  status-go-version.json
  translations/en.json
Labels: request-manual-qa, followup required, test cases required

#20846 chore: disable non selectable bridge assets
  src/quo/components/list_items/token_network/schema.cljs
  src/quo/components/list_items/token_network/style.cljs
  src/quo/components/list_items/token_network/view.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/test_helpers/unit.cljs
Labels: Tested - OK

#20901 feat(wallet): disable complex routing
  src/status_im/contexts/wallet/send/events.cljs
Labels: Tested - OK, request-manual-qa

#20874 Edit button appears below TO section on bridge screen when entering Invalid amount #20809
  src/status_im/contexts/wallet/send/events.cljs
Labels: Tested - OK, request-manual-qa

#20906 Enabling WalletConnect feature flag
  .env
  .env.e2e
  .env.jenkins
  .env.nightly
  .env.release
  src/legacy/status_im/multiaccounts/logout/core.cljs
  src/status_im/contexts/network/events.cljs
  src/status_im/contexts/wallet/wallet_connect/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events.cljs
  src/status_im/contexts/wallet/wallet_connect/processing_events.cljs
  src/status_im/subs/wallet/wallet_connect.cljs
Labels: request-manual-qa

#20721 Cover wallet send events with tests Part 2 #20411 #20533
  src/status_im/contexts/wallet/send/events_test.cljs
Labels: skip-manual-qa

#20902 fix(wallet): fix bridge transactions
  src/native_module/core.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa

#20916 fix_: use usd as default currency
  src/status_im/subs/profile.cljs
Labels: Tested - OK, request-manual-qa

#20921 feat_: add fallback pairing support
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#20924 fix(android): Send and Bridge ERC-20 tokens
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/EncryptionUtils.java
Labels: Tested - OK, request-manual-qa

#20937 e2e: fixes for wallet, community urls and more
  test/appium/support/api/network_api.py
  test/appium/tests/critical/test_deep_and_universal_links.py
  test/appium/tests/critical/test_wallet.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/wallet_view.py
Labels: tests

#20893 fix(wallet): inverted values of receiver and sender when displaying bridging routes
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/send/utils_test.cljs
  src/status_im/subs/wallet/networks.cljs
Labels: Tested - OK, request-manual-qa

#20891 chore: bump react-native-camera-link version to Status fork to remove usage of ML Kit
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  package.json
  yarn.lock
Labels: Tested - OK, request-manual-qa

#20929 [#20914] Fix error while bridging tokens
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/send/events.cljs
Labels: Tested - OK, request-manual-qa
