Repository status-im/status-mobile, pull requests merged in 2024-10, with the labels that each got.

#21333 Dapps Typed Data request improvements
  src/status_im/contexts/wallet/wallet_connect/events/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_requests.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/style.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/sign_message/view.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/signing.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/typed_data.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/typed_data_test.cljs
  src/status_im/subs/wallet/dapps/requests.cljs
Labels: Tested - OK, request-manual-qa

#21350 Fix WalletConnect sessions disappearing
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/wallet_connect/events/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs
  src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs
  src/status_im/contexts/wallet/wallet_connect/events/sessions_test.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/rpc.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/sessions.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21363 feat(swap): remove feature flag
  src/status_im/contexts/wallet/account/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/feature_flags.cljs
Labels: Tested - OK, request-manual-qa

#21313 [#21227] Simpler chat screen
  src/js/worklets/chat/messenger/navigation.js
  src/js/worklets/chat/messenger/placeholder.js
  src/status_im/contexts/chat/messenger/composer/mentions/view.cljs
  src/status_im/contexts/chat/messenger/composer/view.cljs
  src/status_im/contexts/chat/messenger/messages/constants.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/style.cljs
  src/status_im/contexts/chat/messenger/messages/navigation/view.cljs
  src/status_im/contexts/chat/messenger/messages/pin/banner/style.cljs
  src/status_im/contexts/chat/messenger/messages/pin/banner/view.cljs
  src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/view.cljs
  src/status_im/contexts/chat/messenger/messages/view.cljs
  src/status_im/contexts/chat/messenger/placeholder/style.cljs
  src/status_im/contexts/chat/messenger/placeholder/view.cljs
  src/utils/worklets/chat/messenger/messages.cljs
  src/utils/worklets/chat/messenger/navigation.cljs
  src/utils/worklets/chat/messenger/placeholder.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#21338 fix(communities): token-gated community info text
  src/status_im/contexts/communities/overview/view.cljs
  translations/en.json
Labels: skip-manual-qa

#21314 Add syncing notification to System Tab
  src/status_im/contexts/shell/activity_center/notification_types.cljs
Labels: Tested - OK, request-manual-qa

#21373 chore: remove run-tests from wallet-send event tests
  src/status_im/contexts/wallet/send/events_test.cljs
Labels: skip-manual-qa

#21377 e2e: fixes for edit/delete message in tests
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
Labels: tests

#21390 nix: add preBuild phase for generating files
  nix/status-go/library/default.nix
  nix/status-go/mobile/build.nix
  status-go-version.json
Labels: android, Tested - OK, request-manual-qa, nix

#21356 Account selection drawer with balance tag (#20334)
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/sheets/select_account/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#21359 [#21318] Keycard - Allow user to initiate Profile key pair migration …
  resources/images/ui2/check-your-keycard.png
  src/quo/components/info/information_box/view.cljs
  src/quo/components/markdown/list/style.cljs
  src/status_im/common/resources.cljs
  src/status_im/contexts/keycard/check/view.cljs
  src/status_im/contexts/keycard/effects.cljs
  src/status_im/contexts/keycard/empty/view.cljs
  src/status_im/contexts/keycard/error/view.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/login/events.cljs
  src/status_im/contexts/keycard/nfc_sheet/events.cljs
  src/status_im/contexts/keycard/nfc_sheet/view.cljs
  src/status_im/contexts/keycard/not_keycard/view.cljs
  src/status_im/contexts/keycard/sheets/migrate/view.cljs
  src/status_im/contexts/keycard/sign/events.cljs
  src/status_im/contexts/keycard/utils.cljs
  src/status_im/contexts/profile/profiles/view.cljs
  src/status_im/contexts/profile/settings/list_items.cljs
  src/status_im/contexts/settings/keycard/view.cljs
  src/status_im/feature_flags.cljs
  src/status_im/navigation/options.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/navigation/view.cljs
  src/status_im/subs/keycard.cljs
  src/status_im/subs/profile.cljs
  translations/en.json
Labels: skip-manual-qa, keycard

#21374 nix: use multiple nixpkgs sources
  nix/overlay.nix
  nix/pkgs.nix
Labels: Tested - OK, request-manual-qa

#20962 fix(wallet): fix mercuryo on-ramp
  src/quo/components/list_items/network_list/view.cljs
  src/status_im/contexts/wallet/buy_crypto/events.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/sheets/buy_network_selection/style.cljs
  src/status_im/contexts/wallet/sheets/buy_network_selection/view.cljs
  src/status_im/contexts/wallet/sheets/buy_token/view.cljs
  src/status_im/contexts/wallet/sheets/select_asset/view.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/tokens/data.cljs
  src/status_im/contexts/wallet/tokens/events_test.cljs
  src/status_im/events.cljs
  src/status_im/subs/wallet/buy.cljs
  src/status_im/subs/wallet/wallet.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, test cases added, wallet-core

#21376 e2e: added tests for fallback flow
  test/appium/support/testrail_report.py
  test/appium/tests/critical/test_fallback.py
  test/appium/views/base_view.py
  test/appium/views/home_view.py
  test/appium/views/profile_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#21395 fix(swap): update max value when the account is switched
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21370 [#20513] Fix last mesage overlapped with "join community" button
  src/status_im/contexts/chat/messenger/messages/contact_requests/bottom_drawer/view.cljs
  src/status_im/contexts/chat/messenger/messages/list/style.cljs
  src/status_im/contexts/chat/messenger/messages/list/view.cljs
Labels: Tested - OK, request-manual-qa

#21381 [#21354] Exception when navigating back from route generation
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/send/send_amount/view.cljs
  src/utils/money.cljs
Labels: Tested - OK, request-manual-qa

#21388 fix(swap): display very small numbers max values, fix scientific notation, display long number & handle decimal mismatch
  src/quo/components/wallet/swap_input/style.cljs
  src/quo/components/wallet/swap_input/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/utils/number.cljs
  src/utils/number_test.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21372 A black square background at the end of Swap confirmation screen
  src/status_im/contexts/wallet/swap/set_spending_cap/style.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
Labels: Tested - OK, request-manual-qa

#21402 Fixed bug with fiat value displayed as 0 for some tokens in receive field on Swap Page
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#21416 nix: fix sha256 of nixpkgs release 24-05
  nix/pkgs.nix
Labels: Tested - OK, request-manual-qa

#21422 [#21420] Keycard - Auth with password
  src/status_im/contexts/keycard/authorise/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: skip-manual-qa, keycard

#21413 Feature/keycard create pin #21368
  src/status_im/contexts/keycard/pin/create/view.cljs
  translations/en.json
Labels: skip-manual-qa, keycard

#21404 chore : rename crypto phrases, buy Eth and buy assets
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/contexts/wallet/sheets/buy_token/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21408 Keycard - Allow user to migrate existing Profile [Part 2]
  src/status_im/common/enter_seed_phrase/view.cljs
  src/status_im/contexts/keycard/events.cljs
  src/status_im/contexts/keycard/sheets/migrate/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/profile/backup_recovery_phrase/style.cljs
  src/status_im/contexts/profile/backup_recovery_phrase/view.cljs
  src/status_im/contexts/profile/recover/effects.cljs
  src/status_im/contexts/profile/recover/events.cljs
  src/status_im/contexts/profile/settings/view.cljs
  src/status_im/contexts/settings/wallet/events.cljs
  src/status_im/contexts/settings/wallet/events_test.cljs
  src/status_im/contexts/wallet/add_account/create_account/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/contexts/wallet/effects.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/profile.cljs
Labels: Tested - OK, request-manual-qa, keycard

#21379 [#21335] feat: add dApp analytics
  src/status_im/contexts/centralized_metrics/events.cljs
  src/status_im/contexts/centralized_metrics/tracking.cljs
  src/status_im/contexts/centralized_metrics/tracking_test.cljs
  src/status_im/contexts/wallet/wallet_connect/events/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs
  src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/data_store.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/data_store_test.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#21435 Fix error when confirming Swap
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
Labels: Tested - OK, request-manual-qa

#21440 e2e: new wallet test
  test/appium/tests/critical/test_wallet.py
  test/appium/views/profile_view.py
  test/appium/views/wallet_view.py
Labels: tests

#21447 e2e: fix error in reporting
  test/appium/tests/critical/test_wallet.py
Labels: tests

#21410 fix(swap): update icon and don't show contract address for eth on confirmation screen
  resources/images/icons2/20x20/transaction@2x.png
  resources/images/icons2/20x20/transaction@3x.png
  src/quo/components/buttons/wallet_ctas/view.cljs
  src/quo/components/wallet/summary_info/view.cljs
  src/quo/components/wallet/transaction_summary/view.cljs
  src/quo/components/wallet/wallet_activity/view.cljs
  src/status_im/contexts/preview/status_im/common/floating_button_page/view.cljs
  src/status_im/contexts/wallet/common/token_value/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/utils/address.cljs
Labels: Tested - OK, request-manual-qa

#21425 [#20562] fix "not enough assets" case in send screen
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/input_amount/component_spec.cljs
  src/status_im/contexts/wallet/send/input_amount/view.cljs
  src/status_im/subs/wallet/wallet.cljs
  src/utils/money.cljs
Labels: Tested - OK, request-manual-qa

#21448 [#20593] fix: show name of saved address in sending flow
  src/status_im/contexts/settings/wallet/saved_addresses/sheets/address_options/view.cljs
Labels: Tested - OK, request-manual-qa

#21437 feat(wallet)_: Add PDF viewer screen to view ParaSwap TnC
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
  ios/Podfile.lock
  nix/deps/gradle/deps.json
  nix/deps/gradle/deps.list
  nix/deps/gradle/deps.urls
  nix/deps/gradle/proj.list
  package.json
  src/mocks/js_dependencies.cljs
  src/react_native/pdf_viewer.cljs
  src/status_im/common/pdf_viewer/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/status_im/navigation/screens.cljs
  yarn.lock
Labels: Tested - OK, request-manual-qa

#21442 fix(swap): round values for very small values in fiat and crypto
  src/quo/components/wallet/approval_label/component_spec.cljs
  src/quo/components/wallet/approval_label/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/contexts/wallet/sheets/slippage_settings/view.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
  src/status_im/subs/wallet/swap.cljs
  src/utils/number.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21469 fix public chat deletion and name display issues post-migration
  src/status_im/common/confirmation_drawer/view.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/home/chat_list_item/view.cljs
  src/status_im/contexts/chat/messenger/messages/contact_requests/bottom_drawer/view.cljs
  src/status_im/subs/chats.cljs
Labels: Tested - OK, request-manual-qa, test cases required

#21453 fix(wallet): client should pass a list with "Symbol" and without "ChainID-" to status-go
  src/status_im/constants.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/tokens/events.cljs
Labels: Tested - OK, request-manual-qa

#21474 fix(wallet)_: Activity tab is selected on navigating back from the swap flow
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
Labels: Tested - OK, request-manual-qa

#21280 Added metrics for collectibles
  src/status_im/contexts/centralized_metrics/events.cljs
  src/status_im/contexts/centralized_metrics/events_test.cljs
  src/status_im/contexts/centralized_metrics/tracking.cljs
  src/status_im/contexts/centralized_metrics/tracking_test.cljs
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/db.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/home/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, analytics

#21486 chore(ci)_: bump universal apk size limit to 125MB
  ci/Jenkinsfile.android
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.e2e-nightly
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  ci/tests/Jenkinsfile.e2e-upgrade
  ci/tools/Jenkinsfile.fastlane-clean
  ci/tools/Jenkinsfile.nix-cache
  ci/tools/Jenkinsfile.playstore-meta
  ci/tools/Jenkinsfile.xcode-clean
Labels: skip-manual-qa

#21487 feat(onboarding): Present Terms to users upgrading from v1 or those who need to accept updated Terms
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/AccountManager.kt
  modules/react-native-status/ios/RCTStatus/AccountManager.m
  modules/react-native-status/nodejs/status.cpp
  src/native_module/core.cljs
  src/status_im/contexts/onboarding/intro/view.cljs
  src/status_im/contexts/profile/data_store.cljs
  src/status_im/contexts/profile/effects.cljs
  src/status_im/contexts/profile/events.cljs
  src/status_im/subs/profile.cljs
  src/tests/test_utils.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21328 chore: refactor screens definitions and add more navigation events for screens
  shadow-cljs.edn
  src/status_im/contexts/centralized_metrics/events.cljs
  src/status_im/contexts/centralized_metrics/tracking.cljs
  src/status_im/contexts/centralized_metrics/tracking_test.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/setup/interceptor_metrics.cljc
  src/status_im/setup/interceptors.cljs
Labels: Tested - OK, mobile-core, analytics

#21451 fix(wallet)_: token supported networks
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/events_test.cljs
  src/status_im/contexts/wallet/send/routes/view.cljs
  src/status_im/contexts/wallet/swap/utils.cljs
  src/status_im/contexts/wallet/tokens/events.cljs
  src/status_im/contexts/wallet/tokens/events_test.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#21498 fix(wallet-settings)_: Icon color in missing keypair section
  src/quo/components/list_items/missing_keypair/view.cljs
Labels: skip-manual-qa

#21496 fix Error when creating an account on e2e build
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/profile/login/events.cljs
Labels: Tested - OK, request-manual-qa

#21520 fix No tabs are available in the app on Graphene OS
  src/status_im/contexts/onboarding/common/background/view.cljs
Labels: Tested - OK

#21485 feat(swap): add metrics for swaps
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs
  src/status_im/contexts/wallet/swap/setup_swap/view.cljs
  src/status_im/subs/wallet/swap.cljs
Labels: Tested - OK, request-manual-qa
