Repository status-im/status-mobile, pull requests merged in 2025-01, with the labels that each got.

#21872 fix_: add token and selected network on "Select network to receive" screen
  src/status_im/contexts/wallet/bridge/bridge_to/style.cljs
  src/status_im/contexts/wallet/bridge/bridge_to/view.cljs
  src/status_im/contexts/wallet/events.cljs
Labels: Tested - OK, request-manual-qa

#21871 fix(wallet)_: Send flow for collectibles
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/collectible/view.cljs
  src/status_im/contexts/wallet/data_store.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/events_test.cljs
  src/status_im/contexts/wallet/send/from/view.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa

#21877 android: kotlinify root util
  android/app/src/main/java/im/status/ethereum/RootUtil.java
  android/app/src/main/java/im/status/ethereum/RootUtil.kt
Labels: Tested - OK, request-manual-qa

#21879 android: kotlinify ui helper
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/UIHelper.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/UIHelper.kt
Labels: Tested - OK, request-manual-qa

#21878 android: kotlinify encryption utils
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/EncryptionUtils.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/module/EncryptionUtils.kt
Labels: Tested - OK, request-manual-qa

#21880 e2e: cleanup base_test_case and conftest
  ci/tests/Jenkinsfile.e2e-nightly
  ci/tests/Jenkinsfile.e2e-prs
  test/appium/README.md
  test/appium/pytest.ini
  test/appium/support/api/network_api.py
  test/appium/support/api/third_parties_api.py
  test/appium/support/api/web3_api.py
  test/appium/support/appium_container.py
  test/appium/support/device_apps.py
  test/appium/support/device_stats_db.py
  test/appium/support/message_reliability_report.py
  test/appium/support/test_rerun.py
  test/appium/support/utilities.py
  test/appium/tests/__init__.py
  test/appium/tests/activity_center/test_activity_center.py
  test/appium/tests/base_test_case.py
  test/appium/tests/conftest.py
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_fallback.py
  test/appium/tests/critical/test_wallet.py
  test/appium/tests/marks.py
  test/appium/tests/non_func/test_api.py
  test/appium/tests/non_func/test_chatbot.py
  test/appium/tests/non_func/test_performance.py
  test/appium/views/base_element.py
  test/appium/views/base_view.py
  test/appium/views/chat_view.py
  test/appium/views/home_view.py
  test/appium/views/send_transaction_view.py
  test/appium/views/sign_in_view.py
  test/appium/views/web_views/base_web_view.py
Labels: tests

#21886 e2e: requirements cleanup
  test/appium/requirements.txt
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_fallback.py
  test/appium/tests/critical/test_wallet.py
  test/appium/views/elements_templates/images_gallery_inverted.png
  test/appium/views/home_view.py
Labels: tests

#21881 Kotlinify push notifications module
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/ForegroundService.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/ForegroundService.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotification.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotification.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationActions.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationActions.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationJsDelivery.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationJsDelivery.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationPackage.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationPackage.kt
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationPicturesAggregator.java
  modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationPicturesAggregator.kt
  modules/react-native-status/android/src/test/java/im/status/ethereum/pushnotifications/PushNotificationHelperTest.java
  modules/react-native-status/android/src/test/java/im/status/ethereum/pushnotifications/PushNotificationHelperTest.kt
Labels: Tested - OK, request-manual-qa

#21883 fix(wallet)_: collectible route cleanup on navigating back from TX confirmation page
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa

#21884 Fix syncing flow navigation and designs
  src/status_im/contexts/onboarding/intro/view.cljs
  src/status_im/contexts/onboarding/syncing/progress/style.cljs
  src/status_im/contexts/onboarding/syncing/progress/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  translations/en.json
  translations/ja.json
Labels: Tested - OK, request-manual-qa

#21889 [#21825] [Android] Java error at the and of faild Migration to a Keyc…
  package.json
  yarn.lock
Labels: Tested - OK, request-manual-qa, keycard

#21892 Fixed error on opening Advanced settings
  src/legacy/status_im/events.cljs
  src/status_im/subs/profile.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21782 [#21658] - Avatars blinking
  src/react_native/fast_image.cljs
  src/react_native/flat_list.cljs
  src/status_im/common/scalable_avatar/style.cljs
  src/status_im/common/scalable_avatar/view.cljs
  src/status_im/common/standard_authentication/forgot_password_doc/view.cljs
  src/status_im/contexts/chat/home/chat_list_item/view.cljs
  src/status_im/contexts/chat/home/view.cljs
  src/status_im/contexts/profile/settings/header/header_shape.cljs
  src/status_im/contexts/profile/settings/header/style.cljs
  src/status_im/contexts/profile/settings/header/view.cljs
  src/status_im/contexts/profile/settings/view.cljs
Labels: Tested - OK, request-manual-qa

#21890 On-boarding: re add bio-metric screen to syncing flow
  src/status_im/contexts/centralized_metrics/tracking.cljs
  src/status_im/contexts/onboarding/enable_biometrics/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  src/status_im/contexts/onboarding/syncing/progress/view.cljs
  src/status_im/contexts/onboarding/syncing/results/style.cljs
  src/status_im/contexts/onboarding/syncing/results/view.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/navigation/roots.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#21893 [#21652] The main part of a backup flow is missing at Keycard migrati…
  src/status_im/contexts/keycard/create/events.cljs
  src/status_im/contexts/keycard/migrate/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/events_test.cljs
  src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
  src/status_im/navigation/screens.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, followup-required, keycard

#21907 e2e: fix for requirements and getting username
  test/appium/requirements.txt
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/tests/critical/chats/test_group_chat.py
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/tests/critical/test_fallback.py
  test/appium/views/base_element.py
  test/appium/views/home_view.py
  test/appium/views/sign_in_view.py
Labels: tests

#21913 e2e: additional fix for requirements
  test/appium/requirements.txt
Labels: tests

#21830 fix: use image clock when updating profile images to cause re-render
  src/status_im/contexts/profile/edit/header/events.cljs
  src/status_im/contexts/profile/settings/events.cljs
  src/status_im/subs/profile.cljs
Labels: mobile-core

#21921 [#21915] Wrong address generated after creation a new keypair
  src/status_im/contexts/keycard/create/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/events.cljs
  src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs
Labels: Tested - OK, request-manual-qa, blocker

#21547 Upgrade nix interpreter from 2.19.3 to 2.24.11
  Makefile
  ci/Jenkinsfile.android
  ci/Jenkinsfile.ios
  ci/Jenkinsfile.tests
  nix/scripts/lib.sh
  nix/scripts/version.sh
  nix/shell.nix
Labels: Tested - OK, skip-manual-qa

#21874 chore: resolve deprecation warnings related to `custom-color` and `touchable-without-feeback`
  src/legacy/status_im/ui/components/button/view.cljs
  src/quo/components/avatars/group_avatar/style.cljs
  src/quo/components/avatars/wallet_user_avatar/style.cljs
  src/quo/components/banners/banner/style.cljs
  src/quo/components/banners/banner/view.cljs
  src/quo/components/browser/browser_input/view.cljs
  src/quo/components/buttons/button/view.cljs
  src/quo/components/buttons/dynamic_button/view.cljs
  src/quo/components/buttons/slide_button/style.cljs
  src/quo/components/buttons/slide_button/utils.cljs
  src/quo/components/buttons/slide_button/view.cljs
  src/quo/components/colors/color/view.cljs
  src/quo/components/common/notification_dot/style.cljs
  src/quo/components/community/banner/view.cljs
  src/quo/components/community/community_card_view.cljs
  src/quo/components/counter/counter/style.cljs
  src/quo/components/counter/step/style.cljs
  src/quo/components/dividers/strength_divider/view.cljs
  src/quo/components/dropdowns/dropdown/properties.cljs
  src/quo/components/graph/interactive_graph/view.cljs
  src/quo/components/graph/wallet_graph/view.cljs
  src/quo/components/inputs/address_input/view.cljs
  src/quo/components/inputs/input/style.cljs
  src/quo/components/inputs/profile_input/style.cljs
  src/quo/components/inputs/recovery_phrase/style.cljs
  src/quo/components/inputs/title_input/style.cljs
  src/quo/components/list_items/address/component_spec.cljs
  src/quo/components/list_items/address/style.cljs
  src/quo/components/list_items/dapp/style.cljs
  src/quo/components/list_items/saved_address/style.cljs
  src/quo/components/list_items/saved_contact_address/component_spec.cljs
  src/quo/components/list_items/saved_contact_address/style.cljs
  src/quo/components/messages/gap.cljs
  src/quo/components/navigation/bottom_nav_tab/styles.cljs
  src/quo/components/navigation/top_nav/view.cljs
  src/quo/components/notifications/activity_log/style.cljs
  src/quo/components/profile/profile_card/style.cljs
  src/quo/components/profile/select_profile/style.cljs
  src/quo/components/selectors/disclaimer/view.cljs
  src/quo/components/selectors/filter/style.cljs
  src/quo/components/selectors/filter/view.cljs
  src/quo/components/settings/privacy_option/view.cljs
  src/quo/components/tabs/tab/view.cljs
  src/quo/components/tags/base_tag.cljs
  src/quo/components/tags/context_tag/style.cljs
  src/quo/components/tags/context_tag/view.cljs
  src/quo/components/tags/network_tags/style.cljs
  src/quo/components/wallet/account_overview/style.cljs
  src/quo/components/wallet/transaction_progress/view.cljs
  src/quo/foundations/colors.cljs
  src/status_im/contexts/preview/quo/graph/interactive_graph.cljs
  src/status_im/contexts/preview/quo/selectors/react.cljs
  src/status_im/contexts/preview/quo/selectors/react_selector.cljs
  src/status_im/contexts/preview/quo/share/qr_code.cljs
  src/status_im/contexts/preview/quo/wallet/network_routing.cljs
Labels: Tested - OK, request-manual-qa

#21899 fix(wallet)_: Send flow from saved address and QR scanner
  src/status_im/contexts/settings/wallet/saved_addresses/sheets/address_options/view.cljs
  src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/from/view.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21885 chore: cleanup events and tests
  src/legacy/status_im/chat/models/message.cljs
  src/legacy/status_im/test_runner.cljs
  src/status_im/common/log.cljs
  src/status_im/contexts/chat/contacts/events.cljs
  src/status_im/contexts/chat/contacts/events_test.cljs
  src/status_im/contexts/chat/events.cljs
  src/status_im/contexts/chat/messenger/messages/contact_requests/bottom_drawer/view.cljs
  src/status_im/contexts/chat/messenger/messages/delete_message/events.cljs
  src/status_im/contexts/chat/messenger/messages/delete_message/events_test.cljs
  src/status_im/contexts/chat/messenger/messages/delete_message_for_me/events.cljs
  src/status_im/contexts/chat/messenger/messages/delete_message_for_me/events_test.cljs
  src/status_im/contexts/shell/activity_center/notification/contact_requests/events.cljs
  src/status_im/contexts/shell/activity_center/notification/contact_requests/events_test.cljs
Labels: Tested - OK, request-manual-qa, mobile-core

#21917 fix Keyboard overlaps suggestion bar and validation errors
  src/status_im/common/enter_seed_phrase/style.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa

#21918 fix "keycard is not empty" screen shown if keycard moved during create profile flow
  src/status_im/contexts/keycard/create/events.cljs
Labels: Tested - OK, request-manual-qa

#21345 feat_: support xcode 16
  ci/Jenkinsfile.ios
  ios/Podfile.lock
  ios/StatusIm.xcodeproj/project.pbxproj
  nix/overlay.nix
  package.json
  yarn.lock
Labels: skip-manual-qa

#21873 [#21853] fix: check deeplink pending request after wallet connect loaded
  src/react_native/wallet_connect.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/profile/logout/events.cljs
  src/status_im/contexts/wallet/wallet_connect/events/core.cljs
  src/status_im/contexts/wallet/wallet_connect/events/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21909 fix(wallet)_: Dismiss collectible details screen after a is TX placed
  src/status_im/contexts/wallet/collectible/events.cljs
  src/status_im/contexts/wallet/events.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21901 fix(mailserver): Show current mailserver in legacy settings
  src/legacy/status_im/mailserver/core.cljs
  src/legacy/status_im/subs/mailservers.cljs
  src/legacy/status_im/subs/root.cljs
  src/legacy/status_im/ui/screens/offline_messaging_settings/styles.cljs
  src/legacy/status_im/ui/screens/offline_messaging_settings/views.cljs
  src/legacy/status_im/ui/screens/screens.cljs
  src/legacy/status_im/ui/screens/sync_settings/views.cljs
  src/status_im/common/signals/events.cljs
  src/status_im/contexts/profile/login/events.cljs
  src/status_im/db.cljs
Labels: Tested - OK, request-manual-qa

#21931 chore: update status-go with identity images fixes
  src/status_im/contexts/profile/edit/header/events.cljs
  src/status_im/contexts/profile/settings/events.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go, mobile-core

#21805 chore: add support for remote devices with re-frisk server
  Makefile
  shadow-cljs.edn
  src/dev/re_frisk_preload.cljs
  src/status_im/config.cljs
Labels: Tested - OK, skip-manual-qa, mobile-core

#21953 e2e: fix for test_community_mentions_push_notification
  test/appium/tests/critical/chats/test_public_chat_browsing.py
  test/appium/views/home_view.py
Labels: tests

#21838 Screens for editing transaction settings
  src/quo/components/inputs/input/style.cljs
  src/quo/components/inputs/input/view.cljs
  src/quo/components/tags/network_tags/style.cljs
  src/quo/components/tags/network_tags/view.cljs
  src/quo/components/wallet/token_input/schema.cljs
  src/quo/components/wallet/token_input/style.cljs
  src/quo/components/wallet/token_input/view.cljs
  src/status_im/common/controlled_input/utils.cljs
  src/status_im/contexts/preview/quo/tags/network_tags.cljs
  src/status_im/contexts/preview/quo/wallet/token_input.cljs
  src/status_im/contexts/wallet/send/events.cljs
  src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
  src/status_im/contexts/wallet/send/transaction_settings/gas_amount/view.cljs
  src/status_im/contexts/wallet/send/transaction_settings/max_fee/view.cljs
  src/status_im/contexts/wallet/send/transaction_settings/nonce/view.cljs
  src/status_im/contexts/wallet/send/transaction_settings/priority_fee/view.cljs
  src/status_im/contexts/wallet/send/transaction_settings/view.cljs
  src/status_im/navigation/events.cljs
  src/status_im/navigation/screens.cljs
  src/status_im/subs/wallet/send.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa, wallet-core

#21938 fix keycard sign up ui issues
  resources/images/ui2/add-key-to-keycard@2x.png
  resources/images/ui2/add-key-to-keycard@3x.png
  resources/images/ui2/generating-keys-1@2x.png
  resources/images/ui2/generating-keys-1@3x.png
  src/quo/components/onboarding/small_option_card/view.cljs
  src/status_im/common/resources.cljs
  src/status_im/contexts/keycard/create/view.cljs
  src/status_im/contexts/keycard/empty/view.cljs
  src/status_im/navigation/screens.cljs
Labels: Tested - OK, request-manual-qa, keycard

#21908 [#21305] fix: sort assets by value and collectibles by name
  src/status_im/contexts/wallet/collectible/utils.cljs
  src/status_im/contexts/wallet/collectible/utils_test.cljs
  src/status_im/contexts/wallet/common/asset_list/view.cljs
  src/status_im/contexts/wallet/common/utils.cljs
  src/status_im/contexts/wallet/common/utils_test.cljs
  src/status_im/subs/wallet/collectibles.cljs
  src/status_im/subs/wallet/wallet.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#21876 feat: integrate base chain
  resources/images/networks/Base@2x.png
  resources/images/networks/Base@3x.png
  scripts/build-android.sh
  shadow-cljs.edn
  src/quo/components/wallet/summary_info/view.cljs
  src/quo/foundations/resources.cljs
  src/status_im/config.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/profile/config.cljs
  src/status_im/contexts/settings/wallet/network_settings/view.cljs
  src/status_im/contexts/wallet/common/utils/external_links.cljs
  src/status_im/contexts/wallet/common/utils/networks.cljs
  src/status_im/contexts/wallet/send/utils.cljs
  src/status_im/contexts/wallet/swap/events.cljs
  src/status_im/subs/wallet/wallet_test.cljs
  src/tests/contract_test/wallet_test.cljs
  src/utils/ethereum/chain.cljs
  status-go-version.json
  translations/en.json
Labels: Tested - OK, request-manual-qa, wallet-core

#21945 e2e: added verifications to fallback test
  test/appium/requirements.txt
  test/appium/support/helpers.py
  test/appium/tests/critical/test_fallback.py
  test/appium/views/base_element.py
  test/appium/views/wallet_view.py
Labels: tests

#21966 Backend server doc added to readme
  doc/README.md
Labels: skip-manual-qa

#21968 e2e: fix for saving logs
  test/appium/support/testrail_report.py
Labels: tests

#21972 Fix for local re-frisk launch
  src/status_im/config.cljs
Labels: skip-manual-qa

#21923 [#21919] fix: remove on-ramp provider description and reinstate mecuryo
  src/status_im/contexts/wallet/sheets/buy_token/view.cljs
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go, wallet-core

#21949 fix(chat): Same QR shown code for everyone in the `Contacts` tab
  src/quo/components/list_items/user.cljs
  src/status_im/common/home/actions/view.cljs
  src/status_im/common/universal_links.cljs
  src/status_im/contexts/chat/contacts/events.cljs
  src/status_im/contexts/profile/contact/share/view.cljs
Labels: Tested - OK, request-manual-qa

#21947 Keycard - Import a seed phrase into a new Keycard
  src/quo/components/onboarding/small_option_card/view.cljs
  src/status_im/contexts/keycard/create/events.cljs
  src/status_im/contexts/keycard/empty/view.cljs
  src/status_im/contexts/onboarding/events.cljs
  translations/en.json
Labels: Tested - OK, request-manual-qa

#21946 fix: resolve UI glitches for chat, contacts, and keycard
  src/quo/components/selectors/disclaimer/style.cljs
  src/status_im/contexts/chat/messenger/messages/content/view.cljs
  src/status_im/contexts/profile/contact/add_nickname/view.cljs
Labels: Tested - OK, request-manual-qa, mobile-core

#21973 Fix dapps transactions instantly rejected
  status-go-version.json
Labels: Tested - OK, request-manual-qa, status-go

#21989 nix: add fake git to status-go build derivation
  nix/status-go/mobile/build.nix
Labels: skip-manual-qa

#21785 Keycard signing for dapp interactions
  src/native_module/core.cljs
  src/status_im/constants.cljs
  src/status_im/contexts/keycard/utils.cljs
  src/status_im/contexts/wallet/common/account_switcher/view.cljs
  src/status_im/contexts/wallet/effects.cljs
  src/status_im/contexts/wallet/rpc.cljs
  src/status_im/contexts/wallet/wallet_connect/events/effects.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_requests.cljs
  src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs
  src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/data_store.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/data_store_test.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/signing.cljs
  src/status_im/contexts/wallet/wallet_connect/utils/transactions.cljs
  src/status_im/subs/wallet/dapps/requests.cljs
Labels: Tested - OK, Tested - Issues, blocked, request-manual-qa, test cases required, wallet-core

#21998 e2e: added wallet tests for send and swap flows on mainnet
  test/appium/tests/critical/test_wallet.py
  test/appium/views/base_view.py
  test/appium/views/wallet_view.py
Labels: tests

#21862 [#21571] ask user to update their profile
  src/quo/components/colors/color/style.cljs
  src/quo/components/drawers/bottom_actions/view.cljs
  src/status_im/common/home/banner/view.cljs
  src/status_im/contexts/chat/home/view.cljs
  src/status_im/contexts/profile/contact/header/view.cljs
  src/status_im/contexts/profile/edit/accent_colour/events.cljs
  src/status_im/contexts/profile/edit/accent_colour/events_test.cljs
  src/status_im/contexts/profile/edit/accent_colour/view.cljs
  src/status_im/contexts/profile/edit/header/events.cljs
  src/status_im/contexts/profile/edit/header/events_test.cljs
  src/status_im/contexts/profile/edit/header/view.cljs
  src/status_im/contexts/profile/edit/introduce_yourself/view.cljs
  src/status_im/contexts/profile/edit/modal/events.cljs
  src/status_im/contexts/profile/edit/modal/style.cljs
  src/status_im/contexts/profile/edit/modal/view.cljs
  src/status_im/contexts/profile/edit/name/events.cljs
  src/status_im/contexts/profile/edit/name/events_test.cljs
  src/status_im/contexts/profile/edit/name/view.cljs
  src/status_im/contexts/shell/home_stack/view.cljs
  src/status_im/navigation/screens.cljs
  src/tests/integration_test/profile_test.cljs
  translations/en.json
Labels: Tested - OK, Tested - Issues, request-manual-qa, test cases added

#21982 e2e: updated tests with editing profile when starting chat
  test/appium/tests/critical/chats/test_1_1_public_chats.py
  test/appium/views/home_view.py
Labels: tests

#22001 fix: swap fees are not displayed if route estimated time is nil
  src/status_im/contexts/wallet/swap/set_spending_cap/view.cljs
  src/status_im/contexts/wallet/swap/swap_confirmation/view.cljs
Labels: Tested - OK, request-manual-qa, wallet-core

#22003 e2e: added wallet test for bridge flow
  test/appium/tests/critical/test_wallet.py
  test/appium/views/wallet_view.py
Labels: tests
